### ISSUE TITLE
Activate shell autocompletion

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#10]
`chezmoi` uses [Cobra](https://github.com/spf13/cobra) for command line parsing, which can also generate autocompletion code. We should use this to generate `bash` and `zsh` autocompletion code.

**Comment by kkirsche** [comment]
For anyone interested in working on this, the documentation specific to this task is:

https://github.com/spf13/cobra/blob/master/bash_completions.md

At least for bash

**Comment by twpayne** [comment]
Fixed by @davewongillies in #231.
