### ISSUE TITLE
Can't retrieve secrets from KeePassXC

### ISSUE THREAD

**Issue by sersorrel** [twpayne/chezmoi#1002]
## What exactly are you trying to do?

I'm trying to use the `keepassxc` template function to retrieve data from my password database, but chezmoi crashes when it runs the keepassxc-cli command. Running the same command in a shell successfully shows the data from the database.

## What have you tried so far?

Removing the `keepassxc.args` from my chezmoi config results in the same error.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```console
$ chez execute-template --verbose <<< '{{ keepassxc "EDDB" }}'

chezmoi: template: stdin:1:3: executing "stdin" at <keepassxc "EDDB">: error calling keepassxc: keepassxc.cli show --show-protected --key-file /path/to/keyfile.key '/path/to/db.kdbx' EDDB: EOF
$ keepassxc.cli show --show-protected --key-file /path/to/keyfile.key '/path/to/db.kdbx' EDDB
Enter password to unlock /path/to/db.kdbx:
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'Custom': 'RGB ': RGB color space not permitted on grayscale PNG
Title: EDDB
UserName: Ser Sorrel
Password: ...
URL: https://eddb.io/
Notes:
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
     ok: version 1.8.10, commit 11ed57d9a7e86434744f336b595ed0fd19aff6f5, built at 2020-12-20T12:09:31Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/ash/.local/share/chezmoi (source directory, perm 700)
     ok: /home/ash (destination directory, perm 755)
     ok: /home/ash/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /path/to/db.kdbx (KeePassXC database)
     ok: /usr/local/bin/vim (editor)
     ok: /usr/local/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.30.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.4)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /snap/bin/keepassxc.cli (KeePassXC CLI, version 2.6.3)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Hmm, I'm currently unable to reproduce this problem. Note that chezmoi reports that it's getting an empty response from `keepassxc.cli` (chezmoi doesn't crash).

I used `keepassxc.cli` as installed by `sudo snap install keepassxc` on Ubuntu 20.10, which gives me `keepassxc.cli` 2.6.3, the same as you.

My username is `twp` and my chezmoi config file in `~/.config/chezmoi/chezmoi.toml` contains:

```toml
[keepassxc]
  args = ["--key-file", "/home/twp/keyfile"]
  command = "keepassxc.cli"
  database = "/home/twp/keepassxc-keyfile.db"
```

Using the password `foo` I ran the following:

Create key file:
```
$ echo examplekey > ~/keyfile
```

Create DB:
```
$ keepassxc.cli db-create --set-key-file=$HOME/keyfile --set-password keepassxc-keyfile.db
Enter password to encrypt database (optional): foo
Repeat password: foo
QObject::killTimer: Timers cannot be stopped from another thread
Successfully created new database.
```

Add entry:
```
$ keepassxc.cli add --key-file=$HOME/keyfile --password-prompt ~/keepassxc-keyfile.db exampleentry
Enter password to unlock /home/twp/keepassxc-keyfile.db: foo
Enter password for new entry: examplepassword
Successfully added entry exampleentry.
```

Get entry with KeePassXC CLI:
```
$ echo foo | keepassxc.cli show --key-file=$HOME/keyfile --show-protected ~/keepassxc-keyfile.db exampleentry
Enter password to unlock /home/twp/keepassxc-keyfile.db:
Title: exampleentry
UserName:
Password: examplepassword
URL:
Notes:
```

Get entry with chezmoi:
```
$ chezmoi execute-template '{{ (keepassxc "exampleentry").Password }}'
Insert password to unlock /home/twp/keepassxc-keyfile.db: foo

Enter password to unlock /home/twp/keepassxc-keyfile.db:
examplepassword%
```

Could you provide a similar series of steps that reproduce the problem?

**Comment by sersorrel** [comment]
ahh, I see the problem – if I use `chezmoi execute-template '{{ keepassxc "EDDB" }}'` it works fine, but `chezmoi execute-template <<< '{{ keepassxc "EDDB" }}'` (redirecting stdin) breaks. That seems kind of obvious now I think about it... keepassxc-cli needs to read the database password from stdin, but if it's redirected elsewhere, then it can't.

Not a problem with chezmoi. Sorry for the false alarm!

**Comment by twpayne** [comment]
Ah, that makes sense! Glad we got this solved.

For what it's worth, chezmoi will soon read passwords from the TTY (unless told not to with a `--no-tty` flag) which will allow the reading the template from stdin, even if a password is needed to unlock the database.
