### ISSUE TITLE
Install script for Powershell

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#1006]
## Is your feature request related to a problem? Please describe.

I've put together a Powershell version of the installer script.  What do you think about including it alongside `install.sh`, so Windows (and other platforms with `pwsh` installed) can do a one-line install, too?

## Describe the solution you'd like

  I'd love to be able to
```ps1
(iwr https://git.io/chezmoi.ps1).Content | pwsh -c -
```

## Describe alternatives you've considered

No alternative, really -- just stick with the existing install methods.

**Comment by twpayne** [comment]
Yes please - this would be fantastic!

Please put the script in `assets/scripts/install.ps1`.

I just registered `https://git.io/chezmoi.ps1` to point to `https://raw.githubusercontent.com/twpayne/chezmoi/master/assets/scripts/install.ps1`.

**Comment by zb140** [comment]
I've created #1007 for this; I'm just waiting for the CI to finish.

I added a quick note about how to use it to the `INSTALL` doc.  There's some extra detail that needs to be added about how to pass in arguments (sadly, it's not as easy as `... | pwsh -c - other args here`).  When I have a bit more time, I'll find a logical place to add that detail in the doc.

**Comment by zb140** [comment]
I just gave it a try and verified that it's working:
```
$  (iwr https://git.io/chezmoi.ps1).Content | pwsh -c -
checking GitHub for tag latest
found tag v1.8.10 for latest
found version 1.8.10 for latest/windows/amd64
Archive:  chezmoi_1.8.10_windows_amd64.zip
  inflating: LICENSE
  inflating: README.md
  inflating: completions/chezmoi-completion.bash
  inflating: completions/chezmoi.fish
  inflating: completions/chezmoi.ps1
  inflating: completions/chezmoi.zsh
  inflating: docs/CHANGES.md
  inflating: docs/CONTRIBUTING.md
  inflating: docs/FAQ.md
  inflating: docs/HOWTO.md
  inflating: docs/INSTALL.md
  inflating: docs/MEDIA.md
  inflating: docs/QUICKSTART.md
  inflating: docs/REFERENCE.md
  inflating: docs/TEMPLATING.md
  inflating: chezmoi.exe
Installed [...]/chezmoi.exe
```

It works on Linux systems with Powershell installed, too (because I _might_ not be the only one with one of those :wink:).  It _should_ work on macOS but I don't have one, so I can't try.

**Comment by twpayne** [comment]
For info, I just tried this on my Windows machine (which I'm not very familiar with) and got:

```
PS C:\Users\twpay> (iwr https://git.io/chezmoi.ps1).Content | pwsh -c -
iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet
Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:2
+ (iwr https://git.io/chezmoi.ps1).Content | pwsh -c -
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestComman
   d

```

**Comment by twpayne** [comment]
(Note that I've deliberately avoided Internet Explorer, but do have Edge installed and configured as my default browser)

**Comment by zb140** [comment]
Wow, even as a seasoned Windows dev, that's a new one on me.  I didn't know there was an IE-specific component to `Invoke-WebRequest`.

This should work:
```
(iwr https://git.io/chezmoi.ps1 -UseB).Content | pwsh -c -
```

If it does, I can update the doc.  Note that before version 6, `pwsh.exe` was called `powershell.exe`.  The built-in version is still 5.1, so you may need `| powershell -c -` instead, unless you've manually installed v6+.

**Comment by twpayne** [comment]
```
PS C:\Users\twpay> (iwr https://git.io/chezmoi.ps1 -UseB).Content | pwsh -c -
pwsh : The term 'pwsh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:50
+ (iwr https://git.io/chezmoi.ps1 -UseB).Content | pwsh -c -
+                                                  ~~~~
    + CategoryInfo          : ObjectNotFound: (pwsh:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\twpay> (iwr https://git.io/chezmoi.ps1 -UseB).Content | powershell -c -
An error occurred while creating the pipeline.
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RuntimeException

An error occurred while installing: unsupported architecture:
```

(Machine is a Lenovo laptop with an Intel chip)

**Comment by zb140** [comment]
Sorry it's not working quite right :smile:  When you get a chance, can you tell me what this prints?
```
powershell -c "write-host $([Runtime.InteropServices.RuntimeInformation]::OSArchitecture)"
```

**Comment by twpayne** [comment]
Empty string:
```
PS C:\Users\twpay> powershell -c "write-host $([Runtime.InteropServices.RuntimeInformation]::OSArchitecture)"

PS C:\Users\twpay>
```

**Comment by twpayne** [comment]
FYI
:
```
Edition	Windows 10 Home
Version	20H2
Installed on	‎12/‎1/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0
```

**Comment by zb140** [comment]
I'm not sure why the architecture check isn't working on some systems.  I'll reopen this to track the issue while I'm digging.  Maybe there's an alternate way to do the check that will work better.

**Comment by zb140** [comment]
@twpayne It looks like the API I was using to check the architecture is only supported on version 6+ of Powershell.  I thought I'd tried it with v5 but I guess I must have missed it somehow.  Sorry about that!

I've made some tweaks that should be able to support both.  It seems to be working for me, but can you give this version a try when you get a chance?
```
(iwr https://raw.githubusercontent.com/zb140/chezmoi/install-ps1/assets/scripts/install.ps1 -UseB).Content | powershell -c -
```

Thanks!

**Comment by twpayne** [comment]
Much closer :)

```
PS C:\Users\twpay> (iwr https://raw.githubusercontent.com/zb140/chezmoi/install-ps1/assets/scripts/install.ps1 -UseB).Content | powershell -c -
checking GitHub for tag latest
found tag v1.8.10 for latest
found version 1.8.10 for latest/windows/amd64
An error occurred while installing: The term 'unzip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

For what it's worth, my Windows install is pretty minimal: just Edge, VSCode, and Windows Services for Linux. I think Windows Explorer has built-in support for .zip files but I don't think the unzip command is installed by default. Do you think it would be possible to leverage that somehow, to avoid the dependency on an installed unzip command?

**Comment by zb140** [comment]
Thanks for helping me debug!  I've pushed a new version that uses the built-in `Expand-Archive` function to unzip (which is actually a better solution anyway, but I was so used to `unzip` being installed that I never looked for an alternative :smile:).  The docs say it should be available in your version.  Can you give it a try and let me know how it goes?

**Comment by twpayne** [comment]
Perfect!

```
PS C:\Users\twpay> (iwr https://raw.githubusercontent.com/zb140/chezmoi/install-ps1/assets/scripts/install.ps1 -UseB).Content | powershell -c -
checking GitHub for tag latest
found tag v1.8.10 for latest
found version 1.8.10 for latest/windows/amd64
Installed C:\Users\twpay\bin/chezmoi.exe

PS C:\Users\twpay> bin/chezmoi --version
chezmoi version 1.8.10, commit 11ed57d9a7e86434744f336b595ed0fd19aff6f5, built at 2020-12-20T12:09:31Z, built by goreleaser
```
