### ISSUE TITLE
Evaluating .chezmoi.kernel in a template fails in Windows

### ISSUE THREAD

**Issue by holofermes** [twpayne/chezmoi#1028]
## Describe the bug
Evaluating `.chezmoi.kernel` in a template fails inWindows.

## To reproduce

Follow the [directive for detecting WSL on Windows](https://www.chezmoi.io/docs/how-to/#detect-windows-subsystem-for-linux-wsl), and use the `chezmoi.kernel.osrelease` in a `tmpl` file

## Expected behavior

Not an error

## Output of command with `--verbose`

```
$ chezmoi diff --verbose
```

```
chezmoi: template:  C:\Users\me\.bashrc.sh:180: <.chezmoi.kernel.osrelease>: map has no entry for key "kernel"
```

## Additional context

I would like to use the suggested `.chezmoi.kernel.osrelease` directive in a template file that needs to be evaluated under Windows. Is there a way to do this?

**Comment by twpayne** [comment]
What is the output of `chezmoi doctor`? `.chezmoi.kernel` is only available in Linux (including Windows Services for Linux). If you want your template to run on both Windows and Windows Services for Linux then you need an extra guard on `.chezmoi.os`:

```
{{ if (eq .chezmoi.os "linux") }}
{{   if (contains "microsoft" .chezmoi.kernel.osrelease) }}
# running on WSL 2
{{   else }}
# running on Linux, but not WSL 2
{{   end }}
{{ else if (eq .chezmoi.os "windows") }}
# running on Windows
{{ else }}
# running on some other OS
{{ end }}
```

**Comment by holofermes** [comment]
My intention is to use my template from both Windows and Windows Services for Linux, and your suggestion is exactly what I need to do that. Thank you!
