### ISSUE TITLE
chezmoi apply using source file as argument

### ISSUE THREAD

**Issue by jackmac92** [twpayne/chezmoi#1030]
## Is your feature request related to a problem? Please describe.

I'd like to run `chezmoi apply` with a source file argument, to add a helper to my editor which automatically applies individual files on save. 

## Describe the solution you'd like
I can think of two options:
1) Add a `chezmoi target-path` which acts as the inverse of `chezmoi source-path`
this would allow me to run `chezmoi apply $(chezmoi target-path $CHEZMOI_SOURCE_FILE_PATH)`

2) Directly support a source file as argument in `chezmoi apply`

## Describe alternatives you've considered

I could maintain my own function which converts source path -> target path

## Additional context

I'm thinking this shouldn't be much effort, I can send a PR if you'd consider reviewing

**Comment by twpayne** [comment]
Thank you for this :) This is implemented in chezmoi2 (coming very soon - check issues), see #992.
