### ISSUE TITLE
Invoking prompt-functions in templates breaks

### ISSUE THREAD

**Issue by pflakus** [twpayne/chezmoi#1031]
## Describe the bug

The `promptString`-function isn't being recognized and prevents templates from being evaluated properly.  
The same behavior can be reproduced when invoking `promptBool` and `promptInt` instead.

## To reproduce

Define a template that invokes any of the prompt-functions in the chezmoi-repo. Try to parse the template, by invoking `diff`, `apply` or just `execute-template` .

## Expected behavior

The template being evaluated successfully, the user being prompted for input on execution.

## Output of command with `--verbose`

To narrow it down, I've reproduced the bug with a toy config based on the [reference article](https://www.chezmoi.io/docs/reference/):
```
$ cat /home/pflakus/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl
{{ $email := promptString "email" -}}
[data]
email = "{{ $email }}"
```

This yields the following behavior:
```
$ chezmoi execute-template --promptString "email=email@example.com" --verbose < ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl
chezmoi: template: stdin:1: function "promptString" not defined

$ chezmoi apply --verbose
chezmoi: template: /home/pflakus/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl:1: function "promptString" not defined
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version 1.8.11
ok: runtime.GOOS linux, runtime.GOARCH amd64
ok: /home/pflakus/.local/share/chezmoi (source directory, perm 700)
ok: /home/pflakus (destination directory, perm 700)
ok: /home/pflakus/.config/chezmoi/chezmoi.toml (configuration file)
ok: /usr/bin/zsh (shell)
ok: /usr/bin/vi (editor)
warning: vimdiff (merge command, not found)
ok: /usr/bin/git (source VCS command, version 2.30.0)
ok: /usr/bin/gpg (GnuPG, version 2.2.27)
ok: /usr/bin/op (1Password CLI, version 1.8.0)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context

I've found the issue #701, that seems to describe a similar issue. But I haven't found any prescriptions to try out from that research.  
I'm running this on an up-to-date Manjaro, with chezmoi installed via pacman.

I was able to reproduce the same behavior with chezmoi2, by the way:
```
$ go/bin/chezmoi2 diff --verbose
chezmoi: template: dot_config/chezmoi/chezmoi.toml.tmpl:1: function "promptString" not defined
```

**Comment by twpayne** [comment]
Thanks for the detailed report. The `prompt*` functions are only available in to create the initial config file in `chezmoi init`. To get the `prompt*` functions in `chezmoi execute-template` you need to pass the [`--init` flag](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#execute-template-templates).

Note also that the config file template needs to have a leading dot in the filename, e.g. be called `.chezmoi.toml.tmpl`.

Full example:

```
$ cat ~/.local/share/chezmoi/.chezmoi.toml.tmpl
{{ $email := promptString "email" -}}
[data]
email = "{{ $email }}"
$ chezmoi execute-template --init --promptString "email=email@example.com" --verbose < ~/.local/share/chezmoi/dot_config/chezmoi/.chezmoi.toml.tmpl
[data]
email = "email@example.com"
```

**Comment by pflakus** [comment]
That explains why I was running into this issue. When I use `init`/`--init`, everything works as expected!  
I appreciate the timely response! :+1:
