### ISSUE TITLE
Diff view in version 2 is opening the pager wrong

### ISSUE THREAD

**Issue by ptxmac** [twpayne/chezmoi#1040]
## Describe the bug

When running chezmoi diff the behaviour is very different between v1 and v2

Easiest to explain with pictures:

version 1: 
![image](https://user-images.githubusercontent.com/56919/108719217-94740700-751f-11eb-977d-ba89d6f1f4f6.png)

version 2:
![image](https://user-images.githubusercontent.com/56919/108719250-9d64d880-751f-11eb-84e4-dbea2676adf2.png)

Two problems here:
1. the ansi control characters are not interpreted by the pager (which pager is chezmoi starting, and with what arguments)
2. the pager is kept open even though there are only a few lines of output

## To reproduce

Have a small number of config changes and run chezmoi diff 

## Expected behavior

The same output as from version 1.8.11, nice colored output that closes the pager if less than a terminal screen full is needed.

## Output of command with `--verbose`

N/A

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v0.0.0-SNAPSHOT-7a26aca, commit 7a26aca9e30d33dbe8cbb4cc87d5632a3863077c, built at 2021-02-21T20:32:12Z, built by goreleaser
ok        os-arch              darwin/amd64
ok        config-file          /Users/ptx/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /Users/ptx/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in /Users/ptx/.local/share/chezmoi
ok        dest-dir             /Users/ptx is a directory
ok        shell                found /usr/local/bin/fish
ok        editor               found /usr/local/bin/code
ok        git-cli              found /usr/local/bin/git, version 2.23.0
ok        merge-cli            found /usr/bin/vimdiff
ok        gnupg-cli            found /usr/local/bin/gpg, version 2.2.24
warning   1password-cli        op not found in $PATH
warning   bitwarden-cli        bw not found in $PATH
ok        gopass-cli           found /Users/ptx/go/bin/gopass, version 1.12.1
warning   keepassxc-cli        keepassxc-cli not found in $PATH
warning   keepassxc-db         not set
warning   lastpass-cli         lpass not found in $PATH
warning   pass-cli             pass not found in $PATH
warning   vault-cli            vault not found in $PATH
warning   secret-cli           not set
```

## Additional context

Relevant environment variables:

- `TERM=xterm-256color`
- `PAGER` unset

**Comment by ptxmac** [comment]
also present in `chezmoi version v2.0.0, commit 325c65aee3dbc2ef796a2162c71b702bb62431be, built at 2021-02-22T21:12:14Z, built by goreleaser`

**Comment by twpayne** [comment]
I suspect that chezmoi is falling back to its default pager (`less`) here, which might not be the right thing to do. Would you mind running `PAGER=cat chezmoi diff` and reporting what happens?

> the pager is kept open even though there are only a few lines of output

I did a few tests with `git diff` and observed the same behavior (i.e. that if the diff has fewer lines than the terminal then you still get the pager). I observed this by running `git diff` when there were no changes in my working copy or in the index.

**Comment by ptxmac** [comment]
Interesting, `git diff` is not doing that on my system, I guess it chooses a different pager.

explicitly using `cat` reverts to the chezmoi v1 behaviour

**Comment by twpayne** [comment]
Thanks very much for reporting this, I think it's due to chezmoi defaulting to using `less` as a pager, rather than having no default pager. https://github.com/twpayne/chezmoi/pull/1043/commits/e2c039b842937c8c4aeb36a57045e7e65ec5e68f should fix it.

**Comment by ptxmac** [comment]
Looks like the Thanks, this works now!
