### ISSUE TITLE
Chezmoi edit keeps waiting for editor to close even if it's a folder

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1068]
## Describe the bug

This happened always, since v1, but keeps happening in v2.

When I enter: `chezmoi edit`, it's supposed to open my VS Code in my dotfiles folder. And it does, but for some reason, it keeps locked and I have to press Ctrl+C to make chezmoi exit.

See:
![Dz6UILropc](https://user-images.githubusercontent.com/29582865/111534666-04ecfd00-8747-11eb-99a3-d8a761ab4764.gif)

## To reproduce

Check the GIF above.

## Expected behavior

It was expected to not hold the command, as it doesn't when executed without chezmoi.

## Output of command with `--verbose`

Nothing.

## Output of `chezmoi doctor`

```
❯ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.0.0, commit 93d5695f95b94b9dd0f510e66e7f6d6c738021ac, built at 2021-03-17T15:47:14Z, built by homebrew
ok        os-arch              linux/amd64
ok        config-file          /home/felipesantos/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /home/felipesantos/.dotfiles is a directory
ok        suspicious-entries   no suspicious entries found in /home/felipesantos/.dotfiles
ok        dest-dir             /home/felipesantos is a directory
ok        shell                found /usr/bin/zsh
ok        editor               found /home/felipesantos/.local/bin/code
ok        git-cli              found /usr/bin/git, version 2.31.0
ok        merge-cli            found /usr/bin/vimdiff
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.19
warning   1password-cli        op not found in $PATH
warning   bitwarden-cli        bw not found in $PATH
warning   gopass-cli           gopass not found in $PATH
warning   keepassxc-cli        keepassxc-cli not found in $PATH
warning   keepassxc-db         not set
warning   lastpass-cli         lpass not found in $PATH
warning   pass-cli             pass not found in $PATH
warning   vault-cli            vault not found in $PATH
warning   secret-cli           not set
```

## Additional context

If I call it from within vscode, looks at what happens:

```
❯ chezmoi edit
At least one file must be provided to wait for.
❯ echo $EDITOR
code --wait
```

**Comment by twpayne** [comment]
I think what's happening here is that `code --wait` requires at least one file to wait on ([reference](https://code.visualstudio.com/docs/editor/command-line#_core-cli-options)), whereas chezmoi invokes your editor with a directory (not a file) if there are no arguments (as per [this suggestion](https://github.com/twpayne/chezmoi/issues/366#issue-459579962)). This would explain the `At least one file must be provided to wait for.` message from `chezmoi edit`.

Obviously chezmoi's current behavior can be improved. Some suggestions:

* Have some sort of optional args so that `--wait` is only passed to `code` when the arguments include files.
* Have some sort of config option to use [`os/exec.Cmd.Start`](https://pkg.go.dev/os/exec#Cmd.Start) instead of [`os/exec.Cmd.Run`](https://pkg.go.dev/os/exec#Cmd.Run) for running the editor, maybe depending on whether chezmoi needs to wait for the file to be edited (e.g. in the case of `chezmoi edit --apply $TARGET`) or not (e.g. in the case of `chezmoi edit $TARGET`).

chezmoi's current handling of the editor comes from the UNIX process approach, which is sometimes quite different from how processes work on Windows. I'd appreciate any insights that you have here.

**Comment by felipecrs** [comment]
Hey @twpayne,

Did you see that in the GIF, `code --wait ~/.dotfiles` works as expected?

**Comment by twpayne** [comment]
> Did you see that in the GIF, `code --wait ~/.dotfiles` works as expected?

Yes-ish, but it's hard to tell from the GIF whether VS Code is closed or minimized.

Could you also run `chezmoi edit` with the `--debug` option? This will give some insight into exactly what is being executed.

**Comment by felipecrs** [comment]
```sh-session
❯ chezmoi edit --debug
2021-03-17T22:11:42-03:00 DBG Stat name=/home/felipesantos/.config/chezmoi/chezmoistate.boltdb
2021-03-17T22:11:42-03:00 DBG Mkdir error="mkdir /home/felipesantos/.dotfiles: file exists" name=/home/felipesantos/.dotfiles perm=511
2021-03-17T22:11:42-03:00 DBG Stat name=/home/felipesantos/.dotfiles
2021-03-17T22:11:42-03:00 DBG Lstat name=/home/felipesantos/.dotfiles
2021-03-17T22:11:42-03:00 DBG ReadFile data="README.md\nLICENSE\ninstall\nscripts/\ndocs/\nmiscellaneous/\n.gitpod...." filename=/home/felipesantos/.dotfiles/.chezmoiignore
```

And it keeps waiting.

**Comment by felipecrs** [comment]
Actually, I can't reproduce it anymore. Now `code --wait <folder>` is actually waiting for the editor to be closed.

**Comment by twpayne** [comment]
OK, it likely keeps waiting because [`os/exec.Cmd.Run`](https://pkg.go.dev/os/exec#Cmd.Run) never returns, and the logging only logs after the command returns.

**Comment by felipecrs** [comment]
I found out why it's returning 

> ❯ chezmoi edit
> At least one file must be provided to wait for.
> ❯ echo $EDITOR
> code --wait

In VS Code. It's because in VS Code, (and I'm using WSL),  the code binary is actually the code server (`/home/felipesantos/.vscode-server/bin/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/bin/code`) while outside it's `/mnt/c/Program Files/Microsoft VS Code/bin/code`. So this should be a bug for VSCode.

I wonder if there could be a switch like `code --wait --no-wait-for-folders` or something like that.

**Comment by felipecrs** [comment]
I honestly believe nothing should be changed at `chezmoi` anymore and its current behavior is fine.

**Comment by twpayne** [comment]
Cool, but let's keep this issue open for now. I'll change the labels from `bug` to `enhancement`.

Relevant to this, there's also #752, which hasn't been implemented yet.

**Comment by felipecrs** [comment]
FYI https://github.com/microsoft/vscode/issues/119221 and https://github.com/microsoft/vscode/issues/119220

**Comment by twpayne** [comment]
As the VSCode issue has been "resolved", and no changes are required in chezmoi at the moment, I'll close this issue.

**Comment by felipecrs** [comment]
Yep, the remote code cli now is able to wait for folders, it seems.

**Comment by felipecrs** [comment]
@twpayne another solution for this problem would be to allow setting a different editor for chezmoi for folders.

Something like: `chezmoi.folderEditor = 'code'`

**Comment by twpayne** [comment]
Re-opening to mark this as an unresolved discussion.

**Comment by twpayne** [comment]
Thinking about this further, I don't think `chezmoi.folderEditor` is needed. Please re-open if needed.

**Comment by felipecrs** [comment]
This was how I finally worked around this situation:

https://github.com/felipecrs/dotfiles/commit/13367d1b91a17dc1776fd33de097791102bb0cba#diff-25acca575d8eaac4e3467dd0cf6b8ac55699cfd9b80a05ea1e683632268101ddR47-R59
