### ISSUE TITLE
chezmoi v2 docs not yet published to chezmoi.io

### ISSUE THREAD

**Issue by gotgenes** [twpayne/chezmoi#1069]
The chezmoi version 2.0.0 docs still need to be published to [chezmoi.io](https://www.chezmoi.io/). It's currently still displaying the docs for v1. This might have been interrupted by [the Snap Store matter](https://github.com/twpayne/chezmoi/issues/1039#issuecomment-800623545) mentioned in #1039.

Congratulations on releasing version 2! Thanks for all your work on chezmoi!

**Comment by twpayne** [comment]
Thanks for reporting this and thank you for your kind words @gotgenes :) I held off updating chezmoi.io just in case there were some bad bugs (*cough* #1070 *cough*) but I think things are mostly stable now, and chezmoi.io is now up to date.

See https://www.chezmoi.io/docs/changes/ for confirmation.
