### ISSUE TITLE
Restore old behavior for chezmoi diff without diff of scripts by setting in the config

### ISSUE THREAD

**Issue by breml** [twpayne/chezmoi#1083]
## What exactly are you trying to do?

I want to run `chezmoi diff` and don't expect the diff of the scripts to be visible.

## What have you tried so far?

I found out, that I can run `chezmoi diff --exclude scripts`, which restores the old behavior (from before https://github.com/twpayne/chezmoi/commit/2ba9aed42e499266991dd6cada9c5ad3f8aa56f0), but I would like this to be the default. I tried several settings in the config file, but without success.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

**Comment by twpayne** [comment]
Ah, that's a fair request. At the moment there's no way to set this in the config file, you can only do it with the command line option, but I'll add this.

Roughly, it will probably look something like this in your config file:

```toml
[diff]
    exclude = ["scripts"]
```

**Comment by breml** [comment]
@twpayne Thanks for the fix, I am waiting for a release in order to test it in my setup.

**Comment by twpayne** [comment]
> I am waiting for a release in order to test it in my setup.

😄 I usually prefer to test before releasing (joke!)

I'm planning to finish #1149 before tagging `v2.0.10` as there are enough fixes to justify a new point release now, but #1149 is important.

**Comment by twpayne** [comment]
> @twpayne Thanks for the fix, I am waiting for a release in order to test it in my setup.

@breml v2.0.10 is released. Please do report if you find any problems.

**Comment by breml** [comment]
@twpayne Thanks for the update and the release (and all the good work on `chezmoi`). I tested v2.0.10 successfully with the new setting:

```yaml
diff:
    exclude: ["scripts"]
```

The old behavior is restored.
