### ISSUE TITLE
2.0.3's upgrade command doesn't work with `noupgrade`

### ISSUE THREAD

**Issue by daurnimator** [twpayne/chezmoi#1088]
Trying to compile with `noupgrade` I get:
```
# github.com/twpayne/chezmoi/cmd
cmd/upgradecmd.go:20:13: c.runUpgradeCmd undefined (type *Config has no field or method runUpgradeCmd)
```

**Comment by twpayne** [comment]
Whoops, sorry about that. I messed up the build flags in #1086. Fixed with #1090. I'll tag a `v2.0.4` release shortly (I'm hoping to squeeze in a fix for #1083 first).
