### ISSUE TITLE
1password op get item --fields support 

### ISSUE THREAD

**Issue by jdillon** [twpayne/chezmoi#1098]
## Describe the solution you'd like

Current `op` command has a `get item` with `--fields` flag which makes it a lot simpler to extract values from details or **section fields**.

The `output` function can be used with this:

```
{{- output "op" "get" "item" "some-id" "--fields" "some-field" }}
```

But it might be nicer to have a built-in _onepassworditemFields_ function (or something) to make this a bit nicer to integrate?

**Comment by twpayne** [comment]
I might have misunderstood, but is [`onepasswordDetailsFields `](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#onepassworddetailsfields-uuid-vault-uuid) what you're looking for?

**Comment by jdillon** [comment]
@twpayne I do not think so, IIUC that extracts the first details object out of the response and makes the object addressable with dot-notation; where the 1password section data is nested a lot deeper into the document.  I did try a few times to see if that would work using the same uuid and field-name that I pass into `op get item uuid --fields field-name` and it wasn't very happy.  But could also have been user error ;-)

But it seemed like _onepasswordDetailsFields_ was to be used to get at the details.fields[] array, and didn't work for trying to get at details.sections[] array and its nested fields[] array?  The later seems like its also a different structure with keys "k", "n", "t", and "v" vs. "name", "type" and "value" from the top-level details.fields[] array.

When I try with `chezmoi execute-template '{{- onepasswordDetailsFields "uuid" }}'` though it reflects the above and only shows what the document has in in the top-level details.fields[] array.

**Comment by twpayne** [comment]
Ah, thank you for the clarification. I had not seen 1Password sections before. I added a new item and got the following output from `op get item Password`:

```json
{
  "uuid": "kurxepyi4fecvprcrj33y2ppxa",
  "templateUuid": "005",
  "trashed": "N",
  "createdAt": "2021-03-25T21:00:33Z",
  "updatedAt": "2021-03-25T21:00:33Z",
  "changerUuid": "E4E37JRIBJFP7L3VDPWBLKENAY",
  "itemVersion": 1,
  "vaultUuid": "3shvaihfe5dwbixtr4ajkmvrje",
  "details": {
    "notesPlain": "",
    "password": "",
    "passwordHistory": [],
    "sections": [
      {
        "name": "linked items",
        "title": "Related Items"
      },
      {
        "fields": [
          {
            "k": "string",
            "n": "C62E810B76134453AB876F89471DCD62",
            "t": "Section label",
            "v": "Test value"
          }
        ],
        "name": "Section_20E0BD380789477D8904F830BFE8A121",
        "title": ""
      }
    ]
  },
  "overview": {
    "ainfo": "Mar 25, 2021 at 10:00:33 PM",
    "ps": 0,
    "title": "Password"
  }
}
```

So that I can understand correctly, given the above data from `op`, how should `onepasswordItemFields` be called and what should it return?

**Comment by zb140** [comment]
I was about to comment and say I was sure I had added that at one point, but it looks like I only ever mentioned it ([here](https://github.com/twpayne/chezmoi/issues/814#issuecomment-661230512)).

**Comment by twpayne** [comment]
Thanks @zb140!

If someone would like to contribute a PR, the relevant file to modify is [`cmd/onepasswordtemplatefuncs.go`](https://github.com/twpayne/chezmoi/blob/master/cmd/onepasswordtemplatefuncs.go) and you'll also need to add the template function [here](https://github.com/twpayne/chezmoi/blob/master/cmd/config.go#L304-L306). You'll also need to add a test in [`testdata/scripts/onepassword.txt`](https://github.com/twpayne/chezmoi/blob/master/testdata/scripts/onepassword.txt).

**Comment by jdillon** [comment]
@twpayne i've only just started to use 1password with chezmoi so i'm not sure what all the various use-cases might be.  But for what I need something like this to fetch a single field value:

```
{{ onepasswordGetItemField "uuid" "field-name" }}
```

I'm not sure what the utility is for fetching more than one field, but there probably is one that i'm not aware of ;-)  but maybe for that another function:

```
{{ onepasswordGetItemFields "uuid" "field-name1" "field-name2" }}
```

resulting in the json object:

```
{
   "field-name1": "value1",
   "field-name2": "value2"
}
```

BUT as I mentioned i'm not sure what the use-case is for that ;-)

**Comment by jdillon** [comment]
> If someone would like to contribute a PR

I would but my core skills are with Java and GO sill makes my head hurt a little to look at, or I would give it a shot myself.

**Comment by twpayne** [comment]
Re-opening as @bric3 has some great feedback on #1388 which should be addressed before this can be properly considered fixed :)

**Comment by twpayne** [comment]
Comments addressed, so closing this.
