### ISSUE TITLE
[features] add support for shell templates command

### ISSUE THREAD

**Issue by aarnphm** [twpayne/chezmoi#1101]
## Is your feature request related to a problem? Please describe.

I was wondering whether it is possible to assign a pipeline for Linux to a variable in templates. I wasn't able to assign shell functions correctly to a variables in a templates.

## Describe the solution you'd like

I would love to take a look on a solution like so

```gohtmltmpl

{{- $vm := shell "command -v virt-what" }}
...
{{- if eq $vm "" }}
// then this machine is not vm
...
{{- end }}

```

## Describe alternatives you've considered

I have tried 
```gohtmltmpl

{{- $vm := "`$(command -v virt-what)`" }}
// doesn't seem to work
{{- $vm := `"$(command -v virt-what)"` }}

```

## Additional context
Would you like to implement such feature in chezmoi2?

**Comment by twpayne** [comment]
I think the existing [`lookPath`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#lookpath-file) and [`output`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#output-name-args) template functions meet you needs, please re-open this issue if not.

**Comment by aarnphm** [comment]
> I think the existing [`lookPath`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#lookpath-file) and [`output`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#output-name-args) template functions meet you needs, please re-open this issue if not.

Thank you for your help, this would work perfectly.
