### ISSUE TITLE
Cannot use "managed" command without signing in to 1Password anymore

### ISSUE THREAD

**Issue by adriaanzon** [twpayne/chezmoi#1107]
## What exactly are you trying to do?

With chezmoi 1.x I used a shell function to edit my dotfiles and apply them immediately. The function first lists all managed files using `chezmoi managed`, then it edits the chosen file with `chezmoi edit --apply`. This is what it looks like (it's a fish script):

```fish
function d --description 'Edit dotfiles'
    set -l file (chezmoi managed --include files | fzf --select-1 --query "$argv")
    and chezmoi edit --apply --verbose ~/"$file"
end
```

Now when I run `chezmoi managed` with chezmoi 2.x, it tries to execute the templates, some of which contain calls to `onepassword`. So this requires me to be signed in to 1Password only to get a list of the managed files.

Also once I am signed in to 1Password it takes significantly longer to list all files, presumably because it now parses all templates.

So I was wondering if there was a way to work around this, or if this is something that should be fixed in the `managed` command of chezmoi 2.x.

## What have you tried so far?

n/a

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi managed --verbose
chezmoi: template: private_dot_config/nvim/coc-settings.json.tmpl:2:50: executing "private_dot_config/nvim/coc-settings.json.tmpl" at <onepassword "zyuqdsryv5dyzenrn6kadrx6ve">: error calling onepassword: op get item zyuqdsryv5dyzenrn6kadrx6ve: exit status 1: [ERROR] 2021/03/28 14:36:02 You are not currently signed in. Please run `op signin --help` for instructions
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.0.4, commit 9cc8184cc466a87c44006218e02365046e5d5f8b, built at 2021-03-24T20:20:46Z, built by homebrew
ok       os-arch              darwin/arm64
ok       config-file          /Users/adriaan/.config/chezmoi/chezmoi.json is a file
ok       source-dir           /Users/adriaan/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /Users/adriaan/.local/share/chezmoi
ok       dest-dir             /Users/adriaan is a directory
ok       shell                found /bin/zsh
ok       editor               found /opt/homebrew/bin/nvim
ok       git-cli              found /usr/bin/git, version 2.24.3
ok       merge-cli            found /usr/bin/vimdiff
info     age-cli              age not found in $PATH
ok       gnupg-cli            gpg not found in $PATH
ok       1password-cli        found /usr/local/bin/op, version 1.8.0
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

**Comment by twpayne** [comment]
Thanks very much for reporting this and for the clear and complete bug report!

I'm sure that this is a bug in chezmoi v2, and I can reproduce it on my machine. chezmoi is supposed to evaluate templates only when needed, and they are certainly not needed for the `chezmoi managed` command.
