### ISSUE TITLE
chezmoi_2.0.5_linux_amd64.tar.gz: cannot find release asset

### ISSUE THREAD

**Issue by MunifTanjim** [twpayne/chezmoi#1115]
## Describe the bug

```sh
❯ chezmoi upgrade
chezmoi: chezmoi_2.0.5_linux_amd64.tar.gz: cannot find release asset
```

**Comment by twpayne** [comment]
Thanks for reporting this. The underlying problem was that I was building separate glibc and musl libc archives for Linux (#995) and had forgotten that older versions of chezmoi would not be aware of the new distinctions.

#1116 fixes this. I'll tag a new version now.
