### ISSUE TITLE
Error updating subdirectory from another repository

### ISSUE THREAD

**Issue by skymoo** [twpayne/chezmoi#1133]
## Describe the bug

I have oh-my-zsh added to my dotfiles repository and up until recently I updated oh-my-zsh using:

```
curl -s -L -o oh-my-zsh-master.tar.gz https://github.com/robbyrussell/oh-my-zsh/archive/master.tar.gz
chezmoi import --strip-components 1 --destination /home/ram/.oh-my-zsh oh-my-zsh-master.tar.gz
```

as in detailed in the  [how-to](https://www.chezmoi.io/docs/how-to/#include-a-subdirectory-from-another-repository-like-oh-my-zsh). After updating to chezmoi-2.0.7, prior to update I was using something in the 1.8.x series, the above commands no longer work for updating oh-my-zsh.

## To reproduce

```
curl -s -L -o oh-my-zsh-master.tar.gz https://github.com/robbyrussell/oh-my-zsh/archive/master.tar.gz
chezmoi import --strip-components 1 --destination /home/ram/.oh-my-zsh oh-my-zsh-master.tar.gz
```

## Expected behavior

oh-my-zsh is updated and added into my chezmoi repository

## Actual behavior

```
curl -s -L -o oh-my-zsh-master.tar.gz https://github.com/robbyrussell/oh-my-zsh/archive/master.tar.gz
chezmoi import --strip-components 1 --destination /home/ram/.oh-my-zsh oh-my-zsh-master.tar.gz
chezmoi: rename /home/ram/.local/share/chezmoi/dot_oh-my-zsh/dot_oh-my-zsh/dot_github /home/ram/.local/share/chezmoi/dot_oh-my-zsh/dot_oh-my-zsh/dot_github: no such file or directory
```
It seems that it's putting another `dot_oh-my-zsh` directory into the PATH. Any ideas why?

**Comment by twpayne** [comment]
Thanks very much for reporting this!

It turns out that the bug only occurs when the destination directory already exists, which wasn't covered by chezmoi's test suite.

#1134 fixes this and adds a test so that the bug won't re-occur.
