### ISSUE TITLE
cannot get secret from iCloud keychain on macos

### ISSUE THREAD

**Issue by craighurley** [twpayne/chezmoi#1137]
## What exactly are you trying to do?

New user here.  I was just experimenting with the keychain commands to `set` and `get` secrets on macos, hoping I could rely secrets that sync across machines via the `iCloud` keychain.

Using chezmoi, I can `set` and then `get` without issue.  The `set` command creates the secret entry under the `login` keychain.  I may be missing something simple here, but items in the macos `login` keychain do not get sync'd across machines.  When I manually create a secret under the `iCloud` keychain, the secret is sync'd across machines, however I cannot `get` the secret with chezmoi.

#### keychain: login

```
$ chezmoi secret keyring set --service=chezmoi --user=chezmoi-username
Value: pwd
```

```
$ chezmoi secret keyring get --service=chezmoi --user=chezmoi-username
pwd
```

#### keychain: iCloud

I manually create an entry under the iCloud keyring, but I cannot `get` it using chezmoi

```
$ chezmoi secret keyring get --service=chezmoiicloud --user=chezmoiicloud-username
chezmoi: secret not found in keyring
```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

Note: I have not configured anything other than try the commands listed above.

```
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.0.9, commit 7c7213b32435823ce3fd0dc468fdecefe7c5e8f9, built at 2021-04-04T19:13:34Z, built by goreleaser
ok       os-arch              darwin/arm64
info     config-file          /Users/hurley/.config/chezmoi/chezmoi.toml does not exist
error    source-dir           /Users/hurley/.local/share/chezmoi: open /Users/hurley/.local/share/chezmoi: no such file or directory
error    suspicious-entries   lstat /Users/hurley/.local/share/chezmoi: no such file or directory
ok       dest-dir             /Users/hurley is a directory
ok       shell                found /usr/local/bin/bash
ok       editor               found /usr/local/bin/vim
ok       git-cli              found /usr/local/bin/git, version 2.30.0
ok       merge-cli            found /usr/local/bin/vimdiff
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/local/bin/gpg, version 2.2.26
info     1password-cli        op not found in $PATH
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
ok       keepassxc-cli        found /usr/local/bin/keepassxc-cli, version 2.6.4
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

**Comment by twpayne** [comment]
chezmoi uses [`github.com/zalando/go-keyring`](github.com/zalando/go-keyring) for keyring access, which in turn runs `/usr/bin/security`. `man security` makes no mention of the iCloud keychain, and [this StackOverflow question](https://apple.stackexchange.com/questions/297691/is-it-possible-to-access-and-modify-icloud-keychain-from-command-line-or-automa) and [this question on Apple support](https://developer.apple.com/forums/thread/102131) suggest that there is no way to access the iCloud keychain from the command line.

If you do find a way to access the iCloud keychain from the command line then please report it here and re-open this issue and I'll look at integrating it into chezmoi.
