### ISSUE TITLE
Ability to use --template-symlinks=home and --template-symlinks=source at the same time

### ISSUE THREAD

**Issue by Flygrounder** [twpayne/chezmoi#1141]
## Is your feature request related to a problem? Please describe.
I've realized, that `--template-symlinks=home` and `--template-symlinks=source` should not be mutually exclusive. If I am adding a directory, that contains symlinks both to homedir and sourcedir, I want both of this types to be handled appropriately:
1. If a symlink is pointing to sourcedir, then `{{  .chezmoi.sourceDir }}` should be used
2. If it is pointing to some other directory inside home, then `{{ .chezmoi.homedir }}` should be used
3. Otherwise, symlink would not be changed

## Describe the solution you'd like
`chezmoi add --template-symlinks=source,home`

## Describe alternatives you've considered
Adding each file individually with the appropriate option.

## Additional context
I would like to create shell alias on my system, like this:
`alias cha 'chezmoi add --template-symlinks=source,home'` 
to always use this behavior, but currently it's not possible.

Also, if this proposal is fine, I can implement it myself.

**Comment by twpayne** [comment]
`--autotemplate` already has this behavior, by looking for the longest submatch when considering replacements. What do you think of #1142?

**Comment by Flygrounder** [comment]
I am a bit skeptical about using autotemplate because there are some false positives.

For example, I have the following line in my config:
`# a desktop environment or as fallback terminal emulators.`

Since my hostname on current machine is `desktop`, it gets replaced by
`# a {{ .chezmoi.hostname }} environment or as fallback terminal emulators.`

which doesn't make sense.

I might use autotemplate occasionally, but surely not always. On the other hand, `--template-symlinks` is quite safe to be used always with `add`, e.g. using shell alias. 

It's my personal perspective on this. I am also interested, what @3v1n0 thinks about it, since they've originally proposed this functionality.

**Comment by twpayne** [comment]
> I am a bit skeptical about using autotemplate because there are some false positives.

Fair point! How about we make `--template-symlinks` a boolean flag which tries to replace `{{ .chezmoi.sourceDir }}` first then `{{ .chezmoi.homeDir }}` second (as `sourceDir` will usually be subdirectory of `homeDir`)? Are there any situations where you wouldn't want both replacements to be tried? Note that the user can always fall back to creating the symlink template manually for non-standard cases.

**Comment by Flygrounder** [comment]
For me that sounds reasonable, I cannot imagine situation where I don't want this behavior
