### ISSUE TITLE
ARM 2.0.9 install error

### ISSUE THREAD

**Issue by Ranbato** [twpayne/chezmoi#1144]
## Describe the bug

It looks like the naming convention has changed for the precompiled binaries for 2.0.9.  When running `curl -sfL https://git.io/chezmoi | sh` on my RPi it doesn't locate the correct file because there isn't one with glibc in the name.

## To reproduce

Download the install file `wget https://raw.githubusercontent.com/twpayne/chezmoi/master/assets/scripts/install.sh`
Execute ` sh ./install.sh -d`

## Expected behavior

chezmoi to be installed 

## Output of command with `--verbose`

```
raspberrypi% sh ./install.sh -d
debug checking GitHub for tag latest
debug http_download https://github.com/twpayne/chezmoi/releases/latest
debug found tag v2.0.9 for latest
info found version 2.0.9 for latest/linux/arm
debug http_download https://github.com/twpayne/chezmoi/releases/download/v2.0.9/chezmoi_2.0.9_linux-glibc_arm.tar.gz
debug http_download_curl received HTTP status 404
```

**Comment by twpayne** [comment]
Thank you @Ranbato very much for reporting this, and particularly for going the extra mile to add debug output with `-d` which isn't documented. Much appreciated!

Should be fixed with #1146 (have tested locally on my Raspberry Pi). Will merge once CI passes.
