### ISSUE TITLE
Confusion around once_, before_, and after_ with run scripts

### ISSUE THREAD

**Issue by sheeley** [twpayne/chezmoi#1148]
## What exactly are you trying to do?
I have these scripts in `~/.local/share/chezmoi`:
```
bin/plists/run_after_once_ai.krisp.krispMac.sh
run_after_once_fish_shell_setup.sh          
run_before_once_mas_applications.sh
```

I'd hoped that I'd be able to combine `before` or `after` with `once`.

## What have you tried so far?
Reading https://www.chezmoi.io/docs/reference/#scripts and https://www.chezmoi.io/docs/reference/#source-state-attributes

I'm not going to follow the rest of the template because I think this is primarily a comprehension/documentation issue. It looks to me like in saying

> run_, once_, before_ or after_

You're indicating that they cannot be combined. Is that accurate? Can I help to update the docs to reflect that more explicitly, or would you be interested in enabling their combination?

**Comment by twpayne** [comment]
Yes, I'd be very happy for a PR that updates the docs. There's a section in the reference manual [here](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#source-state-attributes) that I think is wrong.

**Comment by sheeley** [comment]
Handling this with #1150
