### ISSUE TITLE
chezmoi init --no-data

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1154]
## Problem

Since https://github.com/twpayne/chezmoi/pull/1033, we are able to use something like the following in our templates:

```
{{- $email := get . "email" -}}
{{- if not $email -}}
{{- $email = promptString "email" -}}
{{- end -}}

[data]
email = "{{ $email }}"
```

However, if I intentionally want to update my email, I don't have much ways to do.

## Solution

A new option for `init`, `--no-data`, which will prevent `chezmoi` from passing `chezmoi data` to `chezmoi init`. As it was before https://github.com/twpayne/chezmoi/pull/1033.

## Alternatives

- Edit the `~/.config/chezmoi/chezmoi.toml` manually
- ```
  rm -f ~/.config/chezmoi/chezmoi.toml
  ~/.dotfiles/install
  # or
  chezmoi init --source-dir ~/.dotfiles
  ```

**Comment by twpayne** [comment]
Thanks for the suggestion. Implemented in #1156. Note that I made the option `--data` defaulting to `true` (not `--no-data` defaulting to `false`) to avoid a double-negative.
