### ISSUE TITLE
Only prompt user about overwriting when there are changes to the content of a file.

### ISSUE THREAD

**Issue by jackmac92** [twpayne/chezmoi#1155]
## Is your feature request related to a problem? Please describe.

I really like the new prompt to prevent accidental overwrites, but I'm consistently getting prompted about "changes" to my zoom config when the diff shows up empty. I use a `modify_` script for this file, and I guess the local zoom server is frequently `touch`ing this file which makes it appear to be updated.

## Describe the solution you'd like

Only prompt the user if there is a real content change

## Describe alternatives you've considered

Use a custom shell command to apply my chezmoi changes, and force apply known problem files first to prevent this prompt

## Additional context

![image](https://user-images.githubusercontent.com/2984710/114624823-48238880-9c7f-11eb-898a-626b7851928c.png)

**Comment by twpayne** [comment]
Thanks very much for reporting this :)

I'm pretty sure that this is a bug in chezmoi, the same one as #1066 and #1091.

There's a work-in-progress fix in #1149, but it's not finished yet.

**Comment by twpayne** [comment]
Should be fixed with #1149.
