### ISSUE TITLE
Ability to compose templates

### ISSUE THREAD

**Issue by mhadam** [twpayne/chezmoi#1158]
## Issue

I tried doing something like this, with the hope of concatenating multiple templates into one file:

```
{{ template "dot_zshrc_shared" }}
{{ if eq .chezmoi.os "darwin" }}
{{ template "dot_zshrc_darwin" }}
{{ end }}
{{ if eq .chezmoi.os "linux" }}
{{ template "dot_zshrc_linux" }}
{{ end }}
```

I put those templates under `.chezmoitemplates`.

But running chezmoi returned this:

```
chezmoi: template: dot_zshrc_shared:85:31: executing "dot_zshrc_shared" at <.chezmoi.username>: nil data; no entry for key "chezmoi"
```

I'm assuming this is because these don't evaluate normally, but rather require arguments be specified.

## Solution

I think the best solution would be a template function like `include` that evaluates the included text.

**Comment by twpayne** [comment]
I think you need to pass in the template context (the first `.` in `.chezmoi.os`), i.e.:

```
{{ template "dot_zshrc_shared" . }}
{{ if eq .chezmoi.os "darwin" }}
{{ template "dot_zshrc_darwin" . }}
{{ end }}
{{ if eq .chezmoi.os "linux" }}
{{ template "dot_zshrc_linux" . }}
{{ end }}
```

The relevant lines from the [`text/template` documentation](https://pkg.go.dev/text/template) are:

```
{{template "name"}}
	The template with the specified name is executed with nil data.

{{template "name" pipeline}}
	The template with the specified name is executed with dot set
	to the value of the pipeline.
```

chezmoi's documentation can obviously be improved here.

**Comment by mhadam** [comment]
Thanks for the quick response! I *just* figured that out before I saw this. Seems to work fine.

Yea, this is just a matter of me not being familiar with Go's template package.
