### ISSUE TITLE
Add support for multiple repos as source of chezmoi user configuration

### ISSUE THREAD

**Issue by MurzNN** [twpayne/chezmoi#1169]
## Is your feature request related to a problem? Please describe.

Very often we have some settings, that can be shared between multiple users. Most of them are universal features, that will be useful for different users and use cases, so can be shared publicly, or privately to some team, to sync via chezmoi.

But also each user often have it's own private settings, that he wasn't share to anybody else, but want sync them between own computers via chezmoi.

And when configuring chezmoi, there is dilemma: make the cool public `dotfiles` git repository, that will be useful for other people, and sync private settings via other way, or make your chezmoi repo private, accessible only for you.

And, I guess, most of users select the private way. So the result is that we have a lot of private `dotfiles` repositores, that aren't available publicly for reusing/forking, and can't be shared between users.

## Describe the solution you'd like

The good solution will be implement support for multiple vcs repositories in chezmoi, and merge settings from all of configured repos to home directory. And, if configured multiple repos, ask user to each repo he want to upload the new file.

As result, we will got much more public `dotfiles` repositories, and ability to sync some separate settings securely between multiple users in team, without sharing user's private settings.

Moreover, we will can build the large hierarchy of configurations for apply on each computer, something like:
- dotfiles-company
- - dotfiles-company-department1
- - - dotfiles-company-department1-designers
- - - - dotfiles-company-department1-designers-vasya

I understand, that we will can got a lot of conflicts and other unusual situations, when applying configuration from multiple repos to same file, but they can be warned and solved manually via overwriting rules or some other ways.

## Describe alternatives you've considered

At not this can be implemented, as I understand, only on vcs (git) side:
- private primary repo with public base repo
- public base repo and private fork with additional files
- private git repo with git submodule to public repo, and bunch of symlinks

But manage all this ways and backport all changes to parent repo is too uncomfortable.

**Comment by twpayne** [comment]
Thanks for the suggestion :)

As you identify, this would add a lot of complexity to chezmoi.

Some initial thoughts:

Firstly, chezmoi supports setting the source directory with the `-S` / `--source` flag. You can then run chezmoi multiple times with different source directories from different repos. For example, you could run chezmoi first with a dotfiles-company source, then run chezmoi with a dotfiles-company-department1 source, and so on. All this can be scripted.

More generally, chezmoi has the stated of goal of helping users manage their personal dotfiles across multiple machines. It is deliberately not a corporate system management tool. For these, whole system and fleet management tools like Ansible, Chef, Puppet, and Salt are much more appropriate, even if the files managed are individual users' dotfiles.

There is some overlap here with #189 and #753. Happy to discuss further.

**Comment by MurzNN** [comment]
> More generally, chezmoi has the stated of goal of helping users manage their personal dotfiles across multiple machines. It is deliberately not a corporate system management tool. For these, whole system and fleet management tools like Ansible, Chef, Puppet, and Salt are much more appropriate, even if the files managed are individual users' dotfiles.

I already use Salt (also his used alternatives to) - they are great for system-wide settings, but applying something in userspace is pain in all of those solutions. This is because I stick to `chezmoi` to deploy user settings in company employees accounts. The `chezmoi` simply runs on user login with user permissions (no root needed), and apply all needed settings, that's all.

Your proposal with using different source directories is cool, and seems not so hard to integrate, here is idea:
In configuration file for `sourceDir` variable allow to set lists instead of one string, and if it contains list - apply actions in cycle to each source in filled order, and for changing actions - ask user to which repository he want to apply this change (ask always or apply the default (first item) with ability to set needed one by argument). 

Something like this:
```yaml
sourceDir: 
  alice: ~/.local/share/chezmoi
  dep1: ~/.local/share/department1
  corp: /opt/company/dotfiles

sourceDirAskAlways: true
```
and on `add` action:
```bash
$ chezmoi add ~/.bashrc
chezmoi is configured to use multiple repositories, to which one you want add this file?
1. alice [default]
2. dep1
3. corp
Fill right number or name of repository, or press "Enter" to use default.
> 
```
and using argument - without questions:
```bash
$ chezmoi add --repo=dep1 ~/.bashrc
```

**Comment by MurzNN** [comment]
Other example of multiple repos needs:
I have my common personal settings (eg bash aliases, some universal automate scripts), that can be easily shared between any computers and servers, with which I works (via my own account or shared technical account).
So on every new not-my-own computer on any login I can simply type `chezmoi init MurzNN` to apply my settings.

Also I have settings, that I need only for my own personal computers, and don't want to share them to other accounts, so want to publish them into private repo.

**Comment by jonbarksdale** [comment]
I have a similar need from a different perspective. 

In my case, I try to keep all my work related settings, aliases, etc out of my personal dotfiles repo to avoid inadvertently leaking anything that might be considered confidential.  I'm not talking just secrets, but maybe there's an directory to a secret project or something in there; better safe than sued.   

To address that, I've kept a public dotfiles repo for my personal stuff, and then I have a private work repo kept on my work git server, using another dotfile manager.  

I'm working on moving my stuff over to chezmoi (very tedious process), but this is a kludgy area, where having two repos isn't well supported.

**Comment by arran4** [comment]
The case I want is slightly different. I would like to be able to use an existing private repo as a vault / secrets which I would like to pull stuff into the templating system to use with my public chezmoi.

**Comment by twpayne** [comment]
> The case I want is slightly different. I would like to be able to use an existing private repo as a vault / secrets which I would like to pull stuff into the templating system to use with my public chezmoi.

Have you considered using a password manager instead of an existing private repo? Many password support storing whole files as well as passwords. Also consider using a [customized password manager](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-a-custom-password-manager) that retrieves data from your existing private repo.

**Comment by arran4** [comment]
Oh I do, and I will. This is more for things like authorized keys, and ssh-config target machines. I will likely be using /several/ different vaults.

**Comment by twpayne** [comment]
For the moment, this is a specialized use case that I think is best served by adding scripting around chezmoi. For example, a script could combine the source state from multiple repos and then invoke `chezmoi apply` using the combined source state.
