### ISSUE TITLE
Chezmoi templates do not contains chezmoi data elements

### ISSUE THREAD

**Issue by gaborbernat** [twpayne/chezmoi#1171]
When instantiating a chezmoi (meta)-template (as suggested by https://www.chezmoi.io/docs/how-to/#handle-different-file-locations-on-different-systems-with-the-same-contents) the `.chezmoi.os` is not set. Reproducible repository https://github.com/gaborbernat/dotfiles/blob/main/.chezmoitemplates/profile.ps1.tmpl#L1

```bash
chezmoi status
chezmoi: template: profile.ps1.tmpl:16:22: executing "profile.ps1.tmpl" at <.chezmoi.os>: nil data; no entry for key "chezmoi"

 chezmoi --version
chezmoi version v2.0.10, commit 3782e9330712b143a3c6383ea171091784fa2de3, built at 2021-04-15T10:50:21Z, built by goreleaser
```

**Comment by twpayne** [comment]
You need to pass the context (typically `.`) when calling `template`, for example:

    {{ template "profile.ps1" . }}

I'll update the documentation to make this clearer.

**Comment by gaborbernat** [comment]
Thanks, I guess perhaps in the above example I've linked in the documentation, if we'd have it passed would have been clearer. Thanks for the excellent tool!
