### ISSUE TITLE
Add ability to sync managed file from remote http source

### ISSUE THREAD

**Issue by MurzNN** [twpayne/chezmoi#1175]
## Is your feature request related to a problem? Please describe.

Sometimes users reusing some single script, that located in some external repository (public git repo, gist, or simple http url). They downloads its manually one time and place in homedir, but forgot to update every time when something changed.

For example, this script https://gist.github.com/MurzNN/ee64f98ab2e71b886c41d55594e5dd9e or this tool https://raw.githubusercontent.com/MurzNN/translate-selection/master/translate-selection.sh

## Describe the solution you'd like

To solve this task will be good to have ability to sync some single files from remote locations (http url) via chezmoi.

**Comment by twpayne** [comment]
This can be done with a `run_` scrtipt.

**Comment by twpayne** [comment]
For example, using `curl`, create a file in the source directory called `modify_translate-selection.sh` containing

```sh
#!/bin/sh

curl -fsLS https://raw.githubusercontent.com/MurzNN/translate-selection/master/translate-selection.sh
```

With this, `modify-selection.sh` will always have the latest contents of the script from the URL, and differences will be visible in `chezmoi diff` etc.

Please re-open this issue if needed.
