### ISSUE TITLE
Chezmoi timing out on chezmoi apply

### ISSUE THREAD

**Issue by rmferrer** [twpayne/chezmoi#1180]
## Describe the bug

Getting `chezmoi: timeout` when performing `chezmoi apply`, dotfiles are not updated.

## To reproduce

Run `chezmoi apply`

## Expected behavior

Command to complete quickly without errors and see the changes applied.

## Output of command with `--verbose`

```
~ chezmoi apply --verbose
chezmoi: timeout
```

## Output of `chezmoi doctor`

```
~ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.0.10, commit 3782e9330712b143a3c6383ea171091784fa2de3, built at 2021-04-15T12:24:50Z, built by homebrew
ok       os-arch              darwin/amd64
ok       config-file          /Users/rmferrer/.config/chezmoi/chezmoi.yaml is a file
ok       source-dir           /Users/rmferrer/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /Users/rmferrer/.local/share/chezmoi
ok       dest-dir             /Users/rmferrer is a directory
ok       shell                found /bin/zsh
ok       editor               found /usr/bin/vi
ok       git-cli              found /usr/local/bin/git, version 2.31.1
ok       merge-cli            found /usr/bin/vimdiff
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/local/bin/gpg, version 2.3.1
ok       1password-cli        found /usr/local/bin/op, version 1.9.0
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set```

## Additional context

Add any other context about the problem here.

**Comment by twpayne** [comment]
Ah, so chezmoi's error message is misleading here. This is likely the same as #815.

What's actually (likely) happening here is that there is another instance of chezmoi running which is holding the database lock. Could this be the case?

**Comment by twpayne** [comment]
What's the output of

    lsof | grep $HOME/.config/chemzoi

?

**Comment by rmferrer** [comment]
$ chezmoi git:(master) lsof | grep ${HOME}/.config/chezmoi
chezmoi   23420 rmferrer  txt       REG                1,4    2097152              667936 /Users/rmferrer/.config/chezmoi/chezmoistate.boltdb
chezmoi   23420 rmferrer    6u      REG                1,4    2097152              667936 /Users/rmferrer/.config/chezmoi/chezmoistate.boltdb

**Comment by twpayne** [comment]
So this seems to indicate that an instance of chezmoi is already running with PID 23420. Do you know what this instance could be? What is the output of

    ps -p 23420

?

**Comment by rmferrer** [comment]
Yeah it seems there was a hanging `chezmoi update` command lingering.
```
$ ps -p 23420
  PID TTY           TIME CMD
23420 ttys000    0:15.76 chezmoi update
```

**Comment by twpayne** [comment]
OK, so this seems to be behaving as expected. Please re-open if needed.
