### ISSUE TITLE
SOPS for data attributes?

### ISSUE THREAD

**Issue by craighurley** [twpayne/chezmoi#1188]
Hello, thanks for making chezmoi :)

## Is your feature request related to a problem? Please describe.

This is not related to a problem.

## Describe the solution you'd like

Have you considered adding support for SOPS (https://github.com/mozilla/sops)?  It could be useful for those wanting to version control data attributes (e.g. tokens) and reference them throughout various templates.

**Comment by twpayne** [comment]
I've had a look at SOPS but it's unclear to me how widely it's used or what advantages it has over a password manager for personal use.

How exactly would you envision the chezmoi/SOPS integration to work?

Note that if you want to use SOPS to manage secrets in the `data` section of your config file (which are available as template variables) then I think you can run:

    sops exec-file ~/.config/chezmoi/chezmoi.yaml 'chezmoi --config={}`

**Comment by twpayne** [comment]
@craighurley or @anthr76, could you provide more details on how you'd like chezmoi/SOPS integration to work?

**Comment by twpayne** [comment]
As it looks like SOPS already has a mechanism to integrate with arbitrary programs (including chezmoi), I'm closing this as `won't fix`. Please re-open this issue if there's a better way to improve SOPS/chezmoi integration.
