### ISSUE TITLE
chezmoi status and (run_) scripts

### ISSUE THREAD

**Issue by neersighted** [twpayne/chezmoi#1189]
## Describe the bug

`chezmoi status` reports a script as modified. The script is templated but the bug persists without the template.

## To reproduce

My dotfiles / this file https://github.com/neersighted/dotfiles/blob/master/private_dot_local/bin/run_compile_disowntty.sh.tmpl exhibit the behavior.

## Expected behavior

`chezmoi status` should not consider a script to be modified.

## Output of command with `--verbose`

```
$ chezmoi status --verbose
 R .local/bin/compile_disowntty.sh
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.0.11
ok        os-arch              linux/amd64
ok        config-file          /home/neersighted/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /home/neersighted/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in /home/neersighted/.local/share/chezmoi
ok        dest-dir             /home/neersighted is a directory
ok        shell                found /usr/sbin/fish
ok        editor               found /usr/sbin/nvim
ok        git-cli              found /usr/sbin/git, version 2.31.1
ok        merge-cli            found /usr/sbin/vimdiff
failed    age-cli              found /usr/sbin/age, could not parse version from (devel)

ok     gnupg-cli       found /usr/sbin/gpg, version 2.2.27
info   1password-cli   op not found in $PATH
info   bitwarden-cli   bw not found in $PATH
ok     gopass-cli      found /home/neersighted/.local/share/go/bin/gopass, version 1.9.2
info   keepassxc-cli   keepassxc-cli not found in $PATH
info   keepassxc-db    not set
info   lastpass-cli    lpass not found in $PATH
info   pass-cli        pass not found in $PATH
info   vault-cli       vault not found in $PATH
info   secret-cli      not set

```

**Comment by twpayne** [comment]
Ah, chezmoi's documentation could be improved here. The thinking behind this behavior is that `chezmoi status` gives you a quick overview of what would happen if you ran `chezmoi apply`.

The `R` indicates that chezmoi will run the script if you run `chezmoi apply`. In this case, the script is a `run_` script, not a `run_once_` script, so chezmoi will run it every time you run `chezmoi apply`.

For this particular script (`run_compile_disowntty.sh.tmpl`), it looks like it would be better as a `run_once_` script. Also, consider using [this trick](https://github.com/twpayne/chezmoi/issues/468#issuecomment-781319352) to ensure that chezmoi recompiles `disowntty` whenever `disowntty.c` changes.

**Comment by neersighted** [comment]
Ah, that explains it. The hash trick will be excellent to add to the docs.

I guess the real source of my confusion is the `chezmoi diff` output, which I think is the real bug here:

```
diff --git a/.local/bin/compile_disowntty.sh b/.local/bin/compile_disowntty.sh
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..2281d40823d30b64086c8b3c7cbf18d516a6a680 100755
--- a/.local/bin/compile_disowntty.sh
+++ b/.local/bin/compile_disowntty.sh
@@ -0,0 +1,5 @@
+#!/bin/sh
+
+cc -g -o "$HOME/.local/bin/disowntty" "/home/neersighted/.local/share/chezmoi/private_dot_local/bin/disowntty.c"
+
+# vi: ft=sh
```

**Comment by twpayne** [comment]
Similar to status, the thinking behind diff is that it shows what would change, including which scripts would be run.

You can exclude scripts from the diff output, see #1083.

I'll keep this issue open until the docs are updated.
