### ISSUE TITLE
chezmoi doesn't detect the hostname set `hostnamectl` (via `systemd-hostnamed`).

### ISSUE THREAD

**Issue by tomprince** [twpayne/chezmoi#1190]
## Describe the bug

Linux distros like Fedora 34 use `systemd-hostnamed` to set the hostname, but doesn't touch `/etc/hosts` so chezmoi doesn't detect the hostname.

## To reproduce

On a fedora 34 host, run the following commands:

```
$ hostnamectl set-hostname some.fqdn.example
$ chezmoi data | jq '.chezmoi.fqdnHostname' -r
localhost
```

## Expected behavior

I expect the result of the commands to be "some.fqdn.example"

## Output of `chezmoi doctor`

```
RESULT   CHECK                MESSAGE
ok       version              v2.0.10, commit 3782e9330712b143a3c6383ea171091784fa2de3, built at 2021-04-15T10:50:21Z, built by goreleaser
ok       os-arch              linux/amd64
ok       config-file          /home/tomprince/.config/chezmoi/chezmoi.toml is a file
ok       source-dir           /home/tomprince/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /home/tomprince/.local/share/chezmoi
ok       dest-dir             /home/tomprince is a directory
ok       shell                found /bin/zsh
ok       editor               found /usr/bin/nvim
ok       git-cli              found /usr/bin/git, version 2.31.1
ok       merge-cli            found /usr/bin/nvim
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/bin/gpg, version 2.2.27
info     1password-cli        op not found in $PATH
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

**Comment by twpayne** [comment]
Thanks for reporting this. It's a shame that `systemd-hostnamed` doesn't update `/etc/hosts`, as - as far as I can tell -reading `/etc/hosts` has been the most common way of determining the FQDN hostname for some time.

Does `hostname --fqdn` at least return the FQDN hostname on Fedora 34? If so, you can use the [`output` template function](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#output-name-args), e.g.

    {{ $hostname := (output "hostname" "--fqdn" | trim) }}

If your FQDN hostname does not change very often then you can create your own FQDN hostname in your config file template (`.chezmoi.toml.tmpl` in the source directory), e.g.

    [data]
        fqdnHostname = {{ output "hostname" "--fqdn" | trim | quote }}

and then use the `.fqdnHostname` (instead of `.chezmoi.fqdnHostname`) in your scripts.

chezmoi runs on many operating systems that will never have systemd (e.g. macOS, Windows, FreeBSD, and non-systemd Linux distributions) so I am extremely resistant to adding systemd-specific code to chezmoi when the problem can be worked around with templates.

Hope this helps.

**Comment by tomprince** [comment]
> Thanks for reporting this. It's a shame that `systemd-hostnamed` doesn't update `/etc/hosts`, as - as far as I can tell -reading `/etc/hosts` has been the most common way of determining the FQDN hostname for some time.

I was curious about this, so I did some digging. Looking in the Debian Administrator's Handbook for [squeeze](https://www.debian.org/releases/squeeze/) (which predates systemd), I found [this example `/etc/hosts`](https://salsa.debian.org/hertzog/debian-handbook/-/blob/squeeze/master/en-US/08_basic-configuration.xml#L736-737) which does have the FQDN in `/etc/hosts`.

Looking closer, I see that the code chezmoi has specifically looks for 127.0.1.1 to find the hostname. Digging into this, it appears that this this convention the originated in debian (see [here](https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution) and the links in the bug about 127.0.1.1), which seems to have spread to some other distros (e.g [arch](https://wiki.archlinux.org/title/Network_configuration#Local_network_hostname_resolution), [linux-man-pages](https://man7.org/linux/man-pages/man5/hosts.5.html) which says it is "often" used for that). Note that even the debian reference says that if the host has a permanent IP, that it should be used instead of 127.0.1.1.

Looking at other unixes, I don't see anything definitive about 127.0.1.1, but it appears common to use that address as the address of jail on freebsd, which would not be appropriate for the local FQDN outside the jail.

> 
> Does `hostname --fqdn` at least return the FQDN hostname on Fedora 34?

Yes. Also, that information is contained in `/etc/hostname` (see [here](https://www.freedesktop.org/software/systemd/man/hostname.html#) for example).

**Comment by twpayne** [comment]
Thanks for the detailed investigation!

I'll update chezmoi to read the hostname from /etc/hostname.

**Comment by twpayne** [comment]
Thanks very much for the detailed investigation - very much appreciate!
