### ISSUE TITLE
Chezmoi cd does not Launch a shell in the source directory.

### ISSUE THREAD

**Issue by DanielTamkin** [twpayne/chezmoi#1201]
## Describe the bug

When attempting to run `chezmoi cd`, I'm only returned back to my default prompt.

## To reproduce

![image](https://user-images.githubusercontent.com/9532762/117844175-1503f300-b245-11eb-9f4f-401022cf46fe.png)

Running WSL2, `Ubuntu 18.04.5 LTS`, on a newly installed [Windows Terminal](https://github.com/Microsoft/Terminal). Interestingly enough, my terminal is listed as chezmoi, however I'm not redirected to the chezmoi source directory.

## Expected behavior

Once running `chezmoi cd`, open a new shell and redirect to the source directory.

## Output of command with `--verbose`

Running :
```
$ chezmoi cd--verbose
```
Produces: 
![image](https://user-images.githubusercontent.com/9532762/117844845-a2474780-b245-11eb-88f4-2419185892ca.png)

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.0.12, commit 2256a83c51b97f4a326feb66fd3ebdc3f1833a15, built at 2021-05-10T22:46:04Z, built by goreleaser
ok       os-arch              linux/amd64
info     config-file          /home/danieltamkin/.config/chezmoi/chezmoi.toml does not exist
ok       source-dir           /home/danieltamkin/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /home/danieltamkin/.local/share/chezmoi
ok       dest-dir             /home/danieltamkin is a directory
ok       shell                found /bin/bash
ok       editor               found /usr/bin/vi
ok       git-cli              found /usr/bin/git, version 2.31.1
ok       merge-cli            found /usr/bin/vimdiff
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/bin/gpg, version 2.2.4
info     1password-cli        op not found in $PATH
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

## Additional context
Most likely User Error. I followed the [One binary](https://www.chezmoi.io/docs/install/#one-line-binary-install) install script on two machines with same configuration, similar behavior.

**Comment by DanielTamkin** [comment]
> Most likely User Error.

<sup>- A very, very dumb person.</sup>

Always check your terminal configs! For anyone that discovers this issue in the future, my `.bashrc` had a specific line that overwrote chezmoi's redirect to source directory.
![image](https://user-images.githubusercontent.com/9532762/117851355-d7569880-b24b-11eb-8e88-c0b4208f0f16.png)
Commenting out this line solved the issue.
![image](https://user-images.githubusercontent.com/9532762/117851466-f9e8b180-b24b-11eb-839e-17bf19c159a5.png)

Hopefully this issue may aide in troubleshooting for others.

**Comment by twpayne** [comment]
Thanks for the investigation and reporting this solution here :)
