### ISSUE TITLE
Is there a way to add all modified files?

### ISSUE THREAD

**Issue by andyborrell** [twpayne/chezmoi#1207]
If I've modified files in the destination directory, chezmoi can show me them all if I do "chezmoi status".  But if I want to add all of these modifed files to the source directory I have to do 

chezmoi add FILENAME 

for every file.

Is there way to add them all?  Similar to how how "git add -u"  works.  Thanks.

**Comment by twpayne** [comment]
There's no such command at the moment. You can do it with a script:

    chezmoi status | cut -c 4- | xargs chezmoi add

That said, this feature has been requested a few times already, so I'll add it.

**Comment by twpayne** [comment]
Fixed with #1208.
