### ISSUE TITLE
How to add whole directory without .keep

### ISSUE THREAD

**Issue by weeebdev** [twpayne/chezmoi#1211]
## What exactly are you trying to do?

I want to add my `~/.config/fish` directory to chezmoi with all completions, functions, etc. Also, even if the directory is not empty, it still creates `.keep` file.

## What have you tried so far?

I tried to use `chezmoi add -r ~/.config/fish`, but it added the files inside of the `~/.config/fish`, but not files inside of subdirectories.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

**Comment by weeebdev** [comment]
Oh, I see, actually, it works. But how do I get rid of this `.keep` files?

**Comment by twpayne** [comment]
You can remove the `.keep` files with `find`:

    find $(chezmoi source-path) -name .keep -delete

The `.keep` files are ignored by chezmoi (as they begin with a `.`) but are required by git as git does not support empty directories.

**Comment by weeebdev** [comment]
> You can remove the `.keep` files with `find`:
> 
> ```
> find $(chezmoi source-path) -name .keep -delete
> ```
> 
> The `.keep` files are ignored by chezmoi (as they begin with a `.`) but are required by git as git does not support empty directories.

Yeah, but it still creates them even if the directory is not empty

**Comment by twpayne** [comment]
Which version of chezmoi are you using?

**Comment by weeebdev** [comment]
> Which version of chezmoi are you using?
`chezmoi version dev`

**Comment by twpayne** [comment]
Ok, please can you try with a released version of chezmoi. See the install docs for how to get one.

**Comment by weeebdev** [comment]
> Ok, please can you try with a released version of chezmoi. See the install docs for how to get one.

Yeah, now it works. Thanks!
