### ISSUE TITLE
Docs: Running scripts on file change

### ISSUE THREAD

**Issue by neersighted** [twpayne/chezmoi#1216]
I noticed the [FAQ entry](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#how-do-i-only-run-a-script-when-a-file-has-changed) is slightly behind the [HOWTO](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#run-a-script-when-the-contents-of-another-file-changes).

It's probably best to fold any still useful ideas from the FAQ into HOWTO and remove the entry from the FAQ list, in my opinion. Either way, I think this should be consolidated now that the idea of including checksums into `run_once_` scripts as comments/triggers is officially documented.

**Comment by twpayne** [comment]
Thanks for spotting this :)
