### ISSUE TITLE
How to make config files conditionally exist

### ISSUE THREAD

**Issue by junwei-wang** [twpayne/chezmoi#1220]
## What exactly are you trying to do?

I have some configuration on my mac in the path "~/Library/...".
Those files are useless for Linux.
But each time, I run "chezmoi diff" on my Linux, chezmoi on Linux would tell me I didn't apply those file.
Is there a programatic way to tell chezmoi that I only want those file exist on macOS?

## What have you tried so far?

I know I can use template. 
But this is not ideal. 
Because, templates still need the unwanted file exist.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

**Comment by twpayne** [comment]
Yes, you can use `.chezmoiignore` for this. Put the following in a file called `.chezmoiignore` in your source directory:

    {{ if ne .chezmoi.os "darwin" }}
    Library
    Library/**
    {{ end }}

This will cause chezmoi to ignore the `Library` and anything in `Library` everywhere _except_ on macOS (darwin).

**Comment by twpayne** [comment]
Hope this answers your question. Please re-open this issue if neeed.
