### ISSUE TITLE
Usage of your install script

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#1223]
I am creating an "just for fun" open source project that can install pre-built binaries for different architectures. I took heavy insipiration from https://github.com/twpayne/chezmoi/blob/master/assets/scripts/install.sh as you have done such diligent work in that script.

I just wanted to be courteous and ask if you are ok with me copying a large part of the code in there? 😃 

**Rationale behind the script**
I install many tools on new machines. I got tired of outdated versions in package managers or even missing packages, so I wanted to create a simple shell script that can be used like:

```sh
git.io/obi fzf exa chezmoi rg
```

Where it automatically installs them into a set `BINDIR` for your os/architecture.

**Comment by twpayne** [comment]
Yup, that's absolutely fine. The code is under the same MIT license as chezmoi, so you're free to use it.
