### ISSUE TITLE
Manage different profiles for different teams/contexts using branches

### ISSUE THREAD

**Issue by ChloeTigre** [twpayne/chezmoi#1234]
## What exactly are you trying to do?

We have several engineering teams with different dotfiles needs. We would like to allow them to have different versions of their dotfiles for example in order to test out some changes before they would have them applied to their entire team.

I'd like to have say the Potato pod from the Roots team to be able to fetch their dotfiles from branch `roots/potato` of their repository and some early adopters/testers to fetch their dotfiles from `roots/potato-next`.

In case things go bad, I'd like to be able to rollback to `roots/potato` but that would be more of a nice to have as there's always the option of cleaning up the files and re-applying.

## What have you tried so far?

Setting up chezmoi and trying to set a branch through the tool. Unsuccessfully. Only managed it through direct git commands.

## Where else have you checked for solutions?

* [x ] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x ] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x ] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Additional context

We are trying to provide a reference tool for a number of developers ecosystem of 80+. chezmoi looks like a great base for this but it seems right now it addresses more the needs of an individual on several computers rather than of several individuals with things in common.

Providing a base branch from which each team could fork their own stuff would also push cooperation between teams which is cool and something we want.

Thanks =)

**Comment by twpayne** [comment]
Thanks for opening this issue :) cc @MurzNN who is considering using chezmoi in a similar way in 
#1169.

As you identify, this is currently possible only through git commands. chezmoi does provide a shortcut to run git in the source directory so you can run a single command now to switch branches:

    chezmoi git checkout roots/potato-next

Rollback support is of course provided by git.

Could you give examples of what you would like the chezmoi interface to look like? One possible addition would be the option to specify a initial branch to checkout in `chezmoi init`, for example:

    chezmoi init --branch=roots/potato githost.com/org/repo

**Comment by twpayne** [comment]
A quick comment on:

> chezmoi looks like a great base for this but it seems right now it addresses more the needs of an individual on several computers rather than of several individuals with things in common.

Yes, this is currently by design -- once your needs expand beyond managing your personal files then you might well be better off with a whole-system management tool like Ansible/Chef/Puppet/Salt.

That said, there have been a number of requests for chezmoi to support multiple source directories (e.g #189, #780, #1169) , so this is still in consideration.

**Comment by twpayne** [comment]
@ChloeTigre could you provide more details on what you'd like the chezmoi interface to look like?

**Comment by ChloeTigre** [comment]
Hi @twpayne 
I would love to indeed be able to follow another branch than the default `main` at init (and your proposal is just *fine* for this).

I would also like to be able to switch to another branch. Using `chezmoi git` commands would be fine for that, and maybe proposing a git flow and explaining the use case. To each their own, but what I suggested to my users is that when they add new tools to their collective dotfiles, they should add a feature branch with the tool name and open a merge request. Then others can review the config for sanity and merge to `main`.

Really just adding a `--ref` or `--branch` option to chezmoi init would be sweet.

**Comment by twpayne** [comment]
OK, #1247 adds a `--branch` option to `chezmoi init`. I'll release a new version of chezmoi in a few days that includes this.
