### ISSUE TITLE
Make the `-c` flag behave like `-S`

### ISSUE THREAD

**Issue by norman-zon** [twpayne/chezmoi#1256]
## Is your feature request related to a problem? Please describe.

My use case is similiar to #1169, but less complex. I have only two repos I want to manage with chezmoi: my private dotfiles and work dotfiles that are shared across the company, but do not conflict with my private ones.
For this scenario using `-S,--source`works well enough. But both repos have a config template `.chezmoi.toml.tmpl`, which leads to conflicts. I expected it would be possible to use the `-c,--config`flag the same way as the `-S,--source` flag, so when running `chezmoi -S ~/.mychezmoi -c ~/.mychezmoi/chezmoi.toml init <myrepo>`the repo would be checked out to `~/.mychezmoi`and the config would be templated to `~/.mychezmoi/chezmoi.toml`. But the config still is templated to `.config/chezmoi/chezmoi.toml`.

## Describe the solution you'd like

I would like to have the `-c` flag behave the same way as the `-S` flag, so it is possible to specify where a config template should be written out to when running `chezmoi init -c <somepath>`.

**Comment by twpayne** [comment]
So, this turned out to be trickier to implement than expected because of chezmoi's support for multiple config file formats.

Instead, #1272 implements a new `-C`/`--config-path` option to the `init` command (and only the `init` command) that specifies where the config file should be created, which should meet your needs.

**Comment by norman-zon** [comment]
Thanks a lot for taking the time to implement this.

**Comment by norman-zon** [comment]
Sorry to come back to this after such a long time, but I just noticed, that when I use the `--config-path` flag I always get the 

```
chezmoi: warning: config file template has changed, run chezmoi init to regenerate config file
``` 

warning when running `chezmoi apply` afterwards. The warning persist if I run `chezmoi init --config-path ...` again.
