### ISSUE TITLE
Linux: distribution detection

### ISSUE THREAD

**Issue by codygarver** [twpayne/chezmoi#126]
My example use case is I have bash functions that manipulate the distro package manager and it would be nice if chezmoi could ifdef them by distro. Something like:

```
{{- if eq .chezmoi.distribution "ubuntu" }}
function install-package { apt install $1 ; }
{{- end }}

{{- if eq .chezmoi.distribution "arch" }}
function install-package { pacman -S $1 ; }
{{- end }}

{{- if eq .chezmoi.distribution "fedora" }}
function install-package { dnf install $1 ; }
{{- end }}
```

`distribution` would be automagically determined by the `ID` field in `/etc/os-release`, which is standard and present on all Linux distributions.

**Comment by codygarver** [comment]
Another good reason for this feature is that `.bashrc` looks different across distros and applying modifications as is right now is overwriting `.bashrc`

**Comment by twpayne** [comment]
Great idea! Will implement.

**Comment by twpayne** [comment]
https://github.com/twpayne/chezmoi/pull/128 should fix this. The syntax is slightly different as you should have all the information from `/etc/os-release` at your disposal. Notably, instead of using `.chezmoi.distribution`, you should use `.chezmoi.osRelease.id`.
