### ISSUE TITLE
.chezmoiignore doesn't work

### ISSUE THREAD

**Issue by weeebdev** [twpayne/chezmoi#1260]
## What exactly are you trying to do?

When I run either `chezmoi diff` or `chezmoi apply` it ignores my `.chezmoiignore`

## What have you tried so far
My `.chezmoiignore` path `chezmoi/private_dot_config/.chezmoiignore`

```
{{- if not (lookPath "glab") }}
private_lab
private_lab/**
{{- end }}
```

I want it to ignore `private_lab` folder which is located at `chezmoi/private_dot_config/`

What happens if I execute `.chezmoignore` as a template
```
private_lab
private_lab/**
```

## Where else have you checked for solutions?

* [ x ] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [ ] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [ x ] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi command --verbose
```
## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
`.chezmoiignore` uses paths in the target directory, not the source directory, so I think your file should contain:

```
{{- if not (lookPath "glab") }}
lab
lab/**
{{- end }}
```

**Comment by weeebdev** [comment]
Thanks!
