### ISSUE TITLE
Chezmoi init does not prompt for a string

### ISSUE THREAD

**Issue by fwSmit** [twpayne/chezmoi#1262]
## Describe the bug

I was following the instruction from https://www.chezmoi.io/docs/how-to/#create-a-config-file-on-a-new-machine-automatically where the promptString template function is used. On running `chezmoi init` there was no prompt, however.

## To reproduce

Set the following config file in the source directory:
`.chezmoi.toml.tmpl`
```toml
{{- $email := promptString "email" -}}
[data]
    email = {{ $email | quote }}
```
Run `chezmoi init`.
There will be no prompt and an incorrect config will be written. For me it writes:

```toml
[gpg]
  symmetric = true
```
If I remove `.chezmoi.toml` and `.chezmoistate.boltdb` nothing changes.

## Expected behavior

Prompt for an email and write the filled in config. And when the prompt fails I expect the non-templated part to still be there.

## Output of command with `--verbose`

```
$ chezmoi init --verbose
_nothing_

## Output of `chezmoi doctor`

```
$ chezmoi docto
warning   version              v2.0.13, built at 2021-05-28T09:29:53Z
ok        os-arch              linux/amd64 (Arch Linux/)
ok        config-file          /home/friso/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /home/friso/.local/share/chezmoi is a directory
warning   suspicious-entries   found suspicious entries in /home/friso/.local/share/chezmoi: /home/friso/.local/share/chezmoi/.chezmoi.toml.tmpl, /home/friso/.local/share/chezmoi/.chezmoiignore
ok        dest-dir             /home/friso is a directory
ok        shell                found /bin/zsh
ok        editor               found /usr/bin/nvim
ok        git-cli              found /usr/bin/git, version 2.32.0
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.27
info      1password-cli        op not found in $PATH
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not setr
```

## Additional context

My old config was something like

```toml
[data]
email=example@example.com
[gpg]
  symmetric = true
```

**Comment by twpayne** [comment]
Could you share the exact contents of `.chezmoi.toml.tmpl` from your source directory?

This issue reports that the contents of `~/.config/chezmoi/chezmoi.toml` are completely different in every way to the contents of `~/.local/share/chezmoi/.chezmoi.toml.tmpl`, which make me suspect that something else is going wrong here.

`promptString` is widely used and well tested so I suspect a configuration problem at this stage.

**Comment by fwSmit** [comment]
> Could you share the exact contents of `.chezmoi.toml.tmpl` from your source directory?
> 
> This issue reports that the contents of `~/.config/chezmoi/chezmoi.toml` are completely different in every way to the contents of `~/.local/share/chezmoi/.chezmoi.toml.tmpl`, which make me suspect that something else is going wrong here.
> 
> `promptString` is widely used and well tested so I suspect a configuration problem at this stage.

My bad, I was under the impression that the chezmoi config file should be located in `~/.local/share/chezmoi/private_dot_config/chezmoi/chezmoi.toml.tmpl`, as that would be consistent with every other file. It works now!
