### ISSUE TITLE
How should I modify the files managed by chezmoi? What if I modified them directly?

### ISSUE THREAD

**Issue by Anthonyive** [twpayne/chezmoi#1265]
## What exactly are you trying to do?

I'm sorry if this question is stupid...I came from git bare repo and I don't conceptually understand some of the workflows.

1. How should I modify the files managed by chezmoi?  I've read the docs and it seems like it's better to use `chezmoi edit ~/.zshrc`, for example, to modify managed/tracked files instead of modify them directly?

2. What if I modified them directly? What if say I directly used `vim ~/.zshrc` and changed something, do I have to re-add them to `chezmoi` git repo?

3. Also, is there a way to add all changes of all managed files to the source state? Like in bare repo, I can just `d git add -u`

## What have you tried so far?

I tried to research other people's guides/tutorials and see if they have the same question as mine. Hmm, nothing tried related to terminal.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
There are three popular approaches:

1. Use `chezmoi edit $FILE`. This will open the source file for `$FILE` in your editor, including . For extra ease, use `chezmoi edit --apply $FILE` to apply the changes when you quit your editor.
2. Use `chezmoi cd` and edit the files in the source directory directly.
3. Edit the file in your home directory, and then either re-add it by running `chezmoi add $FILE` or `chezmoi re-add`. Note that `re-add` doesn't work with templates.

Personally, I use approach #2.

**Comment by Anthonyive** [comment]
@twpayne Thank you! That helps a lot.
