### ISSUE TITLE
Define a specific editor to edit a specific file

### ISSUE THREAD

**Issue by mhalano** [twpayne/chezmoi#1266]
## What exactly are you trying to do?

I think this is a very sharp edge case, but could have other uses.
I use a tool called urlwatch. With this tool you should edit the configuration file with `urlwatch --edit`, and not edit the dotfile itself directly. This is done in that way because after the edition is done, the config file is checked for errors. Very neat.
The problem is after the config file is written (and this config file is kept in Chezmoi) always occurs a conflict, because I didn't edited with `chezmoi edit <config file>` command, but using the own  `urlwatch --edit` command.
A very similar problem could be related do sudo. With sudo you should use `visudo` command to edit the sudoers file, and not try to edit the file directly, because after the edition was done the /etc/sudoets has checked for any errors.
It's not so similar though the sudoers is a system file, inside /etc, and not a dotfile, but I think the principle is the same.

## What have you tried so far?

I looked in the reference for a way to change the editor command just for a specific subset of managed files.

I found the topic: "Handle configuration files which are externally modified". The idea here it was to not use `chezmoi edit` for this file, but keep tracking on the git repository. I tried this but when I use `urlwatch --edit`, do the edition, and save the file, it doesn't respect the symlink in place. It just rewrites the file, so after that I have my original file and lost the symlink.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md),
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer. The better option would be always use `chezmoi add` to add the fresh edit file.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi command --verbose
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.0.15, commit d02e707857d9b7365bb3c1b18a849362876efa88, built at 2021-06-17T20:42:01Z, built by goreleaser
ok        os-arch              linux/amd64 (Ubuntu/21.04 (Hirsute Hippo))
ok        config-file          /home/mhalano/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /home/mhalano/.local/share/chezmoi is a directory
warning   suspicious-entries   found suspicious entries in /home/mhalano/.local/share/chezmoi: /home/mhalano/.local/share/chezmoi/.chezmoiignore
ok        dest-dir             /home/mhalano is a directory
ok        shell                found /bin/zsh
ok        editor               found /usr/bin/nvim
ok        git-cli              found /usr/bin/git, version 2.30.2
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.20
info      1password-cli        op not found in $PATH
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set

```

**Comment by twpayne** [comment]
Interesting request. I think this is most easily handled by a wrapper script or bash function, e.g.:

```bash
urlwatch-edit() {
    urlwatch --edit && chezmoi add ~/.urlwatch
}
```

**Comment by mhalano** [comment]
For this specific case could work, but maybe a more sustainable solution could be nice. This is just my use case, but could have other similar use cases. I would like to mention sudoers case, but I don't think anyone manage this file with Chezmoi, because is a system file not a user file.

**Comment by twpayne** [comment]
Ultimately, as this is so specific, I think this is best achieved with a wrapper script. The script could either wrap `chezmoi edit` and call the appropriate editor for the filename given to it, or be wrap the editor (i.e. be set with chezmoi's `edit.command` configuration variable) and invoke the appropriate editor.
