### ISSUE TITLE
chezmoi specific editor environment variable :: CHEZMOI_EDITOR

### ISSUE THREAD

**Issue by lcrockett** [twpayne/chezmoi#1268]
## Is your feature request related to a problem? Please describe.

Not related to a problem, more of a 'quirk'. Z Shell defaults to VI mode (instead of emacs mode) if `$EDITOR` or `$VISUAL` is set to `*vi*`. This can be overridden by specifically setting `bindkey -e` in the Z Shell resource file (`.zshrc`), however in some configurations it has to be triggered at a specific stage (before or after triggering 'something'. It depends on what one is doing in their Z Shell resource file.

## Describe the solution you'd like

As `chezmoi` respects both the `$EDITOR` and `$VISUAL` environment variable for use with the `chezmoi edit`, one has to set it if an alternative editor is used (nvim instead of vi, for instance). As this interferes with previously described behaviour i'd like to propose introducing a `$CHEZMOI_EDITOR` environment variable that precedes `$VISUAL`, `$EDITOR`, and the default OS editor.

I believed it should be a simple matter of amending the following block:
https://github.com/twpayne/chezmoi/blob/d65299e78e31687ba2b4ada89ba385feff8de73c/internal/cmd/config.go#L835-L839

## Describe alternatives you've considered

I've considered running `bindkey -e` early stage `.zshrc`, but i'd prefer not to set the `$EDITOR` variable at all and therefore not needing the workaround. Quite a few tools seem to support overriding `$EDITOR` with their own variant. See also `$GIT_EDITOR`, `$K9S_EDITOR`.

Another alternative is always prepending `EDITOR=nvim` to running `chezmoi`. I call that workaround B.

**Comment by twpayne** [comment]
You can set the `edit.command` variable in the config file, e.g.

```toml
[edit]
    command = "nvim"
```

chezmoi will use this in preference to `$EDITOR`/`$VISUAL`. I note that this is mentioned in the list of configuration variables in the reference manual, but not in the documentation for the `edit` command. I'll fix that.

**Comment by lcrockett** [comment]
Apologies, I was not aware of that option, just tested it and set it. Works like a charmadillo, cheers !
