### ISSUE TITLE
Check /etc/hosts before /etc/hostname

### ISSUE THREAD

**Issue by camillesf** [twpayne/chezmoi#1269]
Hello! And thanks for chezmoi, it's very neat.

Recently `fqdnHostname` stopped working for me, and I tracked it down to 3a06eb82, where support for /etc/hostname was introduced.

I think support for /etc/hostname is neat, but I also believe the first choice should still be /etc/hosts—i.e., it's a matter of just reversing the order of these two ifs:

https://github.com/twpayne/chezmoi/blob/58570b5f01ec7f34c0a5d250e29f12a70ebef92e/internal/chezmoi/chezmoi_unix.go#L25-L30

My "belief" above can be supported, for example, by the [first three answers in this StackExchange question](https://askubuntu.com/questions/863132/should-one-use-fqdn-in-etc-hostname-instead-of-hostname).

All of them suggest that the standard thing to do is give the FQDN in /etc/hosts—and not necessarily /etc/hostname. That is, I interpret those answers to say that a FQDN in /etc/hostname without a corresponding FQDN in /etc/hosts is an unwanted setup.

Thanks for reading!

(If you agree with our rationale but might not have time to prepare a PR soon, just let us know that you agree, and we might find the time ourselves! Thank you.)

**Comment by camillesf** [comment]
On the other hand my suggestion to swap the calls is probably not the best choice: if someone has a FQDN in /etc/hostname, it would be nice to use it nevertheless?

It could be returned if /etc/hosts yielded nothing, or something without any `.`. Just a final thought.

**Comment by twpayne** [comment]
Thanks for reporting this and for your detailed investigation. I agree with you and have fixed it in #1271.
