### ISSUE TITLE
Not obeying local git configuration

### ISSUE THREAD

**Issue by matrixik** [twpayne/chezmoi#1270]
## Describe the bug

When using `autoCommit = true` and making changes to dotfiles, then chezmoi is using globally configured email instead of custom email set for dotfiles repository.

## To reproduce

* Set `autoCommit = true` in chezmoi config
* Go to dotfile repository
* Set custom local email `git config --local user.email "custom@example.com"`
* Edit some dotfile
* Run `chezmoi edit <file>` or `chezmoi add <file>`
* Check last commit email in dotfile repo with `git log -1 --pretty=format:'%ae'` or `git log -1`

## Expected behavior

Commits created by chezmoi use custom set and repository local configuration.

## Output of command with `--verbose`

```
$ chezmoi command --verbose
```
`chezmoi: unknown command "command" for "chezmoi"`

If you mean `chezmoi --version`:

`chezmoi version v2.0.15, commit d02e707857d9b7365bb3c1b18a849362876efa88, built at 2021-06-17T20:42:01Z, built by goreleaser`

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```
```
RESULT    CHECK                MESSAGE
ok        version              v2.0.15, commit d02e707857d9b7365bb3c1b18a849362876efa88, built at 2021-06-17T20:42:01Z, built by goreleaser
ok        os-arch              linux/amd64 (Ubuntu/20.04.2 LTS (Focal Fossa))
ok        config-file          /home/zybortd/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /home/zybortd/pCloudDrive/Dev/dotfiles is a directory
warning   suspicious-entries   found suspicious entries in /home/zybortd/pCloudDrive/Dev/dotfiles: /home/zybortd/pCloudDrive/Dev/dotfiles/.chezmoi.toml.tmpl
ok        dest-dir             /home/zybortd is a directory
ok        shell                found /bin/zsh
ok        editor               found /usr/bin/vim
ok        git-cli              found /usr/bin/git, version 2.25.1
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.19
info      1password-cli        op not found in $PATH
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

## Additional context

None.

**Comment by matrixik** [comment]
Sorry, turns out I have set up `GIT_AUTHOR_EMAIL` environment variable and it's taking precedence over local repository config...

**Comment by twpayne** [comment]
Thank you very much for the further investigation and reporting here :)
