### ISSUE TITLE
chezmoi does not handle files that conflict with its naming scheme

### ISSUE THREAD

**Issue by diegobernardes** [twpayne/chezmoi#1277]
## What exactly are you trying to do?
I'm trying to use chezmoi to manage some vim plugins. The problem is that one of the plugins has a [file](https://github.com/nvim-lua/plenary.nvim/blob/master/scratch/run_tester.lua) that starts with `run_` and chezmoi is trying to execute it which causes the problem.

It is possible to skip the execution but still copy/manage the file?

## Where else have you checked for solutions?
* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`
```
➜ chezmoi apply --verbose | pbcopy
diff --git a/.local/share/nvim/site/pack/plugins/start/plenary.nvim/scratch/tester.lua b/.local/share/nvim/site/pack/plugins/start/plenary.nvim/scratch/tester.lua
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..ef468ded10b995eb4ac5b11cc5c5a7b255e49a88 100755
--- a/.local/share/nvim/site/pack/plugins/start/plenary.nvim/scratch/tester.lua
+++ b/.local/share/nvim/site/pack/plugins/start/plenary.nvim/scratch/tester.lua
@@ -0,0 +1,16 @@
+
+local lu = require("plenary.luaunit")
+local test_harness = require("plenary.test_harness")
+
+require("tests.plenary.path_spec")
+
+-- lu.LuaUnit.run("./tests/plenary/path_spec.lua")
+-- lu.LuaUnit.run({"TestPath"})
+
+test_harness:run(0, 0, "TestPath")
+
+
+[[
+lua require("plenary.test_harness"):test_directory("luaunit", "./tests/plenary/lu/")
+lua require("plenary.test_harness"):test_directory("busted", "./tests/plenary/bu/")
+]]
chezmoi: fork/exec /var/folders/0m/_pktt2gj0sjcmjt7dhv7gc442j_tbb/T/2618442662.tester.lua: exec format error
```

## Output of `chezmoi doctor`

```
➜ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.0.16, commit 745e198f0477cfee4a7b4bcfc385d51cd80806a0, built at 2021-06-28T00:22:07Z, built by homebrew
ok        os-arch              darwin/amd64
...
```

**Comment by twpayne** [comment]
Thanks for reporting this! I've been waiting three years for a file managed with chezmoi to conflict with chezmoi's file name attributes, and am glad to finally have found one in the wild!

The bad news is that chezmoi version 2.0.16 can't handle this at the moment, but the good news is that `plenary.nvim`'s `scratch/run_tester.lua` doesn't seem to be necessary for the plugin to function, so you can delete it in your case.

In the medium term, I'll come up with a fix. I have a good idea what the fix will look like.

Upgrading this to `bug`.

**Comment by diegobernardes** [comment]
@twpayne, thanks for the fix. The solution works well for owned files but not so well for third-party ones. For example, in my case I don't want to change the file name from `run_tester.lua` to `literal_run_tester.lua` because it's inside a git submodule and would make my upgrade path harder as I would have to remove my changes, update the repository and add the changes again.

What do you think of adding a second layer of attributes on a file like `.chezmoiattributes`? It could be something like this:
```
literal /.local/share/nvim/site/pack/plugins/start/plenary.nvim/scratch/run_tester.lua
```

**Comment by twpayne** [comment]
Rather than using git submodules in your home directory, I would recommend using [`chezmoi import`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#import-filename) to import tarballs into subdirectories, something like:

```console
$ wget ​https://github.com/nvim-lua/plenary.nvim/archive/master.tar.gz
$ chezmoi  import  --strip-components=1 --destination=$HOME/.local/share/nvim/site/pack/plugins/start/plenary.vim master.tar.gz
```

> What do you think of adding a second layer of attributes on a file like `.chezmoiattributes`?

This would violate the [DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and make the source state ambiguous.
