### ISSUE TITLE
support account choice for 1password

### ISSUE THREAD

**Issue by pvinis** [twpayne/chezmoi#1278]
## Is your feature request related to a problem? Please describe.

I use two accounts on 1P, one personal and one from work. When I do `export AWS_ACCESS_KEY_ID="{{ (onepassword "aws credentials").details."access key id" }}"`, chezmoi (and op) don't know where to find that. If I and randomly lastly signed in the right account, it works, but if not, it doesn't.

On the terminal I can do `op get item "aws credentials" --account my` and it will show that there is no item like that. Then doing `op get item "aws credentials" --account team_account` shows me the item.

## Describe the solution you'd like

I would like a way to do something like `{{ (onepassword "aws credential" "team_account").details.whatever }}` and get the right item.

The problem is that now there is a way to add a second argument and it is used for `vault`. I wonder how we could add a way to select an account. I'm happy to implement it myself, but maybe @twpayne you have a good idea for the "API" here?

**Comment by pvinis** [comment]
I'll try to implement it with still 2 args, and if the second arg starts with `:`, it will signify an account. If you have a better idea, let me know.

**Comment by twpayne** [comment]
Any reason not to add the account as a third argument? The vault can always be empty. It'll be a bit ugly, but passable:

    export AWS_ACCESS_KEY_ID="{{ (onepassword "aws credentials" "" "team_account").details."access key id" }}"

Alternatively, does 1Password have a mechanism for sharing secrets between accounts? If so, consider sharing some secrets from your personal account to your work account, and then only use your personal account on personal machines and only the work account on work machines.

**Comment by pvinis** [comment]
It might have a sharing way, but def I don't want to suggest to me or anyone, to share work stuff with their personal stuff 😬.

I guess an empty vault (second arg) works. I will change it to that.

**Comment by twpayne** [comment]
Fixed by @pvinis in #1280.
