### ISSUE TITLE
access a field with space

### ISSUE THREAD

**Issue by pvinis** [twpayne/chezmoi#1279]
## What exactly are you trying to do?

Trying to use the value of a field like `key id` from 1password.

Something like `"{{ (onepassword "some-uuid").details."key id" }}"`. Is that possible in some way?

## What have you tried so far?

I tried the above, because `jq` supports this, but it didn't work for chezmoi.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

## Output of `chezmoi doctor`

```
RESULT    CHECK                MESSAGE
ok        version              v2.0.16, commit 745e198f0477cfee4a7b4bcfc385d51cd80806a0, built at 2021-06-28T00:22:07Z, built by homebrew
ok        os-arch              darwin/amd64
ok        config-file          /Users/pavlos/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           /Users/pavlos/.local/share/chezmoi is a directory
warning   suspicious-entries   found suspicious entries in /Users/pavlos/.local/share/chezmoi: /Users/pavlos/.local/share/chezmoi/.chezmoiignore
ok        dest-dir             /Users/pavlos is a directory
ok        shell                found /usr/local/bin/zsh
ok        editor               found /usr/bin/vi
ok        git-cli              found /usr/local/bin/git, version 2.32.0
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/local/bin/gpg, version 2.3.1
ok        1password-cli        found /usr/local/bin/op, version 1.10.3
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set

```

**Comment by twpayne** [comment]
I think you need to use `text/template`'s `item` function, something like:

    "{{ item (onepassword "some-uuid").details "key id" }}"

**Comment by pvinis** [comment]
Hm, I am doing
```
export AWS_ACCESS_KEY_ID={{ item (onepassword "aws credentials" "" "team_artsy").details "access key id" }}
```
and getting
```
chezmoi: template: private_dot_zshrc_private_artsy.tmpl:1: function "item" not defined
```

Also tried with
```
export AWS_ACCESS_KEY_ID={{ item (onepasswordDetailsFields "aws credentials" "" "team_artsy") "access key id" }}
```
but same error.

**Comment by twpayne** [comment]
s/item/index/

sorry!

**Comment by pvinis** [comment]
I was just checking the docs here https://golang.org/pkg/text/template/ and was looking at index hehe. nice.

**Comment by pvinis** [comment]
I had to go with
```
export AWS_ACCESS_KEY_ID={{ range (index (onepassword "aws credentials" "" "team_artsy").details.sections 1 "fields") -}}
  {{ if eq .t "access key id" -}}
    {{ .v }}
  {{- end }}
{{- end }
```
in the end. 1p has some weird structure for that item.. 🤷.

But it worked. Thanks!
