### ISSUE TITLE
Concerns with adding metadata to filename

### ISSUE THREAD

**Issue by seagoj** [twpayne/chezmoi#1285]
Hello,

First off I love the project and I'd really like to move from a tool I wrote myself (cobbled together git, stow, gitcrypt and gpg), but I had some concerns about adding the metadata to the file name that I was hoping to hear your thoughts on.

Metadata in the filename and avoiding symlinks allows for the decoupling of a given computer's configuration from the repo, but it couples your dotfiles repo to chezmoi since your settings now need to be interpreted by chezmoi in order to receive the correct filenames and permissions. It also seems to complicate the chezmoi implementation by adding the need to translate filenames and permissions which could just come for free.

Anyway, I'm excited about the project and just adding food for thought. Thanks!

**Comment by twpayne** [comment]
Thanks for the question!

> Metadata in the filename and avoiding symlinks allows for the decoupling of a given computer's configuration from the repo, but it couples your dotfiles repo to chezmoi since your settings now need to be interpreted by chezmoi in order to receive the correct filenames and permissions.

Indeed, chezmoi is needed to interpret your settings, but this is no different from any other non-trivial dotfile manager that uses a configuration file. The dotfile manager is still needed to interpret your settings/configuration file.

That said, chezmoi is particularly transparent here:

* chezmoi creates your dotfiles just as if you were not using a dotfile manager at all. Your dotfiles are regular files, directories, and symlinks. If you want to use a different dotfile manager you can run [`chezmoi purge`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#purge) to delete all traces of chezmoi and then use whatever mechanism your new dotfile manager has to add your dotfiles to your new system.
* chezmoi has a [`chezmoi archive`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#archive) command that generates a tarball of your dotfiles.
* chezmoi has a [`chezmoi dump`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#dump-target) command that dumps the interpreted (target) state in a machine-readable form, so you can write scripts around chezmoi.

>  It also seems to complicate the chezmoi implementation by adding the need to translate filenames and permissions which could just come for free.

How would permissions "just come for free"? Remember that chezmoi supports Linux, macOS, FreeBSD, and Windows as equal first class platforms, and Windows does not have UNIX-style file permissions.

You might also be interested in the documentation on ["Why doesn't chezmoi use symlinks like GNU Stow?"](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#why-doesnt-chezmoi-use-symlinks-like-gnu-stow),
["Can I change how chezmoi's source state is represented on disk?"](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#can-i-change-how-chezmois-source-state-is-represented-on-disk), and ["How to migrate away from chezmoi"](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#migrate-away-from-chezmoi).

**Comment by seagoj** [comment]
I agree the actual config in use is transparent in that chezmoi is totally unrequired for day to day use. My point was that the source of truth (the repo) gets coupled to chezmoi in a way that's hard to undo.

The windows use case is admittedly not something I was considering, and this maybe just unfamiliarity, but I can only think of a few programs (git, ssh, gpg) that use dotfiles in actual Windows (not WSL). That use case shouldn't be abandoned, but the current implementation is a pretty large concession, in my opinion.

**Comment by twpayne** [comment]
> My point was that the source of truth (the repo) gets coupled to chezmoi in a way that's hard to undo.

If you run `chezmoi archive` you get all of your dotfiles - including your scripts - in a convenient form. You can replace the contents of your dotfiles repo with the contents of the archive and you've effectively immediately migrated away from chezmoi.

> the current implementation is a pretty large concession, in my opinion.

That's OK. The design choices are there for good reason, and you're free to use whatever dotfile manager you want.

**Comment by seagoj** [comment]
Ok, thanks for your time.

**Comment by twpayne** [comment]
For what it's worth chezmoi also has a [`chezmoi import`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#import-filename) command that allows you to import an existing archive. So, if you have an existing dotfiles repo, say https://github.com/seagoj/dotfiles, you can import it with:

```console
$ curl -sLo https://github.com/seagoj/dotfiles/archive/master.tar.gz
$ chezmoi import --destination=$HOME master.tar.gz
```

⚠️ above code is untested, but something like it should work (or reveal bugs in chezmoi).

**Comment by twpayne** [comment]
Note that this won't work as written - https://github.com/seagoj/dotfiles also mangles file and directory names by removing the leading `.`  from them.

**Comment by twpayne** [comment]
Thanks again for asking the question - please re-open this issue if needed.
