### ISSUE TITLE
How to use a same entry on both ignore and remove files?

### ISSUE THREAD

**Issue by diegobernardes** [twpayne/chezmoi#1287]
## What exactly are you trying to do?
I want to establish some profiles for my machines like for example work and personal. At `chezmoi cd` I have two files:
```
dot_gitconfig-work
dot_gitconfig-personal
```

I can selectively copy the files using the `.chezmoiignore` like this:
```
{{ if not .environment.work }}
.gitconfig-work
{{ end }}

{{ if not .environment.personal }}
.gitconfig-personal
{{ end }}
```

This works fine. But what if I would like to revert the changes? Like for example on my personal machine, I remove the work profile and on the work machine, I remove the personal profile? I would have to use the `.chezmoiremove` to add entries and remove the files right? Well, it does not work because they're listed at the `.chezmoiignore` so they get ignored on the `.chezmoiremove`. I tried to remove them from the `.chezmoiignore` and add just on the `.chezmoiremove` but this gives me an error:
```
➜  chezmoi apply --remove
chezmoi: .gitconfig-work: duplicate source state entries (, dot_gitconfig-work)
```

There is any way to work around this problem that does not involve custom shell scripts?

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [] Other, please give details.

## Output of `chezmoi doctor`
```
➜ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.1.0, commit 509bda706a9046c36d14fc84ba93d4dc975a7171, built at 2021-07-02T23:46:40Z, built by homebrew
ok        os-arch              darwin/amd64
```

**Comment by twpayne** [comment]
This is what templates are for. Create `dot_gitconfig.tmpl` in your source directory containing:

```
{{ if .environment.work }}
# contents of work .gitconfig
{{ end }}
{{ if .environment.personal }}
# contents of personal .gitconfig
{{ end }}
```

Also see [this how to entry](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-completely-different-dotfiles-on-different-machines).

Please re-open if needed.
