### ISSUE TITLE
`overwrite_` prefix

### ISSUE THREAD

**Issue by fredericrous** [twpayne/chezmoi#1295]
## Is your feature request related to a problem? Please describe.

I have git submodules that live in my chezmoi repository. Every time the submodule changes, `chezmoi update` retrieves the new file updates, which is awesome. However when I `apply` the changes, it asks me file by file if I want to do an overwrite. Indeed the files changed within the submodule, there is a difference between the files on my system and the ones just fetched.

## Describe the solution you'd like

 I would like chezmoi not to prompt me and overwrite these files every time.
Could an `overwrite_` prefix or something similar be implemented as a directory prefix in order to force the overwrite of the files in the folder?

## Describe alternatives you've considered

chezmoi could ask globally for submodules if we want to overwrite the whole folder or go through the file by file process. In my opinion adding a prefix to the directory is simpler

## Additional context

Example of submodule living in chezmoi repository:
https://github.com/fredericrous/dotfiles/tree/main/private_dot_config/git
if the repository git-templates is updated, when I do an `apply` I get prompted for each files that has changed on the submodule.

**Comment by twpayne** [comment]
> However when I `apply` the changes, it asks me file by file if I want to do an overwrite

Hmm, this sounds like a bug in chezmoi. Could you re-run the command with the `--debug` flag and post the output here?

> Example of submodule living in chezmoi repository:

For the use of git submodules to include subdirectories in the dotfiles directory, this is a larger topic and chezmoi can definitely do better here. I'll open an issue to track this.

**Comment by fredericrous** [comment]
I re-executed with `--debug`, and I chose to do a diff this time. I usually don't because I know I want the update...and it struck me: I have a script [run_after_git-hooks-setup.zsh](https://github.com/fredericrous/dotfiles/blob/31e486d4dbc0447c2e739d16f88d33f3eca88245/private_dot_config/git/run_after_git-hooks-setup.zsh) that change the permissions on the files.
I created a second script [run_before_git-hooks-chmod-x.zsh](https://github.com/fredericrous/dotfiles/blob/main/private_dot_config/git/run_before_git-hooks-chmod-x.zsh).
I updated the submodule.
I did a chezmoi update. It triggered the apply after fetching the submodules.
Chezmoi did not pick a difference between the content of the files. It did not pick differences of permissions either this time because there were not thanks to the run_before script.
Unless you find the `overwrite_` idea nice and you would like to keep this issue open, I'm good to close it.
A note though: it would be a "nice to have" if chezmoi could remember the permissions when copying from a submodule. Indeed I can see in the fetched repository's folder that the permissions are correct

**Comment by twpayne** [comment]
Generally speaking, I think chezmoi can do a better job of importing dotfiles from external sources, e.g. git submodules and tarballs. I'm currently sketching out the design, but this should get better in the future.

In the meantime, I'll close this issue. Thanks again for opening it!
