### ISSUE TITLE
Cannot add file from subdirectory

### ISSUE THREAD

**Issue by iilyak** [twpayne/chezmoi#13]
I am getting `outside target directory` error. I tried different formats:
- `./chezmoi add  .config/micro/settings.json`
- `./chezmoi add  `pwd`/.config/micro/settings.json`
- `./chezmoi add  /home/jenkins/.config/micro/settings.json`
- `./chezmoi add  ~/.config/micro/settings.json`
  
```
./chezmoi add  /home/jenkins/.config/micro/settings.json
Error: .config/micro: outside target directory
Usage:
  chezmoi add [flags]

Flags:
  -h, --help        help for add
  -r, --recursive   recurse in to subdirectories
  -T, --template    add files as templates

Global Flags:
  -c, --config string       config file (default "/home/jenkins/.chezmoi.yaml")
  -n, --dry-run             dry run
  -s, --source string       source directory (default "/home/jenkins/.chezmoi")
      --source-vcs string   source version control system command (default "git")
  -t, --target string       target directory (default "/home/jenkins")
  -u, --umask int           umask (default 18)
  -v, --verbose             verbose
```

**Comment by twpayne** [comment]
Thanks for the bug report! I probably broke this yesterday with commit f2e097a2e9fe67bce80ed4afbcbdc59db4f3e5b1. Will investigate.

**Comment by twpayne** [comment]
Thanks for reporting the issue @iilyak. It should now be fixed. I've also added some tests to ensure that this bug does not return in the future.
