### ISSUE TITLE
Can filenames be templated?

### ISSUE THREAD

**Issue by kasarpolis** [twpayne/chezmoi#1300]
## What exactly are you trying to do?

Given a list of team names I'd like to generate an AWS config file for each team.

### For example:
If I have teamA and teamB I want to produce 2 files.

~/.aws/teamA.config
~/.aws/teamB.config

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [X] Other, please give details. Searched past issues.

**Comment by twpayne** [comment]
Thanks for opening this issue :)

Currently, chezmoi does not support templated filenames.

Note that it does support [templates for creating similar files](https://github.com/twpayne/chezmoi/blob/master/docs/TEMPLATING.md#using-chezmoitemplates-for-creating-similar-files), which might be helpful for your use case.

Another option would be to use a script which writes the`~/.aws/team*.config` files to your home directory.

**Comment by kasarpolis** [comment]
Thank you for creating this tool!  We're using it to bootstrap newly hired engineers workstations and it's saves a ton of time and headaches.

**Comment by twpayne** [comment]
Thank you for your kind words, and very happy to hear that chezmoi is helpful. Please re-open this issue if needed.
