### ISSUE TITLE
Sourcehut Username Integration

### ISSUE THREAD

**Issue by jgarte** [twpayne/chezmoi#1317]
I'd like to request the feature to [install on a new machine](https://www.chezmoi.io/#chezmoi) by specifying my sourcehut username like so:

 ```sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply <sourcehut-username>```

concrete example:

```sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply ~jgart```

If someone would like to give me any tips on where to get started I'd appreciat that. Otherwise I'll dig into the source soon to see what I can do.

all best

**Comment by twpayne** [comment]
This is already supported. The [patterns supported by `chezmoi init`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#init-repo) include

| Pattern            | HTTPS Repo                             | SSH repo                           |
| ------------------ | -------------------------------------- | ---------------------------------- |
| `~sr.ht/user`      | `https://git.sr.ht/~user/dotfiles`     | `git@git.sr.ht:~user/dotfiles.git` |
| `~sr.ht/user/repo` | `https://git.sr.ht/~user/repo`         | `git@git.sr.ht:~/user/repo.git`    |

So you can do

```console
$ sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply ~sr.ht/jgart
```

or

```console
$ sh -c "$(curl -fsLS git.io/chezmoi)" -- init --apply ~sr.ht/jgart/dots
```

depending on what your dotfiles repo is called.

For what it's worth, the patterns for guessing full repo paths are defined [here](https://github.com/twpayne/chezmoi/blob/master/internal/cmd/initcmd.go#L38).

Hope this helps, please re-open if needed.
