### ISSUE TITLE
GPG Encryption: Encryption suffix confuses $EDITOR

### ISSUE THREAD

**Issue by azmodude** [twpayne/chezmoi#1319]
## What exactly are you trying to do?
Editing an encrypted file with encryption suffix set using `chezmoi edit`.

## What have you tried so far?
Editing the file.

## Where else have you checked for solutions?

* [X] I have_ read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.1.2, commit a3fb755a88315bbdecedba3d849324752989400d, built at 2021-07-14T20:07:22Z, built by goreleaser
ok       os-arch              linux/amd64 (Fedora/34 (Thirty Four))
ok       config-file          /home/azmo/.config/chezmoi/chezmoi.toml is a file
ok       source-dir           /home/azmo/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /home/azmo/.local/share/chezmoi
ok       dest-dir             /home/azmo is a directory
ok       shell                found /bin/zsh
ok       editor               found /usr/bin/nvim
ok       git-cli              found /usr/bin/git, version 2.31.1
ok       merge-cli            found /usr/bin/nvim
ok       age-cli              age not found in $PATH
ok       gnupg-cli            found /usr/bin/gpg, version 2.2.27
ok       1password-cli        found /home/azmo/bin/op, version 1.11.0
info     bitwarden-cli        bw not found in $PATH
info     gopass-cli           gopass not found in $PATH
ok       keepassxc-cli        found /usr/bin/keepassxc-cli, version 2.6.6
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
ok       pass-cli             found /usr/bin/pass, version 1.7.3
info     vault-cli            vault not found in $PATH
info     secret-cli           not set
```

## Additional context

Pull Request https://github.com/twpayne/chezmoi/pull/1034 added the optional encryption suffix, which I like a lot for editing encrypted files directly in chezmoi's repository as vim with vim-gnupg and emacs with EPA are able to decrypt and re-encrypt the files directly.

Maybe I am missing something in my editors' configuration, but when trying to edit encrypted files with an `.asc` (or `.gpg` in my case) suffix, vim and emacs get kind of confused. vim tries to re-encrypt the file on save (since the .gpg suffix is there) and EPA falls flat on its face on invocation as it tries to decrypt the incoming data from chezmoi, which as I understand it, is already decrypted when it reaches the editor. Its error message on the console is 

`*ERROR*: Opening input file: Can't decrypt, No data (no armored data); No data
(expected a packet but did not found one); Exit`

Wouldn't it be better/possible to strip the encryption suffix when editing encrypted files with `chezmoi edit` so any editor receiving the data doesn't get confused (or needs to be tweaked) when it sees the file suffix - as technically the data it sees isn't really GPG encrypted anymore?

Thanks!

## Screenshots
![chezmoi_encrypted_vim](https://user-images.githubusercontent.com/688576/126973260-4939e047-0c8c-46fa-bc88-f2642cec64c0.png)

![chezmoi_encrypted_epa](https://user-images.githubusercontent.com/688576/126973101-9d5bf820-80ae-427b-af9d-f4ccfeba8bd0.png)

**Comment by twpayne** [comment]
Thank you for the very clear and well thought through analysis and issue description!

> Wouldn't it be better/possible to strip the encryption suffix when editing encrypted files with `chezmoi edit` so any editor receiving the data doesn't get confused (or needs to be tweaked) when it sees the file suffix - as technically the data it sees isn't really GPG encrypted anymore?

Yes. Totally agree. #1320 should fix this.

If you're able to test #1320 then please say. Otherwise, I should be able to test it in the next few days.

**Comment by azmodude** [comment]
Just tested #1320 on a few files with both emacs and vim and it works beautifully, fixing my issues. Thanks a lot for your great work!
