### ISSUE TITLE
Slashes and Backslashes on Windows make symlinks a problem

### ISSUE THREAD

**Issue by derphilipp** [twpayne/chezmoi#1329]
## Describe the bug

Generated paths (via template) and used paths for symlinks on windows differ in `/` and `\`, leading to constant "modified" state.

## To reproduce

Create symlink to directory, e.g. 
Filename: `.\AppData\Local\symlink_nvim.tmpl`
Content:
```
{{ joinPath .chezmoi.homeDir ".config/nvim" }}
```

## Expected behavior

- ✅ A symlink is created 
- ✅ The symlink to the directory works
- ❌ Chezmoi state delievers consistent result, not complaining about changes (after applying it once)

## How does it show?
- Running `chezmoi status` ALWAYS results in chages:
```
MM AppData/Local/nvim
```
After applying this stays that way. So let's look into the "changes":

- `chezmoi apply`
```
AppData/Local/nvim has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]?
```

Let's see what actually changed, using diff:

```diff
+ C:/Users/z003hemr/.config/nvim
- C:\Users\z003hemr\.config\nvim
```
Oh no! I could change the `.config/nvim` part of it, but not the used `.chezmoi.homeDir` variable of it.

## Background / What do I want to achieve / Workarounds

Some applications have different config file paths on windows. I therefore want them to point to the very same paths as on non-windows systems using symlinks. This does work for the applications I use (in this example: nvim).
Workarounds like including different files/paths do not work for all applications.

**Comment by bradenhilton** [comment]
@twpayne Perhaps unrelated, but for me chezmoi treats all symlinks created using `joinPath` as modified (on every `diff`/`apply` etc.) on Windows (can't test other OSes at the moment).

<chezmoi_source_dir>/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/symlink_settings.json:
```
{{- joinPath .chezmoi.sourceDir "symlinks" "Windows Terminal" "settings.json" -}}
```

(after `chezmoi apply`):

```
> chezmoi diff
```

```diff
diff --git a/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json b/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
deleted file mode 100666
index ad86cfcf9904798dabf838c2eb82408516514ddb..0000000000000000000000000000000000000000
--- a/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
+++ /dev/null
@@ -1,292 +0,0 @@
-<every line in settings.json removed...>
diff --git a/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json b/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
old mode 100666
new mode 120000
index ad86cfcf9904798dabf838c2eb82408516514ddb..0314c2787356e78f4e37dcaf2f85faf01531f5bc
--- a/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
+++ b/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json
@@ -1,292 +1 @@
-<every line in settings.json removed...>
+C:\Users\Braden\.local\share\chezmoi\symlinks\Windows Terminal\settings.json
```

The symlink does work, but if I change the path to a string (only tested with forward slashes at the moment), the repetitive overwrite prompt does not appear.

<chezmoi_source_dir>/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/symlink_settings.json:
```
{{- .chezmoi.sourceDir -}}/symlinks/Windows Terminal/settings.json
```

(after `chezmoi apply`):

```
> chezmoi diff
```

```diff
(nothing)
```

Again, not sure if related so I'm happy to open a separate issue if you think that would be appropriate.

**Comment by twpayne** [comment]
Thank you very much for this information @bradenhilton, I think it is related.

> Perhaps unrelated, but for me chezmoi treats all symlinks created using `joinPath` as modified (on every `diff`/`apply` etc.) on Windows (can't test other OSes at the moment).

I think there's a bug in chezmoi on Windows here, specifically:
* Symlinks created by chezmoi can have a mix of forward and backward slashes.
* chezmoi stores the symlink state with the mix of slashes.
* When chezmoi reads the actual symlink it converts it to a normalized internal format that only uses forward slashes.
* This means that the symlink state and actual state never match, hence chezmoi thinks that the symlink has been modified.

Fix coming up...
