### ISSUE TITLE
.chezmoidata not entirely clear

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1333]
## What exactly are you trying to do?

Split up my secret data, and not store all my data in `.config/chezmoi/chezmoi.toml`

## What have you tried so far?

I've tried creating `appname.chezmoidata.toml`  files and using `chezmoi add` to add them to the source state, but chezmoi still doesn't seem to know about them. I tried messing about with the config option `data` https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#configuration-file but that wasn't obvious.

I also don't want my chezmoidata committed to the git repo, i back this up manually outside of source control.

## Where else have you checked for solutions?

Yes, specifically https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoidataformat

https://github.com/twpayne/chezmoi/blob/master/docs/TEMPLATING.md#template-data

## Additional context

Looks like it also can take .json files which is good because I have a lot of .json data files I had been using with [yadm](https://github.com/TheLocehiliosan/yadm/) and [j2cli](https://github.com/kolypto/j2cli).

For example with SSH I have:

`.local/template_data/private/Workstation/ssh/hosts.json`

Note that in this case "Workstation" was the "class", on my server environment I call it "Server" and it has different data files available. I'm not sure how I might best achieve this with Chezmoi.

Inside hosts.json is an object with all  my hosts. In the template file I iterate through the json object putting the data in ~/.ssh/config

```json
 "ssh_hosts": [
    {
      "Host": "",
      "Comment": "",
      "Hostname": "",
      "Port": "",
      "User": "",
      "HostKeyAlgorithms": "",
      "KexAlgorithms": "",
      "Ciphers": "",
      "MACs": "",
      "IdentitiesOnly": "",
      "IdentityAgent": "",
      "PasswordAuthentication": "",
      "IdentifyFile": ""
    },....
```

Main reason I'm seriously considering chezmoi over yadm:

- the requirement on bash, and if I use templating python as well.
- envtpl isn't maintained, and I think j2cli might be receiving regular updates either
- I think the population of `chezmoi data`, is better, Yadm tries to get this information by using `lsb_release` and looking at `/etc/os-release`, which means there are things that need to be installed first, one of the machines I want to use chezmoi on I don't have root.
- I like the idea of a single binary, for `chezmoi`, as I can continue to use some simple sh scripts and `jq` where I am manipulating the json objects prior to feeding them to chezmoi. (i've done that in some cases with Yadm).  The case I am thinking of checks whether I am running wayland (sway) or x11 (i3wm) and modified the data in the object accordingly.
- Not litter template files throughout my home directory

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
chezmoi will only read data from a single configuration file, which must be called `chezmoi.<format>`. It uses only the first configuration file that it finds. If you want to use multiple configuration files then you will have to write your own scripts to combine them into a single file. The `--config` option to chezmoi might be helpful for testing here.

**Comment by twpayne** [comment]
An extra thought: #1334 makes it possible for chezmoi to read its config from the standard input, so you can use a shell script or function to wrap your config file generation, something like:

```bash
func my-chezmoi() {
    generate-chezmoi-config *.json | chezmoi --config=/dev/stdin --config-format=json $*
 }
```

You can then use `my-chezmoi` just as you would normally use chezmoi, e.g.

```console
$ my-chezmoi apply
```

and you don't need to run any manual steps when your input `*.json` files change as the config file is assembled when needed.

**Comment by slurikadre** [comment]
Thanks for the answer! So I'll just repeat this so I think I understand correctly.

- The `generate-chezmoi-config()` function joins all the json objects together into a single file. I guess I'd still need `jq` to parse that?

- The `my-chezmoi()` function then feeds that total object to chezmoi via stdin.

In the way I had done this in the past was I would run `yadm bootstrap`, which would call a function like so:

```bash
template_data_path="$HOME/.local/template_data/private/{{ YADM_CLASS }}"
ssh_data_path="ssh/hosts##o.{{ YADM_OS }},u.{{ YADM_USER }}.json"
ssh_config "$template_data_path" "$ssh_data_path"
```

`ssh_config` was a simple function like:

```bash
ssh_config() {
    printf "Writing hosts into .ssh/config\n"
    j2 <"$1/$2" -f json -o "$HOME"/.ssh/config "$HOME"/.ssh/config.j2
}
```

So, thinking about this the performance wise, the I/O for one large json object is probably much quicker than opening/closing file handles for each script.

In cases like `ssh_config` where I am simply using a json data object and writing a file with a template I should need no code?

In some other cases I might want to run a pre-script before the `generate-chezmoi-config()` is run.

I'll give some examples, bear with me.. :) and if you can think of improvements, or features that chezmoi has that I might make use of that would be relevant, don't hesitate to comment.

Would chezmoi's [run_once](https://www.chezmoi.io/docs/how-to/#use-scripts-to-perform-actions) scripts be the right feature for this? 

Some of my usecases:

1. This "recipe" will make vim download plugins if the `submodule_init_vim` variable returns `true` in a global "config". It's kind of how I hacked together a way for a global state in `yadm`

```bash
initiate_vim() {
    mkdir -p "$XDG_CONFIG_HOME"/nvim/autoload/
    ln -sf "$XDG_CONFIG_HOME"/nvim/vim-plug/plug.vim "$XDG_CONFIG_HOME"/nvim/autoload/
    submodule_init_vim=$(jq '.submodule_init_vim' "$1")
    if [ "$submodule_init_vim" = "true" ]; then
        printf "Initializing VimPlug installation\n"
        git --git-dir="$XDG_CONFIG_HOME"/yadm/repo.git/modules/.config/nvim/vim-plug \
            --work-tree="$XDG_CONFIG_HOME"/nvim/vim-plug checkout
        ln -sf "$XDG_CONFIG_HOME"/nvim/vim-plug/plug.vim "$XDG_CONFIG_HOME"/nvim/autoload/plug.vim
        nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    elif [ "$submodule_init_vim" = "false" ]; then
        printf "Not initalizing submodules for vim\n"
    fi
}
```

2. This example which sees if I am running Wayland or X11 and if the configuration is being run in a virtual machine.

It sets the DPI to a different value if running in X11 (i3wm) because X11 has no support for "scaling" on different monitors. If Wayland is running, then the normal DPI can be used. (It was needed for mixed monitor support https://blog.summercat.com/configuring-mixed-dpi-monitors-with-xrandr.html).

```bash
    printf "Setting DPI in .Xresources\n"
    if [ -z "$WAYLAND_DISPLAY" ]; then
    printf "X is running\n"
        jq -r --argjson vm "false" '{ vm: $vm, dpi: .Workstation.hostname.dpi.dpi_x } | { opt: . }' "$1/$2" |
            j2 -f json -o "$HOME"/.Xresources "$HOME"/.Xresources.j2
    elif [ -n "$WAYLAND_DISPLAY" ]; then
    printf "Wayland is running\n"
        jq -r --argjson vm "false" '{ vm: $vm, dpi: .Workstation.hostname.dpi.dpi_wayland } | { opt: . }' "$1/$2" |
            j2 -f json -o "$HOME"/.Xresources "$HOME"/.Xresources.j2
    fi
```

3. This third example builds my PATH from a json array. It checks to see whether Ruby is installed and if it is it inserts the return value of `ruby -e 'puts Gem.user_dir'` the array, before the array is passed to the template:

```bash
shellrc() {
    printf "Configuring shell, .zshrc, .bashrc\n"
    if hash ruby 2>/dev/null; then
        printf "Checking if ruby is installed\n"
            jq -r --arg key "\$(ruby -e 'puts Gem.user_dir')/bin" '.paths += [$key]' "$1/$2" |
        j2 -f json -o "$HOME"/.bashrc "$HOME"/.bashrc.j2
        printf "Writing .zshrc\n"
        jq -r --arg key "\$(ruby -e 'puts Gem.user_dir')/bin" '.paths += [$key]' "$1/$2" |
            j2 -f json -o "$HOME"/.zshrc "$HOME"/.zshrc.j2

    else
        printf "No, ruby installed proceed as normal\n"
        j2 <"$1/$2" -f json -o "$HOME"/.zshrc "$HOME"/.zshrc.j2
        j2 <"$1/$2" -f json -o "$HOME"/.bashrc "$HOME"/.bashrc.j2
    fi
}
```

**Comment by twpayne** [comment]
> if you can think of improvements, or features that chezmoi has that I might make use of that would be relevant, don't hesitate to comment.

I think there are relevant features :) chezmoi already includes support for structured personalized data in its configuration file and already supports templating. So I don't think that JSON files, `jq`, or `j2cli` are needed, and indeed everything above can be done comfortably using chezmoi's existing functionality.

> I also don't want my chezmoidata committed to the git repo, i back this up manually outside of source control.

In this case, reframe the thinking to be "I don't want my chezmoi config file to be committed to the git repo, i back this up manually outside of source control.", i.e. treat your chezmoi config file the same way you previous treated your JSON files.

> 1. This "recipe" will make vim download plugins if the submodule_init_vim variable returns true in a global "config". It's kind of how I hacked together a way for a global state in yadm

chezmoi's `run_once_` scripts are designed for exactly this. You only need to put the initialization code in a `run_once_` script, chezmoi will ensure that the script is only run once (based on the SHA256 of the script's contents).

> 2. This example which sees if I am running Wayland or X11 and if the configuration is being run in a virtual machine.

This can be done with templates. In this specific case I would use a boolean `vm` and `wayland` variables in chezmoi's config file and make `.Xresources` a template. I would not rely on the `$WAYLAND_DISPLAY` environment variable as its presence or otherwise will depend on how you log into the machine.

> 3. This third example builds my PATH from a json array. It checks to see whether Ruby is installed and if it is it inserts the return value of ruby -e 'puts Gem.user_dir' the array, before the array is passed to the template:

This can also be a template, using the `lookPath` template function to detect if `ruby` is in `$PATH`.

**Comment by slurikadre** [comment]
> makes it possible for chezmoi to read its config from the standard input, so you can use a shell script or function to wrap your config file generation, something like:
> 
> ```shell
> func my-chezmoi() {
>     generate-chezmoi-config *.json | chezmoi --config=/dev/stdin --config-format=json $*
>  }
> ```

This looks to be pseudo/sh code that I would have in the wrapping function in my path? Or is this able to somehow go in chezmoi's config?

> chezmoi already includes support for structured personalized data in its configuration file and already supports templating.

Isn't `generate-chezmoi-config()` function you mention there a shell function you've created?. This looks to be in the shell wrapper script so wouldn't I need to do `jq -s '.[]' *.json`? How would I write `generate-chezmoi-config()`?

I'm curious to know more about `generate-chezmoi-config()`, ie where it is located etc.

**Comment by twpayne** [comment]
I strongly recommend that you look at how [people use chezmoi](https://github.com/topics/chezmoi?o=desc&s=updated), and in particular how they use templates to generate configuration files.

If you want to follow your own path of assembling a config file from JSON files, the required infrastructure is already in place, but I cannot take any more time to assist you.

**Comment by slurikadre** [comment]
> If you want to follow your own path of assembling a config file from JSON files, the required infrastructure is already in place, but I cannot take any more time to assist you.

That is exactly the point though, I don't want to depend on `jq` or do that if there's a way to do it with chezmoi alone.

> chezmoi already includes support for structured personalized data in its configuration file and already supports templating. So I don't think that JSON files, jq, or j2cli are needed, and indeed everything above can be done comfortably using chezmoi's existing functionality.

That comment made me think there was a way to use chezmoi to join the json files together under a data object.

If chezmoi doesn't have the ability to do that, I guess I'll have to use `jq` once to join the items together, and then not use split files in the future, which I guess is also possible.

I guess there really isn't any reason to split them.

Thanks for the help so far :+1:

**Comment by twpayne** [comment]
As a specific example, here is [my `.ssh/config`](https://github.com/twpayne/dotfiles/blob/master/private_dot_ssh/config.tmpl). I use:

* Template variables populated by chezmoi like `.chezmoi.os` to vary the contents on different OSes.
* Template variables from my chezmoi config file like `.isovalent` to control the contents on different machines running the same OS.
* The `onepasswordDocument` template function to pull in a whole section of private configuration from my password manager.

Note that the `.hostname` variable I have is to work around the unreliableness of macOS hostnames. If you're exclusively using Linux then the hostname is more reliable and you can use the `.chezmoi.hostname` variable.

**Comment by slurikadre** [comment]
> As a specific example, here is my .ssh/config. I use

Ah yes, that looks very similar to my jinja2 templates, so all I'll have to do is fiddle with a bit of syntax, and the rest of what you've said makes perfect sense.

So if there's no way for chezmoi to assemble the separate `json` files, then I guess I'll do a once-off assembly and then keep it that way in the future. I'm fortunate that each object has a key so they will look very similar to your `.isovalent` example.

This will be a very nice improvement as I won't no longer need `jq` afterwards!

> have is to work around the unreliableness of macOS hostnames.

Ah worth noting. I haven't used MacOS since like 2012.

**Comment by twpayne** [comment]
As a guideline, you should have relatively few variables defined in your chezmoi config file. Here's an example of mine from a personal Linux machine:

```toml
remove = true
[data]
  headless = true
  hostname = "revo"
  transient = false
  isovalent = false
  kubernetes = false
  personal = true
```

I use a bunch of boolean flags to control what I want on the machine, and the individual templates then use these flags.

As a specific example, you should not define your SSH hosts in the chezmoi config file and then have a complex `.ssh/config` file that generates an entry for each host. Instead, the hosts should be defined directly in the `.ssh/config` template file using maybe a couple of template conditions to control exactly which entries are present on each machine.

**Comment by slurikadre** [comment]
> I use a bunch of boolean flags to control what I want on the machine, and the individual templates then use these flags.

That sounds very much like what I did with yadm. I had a global config `~/.config/yadm/bootstrap_vars.json`, which contanied things like:

```json
{
  "submodule_init_vim": false,
  "run_package_manager": false,
  "install_wayland": false,
  "install_x11": false,
}
```

Of course as yadm had no way of accessing this, I had to use `jq` in my "install recipes" to check the value. I'm keen to not have to do that with chezmoi.

> As a specific example, you should not define your SSH hosts in the chezmoi config file and then have a complex `.ssh/config` file that generates an entry for each host.

Interesting, the way I had done this in the past was:

```jinja2
{%- for host in ssh_hosts %}
{% if host.Host != '' %}
Host {{ host.Host }}
{%- endif -%}
{%- if host.Comment != '' %}
    {{ host.Comment }}
{%- endif -%}
{%- if host.Hostname != '' %}
    Hostname {{ host.Hostname }}
{%- endif -%}
{%- if host.Port != '' %}
    Port {{ host.Port }}
{%- endif -%}
{%- if host.User != '' %}
    User {{ host.User }}
{%- endif -%}
{%- if host.HostKeyAlgorithms != '' %}
    HostKeyAlgorithms {{ host.HostKeyAlgorithms }}
{%- endif -%}
{%- if host.KexAlgorithms != '' %}
    KexAlgorithms {{ host.KexAlgorithms }}
{%- endif -%}
{%- if host.Ciphers != '' %}
    Ciphers {{ host.Ciphers }}
{%- endif -%}
{%- if host.MACs != '' %}
    MACs {{ host.MACs }}
{%- endif -%}
{%- if host.PasswordAuthentication != '' %}
    PasswordAuthentication {{ host.PasswordAuthentication }}
{%- endif -%}
{%- if host.IdentitiesOnly != '' %}
    IdentitiesOnly {{ host.IdentitiesOnly }}
{%- endif -%}
{%- if host.IdentityAgent != '' %}
    IdentityAgent {{ host.IdentityAgent }}
{%- endif -%}
{%- if host.IdentifyFile != '' %}
    IdentityFile {{ host.IdentifyFile }}
{%- endif -%}
{% endfor %}
```

>  Instead, the hosts should be defined directly in the `.ssh/config` template file using maybe a couple of template conditions to control exactly which entries are present on each machine.

That is one thing I noted when I looked at your `.ssh/config`. Aren't you worried about people knowing specific hosts you have access to? I'm super paranoid about that.

**Comment by twpayne** [comment]
> Aren't you worried about people knowing specific hosts you have access to? I'm super paranoid about that.

Well, in my case there's only one public IP, which gets constantly bombarded by SSH scanning bots anyway. The rest are IPs on my LAN or local VMs, and anyone with access to my account one of my machines would likely discover them by inspecting my SSH config or running a scan. Overall, in my case I don't think concealing the IPs would significantly improve my security. That said, there's a whole work-related section of my config file that I keep in my password manager and I'm not saying anything about 😉 

For keeping sensitive files private, I'd recommend using encrypting the whole file. Note that chezmoi supports encrypted templates, and the decryption/encryption is handled transparently if you use `chezmoi edit`. There's more information in the [keeping data private section of the how-to](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#keep-data-private).

**Comment by slurikadre** [comment]
> Well, in my case there's only one public IP, which gets constantly bombarded by SSH scanning bots anyway. The rest are IPs on my LAN or local VMs, and anyone with access to my account one of my machines would likely discover them by inspecting my SSH config or running a scan. Overall, in my case I don't think concealing the IPs would significantly improve my security.

True enough. I have a DNS server on my border router issued via DHCP/RDNSS. Every host has it's own `*.internal` name.

> That said, there's a whole work-related section of my config file that I keep in my password manager and I'm not saying anything about that :wink: 

This is precisely one of the reasons I'm keen on chezmoi. With my old configuration the only method I had of keeping things secret was to store the json data filles in a dmcrypt container. Now I think I might move them to keepassxc.

> For keeping sensitive files private, I'd recommend using encrypting the whole file.

I had been doing that for things like ssh keys, where every part of the file is sensitive. Yadm's [encryption](https://yadm.io/docs/encryption) is rather basic. It only allows you to add a bunch of files to a list which are then tar'ed up and encrypted with pgp.

> chezmoi supports encrypted templates, and the decryption/encryption is handled transparently if you use `chezmoi edit`.

That is very cool, and I'm keen to check that out. Also pretty cool that [age](https://github.com/FiloSottile/age) is supported!

Anyway, thanks again for the help, I think everything is sorted :smile:
