### ISSUE TITLE
Hide / display commands based on availability

### ISSUE THREAD

**Issue by kkirsche** [twpayne/chezmoi#134]
Today, with the introduction of support for Hashicorp Vault, it is possible for a command to not necessarily exist. Instead of relying on an error scenario when executing the command to try to locate it, for example:

```
 ~ $ chezmoi vault
chezmoi: exec: "vault": executable file not found in $PATH
```

Instead of relying solely on this, what's your opinion of instead looking to see if the command is a known command in the path and displaying or not including the command based on that, using `exec.LookPath` like so:

```go
func init() {
	config.Vault.Vault = "vault"
	config.addFunc("vault", config.vaultFunc)
        
        _, err := exec.LookPath(config.Vault.Vault); if err == nil {
	    rootCommand.AddCommand(vaultCommand)
         }
}
```

An example application to demonstrate this:

```go
package main

import (
        "fmt"
        "os/exec"
)

func main() {
        p, err := exec.LookPath("ls")
        if err == nil {
                fmt.Printf("ls is installed at %s\n", p)
        } else {
                fmt.Println("ls is not installed")
        }

        p, err = exec.LookPath("vault")
        if err == nil {
                fmt.Printf("vault is installed at %s\n", p)
        } else {
                fmt.Println("vault is not installed")
        }
}
```

and the output on a machine with ls but not vault is:

```
$ go run example.go
ls is installed at /bin/ls
vault is not installed
```

**Comment by twpayne** [comment]
Really good idea - thanks!

To build on this, I suggest:
- Only show available commands, as you suggest.
- Also add a `chezmoi doctor` command that checks for all binaries to assist debugging and user supprt.
