### ISSUE TITLE
Auto commit/push not working

### ISSUE THREAD

**Issue by smichaud** [twpayne/chezmoi#1344]
## What exactly are you trying to do?
I would like to automatically commit and push when a dotfile is changed.

## What have you tried so far?

I added to chezmoi repo config (~/.local/share/chezmoi/.git/config)
```
[git]
    autoCommit = true
    autoPush = true
```

Is it the wrong config file? The actual config file is not mentioned in the documentation, so I assumed it was this one.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

N/A

## Output of `chezmoi doctor`

```console
RESULT    CHECK                MESSAGE
warning   version              v2.1.4, built at 2021-08-05T11:57:28Z
ok        os-arch              linux/amd64
info      config-file          /home/smichaud/.config/chezmoi/chezmoi.toml does not exist
ok        source-dir           /home/smichaud/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in /home/smichaud/.local/share/chezmoi
ok        dest-dir             /home/smichaud is a directory
ok        shell                found /usr/bin/zsh
ok        editor               found /usr/bin/nvim
ok        git-cli              found /usr/bin/git, version 2.32.0
ok        merge-cli            found /usr/bin/vimdiff
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.29
info      1password-cli        op not found in $PATH
ok        bitwarden-cli        found /usr/bin/bw, version 1.17.1
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

**Comment by twpayne** [comment]
> Is it the wrong config file? The actual config file is not mentioned in the documentation, so I assumed it was this one.

It is the wrong config file. A correct one would be `~/.config/chezmoi/chezmoi.toml`.

**Comment by smichaud** [comment]
Thank you for the quick reply and for the awesome tool!
