### ISSUE TITLE
Detect WSL

### ISSUE THREAD

**Issue by baslat** [twpayne/chezmoi#1347]
## What exactly are you trying to do?

I am trying to use chezmoi  in WSL. I see this link: https://www.chezmoi.io/docs/how-to/#detect-windows-subsystem-for-linux-wsl, however I don't know what to do with the code presented their, ie:
```
{{ if (eq .chezmoi.os "linux") }}
{{   if (.chezmoi.kernel.osrelease | lower | contains "microsoft") }}
# WSL-specific code
{{   end }}
{{ end }}
```
The specific problem I am encountering is the different in how each system (ie WSL vs Windows) treats `~`, meaning that the relative paths aren't working as expected when adding or applying files.

## What have you tried so far?
Looking on various blogs and git repos for examples of how this is used; pasting it into `~/.config/chezmoi/chezmoi.toml`

## Where else have you checked for solutions?

* [ Yes] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [ Yes] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [ Yes] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [Yes ] Other, please give details.: googling and experimenting

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.1.5, commit 1a59ced6df2009460cc063e06310197c4eddf2fe, built at 2021-08-11T21:47:16Z, built by goreleaser
ok        os-arch              windows/amd64
ok        config-file          C:/Users/baslat/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           C:/Users/baslat/local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries found in C:/Users/abasi/.local/share/chezmoi
ok        dest-dir             C:/Users/baslat is a directory
ok        shell                found C:\Windows\system32\cmd.exe
ok        editor               found C:\Program Files\Microsoft VS Code\bin\code.cmd
ok        git-cli              found C:\Program Files\Git\cmd\git.exe, version 2.32.0
warning   merge-cli            vimdiff not found in $PATH
ok        age-cli              age not found in $PATH
ok        gnupg-cli            gpg not found in $PATH
info      1password-cli        op not found in $PATH
ok        bitwarden-cli        found C:\ProgramData\chocolatey\bin\bw.exe, version 1.17.0
info      gopass-cli           gopass not found in $PATH
info      keepassxc-cli        keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

## Additional context

Thanks for your help, dotfiles are all new to me.

**Comment by fanuch** [comment]
I use many instances of WSL and I know your pain.

> however I don't know what to do with the code presented 

The code presented is showing you how to wrap  **exclusive** configurations for WSL systems.
I.e. It is _not_ a setting that needs to be applied!

To give you an example, this is how I change VIM to using `clip.exe` for clipboard:
```
" blah blah other configs above
"....
{{ if ( or ( contains "microsoft" ( lower .chezmoi.kernel.osrelease )) ( contains "wsl" ( lower .chezmoi.kernel.osrelease ))) }}
" WSL2 yank support
" Source: https://superuser.com/a/1557751/283408
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " change this path according to your mount point
if executable(s:clip)
    augroup WSLYank
        autocmd!
        autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
    augroup END
endif
{{ end }}
"....
" blah blah other configs below
```

(Yes my conditional is different to the source example, but I worked mine out myself!)
