### ISSUE TITLE
How to manage configs modified externally with symlinks destroyed

### ISSUE THREAD

**Issue by eugenesvk** [twpayne/chezmoi#1348]
## What exactly are you trying to do?

I'd like to add a config file to chezmoi that is:
- modified externally by an app (this part is currently possible via symlinks)
- completely overwritten on such an external modification, i.e. a symlink is replaced by a regular file (this makes the current solution fail)

Is there a great way to manage such a setup? I know there are also hardlinks which, as far as I understand, would eliminate the overwriting (the chezmoi and target state files would be identical unlike with the symlink, so the app wouldn't break it), but chezmoi can't create hardlinks. Could those help (if implemented)?
Thanks!

## What have you tried so far?

I'm currently just managing these files directly with a manual diff resolution on conflict (chezmoi helpfully warns if a file has been modified externally)

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] a similar issue, but slightly different https://github.com/twpayne/chezmoi/issues/467

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.1.4, commit cdbc0851550d5b5a1355af3640a3f9008fb59a61, built at 2021-08-04T21:36:58Z, built by Homebrew
ok       os-arch              darwin/amd64
ok       config-file          /Users/eugenesv/.config/chezmoi/chezmoi.yaml is a file
ok       source-dir           /Users/eugenesv/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries found in /Users/eugenesv/.local/share/chezmoi
ok       dest-dir             /Users/eugenesv is a directory
ok       shell                found /usr/local/bin/xonsh
ok       editor               found /usr/local/bin/subl
ok       git-cli              found /usr/local/bin/git, version 2.32.0
ok       merge-cli            found /usr/bin/vimdiff
ok       age-cli              found /usr/local/bin/age, version 1.0.0-rc.3
ok       gnupg-cli            found /usr/local/bin/gpg, version 2.2.27
info     1password-cli        op not found in $PATH
ok       bitwarden-cli        found /usr/local/bin/bw, version 1.17.1
info     gopass-cli           gopass not found in $PATH
info     keepassxc-cli        keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-cli         lpass not found in $PATH
info     pass-cli             pass not found in $PATH
info     vault-cli            vault not found in $PATH
info     secret-cli           not set

**Comment by twpayne** [comment]
I'll investigate adding hard link support to chezmoi. In theory, it should be possible.

In the short term you can:
* Use `.chezmoiignore` to ignore the dotfile when running `chezmoi apply`.
* Use a `run_once_` script to create a hard link from the dotfile to a file in the source directory.

e.g. if your application creates a file called `.foo` then you would add `.foo` to `.chezmoiignore` and create a `run_once_create-dot_foo-hardlink` script containing something like:

```sh
#!/bin/sh

ln --force $(chezmoi source-path ~/.foo) ~/.foo
```

Warning: the above is untested. I *think* I got the order of arguments to `ln` correct, but please check.

You may also wish to verify that your application will handle the hard link. If the application removes its dotfile before writing it, the hard link approach will not work.

**Comment by eugenesvk** [comment]
Thanks for you prompt response and consideration of the hardlinks!

> If the application removes its dotfile before writing it, the hard link approach will not work.

oh, those abominable applications :( Thanks for the tip! Unfortunately, that's exactly what seems to be happening after a settings update within the app I've started to test this approach with (the hardlink count goes from 2 to 1 and the source dir config doesn't get updated) — so this is even worse than a symlink since I wouldn't even notice this kind of delete&create in a file manager :( 

I think this might be the same reason why symlinks don't work — apps just delete them before updating a config — and **if this is true**, then the hardlink proposal won't help at all (and as such, it wouldn't make sense to implement it). However, maybe there is a different way of updating a file which would break a symlink, but not a hardlink?

But maybe you have another bright idea on how to manage such an edge case in a more convenient way?
Or I just need to have one of these `run_` scripts to `chezmoi add` this app-managed file purely for the backup in git, while the main file to edit by myself/the app would be in the target folder?

**Comment by twpayne** [comment]
The real fix is probably to contact the developer of the application to fix their software :)

Another approach that may work is: if the dotfile is in a subdirectory, then make that subdirectory a symbolic link to a directory in your source state. This means that the application will delete and re-create the the dotfile inside your source state.

Another option is to wrap the application in a shell script that copies the dotfile into its location before running the application, and then copies the dotfile back to the source state after the application has terminated.

**Comment by eugenesvk** [comment]
> The real fix is probably to contact the developer of the application to fix their software :)

True, though this particular app isn't actively developed anymore
(as an aside, I've found a similar issue in another app and there they used an "atomic_write" library that did indeed create temporary files and then just renamed them (deleting the old configs), so this would require the app to resolve symlinks before invoking a write command so that this process would happen at the link target rather than the source)

> Another approach that may work is: if the dotfile is in a subdirectory, then make that subdirectory a symbolic link to a directory in your source state. This means that the application will delete and re-create the the dotfile inside your source state.

Good idea for when it's a lonely file in a subdir, but in this case there are other configs that aren't overwritten, for which I'd very much like to retain the power of using chezmoi templates etc., so don't want the whole folder to be a direct symlink to the source
(currently I'm symlinking
`~/Library/Application Support/app/Settings` to
`~/.config/app/Settings`
which is then managed by chezmoi)
 
> Another option is to wrap the application in a shell script that copies the dotfile into its location before running the application, and then copies the dotfile back to the source state after the application has terminated.

Interesting idea, how is this better than using chezmoi's `run_...` script template to just copy the file to the source dir, with the template allowing me to tweak it to various platforms, where the dotfile location is different?


Anyway, for now the `run_` chezmoi script capability of copying the externally editable file to the source seems like a sufficient fix for this use case, and I don't know of any examples of where a hardlink would help, so feel free to close this unless you think your investigation might still be useful.

P.S.
The only thing I don't like is getting the full script content on `--verbose` as I like this switch since it shows changes in actual config files, I wish there were a verboseness level that would allow me to hide the script content, but keep showing the diffs...

**Comment by twpayne** [comment]
> The only thing I don't like is getting the full script content on `--verbose` as I like this switch since it shows changes in actual config files, I wish there were a verboseness level that would allow me to hide the script content, but keep showing the diffs...

Full response later, but for this see #1083.

**Comment by eugenesvk** [comment]
> Full response later, but for this see #1083.

Very cool, thanks, forgot about this option since haven't used scripts before! Though this doesn't affect the `apply` command, so `chezmoi -vn apply` (or the actual `chemzoi -v apply`) still requires a manual flag `--exclude=scripts`, there isn't a similar config option like this:
```
apply       	:
 exclude   	: ["scripts"]
```

I guess I'll just change my workflow to running `chezmoi diff` instead of the `chezmoi -vn apply` before each update as the scripts are usually much larger than small regular changes to the scripts

**Comment by twpayne** [comment]
Thinking about this more, I'm not sure what else chezmoi can do here.

For what it's worth chezmoi is one of "those" applications that replaces files atomically and so also destroys symlinks in the same way as the "atomic_write" library mentioned does.

> > Another option is to wrap the application in a shell script that copies the dotfile into its location before running the application, and then copies the dotfile back to the source state after the application has terminated.
> 
> Interesting idea, how is this better than using chezmoi's `run_...` script template to just copy the file to the source dir, with the template allowing me to tweak it to various platforms, where the dotfile location is different?

The difference here is that the application's changes to its config file get propagated to chezmoi's source state immediately. The problem with using a `run_` script template to copy the file to the source state is that chezmoi assumes that the source state does not change while chezmoi is being executed.

Hope this helps, please re-open if needed.
