### ISSUE TITLE
Run certain files only on `init`

### ISSUE THREAD

**Issue by ram02z** [twpayne/chezmoi#1352]
## What exactly are you trying to do?

I store my secrets using chezmoi and it works well, however, I would prefer if I had the option to only update their contents on `chezmoi init`.
For example, I use the template function `githubKeys` and I might run into API rates limits when I am editing other parts of my config and then I have to wait a timeout before I can apply again. Of course, there is a solution, which is to use an API key, however, my secrets don't change often, so I would prefer to have run it when I need to force a config change, which is what I use `chezmoi init` for since I have a prompt for my name, email etc.

If this a new feature, I can open a feature request issue instead.

## What have you tried so far?

I have tried using the `once` prefix, however, that only applies to scripts, not plaintext files.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

**Comment by twpayne** [comment]
Consider putting the call to `gitHubKeys` in your config file template (`.chezmoi.toml.tmpl` in your source directory), something like:

```
[data]
  sshPublicKey = {{ (index (gitHubKeys "ram02z") 0).Key | quote }}
```

and then using the `.sshPublicKey` variable in your templates instead of calling `gitHubKeys` each time.

When your GitHub key changes, you'll need to re-run `chezmoi init` to regenerate your config file.
