### ISSUE TITLE
Easiest way to change prompt (PS1) when being inside the "chezmoi cd" sub-shell ?

### ISSUE THREAD

**Issue by SR-G** [twpayne/chezmoi#1353]
## What exactly are you trying to do?

I use "chezmoi cd" in a very regular way. I have some custom prompt. Is there a very simple way for the sub-shell launched by "chezmoi cd" to have a different PS1 ? (different color, or label, or whatever).
I'm using ZSH.
Purpose : i never know if i'm inside the sub-shell - that i then have at some point to exit - or not, hence willing to have a visual difference throught prompt / PS1.

## What have you tried so far?

Have no idea how to configure that : 
- either how to detect from a PS1 command that the current shell is "inside" the "chezmoi cd" subshell
- either how to overwrite PS1 when "chezmoi cd" is launched

It's probably very easy to do but i can't figure any simple / elegant way.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

**Comment by twpayne** [comment]
This is really a zsh question. I'm not an expert, but I think you need to investigate zsh's `chpwd` function. Maybe ask on the zsh mailing list or forums.
