### ISSUE TITLE
chezmoi chattr does not accept hyphen-minus as negative attribute prefix

### ISSUE THREAD

**Issue by Diomendius** [twpayne/chezmoi#1356]
## Describe the bug

`chezmoi chattr +x file` adds the `executable_` prefix to `file`'s counterpart in the source tree, but `chezmoi chattr -x` instead produces the following syntax error:
```console
chezmoi chattr -x file 
chezmoi: unknown shorthand flag: 'x' in -x
```

Using `chezmoi chattr nox file` works correctly, but both methods should work as documented by `chezmoi chattr --help`

`chezmoi chattr -- -x file` also works correctly, so this bug seems to be purely a problem with argument parsing.
## To reproduce

Run `chezmoi chattr -x <file>`, observe the syntax is not accepted.

## Expected behavior

`chezmoi chattr` should behave as described in its documentation.

**Comment by twpayne** [comment]
Thanks for reporting this. This is actually working as designed. You need to pass `--` to stop chezmoi from interpreting `-x` as a flag and instead treat it as a positional argument, e.g.

    chezmoi chattr -- -x file

I've add 81094bfabc764e99385d7c7f4f33780102b7edb0 to document this.
