### ISSUE TITLE
Possible to reverse sync?

### ISSUE THREAD

**Issue by mbbroberg** [twpayne/chezmoi#1362]
## What exactly are you trying to do?

I have had multiple files edited outside of chezmoi. For example, my `config.fish` file. I would like to pull my changes from `~/.config/fish/config.fish` into `dot_config/private_fish/config.fish` instead of the reverse. 

Is there some flag I don't know about like a `chezmoi apply --reverse` I can't hunt down? 

## What have you tried so far?

I've checked all the extended flags for `apply` and looked through other subcommands. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details -> Googled extensively

## Additional context

I could script a reverse solution, but I'm hoping to find a native solution to my dotfile config or something integrated into chezmoi if at all possible. Thanks!

**Comment by twpayne** [comment]
Two options:

1. If you haven't made any changes to `dot_config/private_fish/config.fish` that you want to keep, then re-running `chezmoi add ~/.config/fish/config.fish` will overwrite it with your latest changes.
2. If you have made changes that you want to keep, or it's a template, then run `chezmoi merge ~/.config/fish/config.fish` to open your merge tool to move changes across.

Tip: `chezmoi re-add` runs `chezmoi add` on all files (not templates) managed by chezmoi.

Hope this helps - please re-open if needed.

**Comment by mbbroberg** [comment]
That's perfect, thanks so much @twpayne (for the info and for the wonderful tool 🏠)
