### ISSUE TITLE
Ignoring particular syntax in a text/template

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1364]
## What exactly are you trying to do?

So I have some sections of my plugin_vimrc that is only run if I am on a particular host.

However using vimrc syntax it has some folds like with `{{{` `}}}` in it.

https://stackoverflow.com/a/61121895 indicates you can use backticks like:

```
{{`"output"`}}
```
 but this only works if the text doesn't contain backticks, which [my folded coc.nvim section does](https://github.com/neoclide/coc.nvim#example-vim-configuration).

How would you suggest I solve this?

With Jinja2 I had the option of using {% raw %} {% endraw %}.

**Comment by twpayne** [comment]
I would suggest using a string literal inside template delimiters, for example:

    {{ "{{{" }}

Hope this helps, please re-open if needed.
