### ISSUE TITLE
Using a template to create multiple files

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1369]
## What exactly are you trying to do?

I'd like to use a single template for multiple files.

## What have you tried so far?

I think the only way to do this is with a shell script, because as far as I know there isn't a way to write a template to multiple separate files.

This however that isn't the fastest of ways, it also causes my script to be dependent on `bash`,`jq` and `j2cli`. I'd also like to not have mixed templating languages (script currently uses Jinja2 templates) instead of go text/template like the rest of my files.

A similar example was posted here: https://gist.github.com/miguelmota/9456162

 ```bash
mutt() {
    printf "Building accounts/signatures \n"

    i=0; while read -r line; do
        printf 'Building signatures %d-%s\n' "$((i+1))" "$line";
        jq -r --argjson i "$i" '.mutt[$i]' "$1" |
            j2 -f json -o "$XDG_CONFIG_HOME"/mutt/signatures/$((i+1))-"$line".signature \
            "$XDG_CONFIG_HOME"/mutt/signatures/signature.j2
        jq -r --argjson i "$i" '.mutt[$i]' "$1" |
            j2 -f json -o "$XDG_CONFIG_HOME"/mutt/signatures/$((i+1))-"$line"_html.signature \
            "$XDG_CONFIG_HOME"/mutt/signatures/signature_html.j2
        printf 'Building account configs %d-%s\n' "$((i+1))" "$line";
        jq -r --argjson i "$i" '.mutt [$i] | .currentAccount = $i+1' "$1" |
            j2 -f json -o "$XDG_CONFIG_HOME/mutt/accounts/$((i+1))-$line.muttrc" \
            "$XDG_CONFIG_HOME"/mutt/accounts/account.j2
        i=$(( i + 1 ))
    done < <(jq -r '.mutt[].accountName' "$1")
}
mutt "$XDG_CONFIG_HOME/chezmoi/data/mutt.json"
```

It might not be possible for any way within the template language to write to multiple locations? Maybe it is possible to write a shell script then around the use of chezmoi rather than `bash`,`jq` and `j2cli`.

That might be very well necessary for my mozilla script, it creates a `.desktop`, copies a `user.js` and `userChrome.css` shortcut for my profile based on a git branch. This could be somewhat related to https://github.com/twpayne/chezmoi/issues/1226 so I'll make sure to see what that person has done.

```bash
firefox() {
    local -n branches=$1
    local b p d="$XDG_CONFIG_HOME"/firefox/user.js

    for p in "${!branches[@]}"
    do
        b=${branches["$p"]}
        printf 'Configuring "%s" on "%s"\n' "$p" "$b"
        ln -sf "$XDG_CONFIG_HOME"/firefox/chrome/userChrome.css ~/.mozilla/firefox/"$p"/chrome/userChrome.css
        git --git-dir="$d/.git" --work-tree="$d" checkout "$b" &&
        "$d"/updater.sh -b -d -s
        cp "$d"/user.js "$HOME"/.mozilla/firefox/"$p"/user.js

    jq -nr --arg name "$p" --arg path "$HOME"/.mozilla/firefox/"$p" '{ name: $name, path: $path } | { fx_opt: . }' |
        j2 -f json -o "$XDG_DATA_HOME"/applications/firefox."$p".desktop \
        "$XDG_DATA_HOME"/applications/firefox.desktop.j2
    done
}

prepareMozilla() {
    declare -A profiles

    jsonFileName=$(basename "$1" .json)

    # Read profiles in from JSON array
    while read -r profile; read -r branch; do
        profiles[$profile]=$branch
    done < <(jq -r --arg product "$jsonFileName" '.[$product].{{.chezmoi.hostname}}.profiles[] | .name, .branch' "$1")

    if [ "$jsonFileName" == "firefox" ]; then
        printf "Creating firefox profiles...\n"
        firefox profiles
    elif [ "$jsonFileName" == "thunderbird" ]; then
        printf "Creating Thunderbird profiles...\n"
        thunderbird profiles
    else
        printf "Neither Firefox or Thunderbird?\n"
    fi
}
prepareMozilla "$XDG_CONFIG_HOME/chezmoi/data/firefox.json"
```

This draws from a json object:

```json
{
  "firefox": {
    "hostname": {
      "profiles": [
        {
          "name": "xxxxxxx.default-release",
          "branch": "fx-desktop"
        },
        {
          "name": "xxxxxxxx.other-profile",
          "branch": "fx-desktop"
        }
      ]
    }
  }
}
```

I suppose at worst I could write a program in Go program... instead of a shell script.

If you've got a better idea then I'd be happy to hear it :smile:

**Comment by twpayne** [comment]
I would suggest the following:

1. Put the shared structured data in `.chezmoidata.json` ([link](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoidataformat)).
2. Write separate templates for each dotfile that generate the appropriate contents from the shared data.

**Comment by slurikadre** [comment]
In regard to the mutt configs I think I've come up with a method:

1. Write a very simple helper script `sh` which simply duplicates the template. 
2. The helper script itself could be a template, *.tmpl that way it would know what to make the filenames of each template when it is run, this would come from chezmoidata. It would be `run_before`
3. Each template for each account fills with data.

**Comment by slurikadre** [comment]
@bradenhilton so I worked up a solution as you suggested in https://github.com/twpayne/chezmoi/issues/1369#issuecomment-906264160 and am happy with it.

I have three templates:

#### `$XDG_DATA_HOME/chezmoi/.chezmoitemplates/mutt/account`

The these templates use values like:
- `{{ .accountName }}` (name of account)
- `{{ .realname }}` (my real name)
- `{{ .email }}` (email@example.com)
- `{{ .hostname }}` (hostname to use in Message-ID)
- `{{ .currentAccount }}` (number in the loop)
-  `{{ .keyID }}` (used in `{{- if eq .keyID "" }}` to check if the `keyID` is set and then enable `pgp_self_encrypt` and `pgp_default_key` for that account.
- `{{ .davURL}}` (I check if this is set and bind the `query_command` [`khard`](https://github.com/scheibler/khard) which is updated with [`vdirsyncer`](https://github.com/pimutils/vdirsyncer) to it so that I can access my address book.

#### `$XDG_DATA_HOME/chezmoi/.chezmoitemplates/mutt/signature`
This simply sets a plaintext signature with a bunch of values:
- `{{ .signature -}}` (my name)
- `{{ .shortID }}` (if set for that account)

#### `$XDG_DATA_HOME/chezmoi/.chezmoitemplates/mutt/signature_html`

Same as above but a HTML version. Sometimes [I like to write email in markdown and send it](http://nosubstance.me/post/mutt-secret-sauce/)

Then I wrote a script:

#### `$XDG_DATA_HOME/chezmoi/dot_local/bin/scripts/chezmoi-scripts/run_once_before_00_create_mutt_accounts.sh`

This script checks to see if the account is enabled, (a value in my json data), and if it is then it will produce a template for each.

```sh
#!/bin/sh
muttJson="$XDG_CONFIG_HOME"/chezmoi/data/mutt.json
mkdir -p "$XDG_DATA_HOME"/chezmoi/dot_config/mutt/accounts \
         "$XDG_DATA_HOME"/chezmoi/dot_config/mutt/signatures

i=0
jq -r '.mutt[].accountName' "${muttJson}" |
    while read -r accName
    do
        if eval "$(jq -r --argjson counter $i '.mutt[$counter].enabled' "${muttJson}")"; then
            realname=$(jq -r --argjson counter $i '.mutt[$counter].realname' "${muttJson}")
            email=$(jq -r --argjson counter $i '.mutt[$counter].email' "${muttJson}")
            hostname=$(jq -r --argjson counter $i '.mutt[$counter].hostname' "${muttJson}")
            keyID=$(jq -r  --argjson counter $i '.mutt[$counter].keyID' "${muttJson}")
            davURL=$(jq -r  --argjson counter $i '.mutt[$counter].davURL' "${muttJson}")

            printf 'Building account configs %d-%s\n' "$((i+1))" "$accName";
            printf "%s\n" "{{- template \"mutt/account\" \
dict \"accountName\" \"$accName\" \
\"currentAccount\" \"$i\" \
\"realname\" \"$realname\" \
\"email\"  \"$email\" \
\"hostname\" \"$hostname\" \
\"keyID\" \"$keyID\" \
\"davURL\" \"$davURL\" }}" > \
            "$XDG_DATA_HOME"/chezmoi/dot_config/mutt/accounts/$((i+1))-"$accName".muttrc.tmpl

            signature=$(jq -r --argjson counter $i '.mutt[$counter].signature' "${muttJson}")
            shortID=$(jq -r --argjson counter $i '.mutt[$counter].shortID' "${muttJson}")
            printf 'Building signature configs %d-%s\n' "$((i+1))" "$accName";
            printf "%s\n" "{{- template \"mutt/signature\" \
dict \"signature\" \"$signature\" \
\"shortID\" \"$shortID\" > \
            "$XDG_DATA_HOME"/chezmoi/dot_config/mutt/signatures/$((i+1))-"$accName".signature.tmpl

            printf 'Building html signature configs %d-%s\n' "$((i+1))" "$accName";
            printf "%s\n" "{{- template \"mutt/signature_html\" \
dict \"signature\" \"$signature\" \
\"shortID\" \"$shortID\" > \
"$XDG_DATA_HOME"/chezmoi/dot_config/mutt/signatures/$((i+1))-"$accName".html.signature.tmpl
            i=$(( "$i" + 1))
        fi
    done
```

Now I should be able to do away with the `jq -r --argjson` and turn the script itself into a template like in your previous comment https://github.com/twpayne/chezmoi/issues/1369#issuecomment-907209544.

You'll note there aren't actually any passwords stored in here that's because those are in `$XDG_CONFIG_HOME/msmtp/config` (used for sending email) and `$HOME/.mbsyncrc` used for synchronizing the imap stores.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
