### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by hydrargyrum** [twpayne/chezmoi#1375]
# Describe the bug

https://www.chezmoi.io/docs/reference/#diff-target states:

> Print the difference between the target state and the destination state for targets. If no targets are specified, print the differences for all targets.

If I'm not mistaken it should read:

> Print the difference between the target state and the source state for targets. If no targets are specified, print the differences for all targets.

**Comment by twpayne** [comment]
The documentation is correct. The source state is the state of the files in the source directory, which includes templates and encrypted files. The target state is the result after executing templates and decrypting files. The destination state is the state of the destination directory.
