### ISSUE TITLE
Chezmoi discards first merge argument (destination file) if merge arg is provided

### ISSUE THREAD

**Issue by Jaakkonen** [twpayne/chezmoi#1392]
## Describe the bug

If I have `~/.config/chezmoi/chezmoi.toml` looking like:
```toml
[merge]
    command = "nvim"
    args = ["-d"]
```
running `chezmoi merge .profile` will launch command
```sh
nvim -d $HOME/.local/share/chezmoi/dot_profile /tmp/chezmoi-merge1240087590/.profile
```

## To reproduce

Set args array to one described above and run chezmoi merge

## Expected behavior

Chezmoi would launch the program similarly as it would without arguments. If I have
```toml
# ~/.config/chezmoi/chezmoi.toml
[merge]
    command = "nvim"
    # args = ["-d"]
```
then the launched program is what is expected:
```sh
nvim $HOME/.profile $HOME/.local/share/chezmoi/dot_profile /tmp/chezmoi-merge3942359783/.profile
```
(the first argument is not replaced).
The expectation is that the args are prepended before the files, not that those override the files.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```
A single new line

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.2.0, built at 2021-08-30T04:53:44Z
ok        os-arch              linux/amd64
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml is a file
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   ~/.local/share/chezmoi: no suspicious entries
ok        dest-dir             ~ is a directory
ok        shell                found /bin/dash
ok        editor               found /usr/bin/nvim
ok        git-cli              found /usr/bin/git, version 2.33.0
ok        merge-cli            found /usr/bin/nvim
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.29
info      1password-cli        op not found in $PATH
ok        bitwarden-cli        found /usr/bin/bw, version 1.18.0
info      gopass-cli           gopass not found in $PATH
ok        keepassxc-cli        found /usr/bin/keepassxc-cli, version 2.6.6
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

## Additional context

It used to work a month or so back on Arch Linux so it was probably broken in a pretty recent release

**Comment by twpayne** [comment]
Thank you for reporting this and for the clear and complete bug report :)

This is a definite regression introduced by #1324. What happened was:

* Before #1324, setting `merge.args` created additional args prepended to the merge command.
* After #1324, setting `merge.args` replaced the args to the merge command.

In the short term you can fix this by setting:

```toml
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
```

In the medium term I propose to fix this while maintaining backwards compatibility with both pre- and post-#1324 behaviors with the heuristic "If any of the `merge.args` elements are templates, then `merge.args` replaces the args to the merge command, otherwise prepend `merge.args` to the args to the merge command and use the default destination/source/target order."

**Comment by twpayne** [comment]
Also, thank you for replacing your home directory with `~` in the `chezmoi doctor` output. This is an excellent way of communicating the needed information without revealing any personal details, and previously people have had to make the same change manually. I'll update `chezmoi doctor` to do this automatically.

**Comment by twpayne** [comment]
#1394 should fix this, but your observation and analysis was particular keen in the title of this bug report: "Chezmoi discards first merge argument (destination file) if merge arg is provided".

What was actually happening here, was:

1. chezmoi's default arguments to the merge command are `["{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]`.
2. chezmoi uses [viper](https://github.com/spf13/viper) to parse its configuration file, which in turn builds on [mapstructure](https://github.com/mitchellh/mapstructure).
3. When mapstructure unmarshals an array, it overwrites or appends elements, but does not truncate. Specifically, this meant that if you set `merge.args` to be `["-d"]` then mapstructure would unmarshal this into the default arguments the resulting arguments would be `["-d", , "{{ .Source }}", "{{ .Target }}"]`, i.e. discarding the first merge argument, exactly as you described.

There were a couple of [WTF moments](https://commadot.com/wtf-per-minute/) while debugging this.

Thank you again for the excellent bug report!
