### ISSUE TITLE
Template function to determine if current device is a laptop or desktop

### ISSUE THREAD

**Issue by aw1cks** [twpayne/chezmoi#1396]
Hi! Love the project, makes my life much easier. :)

It occurred to me that it would be really handy to have a function to determine whether the current device is a laptop or desktop.
SMBIOS/DMI could easily provide this information, for example on Linux:
```
alex@desktop::~» sudo dmidecode --string chassis-type

Desktop
alex@desktop::~»
```
And it looks like there is already a nice library for this: https://github.com/digitalocean/go-smbios

If this is something you'd be likely to accept, I may have a crack at it myself.

**Comment by twpayne** [comment]
Thanks for your kind words about chezmoi :)

This will require some care to implement. Reading the SMB BIOS requires root access, but chezmoi usually runs as your normal user, so the go-smbios library on its own is not enough. You'd need a mechanism for chezmoi to elevate its privileges temporarily.

An alternative is to use the existing `output` function, e.g. put this in your config file template (`.chezmoi.toml.tmpl`):

```
[data]
    chassisType = {{ output "sudo" "dmidecode" "--string" "chassis-type" | trim | quote }}
```

chezmoi will then populate this when you run `chezmoi init`, and you'll only need to enter the root password when you run `chezmoi init`, not on every invocation of chezmoi (as you would if reading the SMBIOS/DMI was implemented as a template function).

That said, I think it would be technically possible to make an `smbios` a template function, but that will involve chezmoi executing itself with `sudo` as part of it.

What do you think?

**Comment by aw1cks** [comment]
Thanks for the quick response!
Very good point about running with root privileges, that could be a little annoying. It would definitely be preferable to avoid prompting for a password.
It looks like there could be some ways to get this information without needing elevated privileges though:
```
alex@desktop::~» hostnamectl --json=short | jq -r '.Chassis'
desktop
alex@desktop::~»
```
I'll do a little research and update if it looks feasible in a portable way, otherwise I will close this issue.

**Comment by twpayne** [comment]
Note that chezmoi also has code for parsing JSON, so you don't need to pipe into jq. Instead you should be able to do:

```
{{ output "hostnamectl" "--json=short" | fromJson | .Chassis }}
```

**Comment by aw1cks** [comment]
That's neat! I think I will close this issue then. Thanks again!

**Comment by aw1cks** [comment]
For anyone else trying to do this, this should work across macOS, Linux & Windows:
```
{{- $chassis_type := "" }}
{{- if (eq .chezmoi.os "darwin") }}
{{- if contains "MacBook" (output "sysctl" "-n" "hw.model") }}
{{- $chassis_type = "laptop" }}
{{- else }}
{{- $chassis_type = "desktop" }}
{{- end }}
{{- else if (eq .chezmoi.os "linux") }}
{{- $chassis_type = (output "hostnamectl" "--json=short" | mustFromJson).Chassis }}
{{- else if (eq .chezmoi.os "windows") }}
{{- $chassis_type = (output "powershell.exe" "-noprofile" "-command" "if (Get-WmiObject -Class win32_battery -ComputerName localhost) { echo laptop } else { echo desktop }") }}
{{- else }}
{{- $chassis_type = "desktop" }}
{{- end }}
```

**Comment by twpayne** [comment]
Thanks! Added to the docs in 0b2692ac45e43405d65a62a8a5fefb51ebaab9c4.
