### ISSUE TITLE
Read-only file state attributes

### ISSUE THREAD

**Issue by zacwest** [twpayne/chezmoi#1400]
## Is your feature request related to a problem? Please describe.

This may be an esoteric request, but I'll describe what I'm trying to accomplish.

macOS has the very annoying habit of syncing in and adding to its text replacement database (e.g. `omw` -> `On my way!`) which is hard to otherwise prevent. One solution I've done is to mutate its SQLite database using something like:

```bash
sqlite3 ~/Library/KeyboardServices/TextReplacements.db "delete from ZTEXTREPLACEMENTENTRY;"
```

I've come across a few other versions of this, but nothing really home-directory/config specific. I imagine this could be a problem where it acts as a solution for other cases, or maybe it's extremely rarely necessary and not worth the hassle.

## Describe the solution you'd like

I'd like to be able to create `private_Library/KeyboardServices/readonly_empty_TextReplacements.{db,db-shm,db-wal}` and prevent these files from being mutated by the system. I could see this being either a chmod of -w on macOS/Linux, the 'Locked' attribute on macOS, or the 'read-only' attribute on Windows.

## Describe alternatives you've considered

I imagine a modify_ script could also do this; I've also implemented it as a run_ script, but these are slightly less declarative of what the state of the files on disk should be in this case.

**Comment by twpayne** [comment]
Thanks for the suggestion :)

>  I could see this being either a chmod of -w on macOS/Linux, the 'Locked' attribute on macOS, or the 'read-only' attribute on Windows.

#1403 adds a `readonly_` attribute that clears all write permission bits on UNIX.

I'm cautious about adding the UF_IMMUTABLE flag ('locked' attribute) on macOS/BSD or Windows' read-only attribute for a few reasons:
* It's orthogonal to the write permission bits, and so should be handled separately.
* Most applications are unlikely aware of it: there's no way to represent it in git-formatted diff output, for example.
* I haven't investigated yet, but it's possible that using the flag will significantly complicate how chezmoi updates such files, for example if the target contents of an immutable file change then chezmoi will likely have to clear the immutable flag, update the contents, and then re-set the flag.

Together, these mean a lot of significant extra complexity in chezmoi's codebase for a feature that it will in practice be rarely used and where a workaround (setting the flag or attribute in a `run_` script) exists.

What do you think?

**Comment by zacwest** [comment]
The locked attribute probably adds an additional layer on top that isn't possible with just permissions: disallowing root-privileged processes from changing the contents of the file, too. This is likely even less common than wanting to restrict changing the contents of the file through normal use, and your worry about additional layers of complexity sounds very reasonable considering the workarounds exist and it almost certainly would require toggling the flag to update the contents.

Removing the write permission sounds it'll work out great, thanks for adding it!

**Comment by twpayne** [comment]
OK, #1403 merged, so closing this.
