### ISSUE TITLE
Allow externals to be defined as files in source state

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1423]
## Is your feature request related to a problem? Please describe.

Just like everything else in Chezmoi, every target is defined with a file in the source. Allowing externals to be set in source as files would keep the things more consistent with the rest of the Chezmoi. For example, `symlink`s also works like that.

It's also a minor drawback that with the current approach, you have to maintain the parent folders in the source state regardless. So, if we have to maintain the folder already, why not maintain the file?

## Describe the solution you'd like

I would like to instead of having to:

```sh-session
$ mkdir -p private_dot_local/share/fonts
$ touch private_dot_local/share/fonts/.keep
$ cat <<'EOF' > .chezmoiexternal.yaml
".local/share/fonts/Fira Code Regular Nerd Font Complete.ttf":
  type: file
  url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf
EOF
```

Be able to:

```sh-session
$ mkdir -p private_dot_local/share/fonts
$ cat <<'EOF' > "external_file_literal_Fira Code Regular Nerd Font Complete.ttf"
https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf
EOF
```

An example for folders would be like:

```sh-session
$ cat <<'EOF' > external_archive_exact_dot_oh-my-zsh
https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
EOF
```

## Describe alternatives you've considered

Of course, I can just use `.chezmoiexternal.yaml` for that.

## Additional context

It must be clear that I don't want to get rid of `.chezmoiexternal.yaml`, I would like to have both options available.

**Comment by twpayne** [comment]
Thanks for the suggestion. I also considered this approach when coming up with the design for externals.

There are a few problems with this approach:
1. If the file in the source state contains only the URL to download, there is no way to specify extra options like `stripComponents` for archives or `filter.command` for files (see #1429). Of course, one could parse the contents of the file in the source state as YAML or JSON or whatever, but in the example above you'd end up with a file with a `.ttf` extension that was actually a YAML or JSON file.
2. For archives (directories) you might want to have extra entries inside the external directory itself, for example [I have an additional plugin and theme inside the `.oh-my-zsh` external](https://github.com/twpayne/dotfiles/blob/master/.chezmoiexternal.toml#L4-L18). With the design proposed here, you'd need to have both `external_archive_exact_dot_oh-my-zsh` (a file containing the URL) and `exact_dot_oh-my-zsh` (a directory containing the file `custom/themes/external_archive_exact_powerlevel10k`), i.e. a single directory would need both file and directory representations in the source state.

What I propose to do instead is allow `.chezmoiexternal.<format>` files to be anywhere in the source directory, with the paths relative to where they are. This means you'd end up with something like:

```console
$ mkdir -p private_dot_local/share/fonts
$ cat <<'EOF' > private_dot_local/share/fonts/.chezmoiexternal.yaml
"Fira Code Regular Nerd Font Complete.ttf":
  type: file
  url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf
EOF
```

**Comment by felipecrs** [comment]
The new approach looks cool, I just had to move back my chezmoiexternal files to the root, otherwise a breaking change would happen when you release this new version: https://github.com/felipecrs/dotfiles/commit/75ef590869d116e71fe1cf7d4a75a6f0646c72f3

But once the new version is there, I can move back the chezmoiexternal files to where they belong and take advantage of the new feature. I will also have to update the version of `.chezmoiversion`

**Comment by twpayne** [comment]
>  I just had to move back my chezmoiexternal files to the root, otherwise a breaking change would happen when you release this new version

You're right - thanks for spotting this backwards compatibility break. With #1436, `.chezmoiexternal.<format>` files behave like `.chezmoiignore` files in that they are relative to the directory the file is in. I didn't implement this in the initial externals implementation, but should have. Fingers crossed that there are relatively few people affected by this and that they run `chezmoi diff` or `chezmoi apply -nv` or `chezmoi status` before their next apply. Gulp.

**Comment by twpayne** [comment]
While you're here - I'm about to tag version 2.5.0 once #1440 passes. Is there anything that should be fixed before 2.5.0 is tagged?

**Comment by felipecrs** [comment]
https://github.com/twpayne/chezmoi/issues/1431 and https://github.com/twpayne/chezmoi/issues/891#issuecomment-922379179

Fixing the first would allow me to handle the migration of the root folder to the `home` subfolder more seamlessly, without asking the user to reinitialize everything.

For the second, the workaround I used handles only the case when the user does `chezmoi init --apply` and then `chezmoi update`. If the person does: `chezmoi init` then `chezmoi update` (forgetting the apply in the middle), it would still be broken.

**Comment by felipecrs** [comment]
I'm investigating the second issue in the source code...

**Comment by twpayne** [comment]
Cool, thanks. I'll hold off tagging 2.5.0 until this are investigated and fixed.

**Comment by felipecrs** [comment]
@twpayne:

https://github.com/twpayne/chezmoi/blob/77b48586d2e9fb0457d67be90117ca41471db277/internal/cmd/initcmd.go#L137

```diff
- switch _, err := c.baseSystem.Stat(c.SourceDirAbsPath.Join(".git")); {
+ switch err := c.run(c.SourceDirAbsPath, c.Git.Command, []string{"rev-parse", "--git-dir"}); {
```

And then relying on the status code of the command: 0 means inside of a git dir, else means not inside. On my tests, it seems to always return 128 when not inside of a git repository, but I'm not sure if we should rely on that.

https://stackoverflow.com/a/2180367/12156188 this answer suggest to do the check on the `.git` folder before issuing the `git rev-parse --git-dir` command, but I'm not sure why. Alternatively, there is also `git rev-parse --is-inside-work-tree`, but on my tests they all behave the same if we count only their status codes.
