### ISSUE TITLE
Suggestion: adopt Conventional Commits specification

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1424]
I watch `chezmoi`'s releases for keeping up with it, but I find it a bit more complicated to read and understand than necessary. This could be easily fixed by adopting Conventional Commits specification for commit messages, and then tweaking the release notes generator to only include commits of some given types:

`fix`, `feat`, maybe also `refactor` and `perf`.

https://www.conventionalcommits.org/en/v1.0.0/

https://github.com/goreleaser/chglog

**Comment by twpayne** [comment]
Good idea. I've been thinking about doing this for some time. I'll switch after the next release.

**Comment by felipecrs** [comment]
A tip is to always use the "squash and merge" option from GitHub, as it lets you think twice about the final commit message which will end up in the actual changelog. It also helps as it automatically adds a link to the PR as suffix of the commit message subject.
