### ISSUE TITLE
Allow `chezmoi` to change permission of target but not its contents

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1428]
## Is your feature request related to a problem? Please describe.

I always create `~/.kube/config` without the proper permission, and my terminal keeps bugging me that it has wrong permission.

## Describe the solution you'd like

I would like to make `chezmoi` handle the permissions of the file to me, but not its contents. Something like:

```
touch private_dot_kube/private_dontchange_config
```

And then `chezmoi` would:

- Not change the contents of the file
- Not create it if it's not there
- Assure the file is "private"

## Describe alternatives you've considered

I could probably achieve almost the same using some workaround with:

```
echo "a script which would keep its contents" > private_dot_kube/private_modify_config
```

But still, I'm not sure how I would prevent the file from being created for example. It's just harder than it should be IMO.

**Comment by twpayne** [comment]
How about a `run_after_` script containing:

```sh
#!/bin/sh

chmod 600 ~/.kube/config || true
```

?

**Comment by felipecrs** [comment]
This should work 100%. I'll also thought about making it `run_once.tmpl` and writing some template directives to evaluate if the file exist and if it has the wrong permission.

Using scripts usually works around a bunch of helpers that chezmoi provides.

I'm fine with the workaround though, I just wanted to raise the suggestion and bring the discussion.

**Comment by twpayne** [comment]
Thanks, I think the script is sufficient at this stage. If you want to only update the permissions if the file exists and has the wrong permissions you can use:

```sh
#!/bin/sh

FILE="$HOME/.kube/config"
if [ -f "$FILE" ]; then
	if [ "$(stat -c %a "$FILE")" != "600" ] ; then
		chmod 600 "$FILE"
	fi
fi
```

As another option, if you create a file called `dot_kube/create_private_config` in your source state, then chezmoi will create ~/.kube/config` if it does not already exist and will ensure that it is private whether it exists or not.

**Comment by felipecrs** [comment]
Amazing, thank you so much!!

**Comment by felipecrs** [comment]
Btw, the following also works:

```bash
cat <<'EOF' > private_dot_kube/modify_private_config
#!/bin/sh

cat /dev/stdin
EOF
```

Just for curiosity.
