### ISSUE TITLE
`chezmoi init` should advise when multiple configuration files are present

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1430]
## Is your feature request related to a problem? Please describe.

Recently I switched my `.chezmoi.toml.tmpl` to YAML format, and then I found this issue:

`chezmoi` does not delete the previously generated `.config/chezmoi/chezmoi.toml` when it inits `.config/chezmoi/chezmoi.yaml`. But I believe it should. The `yaml` is newer, and the user expects it to be effective immediately.

## Describe the solution you'd like

Maybe `chezmoi` should delete the previously generated configuration file (but only if it was generated by chezmoi itself? because users can have written data to it manually).

Maybe `chezmoi` should at least advise the user that a new configuration file was created but another is already present and must be removed.

## Describe alternatives you've considered

I always generate the chezmoi configuration automatically, I never touch it manually. So, I wrote:

```
# .chezmoiremove

{{ if stat (joinPath .chezmoi.homeDir ".config/chezmoi/chezmoi.yaml") -}}
.config/chezmoi/chezmoi.toml
{{ end -}}
```

And it does the job for removing the old configuration. But there are some caveats:

The running `chezmoi` apply will still be using the old loaded config in the memory. This means that I have to call `apply` two times to make everything is good. It would be simpler and more deterministic if this was solved at the `init` time.

**Comment by twpayne** [comment]
Thanks for reporting this. chezmoi's support for config files in multiple formats (using github.com/spf13/viper) does cause a lot of ambiguity here. Furthermore, chezmoi supports the XDG Base Directory specification, which also allows multiple configuration directories. So, there could potentially be tens of config files. chezmoi's documentation states explicitly that it uses the first config file it finds.

Implementing a warning when there are multiple config files will require a scan of all possible config filenames in all possible config directories on every invocation. To be honest, it takes quite a special set of circumstances to trigger this, i.e. not many users will be converting their config file formats.

Instead, I propose to add the check for a unique config file to the `chezmoi doctor` command. Users should run this before reporting issues, which should allow them to catch this when it occurs.

**Comment by felipecrs** [comment]
Agreed 100%!

**Comment by felipecrs** [comment]
But there is one thing that probably would not be too risky:

chezmoi init could verify if the extension of the config template matches the extension of the actual config file that chezmoi readed.

And if it does not match a message could be raised.

But regardless, this is just an idea, I already have a working workaround and I'm probably the only one who faced this issue. So I'm completely fine with either way forward.

Thanks a bunch for the support!!
