### ISSUE TITLE
`chezmoi apply -vv`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1451]
## Is your feature request related to a problem? Please describe.

My `chezmoi apply` commands takes some time to run. It's often due to the external commands which I call in my templates, and due to downloading externals. But I can't tell for sure, unless I use `--debug`, which is too much, the information is then barely readable.

## Describe the solution you'd like

It would be interesting if `chezmoi apply -vv` would output more information, such as:

```console
> chezmoi apply --verbose --verbose
- Templating X...
- Templating Y...
- Downloading external X...
- Downloading external Y...
```

## Describe alternatives you've considered

The `writeToStdout` would help me workaround it, but it's only available on initialization. It would not help for showing download status though.

## Additional context

None.

**Comment by twpayne** [comment]
Thanks for the proposal. I think that what's tricky here is that slowness can be the accumulation of many separate steps, and it's not clear where exactly to draw the line.

For example `Templating X...` might be very slow if it involves a call to download a URL if the response is large or the connection is slow, but there's no way to know that unless `Templating X...` also logs the URL download, which would mean also logging the invocation of `curl` via the `output` template function (or whatever) that actually triggers the download, which would mean logging all processes spawned by `Templating X...` ... and then you're back at the level of `--debug`, which is exactly what you wanted to avoid.

I would rather approach this problem by making chezmoi fast in the typical case (e.g. #1450 which would make chezmoi occasionally slow but fast for repeated invocations).

So, closing this as `won't fix` but please re-open if there's more to discuss. I realize that this is a nuanced issue with no easy answers.

**Comment by felipecrs** [comment]
Ok, understood and agreed!
