### ISSUE TITLE
Test suite depends on zip

### ISSUE THREAD

**Issue by daurnimator** [twpayne/chezmoi#1452]
## Describe the bug

The test suite has an unexpected dependency on `zip`.

## To reproduce

Run the test suite without `zip` installed:
```
=== CONT  TestScript/externalguess
    testscript.go:397: 
        WORK=$WORK
        PATH=$WORK/bin:/tmp/testscript-main1578937719/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/us
r/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
        HOME=$WORK/home/user
        TMPDIR=$WORK/.tmp
        devnull=/dev/null
        /=/
        :=:
        $=$
        TESTSCRIPT_COVER_DIR=
        exe=
        CHEZMOICONFIGDIR=$WORK/home/user/.config/chezmoi
        CHEZMOISOURCEDIR=$WORK/home/user/.local/share/chezmoi
        EDITOR=$WORK/bin/editor
        SHELL=$WORK/bin/shell
        
        > [windows] skip 'UNIX only'
        > httpd www
        # test that chezmoi sniffs the format of tar files (0.122s)
        > exec tar -cf www/archive.tar archive/
        > cp www/archive.tar www/archive
        > chezmoi apply --force --refresh-externals
        > cmp $HOME/.dir/dir/file golden/dir/file
        # test that chezmoi sniffs the format of tar.bz2 files (0.073s)
        > exec tar -cjf www/archive.tar.bz2 archive/
        > cp www/archive.tar.bz2 www/archive
        > chezmoi apply --force --refresh-externals
        > cmp $HOME/.dir/dir/file golden/dir/file
        # test that chezmoi sniffs the format of tar.gz files (0.073s)
        > exec tar -czf www/archive.tar.gz archive/
        > cp www/archive.tar.gz www/archive
        > chezmoi apply --force --refresh-externals
        > cmp $HOME/.dir/dir/file golden/dir/file
        # test that chezmoi sniffs the format of zip files (0.000s)
        > exec zip -r www/archive.zip archive
        [exec: "zip": executable file not found in $PATH]
        FAIL: testdata/scripts/externalguess.txt:24: unexpected command failure
```

## Expected behavior

Either clearly document dependency of tests on `zip`, or remove the dependency

## Output of command with the `--verbose` flag

```
chezmoi version v2.5.0, built at 2021-09-24T05:12:22Z
```

## Output of `chezmoi doctor`

N/A

**Comment by twpayne** [comment]
@daurnimator Thanks very much for reporting this :)

For info, I've added explicit tests on Arch Linux to chezmoi's CI system in #1460, and specifically [this Dockerfile](https://github.com/twpayne/chezmoi/blob/master/assets/docker/archlinux.Dockerfile) sets up the Arch Linux container and [this commit adds documentation of the integration test dependencies](https://github.com/twpayne/chezmoi/commit/ffc7f13b30d19a3b57d0177305378aeb36210f70#diff-4c6b93aa75d5affde60dc3849606c9acd75ed444d52e99f3055fc0c7aa77e9e0). Also related to Arch Linux, #1473 now ensures that `Arch Linux` will be shown in the output of `chezmoi doctor`.

Please let me know (e.g. by opening an issue) if there's more that chezmoi can do to better support Arch Linux.
