### ISSUE TITLE
Defining global "feature"-variables based on system hostname for use in .chezmoiignore

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#1463]
## What exactly are you trying to do?

I use multiple similar but not quite the same systems: desktop, laptop, work-laptop, servers and research robots. Writing host name checks in .chezmoiignore is annoying and fragile (makes it hard to add another computer). I want to be able to define in a central place some variables so I can make easy checks like: `{{ if .custom.is_work }}` or `{{ if .custom.is_headless }}`.

### First idea
I tried using the `data` directive in .config/chezmoi/chezmoi.yaml. This file can then be templated based on hostname, along these lines:
```yaml
data:
  custom:
{{- if eq .chezmoi.hostname "system-a" }}
    is_laptop: false
    is_work: false
    is_headless: false
    is_robot: false
{{- else if eq .chezmoi.hostname "system-b" }}
    is_laptop: true
    is_work: true
    is_headless: false
    is_robot: false
{{- else if eq .chezmoi.hostname "system-c" }}
    is_laptop: false
    is_work: true
    is_headless: true
    is_robot: true
...
```

This works except that I can't use the variables until the file exists. This presents a bootstrapping issue on new systems:
```console
% chezmoi diff --verbose
chezmoi: template: /home/arvid/.local/share/chezmoi/.chezmoiignore:3:22: executing "/home/arvid/.local/share/chezmoi/.chezmoiignore" at <.custom.is_laptop>: map has no entry for key "custom"
```

I found that you can set `template.options: ["missingkey=zero"]`, which helps, but it is still an issue bootstrapping on new systems.

### Second idea
Next idea was to use the `.chezmoitemplates` directory to create a common template that define variables and can be included from everywhere. This doesn't work either, for two reasons:
* It appears that templates cannot be used in the top level `.chezmoiignore` file, even if they can be included elsewhere:
```console
% chezmoi diff --verbose
chezmoi: template: /home/arvid/.local/share/chezmoi/.chezmoiignore:1:13: executing "/home/arvid/.local/share/chezmoi/.chezmoiignore" at <{{template "vars"}}>: template "vars" not defined
```
* Also, variables set using `$var = "Value"` appears to be local in scope to the template file? I haven't found a way to export the result to the parent including file.

### Third idea
Another option would be to use the sprig function default. The syntax is cumbersome, (consider: `{{- if or (not (default false .custom.has_ros)) (default false .custom.is_root) }}` vs `{{- if or (not .custom.has_ros) .custom.is_root }}`, and also it doesn't seem to work:
```console
% chezmoi diff --verbose
chezmoi: template: /home/arvid/.local/share/chezmoi/.chezmoiignore:3:37: executing "/home/arvid/.local/share/chezmoi/.chezmoiignore" at <.custom.has_ros>: map has no entry for key "custom"
```
So it seems `default` does not work for variables that are not defined.

At this point I'm out of ideas.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [X] Other, please give details: I have also checked the docs for text/template and sprig to try to find if there was any useful function, such as a 

## Output of any commands you've tried with `--verbose` flag

All commands above already used `--verbose` (not that it made any difference.

## Output of `chezmoi doctor`

```console
% chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.5.0, built at 2021-09-24T05:12:22Z
ok        os-arch              linux/amd64
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   ~/.local/share/chezmoi: no suspicious entries
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        editor               found /usr/bin/code
ok        umask                022
ok        git-cli              found /usr/bin/git, version 2.33.0
ok        merge-cli            found /usr/bin/bcompare
ok        age-cli              age not found in $PATH
ok        gnupg-cli            found /usr/bin/gpg, version 2.2.29
info      1password-cli        op not found in $PATH
info      bitwarden-cli        bw not found in $PATH
info      gopass-cli           gopass not found in $PATH
ok        keepassxc-cli        found /usr/bin/keepassxc-cli, version 2.6.6
info      keepassxc-db         not set
info      lastpass-cli         lpass not found in $PATH
info      pass-cli             pass not found in $PATH
info      vault-cli            vault not found in $PATH
info      secret-cli           not set
```

## Additional context

I use multiple operating systems (Arch Linux, Ubuntu, Debian, Raspbian, ...) and architectures (x86-64, ARM, ARM64), so it doesn't seem useful to list more system details here. I don't think any of that is likely to be relevant anyway.

**Comment by VorpalBlade** [comment]
Update: it seems the missingkey thing doesn't work properly always either. It seems to work at least sometimes, but not in the top level:
```chezmoi diff --verbose
chezmoi: template: /home/arvid/.local/share/chezmoi/.chezmoiignore:3:22: executing "/home/arvid/.local/share/chezmoi/.chezmoiignore" at <.custom.has_ros>: nil pointer evaluating interface {}.has_ros
```

I haven't quite figured out when it works or not. But it definitely doesn't work when the whole `data` block is missing from `chezmoi.yaml` and that property is used in `.chezmoiignore`

**Comment by twpayne** [comment]
[Config file templates](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#create-a-config-file-on-a-new-machine-automatically) are designed to solve exactly this problem. [Here's how I personally handle this](https://github.com/twpayne/dotfiles/blob/master/.chezmoi.toml.tmpl) - I use a very similar approach to your first idea.

**Comment by VorpalBlade** [comment]
Thanks! Correct me if I'm wrong, but it sounds like this is only applied once initially? I prefer something that is kept up-to-date if possible. Both your approach and my first approach have issues if I add a new variable and then immediately use it in a `.chezmoiignore` (or other file).

For my approach the issues are:
* Variable will not be defined (can be dealt with using `missingkey=default`, `missingkey=zero` doesn't do the right thing)
* Since any new variables will not take effect until `chezmoi.yaml` has been updated, this can cause issues with `.chezmoiignore` especially:  A newly added file could be created by mistake on a system that shouldn't have it. Then the next `chezmoi apply` will of course not remove it.

But if your file doesn't recreate the file it seems to have even larger issues in this case. I'm sure your approach works well once you settled on what you need, but my system is still under development and thus change regularly. Plus what sort of systems I work with changes quite often as well.

**Comment by twpayne** [comment]
> Correct me if I'm wrong, but it sounds like this is only applied once initially?

chezmoi checksums your config file template and prompts you to re-run `chezmoi init` when it has changed. This might become unnecessary in the future (see #1427).

**Comment by VorpalBlade** [comment]
Awesome, I didn't realise that. One minor issue is that it doesn't seem I can use chezmoi diff to preview what the changes to the chezmoi config file would be.

**Comment by twpayne** [comment]
To see the diff, you can use:

```console
$ diff ~/.config/chezmoi/chezmoi.toml <(chezmoi execute-template --init  <~/.local/share/chezmoi/.chezmoi.toml.tmpl)
```

**Comment by twpayne** [comment]
I hope this issue is now resolved. Please re-open if needed.
