### ISSUE TITLE
`output` template function does not cause template rendering to fail

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1466]
To help find out the issues, the output template function should cause the template rendering to fail if the command which it runs returns a non-zero status code. If someone wants to ignore the status code, it can be worked around with something like `output "sh" "-c" "my-command || true"`.

I took a long time to realize that the chezmoi installation were failing on newly installed systems because `curl` was not installed before the template runs, then my variables were empty. Instead, I should have been warned by chezmoi that `output` failed the same way that for example, `semverCompare` fails if a non-valid string is supplied as input.

**Comment by twpayne** [comment]
Could you provide a test case to reproduce this?

I tried in https://github.com/twpayne/chezmoi/pull/1467/files but the test passes, i.e. executing the template `{{ output "false" }}` causes chezmoi to print an error to stderr and return a non-zero exit code.

**Comment by felipecrs** [comment]
Oh, I should have added -e to my bash call.

Instead of:

```
{{ $dockerComposeVersion := output "bash" "-c" "basename \"$(curl -fsSL -o /dev/null -w \"%{url_effective}\" https://github.com/docker/compose/releases/latest)\"" | trim -}}
```

I should have done:

```
{{ $dockerComposeVersion := output "bash" "-ec" "basename \"$(curl -fsSL -o /dev/null -w \"%{url_effective}\" https://github.com/docker/compose/releases/latest)\"" | trim -}}
```

**Comment by felipecrs** [comment]
Hm.. I'm trying to reproduce it to make sure.

**Comment by felipecrs** [comment]
Weird, but Bash simply ignores the errors no matter what:

![image](https://user-images.githubusercontent.com/29582865/135175534-e620d171-dcfe-4f17-8cc4-b00fc9ab7d60.png)

The green arrows in my prompt means the command succeeded.

Anyway, it's not a chezmoi issue.

But just for curiosity, do you know anything about it?

**Comment by felipecrs** [comment]
I refactored the command to:

```
{{ $dockerComposeVersion := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" "https://github.com/docker/compose/releases/latest" | trim | base -}}
```

To get out of the issue, btw. Really sorry for the mistake.

**Comment by twpayne** [comment]
> But just for curiosity, do you know anything about it?

Just a quick investigation:

Note that `basename` is bash builtin (I think) and so may be mangling things. I also don't think `-e` is an option to the `bash` command. Are you possibly mixing up bash options (e.g. `set -eufo pipefail`) and bash command line flags?

On my macOS machine:

```console
$ bash -c false; echo $?
1
$ bash -c "basename $(false)"; echo $?
usage: basename string [suffix]
       basename [-a] [-s suffix] string [...]
1
```

**Comment by twpayne** [comment]
Thanks for the extra investigation by the way - much appreciated!

**Comment by felipecrs** [comment]
> On my macOS machine:

Add the quotes: `bash -c 'basename "$(false)"'` so that basename will still suceed.

**Comment by felipecrs** [comment]
Bash does accept the -e flag, and yes, it's the same which we set wit `set -e` in scripts:

![image](https://user-images.githubusercontent.com/29582865/135178855-9a7922e8-9316-485c-ada3-801b205d1637.png)

**Comment by felipecrs** [comment]
And I don't think `basename` is the issue, we can replace it with anything, as `echo`, `true`, and the behavior persists.

**Comment by felipecrs** [comment]
[It's expected](https://unix.stackexchange.com/a/120008/427940), and there isn't much that can be done to work around it. The way is to avoid using command substitution like that.

It's funny how Bash can be complicated. I will watch out on my scripts much more now. Instead of doing things like:

```bash
var=$(some command which may fail)
```

```bash
var=$(some command which may fail); echo "${var:?}"
```

**Comment by twpayne** [comment]
Wow, thank you. TIL.

**Comment by felipecrs** [comment]
No problem, it is for my knowledge as well. But just to give the proper outcome here, in fact the example which I gave above will not always work:

```console
❯ bash -c 'var="$(false)"'; echo $?
1
❯ bash -c '$(false)'; echo $?
1
❯ bash -c 'echo $(false)'; echo $?

0
❯ bash -c 'var=$(false)'; echo $?
1
❯ bash -c 'var=$(echo $(false))'; echo $?
0
❯ bash -c 'var=$(echo $(false)); echo "${var:?}" >/dev/null'; echo $?
bash: line 1: var: parameter null or not set
127
❯ bash -c 'var=$(echo $(true)); echo "${var:?}" >/dev/null'; echo $?
bash: line 1: var: parameter null or not set
127
```

The `echo "${var:?}" >/dev/null` will only work if the value of the variable is what counts but not the status of the actual command which issued it. That's why it fails even when the command does not (`var=$(echo $(true))`).

**Comment by felipecrs** [comment]
This may be more related to https://stackoverflow.com/a/34914900/12156188, so that the suggestion would be to do like so:

Instead of:

```
> bash -ec 'true "$(false)"'; echo $?
0
```

```bash
> bash -ec 'var="$(false)"; true "$var"'; echo $?
1
```

But then, it's important to use `-e`.

**Comment by felipecrs** [comment]
BTW, I opened https://github.com/koalaman/shellcheck/issues/2338.

**Comment by felipecrs** [comment]
Fun fact: a new check is available with `shellcheck -o check-extra-masked-returns` which catches such errors.
