### ISSUE TITLE
Thoughts on collection of boilerplates for somewhat common variables

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#1474]
### Discussed in https://github.com/twpayne/chezmoi/discussions/1439

<div type='discussions-op-text'>

<sup>Originally posted by **bradenhilton** September 20, 2021</sup>
Recently I noticed the section on determining the chassis type of the current machine was added to the how to, and it got me thinking about similar things that might be nice to have as variables.

I was wondering what everyone thought about perhaps creating some kind of centralized repo containing boilerplates/snippets that can be used to achieve similar things. I'm mainly focusing on things that can be determined in an abstract way (if the variable itself was highly specific to your needs and your machine(s), there would be little point in adding it to a repo like this) and can also be done on all or most platforms supported by chezmoi.

Some variables that would be nice to have for me personally that I can think of off the top of my head:

- Whether the current machine is a laptop/desktop/mobile - already achieved with the chassis type snippet plus an additional check `if eq .chezmoi.os "android"`.
- The CPU core count of the current machine - mpv assigns duplicate copies of the thumbnailer script that I use to additional threads in order to generate thumbnails faster. This can bog down an older machine if the number of thumbnailer threads is greater than ~1/2 of the core count and the CPU is also being used to play the video.
- The number of displays connected to/active on the current machine - I typically use three displays with my desktop machine (but not always), and no external displays with my ThinkPad or MacBook Pro. Many applications allow settings to the effect of "Always open on display X" etc.

It also occurred to me that some of these could be implemented in chezmoi itself, depending on demand/ease of implementation/scope of course.

Feel free to offer your thoughts and also any ideas for useful variables you might have.</div>

**Comment by VorpalBlade** [comment]
Side note with regards to the chassis snippet: unfortunately it requires a very recent systemd. The systemd version (245) on Ubuntu 20.04 LTS (current LTS version) does not support JSON output. Out of my systems, only my Arch desktop (systemd 249) has the json option.

Perhaps it should be updated to not require such modern features.

**Comment by VorpalBlade** [comment]
@bradenhilton My raspberry pis do not have this:
```console
$ cat /sys/devices/virtual/dmi/id/chassis_type
cat: /sys/devices/virtual/dmi/id/chassis_type: No such file or directory
$ hostnamectl 
   Static hostname: rpi
         Icon name: computer
        Machine ID: XXXXXXXXXXXXXXXXXX
           Boot ID: XXXXXXXXXXXXXXXXXX
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.63-v7l+
      Architecture: arm
```
Nor do Android devices (they obviously don't have hostnamectl as well).
All other Linux computers I have access to are x86-64 based and do have that file.

I would also assume that any Linux distros that don't use systemd (e.g. Gentoo) will not have hostnamectl. I'm also curious about the various BSDs, but I haven't used those for over a decade at this point.

**Comment by bradenhilton** [comment]
@VorpalBlade Could [this](https://web.archive.org/web/20211013083211/https://forums.raspberrypi.com/viewtopic.php?t=215199) be useful?

Perhaps you could do something like

```
if chezmoi.os = linux
    if chezmoi.osRelease.id = raspbian
        if output of tvservice -s | awk '{print $2}' = 0x40001
            headless
    else if output of xrandr --query | grep -c ' connected' = 0
        headless
    else if some kind of wayland check (possibly using wlr-randr?)
        headless
    else
        not headless
```

I understand you don't want to use hostname checks, but it may still be worth using them as a fallback. That way, if you're having an issue with a particular system, you can quickly add it to the hostname check to get up and running, then see if you can better implement an appropriate check for it later.

**Comment by felipecrs** [comment]
I'm just thinking out loud:

We could have a repository called `chezmoi/common-templates` which we could store as much templates as we want, and users could use them with git submodules:

```
# .gitmodules
[submodule "common-templates"]
	path = ".chezmoitemplates/common-templates"
	url = https://github.com/chezmoi/common-templates
```

**Comment by twpayne** [comment]
On further reflection on this, I think that the right place for shared templates is documenting them in chezmoi's user guide so that users can copy them into their own dotfiles repo. Here's my reasoning:

* Complex logic is generally fragile, and when changes are needed it's much easier for a user to modify their own templates than include the logic in chezmoi or make a PR to a shared repo and wait for it to be merged (which might break other users in the process).
* Each user will have a different set of systems that they care about, and while general solutions are hard, specific solutions are much easier, so it's better to leave things in the user's hands.

Specific examples of this:
* Detecting what version of Windows you're running based on registry values and command output is [complex](https://github.com/sindresorhus/windows-release/blob/edb4b7b5efc4c92bcd32d41701f6f727dff0c485/index.js), as @bradenhilton points out in #2085. However, providing the raw registry values is straightforward (#2086) and the user can add the required logic for the Windows versions that they care about.
* Determining "what is a server" is very user-specific. Detecting chassis type depends on multiple factors, and it's unlikely that we'll ever find a method that works for everyone.

So, I'll close this issue with the resolution: "if you have useful templates to share, please submit a PR that adds them to chezmoi's user guide".

Note also: the eager vs. lazy evaluation of arguments to the `and` and `or` template functions comes from Go's `text/template` language. This has changed a little with the release of [Go 1.18](https://go.dev/doc/go1.18) (search for "template" to find the exact details). chezmoi will always use `text/template`.

**Comment by VorpalBlade** [comment]
@twpayne Where in the user guide would you prefer to add something like https://github.com/VorpalBlade/chezmoi_modify_manager? Would you prefer a new page for "third party addons" (thus making it clear you provide no support or guarantees about the code in question) or would it be better to integrate it into for example the `modify_` section?

Perhaps both: third party addons page but a mention in the `modify_` section that a script to handle KDE ini files can be found "on the third party addons page"? This would increase discoverability but also make it clear that users are on their own using it.

**Comment by twpayne** [comment]
Yes, both please. Specifically:

Add it to the user guide, maybe as part of [this section](https://github.com/twpayne/chezmoi/blob/v2.17.0/assets/chezmoi.io/docs/user-guide/manage-different-types-of-file.md#manage-part-but-not-all-of-a-file).

Add it to the [list of related software](https://github.com/twpayne/chezmoi/blob/v2.17.0/assets/chezmoi.io/docs/links/related-software.md).
