### ISSUE TITLE
run_once script not run after modified

### ISSUE THREAD

**Issue by flyxi121** [twpayne/chezmoi#1497]
## Describe the bug

If you change the content of a run_once script it will run again on `chezmoi apply`, but if you change it back again it does not.

## To reproduce

1. Create a run_once script in the chezmoi source directory.
2. Run `chezmoi apply` and confirm that the script was in fact executed.
3. Change the run_once script.
4. Run `chezmoi apply` again and confirm that the script was in fact executed.
5. Change the run_once script back.
6. Run `chezmoi  apply` once more and realize that the script was not executed, even though the file contents changed. 

## Expected behavior

`chezmoi apply` should run every `run_once` script once, meaning that every time the content of the script changes it should be executed.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose apply # A run_once script which echoes "hello" was created and `chezmoi --verbose apply` runs is
diff --git a/script.sh b/script.sh
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..dc58c79dddf60f2d687175853f67513090df1b55 100755
--- a/script.sh
+++ b/script.sh
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+echo "hello"
hello
```
```console
$ chezmoi --verbose apply # The same run_once script with its file contents changed to echo "hi" instead - again run by `chezmoi --verbose apply`. 
diff --git a/script.sh b/script.sh
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..b478a4921ff41fc92df26afdae52978b12f99703 100755
--- a/script.sh
+++ b/script.sh
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+echo "hi"
hi
```
```console
$ chezmoi --verbose apply # The same run_once script with its file contents changed back to echo "hello" - no output.
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor                   
RESULT    CHECK                MESSAGE
warning   version              v2.6.0, built at 2021-10-02T23:54:23Z
ok        os-arch              linux/amd64 (Artix Linux)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   ~/.local/share/chezmoi: no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /usr/bin/zsh
ok        edit-command         found /usr/bin/nvim
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.33.0
ok        merge-command        found /usr/bin/nvim
failed    age-command          found /usr/bin/age, could not parse version from (devel)
ok        gpg-command          found /usr/bin/gpg, version 2.2.29
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
ok        gopass-command       found /usr/bin/gopass, version 1.12.8
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

## Additional context

As far as I understand, chezmoi saves a hex encoded sha256 hash of the script content as key, the name and the execution time of the script as the key's values. 

So when you look at the output of `chezmoi` state after each time you `chezmoi apply` you will get the following:

```console
$ chezmoi --verbose apply # A run_once script which echoes "hello" was created and `chezmoi --verbose apply` runs is
diff --git a/script.sh b/script.sh
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..dc58c79dddf60f2d687175853f67513090df1b55 100755
--- a/script.sh
+++ b/script.sh
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+echo "hello"
hello
$ chezmoi state dump
{
  "configState": {},
  "entryState": {
    "/home/flyxi/script.sh": {
      "contentsSHA256": "1c9d23c245ef06a87f178c5d82221b702084540fe072b329c6a992d6036e6649",
      "type": "script"
    }
  },
  "scriptState": {
    "1c9d23c245ef06a87f178c5d82221b702084540fe072b329c6a992d6036e6649": {
      "name": "script.sh",
      "runAt": "2021-10-07T00:07:57.428003328Z"
    }
  }
}
```
Chezmoi has created one entry with the sha256 hash of the script content as key under "scriptState" and ran the script successfully.

```console
$ chezmoi --verbose apply # The same run_once script with its file contents changed to echo "hi" instead - again run by `chezmoi --verbose apply`. 
diff --git a/script.sh b/script.sh
index e69de29bb2d1d6434b8b29ae775ad8c2e48c5391..b478a4921ff41fc92df26afdae52978b12f99703 100755
--- a/script.sh
+++ b/script.sh
@@ -0,0 +1,3 @@
+#!/bin/sh
+
+echo "hi"
hi
$ chezmoi state dump
{
  "configState": {},
  "entryState": {
    "/home/flyxi/script.sh": {
      "contentsSHA256": "d388ff413e837942d22e80a880a585628552464cc70ff54a7173248e6010a8b3",
      "type": "script"
    }
  },
  "scriptState": {
    "1c9d23c245ef06a87f178c5d82221b702084540fe072b329c6a992d6036e6649": {
      "name": "script.sh",
      "runAt": "2021-10-07T00:07:57.428003328Z"
    },
    "d388ff413e837942d22e80a880a585628552464cc70ff54a7173248e6010a8b3": {
      "name": "script.sh",
      "runAt": "2021-10-07T00:10:09.610529252Z"
    }
  }
}
```
Chezmoi has created one more entry with the new sha256 content of the script and ran the script successfully.

```console
$ chezmoi --verbose apply # The same run_once script with its file contents changed back to echo "hello" - no output.
$ chezmoi state dump
{
  "configState": {},
  "entryState": {
    "/home/flyxi/script.sh": {
      "contentsSHA256": "d388ff413e837942d22e80a880a585628552464cc70ff54a7173248e6010a8b3",
      "type": "script"
    }
  },
  "scriptState": {
    "1c9d23c245ef06a87f178c5d82221b702084540fe072b329c6a992d6036e6649": {
      "name": "script.sh",
      "runAt": "2021-10-07T00:07:57.428003328Z"
    },
    "d388ff413e837942d22e80a880a585628552464cc70ff54a7173248e6010a8b3": {
      "name": "script.sh",
      "runAt": "2021-10-07T00:10:09.610529252Z"
    }
  }
}
```
Chezmoi does not alter the database as the file content hash is already in the database and does not run the script.

**Comment by twpayne** [comment]
Thanks for reporting this. This is an interesting case, and you're right.

#1501 fixes the docs to match the implementation, of course the other option is to fix the implementation to match the docs.

For chezmoi to implement the currently-described behavior ("`run_once_` scripts are run when their contents change"), it would require chezmoi to change how it currently stores the state of `run_once_` scripts to index them by script name and record the last-run contents SHA256. This is possible (although it will require some care to provide a clean migration from the current state storage), but not without risk as it will break people's setups that rely on the existing actual behavior.

On reflection, the current implementation works well for cases like package installation: adding a package to be installed changes to the contents and so triggers the script to be run; removing a package reverts to a previously-seen state and so chezmoi doesn't run the script, which is fine as all the desired packages are already installed anyway. However, it does not cope well with the dynamic configuration of software through scripts. For example, if you have a `run_once_` script that runs 'set foo=bar` and then change it to be `set foo=qux` and then change it back to be `set foo=bar` again, you definitely want the script to run again after the final change.

Let me see if I can come up with a fix to make the implementation match the docs.
