### ISSUE TITLE
Documentation issue in .chezmoiignore examples 

### ISSUE THREAD

**Issue by ArturDorochowicz** [twpayne/chezmoi#1517]
## Describe the bug

.chezmoiignore example in the documentation lists `backups/**` twice with two different explanations. Is it correct? Or one of these should be different?

https://github.com/twpayne/chezmoi/blob/554be67258c8e8cfcd79f834d0ce3caf5324c96d/docs/REFERENCE.md#L798-L809

**Comment by felipecrs** [comment]
Thank you, there is definitely something wrong with this example. :)
