### ISSUE TITLE
Support `.chezmoiroot` file to redirect `init`'s source dir to subfolder 

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1519]
## Is your feature request related to a problem? Please describe.

This is a follow-up of https://github.com/twpayne/chezmoi/issues/891#issuecomment-933742656. The problem of having to run

```
sh <(curl -fsSL https://git.io/chezmoi) -- init --apply --working-tree=~/.local/share/chezmoi --source=~/.local/share/chezmoi/home felipecrs
```

Is that it's a long command, difficult to remember, and breaks the fact that `chezmoi init` would not work by default on all the repositories.

## Describe the solution you'd like

A new file named `.chezmoiroot` (the name is debatable), which I would put in the root of my dotfiles repository and would have contents like so:

```
$ cat .chezmoiroot
home
```

It would tell chezmoi that, when initializing the repository, it should adjust the `sourceDir` to be the `home` subfolder automatically.

This would allow me to remove some workarounds that I have to circumvent this, such as [this](https://github.com/felipecrs/dotfiles/commit/9cafef4d988ce652c0fcf9ad1ea9fc24b3f58c46#diff-1e142e6277b12b7e1110478a24caee8f006a9349e86970c890203d6266209463R35).

I think this is the only thing missing to declare first-class support for subfolders in the dotfiles directory as the source dir. With it in place, the following would work:

```console
sh <(curl -fsSL https://git.io/chezmoi) -- init --apply felipecrs
```

## Describe alternatives you've considered

Described earlier.

## Additional context

I'm quite happy with my dotfiles being in a subdirectory. Previously, I oftenly created wrong files in my home dir because I forgot to add to .chezmoiignore, now I don't have to remember this step anymore.

**Comment by twpayne** [comment]
This is a great proposal and design, thank you @felipecrs :) #1603 should implement it. Let me know how we can improve this.
