### ISSUE TITLE
bashrc osRelease conditions not respected

### ISSUE THREAD

**Issue by codygarver** [twpayne/chezmoi#152]
Thanks for the quick distribution conditional support, I'm back with another Linux request!

Problem:
`~/.bashrc` has different contents across distributions, so `chezmoi apply` can inadvertently wipe a `.bashrc` that has different contents than the initially committed one.

The workaround I tried isn't working, which was to share a `.bashrc` using the new distro conditions, like:
```
{{- if eq .chezmoi.osRelease.id "ubuntu" }}
This is an Ubuntu .bashrc with customizations
{{- end }}
{{- if eq .chezmoi.osRelease.id "arch" }}
This is an Arch .bashrc with customizations
{{- end }}
```
The expected `.bashrc` result on Ubuntu should be:
```
This is an Ubuntu .bashrc with customizations
```

But as of right now it is including/writing the conditions instead of respecting them:
```
{{- if eq .chezmoi.osRelease.id "ubuntu" }}
This is an Ubuntu .bashrc with customizations
{{- end }}
{{- if eq .chezmoi.osRelease.id "arch" }}
This is an Arch .bashrc with customizations
{{- end }}
```

**Comment by twpayne** [comment]
Is `~/.bashrc` being treated as a template?

Run:
    $ basename $(chezmoi source-path)/dot_bashrc*
If the output is `dot_bashrc.tmpl` then there is a bug in `chezmoi`. If the output is `dot_bashrc` then run the following command to make `~/.bashrc` a template:
    $ chezmoi chattr template ~/.bashrc
Once `~/.bashrc` is a template the conditions should be respected.

**Comment by twpayne** [comment]
I think that there might be a bug in `chezmoi` here: `.chezmoi.osRelease` is only populated on if `/usr/lib/os-release` exists, which is only the case on standard Linux systems.

**Comment by codygarver** [comment]
Aha, my issue is not actually a bug.

The affected distro was a derivative and doesn't report as `ID=Ubuntu`, only `ID_LIKE=ubuntu`

Closing my issue.

**Comment by twpayne** [comment]
Great! Thanks for the testing and happy that we solved this :)

**Comment by codygarver** [comment]
Just for people who might stumble upon this post after facing this issue, here is how to add conditions for multiple distributions simultaneously in a chezmoi template:

```
{{- if or (eq .chezmoi.osRelease.id "ubuntu") (eq .chezmoi.osRelease.id "elementary") }}
This is for Ubuntu or elementary OS
{{- end}}
```
