### ISSUE TITLE
Bitwarden integration using rbw

### ISSUE THREAD

**Issue by samip5** [twpayne/chezmoi#1527]
## Is your feature request related to a problem? Please describe.

I'm frustrated when I don't like the Bitwarden CLI tool (bw), but rather want to use rbw.

## Describe the solution you'd like

I'd like to be able to use my existing rbw utility for Bitwarden.

## Describe alternatives you've considered

Using the Bitwarden CLI.

## Additional context

rbw is an unofficial BItwarden CLI written in Rust.
https://crates.io/crates/rbw

**Comment by twpayne** [comment]
> I haven't used bw, so I wouldn't know.

Please could you compare how chezmoi currently uses `bw` [as described in the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#bitwarden-arg) compares with your use of `rbw`. If `rbw` is not documented, then please contact the author to provide suitable documentation so other applications can integrate with it.

> Perhaps it's time to think about supporting plugins/extensions/addons on `chezmoi` which could contribute functions and so.

Adding extra template functions (if they are even needed) is trivial. A plugin system would seriously complicate chezmoi's "download and run a single statically-linked binary" install.

**Comment by twpayne** [comment]
To move this forward, in your initial comment you said:

> I'm frustrated when I don't like the Bitwarden CLI tool (bw), but rather want to use rbw.

When I [asked about the difference between `bw` and `rbw`](https://github.com/twpayne/chezmoi/issues/1527#issuecomment-944451745) you said:

> I haven't used bw, so I wouldn't know.

Which is inconsistent with your first statement.

When [I asked how `bw` differs with `rbw`](https://github.com/twpayne/chezmoi/issues/1527#issuecomment-944644169) you replied only with [it doesn't work](https://github.com/twpayne/chezmoi/issues/1527#issuecomment-944746414):

> I verified that the way you should be able to get things from Bitwarden doesn't work with it.

...without providing any details about what did not work.

To move this issue forward, please provide:
* Either, more details about what did not work,
* Or, what behavior you would like to see.

**Comment by twpayne** [comment]
For info, you can also use rbw as a [custom password manager](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-a-custom-password-manager).

**Comment by samip5** [comment]
> For info, you can also use rbw as a [custom password manager](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-a-custom-password-manager).

That's exactly what doesn't work with rbw as it doesn't output things as JSON.

**Comment by twpayne** [comment]
You can get the raw output with the [`secret` template function](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#secret-arg). You'll probably want to filter the output through `trim` to strip and trailing or leading whitespace, something like:

```
MY_SECRET_FROM_RBW={{ secret "args" "to" "rbw" | trim }}
```
