### ISSUE TITLE
ssh config file bad permissions

### ISSUE THREAD

**Issue by codygarver** [twpayne/chezmoi#155]
Assuming there is `~/.ssh/config` with permissions `664`:
```
touch ~/.ssh/config
chmod 664 ~/.ssh/config
```

When this gets added to chezmoi and then applied, ssh rejects its permissions:
```
$ chezmoi add ~/.ssh/config && chezmoi apply && ssh user@host
Bad owner or permissions on /home/codygarver/.ssh/config
```

This is fixed by `chmod 664 ~/.ssh/config`, but gets reverted by chezmoi eventually.

**Comment by twpayne** [comment]
Please re-open if you have further questions on this topic.
