### ISSUE TITLE
Determine CPU type

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1566]
## What exactly are you trying to do?

So I want to determine if my machine has an Intel CPU or an AMD CPU.

## What have you tried so far?

I think I can do this using `awk '/^vendor_id[[:blank:]]:/ { print $NF; exit }' /proc/cpuinfo` maybe.

That will return either `GenuineIntel` or `AuthenticAMD`.

I was then thinking something like https://www.chezmoi.io/docs/templating/#determine-whether-the-current-machine-is-a-laptop-or-desktop might be possible.

I tried `chezmoi execute-template '{{ (output "awk" "'/^vendor_id[[:blank:]]:/" "{" "print" "$NF;" "exit" "}'" "/proc/cpuinfo") }}'` but it didn't work so well.

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
The arguments to `awk` are not quoted correctly: they are split when they should be merged and there are extra single quotes in there. Try:

```console
$ chezmoi execute-template '{{ output "awk" "/^vendor_id[[:blank:]]:/{ print $NF; exit }" "/proc/cpuinfo" }}'
```

**Comment by twpayne** [comment]
Hope this helps, please re-open if needed.

**Comment by slurikadre** [comment]
This worked perfectly, I must have been to tired to deal with it. For anyone else wondering this is what I did:

```
{{- $cpu := "intel" -}}
{{-  if eq (output "awk" "/^vendor_id[[:blank:]]:/ { print $NF; exit }" "/proc/cpuinfo") "GenuineIntel" }}
{{-  $cpu = "intel" }}
{{-  else if eq (output "awk" "/^vendor_id[[:blank:]]:/ { print $NF; exit }" "/proc/cpuinfo") "AuthenticAMD" }}
{{-  $cpu = "amd" }}
```

`$cpu` will return either `intel` or `amd` depending on the CPU. Only works on Linux hosts with those CPUs, so it won't work on ARM based architectures as they don't have the `vendor_id`. For those you could search for `model name` or whatever field they have instead.

This is useful if your template has a path in it to say a statically compiled binary. Depending on the host's architecture will depend on which binary is used.

**Comment by twpayne** [comment]
Note that the code proposed calls `awk` twice to get the same value. I would instead write it as:

```
{{ $cpu := output "awk" "/^vendor_id[[:blank:]]:/ { print $NF; exit }" "/proc/cpuinfo" }}
{{ if eq $cpu "GenuineIntel" }}
{{    $cpu = "intel" }}
{{ else if eq $cpu "AuthenticAMD" }}
{{    $cpu = "amd" }}
{{ end }}
```

This:
* Only calls `awk` once.
* Ensures that `$cpu` has a value.
* If the vendor is not recognized, then the detected value is available in `$cpu`, which is useful for debugging.
