### ISSUE TITLE
Additional host values based on hostname

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1567]
## What exactly are you trying to do?

I want to look up a particular host with by hostname.

I'm kind of inspired by your idea in https://github.com/twpayne/chezmoi/issues/1333#issuecomment-894816520

## What have you tried so far?

Describe what you have tried so far.

So I have this json object:

```json
{
  "device": {
    "hosts": [
      {
        "hostname": "",
        "wayland": true,
        "x11": false,
        "bootstrap": {
          "submodule_init_vim": false,
          "run_package_manager": false
        }
      }
    ]
  }
}
```

In each host, I've got various preset values. I've used this to refer to each one in my template 

```
{{- if or (eq .chezmoi.hostname "hostname1") }}
{{- $machine := index .device.hosts 0 }}
{{- else if or (eq .chezmoi.hostname "hostname2") -}}
{{- $machine := index .device.hosts 1 -}}

$machine.xxxx.xxxx
```

However I think operating based on the index is ambiguous and a bad idea. I don't think I'll ever need to iterate through all the hosts. The reason is the host can only be itself.

If I store these "extra values" in an object with the name of the hostname as the object name, how would I search the objects for the particular one I want?

I'm thinking a structure like this makes more sense:

```json
{
  "device": {
    "host1": [
      {
        "wayland": true,
        "x11": false,
        "bootstrap": {
          "submodule_init_vim": false,
          "run_package_manager": false
        }
      }
    ],
    "host2": [
      {
        "wayland": true,
        "x11": false,
        "bootstrap": {
          "submodule_init_vim": false,
          "run_package_manager": false
        }
      }
    ]
  }
}
```

If you can think of suggestions to improve my method of storing the data I'm happy to hear.

**Comment by twpayne** [comment]
Ultimately you want a set of boolean flags depending on the hostname. I do this entirely in [my `.chezmoi.toml.templ`](https://github.com/twpayne/dotfiles/blob/master/.chezmoi.toml.tmpl) and would recommend the same approach.

**Comment by slurikadre** [comment]
Yes, that is more a less exactly what I am trying to do. Any particular reason you like `toml`? I had been in the habit of using json, because it's parsable with jq? I'm curious to know the pros/cons of that choice.

**Comment by twpayne** [comment]
As you say, TOML is much easier to template than JSON (particularly given that `text/template` uses `{{` and `}}`), and TOML is also much easier to write as a human, and is a much better defined language than YAML (have you seen https://noyaml.com/?). That said chezmoi supports all three, so chose whichever you prefer.

For the `jq` argument, in chezmoi you already have the structured data and can manipulate it with templating, so you shouldn't need `jq` unless you're manipulating data outside chezmoi as well.

**Comment by slurikadre** [comment]
> As you say, TOML is much easier to template than JSON (particularly given that `text/template` uses `{{` and `}}`), and TOML is also much easier to write as a human,

That's actually a very good argument, you've sold me on converting it. I do find it annoying to write json, but really only did it because `jq` worked so nicely with shell scripts.

> and is a much better defined language than YAML (have you seen https://noyaml.com/?)

No I hadn't seen that. I only really have had to write YAML for docker-compose and cloud-init, so can't say I've had a huge lot of experience with that.

> so you shouldn't need jq unless you're manipulating data outside chezmoi as well.

That's something I want to reduce/stop doing anyway. About the only time I've been doing that is when I've been looping through something and printing out multiple files for templates like I did here https://github.com/twpayne/chezmoi/issues/1369#issuecomment-908450683

It wasn't ideal, and I think I still want to explore @bradenhilton 's alternative https://github.com/twpayne/chezmoi/issues/1369#issuecomment-907209544 and keep it all in chezmoi.

**Comment by slurikadre** [comment]
I was able to get the block id of my LVM device using:

```
lsblk -o FSTYPE,UUID | awk '/^crypto_LUKS/ { printf $NF; exit }'
````

However, I seem to be having issues putting that into  the `<output>` command. I'm having trouble searching for `<output>`'s usage. So ambiguous.

```
$lvmroot = (output "lsblk" "-o" "FSTYPE,UUID" "|" "awk" "/^crypto_LUKS/ { printf $NF; exit }" )
```

I think it might have something to do with the pipe.

> chezmoi: template: chezmoi.toml:37:20: executing "chezmoi.toml" at <output "lsblk" "-o" "FSTYPE,UUID" "|" "awk" "/^crypto_LUKS/ { printf $NF; exit }">: error calling output: exit status 32

**Comment by twpayne** [comment]
Pipes are interpreted by the shell, and the `output` template function does not invoke your shell.

You can use `output` to invoke the shell explicitly, for example:

```
{{ output "sh" "-c" "lsblk -o FSTYPE,UUID | awk '/^crypto_LUKS/ { printf $NF; exit }'" }}
```

**Comment by slurikadre** [comment]
AH, that makes sense then. Thanks!

I couldn't find any documentation about `<output>` is this in the Go documentation or somewhere else?

**Comment by twpayne** [comment]
> I couldn't find any documentation about `<output>` is this in the Go documentation or somewhere else?

`output` is a chezmoi-specific template function, [documented in the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#output-name-arg).
