### ISSUE TITLE
what is the `chezmoi.yaml` equivelent of `--source ~/foo/bar`

### ISSUE THREAD

**Issue by kquinsland** [twpayne/chezmoi#157]
Hi!  I'm giving this tool a try, and i've got a slightly different repo/sync/org schema in mind. 

I am trying to adopt chezmoi into this existing schema.  to do so, i need the default source to be in a different location.  I have tried to add this to my `chezmoi.yaml` file, but it does not appear that the updated source path was picked up:

```
source:~/foo/bar
```

Thus, my question: **What do i need to add in `chezmoi.yaml` to change the default source dir?**

If this is *not* supported, please let me know. I'll set up an `alias chezmoi=chezmoi -S ~/foo/bar` or, if i can find enough time in the coming days, get a PR open.

Thanks for your time :)

**Comment by twpayne** [comment]
This is supported. The line you need is:

```
sourceDir: /full/path/to/foo/bar
```

Notably, `~` and environment variables are *not* expanded - you need to give the full absolute path.

**Comment by kquinsland** [comment]
thank you much @twpayne !
