### ISSUE TITLE
[Website] Variables table on website triggers horizontal scroll

### ISSUE THREAD

**Issue by mkasberg** [twpayne/chezmoi#1577]
## Describe the bug

When you visit https://www.chezmoi.io/docs/reference/#variables, the table is wider than the content area width so it scrolls horizontally. This experience could be improved, particularly since the table is tall and therefore hides the scrollbar at the bottom. Ideally, the description column on the right would also be wider.

![image](https://user-images.githubusercontent.com/12214617/139561975-fbbbd2c6-3e17-4f68-aaeb-ccda8530b4ac.png)

## To reproduce

Visit https://www.chezmoi.io/docs/reference/#variables. I used Firefox with a fullscreen window on a 1080p monitor. The problem can also be reproduced in Chrome.

## Expected behavior

I think there are a variety of ways to improve the experience. Here are some possibilities:
* Make the content area max width of the site wider. (It doesn't make sense to have whitespace on both sides with a horizontal scroll in between.)
* Make the font size in the table smaller.
* Reduce the padding in the table.
* Remove the first column, `Section`, from the table, and perhaps change that to a heading or combine with the second column, `Variable`.
* Eliminate the table completely. For example, format similarly to [commands](https://www.chezmoi.io/docs/reference/#commands) with an h3 heading per variable.

If any of these ideas sound appealing, I could take a stab at one or more of the above ideas in a PR.

## Additional Context

It's worth noting that there's a similar issue in the table on the [Comparison](https://www.chezmoi.io/docs/comparison/) page, and some solutions above might solve the issue in both places while others wouldn't. In any case, I don't think the issue on the comparison page is quite as problematic since the table's shorter there and it's also less important to see all columns at once, but it might still be worth thinking about in a broader context or coming up with a separate solution for that page.

**Comment by twpayne** [comment]
Thanks for reporting this and for the offer of help. Indeed, the [Hugo Book template](https://github.com/alex-shpak/hugo-book) used by chezmoi doesn't handle wide tables well.

I actually want to re-vamp the documentation to use a better system, and was thinking of switching to [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/), but haven't had time to do this yet.

One complication is that chezmoi uses a single source of truth for the documentation (`docs/REFERENCE.md`) from which each command's long help text and examples are generated. Changes to the structure of `docs/REFERENCE.md` will also require updates to the help extraction code.

**Comment by mkasberg** [comment]
Nice! Seeing as you're planning on migrating to a different template soon, I won't put effort into a PR right now. Material for MkDocs looks nice.

And I don't mind if you want to close this to keep the open issues clean :slightly_smiling_face:

**Comment by twpayne** [comment]
Thank you, I would prefer to keep this issue open as it is a genuine problem with the current docs.
