### ISSUE TITLE
Maximum depth of replacement has been reached. Entry uuid: (uuid here)

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1581]
## What exactly are you trying to do?

I've written a `.chezmoitemplate` and the code being passed into the template is coming from my password manager (keepassxc). It works but I do see this error, about "Maximum depth of replacement has been reached."

I wonder if this is a bug with Chezmoi or with the library chezmoi uses for KeepassXC?

## Describe what you have tried so far.

I have this template:

#### git/gituser

```
[user]
	name = {{ .account }}
	email = {{ .email }}
	signingkey = {{ .signingkey }}
```

I have this script:

#### run_before_git_templates.sh.tmpl

```bash
printf "%s " "{{ keepassxcAttribute "/chezmoi/git/primary" "user" | quote }}" > \
               "$XDG_DATA_HOME"/chezmoi/private_dot_config/git/users/primary.tmpl
```

This is what is in my password manager:

```
{{- template "git/gituser" dict "account" "Joe Bloggs" "email" "joe@example.com" "signingkey" "0x1234567890ABCDEF1234567890ABCDEF12345678" }}
```

Note here, is there a way I can skip this step and use `keepassxcAttribute` inside my template data?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor

RESULT    CHECK                MESSAGE
warning   version              v2.7.1, built at 2021-10-18T12:05:22Z
ok        os-arch              linux/amd64 (Arch Linux)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   ~/.local/share/chezmoi: no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /usr/sbin/nvim
ok        umask                022
ok        git-command          found /usr/sbin/git, version 2.33.1
ok        merge-command        found /usr/sbin/vimdiff
ok        age-command          age not found in $PATH
ok        gpg-command          found /usr/sbin/gpg, version 2.2.29
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/sbin/keepassxc-cli, version 2.6.6
ok        keepassxc-db         ~/container/Passwords.kdbx is a file
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/sbin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

**Comment by twpayne** [comment]
I don't think the "Maximum depth of replacement" message comes from chezmoi or text/template - there are no strings like this in the source code, so I suspect it's coming from the KeepassXC CLI.

Try running chezmoi with the `--debug` flag: amongst the output will be the exact command that chezmoi executes to call the KeepassXC CLI, and then try running this command directly from the terminal.

Note that your `run_before_git_templates.sh.tmpl` script modifies files in chezmoi's source directory, which, as discussed before, you should not do.

**Comment by bradenhilton** [comment]
> Note that your `run_before_git_templates.sh.tmpl` script modifies files in chezmoi's source directory, which, as discussed before, you should not do.

@twpayne Could you elaborate on this further? I'm currently using `.chezmoiexternal` to download scripts for `mpv` to `<chezmoi source dir>/symlinks/mpv/scripts` (which is ignored) and everything seems to work as I'd expect.

I can see how things like scripts creating scripts could cause issues but simple file downloads don't appear to have any obvious problems (other than `chezmoi` attempting to apply a file that failed to download and so does not exist).

**Comment by twpayne** [comment]
I'm referring to this, which (assuming `$XDG_DATA_HOME` is set to `$HOME/.local/share`) is a `run_before_` script that modifies a file in chezmoi's source directory:

> #### run_before_git_templates.sh.tmpl
> ```shell
> printf "%s " "{{ keepassxcAttribute "/chezmoi/git/primary" "user" | quote }}" > \
>                "$XDG_DATA_HOME"/chezmoi/private_dot_config/git/users/primary.tmpl
> ```

**Comment by slurikadre** [comment]
> I'm referring to this, which (assuming `$XDG_DATA_HOME` is set to `$HOME/.local/share`) is a `run_before_` script that modifies a file in chezmoi's source directory:

When I wrote that script I felt it was wrong. I like to not use scripts if I can.

What I want to know is if I use a template can I store, in my password manager?

```
{{- template "git/gituser" dict "account" "Joe Bloggs" "email" "joe@example.com" "signingkey" "0x1234567890ABCDEF1234567890ABCDEF12345678" }}
```

Then my template would simply contain:

```
{{ keepassxcAttribute "/chezmoi/git/primary" "user" | quote }}
```

Or should it contain something more like:

```
{{- template "git/gituser" dict "account" {{ keepassxcAttribute "/chezmoi/git/primary" "user" | quote }}  }}
```

Syntactically that won't work? Can I have password manager code within a `{{ template }}`?

Sorry for all the questions.

This is what I'm trying to achieve with my script:

```bash
{{- if not .ephemeral }}
{{-   if .personal }}
    printf "%s " "{{ keepassxcAttribute "/chezmoi/git/primary" "user" | quote }}" > "$XDG_DATA_HOME"/chezmoi/private_dot_config/git/users/primary.tmpl
{{-   end }}
{{-   if .work }}
    printf "%s " "{{ keepassxcAttribute "/chezmoi/git/secondary" "user" | quote }}" > "$XDG_DATA_HOME"/chezmoi/private_dot_config/git/users/secondary.tmpl
{{-   end -}}
{{- end -}}
```

**Comment by slurikadre** [comment]
It's worth noting I just upgraded to chezmoi-2.7.4-1. I wanted to congratulate @twpayne on this latest release. You seem to really care about this project, and that's great.

I was thinking about this later today. What is normally the recommended approach?

**Comment by twpayne** [comment]
Thanks for the kind words :)

> I was thinking about this later today. What is normally the recommended approach to dealing with sensitive data in templates?

There's [a whole section in the how-to dedicated to this](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#keep-data-private). I would recommend invoking your password manager in your templates. KeepassXC is a bit annoying because you have to type in your password each time, it might be worth investigating if there's a way of avoiding this.

**Comment by slurikadre** [comment]
> There's [a whole section in the how-to dedicated to this](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#keep-data-private). I would recommend invoking your password manager in your templates.

Ah. So what your saying is store the password manager code in the template in `.chezmoitemplates` and not in the .tmpl file containing `{{ template .... }}` Have the logic for which template to run in the .tmpl file.

What I had found was when I stored the dict in the password manager and tried putting that into the .tmpl in `~/.local/share/chezmoi/git/user/primary.tmpl` was it would literally print that out into `~/.config/git/users/primary` instead of the contents of `.chezmoitemplates/git/user `with substituted data.

That's why i considered my crappy `run_before` scripts.

> KeepassXC is a bit annoying because you have to type in your password each time, it might be worth investigating if there's a way of avoiding this.

It does cache your password, per `chezmoi apply`

I'm wondering whether KeepPassXC is even the right tool for the job. I only have two machines, so I kinda want something open-source and managed on my computer (not centrally managed) on a webserver. I originally looked at `pass` but that's hell slow as I have a 4096 bit RSA key on a Yuibkey, and then the decryption happens on the Yuibkey for each secret. I don't imagine `gopass` would be a lot faster.

1pass and lastpass are both proprietary, and online. Bitwarden is open source, but would require me setting these things up on a server.

Maybe I could run https://www.vaultproject.io/ locally, it seems [pretty small](https://archlinux.org/packages/community/x86_64/vault/) and for this purpose?

**Comment by slurikadre** [comment]
>  I only have two machines, so I kinda want something open-source and managed on my computer (not centrally managed) on a webserver.

I've been looking more at https://learn.hashicorp.com/vault and it does seem appropriate.

I do have a machine on my local area network which runs docker. it also has a httpd server. I'm thinking I might just bite the bullet and run a [vault docker container](https://hub.docker.com/_/vault).

I suppose given docker is quite small, if I was out with my laptop and needed to `chezmoi apply` i could run that same docker container locally with a different `docker-compose.yml`, that points to a local configuration instead of the paths on my server.

**Comment by slurikadre** [comment]
I like the idea of using Vault to provision Chezmoi, because it can provision: 

- entire files like ssh keys, it can also 
- [output data in json](https://learn.hashicorp.com/tutorials/vault/getting-started-first-secret?in=vault/getting-started#getting-a-secret), which would mean chezmoi would be able to read that nicely with the `from_json` keyword if I were to choose.

However Vault's power would lie in it's back end storage options (I'd only ever be using disk storage) and I'd likely never need the dynamic secret features.

Vault doesn't seem suited for use as a password manager [1](https://news.ycombinator.com/item?id=22535262), [2](https://news.ycombinator.com/item?id=22535762), so maybe it would be better for me to migrate away from KeepassXC to Bitwarden instead.

**Comment by slurikadre** [comment]
Anyway. I think this one can be closed as it isn't a Chezmoi bug. It seems @twpayne's dotfiles use [1Password and LastPass](https://github.com/twpayne/dotfiles/blob/master/.chezmoi.toml.tmpl#L80). I should be able to do more a less the same thing with my Bitwarden instance. I would still like some clarification re https://github.com/twpayne/chezmoi/issues/1581#issuecomment-960378024 if at all possible.

If anyone has any advice/expertise about using Hashicorp Vault (or comes across this post in the future) it'd be nice to know what you think.

In the meantime I might create some fallback logic that does in fact use `pass` or `gopass`. I can use this if I am in a pinch and need to regenerate my dotfiles when out of the house with my laptop. The only reason I wasn't using those things was because of the performance of my Yubikey ([mentioned above](https://github.com/twpayne/chezmoi/issues/1581#issuecomment-960378024), maybe someday I'll buy a new one that supports ed25519 keys and that will improve things. I think that's a much less annoying solution to spooling up a local Bitwarden/Hashicorp Vault docker container as I posed in https://github.com/twpayne/chezmoi/issues/1581#issuecomment-960495356.

The logic for that could be something like `ping -c 1 bitwarden.web.internal > /dev/null` (`web` being the name of my reverse proxy, and `.internal` being a TLD I use internally). If it fails, then the `.chezmoi.toml.tmpl can fallback to using a local secret.

This is because *most* of the time I am working from home. I don't want to open my Bitwarden instance to be internet facing. I suppose in the future I may consider a VPN (wireguard perhaps) server on my LAN, which would allow such functionality.
