### ISSUE TITLE
cannot use .chezmoiignore

### ISSUE THREAD

**Issue by kaanyalova** [twpayne/chezmoi#1582]
## What exactly are you trying to do?
try ignoring files so it won't be transfered to git repo when i run `chezmoi add file`
Describe in as much detail as possible.
for example when i add  `test/somefile` to .chezmoiignore and i try to add `test` directory using `chezmoi add test` `somefile` won't be ignored 

## What have you tried so far?

Describe what you have tried so far.
tried putting `test/*` , `test` , `test/` to .chezmoiignore but it won't ignore any files

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```
```
diff --git a/test b/test
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/test
```
## Output of `chezmoi doctor`

```console
$ chezmoi doctor
```
```
RESULT    CHECK                MESSAGE
warning   version              v2.6.0, built at 2021-10-02T23:54:23Z
ok        os-arch              linux/amd64 (Manjaro Linux)
ok        executable           /usr/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   ~/.local/share/chezmoi: no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /usr/bin/micro
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.33.0
ok        merge-command        found /usr/bin/vimdiff
ok        age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.29
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

**Comment by twpayne** [comment]
Thanks for reporting this. `chezmoi add` currently does not respect `.chezmoiignore`, but I think it should. Fix coming up.
