### ISSUE TITLE
Not all attributes are available from chezmoi chattr

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#1587]
## Describe the bug

I expected that chezmoi chattr would work to set all the attributes described in https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#source-state-attributes

However, at least the create attribute cannot be set that way. I haven't checked if there are other unsupported attributes for chattr, but the list in `chezmoi chattr --help` looks notably shorter than in the reference. While some of these might be tricky/impossible to set and have sensible behaviour (such as `symlink`), I don't see how setting `create` would be a problem.

## To reproduce

Steps to reproduce the behavior.
```console
$ touch foo
$ chezmoi add foo
$ chezmoi chattr +create foo
chezmoi: create: unknown attribute
```

## Expected behavior

chezmoi should change the attribute to prefix the file with `create_` in the source state.

## Output of command with the `--verbose` flag

Doesn't change anything in the output.

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.7.4, commit 785bd8464fc6fc6503ada0581f03053f3fbdf8b0, built at 2021-11-02T00:23:54Z, built by goreleaser
ok       os-arch              linux/amd64 (Ubuntu 20.04.3 LTS (Focal Fossa))
ok       executable           ~/bin/chezmoi
ok       config-file          ~/.config/chezmoi/chezmoi.yaml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /usr/bin/zsh
ok       edit-command         found /usr/bin/code
ok       umask                002
ok       git-command          found /usr/bin/git, version 2.33.1
ok       merge-command        found /usr/bin/bcompare
ok       age-command          age not found in $PATH
ok       gpg-command          found /usr/bin/gpg, version 2.2.19
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
ok       keepassxc-command    found /usr/bin/keepassxc-cli, version 2.6.6
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

**Comment by twpayne** [comment]
Thanks for opening this. Prefixes like `create_` and `modify_` really change the type of entry rather than its attributes. #1590 implements this.
