### ISSUE TITLE
Add update command

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#159]
`chezmoi` uses relies on the user's source version control system to share changes across machines. You then need to run `chezmoi apply` on each machine.

These commands should be merged into a single `chezmoi update` command that does the following:

1. Updates the source directory according to the user's VCS (e.g. `git pull --rebase` if the VCS is git).
2. Runs `chezmoi apply`.

This will allow a single `chezmoi update` on a machine to update that machine to the user's desired state.

**Comment by tralston** [comment]
@twpayne How would I do a pull without applying? Especially during testing, and adapting existing machines to the chezmoi system, I don't want to automatically overwrite everything. I'd like to:
1. `chezmoi update` (to get the latest changes from my repo)
2. Analyze it with `chezmoi diff` to maker sure I haven't missed something on my local system.

I tried using `chezmoi update -a false` and `chezmoi update -a 0` but none of those will allow me to signal the `update` command to NOT `apply` right after. How can this be done?

**Comment by tralston** [comment]
I can do this by the following:

1. `chezmoi cd`
2. `git pull`
3. `exit`
4. `chezmoi diff`

It's a workaround, but still long-winded. I'd like to just run `chezmoi update --no-apply && chezmoi diff` or something similar.

**Comment by twpayne** [comment]
`chezmoi apply --dry-run` (or `chezmoi apply -n`) should do the trick.

**Comment by twpayne** [comment]
Sorry, what I wrote isn't quite right - the `--dry-run` will apply to `git pull` as well so it won't actually pull.

`chezmoi source pull && chezmoi diff` is what you want, I think.

**Comment by twpayne** [comment]
You asked a good question, I added it to the docs (it wasn't there before) in #391.
