### ISSUE TITLE
Docs need update after #1571 "Create parent directories for externals if needed"

### ISSUE THREAD

**Issue by ArturDorochowicz** [twpayne/chezmoi#1594]
## Describe the bug

I think the documentation should be updated after #1571 "Create parent directories for externals if needed". Unless I'm misunderstanding that PR.
 
https://github.com/twpayne/chezmoi/blob/56b31f931b2f4e77b3f127914bc50e4d1a5c0ddd/docs/REFERENCE.md#L739-L741

Link to source view:
https://github.com/twpayne/chezmoi/blob/56b31f931b2f4e77b3f127914bc50e4d1a5c0ddd/docs/REFERENCE.md?plain=1#L739-L741

## To reproduce
N/A

## Expected behavior
N/A

## Output of command with the `--verbose` flag
N/A

## Output of `chezmoi doctor`
N/A

**Comment by twpayne** [comment]
Thanks for spotting this :)
