### ISSUE TITLE
Output chezmoi diff in reverse

### ISSUE THREAD

**Issue by lcrockett** [twpayne/chezmoi#1599]
## Is your feature request related to a problem? Please describe.

Not related to a problem.

## Describe the solution you'd like

As with `git diff -R` i'd like to use `chezmoi diff` with a similar `--reverse` option to reverse the the diff output. In some cases it makes sense to see a `chezmoi` diff in reverse if changes happened in the target state and you'd like to logically deduce how the git diff of the `chezmoi` repository would look like. It makes more sense if you use colourized diff output, in my case via an external pager (`diff-so-fancy`).

## Describe alternatives you've considered

None.

## Additional context

Cheers on the continuous high quality improvements to `chezmoi` !

**Comment by twpayne** [comment]
FWIW, `-R` was already taken as a global option to refresh externals, so you only get the long `--reverse` option :(

**Comment by lcrockett** [comment]
I'd prefer the long version anyways, makes it easier to understand arguments used instead of seeing `-R -B -d -f -q -a -P -VV -3 +23 /3 *298` etc... ;-)

Cheers !
