### ISSUE TITLE
toml support?

### ISSUE THREAD

**Issue by jhillyerd** [twpayne/chezmoi#16]
Cool project, may try it out this weekend.

Any thoughts on supporting toml for the data file? It's already an indirect import.  YAML is pretty terrible, and considered harmful by many.

**Comment by twpayne** [comment]
Thanks for the feedback! `chezmoi` uses github.com/spf13/viper to read its configuration file, which includes support for TOML, JSON, and others. I've now activated support for all these formats, including TOML.

**Comment by jhillyerd** [comment]
Awesome, thank you.  Will give it a shot soon.
