### ISSUE TITLE
Auto-upgrade chezmoi if codebase bumps chezmoi version

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1600]
## Is your feature request related to a problem? Please describe.

So, now I bumped the minimum version for chezmoi in my repository with the `.chezmoiversion`. While I know what needs to be done if my dotfiles is installed in a PC with an outdated version of chezmoi, it's a bit tedious process for my colleagues who are using the same dotfiles as me. I must teach them that they need to upgrade chezmoi by theirselves before issuing the `apply` command again, considering that they came from the `update` command.

## Describe the solution you'd like

chezmoi could offer to self-upgrade in the case the codebase requires a newer version during the `update` command. If `--force`, it upgrades unattendedly, otherwise, it offers the user which can proceed with the confirmation.

## Describe alternatives you've considered

I have a wrapper script called `full-upgrade`, there, to work around this issue in the future, I'm upgrading chezmoi before trying to run `chezmoi update`. But it was not always this way, so someone who had an old revision of the `full-upgrade` script would still have to do the manual procedure.

## Additional context

None

**Comment by twpayne** [comment]
This is tricky to implement: chezmoi would have to read the source state, including reading `.chezmoiversion`, and then offer to upgrade itself and re-invoke itself with its original arguments. It is trivial to implement with a wrapper script: run `chezmoi upgrade` before running `chezmoi update`.

Given the easy work-around and the fact that chezmoi is for individuals managing their dotfiles, not a general [configuration management system](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#can-i-use-chezmoi-to-manage-files-outside-my-home-directory), I'm going to close this.
