### ISSUE TITLE
Documentation issue with `{{- if .github}}`: map has no entry

### ISSUE THREAD

**Issue by galou** [twpayne/chezmoi#161]
I may not have understood everything but I tried to use a template where something was added if a field existed in `chezmoi.yaml`. In principle, your example with `{{- if .github}}`.

I got the error
```
at <.github>: map has no entry for key "github"
```
in the case that github doesn't exist.

I solved this with
```
{{- if (index . "github") }}
```

If this is the correct way to do it, please update the documentation.

**Comment by twpayne** [comment]
Thank you very much for the bug report and fix :)

**Comment by galou** [comment]
Woah, that was quick! Thank!

**Comment by galou** [comment]
You may have one extra space though.
