### ISSUE TITLE
Add Packaging usecase to Makefile

### ISSUE THREAD

**Issue by Toasterson** [twpayne/chezmoi#1610]
## Is your feature request related to a problem? Please describe.
The current Makefile is intended to be used by the CI to produce downloadable binaries. This is counter productive for most Operating system packaging workflows. As concrete example. In OpenIndiana (the illumos reference distribution) we build software by checking out the git sources of oi-userland and downloading a source tarball into a specific directory into that tree. We then run the Makefile with build and install targets (as is common) and set the output directory to a custom created directory tree where the Makefile is supposed to install the binary. This tree is then used to create the Package manifest which is the textfile containing which files and metadata is going to be installed. To make this process work, we need to patch the Makefile to Hardcode the version number and disable cross-compilation. see https://github.com/OpenIndiana/oi-userland/blob/5629024fa7e6411597f32f6b40374e720f4e3d13/components/sysutils/chezmoi/patches/01-only-build-illumos.patch 

## Describe the solution you'd like
The Source tarball should contain a Makefile suitable for packaging. This means the Makefile follows the following conventions.
- The Makefile does not call git to find what version it is building.
- The Version can be overridden via Environment variable.
- The `install` target supports `DESTDIR` variable
- The default target only builds the source for the current Host os (no cross compilation) or if the Makefile has a documented build target for that purpose. 

Additionally the Source Tarball should contain a Packaging specific document giving the following instructions to the reader
- What additional software must be installed for this software to build
- What additional software can be installed to enable additional features and what flags are needed to compile that additional software
- Which commands to use to build for the target Host os and install the binary in a directory tree of their choosing for example 
```bash
make build
DESTDIR=${PROTO_DIR} make install
```

**Comment by twpayne** [comment]
Thank you very much for opening this issue :)

It's true that the current `Makefile` is primarily targeted at developers, not packagers. I'll fix to to behave as you specify - thank you for the detailed specification.

chezmoi builds as a standard Go project and many packaging managers have infrastructure for building Go projects, which is likely why this issue has not been raised before.

For info, there is specific [information for packagers in chezmoi's contributing guide](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#packaging), which hopefully goes some way towards meeting the requirements of the packaging-specific document.

**Comment by twpayne** [comment]
Hopefully #1617 should address everything here. Please take a look :)

cc @bardo and @torculus
