### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by MuXiu1997** [twpayne/chezmoi#1620]
## Is your feature request related to a problem? Please describe.

`chezmoi` often fails when downloading the urls in `.chezmoiexternal.yaml`. I need to use a proxy to download those urls, but `chezmoi` does not support proxy.

## Describe the solution you'd like

`chezmoi` should allow users to configure proxy addresses, for example:

````shell
$ chezmoi apply -R -p 'socks5://127.0.0.1:1080'
````

or:

````shell
$ chezmoi apply -R --proxy 'socks5://127.0.0.1:1080'
````

## Describe alternatives you've considered

```shell
$ ALL_PROXY=socks5://127.0.0.1:1080 chezmoi apply -R
```

**Comment by twpayne** [comment]
Thanks for reporting this. By default chezmoi respects the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables. This is part of the Go standard library that chezmoi uses (specifically, chezmoi uses the [`DefaultTransport`](https://pkg.go.dev/net/http#RoundTripper) which uses [`ProxyFromEnvironment`](https://pkg.go.dev/net/http#ProxyFromEnvironment)). Go's standard library supports SOCKS5 proxies.

Does
```console
$ HTTP_PROXY=socks5://127.0.0.1:1080 chezmoi apply -R
```
work for you?

**Comment by MuXiu1997** [comment]
Thank you very much for your reply! It worked! I didn't even know about [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment) until now.
Maybe add how to use proxies to the [How-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md).
