### ISSUE TITLE
Add a `git-archive` external type that respects `.gitignore` files

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#1623]
## Is your feature request related to a problem? Please describe.

As proposed by @felipecrs in [this comment](https://github.com/twpayne/chezmoi/issues/1421#issuecomment-964473844) in #1421, importing archives generated by git should respect `.gitignore` files.

## Describe the solution you'd like

Described perfectly by @felipecrs in https://github.com/twpayne/chezmoi/issues/1421#issuecomment-964473844.

## Describe alternatives you've considered

n/a

## Additional context

n/a

**Comment by felipecrs** [comment]
> For what it's worth, I'll probably use https://pkg.go.dev/github.com/go-git/go-git/plumbing/format/gitignore to implement this.

_Originally posted by @twpayne in https://github.com/twpayne/chezmoi/issues/1421#issuecomment-967711063_

Awesome, so no new deps!

**Comment by twpayne** [comment]
As chezmoi's `.chezmoiignore` files and syntax and subtly incompatible with `.gitignore` files, and this problem can be solved with a `.chezmoiignore` file, closing this.
