### ISSUE TITLE
Add files modified externally via run_once_* script - timeout acquiring persistent state lock

### ISSUE THREAD

**Issue by rustikus** [twpayne/chezmoi#1625]
## What exactly are you trying to do?

I would like to automatically add external modified config files to chezmoi. The proposed way by using symlinks is not working as the symlinks are automatically overwritten with the file of the corresponding application. Another problem is that I would like to include encrypted files, too.

So my thought was to simply use an run_once_ script to (re-)add the changed files by using a simple script and the hash function of templates. The script works fine if I execute the shell script directly. The problem occurs if it is called by chezmoi due to timeouts linked to persistent state.

## What have you tried so far?

This is an example from my current script (run_once_externalchanged-configs.sh.tmpl):

```sh
#!/bin/zsh 

chezmoi_changed='^M(M|D|\s)'

{{ if (eq .chezmoi.os "darwin") -}}

# rclone.conf hash: {{ joinPath .chezmoi.homeDir ".config/rclone/rclone.conf" | sha256sum }}
LIST_ENC=(
".config/rclone/rclone.conf"
)

for VAR in $LIST_ENC
do
  if [[ $( chezmoi status {{ joinPath .chezmoi.homeDir "$VAR" | quote }} ) =~ $chezmoi_changed ]]; then
    echo "Encrypted $VAR changed"
    chezmoi add --encrypt {{ joinPath .chezmoi.homeDir "$VAR" | quote }}
  fi
done

{{- end }}

```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.7.5, commit 53bb61524468afe3262d6d8089fdc6912dbccb34, built at 2021-11-07T17:04:07Z, built by Homebrew
ok       os-arch              darwin/arm64
ok       executable           /opt/homebrew/bin/chezmoi
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /opt/homebrew/bin/nvim
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.30.1
ok       merge-command        found /usr/bin/vimdiff
ok       age-command          age not found in $PATH
ok       gpg-command          found /opt/homebrew/bin/gpg, version 2.3.3
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
ok       pass-command         found /opt/homebrew/bin/pass, version 1.7.4
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context

Thanks a lot for all the effort you put into chezmoi!

**Comment by twpayne** [comment]
Thanks for your kind words :)

So what's happening here is that chezmoi stores its persistent state (e.g. which `run_once_` scripts have been run) in a database which is locked while `chezmoi apply` is running. This means that you can't run chezmoi commands that need to read and write the state (like `chezmoi status` and `chezmoi add`) inside scripts run by `chezmoi apply`. Changing this behavior is not easy as the database that chezmoi uses (go.etcd.io/bbolt) only supports a single writer.

In this particular case I would suggest either writing a wrapper script around `chezmoi apply` that runs your script before running `chezmoi apply`.

Another option for you might be the [`re-add` command](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#re-add) which re-encrypts files if needed.

**Comment by rustikus** [comment]
Thanks for the detailed explanation!

It really looks like a `chezmoi re-add` is a very simple way to achieve what I was looking for. So I will simply write a wrapper which executes `chezmoi re-add` before `chezmoi apply`. 

Just one small question. Does `chezmoi re-add` warn me if the file was also changed independently in the source state?

**Comment by twpayne** [comment]
> Does `chezmoi re-add` warn me if the file was also changed independently in the source state?

No, but you should have the previous version in your git history.

**Comment by rustikus** [comment]
OK, then I might use a wrapper script. Thanks for the clarification!
