### ISSUE TITLE
Same file different location

### ISSUE THREAD

**Issue by meznaric** [twpayne/chezmoi#164]
Use case:
 I want to keep my vimrc in sync between Ubuntu and Mac. Unfortunately locations are different.
On Mac the location is in `~/.vim/init.vim` and on Ubuntu `~/.config/nvim/init.vim`

I do not want to have 2 files the same that have different conditional in the template, how would you achieve that?

**Comment by twpayne** [comment]
Hmm, interesting problem. Some ideas:

1. Make them both symbolic links to the same file in a common location (say `~/.meznaric/init.vim`), and then use `.chezmoiignore` to only create one symbolic link on each machine.
2. Simply have both present on both machines. Ugly.
3. We could add a template function to `chezmoi` to include the contents of a file, say `includeSourceFile`. You'd then put the common data in a single file, each `init.vim` would be a template that used that function if `.chezmoi.os` matches, or generate an empty file otherwise.

My preference would be for option 1, as you can do this with the existing functionality in `chezmoi`. I'd like to think through the consequences of 3 before adding it.

**Comment by twpayne** [comment]
Let me know how you get on, and please re-open this issue to continue the discussion here. Thanks again for raising this interesting case :)

**Comment by tapayne88** [comment]
👋 Hi Tom Payne, firstly great tool and great name!

I'm having a similar problem but I'm struggling to get `.chezmoiignore` templating to work. I've got something similar to the below in my `.chezmoiignore` file:
```
{{- if eq .chezmoi.os "darwin" }}dot_dir_colors{{ else }}dot_dircolors{{ end }}
```

However when I run `chezmoi apply` both files are restored. When I place the same snippet in a file like `dot_foo` it behaves as expected echoing the appropriate string into the target directory. 

I'm sure I'm missing something obvious but any advice would be greatly appreciated!

Tom Payne

**Comment by twpayne** [comment]
Ha ha! Hello Tom Payne :)

`.chezmoiignore` works with the target file names, not the source file names. Can you try:

```
{{- if eq .chezmoi.os "darwin" }}.dir_colors{{ else }}.dircolors{{ end }}
```

?

**Comment by eugenesvk** [comment]
I have the same issue when syncing between Windows and Mac as there isn't even a common location like `~/.config/` you could use, so at lease on one machine a new 'unnatural' path has to be created, which is not ideal.
Is there a way to have a 4th solution where the source path would translate to a different target path based on OS/host and that custom target path could be stored in local settings?
Thanks

**Comment by twpayne** [comment]
@eugenesvk another option here is to store the contents in a partial template, create templates for the two different locations, and then selectively ignore all-but-one depending on the machine.

Here's a concrete example:

`~/.local/share/chezmoi/.chezmoitemplates/mycontents`
```
# shared contents here
```

`~/.local/share/chezmoi/windows/specific/location.tmpl`
```
{{- template "mycontents" -}}
```

`~/.local/share/chezmoi/linux/dir/different-name.tmpl`
```
{{- template "mycontents" -}}
```

`~/.local/share/chezmoi/.chezmoiignore`
```
{{ if ne .chezmoi.os "windows" }}
windows/specific/location
{{ end }}
{{ if ne .chezmoi.os "linux" }}
linux/dir/different-name
{{ end }}
```

This should have the effect you want (full disclaimer: I haven't tested the above, but something like it should work). This will result in chezmoi creating unwanted empty directories, see #700 for discussion, but I hope to get a fix for this into v2.
