### ISSUE TITLE
Caching the results of the github api locally

### ISSUE THREAD

**Issue by MuXiu1997** [twpayne/chezmoi#1642]
## Is your feature request related to a problem? Please describe.

Multiple calls to template functions of a short period of time , such as multiple `diff` operations , may make multiple calls to the `github api` , thus triggering [Rate Limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) .

## Describe the solution you'd like

store the response and `Etag` of the github api in [persistentState](https://github.com/twpayne/chezmoi/blob/434c29f49711f35a90bf07831c678f02b6136b95/internal/chezmoi/persistentstate.go#L18) like `githubApiStateBucket` to avoid repeated calls

## Describe alternatives you've considered

n/a

## Additional context

Ref: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

ps: I would like to try to implement this feature

**Comment by twpayne** [comment]
Thanks for proposing this - this is a great idea!

As well as caching GitHub API calls, it would be great if externals could be more intelligently cached too. See [this FIXME in the code](https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/sourcestate.go#L1095-L1096), which is in the function that would need to be modified. I was thinking of using https://github.com/bxcodec/httpcache or something similar.

It may be worth improving external caching first, and then see how we can share the caching code between downloading externals and GitHub API calls.

Would you like to implement the improved external caching?

**Comment by MuXiu1997** [comment]
I'd be happy to contribute, but I have some considerations

https://github.com/bxcodec/httpcache is based on [RFC 7234](http://tools.ietf.org/html/rfc7234) , which will result in:

- ```sh
  $ curl -IL GET 'https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz'
  HTTP/2 302
  ......
  location: https://codeload.github.com/ohmyzsh/ohmyzsh/tar.gz/master
  cache-control: max-age=0, private
  ......
  HTTP/2 200
  access-control-allow-origin: https://render.githubusercontent.com
  content-disposition: attachment; filename=ohmyzsh-master.tar.gz
  content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
  content-type: application/x-gzip
  etag: "572bf59617dd06a0c9433471346bb9c4b4c8c40e2c9885641a76523b0bc93649"
  strict-transport-security: max-age=31536000
  vary: Authorization,Accept-Encoding,Origin
  x-content-type-options: nosniff
  x-frame-options: deny
  x-xss-protection: 1; mode=block
  date: Sat, 20 Nov 2021 06:36:04 GMT
  x-github-request-id: C060:2644:5E6EE:D1F7F:61989753
  ```

  `cache-control: max-age=0` and no `cache-control` header, it may mean still re-downloading every time

- ```sh
  curl -IL 'https://api.github.com/users/MuXiu1997/keys?per_page=100' \
  -H 'Accept: application/vnd.github.v3+json'
  HTTP/2 200
  server: GitHub.com
  date: Sat, 20 Nov 2021 06:47:41 GMT
  content-type: application/json; charset=utf-8
  cache-control: public, max-age=60, s-maxage=60
  vary: Accept, Accept-Encoding, Accept, X-Requested-With
  etag: W/"33a5b8109b0ecb53cacf775a751af1f2105b187660fec1d0e06d35edf193696b"
  x-github-media-type: github.v3; format=json
  access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
  access-control-allow-origin: *
  strict-transport-security: max-age=31536000; includeSubdomains; preload
  x-frame-options: deny
  x-content-type-options: nosniff
  x-xss-protection: 0
  referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
  content-security-policy: default-src 'none'
  x-ratelimit-limit: 60
  x-ratelimit-remaining: 32
  x-ratelimit-reset: 1637392457
  x-ratelimit-resource: core
  x-ratelimit-used: 28
  accept-ranges: bytes
  content-length: 598
  x-github-request-id: 721A:2585:DC5651:E708B3:61989A14
  ```

  `cache-control: public, max-age=60, s-maxage=60` , this may mean that `Rate Limit` cannot be avoided in this way



https://github.com/gregjones/httpcachemight be a better choice
It seems to be based on [RFC 7232](http://tools.ietf.org/html/rfc7232) instead of [RFC 7234](http://tools.ietf.org/html/rfc7234) and also provides out-of-the-box `diskcache`
It is also mentioned in [google/go-github](https://github.com/google/go-github#conditional-requests)
