### ISSUE TITLE
`execute-template` too slow

### ISSUE THREAD

**Issue by MuXiu1997** [twpayne/chezmoi#1662]
## What exactly are you trying to do?

When I used `chezmoi execute-template`, `.chezmoiexternal.yaml` was calculated as a template
For example, if I have network calls in my `.chezmoiexternal.yaml`, `execute-template` will be very slow

So was it necessary to calculate the `.chezmoiexternal.yaml` template when executing `execute-template`?

## What have you tried so far?

When I delete `.chezmoiexternal.yaml` or rename `.chezmoiexternal.yaml` to an unrelated name, `execute-template` executes very fast

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

n/a

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.8.0, commit 10dbbcd2be5049cc4a5bfe97820188d17455c057, built at 2021-11-20T19:52:48Z, built by Homebrew
ok        os-arch              darwin/arm64
ok        executable           /opt/homebrew/bin/chezmoi
ok        upgrade-method       brew-upgrade
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
warning   suspicious-entries   ~/.local/share/chezmoi/.chezmoidata.yaml
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /opt/homebrew/bin/nvim
ok        umask                022
ok        git-command          found /opt/homebrew/bin/git, version 2.34.0
ok        merge-command        found /opt/homebrew/bin/vimdiff
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /opt/homebrew/bin/bw, version 1.19.1
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

## Additional context

n/a

**Comment by felipecrs** [comment]
I also have the same problem. But as `execute-template` is not the only command slow and which I frequently use, I think the real solution is to code some kind of cache mechanism, where I would only call the external commands if 10 minutes passed after they were called before, or something like that.

**Comment by MuXiu1997** [comment]
Slow is acceptable in multiple `apply` calls and `diff` calls
because we use network calls just to keep something up to date

But in `execute-template`, I'm not sure if calculating the `.chezmoiexternal.yaml` template is necessary

**Comment by twpayne** [comment]
As @MuXiu1997 says, executing templates is fast, but if a user decides to use lots of network calls in their template then it will be slow. There is nothing that chezmoi can do about this. It is up to the user to use templates appropriately.

chezmoi uses `text/template` as a _templating_ language. `text/template` is *not* a full programming language. Proposals like #1661 which attempt to add higher level functionality are in effect adding half-baked poorly-defined behavior to something which is fundamentally not designed to accept it. Following this path is how you end up with another PHP 3.

> I think the real solution is to code some kind of cache mechanism, where I would only call the external commands if 10 minutes passed after they were called before, or something like that.

Absolutely not. Such a caching mechanism would break existing users who expect `output` to return the result of running a command. not some historical output of the command.

If you want complex imperative code in your templates then I suggest using the `output` function like this:

`.chezmoiexternals.yaml`:
```
{{- output "generate-chezmoiexternals" (toYaml .) -}}
```

Where `generate-chezmoiexternals` is a script written by the user which parses YAML from its first command line argument and writes the desired contents of `.chezmoiexternals.yaml` to the standard output. `generate-chezmoiexternals` can be any executable, e.g. a shell script or Python script, and perform whatever caching it needs.

**Comment by MuXiu1997** [comment]
Awesome!!! 
I actually like it better this way too!!!
I figured out what to do with all my needs!!!

**Comment by felipecrs** [comment]
> Absolutely not. Such a caching mechanism would break existing users who expect output to return the result of running a command. not some historical output of the command.

I meant in my templates, not in chezmoi core. :)

**Comment by felipecrs** [comment]
I do agree with everything stated here, except that the fundamental question raised by the issue was not answered:

> I'm not sure if calculating the .chezmoiexternal.yaml template is necessary

**Comment by MuXiu1997** [comment]
```yaml
{{- define "gitHubRepoArchive" }}
  {{- $url := printf "https://github.com/%s/archive/master.zip" .repo }}
  {{- if (get . "latest") }}
  {{- $url = printf "https://github.com/%s/archive/%s.zip" .repo (trim (gitHubLatestRelease .repo).TagName) }}
  {{- else if (get . "branch") }}
  {{- $url = printf "https://github.com/%s/archive/%s.zip" .repo .branch }}
  {{- end }}
  type: archive
  url: {{ $url }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
{{- end -}}

{{- if not (eq (index .chezmoi.args 1) "execute-template") -}}

# Oh-my-zsh
{{ .ohMyZshDir }}:
  {{- template "gitHubRepoArchive" .ohMyZsh }}

# Oh-my-zsh themes
{{ range .ohMyZshThemes -}}
  {{- $.ohMyZshThemesDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-zsh plugins
{{ range .ohMyZshPlugins -}}
  {{- $.ohMyZshPluginsDir -}}/{{ base .repo }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Oh-my-tmux
{{ .ohMyTmuxDir }}:
  {{- template "gitHubRepoArchive" .ohMyTmux }}

# Ranger plugins
{{ range .rangerPlugins -}}
  {{- $.rangerPluginsDir -}}/{{ base .repo | snakecase }}:
  {{- template "gitHubRepoArchive" . }}
{{ end }}

# Vim-plug
.local/share/nvim/site/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"
.vim/autoload/plug.vim:
  type: "file"
  url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod: "168h"

{{- end }}
```

**Comment by MuXiu1997** [comment]
Please see the previous one
```diff
+{{- if not (eq (index .chezmoi.args 1) "execute-template") -}}
```

**Comment by felipecrs** [comment]
That's a neat workaround... still does not answer the question, though.

**Comment by MuXiu1997** [comment]
I guess, maybe the answer is that, with the correct use of templates, the execution of templates is very fast, so it is irrelevant whether an additional .chezmoiexternal.yaml is executed

**Comment by felipecrs** [comment]
The problem I found about `{{- if not (eq (index .chezmoi.args 1) "execute-template") -}}` was that, if I'm executing the following:

```
$ cat ~/.dotfiles/home/.chezmoiexternal.yaml | time chezmoi execute-template
```

It skips the template as well.

I ended up doing this: https://github.com/felipecrs/dotfiles/pull/51
