### ISSUE TITLE
Add new modifier for controlling order of execution

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1664]
## Is your feature request related to a problem? Please describe.

Many issues were opened already regarding such thing. If there was such a modifier, which could be applied to any file in the source state, would solve the issue by letting the dotfiles maintainers control their own order of execution.

For example, I could have a `.chezmoitemplate` which would make use of a script defined in the `.chezmoiexternal.yaml`, which would then be used by my `.gitignore`.

## Describe the solution you'd like

Something like: `order_` modifier which could be added to any file in chezmoi source state. For example:

- `order_01_.chezmoiexternal.yaml`
- `.chezmoitemplate/order_02_my-template`
- `order_03_dot_gitconfig`

## Describe alternatives you've considered

I've opened many issues already to debate about the order of execution of things, like https://github.com/twpayne/chezmoi/issues/1616.

And I'm not complaining about the fact that what would work best for my dotfiles is not in common sense with everyone, because, indeed, there is no way to have a predefined order of execution which would fulfill everyone's needs (even though I still believe some good decisions could be made to minimize that).

So, as there isn't a way to fulfill everyone's needs with a predefined order, it would be very welcome if the users could control the order then.

## Additional context

The names I propose are debatable. Please, get the idea, and if the proposed implementation is not good enough, we can improve.

**Comment by twpayne** [comment]
chezmoi is trying to be as declarative as possible. The proposal here is fundamentally imperative, complex to implement, and the resulting system would be complex to reason about.

If these sort of imperative ordered steps are needed, then I would suggest scripting *around* chezmoi. For example, generate a source state in a temporary directory `$SOME_TEMP_DIR`, then invoke `chezmoi apply -S $SOME_TEMP_DIR`.
