### ISSUE TITLE
bad symlink

### ISSUE THREAD

**Issue by arkhan** [twpayne/chezmoi#167]
Hello,

I'm trying to create  symlink_dot to a file but chezmoi puts the file content as a path:

![img-2019-01-24-214038](https://user-images.githubusercontent.com/3141865/51721799-3e22fa00-2021-11e9-9085-82e7a298b680.png)

Can you manage the files in this way?
Thanks

**Comment by twpayne** [comment]
`chezmoi` can handle this. You need to add both the symlink (`~/.bashrc`) and the file that it points to `chezmoi`. The easiest way to do this is probably to get `~/.bashrc` and the file that it points to in the state you want, and then add them with:

    $ chezmoi add ~/.bashrc $(readlink ~/.bashrc)

**Comment by twpayne** [comment]
I hope this worked for you. Please re-open this issue to continue discussion, and thanks for using `chezmoi` :)

**Comment by arkhan** [comment]
The issue is trying to create a symbolic link from the root of chezmoi to the root of the user '~ /' chezmoi creates a route that does not exist:
expected:
``
/home/arkhan/.zprofile -> /home/arkhan/.local/share/chezmoi/symlink_dot_zprofile
``
but what you get when running chezmoi apply is:
![img-2019-01-30-075716](https://user-images.githubusercontent.com/3141865/51982875-30c4a000-2465-11e9-801a-6b9bf36af4ba.png)

**Comment by twpayne** [comment]
What happened here was:

1. You ran `chezmoi add ~/.zprofile`. This created `dot_zprofile` in the source directory where the contents of `dot_zprofile` are the desired contents of `~/.zprofile`.
2. You then renamed `dot_zprofile` to `symlink_dot_zprofile`, without changing its contents. When `chezmoi` sees a `symlink_` file it creates a symbolic link and uses the contents of the file as the target for the symbolic link.
3. As you didn't change the contents of `symlink_dot_zprofile`, `chezmoi` creates a symbolic link where the target is the contents of `symlink_dot_profile`.

Please make sure that you re-read and understand step number 2. It is important. `chezmoi` is not like GNU Stow. `chezmoi` creates real files in your home directory. `chezmoi` does not create symbolic links back to the source directory (unless you explicitly want that).

To fix this, run:

```console
$ chezmoi chattr nosymlink ~/.zprofile
$ chezmoi apply
```

This will then make the contents of `~/.zprofile` what you want them to be.

**Comment by 3v1n0** [comment]
> `$ chezmoi add ~/.bashrc $(readlink ~/.bashrc)`

While this works, I think it's still problematic in for one main reason: the generated symlink is pointing to a full path, while it should instead create a `symlink_dot_bashrc.tmpl` file with content such as `{{ .chezmoi.homedir }}/relative-path-of/.bashrc`

This is the only way to make it stronger to symlink handling so that can work without being dependent on the actual home path.
