### ISSUE TITLE
Auto apply on save with vim/nvim doesn't work

### ISSUE THREAD

**Issue by imekachi** [twpayne/chezmoi#1675]
## What exactly are you trying to do?
I want to edit some config file with vim/neovim
```sh
chezmoi edit ~/.config/nvim/init.vim
```
Then I want the config to be applied automatically.

## What have you tried so far?

1. Add the command suggested in the how-to guide to the `init.vim`
1. save, manually apply
1. try to edit the nvim config with this command
    ```sh
    chezmoi edit ~/.config/nvim/init.vim
    ```
1. save
    ![image](https://user-images.githubusercontent.com/5445243/143690981-16260283-72d8-447d-8bf2-c60a87a1db1f.png)
1. check the `~/.config/nvim/init.vim` content, it wasn't updated

I suspect that because the file path that the editor got as an argument is a temp path and it didn't match the path described in the `autocmd` command, therefore the auto apply command never got executed.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$  chezmoi --verbose edit ~/.config/nvim/init.vim
```
It prints nothing after I exit vim

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.8.0, commit 10dbbcd2be5049cc4a5bfe97820188d17455c057, built at 2021-11-20T20:59:57Z, built by goreleaser
ok       os-arch              darwin/arm64
ok       executable           ~/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /opt/homebrew/bin/nvim
ok       umask                022
ok       git-command          found /opt/homebrew/bin/git, version 2.33.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
info     gpg-command          gpg not found in $PATH
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

**Comment by twpayne** [comment]
Thanks very much for reporting this!

> I suspect that because the file path that the editor got as an argument is a temp path and it didn't match the path described in the `autocmd` command, therefore the auto apply command never got executed.

You're totally correct. #1481 introduced editing via hardlinks so that editors would see the target filename (instead of the source filename) to help them determine the file type correctly, which broke any automation expecting the edited file to be in the source directory.

#1677 makes it possible to disable this behavior, you'll need to put the following in your config file:
```toml
[edit]
    hardlink = false
```

**Comment by imekachi** [comment]
@twpayne Thank you for the quick reply.

So if I disable this feature, I will lose the syntax highlighting right?

Is there a way to get both automation and syntax highlighting?
Maybe symlink/hardlink the file to `~/.local/share/chezmoi/`?
For example,
```console
chezmoi edit ~/.config/nvim/init.vim
```
would create a link to `~/.local/share/chezmoi/.config/nvim/init.vim`

Then I can change the auto save command to
```console
autocmd BufWritePost ~/.local/share/chezmoi/* ! chezmoi apply --source-path "~/%"
```

I don't know much about command lines and links so I have no idea if this will work.

**Comment by twpayne** [comment]
> Is there a way to get both automation and syntax highlighting?

Yes, you can use https://github.com/alker0/chezmoi.vim.

**Comment by imekachi** [comment]
@twpayne Thank you. The syntax highlighting and the autosave command work beautifully with the vim plugin.

When do I expect the `--hardlink=false` to be released?

**Comment by twpayne** [comment]
> When do I expect the `--hardlink=false` to be released?

Probably within a day or so. There have been sufficient changes since v2.8.0 to justify a new release. I'm just going through the open issues now.
