### ISSUE TITLE
Pedantic managing of homedir

### ISSUE THREAD

**Issue by youam** [twpayne/chezmoi#168]
Hi there,

I've found chezmoi only this week, so I'm a fairly new user and might have misses something in the report below.

I want to use chezmoi to manage the home directory of my user on a number of servers. Those homedirs should be as clean as possible, and so I'd want to put all stuff which might be there into subdirectories and ignore them via ```.chezmoiignore```, and tell chezmoi that all other files should be absent.

I tried doing that by running:

```
chezmoi add --exact .
```

This has convinced chezmoi that it should remove _all_ files in the homedirectory, as I've just told it to manage the . target, but it doesn't consider any of the other files I've added to be in this directory:

```
youam@macha:~/.local/share/chezmoi$ ls -la dot_inputrc exact_dot_ -d ; ls -al exact_dot_
-rw-r--r-- 1 youam youam   88 Jan 25 11:46 dot_inputrc
drwxr-xr-x 2 youam youam 4096 Jan 25 11:52 exact_dot_
total 8
drwxr-xr-x 2 youam youam 4096 Jan 25 11:52 .
drwx------ 7 youam youam 4096 Jan 25 11:57 ..
youam@macha:~/.local/share/chezmoi$ chezmoi diff
[...]
rm -rf /home/youam/.inputrc
```

As a really ugly workaround, I can move all my dotfiles into the exact_dot_ source state directory. Is there some easier, less manual and error-prone way of telling chezmoi to handle the destination directory itself as 'exact'?

That said, thank you for this tool!

**Comment by twpayne** [comment]
Thanks for the feedback!

Are you really sure that you want to do this? Making your home directory "exact" will mean that shell history, various program caches, user-specific sockets, etc. will also be deleted.

That said, if you really want to do this, you can instead tell `chemzoi` to manage the _parent directory_ of your home dir, and then your home dir can be an exact directory within that. i.e. set `targetDir` to be `/home` in your config file, and then represent your home directory in the source state as `exact_youam`.

This is a little uncharted territory, so I strongly advise using `chezmoi`'s verbose dry run mode (`-n -v`) before running `chezmoi apply` for real.

**Comment by twpayne** [comment]
I hope that the above solved it for you. Please re-open this issue if you have further questions/thoughts.

**Comment by youam** [comment]
I like to think that I know what I'm doing. :o) Yes, I'd really want to do this - at least try to see if it's feasible.

Sure, this will only work with a generous amount of files in my ```.chezmoiignore``` file.

Modifying ```targetDir``` implies hardcoding part of the home dir into the repository. As that part is the user name, and the user name isn't constant over all my machines (uli,youam,umartens), this isn't really possible to do for me.

I think I'll go a split way for now:

  - on servers (more "cattle"-like machines), where I want this minimal and enforced homedir, I'll keep one repository with all files within the ```exact_dot_``` directory
  - on my actual work stations ("pet"-like machines), I'll run the usual, simple and relaxed setup.

Thank you for your work and your fast responses!

**Comment by twpayne** [comment]
OK, thanks for the response. If I understand correctly, you can achieve what you want with the existing functionality in `chezmoi`.

Please re-open this issue if you need changes to `chezmoi`.
