### ISSUE TITLE
Checking sudo rights

### ISSUE THREAD

**Issue by 5u623l20** [twpayne/chezmoi#1683]
## What exactly are you trying to do?
I am trying to set some variables based on the output of ```sudo -vn```

## What have you tried so far?
I have added the following in ```.chezmoi.toml.tmpl```

```toml
{{- if lookPath "sudo" }}
{{-   $gotroot = output "sudo" "-vn | grep 'password' > /dev/null || false" }}
{{- end }}
```

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [X] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose init -a
chezmoi: template: chezmoi.toml:28:17: executing "chezmoi.toml" at <output "sudo" "-vn | grep 'password' > /dev/null || false">: error calling output: exit status 1
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.8.0, commit 10dbbcd2be5049cc4a5bfe97820188d17455c057, built at 2021-11-20T20:59:57Z, built by goreleaser
ok       os-arch              darwin/amd64
ok       executable           ~/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /usr/bin/vi
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.30.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/local/bin/gpg, version 2.3.3
info     pinentry-command     not set
ok       1password-command    found /usr/local/bin/op, version 1.12.3
info     bitwarden-command    bw not found in $PATH
ok       gopass-command       found /usr/local/bin/gopass, version 1.13.0
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context
I am aware that my way of doing this is wrong  as ```output``` doesn't do error handling and this code has an exit status of 1. So what might be an approach of trying this.

**Comment by felipecrs** [comment]
You probably meant a bash/sh pipeline with your template, right?

```
{{-   $gotroot = output "sh" "-c" "sudo -vn | grep 'password' > /dev/null || false" }}
```

**Comment by felipecrs** [comment]
> as output doesn't do error handling

In fact, it does, the template fails if the `output` command exits with a non-zero code. Which actually does not matter in your case because you are ignoring with `|| true`.

**Comment by felipecrs** [comment]
How about:

```
{{-   $gotroot = output "sh" "-c" "sudo -vn 2>&1 || true" | regexMatch "password" }}
```

```console
> chezmoi execute-template '{{ output "sh" "-c" "sudo -vn 2>&1 || true" | regexMatch "password" }}'
true
```

**Comment by 5u623l20** [comment]
> 

Looks like I need to go through the template documentation once more. :'(

**Comment by 5u623l20** [comment]
> How about:
> 
> ```
> {{-   $gotroot = output "sh" "-c" "sudo -vn 2>&1 || true" | regexMatch "password" }}
> ```
> 
> ```
> > chezmoi execute-template '{{ output "sh" "-c" "sudo -vn 2>&1 || true" | regexMatch "password" }}'
> true
> ```

Thanks. It worked like a charm. :)
