### ISSUE TITLE
Add init command

### ISSUE THREAD

**Issue by fgrosse** [twpayne/chezmoi#170]
After testing chezmoi on different systems for a while I want to propose to add a new `init` command.

This command would be run when chezmoi is initially setup on a host. Its purpose is to handle the checkout of the `~/.local/share/chezmoi` directory from the source repository as well as setting up permissions along that path (i.e. `0700`).

This is useful because `~/.local/share` does usually not exist when I am installing dotfiles on a new _server_. In that case setting up the directories can be annoying. Also the init command can do submodule setup which I use for my dotfiles repo (e.g. for [antigen][1]). Maybe in the future it could also be extended to ask the user for parameters to automatically generate `~/.config/chezmoi/chezmoi.yaml` based on some definition in the source repo but I would not go that far yet and instead defer this topic, maybe into a later issue.

Example usage (tested inside fresh docker containter):

```sh
$ chezmoi init -v git@github.com:example/dotfiles.git
mkdir -m 700 /root/.local
mkdir -m 700 /root/.local/share
Created source directory "/root/.local/share" with file mode 0700 (-rwx------) 
Checking out dotfiles repository "git@github.com:example/dotfiles.git" into "/root/.local/share/chezmoi"
exec git clone git@github.com:example/dotfiles.git /root/.local/share/chezmoi
Enter passphrase for key '/root/.ssh/id_rsa': 
Cloning into '/root/.local/share/chezmoi'...

chmod 700 /root/.local/share/chezmoi
Initializing git submodules in "/root/.local/share/chezmoi"
cd /root/.local/share/chezmoi
exec git submodule init
Submodule 'antigen' (https://github.com/zsh-users/antigen.git) registered for path 'antigen'
```

If you agree that this could be a valuable addition I can provide a pull request (I implemented the command already on my fork). If however you do not want to add this to chezmoi then I will probably fall back to maintaining a bash setup script.

---

P.S. Thanks for this project. I think its a great idea and really motivated me to cleanup my dotfiles :sweat_smile: 

[1]: https://github.com/zsh-users/antigen

**Comment by twpayne** [comment]
Yes, this is a great idea! Please do submit a PR.

**Comment by twpayne** [comment]
Code in #174 merged, thank you!

**Comment by fgrosse** [comment]
Came back here after I got distracted with other shiny things :)

I see chezmoi is doing great and still developing further :+1: 
Regarding this topic I would like to continue with this one part I mentioned in the issue description:

> Maybe in the future it could also be extended to ask the user for parameters to automatically generate ~/.config/chezmoi/chezmoi.yaml based on some definition in the source repo but I would not go that far yet and instead defer this topic, maybe into a later issue.

If you agree with the idea in general I would open a separate issue where we can discuss details. Just wanted to make sure first this is a feature want to follow up with :)

**Comment by twpayne** [comment]
Yes, I think this is a very good idea that I'd like to see in `chezmoi`. Please do open an issue to discuss.

**Comment by twpayne** [comment]
I created the issue #241 for discussion.
