### ISSUE TITLE
`dev` version incompatible with `.chezmoiversion` file

### ISSUE THREAD

**Issue by nandalopes** [twpayne/chezmoi#1701]
## What exactly are you trying to do?

I'm trying to use `master` version with a `.chezmoiversion` file and getting this error:

```console
$ chezmoi status
chezmoi: source state requires version 2.9.0 or later, chezmoi is version 0.0.0
```

## What have you tried so far?

Whether I'm using master branch or the latest tag version, I can't use local compiled chezmoi with `.chezmoiversion`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose status
chezmoi: source state requires version 2.9.0 or later, chezmoi is version 0.0.0
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              dev
ok        os-arch              linux/amd64 (Ubuntu 22.04 (Jammy Jellyfish))
ok        go-version           go1.17.3 (gc)
ok        executable           /home/media/bin/chezmoi/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.dotfiles is a directory
warning   suspicious-entries   ~/.dotfiles/.chezmoidata.yaml
ok        working-tree         ~/.dotfiles is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /usr/bin/vim
warning   umask                027
ok        git-command          found /usr/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.6.6
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/local/bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

## Additional context

```console
$ chezmoi --version
chezmoi version dev
```

**Comment by twpayne** [comment]
This is a definite bug introduced by #1695.

**Comment by nandalopes** [comment]
Is there any way to set chezmoi compiled version, like [fzf](https://github.com/junegunn/fzf) do?

**Comment by twpayne** [comment]
#1701 should fix it.

> Is there any way to set chezmoi compiled version, like [fzf](https://github.com/junegunn/fzf) do?

You can also build chezmoi using `make build-in-git-working-copy` or install it with `make install-from-git-working-copy`. This will build/install chezmoi with the version information embedded in the binary.

Thanks for reporting this!
