### ISSUE TITLE
How many shells are open

### ISSUE THREAD

**Issue by Nagidal** [twpayne/chezmoi#1710]
## What exactly are you trying to do?

Count how many shells are open. Specifically, I forgot to type `exit` after `chezmoi cd`, and over some time I opened multiple shells via `chezmoi cd`. When I finally remembered to type exit, I had to exit like three or four shells until I was back to my parent shell.

Is there a way to see how many shells have I opened in my terminal?

## What have you tried so far?

`ls /dev/pts/  | wc -l` but this shows something else. The count does not go up when I do `chezmoi cd`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Additional context

This is actually not specifically related to chezmoi. You can open multiple shell for example with `su`:

```
[user_A]$ su user_B
[user_B]$ su user_C
[user_C]$ su user_D
[user_D]$ 
```
And here I would like to see for how many levels away from `user_A`'s parent shell `user_D` is. In our example, `user_D` would have to type `exit` three times to go back to `user_A`'s shell.

**Comment by twpayne** [comment]
As you say, this is not related to chezmoi. Consider the [`pstree` command](https://linux.die.net/man/1/pstree).
