### ISSUE TITLE
Extend templating support to .chezmoiexternals

### ISSUE THREAD

**Issue by fhemberger** [twpayne/chezmoi#1712]
## Is your feature request related to a problem? Please describe.

I want to use `.chezmoiexternals` to load files depending on the OS or custom data. For example, I use a variable to setup dotfiles depending on the shell installed (bash, zsh, fish). It would be nice if external dependencies were only requested if the condition matches, e.g. if I'm using "bash" instead of "zsh" on a machine, there's no use to download "zsh-syntax-highlighting".

## Describe the solution you'd like

Extend templating support to `.chezmoiexternals.<format>`, allowing `.chezmoiexternals.<format>.tmpl`:

```go
{{ if eq .shell "zsh" -}}
[".config/zsh/external/zsh-syntax-highlighting"]
  type = "archive"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
{{ end -}}
```

**Comment by fhemberger** [comment]
Oh, looks like this is already working (at least the TOML parser doesn't throw) but not mentioned in the documentation.

**Comment by twpayne** [comment]
It's mentioned in [the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiexternalformat):

> `.chezmoiexternal.<format>` is interpreted as a template. This allows different externals to be included on different machines.

**Comment by fhemberger** [comment]
Ah, sorry, I missed that. 🙈 
Awesome, thank you! 🎉
