### ISSUE TITLE
Blank buffer when editing file with `chezmoi edit <filename>`

### ISSUE THREAD

**Issue by aeberts** [twpayne/chezmoi#1714]
## What exactly are you trying to do?

I'm trying to edit the file `.rgignore` which I added to chezmoi with the `chezmoi add` command.

If I do `chezmoi edit ~/.rgignore` vim opens a blank buffer and the status line reads:

`/var/folders/4f/rvz4stv56tzfg3ml4f1x2d880000gn/T/chezmoi-edit2453336440/.rgignore [New DIRECTORY]`

My assumption is that chezmoi would open the equivalent dot file from the chezmoi source (i.e. `~/.local/share/chezmoi/dot_rgignore`) but I might be mis-understanding how the `chezmoi edit` command works. 

## What have you tried so far?

I have tried `chezmoi edit` on two different files in the chezmoi source directory with emacs and vim (both give the same result as above).

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

Reviewed the issues in github

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose edit ~/.rgignore
chezmoi: warning: /Applications/MacVim.app/Contents/bin/mvim /var/folders/4f/rvz4stv56tzfg3ml4f1x2d880000gn/T/chezmoi-edit4089430477/.rgignore: returned in less than 1s
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.9.0, commit f9ba484442ad5ec2cc1c14fffa5fab05779546c7, built at 2021-11-28T16:57:41Z, built by Homebrew
ok       os-arch              darwin/amd64
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          no config file found
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /usr/local/bin/zsh
ok       edit-command         found /Applications/MacVim.app/Contents/bin/mvim
ok       umask                022
ok       git-command          found /usr/local/bin/git, version 2.32.0
ok       merge-command        found /usr/local/bin/vimdiff
info     age-command          age not found in $PATH
info     gpg-command          gpg not found in $PATH
info     pinentry-command     not set
ok       1password-command    found /usr/local/bin/op, version 1.12.3
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set

```

## Additional context

- On MacOS and using iTerm2

**Comment by twpayne** [comment]
The problem here is that your editor is forking, detaching, and terminating the original process, which chezmoi cannot distinguish from the editor terminating normally. You have two options:
1. Configure your editor command to remain in the foreground by passing the `-f` flag to `mvim`, e.g. by setting the `edit.flags` configuration variable to `["-f"]`, or by setting the `EDITOR` environment variable to `mvim -f`.
2. Set the `edit.hardlink` configuration variable to `false`.

**Comment by aeberts** [comment]
Thanks @twpayne - I can confirm that solved the issue.

And thanks for chezmoi - a very useful piece of software!
