### ISSUE TITLE
Improve performance of chezmoi external

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1715]
## Describe the bug

My dotfiles takes too long to be applied, and I determined that the root cause is my `.chezmoiexternal.yaml`. The problem, however, is not caused by the amount of `output` calls that I make inside of it. With the recent improvements I made, its rendering process now takes only a few moments. Refs https://github.com/felipecrs/dotfiles/pull/51.

```console
> time chezmoi execute-template "$(cat ~/.dotfiles/home/.chezmoiexternal.yaml)"
chezmoi execute-template "$(cat ~/.dotfiles/home/.chezmoiexternal.yaml)"   0.84s user 0.06s system 120% cpu 0.743 total

> time chezmoi apply
chezmoi apply  4.47s 5.28s user 0.78s system 102% cpu 5.896 total
```

This amount of time that it takes really decreases the user experience by a lot. While I know that I'm indeed using many externals, I guess that it's a reasonably common use case for chezmoi.

## To reproduce

With the commands mentioned above, using my dotfiles.

## Expected behavior

I would really appreciate if this time could be reduced, but I have no clue how, I'm opening this issue so we can discuss.

Perhaps more tasks can be run in parallel? Perhaps more data can be stored as cache? Perhaps the cache can be less compressed? I really don't know.

## Output of command with the `--debug` flag

[log.txt](https://github.com/twpayne/chezmoi/files/7673082/file.txt)

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.9.2, commit 9c082e4fe4b74ec9909d1244f29eaacc26b20b1b, built at 2021-12-02T06:35:20Z, built by Homebrew
ok       os-arch              linux/amd64 (Ubuntu 20.04.3 LTS (Focal Fossa))
ok       go-version           go1.17.3 (gc)
ok       executable           /home/linuxbrew/.linuxbrew/Cellar/chezmoi/2.9.2/bin/chezmoi
ok       upgrade-method       brew-upgrade
ok       config-file          ~/.config/chezmoi/chezmoi.yaml
ok       source-dir           ~/.dotfiles is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.dotfiles is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /usr/bin/zsh
ok       edit-command         found ~/.local/bin/code
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.34.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/bin/gpg, version 2.2.19
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context

I tried `exact: false` for the archives but that didn't change anything.

**Comment by twpayne** [comment]
I don't think this is a bug any more than "my car goes slower when I fill the trunk with bricks" is a bug in the car, so I've amended the issue title to fit.

**Comment by felipecrs** [comment]
You are absolutely right.

**Comment by twpayne** [comment]
> Perhaps more tasks can be run in parallel? Perhaps more data can be stored as cache? Perhaps the cache can be less compressed? I really don't know.

Running tasks concurrently breaks the deterministic [application order](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#application-order). Externals are already cached, and only re-downloaded at periodic intervals. Compression is effectively free on current hardware (less data to read from disk/network, and CPUs are fast). Making chezmoi more concurrent (e.g. concurrently reading the source state) while maintaining determinism would require a significant internal re-write.

Looking at your debug log, I see that chezmoi has to read approximately 1,675 files to see if they need updating. There are also eight spawned processes, of which two are `curl https://github.com/...` and probably take 600-800ms each. There are also calls to `deno` and `volta` to generate zsh completions, and a call to `zcat` on a 32MB file.

#1735 adds logging the duration of HTTP GETs and spawned processes to the output of `--debug` which should help you identify and eliminate the slow steps in your configuration.

**Comment by felipecrs** [comment]
Thanks a lot!

**Comment by twpayne** [comment]
#2384, #2385, and #2386 introduce some improvements and bug fixes to `chezmoi status` around externals, but please see [this comment](https://github.com/twpayne/chezmoi/discussions/2375#discussioncomment-3725102).
