### ISSUE TITLE
Better file completion for apply, re-add, edit and friends

### ISSUE THREAD

**Issue by nkgm** [twpayne/chezmoi#1716]
## Is your feature request related to a problem? Please describe.

Right now all commands use vanilla file completion for targets. That makes sense for commands like `add`, but much less so for others, like for instance:

```ShellSession
$ chezmoi apply foo
chezmoi: foo: not in source state

$ chezmoi edit foo
chezmoi: foo: not in source state

$ chezmoi re-add foo
# this will silently fail if you provide a target that's not already managed, or a target that doesn't exist
```

This can make it particularly cumbersome managing app preferences stowed several levels under `~/Library/Preferences`, `~/Library/Application Support` or even more obscure locations. You should only have to do the work *once*, when `add`ing the files, and then let chezmoi take over.

## Describe the solution you'd like

We should get target completion that makes sense for the command in use. Most commands would readily benefit from `git ls-files`, but would be even better isolating just the modified targets for commands like `apply` and `re-add`.

## Describe alternatives you've considered

For `apply` and `re-add`: processing the output of `chezmoi diff` to extract the modified file paths (on a separate note, a flag for this would be really useful), and then feed them to a fuzzy finder like `fzf`.  As a fallback alternative, a simple `chezmoi git ls-files` would still produce significant gains.

**Comment by twpayne** [comment]
> For `apply` and `re-add`: processing the output of `chezmoi diff` to extract the modified file paths (on a separate note, a flag for this would be really useful), and then feed them to a fuzzy finder like `fzf`. As a fallback alternative, a simple `chezmoi git ls-files` would still produce significant gains.

Consider [`chezmoi status`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#status) and [`chezmoi managed`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#managed) for this.
