### ISSUE TITLE
Prevent chezmoi from creating `.git` folder when using `init --one-shot`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1721]
## Is your feature request related to a problem? Please describe.

I'm trying to install my dotfiles doing something like:

```
[...]

SHELL ["bash", "-euxo", "pipefail", "-c"]

# Install dotfiles
RUN --mount=type=bind,source=home,target=/tmp/dotfiles,readonly \
  export REMOTE_CONTAINERS=true; \
  sh <(curl -fsSL https://git.io/chezmoi) init --one-shot --source /tmp/dotfiles
```

Inside of a Dockerfile. As it can be noted, I'm mounting only the `home` subfolder of my repository, so that the docker build caching mechanism is optimized. Also, I'm mounting the dotfiles source folder as a readonly volume, because I plan to only perform a one-shot installation.

Doing that, chezmoi fails with something like:

```console
#11 1.314 info found version 2.9.2 for latest/linux/amd64
#11 2.472 info installed ./bin/chezmoi
#11 2.537 /tmp/dotfiles/.git: Read-only file system
``` 

## Describe the solution you'd like

I think that, in `one-shot` mode, there is no reason to bother about initializing a git repository, as chezmoi would be uninstalled right-after anyway.

## Describe alternatives you've considered

Instead of mounting only the home folder, I'm mounting the whole dotfiles repository, and now I need a `.dockerignore` like so to achieve a similar result:

```
*

!home/
!.chezmoiroot

# Include empty .git folder so that chezmoi does not try to create it
!.git/
.git/*

```

## Additional context

None.

**Comment by twpayne** [comment]
This is not easy to do. Both `git` and `go-git` clone the repo to disk.

Instead of using `chezmoi init` to clone the git repo, consider populating `/tmp/dotfiles` and then running `chezmoi init -S /tmp/dotfiles`.

**Comment by felipecrs** [comment]
> Instead of using `chezmoi init` to clone the git repo, consider populating `/tmp/dotfiles` and then running `chezmoi init -S /tmp/dotfiles`.

I don't get it. Isn't this exactly what I'm doing?

The problem is that, even though the source folder already exists, chezmoi still tries to create the `.git` folder. Even when it has absolutely no need (which is the `--one-shot` case).

**Comment by twpayne** [comment]
`chezmoi init --one-shot` includes cloning the repo. Cloning the repo is done by either `git` or chezmoi's built-in git (which uses `go-git`) and both write to disk, i.e. both create the `.git` folder.

> > Instead of using `chezmoi init` to clone the git repo, consider populating `/tmp/dotfiles` and then running `chezmoi init -S /tmp/dotfiles`.
> 
> I don't get it. Isn't this exactly what I'm doing?

No, you're using `chezmoi init --one-shot` which does many things. `chezmoi init -S /tmp/dotfiles` will only create the config file. You can run `chezmoi apply -S /tmp/dotfiles` to then update the destination directory.

**Comment by felipecrs** [comment]
I just tried here, and it fails with the same error:

```
> [5/5] RUN --mount=type=bind,source=home,target=/tmp/dotfiles,readonly   export REMOTE_CONTAINERS=true;   sh <(curl -fsSL https://git.io/chezmoi) init --source /tmp/dotfiles;   rm -f "/home/vscode/.gitconfig";   sudo rm -rf /var/lib/apt/lists/*:
#11 0.266 + export REMOTE_CONTAINERS=true
#11 0.266 + REMOTE_CONTAINERS=true
#11 0.266 + sh /dev/fd/63 init --source /tmp/dotfiles
#11 0.266 ++ curl -fsSL https://git.io/chezmoi
#11 1.008 info found version 2.9.2 for latest/linux/amd64
#11 1.970 info installed ./bin/chezmoi
#11 2.031 /tmp/dotfiles/.git: Read-only file system
#11 2.031 chezmoi: exit status 1
```

**Comment by twpayne** [comment]
See https://github.com/twpayne/chezmoi/issues/1723#issuecomment-991994750.
