### ISSUE TITLE
Prevent `init --one-shot` from deleting source folder if not created by it

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1723]
## Is your feature request related to a problem? Please describe.

The exact same situation as https://github.com/twpayne/chezmoi/issues/1721. The difference is that, with `--one-shot`, chezmoi tries to delete the source folder after applying.

That's completely intended when using something like `chezmoi init felipecrs --one-shot`, where chezmoi would create the source folder, but I think that it should not be like that for when the source folder was created by something else than chezmoi.

## Describe the solution you'd like

chezmoi to not try to delete `source` when it wasn't created by it.

## Describe alternatives you've considered

```console
$ chezmoi init file:///tmp/dotfiles
```

But with the following caveats:

1. Chezmoi will copy these files to a temporary source folder, which is not optimal
2. Does not work unless I share the whole `.git` folder when building the container, which messes up with Docker's caching.

## Additional context

None.

**Comment by felipecrs** [comment]
By the way, I would also suggest to mention the deletion of the cache and the source state in https://www.chezmoi.io/docs/reference/#--purge.

**Comment by twpayne** [comment]
No, sorry. chezmoi is a dotfile manager for individuals and its a reasonable assumption that `chezmoi init --one-shot` both creates and removes the source directory.

> By the way, I would also suggest to mention the deletion of the cache and the source state in https://www.chezmoi.io/docs/reference/#--purge.

Done in fd690b402893edbbcad0a15f635c2895ce0f6eda.

**Comment by felipecrs** [comment]
> its a reasonable assumption that chezmoi init --one-shot both creates and removes the source directory.

That's not correct. Chezmoi is not creating the source directory in my example. That's the reason why I think it should not delete it: because it's not creating it.

**Comment by twpayne** [comment]
> That's not correct. Chezmoi is not creating the source directory in my example. That's the reason why I think it should not delete it: because it's not creating it.

I disagree here. Part of `chezmoi init`'s responsibilities is to create the source directory, either with a new git repository, or cloning it from an an existing repository. The only exception to this is that `chezmoi init` has also taken the role of re-generating the config file if the config file template has changed. With hindsight, regenerating the config file should have been a different command.

If the source directory already exists, then all of `chezmoi init`'s functionality can be implemented using existing commands. For example, I think the following commands are the equivalent of the desired behavior of `chezmoi init --one-shot` in this issue:

```bash
SOURCEDIR=/tmp/dotfiles
chezmoi init --force --source=$SOURCEDIR # generate config file
chezmoi apply --force --source=$SOURCEDIR # generate dotfiles
rm -rf $(which chezmoi) # purge binary
rm -rf $HOME/.cache/chezmoi # purge cache
rm -rf $HOME/.config/chezmoi # purge config file
```

**Comment by felipecrs** [comment]
Right. These set of commands would do the trick, despite not elegant (and to keep using `--one-shot` elegantly was this issue's goal).

My only problem now is that `chezmoi init` as suggested does not work for me as I stated in https://github.com/twpayne/chezmoi/issues/1721#issuecomment-991909067. The only difference between what I'm running and your suggestion is that yours have `--force`, but I suppose it would not make any difference in this case.
