### ISSUE TITLE
Fine grain control in `--include` and `--exclude`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1728]
## Is your feature request related to a problem? Please describe.

I'm experimenting with using chezmoi to manage my root files with https://github.com/felipecrs/dotfiles/pull/44. There, I have a hook for running chezmoi as root with an `after` script.

But I would also like to be able to perform some `before` actions, like installing `jq` which is used in some of my templates. I could then create a script like `run_always_before_apply_root.sh.tmpl` if there was a way to specify only `--include scripts:before`.

## Describe the solution you'd like

The `--include` and `--exclude` flags to accept a more advanced syntax, like: `--include scripts:before` or `--exclude scripts:onchange`.

## Describe alternatives you've considered

None that I can think of.

## Additional context

None.

**Comment by twpayne** [comment]
No. Scripts should be idempotent and if you want this level of imperative fine-grained control you can do it with a wrapper script that calls chezmoi.

**Comment by felipecrs** [comment]
> Scripts should be idempotent

I don't get what's the relationship to what I reported.

> if you want this level of imperative fine-grained control you can do it with a wrapper script that calls chezmoi.

That's right. But 100% of the features that chezmoi provides can be solved with scripts as well, so I don't know why this feature I suggested is so bad.

**Comment by twpayne** [comment]
Please don't make things personal, i.e don't use the phrase "the feature I suggested". Instead, let's focus on the code and use the phrase "the feature suggested in this issue."

chezmoi is a dotfile manager. One of chezmoi's goals is to make updating your dotfiles a single command:

```console
$ chezmoi update
```

which runs all relevant scripts and updates all entries. All scripts should be idempotent, so it doesn't matter if all scripts are run, which is the relationship to the feature suggested in this issue.

The existing `--include` and `--exclude` options are for practical use cases, specifically excluding scripts from diff and archive output and excluding encrypted files (as it's quite likely you won't have your private keys on some machines). The way that `--include` and `--exclude` are implemented made it easy to add them to all commands.

Firstly, under what circumstances would chezmoi users using chezmoi to manage their dotfiles need the fine grained control of `--include scripts:before` or `--exclude scripts:onchange`?

Secondly, the proposed API is needs refinement. For example, if `--include scripts:before` and `--exclude scripts:onchange` are specified, should a `run_onchange_before_` script be run or not?

Thirdly, the current include/exclude mechanism is based on entry *types* with only one exception for entry *attributes* (`encrypted_`). The implementation with types is quite neat, but the implementation for the attribute is a bit of a hack. The extension of the include/mechanism to include other attributes (e.g. script attributes `once_`, `onchange_`, `before_`, and `after_`) would be a significant amount of work, especially as, for consistency, including/excluding all attributes for all types should also be implemented.

So, for this issue to be accepted, the following would be needed:
1. A convincing use case.
2. A clear specification of how `--include` and `--exclude` should interact for attributes and types.
3. A clean implementation.

**Comment by felipecrs** [comment]
> Please don't make things personal, i.e don't use the phrase "the feature I suggested". Instead, let's focus on the code and use the phrase "the feature suggested in this issue."

You are absolutely right. Thanks for the correction.

> All scripts should be idempotent, so it doesn't matter if all scripts are run, which is the relationship to the feature suggested in this issue.

Yes, scripts should be idempotent. But there are other reasons why someone would like to skip them:

- they can take too long (while still idempotent)
- or, as in my example, to script on top of chezmoi and control better the lifecycle of it

> Firstly, under what circumstances would chezmoi users using chezmoi to manage their dotfiles need the fine grained control of `--include scripts:before` or `--exclude scripts:onchange`?

Better explaining what I wrote in the original issue description:

I have two source states in my dotfiles repository (`home` and `root`), and I script on top of chezmoi to ensure that both are applied when I run `chezmoi apply`. Currently, I'm able to hook the `chezmoi apply --source ~/.dotfiles/root` by creating a `run_after_apply_root.sh` in my `home`. There, however, I cannot achieve the desired goal of having the scripts tagged with `before_` in the `root` source running in the `before_` lifecycle of my normal `home` chezmoi call. If there was such an option, I could do something like:

- home
  - `run_before_apply_root.sh` -> calls `sudo chezmoi apply -S root --include scripts:before`
  - `run_after_apply_root.sh` -> calls `sudo chezmoi apply -S root --exclude scripts:before`
  
This way, I could keep commands like `apt install -y curl git` (which are required in some of my templates) in the root source state, preventing me from having to call `sudo` in any of the scripts in my home source state except when delegating the work to `sudo chezmoi apply -S root`.

In regards of implementation, you are right that the feature description is not complete yet. I did not think of such cases when writing the original suggestion. So here is what I suggest:

A similar syntax to the one that `docker buildx build` uses on `--output` flags: https://docs.docker.com/engine/reference/commandline/buildx_build/#output

This is where it was implemented: https://github.com/docker/buildx/blob/master/util/buildflags/output.go#L14-L111

So that, it can be implemented in chezmoi into something like:

- When no named keys are set, it is read as _type_: `chezmoi apply --include scripts`
   - This retains backwards compatibility with everything but _encrypted_. For that, a special situation can be coded so `encrypted` is also interpreted as a _type_. At least until chezmoi 3.0 to keep backwards compatibility.
   
- Or, type can also be specified: `chezmoi apply --include type=scripts`.

- There is also `attribute` key for the fine grain control: `chezmoi apply --include type=scripts,attribute=before` or `--include type=scripts,attribute=before,attribute=onchange`.

Its blueprint would be something like: `--include [TYPE|type=TYPE[,attribute=ATTRIBUTE]]`
