### ISSUE TITLE
Extend `before_` to files as well

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1729]
## Is your feature request related to a problem? Please describe.

I have a script which makes use of a file created by chezmoi:

`~/.dotfiles/home/dot_local/bin/executable_rootmoi.tmpl`:
```
#!/bin/bash

readonly config_dir="${HOME}/.config/rootmoi"

readonly config="${config_dir}/chezmoi.yaml"
readonly persistent_state="${config_dir}/chezmoistate.boltdb"

exec sudo "{{ .chezmoi.executable }}" \
  --config="${config}" \
  --persistent-state="${persistent_state}" \
  "$@"

```

And then, as mentioned in https://github.com/twpayne/chezmoi/issues/1728, I would use `~/.local/bin/rootmoi` inside of a `run_before` script:

```sh
#!/bin/bash

echo "Applying chezmoi to root..."

executable='{{ joinPath .chezmoi.homeDir ".local/bin/rootmoi" }}'
args=({{ range (rest .chezmoi.args) }} {{ . | quote }}{{ end }})

echo "Executing: ${executable} ${args[@]} --include scripts:before"
exec "${executable}" "${args[@]} --include scripts:before"

```

## Describe the solution you'd like

To be able to specify that a file should be created before. During before, I think that the normal alphabetical order can be retained, so that I can rename my script in case it runs before the file gets created or so.

## Describe alternatives you've considered

To turn the whole `rootmoi` a template inside of `.chezmoitemplates`, and then bundle it in the run before script like:

```bash
#!/bin/bash

echo "Applying chezmoi to root..."

args=({{ range (rest .chezmoi.args) }} {{ . | quote }}{{ end }})

exec <('{{ template "rootmoi" }}') "${args[@]} --include scripts:before"

```

## Additional context

None.

**Comment by twpayne** [comment]
No, sorry. chezmoi's [application order](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#application-order) is already complex enough, and adding something like `before_` for files makes chezmoi less declarative and more imperative.

I suggest working around this by using scripts or using a wrapper script that creates the file and then calls chezmoi.
