### ISSUE TITLE
Order of script execution by .chezmoiscripts

### ISSUE THREAD

**Issue by lcrockett** [twpayne/chezmoi#1734]
## Is your feature request related to a problem? Please describe.

Since moving all `run_` scripts to a `.chezmoiscripts` folder it seems i'm running into ordering issues. Some `run_` scripts rely on the assumption that files controlled by `chezmoi` are in place once the `run_` scripts are executed. A good example is `~/.Brewfile` which is used in a `run_` script (that resides in `.chezmoiscripts`) via `brew bundle install --global`.

It seems that the current behaviour is that due to "re-ordering", `.chezmoiscripts` is processed first and only then file / directory changes are processed, in this example `~/.local/share/chezmoi/dot_Brewfile`

## Describe the solution you'd like

I'd reckon it would suffice to process `.chezmoiscripts` last, after having dealt with file / directory changes

**Comment by twpayne** [comment]
Please see the [description of chezmoi's application order](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#application-order).

To have scripts run after files are updated, you can use a `run_after_` script.

I suspect that what was happening before is that `~/.Brewfile` was being created before the script that used it, and by moving the the script into `.chezmoiscripts` the script then sorted before `~/.Brewfile`.

Note that you can use `brew bundle` without creating `~/.Brewfile`. See [this example](https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiscripts/run_once_before_10-install-packages-darwin.sh.tmpl).

Hope this resolves the issue, please re-open if needed.

**Comment by lcrockett** [comment]
Cheers on the `run_after_` hint, I completely missed that and it works well now. I suspect that what was happening before was that `run_` scripts in the `sourceDir` were picked up last because I had pretty much no other files starting with a letter that comes after `r`.
