### ISSUE TITLE
common config locations

### ISSUE THREAD

**Issue by boehs** [twpayne/chezmoi#1747]
## Is your feature request related to a problem? Please describe.

It's slightly labor intensive to hunt down configurations, ideally I could just do `chezmoi from zsh` to add to the repository my config for `zsh`, or the likes

## Describe the solution you'd like

a directory in this repository containing a list of ??? files (ie: `zsh.???`). I have considered go and yml, there might be more

### Yml

Pros: Easy
Cons: Not very configurable

`zsh.yml`
```yml
locations:
    - ~/.zshrc
```

### Go

Pros: Access to variables, scripting
Cons: Harder

`zsh.go` (I don't know go, this is python code)
```py
if exists('~/.zshrc`):
    chezmoi.configfrom('~/.zshrc')
```

---

Regardless, the idea is without much thought one can add a specific program to their configuration

## Additional Notes

I tried to find a issue for this but could not. If one has already been opened at some point this will act as a pointer

## My role

If this is approved and some basic spec is developed I would be happy to implement it. I'm hesitant to use chezmoi until I implement this because I would like to write these files as I go.

**Comment by twpayne** [comment]
#885 is a similar issue.

[Mackup](https://github.com/lra/mackup) has a database of config files used on macOS, and #1325 added support to chezmoi for using Mackup's database. #1458 then removed it for multiple reasons:
1. Very few chezmoi users actually seemed to want it.
2. The Mackup developers were unresponsive when asked about collaboration.
3. The Mackup database is only partially accurate.

That said, there are a number of difficult problems that mean that this feature is not a good fit for chezmoi:
1. The config files used by an application can vary a lot and cannot realistically be listed or automatically determined, as the Mackup developers have discovered.
2. Maintaining a database of config flies per application is a lot of manual work that I do not want to take on.
3. The actual benefit of such a feature is marginal: users already know which dotfiles they've modified.

If you do want to implement this, then I would suggest writing a script in whichever language you prefer that eventually calls `chezmoi add` with the relevant list of files.

**Comment by boehs** [comment]
Thank you for the outlinks!
