### ISSUE TITLE
`No such file or directory` when `chezmoi cd` run with `source myscript.sh` in `.bashrc`

### ISSUE THREAD

**Issue by dharmaturtle** [twpayne/chezmoi#1755]
This is a resolved issue - I'm documenting it so other Linux newbies like me can easily find it. Perhaps it is obvious, but I'm a noob so it took some thrashing to figure out 😅 

## Initial conditions

My `.bashrc` contained lines that shouldn't be public. I moved those lines to `~/private.sh` and added `source private.sh` to my `.bashrc`. Now I can safely `chezmoi add ~/.bashrc` and push it to a public repository without exposing `private.sh`.

## Problem

However, now `chezmoi cd` prints the following:

```
$ chezmoi cd
bash: private.sh: No such file or directory
```

## Solution

Qualify the path: `source ~/private.sh`. Note the `~`.

Qualifying the path seems like a "best practice", even if you don't use chezmoi. You can't always know how/where a terminal session begins. I believe that chezmoi starts a new session in order to `cd` your current prompt, which leads to this behavior.

Thanks for a great project Tom :)

**Comment by twpayne** [comment]
Thanks for sharing this and the kind words :)

> Qualifying the path seems like a "best practice", even if you don't use chezmoi. You can't always know how/where a terminal session begins. I believe that chezmoi starts a new session in order to `cd` your current prompt, which leads to this behavior.

Yes, `chemzoi cd` starts your shell (`bash` in the case) with the bash working directory set to the source directory. When bash starts it executes its init scripts like `~/.bashrc`. If `~/.bashrc` uses a relative path, as in your `source private.sh`, then bash will look for `private.sh` in its working directory. This file doesn't exist.

A couple of things to note:
* The expansion of `~` to your home directory is performed by your shell. Not all shells use this. Using `$HOME` instead is generally more portable.
* If you want to keep data private, I recommend using a password manager. There are some [tips in the how-to](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#keep-data-private).
