### ISSUE TITLE
Can `chezmoi diff` command be faster (if there's no any workaround)?

### ISSUE THREAD

**Issue by CodesOfRishi** [twpayne/chezmoi#1758]
## What exactly are you trying to do?
I defined a user-defined segment in [Powerlevel10k](https://github.com/romkatv/powerlevel10k), so that my prompt can indicate if there are any changes between the target and destination state using the `chezmoi diff` command.

**My user-defined segment function in `.p10k.zsh`:**
```bash
function prompt_chezmoi_dirty() {
	[[ ! $( chezmoi diff | wc -l ) -eq 0 ]] && p10k segment -t "chezmoi dirty" -f "#FF5733"
}
```

Now, using the segment above makes the prompt slower! As I checked, it's only happening when I am using the `chezmoi diff` command in the function.

Even if running the below two commands at a time, one can see the difference,
```bash
[[ ! $( chezmoi diff | wc -l ) -eq 0 ]] && echo "chezmoi dirty"

[[ $( git status 2>&1 ) != fatal* ]] && echo "In a git repo"
```

## What have you tried so far?
None

## Where else have you checked for solutions?
None

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag
None

## Output of `chezmoi doctor`

```console
RESULT   CHECK                MESSAGE
ok       version              v2.9.2, commit 9c082e4fe4b74ec9909d1244f29eaacc26b20b1b, built at 2021-12-02T07:22:55Z, built by goreleaser
ok       os-arch              linux/amd64 (Ubuntu 20.04.3 LTS (Focal Fossa))
ok       go-version           go1.17.3 (gc)
ok       executable           ~/.local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /usr/bin/zsh
ok       edit-command         found /usr/bin/nvim
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.34.1
ok       merge-command        found /usr/bin/nvim
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/bin/gpg, version 2.2.19
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context
None

**Comment by twpayne** [comment]
`chezmoi diff` has to compute the target state of every file managed by chezmoi in your home directory, compare it to the actual state of each file in your home directory, and compute any diff. This has to be done for hundreds or thousands of files. Computing the target state might include downloading externals, decrypting files, or invoking your password manager multiple times.

This is not fast by nature, and I think it is unwise to run this every time you press enter in your terminal.

There is a [`chezmoi verify`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#verify-target) which is slightly faster as it avoids computing the diff, but chezmoi still needs to check every single file to see if any are modified.

Fundamentally, I think it is a bad choice to include chezmoi status in your prompt.
