### ISSUE TITLE
Built-in age does not support passphrase

### ISSUE THREAD

**Issue by seanfarley** [twpayne/chezmoi#1782]
## Describe the bug

When `age` isn't installed, chezmoi will error with `no recipients specified`.

## To reproduce

When I enable `age` encryption with this config:

```
encryption = "age"
[age]
    passphrase = true
```

then trying to encrypt a file will result in:

```shell
$ echo test > foo
$ chezmoi encrypt foo 
chezmoi: no recipients specified
```

## Expected behavior

The user should be prompted for a passphrase just like when `age` is installed (and correctly prompts for a passphrase). After installing `age`, the user is prompted:

```shell
$ chezmoi encrypt foo
Enter passphrase (leave empty to autogenerate a secure one): 
Confirm passphrase:
```

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose encrypt foo
```

Same as above.

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
```

```
RESULT    CHECK                MESSAGE
ok        version              v2.9.4, commit 7f0702503528fb708a5d9fc7b2a826decb777b26, built at 2021-12-19T21:10:21Z, built by Homebrew
ok        os-arch              darwin/amd64
ok        go-version           go1.17.5 (gc)
ok        executable           /usr/local/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/projects/dotfiles is a directory
warning   suspicious-entries   ~/projects/dotfiles/.chezmoidata.toml
ok        working-tree         ~/projects/dotfiles is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /usr/local/bin/bash
ok        edit-command         found /usr/local/bin/emacsclient
ok        umask                022
ok        git-command          found /usr/local/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/local/bin/gpg, version 2.3.4
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /usr/local/bin/bw, version 1.20.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

## Additional context

Tested on both MacOS and Ubuntu 20.04. I've also tested forcing `--use-builtin-age on` but it didn't change anything.

**Comment by twpayne** [comment]
As [specified in the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#--use-builtin-age-value):

> The builtin `age` command does not support passphrases, symmetric encryption, or the use of SSH keys.

**Comment by seanfarley** [comment]
D'oh! So sorry to have missed this in the docs. A bummer but I can understand; thanks for the great chezmoi!

**Comment by twpayne** [comment]
Background info:
* If the builtin age command supported passphrases, then you'd have to type in your passphrase for many chezmoi commands, which would quickly become tiresome.
* Symmetric encryption is not supported yet because I haven't ported the code from https://github.com/FiloSottile/age yet.
* SSH keys are not supported as the author of age [explicitly recommends not using them](https://pkg.go.dev/filippo.io/age#hdr-Key_management):
   > When integrating age into a new system, it's recommended that you only support X25519 keys, and not SSH keys. The latter are supported for manual encryption operations.

**Comment by seanfarley** [comment]
Thanks for the explanation. The problem I'm running into are on (the many) systems where I'm not root. On some systems, even `gpg` isn't installed.

**Comment by twpayne** [comment]
In this case, I'd recommend using age with asymmetric encryption and copying the private key onto the machine manually.

Note that age supports multiple recipients, so you can use different private keys for different files.

**Comment by seanfarley** [comment]
> In this case, I'd recommend using age with asymmetric encryption and copying the private key onto the machine manually.

But that's equivalent to just copying the original file instead of jumping through the encryption dance :-/

**Comment by twpayne** [comment]
Not really. Using the encrypted files:
* Enables your dotfiles repo to be public, without fear of leaking your secrets.
* Means that anyone who can become you on an individual machine can only decrypt secrets for which the private key is on the same machine.

**Comment by seanfarley** [comment]
> Enables your dotfiles repo to be public, without fear of leaking your secrets.

But I'd still have to keep a file outside of the repo. So, why not just keep the actual file outside the repo instead?

> Means that anyone who can become you on an individual machine can only decrypt secrets for which the private key is on the same machine.

In my case, I want to decrypt the file for configuration. So if someone can become me on the machine, then they can already read the decrypted result.
