### ISSUE TITLE
Returning an array with vault

### ISSUE THREAD

**Issue by slurikadre** [twpayne/chezmoi#1786]
## What exactly are you trying to do?

I'm trying to return an array inside my vault request:

```
vault kv get --format=json 'kv/users/1002/notmuch'
```

Returns:

```json

{
  "request_id": "006ca7d7-9498-2005-f663-b9db19a2156c",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "data": {
      "notmuch": [
        {
          "name": "Bill Bloggs",
          "other_email": "bill@workplace.example.com;",
          "path": "/home/bill/.local/share/mail/notmuch/bill",
          "primary_email": "bill@personal.example.com",
          "profile": "bill",
          "sym_roots": [
            "../../bill",
            "../../bill_work"
          ]
        }
      ]
    },
    "metadata": {
      "created_time": "2021-12-26T08:49:20.52982075Z",
      "custom_metadata": null,
      "deletion_time": "",
      "destroyed": false,
      "version": 2
    }
  },
  "warnings": null
}
```

Now if I want to write a shell script that fills a string with the values of `sym_roots` how would I do that? I can do this with jq by doing:

```
vault kv get --format=json kv/users/1002/notmuch |
jq -j '.data.data.notmuch[].sym_roots[] | @sh'
```

I was thinking of combining this with a solution like https://github.com/twpayne/chezmoi/issues/1369#issuecomment-907209544, it shouldn't be necessary to use `jq` in my script now that I can make direct queries to vault.

That should in theory mean I can use a lot less complicated method than what @bradenhilton suggested to me there now.

I've tried a couple of things:

```
#!/bin/sh

{{ $item := index (vault (printf "kv/users/%s/notmuch" .primaryuid)).data.data.notmuch.sym_roots -}}
value = {{ $item }}

echo $values
```

which gives me the error:

> chezmoi: template: .chezmoiscripts/run_create_notmuch_accounts.sh.tmpl:3:55: executing ".chezmoiscripts/run_create_notmuch_accounts.sh.tmpl" at <.primaryuid>: can't evaluate field sym_roots in type interface {}

Seems should be easy.

**Comment by twpayne** [comment]
What's missing here is that `.data.data.notmuch` is an array, so you need to use `index` to extract the first item, something like (split into three statements for clarity):

```
{{- $vaultJson := vault (printf "kv/users/%s/notmuch" .primaryuid) -}}
{{- $sym_roots := (index $vaultJson.data.data.notmuch 0).sym_roots  -}}
{{- $sym_roots -}}
```

Note that at this point, `$sym_roots` is still an array, so you'll likely want to use `range` to iterate over it.

Please re-open if needed.

**Comment by slurikadre** [comment]
So I think I kinda got this working:

```
#!/bin/bash

{{- $vaultJson := vault (printf "kv/users/%s/notmuch" .primaryuid) -}}
{{- $sym_roots := (index $vaultJson.data.data.notmuch 0).sym_roots  -}}

{{- $values := "" -}}
{{- range $v, $sym_roots -}}
{{-   if gt (len $v) 0 -}}
{{-     $values = list $values $v | join " " }}
{{-   else -}}
{{-    $values = $v }}
{{-   end }}
{{- end }}

values="{{ $values }}"
for i in "${values[@]}" ; do
  printf "$i test"
done
```

Which gives me:

```
../../bill ../../bill_work test
```

The plan is to use `$values` within the shell script with the populated secret.

I'm wondering if I am going about this the wrong way.

**Comment by twpayne** [comment]
You may be confusing what is `text/template` and what is bash. The two are separate languages. The template needs to generate a shell script that bash then runs.

**Comment by slurikadre** [comment]
Well the `text/template` runs first. The idea is that it will populate an array `values`, that will actually look like:

`values=("../../bill", "../../bill_work")`

The intention is to use template just put the data into bash array.

When the actual bash component runs it will then have some values to work with. The `test` thing there was just  atest, that's not intended to be there in the final work.

**Comment by twpayne** [comment]
I suspect that you need to use the [`join` template function](https://masterminds.github.io/sprig/string_slice.html), something like:

```
values=({{ $values | join " " }})
```

**Comment by slurikadre** [comment]
> I suspect that you need to use the [`join` template function](https://masterminds.github.io/sprig/string_slice.html), something like:
> 
> ```
> values=({{ $values | join " " }})
> ```

Hah, yes, i spotted that just then :+1:

**Comment by slurikadre** [comment]
:star: it works:

```bash
#!/bin/bash

{{- $vaultJson := vault (printf "kv/users/%s/notmuch" .primaryuid) -}}
{{- $sym_roots := (index $vaultJson.data.data.notmuch 0).sym_roots  -}}

{{- $values := "" -}}
{{- range $v, $sym_roots -}}
{{-   if gt (len $values) 0 -}}
{{-     $values = list $values $v | join " " }}
{{-   else }}
{{-    $values = $v }}
{{-   end }}
{{- end }}

values=(""{{ $values }}"")
for i in "${values[@]}" ; do
  ln -sf "$i" "$XDG_DATA_HOME/mail/notmuch/test"
done
```
