### ISSUE TITLE
lastpass module is picky about map keys and mangles them

### ISSUE THREAD

**Issue by kdomanski** [twpayne/chezmoi#1790]
## Describe the bug

I'd like to understand why the lastpass functionality parses the notes the way it does. First it tries to parse k-v pairs with the regex `\A([ A-Za-z]*):(.*)\z` and then in changes the first letter of the key to lowercase. So, if I try to use a note with the following content:
```
SOME_VARIABLE:foo
ANOTHERVAR:bar
```
I will end up with the following map:
```
"": "SOME_VARIABLE:foo",
"aNOTHERVAR": "bar"
```

Is there a rationale behind this behavior, or would you be willing to change it to allow more characters in keys (e.g. undescore, dash) and stop changing the letter casing?

## To reproduce

A note in LastPass:
```
SOME_VARIABLE:foo
ANOTHERVAR:bar
```

Template:
```
{{ range $k, $v := (index (lastpass "note with env vars") 0).note -}}
export {{ $k }}={{ $v }}
{{- end -}}
```

## Expected behavior

```
export SOME_VARIABLE=foo
export ANOTHERVAR=bar
```

## Actual behavior

```
export =SOME_VARIABLE:foo
export aNOTHERVAR=bar
```

## Output of `chezmoi doctor`

<details>

```console
RESULT   CHECK                MESSAGE
ok       version              v2.9.4, commit 7f0702503528fb708a5d9fc7b2a826decb777b26, built at 2021-12-19T21:10:21Z, built by Homebrew
ok       os-arch              darwin/amd64
ok       go-version           go1.17.5 (gc)
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /usr/bin/vim
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.32.0
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/local/bin/gpg, version 2.3.4
info     pinentry-command     not set
ok       1password-command    found /usr/local/bin/op, version 1.12.3
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
ok       lastpass-command     found /usr/local/bin/lpass, version 1.3.3
info     pass-command         pass not found in $PATH
ok       vault-command        found /usr/local/bin/vault, version 1.9.2
info     secret-command       not se
```

</details>

**Comment by twpayne** [comment]
See also #607.

This behavior was added to parse notes added by LastPass itself. [This test](https://github.com/twpayne/chezmoi/blob/v2.9.3/internal/cmd/lastpasstemplatefuncs_test.go#L28-L53) shows example output from LastPass and how chezmoi interprets it. The reasons for mangling are:
* The `text/template` language does not have a graceful syntax for keys with spaces in them. For example, to access a field called `Public Key` you cannot use `.Public Key`, you have to write `index . "Public Key"`.
* The lowercasing for the first letter is done to make key names more consistent with other field accesses.

Changing the existing behavior of the `lastpass` function would break backwards compatibility for existing users.

#608 added the [`lastpassRaw` template function](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#lastpassraw-id) which does not do any parsing of the output. This is perhaps a better fit for you if you're using a custom format for data in your notes (I can't find any mention of environment variables in the LastPass Vault UI).

Please re-open if needed.
