### ISSUE TITLE
zsh completion on macOS Monterey 

### ISSUE THREAD

**Issue by gadams999** [twpayne/chezmoi#1797]
## What exactly are you trying to do?

Enable completions for zsh and chezmoi.

## What have you tried so far?

1. Installed chezmoi from source: `curl -sfL https://git.io/chezmoi | sh`
1. Install completion script from `chezmoi completion zsh` to `~/.oh-my-zsh/custom/plugins/chezmoi/chezmoi.plugin.sh` and then modified plugins:

    ```shell
    if [ -f $HOME/.oh-my-zsh/oh-my-zsh.sh ]; then
      export ZSH="$HOME/.oh-my-zsh"
      plugins=(
        git
        chezmoi
      )
      source $ZSH/oh-my-zsh.sh
    ```

1. I've tried various `compinit` commands, removing the cache file, and rehashing.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

N/A. Attempting to tab-complete.

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.9.4, commit 7f0702503528fb708a5d9fc7b2a826decb777b26, built at 2021-12-19T22:18:18Z, built by goreleaser
ok       os-arch              darwin/amd64
ok       go-version           go1.17.5 (gc)
ok       executable           ~/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /usr/local/bin/code
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.32.0
ok       merge-command        found /usr/bin/vimdiff
ok       age-command          found /usr/local/bin/age, version 1.0.0
info     gpg-command          gpg not found in $PATH
info     pinentry-command     not set
info     1password-command    op not found in $PATH
ok       bitwarden-command    found /usr/local/bin/bw, version 1.20.0
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

## Additional context

I can see the `_chezmoi()` and `__chezmoi_debug()` functions loaded. Just execting `_chezmoi` returns the following, I assume this is correct:

```
$ _chezmoi
_tags:comptags:36: can only be called from completion function
_tags:comptry:55: can only be called from completion function
_tags:comptags:60: can only be called from completion function
_tags:comptags:67: can only be called from completion function
_arguments:comparguments:325: can only be called from completion function
```

All tab-completion only returns file system responses, no commands or subcommands.

New to zsh completions, so not sure if there a problem or not. :)

**Comment by twpayne** [comment]
This is really a zsh question, not a chezmoi question.

You need to add the directory containing chezmoi's zsh completion to the zsh `fpath` variable.

I use Homebrew and have the following in my `.zprofile`:
```zsh
fpath+=("$(/opt/homebrew/bin/brew --prefix)/share/zsh/site-functions")
```

In your case, as you've installed chezmoi manually, you'll need to generate the completions file, which you can do with:
```console
$ chezmoi completion zsh > _chezmoi
```
You'll then need to put the `_chezmoi` file in a directory somewhere, add that directory to `fpath` in your `.zprofile`, and then start a new shell.

**Comment by gadams999** [comment]
Thanks for the response. This helped me connect the dots regarding zsh, oh-my-zsh, chezmoi, and completions. I've got it working and now understand the concepts better too. Appreciate the details even when not related to chezmoi!
