### ISSUE TITLE
Migration script from stow-managed dotfiles to chezmoi

### ISSUE THREAD

**Issue by offbyone** [twpayne/chezmoi#180]
I've made a simple bash script that, on a mac at least, will convert a set of stowed dotfiles whose actual files are in `~/dotfiles` into a chezmoi managed homedir.

It's probably got edge cases I haven't run into, but it works fine on my macOS homedir.

Usage: `stow-to-chezmoi.sh [BASE_DIR] [DOTFILES_DIRNAME]`

`BASE_DIR` is the chezmoi destination directory
`DOTFILES_DIRNAME` is the subdirectory of the `BASE_DIR` that stow is run from.

[stow-to-chezmoi.sh](https://github.com/twpayne/chezmoi/files/2805208/stow-to-chezmoi.txt)

**Comment by twpayne** [comment]
Thanks so much @offbyone :) I added your script in #181 setting the author to you. Thank you for the excellent contribution :)
