### ISSUE TITLE
Missing FQDN Hostname on MacOS

### ISSUE THREAD

**Issue by ClayMav** [twpayne/chezmoi#1802]
## What exactly are you trying to do?

I am trying to use fqdnHostname in my templates, and on my linux box, this is working well, but on MacOS, the hostname (found by the command `hostname`) is empty string in output of `chezmoi data` located in either the /etc/hosts file, nor the /etc/hostname file (since that file doesn't exist in my case) seems that MacOS has a different mechanism for storing this hostname.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Searched through the issues and familiarized myself with previous work done on determining fqdn generically for all OS'.

## Output of `chezmoi doctor`

```console
➜  chezmoi git:(main) chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.9.4, commit 7f0702503528fb708a5d9fc7b2a826decb777b26, built at 2021-12-19T21:10:21Z, built by Homebrew
ok       os-arch              darwin/amd64
ok       go-version           go1.17.5 (gc)
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          no config file found
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /usr/local/bin/zsh
ok       edit-command         found /usr/bin/vim
ok       umask                022
ok       git-command          found /usr/local/bin/git, version 2.33.0
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
info     gpg-command          gpg not found in $PATH
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

**Comment by twpayne** [comment]
I recommend [using `scutil`](https://github.com/twpayne/chezmoi/blob/master/docs/TEMPLATING.md#determine-the-hostname-of-a-macos-machine).

**Comment by twpayne** [comment]
Specifically, here's [how I determine the hostname in my own dotfiles](https://github.com/twpayne/dotfiles/blob/master/home/.chezmoi.toml.tmpl#L15-L28).

Hope this helps, please re-open if needed.
