### ISSUE TITLE
Pattern matching in templates?

### ISSUE THREAD

**Issue by gdevenyi** [twpayne/chezmoi#1807]
## Is your feature request related to a problem? Please describe.

I have several systems where I might login to any number of 10's to 100 networked machines which are all similar in configuration, and where the exact machine hostname isn't important to me. I'd like to be able to pattern match template generation based on a partial, rather than exact match of a hostname to avoid having to hard code all the hostnames.

## Describe the solution you'd like

Some sort of pattern matching in templating to be implemented (or documented if it works already)

## Describe alternatives you've considered

Hard coding things.

## Additional context

For example here, I have a number of systems which all have hostname `nia-NN` where I'd like to match on the `nia-`

**Comment by twpayne** [comment]
chezmoi includes templates from [sprig](https://masterminds.github.io/sprig/), as [already documented](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#template-functions), which includes [`hasPrefix`](https://masterminds.github.io/sprig/strings.html) so you can use, for example:

```
{{ if hasPrefix "nia-" .chezmoi.hostname }}
# matched on nia-
{{ end }}
```

**Comment by gdevenyi** [comment]
Perfect, I couldn't find something I recognized as pattern matching, this will do. :+1: Thanks.

**Comment by twpayne** [comment]
Great! sprig also provides a bunch of [`regex*` functions](https://masterminds.github.io/sprig/strings.html) if more advanced pattern matching is needed.

**Comment by gdevenyi** [comment]
I figured it out, I was just looking at https://masterminds.github.io/sprig/ not realizing there was a bunch of sub-pages with more functions :+1:

**Comment by twpayne** [comment]
Yeah, it's a shame that https://masterminds.github.io/sprig/ does not allow linking to individual functions (and also that their function names do not match idiomatic Go (e.g. `fromJson` should be called `fromJSON` 👿), but sadly sprig is the widely-adopted "standard" now.
