### ISSUE TITLE
How to ignore subset of files when adding a directory?

### ISSUE THREAD

**Issue by johnmathews** [twpayne/chezmoi#1823]
## What exactly are you trying to do?

I would like to add an entire directory (`~/.config/nvim`) but ignore a subset of files (`~/.config/nvim/plugin/*`)

## What have you tried so far?

`.chezmoiignore` ignores files when `apply`ing 
I could add every file in `~/.config/nvim` individually, but that seems laborious.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Additional context

fwiw, my intuition around `.chezmoiignore` was the opposite way around, i thought it would ignore when running `chezmoi add ..`

**Comment by twpayne** [comment]
Putting

    .config/nvim/plugins/**

in your `.chezmoiignore` file and then running

    chezmoi add ~/.config/nvim

will add everything in `~/.config/nvim` except `.config/nvim/plugins`. The double star `**` is needed to match multiple directory levels.

**Comment by johnmathews** [comment]
Oh! thanks. 
I'd read about `.chezmoiignore` in the documentation but somehow hadn't understood that.
cheers!
