### ISSUE TITLE
Current advetised pull URL on `git.io` will be deprecated

### ISSUE THREAD

**Issue by cubic3d** [twpayne/chezmoi#1824]
Git announced to deprecate `git.io`, registration of new short URLs is already [disabled](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/). To allow a smoother transition in scrips, it's possibly a good idea to introduce a new URL early.

**Comment by twpayne** [comment]
Thanks for reporting this. #1825 adds `chezmoi.io/get` as a replacement and updates the docs.
