### ISSUE TITLE
ignoring files inside .chezmoitemplates folder

### ISSUE THREAD

**Issue by j-xella** [twpayne/chezmoi#1833]
While I edit with vim any template in `.chezmoitemplates` folder, chezmoi becomes unusable. Trying to invoke it, for example `:!cat % | chezmoi execute-template` gives an error like:

```
chezmoi: template: .update_vim_plugin_from_git.sh.swp:2: unexpected {{end}}
``` 

This happens  because vim creates a temporary swap file next to the edited file (in this case in .chezmoitemplates folder). The swap file is a binary file. chezmoi tries to process all templates in .chezmoitemplates folder (that includes our temp binary file) and chokes on it.

Interestingly, I have the following in `.chezmoiignore` file:

```
**/.*.sw?
```

This is supposed to exclude vim swap files from processing. However, it does not seem to work in .chezmoitemplates folder.

On the other hand, my swap file is obviously a bad "chezmoi template", but it is not referenced anywhere. So it should not make any difference if this is a good template or not. A warning could be produced, but crash is a bit too much, IMO.

**Comment by j-xella** [comment]
`-k` flag does not help either

**Comment by twpayne** [comment]
Thanks for reporting this. Some explanations/clarifications:

> A warning could be produced, but crash is a bit too much, IMO.

chezmoi is not crashing. It is reporting an invalid template and exiting.

> Interestingly, I have the following in `.chezmoiignore` file:
> **/.*.sw?

`.chezmoiignore` applies to files in the target directory, not the source directory.

> `-k` flag does not help either

Indeed, `-k` only applies when writing files. The error here occurs while chezmoi is reading the source state.

I'll modify chezmoi to ignore files starting with `.` in the `.chezmoitemplates` directory, as this is more consistent with how chezmoi treats other files beginning with `.` in the source directory.

In the short term you can work around this by configuring VIM to write its swap files to a different directory, for example by putting the following in your `.vimrc`:

```
set directory=~/vimswap,.
```

**Comment by j-xella** [comment]
Hi, thanks for a quick response. Just a couple of thoughts:

 * The modification you made is not backwards compatible, and may break some people's configurations, correct?
 * Here is a scenario where we would still have a problem: I am editing a template file `.chezmoitemplates/xxx` in vim, and save it in a bad state. Then I fix it and save again. If my vim is configured to save backups of files, I am now having 2 files in .chezmoitemplates : `xxx` and `xxx~`. `xxx~` is a template in a bad state, and will cause chezmoi to exit. Other editors have similar functionality, but different naming convention for the backup files....
 
Now, in all fairness, your proposed solution is simple and solves 90% of the issues. And for most of the people, nothing will be broken. But I wonder if a proper solution would be to make template ingnores configurable, something like `.chezmoiignore` file, but for `.chezmoitemplates` folder?

**Comment by twpayne** [comment]
> * The modification you made is not backwards compatible, and may break some people's configurations, correct?

Yes, you are correct.

However, I think the scope of breakage will be very minimal, i.e. the user has to be using `.chezmoitemplates` and have files in `.chezmoitemplates` that begin with a `.`. At the same time, chezmoi's documentation says [paraphrasing] "files and directories beginning with a `.` are ignored unless they begin with `.chezmoi`" and chezmoi wasn't following its own documentation here, which is why I marked this a bug: either chezmoi's implementation or its documentation were wrong (or both).

The commit message that users will see in the release notes is also clear: it states that files beginning with `.` in `.chezmoitemplates` were not ignored, when they should have been,

That all said, the practical number of users impacted by the change in #1837 is likely to be between zero and three. They will be advanced chezmoi templating users who will get an error message ("template `.foo` not found" or something similar) and will most likely quickly diagnose and fix the problem themselves.

> * Here is a scenario where we would still have a problem: I am editing a template file `.chezmoitemplates/xxx` in vim, and save it in a bad state. Then I fix it and save again. If my vim is configured to save backups of files, I am now having 2 files in .chezmoitemplates : `xxx` and `xxx~`. `xxx~` is a template in a bad state, and will cause chezmoi to exit.

Yes, and this only applies if you're running chezmoi while your editor is open. Again, few people...

> Other editors have similar functionality, but different naming convention for the backup files....

Yes, and chezmoi has already added a workaround for emacs: https://github.com/twpayne/chezmoi/blob/524cf197fefc069cabd60e16ecb578605f847487/internal/chezmoi/sourcestate.go#L741-L746

> But I wonder if a proper solution would be to make template ingnores configurable, something like `.chezmoiignore` file, but for `.chezmoitemplates` folder?

Adding a configuration option does prevent breaking backwards compatibility, but adds complexity and a maintenance burden that has to be borne for a long time to come. I would rather break zero to three existing knowledgable users now and keep things clear for all users going forward.

Obligatory XKCD: https://xkcd.com/1172/

Does this sound reasonable?

**Comment by j-xella** [comment]
> However, I think the scope of breakage will be very minimal, i.e. the user has to be using `.chezmoitemplates` and have files in `.chezmoitemplates` that begin with a `.`. At the same time, chezmoi's documentation says [paraphrasing] "files and directories beginning with a `.` are ignored unless they begin with `.chezmoi`" and chezmoi wasn't following its own documentation here, which is why I marked this a bug: either chezmoi's implementation or its documentation were wrong (or both).

Speaking of the documentation. I wonder if it still [says](https://www.chezmoi.io/reference/special-files-and-directories/chezmoitemplates/) that "If a directory called `.chezmoitemplates` exists, then **all** files in this
directory are parsed as templates"  ;-)

> > * Here is a scenario where we would still have a problem: I am editing a template file `.chezmoitemplates/xxx` in vim, and save it in a bad state. Then I fix it and save again. If my vim is configured to save **backups** of files, I am now having 2 files in .chezmoitemplates : `xxx` and `xxx~`. `xxx~` is a template in a bad state, and will cause chezmoi to exit.
> 
> Yes, and this **only applies if you're running chezmoi while your editor is open**. Again, few people...

I must disagree here. At least with vim, **backup** files and **swap** files are different things. Swap files (the ones starting with dot) are only supposed to exist while a file is opened in the editor, they are used for edit locking, recovery of the last edits after a crash, etc... Backup files, on the other hand, they are like mini version control, they are created during save, contain the previous version of the file and stay until the next save, which could be any period of time, even after the editor is closed.

To be fair, however, swap file is a binary file, so the chances of it being a "bad template" are much much higher. Backup file is more likely to be a "wrong / old" template rather than a bad one. But since it has a different name, it will not be referenced from anywhere, so it is mostly harmless as long as it does not cause chezmoi to exit.
 
> Adding a configuration option does prevent breaking backwards compatibility, but adds complexity and a maintenance burden that has to be borne for a long time to come. I would rather break zero to three existing knowledgable users now and keep things clear for all users going forward.

I am not the author of the code and just guessing here, but I wonder if all the building blocks for this already exist? chezmoi already knows how to parse `.chezmoiignore` file, and how to apply these patterns to a (target) folder. The "new configuration" would be to parse another similar file, and apply the patterns to the `.chezmoitemplates` folder... 

In any case, even with just ignoring the templates starting with dot, this is already a great improvement. Thanks!
