### ISSUE TITLE
User guide is empty

### ISSUE THREAD

**Issue by uhthomas** [twpayne/chezmoi#1834]
## Describe the bug

The [user guide](https://www.chezmoi.io/user-guide/) is empty.

<img width="1265" alt="Screenshot 2022-01-19 at 17 07 52" src="https://user-images.githubusercontent.com/9749173/150179630-e7f26033-9448-47c6-a86f-7a8a69eaed20.png">

## To reproduce

Visit https://www.chezmoi.io/user-guide/.

Tested with Chrome and Safari.

## Expected behavior

The user guide should not be empty.

## Output of command with the `--verbose` flag

N/A

## Additional context

N/A

**Comment by uhthomas** [comment]
Same with the [FAQ](https://www.chezmoi.io/user-guide/frequently-asked-questions/).

**Comment by twpayne** [comment]
Use the table of contents on the left to navigate through the user guide. I'll add some text to make this clearer.

**Comment by uhthomas** [comment]
Great! Thank you. A table of contents on those pages would also be really helpful 😄 The table of contents on the left for the FAQ for instance is not in view and no so easy to discover.

**Comment by twpayne** [comment]
This is now fixed.
