### ISSUE TITLE
Howto: insert templates in .chezmoi.toml.tmpl to have them in chezmoi.toml

### ISSUE THREAD

**Issue by gaerfield** [twpayne/chezmoi#1835]
Want to set the default merge tool to nvim within `.chezmoi.toml.tmpl`.
The resulting `.config/chezmoi/chezmoi.toml`should contain ([source](https://www.chezmoi.io/user-guide/tools/merge/#use-a-custom-merge-command)):
```
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
```
When inserting the following in `.local/share/chezmoi/.chezmoi.toml.tmpl`:
```
[merge]
    command = "nvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
```
The result after `chezmoi init` will (of course) replacing the templates:
```
[merge]
    command = "nvim"
    args = ["-d", "<no value>", "<no value>", "<no value>"]
```
How to escape the templates?

**Comment by twpayne** [comment]
See https://github.com/twpayne/chezmoi/discussions/1706. I'll add an FAQ entry for this.
