### ISSUE TITLE
Any future plans to make chezmoi available as a Go package?

### ISSUE THREAD

**Issue by shakefu** [twpayne/chezmoi#1836]
Looking at the source I noticed everything except the CLI command is `internal`. It would be awesome to be able to import chezmoi for the use case of leveraging its powerful management of dotfiles inside other Go programs. Is this at all on the roadmap?

**Comment by twpayne** [comment]
It's certainly possible, and chezmoi has been implemented with a reasonably good (but also far from perfect) separation between core functionality and user-facing commands that build on that functionality.

Could you be more specific above what "other Go programs" would import chezmoi's functionality? What functionality would chezmoi need to export, and would instead executing the `chezmoi` binary with appropriate arguments be sufficient?

Background info:
* This is technically possible: moving `internal/cmd` and `internal/chezmoi` directories out of `internal/` would immediately export chezmoi's internal APIs, but that's not the hard part :)
* For the indefinite future, I would not commit to any kind of API stability, even though chezmoi is tagged with stable `v2.x.x` version. This stable tag is for the `chezmoi` command, not its internals.

**Comment by shakefu** [comment]
My primary use case is building a larger unified environment manager that's out of the scope of chezmoi itself.

But being able to leverage the really nice chezmoi lifecycle (esp the diff/edit, that's awesome) would be really advantageous. Additionally extending the chezmoi write/overwrite to include templating and yaml merging (with some private API based sources), and finally leveraging some of the chezmoi lifecycle to include scripts/binary/installs. 

Obviously this could just be a fork too, but since it is, for my use case, a smaller part of a larger tool, that wouldn't make a ton of sense.

**Comment by twpayne** [comment]
OK, fixed with #1852.

> Edit: Obviously a not super stable API would not be great, but with SemVer it's definitely manageable.

Note that the semantic version applies to the `chezmoi` command, not to any Go API.
