### ISSUE TITLE
Add sprig for improved template functionality

### ISSUE THREAD

**Issue by jdotjdot** [twpayne/chezmoi#184]
I just started using chezmoi and love it&mdash;it's been only one day and has already totally changed my workflow.

However, the biggest problem I'm running into right now is it's awkward to store many or complex secrets, which is a key use case for me.  For anything beyond the most basic string-token secrets, password managers like 1Password or LastPass don't work well with chezmoi.  For example, even though chezmoi can parse the notes field in a LastPass secret, it's a native colon-separated regex, and it can't handle multiline secrets like kubeconfigs.

This could be dramatically simplified with minimal modifications to the core logic itself if [`sprig`](https://github.com/Masterminds/sprig) template functions were included rather than just `text/template`.  That way, even for a complex secret like a kubeconfig, there would be access to functions like `b64dec` in the template in order to decode complex secrets like kubeconfigs, which could just be base64-encoded ahead of time.

**Comment by twpayne** [comment]
Thanks, this makes sense. I've added the hermetic text functions from `sprig`. The non-hermetic ones will cause problems as they can generate different values each time they are run, so `chezmoi` will always think that a file is out-of-date. I hope that no one has config files written in HTML.
