### ISSUE TITLE
Give feedback to the user when downloading externals when verbose output is set

### ISSUE THREAD

**Issue by rocode** [twpayne/chezmoi#1840]
## Is your feature request related to a problem? Please describe.

When downloading an external archive, chezmoi appears to 'hang' with no output for an extended period of time when downloading large externals over a slow connection, even with maximum verbosity set.

## Describe the solution you'd like

Give an indication that an external is being downloaded, i.e. a file size or a start message when verbose is set.

## Describe alternatives you've considered

During my troubleshooting steps, I eventually identified the issue via a combination of the --debug flag and attempting to download the archive outside of chezmoi, which then revealed that it was much bigger than expected. So --debug technically resolves the issue, but was non-evident to me as an end user. I kept trying to increase verbosity trying to understand what was happening.

## Additional context

#1715 is tangentially related, as it is the first issue that was discovered when troubleshooting, and provides a naive solution: If your car is running slow/appears to not be moving, it may be the pile of bricks in the back. 

#1838 is also related, as the large external archive in my case was a git repository, and git clone/pull gives you some indication of progress feedback.

**Comment by kitos9112** [comment]
I second this one too. I've just started to use the external for `git-repo` types to replace several custom SH scripts, however, when there's an existing folder not initialised with `git` but created in the destination, `chezmoi` replies with exit status 128 from the `git pull` command.

```sh
> chezmoi apply -v
chezmoi: exit status 128
```

```sh
> chemoi apply -v --debug
2022-04-16T17:58:30+01:00 ERR Run error="exit status 128" args=["git","pull"] dir=/Users/msoutullo/.pyenv duration=3.435708ms exitCode=128 path=/opt/homebrew/bin/git systemTime=0.972 userTime=1.304
2022-04-16T17:58:30+01:00 ERR RunCmd error="exit status 128" args=["git","pull"] component=system dir=/Users/msoutullo/.pyenv exitCode=128 path=/opt/homebrew/bin/git systemTime=0.972 userTime=1.304
chezmoi: exit status 128
```

**Comment by twpayne** [comment]
@kitos9112 did you upgrade git to version 2.35.2 or later recently? If so, the `exit status 128` is likely due to [the work-arounds added by git for its recent security vulnerabilities](https://github.blog/2022-04-12-git-security-vulnerability-announced/) and you will need to configure git appropriately (i.e. by setting git's `safe.directory` configuration option).

**Comment by twpayne** [comment]
#2019 connects stdin, stdout, and stderr when running git commands for `git-repo` externals, which should make errors from git more visible.
