### ISSUE TITLE
Broken links in the documentation at https://www.chezmoi.io/

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#1843]
## Describe the bug

The link to the user guide on the main page (https://www.chezmoi.io/) is broken. It is under the heading "Getting started". The link points to https://www.chezmoi.io/user-guide/ which is a 404. Clicking the link in the banner at the top of the page works. It goes to https://www.chezmoi.io/user-guide/setup/.

## To reproduce

Try to follow the links in the documentation.

## Expected behavior

Working links.

## Output of command with the `--verbose` flag

N/A

## Output of `chezmoi doctor`

N/A

## Additional context

N/A

**Comment by twpayne** [comment]
Thanks for reporting this. Fixed in f4c150595c0916da16da792f472ebd70a9cf8e66.
