### ISSUE TITLE
How to check diff for files, added by `add --follow`?

### ISSUE THREAD

**Issue by Mephistophiles** [twpayne/chezmoi#1848]
## What exactly are you trying to do?

How to permanently add a `follow` strategy to the file? In my case:
* I use home-manager + chezmoi on my laptop and chezmoi only on my work pc
* I added symlink file via `chezmoi add --follow ~/.config/starship.toml`
```
❯ exa -l ~/.config/starship.toml
lrwxrwxrwx 84 mzhukov 24 Jan 12:54 /home/mzhukov/.config/starship.toml -> /nix/store/agb14bp4jmhf47vnyfw03mpyf1z9xlda-home-manager-files/.config/starship.toml
```
* `chezmoi diff` gives to me like that:
```
diff --git a/.config/starship.toml b/.config/starship.toml
deleted file mode 120777
index 85ff33208442e1290c3421b6bbbdb4ad405b155b..0000000000000000000000000000000000000000
--- a/.config/starship.toml
+++ /dev/null
@@ -1 +0,0 @@
-/nix/store/agb14bp4jmhf47vnyfw03mpyf1z9xlda-home-manager-files/.config/starship.toml
```

Is there any way to force chezmoi to permanently follow the symlinks for some files?

## What have you tried so far?

Describe what you have tried so far.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.10.1, built by nixpkgs
ok        os-arch              linux/amd64 (NixOS 21.11 (Porcupine))
ok        go-version           go1.16.13 (gc)
ok        executable           /nix/store/zqip5priifakj52srwb27l3h16kaaxjd-chezmoi-2.10.1/bin/chezmoi
ok        upgrade-method       sudo-upgrade-package
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.dotfiles is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.dotfiles is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /run/current-system/sw/bin/fish
ok        edit-command         found /run/current-system/sw/bin/nvim
ok        umask                022
ok        git-command          found ~/.nix-profile/bin/git, version 2.33.1
warning   merge-command        vimdiff not found in $PATH
ok        age-command          found /run/current-system/sw/bin/age, version 1.0.0
ok        gpg-command          found ~/.nix-profile/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /run/current-system/sw/bin/bw, version 1.19.1
ok        gopass-command       found ~/.nix-profile/bin/gopass, version 1.13.0
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by twpayne** [comment]
`add --follow` is convenience for users migrating to chezmoi from dotfile managers that use symlinks. It does not record state.

Fundamentally, using multiple dotfile managers to manage the same dotfile but with different contents (e.g. `~/.config/starship.toml` being a real file with chezmoi but an ever-changing symlink in home-manager) is going to cause conflicts, and I would suggest simply not doing it. Ultimately, only one of chezmoi or home-manager can be the single source of truth for what `~/.config/starship.toml` is and contains.

If you do insist on using two different dotfile managers to manage the same file, then I would suggest configuring chezmoi to ignore `~/.config/starship.toml` on your laptop where it is managed by home-manager. You can then copy changes from home-manager using:

```console
$ cat ~/.config/starship.toml > $(chezmoi source-path ~/.config)/starship.toml
```

and committing the changes to your chezmoi source repo.

Another option would be, if starship supports reading its config file from different locations (and it should do, if it follows the XDG spec), would be to have chezmoi manage the file in one location on your work PC and ignore it completely on your laptop. You'll still need to manually move changes.

I'm not familiar with home-manager, but it looks like it generates a limited set of dotfiles for some well-known programs. Is there a reason to keep your starship config in home-manager and not just use chezmoi for it?

**Comment by Mephistophiles** [comment]
Thanks for the clarification! I will keep the variant copying the file after the home-manager setup (https://github.com/nix-community/home-manager/pull/389#issuecomment-421460199). 

>  Is there a reason to keep your starship config in home-manager and not just use chezmoi for it?

In general, I use home manager because it automatically adjusts the config to the latest versions of programs without losing backward compatibility. Still, in the case of the starship, it's just a copy-paste from the config. So in the future, I will switch to a regular file.

Once again - thank you very much!
