### ISSUE TITLE
Recursive exact_ attribute on directories

### ISSUE THREAD

**Issue by ajgrf** [twpayne/chezmoi#1849]
## Is your feature request related to a problem? Please describe.

I'm working on a custom [doom](https://github.com/hlissner/doom-emacs) module inside my dotfiles repo, and want the module folder in $HOME to match exactly the state of my working tree. Files which remain after a rename or deletion can continue to affect my configuration. To achieve this currently, I have to add the exact_ attribute to every single directory.

When I do this I end up with file paths like `dot_config/doom/exact_modules/exact_tools/exact_chezmoi/exact_autoload/chezmoi.el`, which is quite ugly.

## Describe the solution you'd like

The exact_ attribute on a directory should apply recursively. In the above example, it would only need to be applied to the modules directory.

(P.S. Sorry for the poor state of my initial issue report. I accidentally submitted it when I thought another window was focused.)

**Comment by twpayne** [comment]
> The exact_ attribute on a directory should apply recursively. In the above example, it would only need to be applied to the modules directory.

This would break existing users and reduce functionality: for example, it makes it impossible to have a non-`exact_` directory inside an `exact_` directory.

Have you considered using an [external](https://www.chezmoi.io/user-guide/include-dotfiles-from-elsewhere/) to add your custom doom module instead?

**Comment by twpayne** [comment]
`recursive_` breaks the current property that an entry's attributes are purely determined by its basename in the source directory. With `recursive_`, you'd have to also inspect the basenames of all its parent directories.

Have you considered using `chezmoi edit` to invoke emacs? It creates hardlinks in a temporary directory so the path you see in your editor matches the path in the target state. For example, `dot_config/doom/exact_modules/exact_tools/exact_chezmoi/exact_autoload/chezmoi.el` appears as `$TMP/.config/doom/modules/tools/chezmoi/autoload/chezmoi.el`.

**Comment by twpayne** [comment]
Closing this for now. Please re-open if needed.
