### ISSUE TITLE
raspberry pi supported?

### ISSUE THREAD

**Issue by niksfirefly** [twpayne/chezmoi#185]
Is raspberry pi 3 or zer0 W supported?
regards

**Comment by twpayne** [comment]
Yes, `chezmoi` works on all Linux systems, including Raspbian. There're aren't any pre-built packages for `armhf` yet, but you can install it with the Go tool:

    $ go get -u github.com/twpayne/chezmoi

**Comment by niksfirefly** [comment]
thx
can I compile version for Pi in linux VM ?

**Comment by twpayne** [comment]
Yes, go supports cross-compiling. See this post on [cross-compiling Go applications for the Raspberry PI](https://www.thepolyglotdeveloper.com/2017/04/cross-compiling-golang-applications-raspberry-pi/) for example.

**Comment by niksfirefly** [comment]
during compile on Rpi3 error and nothing happens
# github.com/Masterminds/sprig
/home/root/.gocode/src/github.com/Masterminds/sprig/date.go:69: time.Since(t).Round undefined (type time.Duration has no field or method Round)

**Comment by twpayne** [comment]
You need a more recent version of Go, I'm not sure which version exactly, but it will definitely work with Go 1.11.

**Comment by niksfirefly** [comment]
unfortunately ubuntu offers only go 1.10
fortunately there is snap package go 1.15 and it works on Rpi :)
