### ISSUE TITLE
Editied all local files with huge changes 

### ISSUE THREAD

**Issue by Decapitater** [twpayne/chezmoi#1853]
## What exactly are you trying to do?
Tried to update my dotfiles locally and forgot the chezmoi edit or any other way 
i dont know what to do as i would be unable to remove and readd the huge amounts of file manually

Describe in as much detail as possible.

## What have you tried so far?
I Have done this foolishness before and i  had to readd files 
i have searched thoroughly but i am unable to understand 
i have read docs 
Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

<Output>

```console
$ chezmoi --verbose merge -n ~/.config/nvim/init.vim
```

panic: .config/nvim/init.vim: not in source state

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceState).MustEntry(0xc00018ea80, {{0x7ffcb871759e, 0xc00072c240}})
	github.com/twpayne/chezmoi/v2/internal/chezmoi/sourcestate.go:707 +0xbc
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).runMergeCmd(0xc000541010, 0xc000418468, {0xc00072c240, 0xc000541020, 0xc00013e720}, 0xc000144740)
	github.com/twpayne/chezmoi/v2/internal/cmd/mergecmd.go:49 +0xa5
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).makeRunEWithSourceState.func1(0xc000790f00, {0xc00072c240, 0x1, 0x3})
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1220 +0x97
github.com/spf13/cobra.(*Command).execute(0xc000790f00, {0xc00072c210, 0x3, 0x3})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000130500)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0xc00081fe00, {0xc0000320b0, 0x4, 0x4})
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1092 +0x78
github.com/twpayne/chezmoi/v2/internal/cmd.runMain({{0x5626e79d8218, 0x6}, {0x0, 0x0}, {0x5626e79d92d0, 0x14}, {0x0, 0x0}}, {0xc0000320b0, 0x4, ...})
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:259 +0x151
github.com/twpayne/chezmoi/v2/internal/cmd.Main({{0x5626e79d8218, 0x6}, {0x0, 0x0}, {0x5626e79d92d0, 0x14}, {0x0, 0x0}}, {0xc0000320b0, 0x4, ...})
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:121 +0xc9
main.main()
	github.com/twpayne/chezmoi/v2/main.go:26 +0x125
</Output>

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```
RESULT    CHECK                MESSAGE
warning   version              v2.10.0, built at 2022-01-17T03:42:43Z
ok        os-arch              linux/amd64 (Arch Linux)
ok        go-version           go1.17.6 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /usr/bin/fish
ok        edit-command         found /usr/bin/vi
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.32
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /usr/bin/bw, version 1.20.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
</details>

## Additional context
I have changed my internal directory of chezmoi from all the files going to private_dotfiles to their separate ones for ex: /.local/share/chezmoi/private_dotfiles/nvim ---> /.local/share/chezmoi/nvim
Maybe this is causing problem , i would be more than happy to get a solution for changing files after local changes (yup i read the userguide and i did not understand)

i would be happy to get a assist in my problem 
@twpayne

**Comment by twpayne** [comment]
If you've edited a lot of files then

```console
$ chezmoi re-add
```

will re-add them. See the limitations in the [documentation](https://www.chezmoi.io/reference/commands/re-add/).

If you've moved a lot of files around then you will have to unpick this manually. It may be easier to start with a new dotfiles repo and add the files you want to manage in their new locations.

Hope this helps.

**Comment by Decapitater** [comment]
Thanks for the answer , if i may ask how do you manage the dotfile changes ?

**Comment by twpayne** [comment]
From the [options in the FAQ](https://www.chezmoi.io/user-guide/frequently-asked-questions/usage/#how-do-i-edit-my-dotfiles-with-chezmoi), I use mainly options 1 and 2.
