### ISSUE TITLE
After editing a configuration file using 'chezmoi edit' on my editor emacs, the emacs backup file ending with ~ is tracked by chezmoi

### ISSUE THREAD

**Issue by lgp171188** [twpayne/chezmoi#1854]
## Describe the bug

Emacs is my editor and when I edit configuration files using 'chezmoi edit' and emacs and then save the files, the backup file created by emacs that has the name of the format `<file name>~` is also tracked by chezmoi and shows up in the output of `chezmoi diff` automatically.

For instance, I edited my `~/.zshrc` configuration file using `chezmoi edit ~/.zshrc` and after I saved the file and closed it, there is a `dot_zshrc~` file in the chezmoi working directory. 

I tried adding `*~` to a `.chezmoiignore` file and also added that file to chezmoi but that didn't ignore that file either. For this specific thing, I could have misunderstood how the `.chezmoiignore` file works.

## To reproduce

* Edit a configuration file added to `chezmoi`, say `~/.zshrc` using `emacs`. Save and quit emacs. With vanilla emacs configuration, a backup file `~/.zshrc~` will be created.

## Expected behavior

`chezmoi` doesn't automatically track `~/.zshrc~` without the user explicitly asking it to.

## Output of command with the `--verbose` flag

<details>

```console
$ chezmoi --verbose diff
diff --git a/.zshrc b/.zshrc
index 1c5ca8f438f0185a6fa4a6736e3c0e829dd714a6..09d0b3b96bdecf4b80c4724dbf47943243deaa02 100644
--- a/.zshrc
+++ b/.zshrc
@@ -20,6 +20,8 @@
 # Set up the configuration for various utilities.
 eval "$(starship init zsh)"
 eval "$(direnv hook zsh)"
+source /usr/share/fzf/completion.zsh
+source /usr/share/fzf/key-bindings.zsh
 
 # Set up environment variable overrides.
 export EDITOR='emacsclient'
diff --git a/.zshrc~ b/.zshrc~
new file mode 100644
index 0000000000000000000000000000000000000000..1c5ca8f438f0185a6fa4a6736e3c0e829dd714a6
--- /dev/null
+++ b/.zshrc~
@@ -0,0 +1,31 @@
+# Lines configured by zsh-newuser-install
+HISTFILE=~/.histfile
+HISTSIZE=10000000000
+SAVEHIST=10000000000
+bindkey -e
+# End of lines configured by zsh-newuser-install
+# The following lines were added by compinstall
+zstyle :compinstall filename '/home/guruprasad/.zshrc'
+
+autoload -Uz compinit
+compinit
+# End of lines added by compinstall
+# Enables auto-completion for commands from newly installed packages.
+
+# Fix buggy delete key behaviour - seen on kal-el
+bindkey  "^[[3~"  delete-char
+
+zstyle ':completion:*' rehash true
+
+# Set up the configuration for various utilities.
+eval "$(starship init zsh)"
+eval "$(direnv hook zsh)"
+
+# Set up environment variable overrides.
+export EDITOR='emacsclient'
+
+# Set up aliases.
+alias cz='chezmoi'
+alias emacs='emacsclient -t -a "" -c'
+alias ls='lsd'
+alias rg='rg -p'
```

</details>

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.10.1, built at 2022-01-24T03:47:18Z
ok        os-arch              linux/amd64 (EndeavourOS)
ok        go-version           go1.17.6 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /usr/bin/zsh
ok        edit-command         found /usr/bin/emacsclient
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.35.0
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.32
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional details
None.

**Comment by twpayne** [comment]
`.chezmoiignore` files work a little differently to `.gitignore` files. Try the following in your `.chezmoiignore`:

```
*~
**/*~
```

**Comment by lgp171188** [comment]
@twpayne, thank you for your quick reply. I will try your example out and report if that fixed my issue. That said, is there a reason why `chezmoi` automatically tries to track files that the user never asked it to explicitly track?

**Comment by lgp171188** [comment]
I already had `*~` in my `~/.chezmoiignore` file and added `***~` to it and also added it to `chezmoi` by running `chezmoi add ~/.chezmoiignore`. But when I edited my `~/.zshrc` file, `chezmoi` still automatically tracks the `~/.zshrc~` file. 😞

**Comment by twpayne** [comment]
> That said, is there a reason why `chezmoi` automatically tries to track files that the user never asked it to explicitly track?

chezmoi isn't doing this. chezmoi uses files in the source state to know what it's tracking, and your editor is creating extra files in the source state, effectively polluting it.

> I already had `*~` in my `~/.chezmoiignore` file and added `***~` to it and also added it to `chezmoi` by running `chezmoi add ~/.chezmoiignore`.

This isn't what's needed. You need to create the `.chezmoiignore` file in `~/.local/share/chezmoi/.chezmoiignore` and add these two lines to it:
```
*~
**/*~
```
Note the `/` in the second line. It is important.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.

**Comment by lgp171188** [comment]
Thank you @twpayne. Adding these patterns to `~/.local/share/chezmoi/.chezmoiignore` stopped `chezmoi` from tracking these backup files. 👍🏼
