### ISSUE TITLE
Add a command for identifying unmanaged files in the destination

### ISSUE THREAD

**Issue by offbyone** [twpayne/chezmoi#186]
I envision something (vaguely!) along these lines:

```
$ chezmoi unmanaged
...
.config/some-app/conf.toml
.local/share/something
...
```

The idea here is to identify files and directories that are:

1. Not managed in this chezmoi repository
2. Are not ignored by it due to `.chezmoiignore`
3. Are the shortest-possible tree entry for their path -- meaning, if a directory is found that is unmanaged, it would appear, but not its sub-directories or contents.

I'm not looking for pedantic homedir management a-la #168, but I would like tools for seeing what I'm missing in my repository.

**Comment by twpayne** [comment]
This is a very interesting idea. The shortest-possible tree entry should mean that the output is short, and also it can be fast as `chezmoi` can probably quickly determine that it doesn't need to descend into these directories.

I'd definitely accept a PR that implements this well.

**Comment by offbyone** [comment]
Oh, that is NICE. Thank you!
