### ISSUE TITLE
Support 1Password CLI 2.0

### ISSUE THREAD

**Issue by cadenkriese** [twpayne/chezmoi#1860]
## Is your feature request related to a problem? Please describe.
Currently, when using the 1Password CLI beta, my template file with a 1Password document fails and breaks `chezmoi apply`.

## Describe the solution you'd like

Chezmoi should check `op -v` and change the syntax appropriately. 

## Describe alternatives you've considered

I could downgrade back to 1.0 but that defeats the purpose of beta testing.

## Additional context

Instructions on the new CLI can be found [here](https://developer.1password.com/docs/cli/upgrade/).

**Comment by twpayne** [comment]
@kdomanski is already on the case in #1828.

Do you have any insight into how stable the 1Password CLI 2.0 is and when it is likely to be released? Normally, I would add support for it to chezmoi once version 2.0 is released.

**Comment by cadenkriese** [comment]
The private discussion forum only has ~3 posts about bugs; the other 30 or so are general questions or feedback, so I think it's reasonably stable? Regardless, a beta's a beta. As for the release timeline, they started this beta in November without two significant features. They said there would be released 'in the coming months.' The first one, biometric unlock, arrived three days ago, probably 2-4 months.
