### ISSUE TITLE
chezmoi does not ignore emacs lock files

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#1866]
## Describe the bug

As [described in `tuh8888/chezmoi.el`](https://github.com/tuh8888/chezmoi.el#lock-files):

> When running chezmoi while working with Emacs, an error will occur when a lockfile is created in the source directory. This occurs when a buffer has been edited, but before it is saved. Emacs creates a file starting with .#. For some reason, chezmoi will attempt to resolve this file, even though it claims to ignore files starting with a . in its reference:
> > chezmoi ignores all files and directories in the source directory that begin with a . with the exception of files and directories that begin with .chezmoi.
> 
> When this occurs, for example when editing your source .bashrc in /.local/share/chezmoi/dot_bashrc, commands such as chezmoi diff will produce errors like: `chezmoi: stat /home/user/.local/share/chezmoi.

## To reproduce

See above.

## Expected behavior

chezmoi ignores the emacs lockfile.

## Output of command with the `--verbose` flag

n/a

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.10.1, commit 6ed080bba2bd3f439832c2bd4b14ed2812c8ee9b, built at 2022-01-23T18:12:56Z, built by Homebrew
ok       os-arch              darwin/arm64
ok       go-version           go1.17.6 (gc)
ok       executable           /opt/homebrew/bin/chezmoi
ok       upgrade-method       brew-upgrade
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell                found /bin/zsh
ok       edit-command         found /opt/homebrew/bin/vim
ok       umask                022
ok       git-command          found /opt/homebrew/bin/git, version 2.35.0
ok       merge-command        found /opt/homebrew/bin/vimdiff
ok       age-command          found /opt/homebrew/bin/age, version 1.0.0
ok       gpg-command          found /opt/homebrew/bin/gpg, version 2.3.4
info     pinentry-command     not set
ok       1password-command    found /usr/local/bin/op, version 1.12.4
ok       bitwarden-command    found /opt/homebrew/bin/bw, version 1.20.0
ok       gopass-command       found /opt/homebrew/bin/gopass, version 1.13.1
ok       keepassxc-command    found /opt/homebrew/bin/keepassxc-cli, version 2.6.6
info     keepassxc-db         not set
ok       lastpass-command     found /opt/homebrew/bin/lpass, version 1.3.3
ok       pass-command         found /opt/homebrew/bin/pass, version 1.7.4
ok       vault-command        found /opt/homebrew/bin/vault, version 1.9.2
info     secret-command       not set
```

</details>

## Additional context

https://github.com/twpayne/chezmoi/blob/master/pkg/chezmoi/sourcestate.go#L813-L822 needs fixing

cc @tuh8888

**Comment by tuh8888** [comment]
I think you may have resolved this already, but I haven't properly tested in my package. I will check shortly on my side and remove the caveat if it seems to not cause issues.

Also, I thought you should be aware that chezmoi.el got merged into MELPA (Emacs package repo): https://github.com/melpa/melpa/pull/7879

**Comment by twpayne** [comment]
Thanks very much for the feedback. I've added a test for skipping the lockfile in #1867, which passes, but the test could well be wrong, so I very much appreciate you testing.

> Also, I thought you should be aware that chezmoi.el got merged into MELPA (Emacs package repo): [melpa/melpa#7879](https://github.com/melpa/melpa/pull/7879)

That's fantastic! Congratulations! I've added a link to `tuh8888/chezmoi.el` in chezmoi's user guide in #1867 too.

**Comment by tuh8888** [comment]
My own attempt at reproducing this issue failed, so I've removed the gotcha from [chezmoi.el](github.com/tuh8888/chezmoi.el)'s README. Using `chezmoi version v2.10.1` btw
