### ISSUE TITLE
How can one handle multiple sources?

### ISSUE THREAD

**Issue by offbyone** [twpayne/chezmoi#189]
I would like to keep a subset of my work scripts in a managed chezmoi repository on our private VCS system, and "merge" it with the stuff I keep in my common dotfiles. Currently, I achieve this with stow and something *like* submodules:

```
repo1/
  common/
    .dotfile
    .other-dotfile
  ssh/
    .ssh/config
  work-repository/ . # <--- a checkout of my work dotfiles repo
    .aws/config
```

I'm not quite sure how to work this out in chezmoi, since it seems to only be able to consider one root at a time. I can, and am planning to, create a second chezmoi source directory that contains just my work things, but I'm not completely sure how to manage diffing and applying once I do.

**Comment by offbyone** [comment]
So, I considered the ignore/template model a bit, but the problem is that I found myself doing a *lot* of redacting to the point where some of my scripts were mashes of templates rather than the original content. It's not so much secrets qua secrets but things like LDAP schema, hostnames, etc...

In addition, I hit the point where I had ~20 files that were entirely wrapped in an `{{- if .work }}` blob. Almost half of the repo, in fact.

So, I was hoping :)

The commands you've laid out are the ones I was already planning on going with; it's not ideal, but it might just work.

**Comment by twpayne** [comment]
@niksfirefly proposal in #205 is a nice way of handling files that vary significantly from machine to machine.

**Comment by twpayne** [comment]
Realistically, handling multiple sources adds too much complication, so I will not attempt it.

**Comment by MurzNN** [comment]
I've created new feature request with suggestion how this can be implemented, let's join to discuss here: https://github.com/twpayne/chezmoi/issues/1169#issuecomment-826645336
