### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#19]
[habarnam](https://www.reddit.com/user/habarnam) on Reddit [suggested](https://www.reddit.com/r/programming/comments/9zss15/chezmoi_a_tool_for_managing_your_dotfiles_across/eacoz36) following the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html). This seems like a good idea.

**Comment by jhillyerd** [comment]
That interesting- although I find right now that I'm more likely to `cd .chezmoi` and make edits & run git commands than run `chezmoi edit` etc; so I don't mind the pollution.

Which reminds me, I have an FR to file...

**Comment by twpayne** [comment]
With #55, there's now a `chezmoi cd` command that launches a shell in your source directory. It's very convenient, and also means that it matters much less where your source directory actually is.

**Comment by EvanCarroll** [comment]
#1132 patch that moves to use ~/.local/bin
