### ISSUE TITLE
Add `external` to the exclude filter of `chezmoi diff`

### ISSUE THREAD

**Issue by fhemberger** [twpayne/chezmoi#1912]
In my chezmoi setup, I include several external resources through `.chezmoiexternal.toml`, for example [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/), which ships docs and extensive unit tests in its repo.

Running `chezmoi diff` to see if I changed files locally which I forgot to commit, I sometimes get long diffs full of "fixed a typo in the docs", "added a unit test", "updated some github config", etc. from those external repositories, which makes it hard to quickly scan the diff for my own changes.

## Describe the solution you'd like

`chezmoi diff` already comes with an `--exclude` flag, allowing the values `all`, `dirs`, `files`, `remove`, `scripts`, `symlinks`, and `encrypted`. I'd like to see an additional value `external`, which doesn't process `.chezmoiexternal.*` for this particular run.

**Comment by twpayne** [comment]
This is a great suggestion, thank you! Implemented in #1915.

**Comment by twpayne** [comment]
Note that the additional value is `externals` (plural) not `external` (singular).

**Comment by fhemberger** [comment]
Wow, that was quick. Thank you!
