### ISSUE TITLE
`chezmoi update`

### ISSUE THREAD

**Issue by k4leg** [twpayne/chezmoi#1913]
`chezmoi update` can only ask for `Username for 'https://github.com'` but not for other services such as GitLab that `chezmoi init` supports.

**Comment by twpayne** [comment]
This is not correct. chezmoi prompts for a password for all services.

What is the output of the following commands?
* `chezmoi doctor`
* `chezmoi update --debug`

**Comment by k4leg** [comment]
[`chezmoi docor` output.](https://pastebin.com/RUnMBjm5)
[`chezmoi update --debug` output.](https://pastebin.com/7KM6xmtB)

Steps to reproduce:
1. `chezmoi init username` — clone dotfiles (e. g. from GitHub).
2. *Remote repository (`origin`) is delete or moved (e. g. to GitLab).*
3. `chezmoi update` gives prompt only for GitHub, not universal.  If I enter `gitlab.com/username` then it gives `Password for 'https://gitlab.com/username@github.com': `.

**Comment by twpayne** [comment]
> 2\. Remote repository (`origin`) is deleted or moved (e. g. to GitLab).

If you delete or move the repository that you initially cloned from, then you to tell git about the new location with the `git remote set-url` command. This has nothing to do with chezmoi.
