### ISSUE TITLE
Update zalando/go-keyring when FreeBSD support gets merged

### ISSUE THREAD

**Issue by torculus** [twpayne/chezmoi#1918]
## Is your feature request related to a problem? Please describe.

I'm using `chezmoi` on FreeBSD, but I couldn't use the integration with `zalando/go-keyring` since FreeBSD isn't supported. I opened an issue [there](https://github.com/zalando/go-keyring/issues/67), and *BSD support should be added soon

## Describe the solution you'd like

When upstream `zalando-keyring` gets released, please test and consider requiring the new version here (so *BSD users can enjoy keyring support with chezmoi)

## Describe alternatives you've considered

Crying over my lack of proficiency to implement this myself

## Additional context

NA

**Comment by twpayne** [comment]
Thank you for suggesting this! I think everything is now in place. Note that for the moment you'll have to build chezmoi from source on your FreeBSD machine to get the keyring functionality, as it indirectly depends on cgo (Go's way of calling C functions) which is not available in chezmoi's official releases (chezmoi's official releases are built on Linux and don't have cgo for FreeBSD).

Please do report any problems.
