### ISSUE TITLE
Unable to add files -- "outside target directory"

### ISSUE THREAD

**Issue by offbyone** [twpayne/chezmoi#192]
On one of my servers, admittedly running an older Linux, I'm seeing this:

```
~/> chezmoi -v add snoop/*.sh
chmod 700 /home/offbyone/.local/share/chezmoi
chezmoi: /local/home/offbyone/snoop/cron_run.sh: outside target directory
~/> ls -ld /home/offbyone/.local/share/chezmoi
drwx------ 12 offbyone users 4096 Jan 30 16:14 /home/offbyone/.local/share/chezmoi/
~/> chezmoi --version
chezmoi version 1.3.0, commit 8d19d62fe1272ea162e4f881b9d56cc2b5990bfe, built at 2019-01-30T06:27:27Z
 ~/> chezmoi doctor
     ok: /home/offbyone/.local/share/chezmoi (source directory, perm 700)
     ok: /home/offbyone (destination directory, perm 750)
     ok: /home/offbyone/.config/chezmoi/chezmoi.yaml (configuration file)
     ok: /bin/vi (editor)
     ok: /usr/bin/git (source VCS command, version 2.16.5)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

I can't figure this one out; this is the only host where I'm encountering the issue, so I'm suspicious that it's something about the OS.

**Comment by offbyone** [comment]
```
~> pwd
/local/home/offbyone
```

I'm in `/local/home/offbyone` as well.

**Comment by offbyone** [comment]
Ah, I see the surface problem: if `$HOME` is a symlink -- and it is, for me -- then the two values don't agree. The realpath of `$HOME` is `/local/home/offbyone` while the value of the `$HOME` environment variable is `/home/offbyone`.

**Comment by twpayne** [comment]
Interesting. I don't think #193 is quite right -- see the comment there.

#194 might help.

**Comment by offbyone** [comment]
I'd love to try it, but I can't build it on the machine that experiences the issue (no compiler modern enough to handle it) and I don't know enough Golang to cross-compile.

**Comment by twpayne** [comment]
Assuming that you're in the `chezmoi` working copy checked out somewhere, you can cross compile with:

```
GOOS=linux GOARCH=amd64 go build -o chezmoi-linux-amd64 .
```

This will produce the `chezmoi-linux-amd64` Linux binary.

**Comment by offbyone** [comment]
Oooh!  /me learns a thing!

**Comment by offbyone** [comment]
I did a bit of testing, and it turns out that for me, `$HOME` is not the abspath, it's the relative. So, `HOME=/users/offbyone` while the realpath of the directory is `/local/users/offbyone`

**Comment by twpayne** [comment]
For what it's worth, this problem is being worked on in https://github.com/twpayne/go-vfs/pull/23.

**Comment by twpayne** [comment]
This should be fixed by #235. However, it's possible that I mis-interpreted your scenario in the [test case](https://github.com/twpayne/chezmoi/commit/7c8e4b622736fcee68314ff64a8ae3295f707ce0). Please test if you can, and re-open this issue if things still don't work.

**Comment by offbyone** [comment]
As far as I can tell, it's not. I pulled the tip of `master` and built it, but I'm still seeing a problem:

```
 ✘  ⚙  ~/chezmoi-linux-amd64 -v add ~/snoop/.list
mkdir -m 755 /home/offbyone/.local/share: mkdir /home/offbyone/.local/share: file exists
chmod 700 /home/offbyone/.local/share/chezmoi
chezmoi: /local/home: outside target directory
 ✘  ⚙ ~/chezmoi-linux-amd64 doctor
     ok: /home/offbyone/.local/share/chezmoi (source directory, perm 700)
     ok: /home/offbyone (destination directory, perm 750)
     ok: /home/offbyone/.config/chezmoi/chezmoi.yaml (configuration file)
     ok: /bin/vi (editor)
     ok: /usr/bin/git (source VCS command, version 2.16.5)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
 ✘  ⚙  pwd
/local/home/offbyone
 ⚙  cd /home/offbyone/
 ⚙  pwd
/local/home/offbyone
 ⚙  
```

**Comment by twpayne** [comment]
Thank you. It looks like I failed to replicate your environment.

Please run the following...

```
ls -l /
ls -l /home
ls -l /local/home
echo $HOME
```

...and post the output here. Please remove any sensitive info before posting the output.

**Comment by offbyone** [comment]
```
$  ls -l /
total 156
dr-xr-xr-x   2 root    root    4096 Feb 17 03:38 bin/
dr-xr-xr-x   4 root    root    4096 Mar 25 03:21 boot/
drwxr-xr-x  10 root    root    4096 Apr 17  2018 cgroup/
drwxr-xr-x  15 root    root    3080 Mar 19 11:07 dev/
drwxr-xr-x 105 root    root   12288 Mar 26 15:56 etc/
drwxr-xr-x   5 root    root    4096 Jan 24 14:05 home/
dr-xr-xr-x  12 root    root    4096 Feb 17 03:38 lib/
dr-xr-xr-x   9 root    root   12288 Feb 17 03:38 lib64/
drwxr-xr-x   5 root    root    4096 Jul  2  2018 local/
drwx------   2 root    root   16384 Nov 14  2016 lost+found/
drwxr-xr-x   2 root    root    4096 Jan  6  2012 media/
drwxr-xr-x   2 root    root    4096 Jan  6  2012 mnt/
drwxr-xr-x   8 root    root    4096 Apr 18  2018 opt/
dr-xr-xr-x 467 root    root       0 Jan 21 13:19 proc/
dr-xr-x---   6 root    root    4096 Mar 26 02:53 root/
drw-------   5 root    root    4096 Jan 19 02:41 run/
dr-xr-xr-x   2 root    root   12288 Feb 17 03:38 sbin/
drwxr-xr-x   2 root    root    4096 Jan  6  2012 selinux/
drwxr-xr-x   2 root    root    4096 Jan  6  2012 srv/
dr-xr-xr-x  13 root    root       0 Mar 26 15:56 sys/
drwxrwxrwt  96 root    root   32768 Mar 26 15:56 tmp/
lrwxrwxrwx   1 root    root       5 Jan 15 11:23 Users -> /home/
drwxr-xr-x  20 root    root    4096 Apr 17  2018 usr/
drwxr-xr-x  33 root    root    4096 Mar 25 03:21 var/
```

```
$ ls -l /home
total 12
lrwxrwxrwx 1 root     root         20 Apr 17  2018 offbyone -> /local/home/offbyone/
drwxr-xr-x 3 root     root       4096 Jan 24 14:05 linuxbrew/
```

```
$ ls -l /local/home
total 136
drwxr-x--- 70 offbyone staff 4096 Mar 26 12:46 offbyone/
```

```
$ echo $HOME
/home/offbyone
```

**Comment by twpayne** [comment]
I created what I believe to be a correct test case for this situation in https://github.com/twpayne/chezmoi/pull/252/commits/529310520b6987901d6169d8db00f1dbdb022501, and in the process found a fixed a small bug (https://github.com/twpayne/chezmoi/pull/252/commits/58bf7e92b9e2100c1c45f5ac65901c3d2774e9dd). However, I'm still unable to duplicate the "outside target directory" directory error that you're seeing.

Could you review the test case and re-open if you spot any problems? I'm a little at a loss here: it seems specific to your machine.
