### ISSUE TITLE
.chezmoi.hostname no longer strips text after the first .

### ISSUE THREAD

**Issue by swt30** [twpayne/chezmoi#1920]
I'm using chezmoi built by the nix package manager on OSX. I updated chezmoi a few days ago to 2.12.0. 

The `.chezmoi.hostname` variable is documented as:
```
The hostname of the machine chezmoi is running on, up to the first .
```
It used to return `swt30-mbp` for me. 

After the update this variable now returns `swt30-mbp.local`, so my templates using this variable have broken. 

```shell
$ chezmoi execute-template "{{ .chezmoi.hostname }}"
swt30-mbp.local
```

This seems like it's probably a bug? Though as a workaround, I can always include the suffix or switch to another test to distinguish between machines.

Also, I see there's a `fqdnHostname`, but this is blank:
```shell
$ chezmoi execute-template "{{ .chezmoi.fqdnHostname }}"
  
```

I hadn't updated chezmoi for a while so was probably a few versions behind - so I'm sorry I can't be more specific about the last working version.

**Comment by swt30** [comment]
I think this is the commit that caused it:
https://github.com/twpayne/chezmoi/commit/b9640d40d6d5001ae8f6bb66c51eedcdafdc34c8#diff-a59528653ec4d512d46856d5f6f241559e6839b4ca63d60e427d298b189003e9

It's trying to split the hostname at `=` instead of `.`

**Comment by twpayne** [comment]
Thanks very much for spotting, debugging, and fixing this :)
