### ISSUE TITLE
Installer script / codespaces env variable conflict

### ISSUE THREAD

**Issue by jfuchs** [twpayne/chezmoi#1924]
## Describe the bug

The script returned from `https://chezmoi.io/get` uses the `GITHUB_USER` environment variable to determine which GitHub repo to request a chezmoi release from. But `GITHUB_USER` is also in [the set of standard environment variables in a codespace](https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace), so the command silently fails.

## To reproduce

1. Follow the instructions described [here](https://www.chezmoi.io/user-guide/machines/containers-and-vms/) to create an install script
2. Create a codespace
3. The dotfiles setup fails to install chezmoi
4. There is no chezmoi to initialize/apply

## Expected behavior

1. The dotfiles setup should successfully install chezmoi
2. Chezmoi should successfully initialize/apply

## Output of command with the `--verbose` flag

n/a — chezmoi was never installed

## Output of `chezmoi doctor`

n/a — chezmoi was never installed

## Additional context

My workaround was to add `GITHUB_USER=""` near the top of my install.sh. If that workaround is the best path, maybe this issue can be closed with a docs update?

**Comment by twpayne** [comment]
Thanks very much for reporting this :)

#1925 fixes it by replacing the use of `GITHUB_USERNAME` with `CHEZMOI_USER_REPO` (so you can also override the repo name in the install script).

I've re-deployed chezmoi.io and the fixed chezmoi.io/get URL should be available in the next few minutes.

**Comment by jfuchs** [comment]
Thanks for the quick fix! One other question: I'm not sure I'd consider it a bug, but I was surprised that the chezmoi.io/get URL redirects to www.chezmoi.io/get. Is that intentional?

**Comment by twpayne** [comment]
> I was surprised that the chezmoi.io/get URL redirects to [www.chezmoi.io/get](http://www.chezmoi.io/get). Is that intentional?

I think is a side effect of chezmoi.io being hosted on GitHub pages. I wanted both https://chezmoi.io/ and https://www.chezmoi.io/ to work, and one of them has to be canonical. I followed [these instructions](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain-and-the-www-subdomain-variant). I suspect that it's GItHub Pages that is reply with the redirect, although I am surprised that www.chezmoi.io is being treated as the canonical domain. If you have any insight into this, I would be happy to hear :)
