### ISSUE TITLE
how to support a cyclical dependency in kube config

### ISSUE THREAD

**Issue by johnstegeman** [twpayne/chezmoi#1944]
## What exactly are you trying to do?

Much like as is described in https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file I am trying to have chezmoi manage my .kube/config file. The documentation shows how to use a template to use the output of kubectl config current-context to set the value for current-context. This, however, will fail on a new fresh machine with no .kube/config file (error: current-context is not set). I thought of using a script to create a bare-bones .kube/config to bootstrap, but that seems like a real hack. Is there any better way to do this?

## What have you tried so far?

Added this snippet to .kube/config

```
current-context: {{ output "kubectl" "config" "current-context" | trim }}
```

When I do that, all is OK if I'm just updating a machine that already has a kube config file, but on a new machine it fails with "error: current-context is not set" I cannot find a way to have a conditional in the template.

## Where else have you checked for solutions?

* [X ] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [X ] Other, google

## Output of `chezmoi doctor`

<details>

```console
RESULT   CHECK                MESSAGE
ok       version              v2.13.1, commit e2e199bd48b9abb89e9a38fb2a5e42970e9267c4, built at 2022-03-03T00:36:40Z, built by Homebrew
ok       latest-version       v2.13.1
ok       os-arch              darwin/amd64
ok       uname                Darwin C02Y1068JGH5 20.6.0 Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64 x86_64
ok       go-version           go1.17.8 (gc)
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell-command        found /usr/local/bin/zsh
ok       shell-args           /usr/local/bin/zsh
ok       cd-command           found /usr/local/bin/zsh
ok       cd-args              /usr/local/bin/zsh
ok       edit-command         found /usr/bin/vi
ok       edit-args            /usr/bin/vi
info     diff-command         not set
ok       umask                022
ok       git-command          found /usr/local/bin/git, version 2.35.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
info     gpg-command          gpg not found in $PATH
info     pinentry-command     not set
info     1password-command    op not found in $PATH
ok       bitwarden-command    found /usr/local/bin/bw, version 1.21.1
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by johnstegeman** [comment]
I have tried this snippet:

```
{{ if stat (joinPath "~" ".kube" "config") }}
current-context: current-context: {{ output "kubectl" "config" "current-context" | trim }}
{{ else }}
current-context: default
{{ end }}
```

But this doesn't seem to work either. On the first run, it will output current-context: default just fine, but on subsequent runs, if i have changed the current-context, chezmoi will prompt me that the file has changed and offer to overwrite or skip. If I overwrite, the current-context is lost.

**Comment by twpayne** [comment]
You could probably use a [`modify_` script](https://www.chezmoi.io/reference/target-types/#modify-file) for this.

**Comment by twpayne** [comment]
> I have a run_once to touch the file

Note you can also use a [`create_` file](https://www.chezmoi.io/reference/target-types/#create-file) for this, e.g. `dot_kube/create_empty_config`.

**Comment by johnstegeman** [comment]
sweeet, thanks so much. I just found chezmoi in my news feed on Saturday, and I love it.
