### ISSUE TITLE
Can't edit private template

### ISSUE THREAD

**Issue by katelovescode** [twpayne/chezmoi#1948]
## What exactly are you trying to do?

I'm trying to edit a private template; the command to `edit` opens a new blank file instead of the one stored by chezmoi - I can go into `~/.local/share/chezmoi/private_dot_aws` and edit the `private_credentials.tmpl` file directly, but if I use the `edit` CLI command it opens what looks like a new file, and returns an error.

## What have you tried so far?

`chezmoi edit ~/.aws/credentials`

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
➜ chezmoi edit ~/.aws/credentials --verbose
chezmoi: warning: /usr/local/bin/code /var/folders/3z/b718q6794kz1r5c7jp016ykh0000gn/T/chezmoi-edit3881051103/.aws/credentials.tmpl: returned in less than 1s
```

## Output of `chezmoi doctor`

<details>

```console
➜ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.14.0, commit 7a2edbef28cc946972799ec287f78cb3b867ead4, built at 2022-03-09T20:56:57Z, built by Homebrew
ok       latest-version       v2.14.0
ok       os-arch              darwin/amd64
ok       uname                Darwin katedonaldson 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
ok       go-version           go1.17.8 (gc)
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          no config file found
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell-command        found /bin/zsh
ok       shell-args           /bin/zsh
ok       cd-command           found /bin/zsh
ok       cd-args              /bin/zsh
ok       edit-command         found /usr/local/bin/code
ok       edit-args            /usr/local/bin/code
info     diff-command         not set
ok       umask                022
ok       git-command          found /usr/local/bin/git, version 2.34.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/local/bin/gpg, version 2.3.4
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
ok       lastpass-command     found /usr/local/bin/lpass, version 1.3.3
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by twpayne** [comment]
Thank you very much for the complete report! I'm pretty sure that you're hitting [this case](https://www.chezmoi.io/user-guide/frequently-asked-questions/troubleshooting/#why-do-i-get-a-blank-buffer-when-running-chezmoi-edit). I also see that chezmoi's documentation has some formatting errors here so I'll tidy that up right now.

**Comment by twpayne** [comment]
So, thanks again for reporting this. It turns out that chezmoi's documentation was particularly lacking in this area. For example, there was no connection between the warning reported by `chezmoi edit` and anything searchable in chezmoi's documentation. #1949 should fix this.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.

**Comment by katelovescode** [comment]
Perfect!  Changing the config worked perfectly, and the explanation was extremely helpful.  Thank you!
