### ISSUE TITLE
Docs: Unclear difference between once and onchange? And about target state

### ISSUE THREAD

**Issue by hydrargyrum** [twpayne/chezmoi#1955]
## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

## Other

The docs mention

```
| `once_`       | Only run the script if it has not been run before                              |
| `onchange_`   | Only run the script if its contents have changed from the last time it was run |
```

but later

> `run_once_` scripts are only executed if a script with
the same contents has not been run before, i.e. if the script is new or if its
contents have changed. `run_onchange_` scripts are executed whenever their
contents change, even if a script with the same contents has run before.
	
So it seems `once` is per-content, not per-file? Does it record the content of every `once` script modification to ensure it will not run again?

Is it based on the filename or cross-filename, i.e. if the script is renamed, will it be considered new, though its content has been run before and not changed since?

## Other

We can read:

> If a directory called `.chezmoiscripts` exists in the root of the source
directory then any scripts in it are executed as normal scripts without
creating a corresponding directory in the target state.

but also for scripts outside `.chezmoiscripts`:

> When chezmoi executes a script, it first generates the script contents in a
file in a temporary directory with the executable bit set, and then executes
the contents with `exec(3)`.

So it seems it wouldn't create a directory in the target state either?

**Comment by twpayne** [comment]
> So it seems `once` is per-content, not per-file? Does it record the content of every `once` script modification to ensure it will not run again?

Yes to both. chezmoi stores this state in a database (`~/.config/chezmoi/chezmoistate.boltdb` by default). Specifically, chezmoi stores the SHA256 sum of every `run_once_` script that it has ever executed, and will not run a `run_once_` script if its SHA256 sum already exists in the database. You can inspect this state with:

```console
$ chezmoi state get-bucket --bucket=scriptState
```

> Is it based on the filename or cross-filename, i.e. if the script is renamed, will it be considered new, though its content has been run before and not changed since?

It is cross-filename, i.e. renaming a `run_once_` script will not cause it to be re-run, only changing its contents will.

In contrast, `run_onchange_` scripts are based on the filename, and, when deciding whether to re-run them, chezmoi will only re-run them if the SHA256 sum is different to the last time that the script with the same filename was run. You can inspect this state with the command:

```console
$ chezmoi state get-bucket --bucket=entryState
```

Note that the state output here includes all target entries, you'll have to search to find the script states, and the names will have been translated into target state filenames, i.e. the `run_onchange_` attributes will have been stripped from the filename.

> We can read:
> 
> > If a directory called `.chezmoiscripts` exists in the root of the source
> > directory then any scripts in it are executed as normal scripts without
> > creating a corresponding directory in the target state.
> 
> but also for scripts outside `.chezmoiscripts`:
> 
> > When chezmoi executes a script, it first generates the script contents in a
> > file in a temporary directory with the executable bit set, and then executes
> > the contents with `exec(3)`.
> 
> So it seems it wouldn't create a directory in the target state either?

Correct, this *will not* create a directory in the target state called `.chezmoiscripts`. When running a script, chezmoi will run the script in the first existing parent directory.

Hope this helps. Any improvements to the documentation would be much appreciated.

**Comment by twpayne** [comment]
Hopefully this answers your question. Please re-open if needed.
