### ISSUE TITLE
Add `ignore` command

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [twpayne/chezmoi#1959]
## Is your feature request related to a problem? Please describe.

I'm kind of confused of how to add patterns to .chezmoiignore. The doc about it is well simplistic. It should have more details, IMHO. The source and destination/target concepts that work little different compared to git add up to the confusion as we have to deal with chezmoi and git at the same time.

## Describe the solution you'd like

It could be nice to have a "chezmoi ignore" command to automatically create .chezmoiignore if it doesn't exist yet and append that pattern to it. And if some of the entries overlaps a managed entry it could be really helpful if, for example, "chezmoi ignored" shows that to confirm that some initially managed entries are being ignored.

## Describe alternatives you've considered

So far, I don't visualize an alternative

## Additional context

N/A so far

**Comment by twpayne** [comment]
Thank you very much for your feedback here. I agree that chezmoi's ignore system is non-obvious. Fundamentally, this comes from the extra precision needed by chezmoi compared to git. git only needs to ignore entries in a directory managed by git (the working copy) whereas chezmoi needs to be able to ignore entries in an arbitrary directory tree (your home directory) with many other files present. In a later version of chezmoi, I would like to fix this.

> And if some of the entries overlaps a managed entry it could be really helpful if, for example, "chezmoi ignored" shows that to confirm that some initially managed entries are being ignored.

#1962 adds a draft `chezmoi ignored` command, which I think works, but needs more tests.

> It could be nice to have a "chezmoi ignore" command to automatically create .chezmoiignore if it doesn't exist yet and append that pattern to it.

Adding a `chezmoi ignore` command is more complicated, as there is no canonical representation of `.chezmoiignore` files.

> I'm kind of confused of how to add patterns to .chezmoiignore. The doc about it is well simplistic. It should have more details, IMHO. The source and destination/target concepts that work little different compared to git add up to the confusion as we have to deal with chezmoi and git at the same time.

If you could be more explicit about which specific parts of the documentation are confusing, it would help me fix them.

**Comment by KlausEverWalkingDev** [comment]
Thanks for the reply, @twpayne. It's a great honor receive that. Certainly I could give some insights about the docs, although I know chezmoi is a tool very very advanced and it has many concepts I don't know. But I can help. Thanks for creating this great tool :)

**Comment by twpayne** [comment]
#1962 adds the `chezmoi ignored` command, and I think it's impractical to add a robust `chezmoi ignore` command so I'll close this for now. If you have ideas for how to improve the documentation, please do say.
