### ISSUE TITLE
Add certain files automatically

### ISSUE THREAD

**Issue by rubiin** [twpayne/chezmoi#1960]
## What exactly are you trying to do?

Describe in as much detail as possible.

I have a script to add the necessary files in my dotfiles repo.
The content goes as :
```sh
chezmoi add .zshrc;
chezmoi add .tmux.conf;
chezmoi add .bin;
.
.
.
and soon
```
Does chezmoi support some sort of configuration so all the files and directories specified are automatically added with command
like chezmoi add-all

## What have you tried so far?

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose <your-command>
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
I'm not sure I understand what you're looking for, but:

1. `chezmoi add` can take multiple arguments, e.g. ` chezmoi add .zshrc .tmux.conf .bin`.
2. There's a [`chezmoi re-add`](https://chezmoi.io/reference/commands/re-add/) command, maybe that's what you want?

**Comment by twpayne** [comment]
Hopefully this answers your question. Please re-open if needed.
