### ISSUE TITLE
PowerShell install command not working

### ISSUE THREAD

**Issue by jibbers42** [twpayne/chezmoi#1979]
## Describe the bug
The powershell install command outputs numeric data to the terminal and does not run the script.

## To reproduce
```
> (iwr -UseBasicParsing https://chezmoi.io/get.ps1).Content | powershell -c -
101
110
117
109
32
76
111
103
76
...
```

**Comment by bradenhilton** [comment]
I can reproduce:

![image](https://user-images.githubusercontent.com/23157013/161183371-543cd9ee-9524-444a-8b0f-306e15df8dd6.png)

It works for me if I use Invoke-RestMethod and use the content directly:

```console
~\Desktop\chezmoi_ps_test
❯ (irm -useb https://chezmoi.io/get.ps1) | powershell -c -
checking GitHub for tag latest
found tag v2.14.0 for latest
found version 2.14.0 for latest/windows/amd64
Installed ~\Desktop\chezmoi_ps_test\bin/chezmoi.exe
```

@twpayne Perhaps this shorthand could be used by default (after a bit more testing), with a sentence or two about what each shorthand actually means? Using shorthands within scripts themselves is generally discouraged, however you can see that the full command

```powershell
(Invoke-RestMethod -UseBasicParsing -Uri https://chezmoi.io/get.ps1) | powershell -Command -
```

is rather verbose. There are, of course, several other ways to execute a remote script in PowerShell, but I don't think any of them are particularly elegant.

I think `-UseBasicParsing` became the default at some point but it cant really hurt to leave it there as `-useb`.

**Comment by zb140** [comment]
I suspect this is happening because the `Content-Type` header for the script is set to `application/octet-stream`. I'm not sure if that's a recent change on the Github side; this definitely worked back when I was originally testing it but I haven't gotten a new computer (and thus freshly installed `chezmoi`) in a while :smile:

Since `Invoke-RestMethod` seems ok with the `Content-Type`, it seems reasonable to switch to `irm`.  I don't recall why I originally wrote `-UseBasicParsing` out in full but abbreviated `iwr`, but in the interest of brevity for a simple install command like this, I think `-useb` would be better.

**Comment by twpayne** [comment]
The change of short URL from `git.io/chezmoi` to `chezmoi.io/get` changed the content type (see #1824).

Specifically `git.io/chezmoi` is eventually served by `raw.githubusercontent.com` and returns a content type of `text/plain`:

```console
$ curl --HEAD -Ls https://git.io/chezmoi | grep -i ^content-type:
Content-Type: text/html;charset=utf-8
content-type: text/plain; charset=utf-8
```

Whereas `chezmoi.io/get` is served by GitHub pages which eventually returns a content type of `application/octet-stream`:

```console
$ curl --HEAD -Ls https://chezmoi.io/get | grep -i ^content-type:
content-type: text/html
content-type: application/octet-stream
```

**Comment by bradenhilton** [comment]
Okay so I looked into this a bit more.

`-UseBasicParsing` became the default (and thus was deprecated, remaining only to facilitate backwards compatibility) in PowerShell Core v6, so it's still required for Windows PowerShell.

Running the command with `RawContent` shows that it does indeed return the script, as one might expect:

```console
~\chezmoi_ps_test
❯ (iwr -useb https://chezmoi.io/get.ps1).RawContent
HTTP/1.1 200 OK
Connection: keep-alive
Server: GitHub.com
Access-Control-Allow-Origin: *
ETag: "622923d0-22c0"
Cache-Control: max-age=600
x-proxy-cache: MISS
X-GitHub-Request-Id: B37E:989E:8DF5D3:9210A3:624662F3
Accept-Ranges: bytes
Date: Sat, 02 Apr 2022 02:35:44 GMT
Via: 1.1 varnish
Age: 157
X-Served-By: cache-lon4234-LON
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1648866945.896712,VS0,VE0
Vary: Accept-Encoding
X-Fastly-Request-ID: 0d52ae0ccbea0dd716750277e87fbb53201a48bf
Content-Length: 8896
Content-Type: application/octet-stream
Last-Modified: Wed, 09 Mar 2022 22:01:52 GMT
Expires: Fri, 01 Apr 2022 02:36:59 GMT

enum LogLevel {
    Debug = 3
    Info = 2
    Error = 1
    Critical = 0
}

$old_eap = $ErrorActionPreference
$ErrorActionPreference = 'Stop' # throw an exception if anything bad happens
...
```

`Invoke-WebRequest` returns a [`BasicHtmlWebResponseObject`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.basichtmlwebresponseobject?view=powershellsdk-7.0.0) (pwsh) or a [`HtmlWebResponseObject`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.htmlwebresponseobject?view=powershellsdk-1.1.0) (Windows PowerShell), both of which have a `ToString()` method.

Using `ToString()` runs the script as expected:

```console
~\chezmoi_ps_test
❯ (iwr -useb https://chezmoi.io/get.ps1).ToString() | powershell -c -
checking GitHub for tag latest
found tag v2.14.0 for latest
found version 2.14.0 for latest/windows/amd64
Installed ~\chezmoi_ps_test\bin/chezmoi.exe
```

So, to me it looks like we can either use 

```powershell
(irm -useb https://chezmoi.io/get.ps1) | powershell -c -
```

or

```powershell
(iwr -useb https://chezmoi.io/get.ps1).ToString() | powershell -c -
```

or perhaps it's possible to change the content type to `text/plain`.

**Comment by twpayne** [comment]
Thanks for the investigation and fixes here. #1988 updates the install instructions and adds a couple of tests so we get warned if this breaks again.
