### ISSUE TITLE
Add arguments to "chezmoi unmanaged" and "chezmoi managed"

### ISSUE THREAD

**Issue by RuijieYu** [twpayne/chezmoi#1985]
## Is your feature request related to a problem? Please describe.
Related to and inspired by #186 -- especially the last two comments from @markstos.

I already have some local additions trying to make `chezmoi unmanaged` work as proposed below, so if this feature request is accepted, I can whip up some more code for both `unmanaged` and `managed` and create a PR somewhat soon.

I don't see this feature proposal as "breaking", because it does not take away people's ability to use, nor modify the behavior of, the `unmanaged` and `managed` commands with no specified paths.

### Feature Descriptions
- `chezmoi unmanaged` would take arbitrary amount of arguments, each assumed to be below the destination root (`c.DestDirAbsPath`).
  - Comparable to `git status`, list the unmanaged files / directories only under the specified paths.
  - If an argument is a directory, list its unmanaged and unignored children. (Think of `ls directory`.)
  - If an argument is not a directory, list itself if unmanaged and unignored. (Think of `ls file`.)
  - Accept additional flag `-r` / `--recursive` (Conceptually similar to `-r` flag in `chezmoi status`)
    - default disabled
    - When enabled, makes `chezmoi unmanaged` recursively list all unmanaged files under the command-line paths. Symlinks are never followed.
    - Potentially very time- and resource-consuming when no paths are supplied, since most files in `~` are unmanaged.
- Similarly, `chezmoi managed` would do the same thing but lists managed files instead under the paths specified on command line.
  - While on the topic, given the similarity of `unmanaged` and `managed`, does it make sense to merge the code base for these two commands and reuse the same portions? (This can be tracked in a different issue if deemed necessary.)

### Proposed synopses
```text
Usage:
  chezmoi unmanaged [paths]... [flags]
  chezmoi managed [paths]... [flags]

Flags:
  -r, --recursive    (recursive description)
```

### Proposed examples
```console
$ chezmoi unmanaged # this part is unchanged
.config/i3
.tmux.conf
$ chezmoi unmanaged ~/.config/ # only find unmanaged files *under* the specified path(s)
.config/i3
$ chezmoi unmanaged ~/.config -r # recursively list all unmanaged files
.config/i3/config
.config/i3/config.d/hello
.config/i3/config.d/world
$ chezmoi unmanaged ~/.config/i3/config # we can also specify file names
.config/i3/config
$ chezmoi unmanaged /etc/i3 # what should happen here? (panic / silent ignore / print + skip / ...)
```
```console
$ chezmoi managed # this part is unchanged
.gnupg/gpg.conf
.ssh/config
.config/emacs
$ chezmoi managed ~/.gnupg ~/.ssh # the commands can accept multiple paths
.gnupg/gpg.conf
.ssh/config
```

### Unmade decisions
- [ ] Is the proposed flag `-r` / `--recursive` necessary?
  - [ ] If so, should `-r` be ignored when no paths are specified? (As in `chezmoi unmanaged -r`)
- [ ] Should `chezmoi unmanaged` descend one level from command-line directories?
  - That is, should `chezmoi unmanaged ~/.ssh` print `.ssh` or `.ssh/config`?
- [ ] What should happen if a path outside of destination root is given?
  - See last example of `chezmoi unmanaged`.

## Describe alternatives you've considered
I have been using the `chezmoi unmanaged | grep TERM` pattern for a long time, but there are two problems I face. 

First, When I want to just list the unmanaged files under multiple directories, I have to do some OR logic on `grep` level using regex or other hacky stuff.
```console
$ chezmoi unmanaged | grep -P 'i3|sway' # current chezmoi
.config/i3
.config/i3blocks
.config/sway
.config/swaylock
$ chezmoi unmanaged .config/{i3,sway} # with proposed changes
.config/i3/config
.config/sway/config
```

In addition, this pattern prints unnecessary files (for me):
```console
$ chezmoi unmanaged | grep emacs
.config/emacs
.config/zsh/config/40-emacs.zsh
```

## Additional context
Currently, the command `chezmoi status` takes arguments similar to this proposal on `chezmoi unmanaged` and `chezmoi managed`.

**Comment by twpayne** [comment]
Thank you for the well-researched and well thought-through enhancement request!

This all sounds good. Please do consider submitting a PR. I'll assign this issue to you. Please match chezmoi's existing style and approach in the [unmanaged](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/unmanagedcmd.go) and [managed](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/managedcmd.go) commands.

A couple of quick notes:

> ### Feature Descriptions
> * `chezmoi unmanaged` would take arbitrary amount of arguments, each assumed to be below the destination root (`c.DestDirAbsPath`).
>   * Potentially very time- and resource-consuming when no paths are supplied, since most files in `~` are unmanaged.

The time- and resource- consumption is currently well limited: as soon as `chezmoi unmanaged` finds an unmanaged directory it returns `vfs.SkipDir` which prevents recursion into the subdirectory.

> Similarly, `chezmoi managed` would do the same thing but lists managed files instead under the paths specified on command line.
> * While on the topic, given the similarity of `unmanaged` and `managed`, does it make sense to merge the code base for these two commands and reuse the same portions? (This can be tracked in a different issue if deemed necessary.)

These two commands are different:
* `chezmoi managed` traverses the source state and lists all targets found there.
* `chezmoi unmanaged` traverses the destination state and lists all targets that are not in the source state.

It may be possible to combine some common elements, but I think that fundamentally they are iterations over different things.

> ## Describe alternatives you've considered
> I have been using the `chezmoi unmanaged | grep TERM` pattern for a long time, but there are two problems I face.

These problems (matching on substrings which matches too much) can be partially resolved by refining the regular expression. For example, given a suitably modern grep, `\b` matches on word boundaries so the regexp `\.config/i3\b` matches `.config/i3` but not `.config/i3blocks`.

**Comment by RuijieYu** [comment]
Thanks for your response. Regarding the point that operations could be costing, I was in the context that we may allow `--recursive` flag which, similar to `ls -R`, recursively lists all unmanaged files instead of stopping at an unmanaged directory.

An example using `git` that just came to my mind to differentiate these two is as follows.

Without `--recursive`, regular behavior:
```console
$ git status -s # list and do not descend into the unmanaged directory
1
2/
```
With `--recursive`, potentially costly behavior:
```console
$ git status -su # recursively list all unmanaged files
1
2/3/4
2/3/5
```

With this in mind, what is your view on the bullet points under "unmade decisions" listed in the post? If you are indifferent, I will try to make sensible decisions for them. Also let me know if anything I said is unclear, and I will try to elaborate.

**Comment by twpayne** [comment]
> ### Unmade decisions
> * [ ]  Is the proposed flag `-r` / `--recursive` necessary?

No, I think that the current behavior of `managed` and `unmanaged` is sufficient. `managed` lists all managed entries. `unmanaged` does not recurse into unmanaged directories.

> * [ ]  Should `chezmoi unmanaged` descend one level from command-line directories?

No, command-line directories should be treated as chezmoi currently treats them (using [`Config.applyArgs`](https://github.com/twpayne/chezmoi/blob/v2.15.1/pkg/cmd/config.go#L508)).

> * [ ]  What should happen if a path outside of destination root is given?

This should return a [`notInAbsDir` error](https://github.com/twpayne/chezmoi/blob/v2.15.1/pkg/chezmoi/errors.go#L39).

**Comment by RuijieYu** [comment]
Sounds good, I will tweak the code to reflect them.
