### ISSUE TITLE
"re-add" discrepency between synopsis and description

### ISSUE THREAD

**Issue by RuijieYu** [twpayne/chezmoi#1986]
## Describe the bug

The description says that `chezmoi re-add` re-adds all modified files, but the usage says `chezmoi re-add [targets...] [flags]`, suggesting that it would be possible to specify individual files / directories to re-add.

However, the source code and the example shell session below shows that `chezmoi re-add` re-adds all modified files, and ignores all potential arguments where the user may try to specify the specific files or directories to re-add changes.  In particular, the `args` parameter of `runReAddCmd` is never used within the function.

## To reproduce

```console
$ echo 1 > ~/file1 ; echo 2 > ~/file2
$ chezmoi add ~/file{1,2}
$ chezmoi status # no output
$ echo 3 > ~/file1 ; echo 2 > ~/file2
$ chezmoi status
MM file1
MM file2
$ chezmoi re-add ~/file1 # this also re-adds file2 as described in description
$ chezmoi status # no output
```

If by design `re-add` should not take arguments, I believe only the [args](https://github.com/twpayne/chezmoi/blob/f10fdcd612df5af8a7b746a7305ba6918fb4140b/pkg/cmd/readdcmd.go#L26) and the [usage](https://github.com/twpayne/chezmoi/blob/f10fdcd612df5af8a7b746a7305ba6918fb4140b/pkg/cmd/readdcmd.go#L21) need to be updated to reflect this intention.  Otherwise, additional code should be added to handle the arguments.

**Comment by twpayne** [comment]
Thanks for reporting this. #1987 updates the help and removes an unused command line flag.
