### ISSUE TITLE
Add openSUSE support

### ISSUE THREAD

**Issue by m-rey** [twpayne/chezmoi#199]
Would it be possible to add openSUSE support to chezmoi?

**Comment by twpayne** [comment]
OpenSUSE is already supported - you can download a RPM or pre-built binary from [the releases page](https://github.com/twpayne/chezmoi/releases) - look for `chezmoi-1.3.0-460-x86_64.rpm` for example. You can also install `chezmoi` with `go get -u github.com/twpayne/chezmoi`.

I'll update the documentation to make it clearer that the RPMs work on OpenSUSE.
