### ISSUE TITLE
multiple sources

### ISSUE THREAD

**Issue by pkpowell** [twpayne/chezmoi#1992]
Is it possible to share data between different repos?
Currently I have two slightly different repos for admin and client prefs where certain content overlaps, e.g. fish functions or public keys. Ideally the admin repo would reference the client repo and add a few other files, but I haven't been able to figure out how to do this.
Great project btw!

**Comment by twpayne** [comment]
Thanks for the kind words!

Currently this can only be achieved by running `chezmoi` twice, once for each repo. Note that the `-S`/`--source` flag allows you to specify the source directory. However, you probably don't want to do this. Read on...

One of the design goals is that chezmoi populates your dotfiles for multiple machines (configs) from a single source of truth, i.e. from a single branch in a single git repo.  In the chezmoi world you would use a single repo for both admin and client prefs. You can control which files are created on different machines with `.chezmoiignore` and control the contents of common files with templates. In your specific case, I would expect the repo to contain all files, but `.chezmoiignore` to exclude some files on client machines. To avoid storing sensitive data (e.g. private keys) in plaintext in the repo, use either a password manager or encrypted files. This will prevent secrets from being stored on client machines.

Hope this helps. Please do follow-up with questions.

**Comment by pkpowell** [comment]
You're welcome, and thanks for clearing things up. 
I think I'll stick with separate repos until I can reliably differentiate between regular-admin and personal-admin accounts.

**Comment by twpayne** [comment]
Ack.

Note that [externals](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/) allow you to bring in files and directories from other repos.

Please re-open if needed.
