### ISSUE TITLE
Potential documentation issue (If I understand how chezmoi works)

### ISSUE THREAD

**Issue by danielo515** [twpayne/chezmoi#1997]
## Describe the bug

Potential documentation mistake or not correctly explained

## To reproduce

This part of the docs

![image](https://user-images.githubusercontent.com/2270425/162437931-466e6775-5aad-4dee-bf54-38598e060fca.png)

## Expected behavior

I expected that to be part of the same repository that everything else lives on. If I am correct, that is under `~/.local/share/chezmoi`, or there is where chezmoi reads my files from. So the path should be `~/.local/share/chezmoi/chezmoi.toml.tmpl` ?

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
[I] ‚ûú  chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.14.0, commit 7a2edbef28cc946972799ec287f78cb3b867ead4, built at 2022-03-09T21:44:20Z, built by goreleaser
warning   latest-version       v2.15.0
ok        os-arch              darwin/arm64
ok        uname                Darwin mac-lan.home 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
ok        go-version           go1.17.8 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /opt/homebrew/bin/nvim
ok        edit-args            /opt/homebrew/bin/nvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.32.0
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /opt/homebrew/bin/bw, version 1.22.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

In general I find the documentation a bit confusing about the paths it refers to. They are not always the same, and the reasoning why the path is not the one expected is not clear.

**Comment by danielo515** [comment]
As a side proposition, what do you think about changing all references to chezmoi paths to instead an execution of `$(chezmoi source-path)`, that should avoid any mismatch issues.

**Comment by twpayne** [comment]
Thanks very much for spotting this. You're right, the docs were incorrect. #1998 fixes this.

> As a side proposition, what do you think about changing all references to chezmoi paths to instead an execution of `$(chezmoi source-path)`, that should avoid any mismatch issues.

This is an interesting idea. I think it would make the documentation less easy to understand however, as an explicit path (e.g. `~/.local/share/chezmoi/dot_file`) does not require the user to understand the `chezmoi source-path` command. As a compromise, I've added a section to the user guide in #1998.

**Comment by danielo515** [comment]
wow, that was a quick fix,thanks. I agree that explicit pats are easier to understand for everybody than a command that "who knows that it returns" and a syntax that requires shell knowledge. Thanks for the extra details
