### ISSUE TITLE
chezmoi managed: have the full path in listing

### ISSUE THREAD

**Issue by esdnm** [twpayne/chezmoi#2004]
If I run `chezmoi managed` in a directory that isn't `~`, it prints the managed files the same way it does if I am in `~`. When I am in `~` it's not very confusing to see the file names not having `~/` in front of them, but if I am in a different directory, seeing the filenames without the full path it confusing.

I want to see the filenames being printed with their full path name, it doesn't need to be the exact full path, like having the part that refers to users home directory can be printed as `~/`

**Comment by twpayne** [comment]
`chezmoi apply` updates your home directory, no matter where you run it from. `chezmoi managed` similarly lists files in your home directory, no matter where you run it from. Given that the paths printed are relative and refer to well known files, I think the current behavior is reasonable.
