### ISSUE TITLE
lastpass not working

### ISSUE THREAD

**Issue by niksfirefly** [twpayne/chezmoi#201]
Ubuntu 18.10 - lastpass is not working - there is no option -j for show in lastpass
show: invalid option -- 'j'
https://lastpass.github.io/lastpass-cli/lpass.1.html
regards

**Comment by niksfirefly** [comment]
nevermind I believe it is old version lastpass package for Ubuntu :(

**Comment by twpayne** [comment]
Thanks for the report. I've added #202 to check for the version of `lastpass` when first used.
