### ISSUE TITLE
.chezmoiscripts sub directories

### ISSUE THREAD

**Issue by 5u623l20** [twpayne/chezmoi#2013]
## What exactly are you trying to do?
Normally beside reading the documentations I try to follow the [dotfiles](https://github.com/twpayne/dotfiles) of @twpayne for reference beside checking the documentation. Recently I saw that you have organized scripts based on `chezmoi.os` in the `.chezmoiscripts` directory. This is not mentioned anywhere in the documentation. Although this works perfectly in the stable version `2.8.0`. But as this one is not mentioned in the documents should I consider it as testing or should I consider it stable feature so that I can use this subdir architecture in my dotfiles?

## What have you tried so far?

Describe what you have tried so far.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
`.chezmoiscripts` is [described in the reference manual](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiscripts/) and is stable.

Please re-open if needed.

**Comment by 5u623l20** [comment]
Yes it does. But it doesn't reference subdirectories of `chezmoi.os` are allowed and that based on `chezmoi.os` it executes the scripts. :)

**Comment by twpayne** [comment]
There is no special treatment of subdirectories. Each script is individually [enabled or disabled for the relevant OS](https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiscripts/darwin/run_onchange_after_configure.sh.tmpl#L1).
