### ISSUE TITLE
Dangling symbolic links listed in .chezmoiremove are ignored

### ISSUE THREAD

**Issue by paltherr** [twpayne/chezmoi#2016]
## Describe the bug

If a file listed in `.chezmoiremove` happens to be a dangling symbolic link (i.e., a link that points to a non existent file or that is part of a loop), then chezmoi ignores it; `chezmoi status` doesn't list it and `chezmoi diff FILE` and `chezmoi apply FILE` both state that it isn't in the source state.

If the symbolic link points to an existing file, then everything works as expected; `chezmoi status` lists it, `chezmoi diff FILE` indicates that the link should be deleted, and `chezmoi apply FILE` deletes the link.

## To reproduce

- Add `foo` to `.chezmoiremove`.
- Run `ln -s foo foo` (or `ln -s bar foo` where `bar` doesn't exist).

After that:
- `chezmoi status` doesn't list `foo`.
- `chezmoi diff foo` states that `foo` isn't in the source state.
- `chezmoi apply foo` states that `foo` isn't in the source state.

## Expected behavior

- `chezmoi status` should list `foo`.
- `chezmoi diff foo` should indicate that `foo` is to be deleted.
- `chezmoi apply foo` should delete `foo`.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose status
$ chezmoi --verbose diff foo
chezmoi: foo: not in source state
$ chezmoi --verbose apply foo
chezmoi: foo: not in source state
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.15.1, commit 462e547efc45432edd6fc9b13bd97a7e51e37f58, built at 2022-04-10T17:25:43Z, built by Homebrew
ok        latest-version       v2.15.1
ok        os-arch              darwin/amd64
ok        uname                Darwin lamajo 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ok        go-version           go1.18 (gc)
ok        executable           /usr/local/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/account-customization/chezhome is a directory
warning   suspicious-entries   ~/account-customization/chezhome/.chezmoitemplates/chezmoi.toml and ~/account-customization/chezhome/.chezmoi.toml.tmpl
ok        working-tree         ~/account-customization is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /usr/local/bin/emacs
ok        edit-args            emacs
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/local/bin/git, version 2.35.2
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by twpayne** [comment]
Thanks for reporting this. I confirm that this is a bug. The bug is in the library that chezmoi uses for file pattern matching, which [does not handle broken symlinks](https://github.com/bmatcuk/doublestar/blob/34e84fce94f2653a09f9660de28b7af951fcb40d/doublestar_test.go#L139-L140).
