### ISSUE TITLE
Chezmoi should correctly understand what "~" for external files

### ISSUE THREAD

**Issue by danielo515** [twpayne/chezmoi#2017]
## Describe the bug

Chezmoi creates a subdirectory called `~` if you put that as path of an external file. Something like this

```toml
["~/.tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm"
refreshPeriod = "1h"
exact = true
```

Will create a nested `~` directory inside your home. I guess chezmoi is supposed to target the home directory, therefore there is no need to specify the home path as destination, but I think chezmoi should be smart enough to understand the intention rather than creating this confusing scenario where noting fails but nothing works.

## To reproduce

Check the example provided above.

## Expected behavior

I expect, at least, a warning, but in the best scenario I want chezmoi to just use my home directory. 

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
RESULT    CHECK                MESSAGE
ok        version              v2.14.0, commit 7a2edbef28cc946972799ec287f78cb3b867ead4, built at 2022-03-09T21:44:20Z, built by goreleaser
warning   latest-version       v2.15.1
ok        os-arch              darwin/arm64
ok        uname                Darwin mac-lan.home 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
ok        go-version           go1.17.8 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
warning   suspicious-entries   ~/.local/share/chezmoi/chezmoi/dot_config/chezmoi/chezmoi.yaml
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /opt/homebrew/bin/nvim
ok        edit-args            /opt/homebrew/bin/nvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.32.0
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /opt/homebrew/bin/bw, version 1.22.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

This frustrated me for a couple of hours

**Comment by twpayne** [comment]
`~` is expanded by the shell, and the chezmoi documentation [explicitly states that the entries in `.chezmoiexternal` are relative paths](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/).

**Comment by danielo515** [comment]
> `~` is expanded by the shell,

no, in my case it is not, chezmoi created a subfolder with that literal name

**Comment by twpayne** [comment]
> > `~` is expanded by the shell,
> 
> no, in my case it is not, chezmoi created a subfolder with that literal name

Exactly. When you use `~` in a shell command, the shell expands this to your home directory before invoking the command. Elsewhere, `~` is a literal name.
