### ISSUE TITLE
How to check in template if a file/dir matches a glob (i. e. it exists)?

### ISSUE THREAD

**Issue by jose1711** [twpayne/chezmoi#2023]
## What exactly are you trying to do?

I would like to modify a template adding a check if a file matching glob exists in the filesystem.

## What have you tried so far?

Checked the documentation: `stat` does not expand globs, `output` produces error (and fails rendering) if e. g. `ls /foo/*/bar` is not a match). I was looking at https://pkg.go.dev/path/filepath#Glob but that does not seem to be available in `chezmoi`.

I was also considering the following but it's not elegant and I am sure there is a better way to achieve the same:

    {{ if output "sh" "-c" "ls -d /foo/bar || true" }} found something {{ end }}

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by twpayne** [comment]
The only way to do it right now that I know of is to use `sh` as you propose.

#2025 adds a `glob` template function to fix this.
