### ISSUE TITLE
Sequence for .chezmoiexternal in Application Order

### ISSUE THREAD

**Issue by 5u623l20** [twpayne/chezmoi#2027]
## What exactly are you trying to do?
Installing files using git-repo from .chezmoiexternal and it already mentions that we need git binary in the $PATH. So trying to figure out the sequence of .chezmoiexternal and run_ scripts

## What have you tried so far?
I want to know how .chezmoiexternal fits in this [application-order](https://www.chezmoi.io/reference/application-order/). So on a fresh Debian system if git is not installed my run_once_before installs git. But even though looks like .chezmoiexternal fails to find git.

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

So this is the snipped output from a GitHub Action log where I am testing my dotfiles in multiplatform. The run_ script is run with -x for debugging purpose.

```console
+ /usr/bin/apt -y install git

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
.
.
.
Setting up git (1:2.30.2-1) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
+ which git
/usr/bin/git
.
.
.
chezmoi: exec: "git": executable file not found in $PATH
Error: Process completed with exit code 1.
```

This just fails when I am trying to use a git-repo in .chezmoiexternal

## Additional context

I think once the installation script of chezmoi begins it fails to find new binaries installed in between run_ scripts and other actions.

**Comment by twpayne** [comment]
What's the output of the failed command with the `--debug` flag?

What's the output of `chezmoi doctor`?

**Comment by 5u623l20** [comment]
> What's the output of the failed command with the `--debug` flag?
> 
https://bsd.to/9RDp
> What's the output of `chezmoi doctor`?
```
RESULT    CHECK                MESSAGE
ok        version              v2.15.1, commit 462e547efc45432edd6fc9b13bd97a7e51e37f58, built at 2022-04-10T17:54:04Z, built by goreleaser
ok        latest-version       v2.15.1
ok        os-arch              linux/amd64 (Debian GNU/Linux 11 (bullseye))
ok        uname                Linux 5a137b53662a 5.13.0-1022-azure #26~20.04.1-Ubuntu SMP Thu Apr 7 19:42:45 UTC 2022 x86_64 GNU/Linux
ok        go-version           go1.18 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
ok        cd-command           found /bin/bash
ok        cd-args              /bin/bash
warning   edit-command         vi not found in $PATH
ok        edit-args            vi
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.30.2
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

**Comment by twpayne** [comment]
Thanks for the extra details. I now see what's happening.

dfca5bbc adding caching of lookups of programs in `$PATH` as an optimization, which resulted in the following:
1. When you run `chezmoi init`, `git` is not in `$PATH`, so chezmoi caches its absence and uses chezmoi's builtin git command to clone your dotfiles repo instead of the `git` command.
2. Your `run_once_before` script installs `git` in `/usr/bin`.
3. chezmoi externals rely on an external `git` command (chezmoi currently cannot use its builtin git for externals), but chezmoi re-uses the cached absence of `git` and reports the `executable file not found` error from step 1.

PR to fix this coming up...

**Comment by twpayne** [comment]
> I think once the installation script of chezmoi begins it fails to find new binaries installed in between run_ scripts and other actions.

This is completely correct.
