### ISSUE TITLE
How is refreshPeriod triggered with .chezmoiexternal?

### ISSUE THREAD

**Issue by 5u623l20** [twpayne/chezmoi#2032]
## What exactly are you trying to do?
In the [.chezmoiexternal](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiexternal-format/) it's mentioned that "The optional duration refreshPeriod field specifies how often chezmoi will re-download the URL." Does this mean that it will be refreshed automatically behind the scene at the mentioned period unless 0 or is it triggered by ```chezmoi update```?

## What have you tried so far?
Currently I have put ```chezmoi update``` in a user crontab but trying to figure out whether if this is absolutely necessary. 

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context
I am trying to figure out whether if I should put ```chezmoi update``` on a crontab for the externals to be updated or is it done behind the scene automagically?

**Comment by twpayne** [comment]
chezmoi only downloads URLs when you run chezmoi. There is no background daemon. For `refreshPeriod` chezmoi will re-download the URL if more than that amount of time has passed since the last download. chezmoi knows about HTTP caching so will only download the URL if its contents have changed since the last download.
