### ISSUE TITLE
Handling of $ErrorActionPreference in install.ps1 install script

### ISSUE THREAD

**Issue by Hrxn** [twpayne/chezmoi#2044]
## Describe the bug

The install script for PowerShell stores the ErrorAction preference variable previously set in the session before it gets changed for the script (Line 8):

https://github.com/twpayne/chezmoi/blob/bf0c9bee555f1de78cd003638621fff375a26867/assets/scripts/install.ps1#L7-L12

But it never gets restored?

## Expected behavior

If you save the pre-existing ErrorAction preference, which is considered good behaviour for a script that does change it,
restore it after the script is done with its tasks..
e.g. here 

https://github.com/twpayne/chezmoi/blob/bf0c9bee555f1de78cd003638621fff375a26867/assets/scripts/install.ps1#L317-L322

`$ErrorActionPreference = $old_eap`

## Output of command with the `--verbose` flag

*no need to even install chezmoi to see*

**Comment by twpayne** [comment]
Thanks for opening the issue :) @zb140 is the expert here.

**Comment by zb140** [comment]
Yep, that definitely looks like an oversight... Good catch! I'm away from my computer until tomorrow but I can fix it when I'm back.

**Comment by bradenhilton** [comment]
Aren't preference value modifications within scripts scoped by default?

```console
❯ $ErrorActionPreference
Continue

❯ Get-Content .\PreferenceTest.ps1
$ErrorActionPreference = 'Stop'
$ErrorActionPreference

❯ .\PreferenceTest.ps1
Stop

❯ $ErrorActionPreference
Continue
```

**Comment by twpayne** [comment]
> Instead of adding a line of code, here we could simply get rid of a line of code, and that's kinda my favorite kind of change 😄

+1. Increasing code quality by removing code is the best change.

Thanks all, I created #2051 with you all as co-authors to fix this.
