### ISSUE TITLE
Handling parts of .xml files

### ISSUE THREAD

**Issue by jose1711** [twpayne/chezmoi#2045]
## What exactly are you trying to do?

Geeqie image editor likes to store last state of its window into its config file (dimensions, maximized yes/no). `chezmoi apply` detects the change every time and it gets a little annoying to have it skipped or overwritten. At the same time I still want `chezmoi` to manage the remaining parts of the config file should something relevant happens in other sections.

## What have you tried so far?

Configuration is in XML format (`geeqierc.xml`) which makes it impossible to process using `sed`. Here is the idea.

```console
$ cat foo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<xml>
<foo>
	<element>this_is_being_changed_on_each_geeqie_invocation</element>
</foo>
<bar>
	<element>this_element_will_be_carried_over_to_other_hosts_on_geeqie_apply</element>
</bar>
</xml>

$ cat test.tmpl
{{ output ( printf "%s/%s" .chezmoi.workingTree "edit_test.sh") ( printf "%s/%s" .chezmoi.homeDir "foo.xml") | trim }}

$ cat edit_test.sh
#!/bin/sh
# any code to merge user-defined changes and the current state of the window
# so that diff does not detect any change here.
# xmlstarlet command used below only as a reference
xmlstarlet ed --delete '/xml/foo' "$1"
```

Does this make any sense to you or I am looking at the problem from a wrong angle (e. g. is reading and a source file within a template a good idea)? Does a better approach exist?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by twpayne** [comment]
chezmoi has [`modify_` scripts](https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file) that can be a good solution in for cases like these.

**Comment by jose1711** [comment]
A minor problem with `modify_` is that it assumes a stream-oriented approach meaning the lines of the file are being modified/removed as they're going into and leaving the processing loop. If a multiple access to the source file is required then one needs to store it in memory or a temporary location. Perhaps this is intentional but I still think it would be great if there was a way to pass only a filehandle - and thus allowing a script to perform any lookups or random jump.
To the original problem. I managed to get pretty close to what I was aiming for with
```
#!/bin/sh
out=$(xmlstarlet sel -t -v '//layout/@show_marks' -o ' ' -t -v '//layout/bar/@width')
marks=$(echo "$out" | cut -d' ' -f1)
width=$(echo "$out" | cut -d' ' -f2)
cat template.xml | xmlstarlet ed -P -S -O -u '//layout/@show_marks' -v "$marks" \
                                          -u '//layout/bar/@width' -v "$width"
```
Does the job (updates the requested fields with the current ones) but even with `-P` switch `xmlstarlet` does not preserve the original formatting and a change is detected. This is a more profound issue and outside of `chezmoi`'s scope though.

**Comment by twpayne** [comment]
> A minor problem with `modify_` is that it assumes a stream-oriented approach meaning the lines of the file are being modified/removed as they're going into and leaving the processing loop. If a multiple access to the source file is required then one needs to store it in memory or a temporary location.

This statement is not correct. You write all of standard input to a file, modify that file, and then write the modified file to standard output:

```bash
#!/bin/sh
tempfile=$(mktemp)
trap 'rm -rf ${tempfile}' EXIT
cat >${tempfile}
# modify ${tempfile}
cat ${tempfile}
```

**Comment by jose1711** [comment]
> > A minor problem with `modify_` is that it assumes a stream-oriented approach meaning the lines of the file are being modified/removed as they're going into and leaving the processing loop. If a multiple access to the source file is required then one needs to store it in memory or a temporary location.
> 
> This statement is not correct. You write all of standard input to a file, modify that file, and then write the modified file to standard output:
> 
Yes, I can understand that but I still see this as a workaround. If you're not planning any change in this regard then perhaps you could update a documentation with the snippet above?

**Comment by twpayne** [comment]
> If you're not planning any change in this regard then perhaps you could update a documentation with the snippet above?

Documented in ccb709c483c8513fde4f5a95b09917d132d87c6c.
