### ISSUE TITLE
chezmoi diff: just list files that are different?

### ISSUE THREAD

**Issue by mathomp4** [twpayne/chezmoi#2050]
## What exactly are you trying to do?

I'm a newbie to chezmoi so I'm still learning it. At the moment, I'm wondering if there is is an option to `chezmoi diff` that is similar to `git diff --name-only`. That is, it would list the files that are different, rather than actually doing the diff.

I did try the User's Guide and Reference Guide, but my search fu failed me.

I'm mainly asking because I'm still trying to set stuff up to work on multiple machines so my diff's are...excitingly large at the moment. Turns out I wasn't very good at using the same rc files on different machines. 😄 

## What have you tried so far?

* `chezmoi diff --name-only` (a la `git-diff`)
* `chezmoi diff -q` (a la `diff`)
* `chezmoi diff --brief` (a la `diff`)

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

Well...no commands worked so... 🤷🏼 

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.15.2, commit bf0c9bee555f1de78cd003638621fff375a26867, built at 2022-05-01T12:04:08Z, built by Homebrew
ok       latest-version       v2.15.2
ok       os-arch              darwin/amd64
ok       uname                Darwin MacBook-Pro-16.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
ok       go-version           go1.18.1 (gc)
ok       executable           /usr/local/bin/chezmoi
ok       upgrade-method       replace-executable
ok       config-file          ~/.config/chezmoi/chezmoi.toml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell-command        found /usr/local/bin/bash
ok       shell-args           /usr/local/bin/bash
ok       cd-command           found /usr/local/bin/bash
ok       cd-args              /usr/local/bin/bash
ok       edit-command         found /usr/local/bin/vim
ok       edit-args            /usr/local/bin/vim
info     diff-command         not set
ok       umask                022
ok       git-command          found /usr/local/bin/git, version 2.36.0
ok       merge-command        found /usr/local/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/local/bin/gpg, version 2.3.6
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
ok       lastpass-command     found /usr/local/bin/lpass, version 1.3.3
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by twpayne** [comment]
I think [`chezmoi status`](https://www.chezmoi.io/reference/commands/status/) might be the command you want.

**Comment by mathomp4** [comment]
> I think [`chezmoi status`](https://www.chezmoi.io/reference/commands/status/) might be the command you want.

Well I feel dumb. I saw it in the list of commands but I guess I thought it was something like `doctor`. 

Looks like it does a `git-status --porcelain=v2` like output? Cool. 

Welp, I guess I can close this!
