### ISSUE TITLE
chezmoi init fails if repository url doesn't have .git ending

### ISSUE THREAD

**Issue by privatewright** [twpayne/chezmoi#2052]
## Describe the bug

I've found out that chezmoi init fails if the remote repository url doesn't have .git in its path. This has no problem if the git repository can be accessed from a .git ending path (such as git.site.com/user/repo.git) with git implementation such Github, Gitlab, or Gitea.

However, some git implementations doesn't have .git ending in its git clone path, for example in [Onedev](https://github.com/theonedev/onedev), the repository is stored in git.site.com/user/repo only and cloning with git.site.com/user/repo.git will fail. It seems chezmoi tried to expand the path from git.site.com/user/repo to git.site.com/user/repo.git, but failed as the url doesn't exist in the particular git implementation. 

Maybe chezmoi can fallback to the git.site.com/user/repo if the git.site.com/user/repo.git path doesn't exist? I've scanned the particular regex implementation in initcmd.go and it seems that only [sourcehut](https://git.sr.ht) is currently supported for regex guess that doesn't involve .git in its path. 

Better yet, maybe chezmoi can add additional flag for init command to support literal url so that chezmoi doesn't have to support all possible implementations of git path (for example, Onedev can also have git.site.com/repo path or in the case of self-hosted ssh git repo, the repo url may involve long file paths). 

## To reproduce

Run chezmoi init with repository url that doesn't have .git and the remote repo git clone url doesn't have .git ending in its path.

## Expected behavior

Chezmoi repository is initialized normally

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose init git.site.com/user/repo
Cloning into '/home/privatewright/.local/share/chezmoi'...
fatal: remote error: Unable to find project 'user/repo.git'
chezmoi: exit status 128
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.15.2, commit v2.15.2, built at 2022-05-02, built by xbps
ok        latest-version       v2.15.2
ok        os-arch              linux/amd64 (Void)
ok        uname                Linux privatewright 5.15.36_1 #1 SMP Wed Apr 27 13:50:49 UTC 2022 x86_64 GNU/Linux
ok        go-version           go1.18.1 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /bin/nvim
ok        edit-args            /bin/nvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /bin/git, version 2.36.0
warning   merge-command        vimdiff not found in $PATH
ok        age-command          found /bin/age, version 1.0.0
ok        gpg-command          found /bin/gpg, version 2.2.34
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

In case it's not obvious, I'm using Onedev and the error happens when I try to initialize the repository in a new machine. I've previously hosted the same repository in Gitea and it has no problem before and after in the same machine. I've tried using the full url https://git.site.com/user/repo, but it still fails.

**Comment by twpayne** [comment]
Thanks very much for reporting this - I hadn't anticipated this case.

> Better yet, maybe chezmoi can add additional flag for init command to support literal url so that chezmoi doesn't have to support all possible implementations of git path (for example, Onedev can also have git.site.com/repo path or in the case of self-hosted ssh git repo, the repo url may involve long file paths).

#2053 adds a `--guess-repo-url` option (`-g` for short and defaulting to `true`) so you will be able to use:

```console
$ chezmoi init --guess-repo-url=false git.site.com/user/repo
```

or, equally, using short options:

```console
$ chezmoi init -gn git.site.com/user/repo
```
