### ISSUE TITLE
chezmoi apply produce errors if file listed in .chezmoiignore are not present in the home directory

### ISSUE THREAD

**Issue by claudio4** [twpayne/chezmoi#2054]
## Describe the bug
Files listed in `.chezmoiignore` will produce an error in the `chezmoi apply` if they are not present in the home directory.
Example output (with debug, the error also appears withot the debug flag):
```console
.oh-my-zsh/cache/.gitkeep has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? overwrite
diff --git a/.oh-my-zsh/cache/.gitkeep b/.oh-my-zsh/cache/.gitkeep
new file mode 100644
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/.oh-my-zsh/cache/.gitkeep
chezmoi: stat /home/claudio4/.oh-my-zsh/cache: no such file or directory
```
## To reproduce
1. Add a file to `.chezmoiignore`.
2. Ensure that the file does not exist in the destination directory (a.k.a home directory).
3. Commit chezmoi config.
4. Execute `chezmoi apply`

## Expected behavior
`chezmoi apply` should be performed without errors.
## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.15.2, commit bf0c9bee555f1de78cd003638621fff375a26867, built at 2022-05-01T13:19:59Z, built by goreleaser
ok       latest-version       v2.15.2
ok       os-arch              linux/amd64 (Ubuntu 21.10 (Impish Indri))
ok       uname                Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ok       go-version           go1.18.1 (gc)
ok       executable           /usr/bin/chezmoi
ok       upgrade-method       sudo-upgrade-package
ok       config-file          no config file found
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell-command        found /usr/bin/zsh
ok       shell-args           /usr/bin/zsh
ok       cd-command           found /usr/bin/zsh
ok       cd-args              /usr/bin/zsh
ok       edit-command         found /usr/bin/vim
ok       edit-args            /usr/bin/vim
info     diff-command         not set
ok       umask                022
ok       git-command          found /usr/bin/git, version 2.32.0
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/bin/gpg, version 2.2.20
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by twpayne** [comment]
I tried to reproduce this in #2054, but was unsuccessful.

Is there anything special about your setup? I notice that you're running on WSL2. Is it possible that you have some broken symlinks?

What is the output of the following command?

```console
$ ls -l $HOME/.oh-my-zsh/cache
```

Can you provide steps to reproduce the problem on an empty system?

**Comment by claudio4** [comment]
I'm sorry, I overlooked a crucial step, for this to trigger you also need a `.chezmoiexternal.toml` that overlaps with the ignored file.

A minimal example will be a `.chezmoiignore` with 
```
.oh-my-zsh/cache

```
And a `.chezmoiexternal.toml` with:
```toml
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
```

**Comment by twpayne** [comment]
Thank you for the extra details. I think that the following is happening:
* The oh-my-zsh archive contains a `cache` directory.
* The `.chezmoiignore` file specifies that the `cache` directory should be ignored.
* Therefore chezmoi ignores the `cache` directory in the oh-my-zsh archive, and we get the "no such file or directory" error.

I think the fix is to configure chezmoi to ignore the _contents_ of the `.oh-my-zsh/cache` but not the directory itself. You can do this by changing your `.chezmoiignore` file to contain

```
.oh-my-zsh/cache/**
```

Could you test this?

**Comment by claudio4** [comment]
Yes, that fixes it. Thank you!
