### ISSUE TITLE
glob template function does not work with joinPath on Windows

### ISSUE THREAD

**Issue by neersighted** [twpayne/chezmoi#2063]
The newly added `glob` template function requires all input paths to use forward slashes. Meanwhile, the `joinPath` template function specifically coerces all slashes to the platform-specific separator. This means that on Windows, where backslashes are used, `joinPath` cannot be combined with `glob`.

To resolve this, `filepath.ToSlash()` could be called on all inputs before they are passed to `doublestar.Glob()`.

**Comment by twpayne** [comment]
Thank you very much for reporting this and describing the fix. #2071 should fix it. Would you be able to test ths?
