### ISSUE TITLE
Include not working when extracting subfolders from external archive

### ISSUE THREAD

**Issue by jmgilman** [twpayne/chezmoi#2065]
## What exactly are you trying to do?

I'm trying to extract a subfolder out of an archive and place it on my local system. 

## What have you tried so far?

The syntax for the `include` parameter for downloading external archives has been stumping me for a while now. I've tried several variations to get the files I'm targeting but it appears that `include` does nothing. 

Archive contents:

```
brew/bundle
nix/configuration.nix
nix/flake.lock
nix/flake.nix
nix/home.nix
nix/packages/gopass.nix
nix/packages/chezmoi.nix
LICENSE
README.md
```

My attempt at trying to get the `nix` subfolder into `~/.config/darwin`:

```
[".config/darwin"]
    type = "archive"
    url = "https://github.com/jmgilman/dev-mac/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    include = ["**/nix/*"]
```

The resulting files in `~/.config/darwin`:

```
bundle
configuration.nix
flake.lock
flake.nix
home.nix
packages/gopass.nix
packages/chezmoi.nix
```

Note the existence of `bundle` which shouldn't be there (that's located under `brew/...`). I've tried changing the `include` to all sorts of ridiculous values and it seems to not affect the output at all.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

Other: #2056

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi -R apply
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.15.4, built by nixpkgs
ok        os-arch              darwin/arm64
ok        executable           /etc/profiles/per-user/josh/bin/chezmoi
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found /bin/zsh
ok        edit-command         found /run/current-system/sw/bin/vim
ok        umask                022
ok        git-command          found /run/current-system/sw/bin/git, version 2.36.0
ok        merge-command        found /run/current-system/sw/bin/vimdiff
ok        age-command          age not found in $PATH
ok        gpg-command          found /run/current-system/sw/bin/gpg, version 2.3.4
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /etc/profiles/per-user/josh/bin/bw, version 1.22.1
ok        gopass-command       found /etc/profiles/per-user/josh/bin/gopass, version 1.14.0
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
ok        lastpass-command     found /etc/profiles/per-user/josh/bin/lpass, version 1.3.3
info      pass-command         pass not found in $PATH
ok        vault-command        found /etc/profiles/per-user/josh/bin/vault, version 1.10.2
info      secret-command       not set
```

</details>

## Additional context

After seeing the issue mentioned above, I updated to the latest release just to verify I wasn't missing anything, and I am still running into the same issue.

**Comment by twpayne** [comment]
This might be an unintended consequence of #2057. As a short-term workation, does adding`exclude = ["brew"]` to the external help?

**Comment by jmgilman** [comment]
It doesn't appear to change the output:

```toml
[".config/darwin"]
    type = "archive"
    url = "https://github.com/jmgilman/dev-mac/archive/refs/heads/master.tar.gz"
    stripComponents = 2
    refreshPeriod = "168h"
    exclude = ["brew"] # also tried ["**/brew/*"]
    include = ["**/nix/*"]
```

**Comment by jmgilman** [comment]
I can't really seem to produce anything that's reasonable, which made me think that I was fundamentally misunderstanding something. What's the pattern matching syntax being used? I figured something like this would exclude everything:

```toml
[".config/darwin"]
    type = "archive"
    url = "https://github.com/jmgilman/dev-mac/archive/refs/heads/master.tar.gz"
    stripComponents = 2
    refreshPeriod = "168h"
    exclude = ["**/**"]
```

However, I still get the same result.

**Comment by jmgilman** [comment]
Perhaps I'm confused about what's been released. Cloning and running the current `master` branch locally produces the results I was expecting with the configuration I provided in my original example (and exclude seems to behave correctly as well). It's only in the latest v2.15.4 release that I'm seeing these issues.

**Comment by jmgilman** [comment]
Turns out this was a problem on my end. Nix was caching the chezmoi build and building v2.15.2 instead of v2.15.4, so I was mistakenly behind two patches. I can confirm it works as expected with v2.15.4. Sorry for the confusion!
