### ISSUE TITLE
Broken zsh and bash tab completion for flag values.

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#2066]
## Describe the bug

Not sure if this is a bug or missing feature: There doesn't seem to be any tab completion of arguments to flags. It just defaults to completing file names instead.

## To reproduce

Note: I use zsh, but a quick test show that the same issues exist with bash.

```zsh
$ chezmoi --mode <tab>
# This completes files. Probably should complete either valid modes or just offer
# a description (in zsh) of what is expected.

$ chezmoi --use-builtin-git <tab>
# This also completes files, but according to --help the valid options are bool|auto,
# so presumably the completion should be ( true false auto) (using _arguments
# syntax, which I know chezmoi doesn't use).
```

And so on. This seems to be a problem for all flags taking arguments that I have tested, both global flags and sub-command flags.

## Expected behavior

For flags where file completions don't make sense either show valid options (feasible when it is an enumeration) or just show a message about what to complete (for zsh, not much that can be done for bash when it comes that as far as I know). I know nothing about the other shells (fish, powershell), so I have no idea what should happen for those.

## Output of command with the `--verbose` flag

Not really applicable here, as I'm not running a command, just tab completing.
```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.15.4, built at 2022-05-09T23:08:51Z
ok        latest-version       v2.15.4
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux athena 5.17.6-arch1-1 #1 SMP PREEMPT Tue, 10 May 2022 23:00:39 +0000 x86_64 GNU/Linux
ok        go-version           go1.18.1 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.yaml
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        edit-command         found /usr/bin/code
ok        edit-args            /usr/bin/code -wr
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.36.1
ok        merge-command        found /usr/bin/bcompare
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.35
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.1
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by twpayne** [comment]
Thank you for reporting this :) My initial investigations match what you have observed and also that flag completion works for the fish shell but not bash or zsh. I don't have a solution yet (the completions are generated by spf13/cobra and so in a dependency of chezmoi), but this issue has not been forgotten :)

**Comment by VorpalBlade** [comment]
@twpayne Did you file an upstream bug yet or are you not sure of if it is an upstream or downstream bug still?

**Comment by twpayne** [comment]
I haven't filed an upstream bug yet. I'm pretty sure this is a bug in spf13/cobra.

**Comment by twpayne** [comment]
Correction: I think this is a missing feature in spf13/cobra.

spf13/cobra generates the shell completions and uses flags that implement the [`flag.Value` interface](https://pkg.go.dev/github.com/spf13/pflag#Value). This interface does not include a method for a flag to report what its completions could be. So, for example, there's no way for `--use-builtin-git` (which is an [autoBool in chezmoi](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/autobool.go)) to report that its possible completions are `true`, `false`, `auto`, `yes`, `no`, and so on.

Implementing this will likely need moderate changes to spf13/cobra library. I'll open an issue for this.

**Comment by twpayne** [comment]
And more searching reveals that [`RegisterFlagCompletionFunc`](https://pkg.go.dev/github.com/spf13/cobra#Command.RegisterFlagCompletionFunc) might already be what's required...

**Comment by VorpalBlade** [comment]
I'm confused and curious: How would it work for the fish shell in that case?

**Comment by twpayne** [comment]
It's because I mixed up flag completion and flag value completion.

`--f*` completion works (here we're completing the flag `--f`) but `--flag=v*` doesn't (here we're completing the flag value `v*`.

PR coming up...
