### ISSUE TITLE
Conditional deployment of whole paths

### ISSUE THREAD

**Issue by nivaca** [twpayne/chezmoi#2072]
## Is your feature request related to a problem? Please describe.

I have certain config directories (whole path: a directory with a set of files and subdirectories) which only exist on certain machines. I would like to make Chezmoi deploy them conditionally.

## Describe the solution you'd like

I would like to have a template that, depending on the value of the host variable, deploys or not a directory with its contents. In other words, I would like Chezmoi to copy (or deply) the whole directory conditionally.

## Describe alternatives you've considered

I tried creating file templates for that, but there are simply some files that don't exist, and others that do exist, according to the machine.

**Comment by twpayne** [comment]
This is what `.chezmoiignore` is for, as described in [the user guide](https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#ignore-files-or-a-directory-on-different-machines) and [the reference manual](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiignore/).
