### ISSUE TITLE
chezmoi apply force delete my home directory on Linux

### ISSUE THREAD

**Issue by yoarch** [twpayne/chezmoi#2076]
Hi everyone,
I have been using chezmoi for a few weeks now and I love it. However, I observed a very problematic behavior from chezmoi.

## Describe the bug

The 18/05/2022 with chezmoi up to date on my archlinux machine, I ran `chezmoi apply force` and after more or less one minute without returning the prompt, **all my home directory was deleted**. As a clue, it seems to me that my .aliases template file had an issue at this moment. I don't have more clues as my home session was dead just after and I have now to reinstall my operating system from scratch.

## To reproduce

I can't really say how to reproduce it as I lost all my files under /home involving the possible `.aliases` template that could have caused this action while running `chezmoi apply force`.

## Expected behavior

Applying changes if so but not deleting the /home folder.

## Additional context

I can't really furnish more than these information as my system is not functional anymore. I am mostly sharing this to prevent future similar dramatic behaviors 🥲.

**Comment by twpayne** [comment]
Sorry to hear about your data loss. chezmoi provides a `diff` command and `--dry-run` flag so you can see what changes chezmoi would make to your system without making any changes. Running `chezmoi apply --force` can have the same effect as running `rm -rf` on some directories, and both require careful use.

As there is no information on how this data loss occurred, there's not much else that chezmoi can do here.

**Comment by yoarch** [comment]
Thanks for the reply. I began to use the `--force` parameter as I have some files that change on my fs that I don't want to update on chezmoi (special use case) and I don't want to write skip for each of them when performing `chezmoi apply`.

Would you have any clue of what can lead to a `rm -rf HOME_DIRECTORY` through a `chezmoi apply` ? Then I could investigate and maybe come back with some valuable info.

**Comment by twpayne** [comment]
> Would you have any clue of what can lead to a `rm -rf HOME_DIRECTORY` through a `chezmoi apply` ? Then I could investigate and maybe come back with some valuable info.

The only possibility I can think of is if you use a parent of the home directory as the destination directory and have an `exact_` directory matching your username, i.e. something like:

```console
$ echo $HOME
/home/user
$ ls $(chezmoi source-dir)
exact_user/
$ chezmoi --destination /home --force apply
```

**Comment by yoarch** [comment]
Ok, thanks. I don't think I did have anything like that.
I will try it again with more caution.
