### ISSUE TITLE
Option to automatically add files if modified

### ISSUE THREAD

**Issue by nivaca** [twpayne/chezmoi#2078]
## Is your feature request related to a problem? Please describe.

Whenever I run `chezmoi status` and a file gets modified, I have to manually add it with `chezmoi add` in a separate step. It would be nice if chezmoi could add it automatically (after confirmation).

## Describe the solution you'd like

If `chezmoi status` reports that files have been modified, the user is queried as to whether the files should be added or ignored. 

E.g.:

```sh
$ chezmoi status
  MM .zshaliases. Do you want to add it (Y/n)?
  Y
  .zshaliases added.
```

## Describe alternatives you've considered
Doing it manually, which takes time if the paths are long and the files are many.

**Comment by twpayne** [comment]
Is [`chezmoi re-add`](https://www.chezmoi.io/reference/commands/re-add/) close enough?

**Comment by nivaca** [comment]
Yeah, thanks. But could you add a flag (e.g. -t) to re-add modified templates as well, please?

**Comment by twpayne** [comment]
> Yeah, thanks. But could you add a flag (e.g. -t) to re-add modified templates as well, please?

This is not possible. If you replace the template with the file in the destination directory you will lose the template.

**Comment by nivaca** [comment]
Yeah, you're right. Thanks!
