### ISSUE TITLE
Handling config files that are updated by GUI software with irrelevant things

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#2083]
## Is your feature request related to a problem? Please describe.

Certain programs (a lot of the programs from KDE for example) store both settings (that I want to track) and "useless" data in the same settings file. With "useless" I mean things like:
* Position and size of main window the last time the program was opened
* Recently used files
* etc

This generate a lot of noise and "useless" changes. There is obviously no generic "magic" way for chezmoi to handle this, but I would like a bit of support so that scripts could handle it more easily and in a less clunky way than today.

## Describe the solution you'd like

I see two viable approaches to this. 

### Filters
This is probably the "simpler approach". 

I would like a type of "filter" script that is applied when chezmoi is considering if the file differs from the source state. This script would be given the file in ~ and be able to filter out sections of the files before the diff is generated. It would also be called to apply changes and re-add the file.

I imagine this being a `run_filter_` file with the same name as the target file. It is up to the script to figure out where in the source state it would store the file data. This makes things simpler for chezmoi: rather than having to track both a filter script and a source file state separately, chezmoi just calls the script with a simple API consisting of the target file path in ~ and the required operation (diff, apply, add/re-add). The script would then perform the operation and (for diff) output the two files content in a standard format back to chezmoi to allow displaying the diff.

The actual semantics of the API between chezmoi and the script needs some further consideration to ensure that the behaviour is sane. For example, how should it output two files back to chezmoi (stdout alone might not be the best option, nor do you want the overhead of json escaping, which would be annoying if implementing this using a shell script). Perhaps passing more than one output file descriptor would be the right option.

### Plugins

Another option is a more generic plugin system, that would be a much larger system though. Also I don't know Go, and I would prefer not to have to learn it. ;-)

## Describe alternatives you've considered

Obviously a run_ script could be used to modify the file in ~ with the changes you want, but I usually want to capture all the data in the file except for certain specific ini keys (in the case of KDE). Since the software in question modifies the file I would like to be able to see any changes that have occurred (outside the filtered parts) so I can readd the file. Thus I believe the current run_ scripts are not suitable.

I could of course write a script that I put in ~/bin that handles this separately from chezmoi and simply store the files in an ignored directory in the source directory. This would completely bypass chezmoi which would give me total freedom. However I would loose out of all the benefits it have as well, and would have to reinvent the wheel for many things such as path handling, diff display, applying changes etc. Also it would require running two commands when I want to apply/diff etc. 

The best solution would be to get the programs to put different types of settings/data into different files, but I feel that would be an uphill battle for a project as large as KDE. Most developers would probably not see the use of the feature, and consider it worth the added complexity, even if I did the implementation work. Besides there is always other pieces of software that does the same thing (not just KDE). (At least it isn't dconf where everything is in a binary registry like file.)

## Additional context

For KDE I imagine I would write a generic python script that I'd store in an ignored part of the chezmoi source directory. Then for each config file I would want to handle like this I would have a `run_filter_` shell script that calls this python script with a list of keys to ignore in that specific case, plus a path of where to store the checked in state of this specific config file.

The same approach could be taken for other programs that do similar things but use different file formats (XML, json etc for example).

**Comment by twpayne** [comment]
[`modify_` files](https://www.chezmoi.io/reference/target-types/#modify-file) implements something very close to the filter approach you propose. See also this [user guide entry](https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file).

**Comment by VorpalBlade** [comment]
Firstly: as far I can read (it is really late here, just about to go to bed, so I apologise if I missed something) I'm not sure if `modify_` allows displaying diffs? Other than that it seems like it would work. Readding might need to be handled separately via another (out of band?) script as well, but that is a less common operation and would naturally be a separate operation anyway.

Secondly: https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/ should perhaps provide a link to the modify_ documentation, as that is where I went looking for something that matched my needs. I find in general that since you moved from the old "everything in a few huge pages" into many smaller pages that is is harder to find what I'm looking for, as I generally try to open the page an search for relevant key words.

**Comment by twpayne** [comment]
> Firstly: as far I can read (it is really late here, just about to go to bed, so I apologise if I missed something) I'm not sure if `modify_` allows displaying diffs?

Yes, it does. chezmoi uses the `modify_` script to compute the target state of the file and computes diffs as normal. `modify_` scripts integrate completely with all aspects of chezmoi.

**Comment by twpayne** [comment]
See #847 for the previous discussion on this topic.

**Comment by VorpalBlade** [comment]
Using `modify_` works. I'm closing this and opening a separate bug with respect to the new split documentation being harder to find things in.

**Comment by VorpalBlade** [comment]
@twpayne I wrote some generic scripts for this (both a generic modify_ helper and a helper to add files in that mode). Is there a good location to publish this so other can reuse it?

In addition, if I put them in a git repo and use chezmoiexternal it seems to me that the scripts will not be downloaded in time to be executed on first init? chezmoiexternal seems to be handled at the end.

**Comment by twpayne** [comment]
> @twpayne I wrote some generic scripts for this (both a generic modify_ helper and a helper to add files in that mode). Is there a good location to publish this so other can reuse it?

That's awesome! The best place for this is probably chezmoi's [user guide](https://github.com/twpayne/chezmoi/tree/master/assets/chezmoi.io/docs/user-guide). You could add them to an existing file there, or create a new file. If you create a new file then you'll need to add it to [`mkdocs.yml`](https://github.com/twpayne/chezmoi/blob/master/assets/chezmoi.io/mkdocs.yml). More details on how the website is built are [in the contributing docs](https://www.chezmoi.io/developer/website/).

> In addition, if I put them in a git repo and use chezmoiexternal it seems to me that the scripts will not be downloaded in time to be executed on first init? chezmoiexternal seems to be handled at the end.

For this, see the [application order](https://www.chezmoi.io/reference/application-order/). Externals are updated with other targets, so you're right that they're not downloaded in time to be executed on first init. Could you describe what you need in a new issue? It sounds like chezmoi is missing a feature here.

**Comment by VorpalBlade** [comment]
> Could you describe what you need in a new issue? It sounds like chezmoi is missing a feature here.

No problem, I'll do that as soon as I have time.
