### ISSUE TITLE
Provide the documentation as one big merged page as an option

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#2084]
## Is your feature request related to a problem? Please describe.

A few months ago the documentation was split into many smaller pages instead of just a couple of really large one. While this has advantages (less overwhelming) it is harder to quickly search through quickly looking for relevant key words related to what you want to do.

## Describe the solution you'd like

I suggest providing an alternative version of the documentation where everything is merged into one page for each main heading ("User guide", "Reference" and presumably also "Developer" though that is less relevant for me). This could hopefully be done automatically by just putting a heading on top and then concatenating all the pages.

Worth noting is that I have seen at least a few other projects do this already, such as [GNU binutils](https://sourceware.org/binutils/docs/). They probably use texinfo, but hopefully this won't be too difficult with whatever system you use either.

## Describe alternatives you've considered

Google helps a bit, but I find it less easy and less reliable than just Ctrl+F on the page.

Going through a lot of different pages manually takes a lot of time, and I'm not patient enough to do that generally.

## Additional context

Had this existed I would likely not have filed issue #2083 because I would have found `modify_` while looking around.

**Comment by twpayne** [comment]
How the website is built is described in [the contributing guide](https://www.chezmoi.io/developer/website/). Please do submit a PR to implement what you want.

**Comment by twpayne** [comment]
The website is built with [MkDocs](https://www.mkdocs.org/). As far as I can tell, there's no way to generate the website as a single page. Please do re-open this if you find a way.
