### ISSUE TITLE
Run scripts after externals have been fetched. Or fetch externals before running scripts

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#2089]
## Is your feature request related to a problem? Please describe.

I wrote a `modify_` script helper to deal with annoying ini files. It allows ignoring specific keys, applying arbitrary transforms on certain keys etc. This is all aimed at dealing with KDE (and a few other programs) configs where settings are mixed with state (recently used files, position of main window, ...).

This program takes the form of a python script that lives in `<source dir>/.utils/`. Then I use `modify_` shell scripts to call this python script with the proper flags to specify what to ignore for *that* specific ini file.

This works great. And now I want to make this public and distribute it. The obvious solution is to create a git repo that contains this script (as well as the helper zsh script to add a new template `modify_` script). But that runs into some issues. Specifically (as I understand the [application order](https://www.chezmoi.io/reference/application-order/), externals are only fetched *after* `modify_` scripts have been run.  Or at least are handled intermingled with them based on alphabetic order. This creates a bad situation on initial checkout and setup (i.e. `chezmoi init --git somerepo`). Or perhaps the documentation just needs to be more clear on when externals are processed.

## Describe the solution you'd like

I want a way to reliably call a script in an external repo from a `modify_` script. I don't know what form that should take. `modify_after_` perhaps? The [application order](https://www.chezmoi.io/reference/application-order/) page only mentions `run_after_`, not `modify_after_`. And testing indicates that "after_" is treated as part of the file name in that case. That raises the possibility of adding this being a breaking change by the way, in case someone expects to modify a file `after_dark` or such.

Or perhaps you have a better suggestion for how to handle this?

## Describe alternatives you've considered

I could tell people to copy the script into their source directory. But that makes updates much harder to handle. Or I could publish it as a package on pypi. But that is again more effort to handle on new installs.

## Additional context

My goal is that this should be transparent to `chezmoi init` once "installed" into the chezmoi source directory. All options like "install from pypi" etc means having to run extra commands before you can run `chezmoi init` on a new system and adds extra dependencies (I intentionally wrote the script to only use things from the python standard library by default).

**Comment by twpayne** [comment]
Thanks for opening the issue.

chezmoi's externals are for including external files in your dotfiles in a declarative way.  As you've discovered, they're not suitable for pulling in dependencies needed to generate the target states of the dotfiles themselves.

chezmoi's application order is already sufficiently complicated, and I do not want to make it even more complicated without a very, very strong reason.

A possible solutions here would be to use a git submodule for the common script. This will automatically be cloned when you run `chezmoi init`.

An alternative would be to add a "self-update" option to your script which would replace the script with the most recent version.

However, having users copy the script into their dotfiles repo is a good solution in my opinion. Yes, updates require the user to download the new version, but this is a good thing. Users only need to update if the script is not working for them or if they need a feature only available in a newer version. Updates do not need to be automatic, and indeed automatic updates are huge security risks.

**Comment by VorpalBlade** [comment]
Hm that are some good points. For my personal use I do not want to maintain two separate copies (thus I do not want to copy, and I want auto update, as I *do* trust myself funnily enough).

I did not think of submodules, as git normally doesn't do anything with them unless you pass extra flags. If chezmoi does pass `--recursive` to clone and pull that would work. It would also alleviate any auto update risks, as once added to .gitmodules it would point to a specific commit and require user interaction to update to a new target revision.

**Comment by twpayne** [comment]
Sounds good. chezmoi does pass `--recurse-submodules` to `git clone` when you run `chezmoi init` ([link](https://github.com/twpayne/chezmoi/blob/5ec1ad802b2c3331452740adcdb3a87d3a8a1bf0/pkg/cmd/initcmd.go#L173)), and it's even supported when [using the builtin git](https://github.com/twpayne/chezmoi/blob/5ec1ad802b2c3331452740adcdb3a87d3a8a1bf0/pkg/cmd/initcmd.go#L241).

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed. And nice work on [chezmoi_modify_manager](https://github.com/VorpalBlade/chezmoi_modify_manager)!
