### ISSUE TITLE
Add passhole password manager as an alternative for KeePass users

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#2099]
### Discussed in https://github.com/twpayne/chezmoi/discussions/2098

<div type='discussions-op-text'>

<sup>Originally posted by **JackTheMico** May 30, 2022</sup>
Can we add [passhole](https://github.com/Evidlo/passhole) as an alternative integration for KeePass users?
I'm willing to implement this feature.</div>

**Comment by twpayne** [comment]
@JackTheMico has offered to implement this. https://github.com/twpayne/chezmoi/pull/2062/files gives an idea of what is required.

**Comment by JackTheMico** [comment]
@twpayne Thank you, I'm working on it. I want to know is there any way that I can use to test the functions I wrote for passhole ?

**Comment by twpayne** [comment]
The easiest way to test is to build on top of the existing [`testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript)-based tests in [`pkg/cmd/testdata/scripts`](https://github.com/twpayne/chezmoi/tree/master/pkg/cmd/testdata/scripts). An example to follow is [`keepassxc.txt`](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/testdata/scripts/keepassxc.txt).

**Comment by twpayne** [comment]
Fixed with #2317.
