### ISSUE TITLE
NixOS package

### ISSUE THREAD

**Issue by jhillyerd** [twpayne/chezmoi#210]
Tracking issue for package in Nix/NixOS.

nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/55368

**Comment by twpayne** [comment]
Fantastic, thanks for this :)

**Comment by jhillyerd** [comment]
Merged.  Hopefully this means it makes it into the March release.

**Comment by twpayne** [comment]
That's brilliant, many thanks @jhillyerd :)
