### ISSUE TITLE
parseOSRelease breaks on RedHat

### ISSUE THREAD

**Issue by johnweldon** [twpayne/chezmoi#212]
`parseOSRelease` in `cmd/os_release.go` doesn't know how to handle empty lines in `/etc/os-release`

The "[spec](https://www.freedesktop.org/software/systemd/man/os-release.html)" says that:
> Lines beginning with "#" shall be ignored as comments. Blank lines are permitted and ignored.

On RedHat in particular, the `/etc/os-release` file isn't installed by default, and when it is with the `redhat-release-server` package it has empty lines in it that cause chezmoi to issue the error: `cannot parse ""`

**Comment by twpayne** [comment]
Fixed thanks to @johnweldon in #213.
