### ISSUE TITLE
Files in .chezmoitemplates do not see automatic variables '.chezmoi.*'

### ISSUE THREAD

**Issue by l-c-g** [twpayne/chezmoi#2125]
## Describe the bug

To have mostly the same VS Code config on Windows and Linux, I keep my settings in a template file `.chezmoitemplates\VSCode_settings.json`. I include this template file in the two OS-specific locations `.config/Code/User/settings.json.tmpl` and `AppData\Roaming\Code\User\settings.json.tmpl`: `{{- template "VSCode_settings.json" -}}`.

Now I need a setting only on Linux, so I added a test for the current OS in `VSCode_settings.json` in .chezmoitemplates:
```
{{- if eq .chezmoi.os "linux" }}
  "window.zoomLevel": 0.5,
{{ end }}
```

When running `chezmoi diff`, it complains about not having an entry for key "chezmoi":
```console
~ > chezmoi diff
chezmoi: template: VSCode_settings.json:75:18: executing "VSCode_settings.json" at <.chezmoi.os>: nil data; no entry for key "chezmoi"
```

The command `chezmoi data` shows the variable correctly populated:
```console
~ > chezmoi data
{
  "chezmoi": {
    "arch": "amd64",
    ...
```
and I use a similar construct in my `.chezmoiignore`, where it works fine:
```
{{ if ne .chezmoi.os "linux" }}
.zshenv
{{ end }}
```

## To reproduce

1. Create a file `.chezmoitemplates\chezmoi_variable_test`:
```
Some text that is always there
{{- if eq .chezmoi.os "linux" }}
and some text that is specific to Linux
{{- end }}
```
... and a file `chezmoi_variable_bug.tmpl` that includes it:
```
{{- template "chezmoi_variable_test" -}}
```
2. Run `chezmoi diff` and observe the error:
```console
~ > chezmoi diff
chezmoi: template: chezmoi_variable_test:2:18: executing "chezmoi_variable_test" at <.chezmoi.os>: nil data; no entry for key "chezmoi"
```
3. Copy the contents of `.chezmoitemplates\chezmoi_variable_test` to `chezmoi_variable_bug.tmpl` directly (I copied it to ensure there was no typo in `.chezmoitemplates\chezmoi_variable_test)`:
```
Some text that is always there
{{- if eq .chezmoi.os "linux" }}
and some text that is specific to Linux
{{- end }}
```
4. Run `chezmoi diff` again and observe the output:
```console
~ > chezmoi diff
diff --git a/chezmoi_variable_bug b/chezmoi_variable_bug
new file mode 100666
index 0000000000000000000000000000000000000000..7a1a801982d6ba6d8dd40da88a78f7b56047a453
--- /dev/null
+++ b/chezmoi_variable_bug
@@ -0,0 +1 @@
+Some text that is always there
```

## Expected behavior

Depending on the OS, chezmoi writes the file with or without the conditional part and does not error out.

## Output of command with the `--verbose` flag

```console
~ > chezmoi --verbose diff
chezmoi: template: chezmoi_variable_test:2:18: executing "chezmoi_variable_test" at <.chezmoi.os>: nil data; no entry for key "chezmoi"
```

## Output of `chezmoi doctor`

<details>

```console
~ > chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.17.1, commit 565cbbe117746aa6bfec5f2cee20ae4cbbb5e645, built at 2022-05-30T10:24:34Z, built by goreleaser
ok        latest-version       v2.17.1
ok        os-arch              windows/amd64
ok        systeminfo            ()
ok        go-version           go1.18.2 (gc)
ok        executable           C:/bin/chezmoi.exe
ok        config-file          ~/.config/chezmoi/chezmoi.json
ok        source-dir           ~/.local/share/chezmoi is a directory
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell-command        found C:/Windows/system32/cmd.exe
ok        shell-args           'C:\\Windows\\system32\\cmd.exe'
ok        cd-command           found C:/Windows/system32/cmd.exe
ok        cd-args              'C:\\Windows\\system32\\cmd.exe'
ok        edit-command         found C:/Windows/system32/notepad.exe
ok        edit-args            'C:\\Windows\\system32\\notepad.exe'
info      diff-command         not set
ok        git-command          found C:/Program Files/Git/cmd/git.exe, version 2.36.1
warning   merge-command        nvim not found in $PATH
info      age-command          age not found in $PATH
ok        gpg-command          found C:/Program Files (x86)/gnupg/bin/gpg.exe, version 2.3.6
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

The behavior is the same on Linux and Windows.

**Comment by twpayne** [comment]
As [described in the templating guide](https://www.chezmoi.io/user-guide/templating/#template-variables) you must pass the template data in explicitly, i.e. 

> ... and a file `chezmoi_variable_bug.tmpl` that includes it:
> 
> ```
> {{- template "chezmoi_variable_test" -}}
> ```

should be

```
{{- template "chezmoi_variable_test" . -}}
```

Note the extra `.`.

**Comment by twpayne** [comment]
Hopefully this resolved the issue. Please re-open if needed.

**Comment by l-c-g** [comment]
Thanks for pointing me at the guide. I had only looked at the reference and while it is also explained there, I did not fully understand that part without the example in the guide.

Frankly, I still find it strange that .tmpl files behave differently than files in .chezmoitemplates. I guess the rationale is that .chezmoitemplates can be parameterized and need to have parameters passed explicitly.
