### ISSUE TITLE
Unable to install on fresh Ubuntu 22.04 

### ISSUE THREAD

**Issue by shadycuz** [twpayne/chezmoi#2151]
## Describe the bug

Unable to run the install command from the [documentation](https://www.chezmoi.io/install/) on a fresh Ubuntu 22.04 machine.

## To reproduce

```sh
shadycuz@La-Laptop:~$ sh -c "$(curl -fsLS chezmoi.io/get)"
info found version 2.17.1 for latest/linux/amd64
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

## Expected behavior

I'm not sure, I'm new to `chezmoi` but I'm guessing the binary was supposed to be installed in `./bin`? Where ever that is. Either the home directory or whever the script is run from? But I didnt find it in either.

```
shadycuz@La-Laptop:~$ ls -la ./bin
ls: cannot access './bin': No such file or directory
```

## Output of command with the `--verbose` flag

N/A

## Output of `chezmoi doctor`

N/A

## Additional context

This is on WSL

**Comment by shadycuz** [comment]
hmmm... great https://stackoverflow.com/a/61519831

**Comment by shadycuz** [comment]
So the issue is that `wsl1` installs a 32-bit version of Ubuntu while `wsl2` installs a 64bit version. There is an upgrade command to upgrade a single distribution from version 1 to 2 but since mine was brand new I just removed it and reinstalled it. 

```ps
wsl --unregister Ubuntu-22.04
wsl --set-default-version 2
# Then I installed from the windows app store again
```

I will let the maintainers close this issue in case they have any action items for it.

**Comment by twpayne** [comment]
Thank you very much for digging further into this issue and happy to hear that chezmoi's install works :)
