### ISSUE TITLE
Spurious error messages: "chezmoi: The parameter is incorrect."

### ISSUE THREAD

**Issue by pecheny** [twpayne/chezmoi#2152]
I've been got this error on calling chezmoi with any arguments except '--help' (Win10). Spended a day and found the source:
https://github.com/twpayne/chezmoi/blob/9605e40fbdc412f9a634ca0bde8f40543d65aaf0/pkg/cmd/util_windows.go#L46

The issue disappeared after rewriting  registry values under ```HKEY_CURRENT_USER\Console``` from the fresh user. It would be great if chezmoi will provide some information about what it tries to do at least in cases which can fail like this.

Unfortunately I can't reproduce it now to check what ```chezmoi doctor``` would say, but ```--verbose``` / ```--debug``` flags had no effect.

**Comment by twpayne** [comment]
Thank you for reporting this, thank you for spending the time investigating, and so sorry that digging to the bottom of the problem cost you a day. #2153 adds more context to errors returned from Windows API calls, which will help people in the future when chezmoi next fails like this.

**Comment by pecheny** [comment]
Don't worry, on the other hand it was an occasion to meet golang. And thank you for quick response and fix.
