### ISSUE TITLE
Adding all existing file changes to chezmoi

### ISSUE THREAD

**Issue by Da-Viper** [twpayne/chezmoi#2163]
## Is your feature request related to a problem? Please describe.

Take for example you have not added your changes to your chezmoi working copy in a long time 
you now want to do so there is no command to update the configs from your home directory to the working copy before commiting

if it was from the working copy to the local repo you can just do `git add . ` and `git commit ` but from the  home directory to the working copy i have to add them manually. And some of them i do not remember where they are stored. Then the convienece is out the window and it becomes more like a chore. 

## Describe the solution you'd like

a command similar to `apply` at but in the reverse order 

something like `chezmoi add --all ` or `chezmoi add_all` something to that essence

**Comment by twpayne** [comment]
[`re-add`](https://www.chezmoi.io/reference/commands/re-add/)?

**Comment by Da-Viper** [comment]
Yeah you are right will close the issue
