### ISSUE TITLE
Questions about chezmoi cd 

### ISSUE THREAD

**Issue by pecheny** [twpayne/chezmoi#2164]
I have several questions about ```chezmoi cd```.

1. What the point to start new shell instance? Shells seems to me tend to store shared command history. In order to return to initial location one can use ```pushd/popd``` instead of ```cd```. And new shell also brokes experience if launched from filemanager's command prompt since you can't reach panels. (I'm using Far manager but suggest that with mc one've got the same).

2. I'm under windows and have following issues. The doc suggests using ```cd $(chezmoi source-path)``` for changing location in the current shell, but there is no convenient equivalent for windows cmd. I can't find the way to pass output of any command to ```cd```. So i can guess the only way to use shortcut/alias under cmd that is to declare env var. It also seems to me against chezmoi ideology (only my way of understanding it) since chezmoi tend to provide all customization in os/env independent manner.

3. I've tried to override default behavior of ```cd.command``` with plain ```cd``` but it doesn't work for me since chezmoi looks for executable rather than shell command:
```chezmoi: exec: "cd": executable file not found in %PATH%```

4. With alternative shells under windows there are also several issues.

-  git-bash works fine
-  bash / zsh from cygwin launched under mintty fail with
 ```chezmoi: exec: "/bin/zsh": file does not exis```
-  under bash / zhs / powershell launched as plain exe ```chezmoi cd``` launches plain cmd instead shell from within it was launched

thanks in advance

**Comment by twpayne** [comment]
1. See [this FAQ entry](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-cd-spawn-a-shell-instead-of-just-changing-directory).
2. I don't use Windows and don't know the answer. This sounds like a Windows shell question, not related to chezmoi.
3. This is because `cd` is a shell builtin command, not an executable. Indeed, `cd` can never be an executable for the reasons described in the FAQ entry.
4. For bash / zsh in cygwin, it looks like you need to set the full path to the executable in `cd.command`. For the third bullet point, see the the [documentation on `chezmoi cd`](https://www.chezmoi.io/reference/commands/cd/).

**Comment by pecheny** [comment]
Thanks! Sorry for bothering you with question presented in FAQ, may i suggest to reference this faq entry from ```chezmoi cd``` help page? The only thing i can complain now is confusion with name of the command, since ```cd``` is acronym for "change directory" and the command does something else.

A bit of investigation led me to workaround for cmd. I've put ```chez-cd.cmd``` in the directory presented in %path%  and containing:
```For /f %%i in ('chezmoi source-path') do doskey chez-cd=cd "%%i"```
When i call ```chez-cd``` first time in the current cmd session it overrides ```chez-cd``` with alias to ```"cd %OUTPUT_OF_CHEZMOI_SOURCEPATH%"``` next time i call it in this session it would change dir as supposed. This workaround may be a bit ugly but maybe some windows user can find it useful.

**Comment by bradenhilton** [comment]
@pecheny Does

```cmd
# chezmoi-cd.cmd
@echo off
FOR /F "delims=" %%c IN ('chezmoi source-path') DO cd "%%c"
```

not achieve what you want?

```console
C:\Users\user>chezmoi-cd

C:\Users\user\.local\share\chezmoi>
```

`cd $(chezmoi source-path)` also works in PowerShell if you'd rather use it instead.

**Comment by pecheny** [comment]
Thank you! Unfortunately, it doesn't. It seems to be forbidden to change directory for the parent process same way as for chezmoi itself. So after cmd execution the current shell stay in old state. 
My option works since it doesn't use batch script to change directory, the batch is called once. It defines macro-substitution for shell which works in the parent process. Thus next time i call ```chez-cd``` the shell doesn't call batch but substituted with ```cd``` command.
I don't use PowerShell. I would prefer zsh, but stuck with cmd because of far manager. I do a lot of stuff within and it has built-in cmd powered up with completion popups, history and so on.

**Comment by bradenhilton** [comment]
@pecheny Ah, I see what you mean now.

You might still want to use `"delims="` in case you ever have a path with spaces. While testing I changed my `source-path` from `C:\Users\user\.local\share\chezmoi\home` to `C:\Users\user\.local\share\chezmoi\home & home` and without `"delims="` it `cd`'d into `C:\Users\user\.local\share\chezmoi\home`.

**Comment by pecheny** [comment]
@bradenhilton  You are right. I tend to avoid spaces in paths so didn't notice the cmd would fail on one. I have updated the cmd so it looks like:
```For /f "delims=" %%i in ('chezmoi source-path') do doskey chez-cd=cd "%%i"```
Thanks again.
