### ISSUE TITLE
adding an external, and then doing chezmoi forget "that external", asks to remove all chezmoi

### ISSUE THREAD

**Issue by alexjp** [twpayne/chezmoi#2177]
## Describe the bug

Adding an external, for example, a github repo into "test_external" in chezmoi.
Then, doing chezmoi forget test_external, chezmoi asks to remove all of chezmoi data.

I tested answering yes, and it did removed everything (no worries though, i did a backup first)

## To reproduce

add an external to .chezmoiexternal.toml.
either apply that external or not, its indiferent.
do a chezmoi forget "that external"

## Expected behavior

chezmoi to either remove the external, from the .chezmoiexternal.toml or simply say that it can't forget it because its a configured external in the file .chezmoiexternal.toml

## Output of command with the `--verbose` flag
(edit: forgot to mention, but I aliased chezmoi to cm, so cm command below is chezmoi)
(using oh-my-posh, nothing against it, nor do I want to forget it :) just an example)
```console
cm --verbose forget oh-my-posh
Remove /mnt/data/alex/chezmoi [yes,no,all,quit]? 
```

## Output of `chezmoi doctor`
in this case, yes, I have the .config/chezmoi.toml added, but I just read the issue where it should not be added, so I will remove it :)
<details>

```console
chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.18.1, built at 2022-06-23T21:17:54Z
ok        latest-version       v2.18.1
ok        os-arch              linux/amd64 (Garuda Linux)
ok        uname                Linux stormtrooper 5.18.6-zen1-1.1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 23 Jun 2022 15:04:31 +0000 x86_64 GNU/Linux
ok        go-version           go1.18.3 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-06-13T04:51:52+01:00
ok        source-dir           /mnt/data/alex/chezmoi is a git working tree (clean)
warning   suspicious-entries   /mnt/data/alex/chezmoi/dot_config/chezmoi/chezmoi.toml
ok        working-tree         /mnt/data/alex/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
ok        cd-command           found /usr/bin/fish
ok        cd-args              /usr/bin/fish
ok        edit-command         found /usr/bin/nvim
ok        edit-args            nvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.36.1
ok        merge-command        found /usr/bin/nvim
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.35
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.1
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set

```

</details>

## Additional context

Thanks for chezmoi, very nice and cool tool !!!

**Comment by bradenhilton** [comment]
I think I can reproduce:

```console
~
❯ Get-Content -Path '.local\share\chezmoi\home\.chezmoiexternal.toml'
[".vim/pack/alker0/chezmoi.vim"]
    type = "git-repo"
    url = "https://github.com/alker0/chezmoi.vim.git"
    refreshPeriod = "168h"

❯ chezmoi apply
Cloning into '~/.vim/pack/alker0/chezmoi.vim'...
remote: Enumerating objects: 297, done.
remote: Counting objects: 100% (1/1), done.
Receiving objects:  75% (223/297)ed 0 (delta 0), pack-reused 296
Receiving objects: 100% (297/297), 61.64 KiB | 3.63 MiB/s, done.
Resolving deltas: 100% (126/126), done.

❯ chezmoi forget '.vim\pack\alker0\chezmoi.vim'
Remove ~/.local/share/chezmoi/home [yes,no,all,quit]?
```

**Comment by bradenhilton** [comment]
I think I've wrapped my head around setting up debugging Go in VS Code...

https://github.com/twpayne/chezmoi/blob/f72bac8f8110ba489fd15d6ee6406950f54705d2/pkg/cmd/forgetcmd.go#L38-L41

`sourceAbsPath` is set to the source path root (default `~/.local/share/chezmoi`) when attempting to forget an external.

---

> ## Expected behavior
>
> chezmoi to either remove the external, from the .chezmoiexternal.toml or simply say that it can't forget it because its a configured external in the file .chezmoiexternal.toml

Skipping might be simpler, external files/directories can be named using templates so I'm guessing it would be difficult to know exactly what to remove.

**Comment by alexjp** [comment]
> Skipping might be simpler, external files/directories can be named using templates so I'm guessing it would be difficult to know exactly what to remove.

Definitely. Skipping wouldn't be any issue, at least in my opinion.

But its current behavior of "do you want to delete all your data" is a little dangerous, i think, although it seems nobody (thankfully) has been in that situation so far :)

**Comment by twpayne** [comment]
Thanks for reporting this. With #2179, chezmoi prints a warning and skips targets that are defined via externals.
