### ISSUE TITLE
Allow fully encrypted files

### ISSUE THREAD

**Issue by jgoguen** [twpayne/chezmoi#218]
I have some files I'd like to manage, but the data format doesn't lend itself well to the current way of puling in from `chezmoi.toml` or from a secret manager. An example is my SSH config, setting it up to work with `op` would be a lot of secrets or a lot of work to avoid leaking data; much simpler to just encrypt the file and move on. Another example is I have a config file which is a JSON struct where each key is a secret; rather than set up a secret per key, it would be easier to just encrypt the whole file and let `chezmoi` decrypt it.

I see this working with a new `--encrypt` flag to `chezmoi add` and an `encrypt` config file section. Something like:

```
[encrypt]
  # This could be any secret provider: onepassword, keychain, lastpass, etc.
  provider = "onepassword"
  # This is the lookup key for the encryption key. ( onepassword "uuid" ).details.password is expected to be the encryption key
  key = "sjalskakejwkwmwknfe"
```

Then when I want to add an encrypted file (example: `~/.secret_file` with permissions `0600`): 

```
% chezmoi add --encrypt .secret_file
# Creates ~/.local/share/chezmoi/private_encrypted_dot_secret_file
```

This will look up the encryption key, encrypt the file, and add that to the source directory. Then when `chezmoi apply` encounters a file with `encrypted_`, it looks up the encryption key and uses it to decrypt the file before writing it out to disk.

A `chezmoi encrypt` command would also be needed to allow updating an encrypted file in the source directory.

**Comment by twpayne** [comment]
This is a great idea!

For the encryption itself, I would be tempted to use [`gpg`](https://www.gnupg.org/) and in the config file specify the key ID to be used for encryption. For decryption, I think `gpg` will find the key itself. Using `gpg` means that `chezmoi` doesn't have to roll its own crypto.

There's a small bootstrapping problem here: you have to get your private key onto the machine where you run `chezmoi`, but hopefully this is not too high a price to pay.

What do you think? Is `gpg` sufficient for your needs?

**Comment by jgoguen** [comment]
I see no reason why not. There's a minor bootstrap problem, but I already store some of the stuff I need to bootstrap a new environment in 1Password, I see no reason why I couldn't also put an encrypted private key in there.

**Comment by twpayne** [comment]
OK, great! I'll try implementing this this evening.
