### ISSUE TITLE
Allow merging config config files

### ISSUE THREAD

**Issue by jgoguen** [twpayne/chezmoi#219]
I have config files which can mutate, but I want to merge in some data to ensure it's present. There's two states I'd like considered: "merge and overwrite" and "merge unless present". For bonus points, allow both JSON and INI formats (but I only need JSON for my use case).

## Merge and Overwrite

In this case, the data `chezmoi` has in the source state takes precedence over what's on disk (like any other file currently). If I have a file in the target directory:

```
{
  "foo": "bar",
  "sky": "night"
}
```

And in `chezmoi` the file is:

```
{
  "foo": "baz",
  "deep": "thought"
}
```

The resulting file `chezmoi` actually writes out to disk would be:

```
{
  "foo": "baz",
  "sky": "night",
  "deep": "thought"
}
```

In this case, I have a config file in which I want to enforce certain keys, but others are free to be modified (or not present).

## Merge unless present

In this case, the data on disk actually takes precendence over the source state. Reusing the files from above, if I have a file in the target directory:

```
{
  "foo": "bar",
  "sky": "night"
}
```

And in `chezmoi` the file is:

```
{
  "foo": "baz",
  "sky": "blue",
  "deep": "thought"
}
```

The resulting file `chezmoi` actually writes out to disk would be:

```
{
  "foo": "bar",
  "sky": "night",
  "deep": "thought"
}
```

For this, I have a config file which contains tokens which peroidically gets modified. I want to make sure a good configuration is present, but if the tokens have been modified I'd rather keep them in place. Most of these would periodically get backed up to a secret store (and included in `chezmoi` using a template function like `onepassword`) but some could stay in the file. Or, with #218 implemented, the file could be periodically encrypted and copied back in to the source directory.

**Comment by twpayne** [comment]
This is an interesting idea. At the moment, `chezmoi` is ignorant of file contents - it just blindly replaces the contents. This would require `chezmoi` to understand the structure of the target file.

The desired effect might be better achieved using another method, for example using scripts (e.g. #206) to generate the source file.

I'd like to collect requirements on this idea before jumping in with an implementation. Other filetypes might have similar requirements, for example you might want to ensure that a particular line is present or absent in a text config file.

**Comment by jgoguen** [comment]
Oh I missed the scripts task. That would actually work far better. I'd also like to be able to handle INI files, and if it can run arbitrary scripts only on first run and others every time I could replace a bad Chef setup with a handful of scripts and a systemd timer.

**Comment by jgoguen** [comment]
#287 handles this nicely
