### ISSUE TITLE
[documentation] Clarify the names used for different types in arguments to apply

### ISSUE THREAD

**Issue by ptxmac** [twpayne/chezmoi#2191]
## Missing description of flag

The documentation for [apply](https://www.chezmoi.io/reference/commands/apply/#-i-include-types) mentions `--include` which can be used to enable specific target types, but the correct names to use for each type is not mentioned.

From looking at the code, I believe it's simply a matter of adding this list: https://github.com/twpayne/chezmoi/blob/master/pkg/chezmoi/entrytypeset.go#L47 

## Missing flags

`chezmoi apply -h` returns more flags than is described on the homepage:
```
Usage:
  chezmoi apply [target]... [flags]

Examples:
  $ chezmoi apply
  $ chezmoi apply --dry-run --verbose
  $ chezmoi apply ~/.bashrc

Flags:
  -x, --exclude types   Exclude entry types (default none)
  -h, --help            help for apply
  -i, --include types   Include entry types (default all)
      --init            Recreate config file from template
  -r, --recursive       Recurse into subdirectories (default true)
```

These should also be described

**Comment by twpayne** [comment]
These are [described in the reference manual](https://www.chezmoi.io/reference/command-line-flags/common/#-i-include-types).
