### ISSUE TITLE
Docs: muting gpg output that is sent to stderr

### ISSUE THREAD

**Issue by promisedlandt** [twpayne/chezmoi#2192]
## Is your feature request related to a problem? Please describe.

Running chezmoi with gpg passphrase encryption in a cronjob generates one mail per run even if no error occurred.
This is because gpg sends some info messages to stderr instead of stdout. I don't know why gpg does this.

Example:

```sh
gpg: AES256.CFB encrypted data
gpg: encrypted with 1 passphrase
```

## Describe the solution you'd like

gpg has a `--quiet` flag that suppresses the mentioned info output.
After I added it to gpg.args in ~/.config/chezmoi/chezmoi.toml I don't get any info output anymore.
Errors are still shown.

Since it took me quite a while to find the cause and the solution here, I suggest to add `--quiet` on the [documentation page](https://www.chezmoi.io/user-guide/encryption/gpg/#encrypting-files-with-a-passphrase) to spare other users this effort.
I had a look at the gh-pages branch but I did not figure out how you generated the html, so I did not open a merge request.

## Describe alternatives you've considered

The output can also be muted by running `chezmoi apply ... > /dev/null 2>&1`, but then no output is generated even if there are actual errors.

## Additional context

I did not test this with symmetric / asymmetric encryption. If the gpg.args option works for them too, then it might be a good idea to add a new heading, e.g. "Muting gpg output", instead of just adding the flag to the passphrase documentation.

**Comment by twpayne** [comment]
Yes, adding `--quiet` to `gpg.args` is the correct way to fix this.

The website generation is [documented in the contributing guide](https://www.chezmoi.io/developer/website/).

**Comment by bradenhilton** [comment]
@promisedlandt The file to edit is [`assets/chezmoi.io/docs/user-guide/encryption/gpg.md`](https://github.com/twpayne/chezmoi/blob/master/assets/chezmoi.io/docs/user-guide/encryption/gpg.md).

**Comment by promisedlandt** [comment]
Thank you both. I feel a bit silly for not noticing the website section in the contributing guide :man_facepalming:
