### ISSUE TITLE
Chezmoi Diff reversed output

### ISSUE THREAD

**Issue by SreenivasVRao** [twpayne/chezmoi#2195]
## What exactly are you trying to do?

`chezmoi add ~/.bashrc`
`chezmoi diff`

## What have you tried so far?

`chezmoi add ~/.bashrc`
`chezmoi diff` and `chezmoi diff --reverse`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose diff
diff --git a/.bashrc b/.bashrc
index 448fc7b4adc06d11aecb62944f0bfdb4de55b015..247b84a6e61849e8bb0207d4efe7fc55f07db5e2 100664
--- a/.bashrc
+++ b/.bashrc
@@ -117,5 +117,3 @@   fi
 fi
 
 . "$HOME/.cargo/env"
-
-export EDITOR="emacs -nw"

```

## Output of `chezmoi doctor`

```console
RESULT    CHECK                MESSAGE
ok        version              v2.18.1, commit 89f8b0ea0aa4e3add6e1bd2706d3db22373968c8, built at 2022-06-23T17:33:13Z, built by goreleaser
ok        latest-version       v2.18.1
ok        os-arch              linux/amd64 (Ubuntu 22.04 LTS (Jammy Jellyfish))
ok        uname                Linux arceus 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.18.3 (gc)
ok        executable           /snap/chezmoi/472/chezmoi
ok        upgrade-method       snap-refresh
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
ok        cd-command           found /bin/bash
ok        cd-args              /bin/bash
ok        edit-command         found /usr/bin/vi
ok        edit-args            /usr/bin/vi
info      diff-command         not set
ok        umask                002
ok        git-command          found /usr/bin/git, version 2.34.1
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

```

## Additional context
The diff is reversed. I added `export EDITOR="emacs -nw"` to my `~/.bashrc` - but chezmoi diff shows that the line was removed. So it doesn't get added to my dotfiles with `git commit -m`

**Comment by twpayne** [comment]
I'm sorry, I don't understand what you are trying to do:

> `chezmoi add ~/.bashrc`
> `chezmoi diff`

What output do you get and what output do you expect?

After running `chezmoi add ~/.bashrc`, chezmoi will update `dot_bashrc` in your source directory, and the output of `chezmoi diff` should be empty (at least as far as ~/.bashrc` is concerned). Is this the case?

**Comment by SreenivasVRao** [comment]
yes - I committed `dot_bashrc` initially. 

when I add a line to the file, `chezmoi diff` shows that I removed that line from the file instead. note the `-export EDITOR="emacs -nw"` instead of `+export EDITOR="emacs -nw"` , i.e., it seems like the diff sources are swapped for some reason.


```
$ chezmoi --verbose diff
diff --git a/.bashrc b/.bashrc
index 448fc7b4adc06d11aecb62944f0bfdb4de55b015..247b84a6e61849e8bb0207d4efe7fc55f07db5e2 100664
--- a/.bashrc
+++ b/.bashrc
@@ -117,5 +117,3 @@   fi
 fi
 
 . "$HOME/.cargo/env"
-
-export EDITOR="emacs -nw"
```


`chezmoi --verbose apply` shows the following

```
sreenivas@arceus:~$ chezmoi --verbose apply
.bashrc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? diff
diff --git a/.bashrc b/.bashrc
index 448fc7b4adc06d11aecb62944f0bfdb4de55b015..247b84a6e61849e8bb0207d4efe7fc55f07db5e2 100664
--- a/.bashrc
+++ b/.bashrc
@@ -117,5 +117,3 @@   fi
 fi
 
 . "$HOME/.cargo/env"
-
-export EDITOR="emacs -nw"
.bashrc has changed since chezmoi last wrote it [diff,overwrite,all-overwrite,skip,quit]? quit
chezmoi: exit status 0
```

If I select `overwrite`, the `export EDITOR="emacs -nw"` line gets removed from my `~/.bashrc` as well.

**Comment by bradenhilton** [comment]
@SreenivasVRao Did you add `export EDITOR="emacs -nw"` to `.bashrc`? Or did you add it to `dot_bashrc`?

If you added it to `.bashrc` and want to overwrite `dot_bashrc`, you need to run `chezmoi re-add` or `chezmoi add .bashrc` again.

When you run `chezmoi apply`, the contents of `.bashrc` are computed from `dot_bashrc`, so if the line is missing from `dot_bashrc`, the diff will show that the line will be removed.

Personally, I always edit the source targets (`dot_bashrc` in this case) manually (I have the `~/.local/share/chezmoi` directory open in VS Code and I edit the files in there), but the tricky thing with this approach is remembering to run `chezmoi apply` to apply the changes.

You can also run `chezmoi edit .bashrc`, or `chezmoi cd` and then edit `dot_bashrc` in your `$EDITOR`.

If you added it to `dot_bashrc` then this might need more investigation.

**Comment by twpayne** [comment]
@SreenivasVRao, @bradenhilton's comment should explain your situation. Please re-open if needed.
