### ISSUE TITLE
Invalid key in config when using dash

### ISSUE THREAD

**Issue by mcexit** [twpayne/chezmoi#2198]
## Describe the bug

Whenever trying to use a key with a dash in `~/.config/chezmoi/chezmoi.toml, it gives an error. According to the TOML v1.0.0 spec[^1] this should be valid.

## To reproduce

Add a key with a dash/hypen in the chezmoi `config.toml`

## Expected behavior

Allow key with dash/hyphen.

## Output of command with the `--verbose` flag

```console
chezmoi: invalid config: /home/user/.config/chezmoi/chezmoi.toml: key-name: invalid key
```

## Output of `chezmoi doctor`

<details>

```console
chezmoi: warning: /home/user/.config/chezmoi/chezmoi.toml: key-name: invalid key
RESULT    CHECK                MESSAGE
warning   version              v2.18.1, built at 2022-06-23T20:04:43Z
ok        latest-version       v2.18.1
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux host 5.18.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 02 Jul 2022 21:03:08 +0000 x86_64 GNU/Linux
ok        go-version           go1.18.3 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-07-04T15:44:59-07:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
ok        cd-command           found /bin/bash
ok        cd-args              /bin/bash
ok        edit-command         found /usr/bin/vim
ok        edit-args            /usr/bin/vim
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.37.0
ok        merge-command        found /usr/bin/vimdiff
ok        age-command          found /usr/bin/age, version 1.0.0
ok        gpg-command          found /usr/bin/gpg, version 2.2.35
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
ok        gopass-command       found /usr/bin/gopass, version 1.14.3
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.1
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/bin/pass, version 1.7.4
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

Unsure if this is an issue with the module or version of module being used. If so, then I can report upstream if desired.

[^1]: https://toml.io/en/v1.0.0#keys

**Comment by twpayne** [comment]
This is a deliberate extra check added by chezmoi. Keys with dashes in them cannot be used unquoted in templates. See #1438.

**Comment by twpayne** [comment]
Thank you for the detailed follow-up and for your kind words :)

> I'm curious on the design decision to use different rules from `.chezmoidata.toml` in the source state and `chezmoi.toml` in the config directory.

This was an oversight. I initially added the check to disallow dashes in keys as a way to reduce the support burden on me when users hit the problem: instead of getting confused with invalid template variable names, they would instead get an early warning. However, I didn't apply the same checks to `.chezmoidata.toml`. #2202 removes the check, and makes chezmoi consistent in its parsing (with the exception of spf13/cobra downcasing keys in the config file, of course).

> `.chezmoidata.toml` appears to offer all the features I'm looking for, including maintaining capitalization. Maybe the best route is to figure out how to automatically copy the user config into the source state and then add it to .gitignore. This is less than ideal, but should be doable.

Yeah, case preservation (#463) is a long-standing bug in a dependency that is sadly quite hard to fix. I would question whether preserving case is so important that a major work-around is preferable to losing case.

> A separate request that I may open would be to integrate gomplate[1](#user-content-fn-1-338ee5dc1f70911fc9b373495878cf60)[2](#user-content-fn-2-338ee5dc1f70911fc9b373495878cf60) or additional functions to convert to TOML[2](#user-content-fn-2-338ee5dc1f70911fc9b373495878cf60)[3](#user-content-fn-3-338ee5dc1f70911fc9b373495878cf60) and potentially INI[4](#user-content-fn-4-338ee5dc1f70911fc9b373495878cf60) format as well.

Please do open separate issues for these so we can track them.
