### ISSUE TITLE
Stop chezmoi from adding dot_DS_Store file

### ISSUE THREAD

**Issue by viggo-gascou** [twpayne/chezmoi#2203]
## What exactly are you trying to do?

I am trying to add a folder to chezmoi without the `.DS_Store` file that exists in every folder on MacOS. 
When adding a folder to chezmoi on MacOS it always adds a `dot_DS_Store` file, because I guess it assumes that, it is an 'important' file and should be added/managed as well. 

## What have you tried so far?

I have tried to add `.DS_Store` and `*.DS_Store` to the `.chezmoiignore` file and added that in the source state (`~/.local/share/chezmoi`, my local git repository.) If I understand what 'source state' means correctly 😅. Then adding a folder where `.DS_Store` is present, did not change the outcome.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.
    * Checked the GitHub issues, both closed and open. 

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

I think the dirty git tree warnings are because I added the `.chezmoiignore` file without committing and pushing.

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.18.1, commit 89f8b0ea0aa4e3add6e1bd2706d3db22373968c8, built at 2022-06-23T16:19:01Z, built by Homebrew
ok        latest-version       v2.18.1
ok        os-arch              darwin/arm64
ok        uname                Darwin MacBook-Air.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
ok        go-version           go1.18.3 (gc)
ok        executable           /opt/homebrew/bin/chezmoi
ok        upgrade-method       brew-upgrade
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-07-05T21:16:39+02:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
warning   suspicious-entries   ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        shell-command        found /opt/homebrew/bin/zsh
ok        shell-args           /opt/homebrew/bin/zsh
ok        cd-command           found /opt/homebrew/bin/zsh
ok        cd-args              /opt/homebrew/bin/zsh
ok        edit-command         found ~/.local/bin/lvim
ok        edit-args            lvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /opt/homebrew/bin/git, version 2.37.0
ok        merge-command        found /usr/bin/vimdiff
ok        age-command          found /opt/homebrew/bin/age, version 1.0.0
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

Might just be me that is missing a fundamental config or something somewhere, so any tips or help would be appreciated!
Also any tips for managing my dotfiles and or [GitHub repo](https://github.com/viggo-gascou/dotfiles) with chezmoi would be highly appreciated! I am a bit overwhelmed by all the different ways to use chezmoi.

**Comment by twpayne** [comment]
chezmoi's ignore syntax is a little different from git's. Try putting the following in `~/.local/share/chezmoi/.chezmoiignore`:

```
**/.DS_Store
```

**Comment by viggo-gascou** [comment]
Oh wow that worked perfectly! Thanks!

Also is it 'wrong' to have my chezmoi config also managed by chezmoi? Specifically asking because of the `suspicious-entries` warning from `chezmoi doctor`.

**Comment by twpayne** [comment]
> Also is it 'wrong' to have my chezmoi config also managed by chezmoi? Specifically asking because of the `suspicious-entries` warning from `chezmoi doctor`.

Yes, it's 'wrong'. Use a [config file template](https://www.chezmoi.io/user-guide/setup/#create-a-config-file-on-a-new-machine-automatically) instead.

**Comment by viggo-gascou** [comment]
Alright thanks! Will look into that.
Also thanks for the quick replies!

Will close the issue now.
