### ISSUE TITLE
template documentation hell

### ISSUE THREAD

**Issue by j-xella** [twpayne/chezmoi#2209]
## What exactly are you trying to do?

I am trying create a template **run_onchange_** script that is invoked when a file in the target dir changes. For that, I am trying to calculate checksum of a file in the target folder, and not fail if the file does not exist (yet).

## What have you tried so far?

I noticed the `{{ include 'file' | sha256sum }}` example. However, it fails if the file does not exist. 

I tried to find more documentation about "include" command - FAIL

I tried to find a template function to check for file existence - FAIL

I tried to find an os-independent way to generate full path to a file - FAIL

## Where else have you checked for solutions?

* https://pkg.go.dev/text/template
* http://masterminds.github.io/sprig/
* https://www.chezmoi.io/reference/templates/functions/

**Comment by twpayne** [comment]
> I tried to find more documentation about "include" command - FAIL

https://www.chezmoi.io/reference/templates/functions/include/

> I tried to find a template function to check for file existence - FAIL

https://www.chezmoi.io/reference/templates/functions/stat/

> I tried to find an os-independent way to generate full path to a file - FAIL

https://www.chezmoi.io/reference/templates/functions/joinPath/

Hope this helps.
