### ISSUE TITLE
chezmoiexternal - pre/post events

### ISSUE THREAD

**Issue by j-xella** [twpayne/chezmoi#2211]
I am using new chezmoi git-repo functionality to install some vim plugins (for example [this](https://github.com/airblade/vim-gitgutter)) automatically. All is great, except that after the plugin is installed/updated, an additional step has to be performed (in this case regenerating help tags). I am not sure it is possible to do with chezmoi at the moment.

I think it would be great if chezmoiexternal config could be extended with possibility to perform events before/after update. For any type of external file, not just git-repo...

---------------

This is how I imagine it:

```
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
    [".vim/autoload/plug.vim".pre]
        script = "{{- template xyz -}}"
        args = [ "-a", "-b", ... ]

[".vim/pack/alker0/chezmoi.vim"]
    type = "git-repo"
    url = "https://github.com/alker0/chezmoi.vim.git"
    refreshPeriod = "168h"
    [".vim/pack/alker0/chezmoi.vim".post]
        executable = "vim"
        args = ["-c", "helptags doc", ...]
```

Every external section would get 2 new subsections available, `$DIR.pre` and `$DIR.post`. Those subsections would have identical set of variables, but one would control event fired before the update, another - after.

The program to run for the event would be specified with either `script` or `executable` variable (mutually exclusive). `executable` is assumed to be available on the system, chezmoi would just exec it. The value of `script`, however, would undergo template expansion, the result is stored in a temporary script, similar to what happens with `run_*.tmpl` scripts. Obviously, the `script` option is more flexible, but it breaks the declarative approach, so the usage of `executable` is recommended where possible.

Then, either the excutable or the temporary script is executed from within `$DIR`, passing it `args`, if available.

**Comment by twpayne** [comment]
Thanks for opening this issue, it's an interesting use case.

I propose to solve this a different way for a couple of reasons:
* `.chezmoiexternal` is currently declarative, and adding pre- and post- scripts will break that. chezmoi tries to keep all of its imperative code in scripts.
* Writing scripts - which can be templates - inside `.chezmoiexternal` which is already itself a template will be very tricky to maintain.
* chezmoi needs to evaluate the target state for dry-run-like operations like `chezmoi diff` and `chezmoi archive`.

Instead I propose the following based on [Run a script when the contents of another file changes](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) but running the script when a *directory* changes instead of when a *file* changes.

As you can use
    {{ include $filename | sha256sum }}
inside a `run_onchange_` script to run the script when the contents of `$filename` change, I propose to add something like:
    {{ dirContents $dirname | sha256sum }}
that will generate a hash based on the contents of `$dirname`, including file permissions of all entries in `$dirname` but not modification times.

With this approach, you can use a `run_onchange_` script to run whatever you want when the contents of a directory changes.

What do you think?

**Comment by j-xella** [comment]
> Instead I propose the following based on [Run a script when the contents of another file changes](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) ...
> 

A bit off-topic, but since you mentioned [Run a script when the contents of another file changes](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) page, I wonder if there is a lot of typos in that section. The whole section mentions `run_once_*` scripts, but shouldn't they be `run_onchange_*` ?

**Comment by j-xella** [comment]
> ... I propose to add something like:
> 
> ```
> {{ dirContents $dirname | sha256sum }}
> ```
> 
> that will generate a hash based on the contents of `$dirname`, including file permissions of all entries in `$dirname` but not modification times.
> 
> With this approach, you can use a `run_onchange_` script to run whatever you want when the contents of a directory changes.
> 
> What do you think?

Well, actually I have already implemented something like this. I used `chezmoi.homeDir` to determine the root of the target directory, and then find the relative location of my externals. Then, since in my case the external folders were git repositories, the script would run if the current commit changed. Below is the code, if you are interested:

```
{{- $dest_folder := joinPath .core.chezmoi.homeDir ".config" "nvim" "pack" .pack_path -}}
{{- if stat ( joinPath $dest_folder "doc" ) -}}

{{- if (ne .core.chezmoi.os "windows") -}}
#! /usr/bin/sh

{{ if stat ( joinPath $dest_folder ".git" "HEAD" ) -}}
{{- $git_head := regexReplaceAll "^ref: *" ( include ( joinPath $dest_folder ".git" "HEAD" ) ) "" -}}
{{- $git_head := regexReplaceAll "\\s*$" $git_head "" -}}
# Current git HEAD of {{.pack_path}} is {{$git_head}}
{{ if stat ( joinPath $dest_folder ".git" $git_head ) -}}
# Resolves into : {{ include ( joinPath $dest_folder ".git" $git_head ) }}
{{ end -}}
{{- end -}}


cd {{ $dest_folder | squote }}
nvim -Es -c "helptags doc | qa!"

{{- end -}} {{- /* OS is not windows */ -}}
{{- end -}} {{- /* plugin has documentation */ -}}
```

What I have noticed, though, is that with this approach, it is impossible to predict what is going to happen first: the update of the externals, or the invokation of my run_onchange script. In my case, the invokation of the script happened first, while I really needed the "post" event. So I have to run `chezmoi apply` twice to get what I need.

**Comment by j-xella** [comment]
> * `.chezmoiexternal` is currently declarative, and adding pre- and post- scripts will break that. chezmoi tries to keep all of its imperative code in scripts.
> * Writing scripts - which can be templates - inside `.chezmoiexternal` which is already itself a template will be very tricky to maintain.

OK, maybe the `script` option with templates is an overkill. But specifying a name of the executable to run - will it break declarativeness a lot?

```
    [".vim/pack/alker0/chezmoi.vim".post]
        executable = "vim"
        args = ["-c", "helptags doc", ...]
```

**Comment by bradenhilton** [comment]
@j-xella

> > Instead I propose the following based on [Run a script when the contents of another file changes](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) ...
> 
> A bit off-topic, but since you mentioned [Run a script when the contents of another file changes](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) page, I wonder if there is a lot of typos in that section. The whole section mentions `run_once_*` scripts, but shouldn't they be `run_onchange_*` ?

No. `run_once_` and `run_onchange_` are both sufficient for that use case.

> I can say that
> 1. This approach can only work for "post" events, when externals already changed. But what if I need to do something before the external is updated? "onchange" script is not going to help here.
> 2. Even for "post" events, this will only work OK if the "onchange" script is checked and executed after the external was updated. Unfortunately, this is not the case - chezmoi seems to run the scripts firts, then updates externals. So I have to run chezmoi apply twice every time now to get what I need. Can this be addressed?

`run_*` scripts accept `before_` and `after_` attributes, thought I'm not entirely sure how they interact with externals. Perhaps @twpayne can clarify if an external being refreshed with a new version will trigger `run_onchange/once_before_` before the external is applied to the destination directory. Maybe `{{ dirContents $dirname | sha256sum }}` would be necessary for this?

> OK, maybe the `script` option with templates is an overkill. But specifying a name of the executable to run - will it break declarativeness a lot?
> ```
>     [".vim/pack/alker0/chezmoi.vim".post]
>         executable = "vim"
>        args = ["-c", "helptags doc", ...]
> ```

What should happen if the external fails to download for whatever reason? Should the `*.pre` still be run? What if you'd like it to still be run in some cases but not others? What should happen if a `*.pre` or `*.post` fails to run (executable not installed, missing dependencies etc.)? I still think this is imperative. It just assumes the necessary checks were successful.

---

Externals have some nice features (auto-refresh, stripping/filtering contents etc.) but you don't have to use them if it's easier to just write a single script to take care of dependencies (both before and after) as well as downloading the files.

**Comment by twpayne** [comment]
Thanks all for the discussion.

> Perhaps @twpayne can clarify if an external being refreshed with a new version will trigger `run_onchange/once_before_` before the external is applied to the destination directory. Maybe `{{ dirContents $dirname | sha256sum }}` would be necessary for this?

This depends on when the template containing the `{{ dirContents ... }}` is executed. Generally speaking, chezmoi only executes templates when their contents are needed, but for scripts this is generally quite early, especially for `once_` and `onchange_` scripts whose contents are needed to determine whether they should be run or not. chezmoi only executes templates once and then caches the result. chezmoi cannot realistically determine when a template depends on external state or re-execute the template when that external state changes.

All of this leads me to agree with @bradenhilton that an unconditional `run_after_` script is the best fit here. I don't think pre/post events can work well with externals, and clearly using a `run_onchange_` script with a `{{ dirContents ... }}` doesn't work either as it depends on when the template is executed, which is not defined. So, closing this as "won't fix".  Thank you for the suggestion and discussion.
