### ISSUE TITLE
chezmoi select menu on terminal

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [twpayne/chezmoi#2212]
![image](https://user-images.githubusercontent.com/45184918/178627273-354be6ba-6aa3-4aa4-ae17-9a657c16d6c0.png)

I would like to be able to see a menu all my files i could edit

**Comment by twpayne** [comment]
`chezmoi managed` lists the files managed by chezmoi.

Please read chezmoi's documentation before creating issues. In the last two days you have posted three questions that would have been answered by reading chezmoi's documentation (#2206, #2207, #2212). If you post another question that is already answered in the documentation I will block you from posting.
