### ISSUE TITLE
Support for AWS Secrets Manager

### ISSUE THREAD

**Issue by craiggwilson** [twpayne/chezmoi#2216]
## Is your feature request related to a problem? Please describe.

I have personal secrets in 1password, but my company has secrets in AWS Secrets Manager. I'd like to have my dotfiles pull from both places natively. I know I could use the secret command line callout, but having something natively integrated is nice.

## Describe the solution you'd like

I would like some template functions that allow for reading secrets from AWS Secrets Manager.

## Describe alternatives you've considered

Could use the secret command callout, which is likely sufficient, but it's not native.

## Additional context

If this is of interest, I have it working locally, just need to add documentation and figure out how to do testing, as not everyone who is running tests will have secrets in AWS...

It does take a dependency on the `aws-go-sdk-v2`, which might be a deal breaker if `chezmoi` doesn't want further dependencies. It is natively go, so it's just like any other dep.

**Comment by twpayne** [comment]
This would be a very nice addition, thank you. Please do open a PR.

The extra dependency is OK, as long as it does not massively increase the size of chezmoi's binary. chezmoi's binaries are currently about 30MB in size, and, as long as adding `aws-go-sdk-v2` does not add more than, say, 10MB to it the final size, it's OK.

#2062 is a good reference for the changes needed to add a new password manager.
