### ISSUE TITLE
Chezmoi on android arm64 termux only tries IPv6 lookup and fails

### ISSUE THREAD

**Issue by gdevenyi** [twpayne/chezmoi#2222]
## Describe the bug

I am trying to init my repo and chez-moi cannot download a file from my chezmoi external config

Chezmoi on android arm64 termux only tries IPv6 lookup and fails

## To reproduce

chezmoi init

## Expected behavior

Init works 

## Output of command with the `--verbose` flag

```console
$ bash -c "$(curl -fsLS https://chezmoi.io/get)" -- init --apply gdevenyi/chezmoi --verbose
info found version 2.19.0 for latest/linux/arm64
info installed ./bin/chezmoi
chezmoi: Get "https://github.com/nojhan/liquidprompt/archive/refs/heads/master.zip": dial tcp: lookup github.com on [::1]:53: read udp [::1]:46911->[::1]:53: read: connection refused
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
./chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.19.0, commit c2fc69d68a87620c5f166573d50958da35a1033e, built at 2022-07-17T17:36:27Z, built by goreleaser
failed    latest-version       Get "https://api.github.com/repos/twpayne/chezmoi/releases/latest": dial tcp: lookup api.github.com on [::1]:53: read udp [::1]:48198->[::1]:53: read: connection refused
ok        os-arch              linux/arm64
ok        uname                Linux localhost 4.9.227-g8bce3f4b0603 #1 SMP PREEMPT Tue Jul 12 00:26:45 UTC 2022 aarch64 Android
ok        go-version           go1.18.4 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        shell-command        found /data/data/com.termux/files/usr/bin/bash
ok        shell-args           /data/data/com.termux/files/usr/bin/bash
ok        cd-command           found /data/data/com.termux/files/usr/bin/bash
ok        cd-args              /data/data/com.termux/files/usr/bin/bash
warning   edit-command         vi not found in $PATH
ok        edit-args            vi
info      diff-command         not set
warning   umask                077
ok        git-command          found /data/data/com.termux/files/usr/bin/git, version 2.37.1
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

Using `curl` to directly access the failing URL works.

**Comment by twpayne** [comment]
Thank you for reporting this. I strongly suspect that the underlying problem is that the chezmoi binary distributed on GitHub and downloaded by `bash -c "$(curl -fsLS https://chezmoi.io/get)"` is built with cgo disabled, which means that Go falls back to its own builtin DNS resolver code, which I suspect does not resolve IPv4 addresses correctly on Termux.

The short-term fix is to [install chezmoi from source](https://www.chezmoi.io/install/#install-from-source) in your Termux environment and use the resulting binary.

In the medium term, this will require updating [chezmoi's release automation](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml) to install and use a cross-compiler to build the linux/arm64 binary with cgo enabled. This may take some time.

**Comment by gdevenyi** [comment]
In the meantime, I just discovered the termux software repository has chezmoi built in its system which works:
https://github.com/termux/termux-packages/tree/master/packages/chezmoi

So this could be a documentation adjustment for Android/Termux to do `pkg install chezmoi`

**Comment by twpayne** [comment]
Awesome! That's a much better solution, thank you.

I'll close this issue, but please re-open it if you think that `bash -c "$(curl -fsLS https://chezmoi.io/get)"` should install a version of chezmoi that resolves IPv4 directly - it's an entirely reasonable request, methinks.
