### ISSUE TITLE
Add dark mode to documentation site

### ISSUE THREAD

**Issue by Hudater** [twpayne/chezmoi#2228]
## Is your feature request related to a problem? Please describe.

No dark mode makes it tough to read documentation for some of us

## Describe the solution you'd like

Add the native theme toggle available in mkdocs-material

## Describe alternatives you've considered

Dark reader or other similar extensions work fine but not every browser supports or works well with them. Mobile devices don't support extensions in Brave or other chromium browsers

## Additional context

You just need to add `palette` sub-option under theme in `mkdocs.yml` file. I can open PR if it's a go from admin's side

**Comment by twpayne** [comment]
A PR would be very welcome, thank you!

The contributing guide for website-related stuff is [here](https://www.chezmoi.io/developer/website/), but I think you've already read it :)

**Comment by Hudater** [comment]
[PR#2231](https://github.com/twpayne/chezmoi/pull/2231)
Closing issue, thanks!

**Comment by twpayne** [comment]
#2231 isn't merged yet, let's keep this open until it is.
