### ISSUE TITLE
xs

### ISSUE THREAD

**Issue by ranjeetwwstay** [twpayne/chezmoi#2233]
## What exactly are you trying to do?

Describe in as much detail as possible.

## What have you tried so far?

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by ranjeetwwstay** [comment]
test

**Comment by twpayne** [comment]
There doesn't seem to be any information in this issue.
