### ISSUE TITLE
wish: chezmoi merge

### ISSUE THREAD

**Issue by markstos** [twpayne/chezmoi#224]
This is different than the merge feature requested in #219.

I would like `chezmoi merge ./path/to/file.txt` open up a configurable merge tool for the target and source files.

If I was more disciplined, I would always use `chezmoi edit` for updates. But I'm not. I tend to update the target files directly and deal with sync'ing the target state later.

Now I'm in a state where my target and source files both have changes I want to keep, so either `add` nor `apply` is the corect answer.

Perhaps instead I should `chmod` all the target files to be read-only to remind me to edit the source files instead!

Once I start using templates, it will be increasingly messy to edit the target files. Maybe this workflow isn't one that should be encouraged and making the targets read-only by default is a better idea.

**Comment by twpayne** [comment]
Very good wish :)

If I understand correctly, the three-way merge is between:
1. The file contents in the target directory.
2. The computed file contents in the target state.
3. The source file in the source state (which is where you want to save the changes).

If you're not using templates then 2 and 3 are the same and the problem becomes a two-way merge.

Could you give an example of a three-way merge tool that you'd prefer to use?

**Comment by markstos** [comment]
Personally, I would use `vimdiff`, which I imagine would also be of interest to some other `chezmoi` users.  Other merge tools include  emerge, gvimdiff, kdiff3, meld, and tortoisemerge.

It turns out that some of the Git code used for interacting with the merge tools is written in bash:

https://github.com/git/git/blob/master/git-mergetool.sh

A `--tool` option is used to select the merge tool.

**Comment by markstos** [comment]
Thanks @twpayne !
