### ISSUE TITLE
Overwrite change handling for `modify_` scripts

### ISSUE THREAD

**Issue by VorpalBlade** [twpayne/chezmoi#2244]
## Is your feature request related to a problem? Please describe.

When a settings file has changed on the system `chezmoi apply` will ask if I want to overwrite/diff the changes. This feature isn't available when using `modify_` scripts. For example when I use my [chezmoi_modify_manager](https://github.com/VorpalBlade/chezmoi_modify_manager) to handle KDE settings files.

## Describe the solution you'd like

I would like some way to interact with the overwrite-detection logic from `modify_` scripts. Or perhaps a way to present my own such prompt (as stdout and stdin is captured by chezmoi this doesn't currently work). Like any programmer I would like to do the least amount of work myself, so I would like to piggyback on what functionality chezmoi has as much as possible. Maybe a way to query if the modified file has changed since chezmoi last applied it and what the change is?

## Describe alternatives you've considered

I considered implementing all the required machinery in my modify script, but as `chezmoi` captures stdout this presents some problems with the user interaction. Even if I could use stderr for output, stdin is also redirected by `chezmoi` making this a non-starter, as I could not interact with the user.

In addition, such an approach would result in a significant amount of reimplementation of functionality that is already in chezmoi.

**Comment by twpayne** [comment]
> When a settings file has changed on the system `chezmoi apply` will ask if I want to overwrite/diff the changes. This feature isn't available when using `modify_` scripts.

Could you be more specific in why "this feature isn't available" when using `modify_` scripts? Internally, chezmoi uses the `modify_` script to generate the target state of the file so all these features should be available as normal. Could you give a reproducible example where this doesn't work as expected?

**Comment by VorpalBlade** [comment]
Hm, I have observed `modify_` scripts silently overwriting changes on the system side. So I assumed that the feature simply didn't work in that case. If that is a bug, I will investigate this further and try to find a small reproducer.

**Comment by VorpalBlade** [comment]
Here is an easy reproducer:
```shell
$ chezmoi cd
$ cat > modify_foo <<EOF
#!/bin/bash

cat > /dev/null # Discard input
echo "a" # Always output same text
EOF
$ chezmoi apply
$ echo b > ~/foo
$ chezmoi apply
```
The last chezmoi apply should ask about overwriting (since the file has been changed on the system). It doesn't, instead it just applies the change, overwriting the system-side change.

**Comment by twpayne** [comment]
Ah, thank you for the clear reproduction case.

It turns out that the current behavior is explicit. The background is #1046, particularly in [this comment](https://github.com/twpayne/chezmoi/issues/1046#issuecomment-864343405), and the behavior added in #1296.

The tl;dr is that the intention behind `modify_` scripts is that they modify files that are assumed to be changed regularly by third-party software, so if `chezmoi apply` prompts every time the third-party software changes the file, this quickly becomes annoying.

Maybe this always-overwrite behavior for `modify_` scripts should be configurable? What are your thoughts?

**Comment by twpayne** [comment]
Also, @lcrockett identified that a selective approach might be needed [in this comment](https://github.com/twpayne/chezmoi/pull/1296#issuecomment-878882034). Respect for the foresight!

**Comment by VorpalBlade** [comment]
> Maybe this always-overwrite behavior for `modify_` scripts should be configurable? What are your thoughts?

After thinking about it I realise I want to have my cake and eat it too. My modify scripts do modify files that change often (state such as recently opened files). Yet when something relevant changes I want to prompt the user. I don't think chezmoi can determine this in the general case.

You would end up with some crazy heuristic like "ignore lines that in changed in system state and that the script also changed the same way, but warn if the script overwrites lines the changed in system state with something different". That would *kind of* work, but what about two applies in a row? How long should chezmoi remember that those lines changed? Only since the most recent apply? Since the time the script last wrote to those specific lines? No, this way lies madness.

However, the modify script itself is in a far better position to make sense of the situation! So what I believe should be done is give the modify script the tools to handle it. Here is the minimum needed for this I believe:
* A way to query the database of file state according to chezmoi. Sure the script can track this on it's own, implement 3-way merge etc. But if chezmoi already stores this, then lets reuse the data!
* A way to interact with the user. stdin/stdout is already used up by other tasks. I guess I could open `/dev/tty` directly. But I risk clobbering chezmoi I think? Some thought is needed here. Also, what about when run non-interactively, such as when I trigger `chezmoi update` over ssh using GNU parallel, ansible or some other tool on multiple computers?

**Comment by VorpalBlade** [comment]
As an addendum: I believe after thinking some more that `modify_` was made with the intent of "ignore everything by default, change a few lines in the file", but I'm trying to use it for "include everything by default, ignore a few lines". This causes a mismatch of expectations.

**Comment by VorpalBlade** [comment]
Second addendum: For the non-interactive case I'm more than happy to just be able to detect it and default to the save option (don't overwrite).

**Comment by twpayne** [comment]
Crazy idea: introduce a `tweak_` attribute (or [other synonym](https://www.thesaurus.com/browse/modify)) that behaves like `modify_` except that it doesn't overwrite files by default.

**Comment by VorpalBlade** [comment]
> Crazy idea: introduce a tweak_ attribute (or [other synonym](https://www.thesaurus.com/browse/modify)) that behaves like modify_ except that it doesn't overwrite files by default.

That doesn't quite work for my use case, as I do expect changes in "ignored" parts of the ini file. I copy those from the system state directly. What I really want is to only get a question when there are changes in non-ignored parts.

This means I have to track not just the checksum of the file, but the whole file that was written out to the system state last time (otherwise I can't tell if it was a change in the system or source state). Then I need to handle things from there. However only the modify script is in a position to know about this.

However the `tweak_` script idea might still be good, with different semantics. Why not pass the system state via FD 3 and expect output on FD4? Then leave stdin/stdout/stderr connected to the user. Then the script can do whatever crazy multi-way merge kind of deal it wants to do, possibly interactively?

**Comment by VorpalBlade** [comment]
@twpayne Hm, I'm not sure what you mean by the "two eyes" emoji.

Do you have any comments on my suggestion? Perhaps a different API that accomplishes the same result in case you think this is too messy?

**Comment by twpayne** [comment]
Hi, sorry, to me 👀 meant that I'd seen the comment.

Your suggestion is very good, I need a bit of time to think it through. It was late last night and occasionally real life gets in the way of open source 😅

**Comment by twpayne** [comment]
Some thoughts:

`modify_` scripts are invoked every time that chezmoi needs to compute the target state. This occurs not only for `chezmoi apply`, but for other commands like `diff`, `status`, and `archive`. Since `modify_` scripts are invoked so often, making them interactive will quickly be annoying. For example, if you do a `chezmoi diff` to see what would change you'd have to go through the scripts prompts, and then if you did a `chezmoi apply` to apply the changes you'd have to go through the same set of prompts again.

chezmoi deliberately stores hashes of targets in its state, not complete contents, for two reasons. Firstly, security. The state is stored in unencrypted and I don't want to risk secrets being stored in there. Hashing avoids this. Secondly, size. The managed files can potentially be quite large, and storing all of them in there will make the database large too. Hashing also avoids this.

An alternative suggestion would be that if a `modify_` script wants to be interactive it can use `/dev/tty`to get a terminal.

**Comment by VorpalBlade** [comment]
> For example, if you do a chezmoi diff to see what would change you'd have to go through the scripts prompts, and then if you did a chezmoi apply to apply the changes you'd have to go through the same set of prompts again.

This is a good point. Would it be possible to communicate to the script what operation is on-going? Maybe via an environment variable. That way I can avoid asking the user unless the operation is `apply` (I will need to look through the other operations to determine what to do).

> An alternative suggestion would be that if a modify_ script wants to be interactive it can use /dev/ttyto get a terminal.

That would work assuming that it does not play havoc with chezmoi (both programs reading the input or something like that). What happens if the `modify_` script has a prompt, does it's job and then chezmoi has another prompt later? Does this result in chezmoi also reading the same input?

**Comment by twpayne** [comment]
> This is a good point. Would it be possible to communicate to the script what operation is on-going? Maybe via an environment variable. That way I can avoid asking the user unless the operation is `apply` (I will need to look through the other operations to determine what to do).

This is not a path I want to follow. chezmoi internally is very careful to make sure the code paths for `apply`, `diff`, `archive`, etc. are as identical as possible to ensure that the effects are consistent. Having `modify_` scripts that behave differently depending on how chezmoi is invoked would likely lead to strange and difficult-to-debug behavior. If you really want to know, the script could look at its parent process to determine if it was invoked by chezmoi and if so what arguments chezmoi was invoked with. 

> > An alternative suggestion would be that if a modify_ script wants to be interactive it can use /dev/tty to get a terminal.
> 
> That would work assuming that it does not play havoc with chezmoi (both programs reading the input or something like that). What happens if the `modify_` script has a prompt, does it's job and then chezmoi has another prompt later? Does this result in chezmoi also reading the same input?

The two should be independent. chezmoi does not actually use any terminal functionality at the moment, and so should leave the terminal in a good state.

**Comment by VorpalBlade** [comment]
> This is not a path I want to follow. chezmoi internally is very careful to make sure the code paths for apply, diff, archive, etc. are as identical as possible to ensure that the effects are consistent. Having modify_ scripts that behave differently depending on how chezmoi is invoked would likely lead to strange and difficult-to-debug behavior. If you really want to know, the script could look at its parent process to determine if it was invoked by chezmoi and if so what arguments chezmoi was invoked with.

Fair enough, this is a sound argument. I intend the only difference to be showing a prompt or not, which is a relatively benign difference. Looking at the parent process will absolutely work under Linux at least, which is fine for my use case.

> The two should be independent. chezmoi does not actually use any terminal functionality at the moment, and so should leave the terminal in a good state.

That is good, I know very little about TTY programming, so I'm not sure what would happen if one process reads /dev/tty and the other process reads stdin attached to that tty

**Comment by twpayne** [comment]
Hopefully this is now resolved, please re-open if needed.
