### ISSUE TITLE
Show vX.Y+something for dev versions

### ISSUE THREAD

**Issue by jayvdb** [twpayne/chezmoi#2254]
## Is your feature request related to a problem? Please describe.

I first installed chezmoi using guix, and its build shows version "dev". i.e.
```
$ chezmoi --version
chezmoi version dev
```
It was mentioned on the installation guide so I assumed this would be a recent version.  Turns out `guix show chezmoi` shows `1.8.1`.  

IMO it would be a good idea to remove guix since it is unmaintained, or at least link to/ use data from https://repology.org/project/chezmoi/versions to help inform people of which package manager they may wish to avoid.

I then built it locally from git, and found it also shows "dev" as the version.

## Describe the solution you'd like

At least for git builds, which are easy to detect, it would be good to have the version number + sha, i.e. `v2.20.0+892c584`

## Describe alternatives you've considered

Another pattern which is common is the most recent tag name followed by the number of commits since that tag, i.e. `v2.20.0-NEXT.20`

**Comment by jayvdb** [comment]
Ugh, I see the Makefile has support for this as `install-from-git-working-copy` , which isn't mentioned on https://www.chezmoi.io/install/#install-from-source

**Comment by twpayne** [comment]
Thanks for this, I've created #2255 to update the docs.
