### ISSUE TITLE
Separate VCS for each type of dotfile

### ISSUE THREAD

**Issue by johnramsden** [twpayne/chezmoi#226]
In the past I have used dotfile managers which put individual types of dotfiles in different repositories. From what I could tell looking at the help section and docs, only one monolithic repo can be used with chezmoi. Is there any support for using different git repos for each type of dotfile?

For example I might want to stick my ssh config in one repo, zsh config in another, then have a specific set up where I only clone certain repositories on each machine. Is something similar to this possible with chezmoi? If it isn't, would it be possible to add this functionality?

**Comment by twpayne** [comment]
I think this over-complicates things for no major benefit. `chezmoi` already has several mechanisms for reducing the data exposed on each machine, without needing the complexity of using multiple repos.

You're free to manage your source state directory using whatever tool you wish. I would suggest writing a script to combine the output of your multiple repositories into a single source state directory, and then invoking `chezmoi` with that source state directory.

**Comment by johnramsden** [comment]
Would you consider adding a `--recursive` flag to the apply command? That way if someone chose to use git sub-modules to manage their source repository they could be applied in one step.

**Comment by twpayne** [comment]
Currently the structure of the source state matches the structure of the target state exactly. Adding a `--recursive` flag would break that and that `chezmoi` would have to work out when a subdirectory is a subdirectory in the target state and when a subdirectory is a git submodule and should be treated as if it were its parent. You also need to work out what to do when a target file is present in multiple submodules. This is all very complicated and error-prone.

So, in a word, no :)
