### ISSUE TITLE
Hash Content of Directory

### ISSUE THREAD

**Issue by twobiers** [twpayne/chezmoi#2271]
## What exactly are you trying to do?

I'm using the `.chezmoiexternal.toml` file to include some fonts in the `./local/share/fonts` directory. Using Windows, I need to do additional steps to install fonts and therefore I need to run a script.
My script is based on [this gist](https://gist.github.com/anthonyeden/0088b07de8951403a643a8485af2709b?permalink_comment_id=3651336#gistcomment-3651336) and works as expected.

Now I want to run the script everytime the content in the font directory changes. This can occur for example when a font is updated. [According to the documentation](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/#run-a-script-when-the-contents-of-another-file-changes) I can use comments in the script with hashes to accomplish that. Unfortunately it seems to be only possible with file contents.

## What have you tried so far?

At the moment I'm hardcoding the files into the script:
```ps1
# {{ include ".local/share/fonts/Jetbrains Mono NF Regular.ttf" | sha256sum }}
# {{ include ".local/share/fonts/Jetbrains Mono NF Bold.ttf" | sha256sum }}
# {{ include ".local/share/fonts/Jetbrains Mono NF Italic.ttf" | sha256sum }}
# {{ include ".local/share/fonts/Jetbrains Mono NF BoldItalic.ttf" | sha256sum }}
```

I guess it would be sufficient to have a template function that (recursively) iterates over the files inside a directory.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Searched for Keywords in GitHub Issues
* [x] Sprig [Templates](http://masterminds.github.io/sprig/)

## Output of `chezmoi doctor`

<details>

```console
chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.20.0, commit 774eed29f7ddb9c910534d627990d63182ad0304, built at 2022-07-29T00:09:29Z, built by goreleaser
ok       latest-version       v2.20.0
ok       os-arch              windows/amd64
ok       systeminfo           Microsoft Windows 11 Pro (10.0.22000 N/A Build 22000)
ok       go-version           go1.18.4 (gc)
ok       executable           C:/ProgramData/chocolatey/lib/chezmoi/tools/chezmoi.exe
ok       config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-08-16T21:16:53+02:00
ok       source-dir           ~/.local/share/chezmoi is a git working tree (clean)
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok       dest-dir             ~ is a directory
ok       shell-command        found C:/Program Files/PowerShell/7/pwsh.exe
ok       shell-args           'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
ok       cd-command           found C:/Program Files/PowerShell/7/pwsh.exe
ok       cd-args              'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
ok       edit-command         found C:/Program Files/Microsoft VS Code/bin/code.cmd
ok       edit-args            code --wait
info     diff-command         not set
ok       git-command          found C:/Program Files/Git/cmd/git.exe, version 2.37.2
ok       merge-command        found C:/Program Files/Git/usr/bin/vimdiff.exe
info     age-command          age not found in $PATH
ok       gpg-command          found C:/Program Files (x86)/GnuPG/bin/gpg.exe, version 2.3.7
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keeper-command       keeper not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by twpayne** [comment]
This can be achieved with the [`glob` template function](https://www.chezmoi.io/reference/templates/functions/glob/) which implicitly supports recursion through the `**` pattern.

If you don't need recursion (i.e. if you don't have fonts in subdirectories) then something like the following might work for you (warning: untested):

```
{{ range (glob ".local/share/fonts/*.tff") -}}
# {{ include . | sha256sum }}
{{ end -}}
```

Please do report back if this works or not.

**Comment by twobiers** [comment]
Thank you for the fast response, really appreciate that.
It works for me with the following template as the Fonts are not part of the source files:
```
{{ range (glob (joinPath .chezmoi.homeDir ".local/share/fonts/*.ttf")) -}}
# {{ . | sha256sum }}
{{ end -}}
```

**Comment by twpayne** [comment]
> ```
> {{ range (glob (joinPath .chezmoi.homeDir ".local/share/fonts/*.ttf")) -}}
> # {{ . | sha256sum }}
> {{ end -}}
> ```

Note that this is computing the SHA256 sum of the file's _name_, not the file's _contents_.

**Comment by twobiers** [comment]
> > ```
> > {{ range (glob (joinPath .chezmoi.homeDir ".local/share/fonts/*.ttf")) -}}
> > # {{ . | sha256sum }}
> > {{ end -}}
> > ```
> 
> Note that this is computing the SHA256 sum of the file's _name_, not the file's _contents_.

Whops, missed the `include` function. Good catch, thank you again.
