### ISSUE TITLE
confusing priority of `Source state attributes`

### ISSUE THREAD

**Issue by loynoir** [twpayne/chezmoi#2292]
## Describe the bug
confusing priority of `Source state attributes`

## Actual behavior
confusing state attr order priority

| priority | action |
| --- | --- |
| `dot_modify_private_bash_history.tmpl` | Got `.modify_private_bash_history` |
| `modify_dot_private_bash_history.tmpl` | Got `.private_bash_history` |
| `modify_private_dot_bash_history.tmpl` | Able to append history and corrrect permmision on `.bash_history` |

## Expected behavior
- state attr order does not matter, or only allow order in ascii string order

| priority | action |
| --- | --- |
| `dot_modify_private_bash_history.tmpl` | Able to append history and corrrect permmision on `.bash_history` |
| `modify_dot_private_bash_history.tmpl` | Able to append history and corrrect permmision on `.bash_history` |
| `modify_private_dot_bash_history.tmpl` | Able to append history and corrrect permmision on `.bash_history` |

## Output of command with the `--verbose` flag

```console
$ chezmoi init --apply REPO
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context

I think this maybe a design bug.

If not, I think the priority problem should be mentioned on

https://www.chezmoi.io/reference/source-state-attributes/

**Comment by twpayne** [comment]
This is by design. The page in the reference manual you link to specifically states:

> The order of prefixes is important.

The order of prefixes is also listed in the page.
