### ISSUE TITLE
Ability to include templates with a dynamic name

### ISSUE THREAD

**Issue by joshuaspence** [twpayne/chezmoi#2310]
## Is your feature request related to a problem? Please describe.

I want to keep my dotfiles modular and so my `dot_profile.tmpl` currently looks like this:

```
if test -n "${BASH_VERSION}" && test -f ~/.bashrc; then
  . ~/.bashrc
fi

{{ include "shell/helpers.sh" }}

{{- $base := print .chezmoi.sourceDir "/" -}}
{{ range $file := glob (joinPath .chezmoi.sourceDir "shell/environment/*.sh") }}
# source={{ replace $base "" $file }}
{{ include $file -}}
{{ end -}}
```

I want to parse `$file` as a template rather than including it directly, but `template $file` doesn't work.

```
chezmoi: template: stdin:6: unexpected "$file" in template clause
```

## Describe the solution you'd like

Either an alternative `template` function that accepts a variable as it's first argument or extend `include` to be able to handle templates.

## Describe alternatives you've considered

For now I am using just avoiding the use of templates and using runtime logic (e.g. `if command -v`) instead.

**Comment by bradenhilton** [comment]
Seems like you're aware of this already, but just in case you aren't, [`template` searches for files within the `.chezmoitemplates` directory](https://www.chezmoi.io/reference/special-files-and-directories/chezmoitemplates/), so your `dot_profile.tmpl` would need some adjustments.

@twpayne can probably confirm here, but the `text/template` template action requiring constant string names/paths is deliberate, so a dynamic solution would probably require some kind of wrapper function which resolves the variable to a constant string first.

In the meantime, you could try creating a single monolithic template which includes other templates, in these other templates you can check the pipeline (`.`) and add content accordingly. You lose the ability to `glob` but it seems like it might work.

Something like:

`.local/share/chezmoi/dot_profile.tmpl`:
```
if test -n "${BASH_VERSION}" && test -f ~/.bashrc; then
  . ~/.bashrc
fi

{{ include "shell/helpers.sh" }}

{{ template "shell/environment/main.sh" }}
```

`.local/share/chezmoi/.chezmoitemplates/shell/environment/main.sh`:
```
{{ template "shell/environment/hello.sh" . }}

{{ template "shell/environment/world.sh" . }}

...
```

`.local/share/chezmoi/.chezmoitemplates/shell/environment/hello.sh`:
```
{{ if <some check here> }}
#source=shell/environment/hello.sh
...
{{ end }}
```

If the conditional doesn't pass, no content is added to `dot_profile.tmpl`

**Comment by twpayne** [comment]
> @twpayne can probably confirm here, but the `text/template` template action requiring constant string names/paths is deliberate, so a dynamic solution would probably require some kind of wrapper function which resolves the variable to a constant string first.

This is correct. chezmoi uses Go's standard `text/template` library which is quite opinionated. I have no plans to change or modify the template library used, so dynamic template inclusion is never likely to be supported. As a workaround, you can use conditional logic in the template, e.g. as @bradenhilton suggests.

**Comment by joshuaspence** [comment]
To clarify, the proposal was to add a new function rather than modifying the underlying library/functionality. I thought that such a function would be consistent with the existing `include` function.
