### ISSUE TITLE
`includeTemplate` function not respecting `.chezmoitemplates` directory

### ISSUE THREAD

**Issue by latipun7** [twpayne/chezmoi#2332]
## Describe the bug

Chezmoi v2.22.0 added `includeTemplate` template function. But the behavior slightly different than using [template](https://pkg.go.dev/text/template#hdr-Actions) action.

> If a directory called `.chezmoitemplates` exists, then all files in this directory are parsed as templates are available as templates with a name equal to the relative path to the `.chezmoitemplates` directory.
> https://www.chezmoi.io/reference/special-files-and-directories/chezmoitemplates/

As I understand from that statement, if files inside `.chezmoitemplates`, it is treated relative to the source root. So, only including the name is sufficient.

## To reproduce

Include template from `.chezmoitemplates` directory.

## Expected behavior

It should only use its name, didn't require relative to `.chezmoitemplates` directory as the specs stated.

## Output of command with the `--verbose` flag

```console
❯ cm execute-template '{{ template "fnm-download-url" . }}'
https://github.com/Schniz/fnm/releases/latest/download/fnm-arm64.zip%
❯ cm execute-template '{{ includeTemplate "fnm-download-url" }}'
chezmoi: template: arg1:1:3: executing "arg1" at <includeTemplate "fnm-download-url">: error calling includeTemplate: open /home/latipun/.local/share/chezmoi/home/fnm-download-url: no such file or directory
❯ cm execute-template '{{ includeTemplate ".chezmoitemplates/fnm-download-url" }}'
https://github.com/Schniz/fnm/releases/latest/download/fnm-macos.zip%

```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
# no error
```

</details>

**Comment by bradenhilton** [comment]
> As I understand from that statement, if files inside `.chezmoitemplates`, it is treated relative to the source root. So, only including the name is sufficient.
> ...
> ## Expected behavior
> 
> It should only use its name, didn't require relative to `.chezmoitemplates` directory as the specs stated.

https://www.chezmoi.io/reference/templates/functions/includeTemplate/:

> Relative paths are interpreted relative to the source directory.

---

```
<chezmoi sourceDir>
├─ .chezmoitemplates
│  ├─ fnm-download-url
│  ...
...
```

In this scenario, `fnm-download-url` is relative to `.chezmoitemplates`, not `<chezmoi sourceDir>`.

`.chezmoitemplates/fnm-download-url` is relative to `<chezmoi sourceDir>`.

**Comment by twpayne** [comment]
@mcexit [observed the same](https://github.com/twpayne/chezmoi/issues/2279#issuecomment-1235310718).

I think that searching first in `.chezmoitemplates` and otherwise looking in the source directory is reasonable behavior. In the future, I think there will be confusion between the `template` statement and the `includeTemplate` function, but I don't have any good solutions.

**Comment by bradenhilton** [comment]
To clarify, I agree with the change. I was just pointing out that the docs and the behavior were consistent.
