### ISSUE TITLE
Release less often

### ISSUE THREAD

**Issue by hwittenborn** [twpayne/chezmoi#2339]
## Is your feature request related to a problem? Please describe.

I maintain chezmoi on the [MPR](https://mpr.makedeb.org/packages/chezmoi), and it's quite easy for the package to go out of date due to how often new releases are made. There's also a bit of reluctance to have to update and test new versions as a result.

## Describe the solution you'd like

Releasing less often, maybe every month or couple weeks, would be nice.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by twpayne** [comment]
Thank you for packaging chezmoi :)

chezmoi follows semantic versioning with minor releases adding features and patch releases fixing bugs. Normally I release on a roughly two-week cadence, but when there are multiple users waiting on a feature or there is a significant bug fix that might cause more support load for me if not released then I will release more often.

I would recommend automating the process of version bumps in MPR for packages you trust. [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/chezmoi.rb) and [Chocolately](https://github.com/rasmuskriest/Chocolatey-Packages/tree/master/chezmoi) do this, and consequently there is no manual intervention required when a new version of chezmoi is released. You can use the [GitHub API to determine the latest release of chezmoi](https://docs.github.com/en/rest/releases/releases). Chocolately polls this every four hours.

Of course MPR is free to follow its own release schedule for its packages. Proposed updates should be automatic (see previous paragraph) and chezmoi includes a large number of tests that can also be run as part of the packaging process if desired.

P.S. The chezmoi MPR package includes a build dependency on `golang-go>=2:1.17`. Note that chezmoi requires Go version 1.18 or later. chezmoi's [documentation for package maintainers](https://www.chezmoi.io/developer/packaging/) may also be helpful.

**Comment by hwittenborn** [comment]
> I would recommend automating the process of version bumps in MPR for packages you trust.

My only problem with that is that if a package still breaks, such as a new release just changing how build files are layed out during installation, then I can't manually check that in an automated environment. I don't know how likely that'd be in practice, but I've generally moved away from doing stuff like that (I used to have some of my packages auto update, just not anymore), though with

> Homebrew and Chocolately do this, and consequently there is no manual intervention required when a new version of chezmoi is released

that's a good enough reason to allow it to be automated, I'll think about implementing it for myself.

> P.S. The chezmoi MPR package includes a build dependency on golang-go>=2:1.17. Note that chezmoi requires Go version 1.18 or later.

Thanks, I'll get that fixed!

The rapid releasing isn't the end of the world, if it's working for Homebrew and Chocolatey I'd say it's probably fine for me, at least with chezmoi. I think that's all the info I need, thanks!
