### ISSUE TITLE
Error running (`fork/exec`) bitwarden binary in termux

### ISSUE THREAD

**Issue by latipun7** [twpayne/chezmoi#2345]
## Describe the bug

Chezmoi error when my template has `bitwardenFields` template function. Error when trying to run bitwarden.

## To reproduce

- Login bitwarden
- Bootstrap dotfiles with `chezmoi init latipun7 --apply --verbose`
- Error happened

## Expected behavior

Chezmoi found `bw` in `$PATH` and able to run it. No error.

## Output of command with the `--verbose` flag

<details>
<summary>Output</summary>

_sorry for the screenshot, it seems the formatting is broken when I tried to copy and paste from Android_
![Screenshot_20220908-114909](https://user-images.githubusercontent.com/20012970/189049284-028f1bac-6ff0-4c77-a24b-211a550dc105.png)

</details>

## Output of `chezmoi doctor`

<details>

![Screenshot_20220908-125108](https://user-images.githubusercontent.com/20012970/189049612-81af5723-04d9-4ec7-9c58-4f8a66413b46.png)

</details>

## Additional context

If I run `bw`, it is found on path, even when I run full absolute path, it still can run.

<details>
<summary>Step</summary>

![image](https://user-images.githubusercontent.com/20012970/189049988-87e0a3cb-7187-4a83-839b-31936b2dc127.png)

</details>

**Comment by twpayne** [comment]
This is weird. The output from chezmoi doctor shows that chezmoi can run `git` but it can't run `bw`. I suspect there is something strange about the `bw` command on your device. What's the output of the following commands?

```console
$ ls -l /data/data/com.termux/files/usr/bin/bw
$ file /data/data/com.termux/files/usr/bin/bw
$ ldd /data/data/com.termux/files/usr/bin/bw
```

**Comment by latipun7** [comment]
![image](https://user-images.githubusercontent.com/20012970/189238071-19ce1621-51e0-48f9-9aea-7df70333385c.png)
but if I run `bw get item xxxxxxx` directly in terminal, it is fine and I get the result.

**Comment by twpayne** [comment]
OK, so `bw` cannot be executed directly as it is a JavaScript source file, not a executable file or something with a `#!` line. Have you (or Termux) configured your shell in some way to run JavaScript source files directly? chezmoi is certainly not able execute them.

The solution here is to use a wrapper script around the `bw` command that chezmoi can execute. You can point to the wrapper with the `bitwarden.command` configuration variable.

**Comment by latipun7** [comment]
bw.js has shebang on top of file `#!/usr/bin/env node`.
Now I think I migh know what causing the error. `git` is binary, while `bw` is script with that shebang. Termux didn't have `/usr/bin`. If I change shebang to `#!/data/data/com.termux/files/usr/bin/node`, the error go away.
It seems even using termux-exec (which is modifying traditional unix shebang to termux's, which is installed by default on termux), the shebang prefix not modified if script run from subproccess, but I didn't get error if I run `bw get item xxx` directly, because termux-exec is in effect.

This is indeed not chezmoi's bug. Thank you for your support and patience. 🙏

**Comment by twpayne** [comment]
[Looking at `termux-exec`](https://github.com/termux/termux-exec), it works by using `LD_PRELOAD` to hook in extra code around the `execve` function call. This only works for programs written in C, i.e. it doesn't work for chezmoi.
