### ISSUE TITLE
Fallback to EDITOR if VISUAL failed to start

### ISSUE THREAD

**Issue by poscat0x04** [twpayne/chezmoi#2357]
## Is your feature request related to a problem? Please describe.
Currently, when both `VISUAL` and `EDITOR` environment variables are set, `VISUAL` has absolute priority over `EDITOR`, that is, if `VISUAL` is present, then `EDITOR` will be ignored completely, even if the `VISUAL` editor does not exist or failed to start.

## Describe the solution you'd like
Chezmoi should fallback to `EDITOR` when `VISUAL` fails.

## Describe alternatives you've considered

1. Unset `VISUAL`
2. Config chezmoi to always use the `EDITOR` program

None of these work perfectly though since it is possible that one might want to sometimes use `VISUAL` (for example when accessing the machine through an graphical interface) and sometimes use `EDITOR` (for example when accessing the same machine through SSH).

**Comment by twpayne** [comment]
Thanks for the suggestion. If `$VISUAL` is not set correctly (e.g. it specifies a program that does not exist or fails to start) then really the solution is to either set `VISUAL` correctly, or specify the editor with the `edit.command` (which will override `$VISUAL`). If you want a different editor depending on whether a GUI is available or not, you can wrap the editor in a script which launches the preferred editor.
