### ISSUE TITLE
chezmoi from snap has no access to stdin and stdout

### ISSUE THREAD

**Issue by galou** [twpayne/chezmoi#2364]
## Describe the bug

The snap version of chezmoi (rev 517 with chezmoi v2.22.1) has no access to stdin and stdout

## To reproduce

```console
$ /snap/bin/chezmoi execute-template < modify_PrusaSlicer.ini.tmpl
chezmoi: read /dev/stdin: permission denied
```

```console
$ cat modify_PrusaSlicer.ini.tmpl | /snap/bin/chezmoi execute-template > modify_PrusaSlicer.bash
chezmoi: write /dev/stdout: permission denied
```
I discovered the issue when trying to use [chezmoi_modify_manager](https://github.com/VorpalBlade/chezmoi_modify_manager).

Interstingly, this works:
```console
$ /snap/chezmoi/517/chezmoi execute-template < modify_PrusaSlicer.ini.tmpl
#!/bin/bash
...
```

## Expected behavior

The expected behavior is obtained with `cat modify_PrusaSlicer.ini.tmpl | chezmoi execute-template` to print to stdout or `cat modify_PrusaSlicer.ini.tmpl | chezmoi execute-template | cat >  modify_PrusaSlicer.bash` to save to a file.

## Output of command with the `--verbose` flag

Same as without `--verbose`.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.22.1, commit 64b9c1fa7346526c17d5073827fe055dc46f6c09, built at 2022-09-04T23:00:07Z, built by goreleaser
ok        latest-version       v2.22.1
ok        os-arch              linux/amd64 (Ubuntu 20.04.5 LTS (Focal Fossa))
ok        uname                Linux pcgael3 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.19 (gc)
ok        executable           /snap/chezmoi/517/chezmoi
ok        upgrade-method       snap-refresh
ok        config-file          ~/.config/chezmoi/chezmoi.yaml, last modified 2022-09-07T15:26:21+02:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        shell-command        found /usr/bin/zsh
ok        shell-args           /usr/bin/zsh
ok        cd-command           found /usr/bin/zsh
ok        cd-args              /usr/bin/zsh
ok        edit-command         found /usr/bin/vim
ok        edit-args            /usr/bin/vim
info      diff-command         not set
ok        umask                002
ok        git-command          found /usr/bin/git, version 2.25.1
ok        merge-command        found ~/.local/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.19
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

I was trying to use [chezmoi_modify_manager](https://github.com/VorpalBlade/chezmoi_modify_manager) on a modified version to support Python 3.8 but I guess and hope that my changes are not what trigger the error because the scripts run correctly outside of chezmoi.

```console
$ chezmoi diff
chezmoi: fork/exec /tmp/698457680.PrusaSlicer.ini: exec format error
```
This time, using `/snap/chezmoi/517/chezmoi` doesn't help:
```console
$ /snap/chezmoi/517/chezmoi diff
chezmoi: fork/exec /tmp/1720462014.PrusaSlicer.ini: exec format error
```

**Comment by galou** [comment]
I realized that the error with `chezmoi diff` had another cause. It looks like the plugin is working, but the errors with stdin and stderr still persist.

**Comment by twpayne** [comment]
I'm unable to duplicate this on Ubuntu 22.04.01:

```console
$ which chezmoi
/snap/bin/chezmoi
$ chezmoi doctor | head -n 5
RESULT   CHECK                MESSAGE
ok       version              v2.22.1, commit 64b9c1fa7346526c17d5073827fe055dc46f6c09, built at 2022-09-04T23:00:07Z, built by goreleaser
ok       latest-version       v2.22.1
ok       os-arch              linux/amd64 (Ubuntu 22.04.1 LTS (Jammy Jellyfish))
ok       uname                Linux elitedesk 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ echo foo | chezmoi execute-template
foo
$ echo foo > bar
$ chezmoi execute-template < bar
foo
```

From scanning some snapcraft forum threads [1](https://forum.snapcraft.io/t/snappy-packaged-automation-snap-lxd-permission-denied-error/4955) [2](https://forum.snapcraft.io/t/permission-denied-when-installing-jq-using-snap/15030) [3](https://forum.snapcraft.io/t/failed-to-flush-stdout-permission-denied/485/2) it looks like some other programs might be confined by snap.

chezmoi already uses snap's classic confinement, and there is nothing more that chezmoi can do here. It may be that chezmoi_modify_manager is incompatible with chezmoi installed via snap and that your only option if you want to use the two together is to use an alternative method to install chezmoi.

**Comment by twpayne** [comment]
Hope that this is now resolved. Please re-open if needed.
