### ISSUE TITLE
Confused with .chezmoiignore

### ISSUE THREAD

**Issue by szinn** [twpayne/chezmoi#2366]
## What exactly are you trying to do?

I would like to have chezmoi manage files in a few subdirectories of "Library/Application Support" but I don't want to have to explicitly specify all of the subdirectories of Library to achieve this

## What have you tried so far?

I have tried using .chezmoiignore with
```
Library
!Library/Application\ Support
```

but that doesn't change anything and appears that all of Library is excluded.

What I would like to be able to say is
- exclude Library
- include Library/Application\ Support/xxx
- include Library/Application\ Support/yyy

in the .chezmoiignore file which would achieve what I want

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [X] Other, please give details. Searched google but there doesn't seem to be any examples of using the ! operator

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.22.1, commit 64b9c1fa7346526c17d5073827fe055dc46f6c09, built at 2022-09-03T11:57:36Z, built by Homebrew
ok        latest-version       v2.22.1
ok        os-arch              darwin/arm64
ok        uname                Darwin Odin.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64
ok        go-version           go1.19 (gc)
ok        executable           /opt/homebrew/bin/chezmoi
ok        upgrade-method       brew-upgrade
ok        config-file          ~/.config/chezmoi/chezmoi.yaml, last modified 2022-09-15T20:16:27-04:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        shell-command        found /opt/homebrew/bin/fish
ok        shell-args           /opt/homebrew/bin/fish
ok        cd-command           found /opt/homebrew/bin/fish
ok        cd-args              /opt/homebrew/bin/fish
ok        edit-command         found /usr/bin/vi
ok        edit-args            /usr/bin/vi
info      diff-command         not set
ok        umask                022
ok        git-command          found /opt/homebrew/bin/git, version 2.37.3
ok        merge-command        found /usr/bin/vimdiff
ok        age-command          found /opt/homebrew/bin/age, version 1.0.0
ok        gpg-command          found /usr/local/bin/gpg, version 2.2.34
info      pinentry-command     not set
ok        1password-command    found /usr/local/bin/op, version 2.7.1
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set```

</details>

## Additional context

Add any other context about the problem here.

**Comment by twpayne** [comment]
You don't need `.chezmoiignore` for this, just add the directories to chezmoi that you want chezmoi to manage, e.g.

```console
$ chezmoi add ~/Library/Application\ Support/xxx
$ chezmoi add ~/Library/Application\ Support/yyy
```

**Comment by szinn** [comment]
The other thing is that I would like chezmoi unmanaged to be empty so I know when something new shows up

**Comment by twpayne** [comment]
In that case you'll need to manually maintain a list of directories in `.chezmoiignore`.

Note that

```
Library
!Library/Application Support
```

does not work because as soon as chezmoi sees that the `Library` directory is excluded it does not recurse into it, and so never  sees `Library/Application Support`. Similarly, it is not possible for chezmoi to manage `Library/Application Support/xxx` but not `Library` or `Library/Application Support`. For `Library/Application Support/xxx` to exist, its parent directories must also exist, so managing `Library/Application Support/xxx` necessarily implies ensuring that both `Library` and `Library/Application Support` exist, so they are implicitly managed.

**Comment by szinn** [comment]
Thanks - I've worked around by having a few .chezmoiignore files. I might be asking too much, but it is nice to see a file that is new and to decide if I want to track it or not.
