### ISSUE TITLE
Passing all-overwrite flag to chezmoi update or chezmoi apply

### ISSUE THREAD

**Issue by dhruvinsh** [twpayne/chezmoi#2379]
## Is your feature request related to a problem? Please describe.

Just because I have working dotfiles system thanks to chezmoi, I am carelessly updated, trying new settings for some configs. When that config breakes I delete them and start them again. For example neovim, emacs etc config. Now when I knowingly delete the file, chezmoi does its job perfectly saying the current state is change. And with that, it also give me that nice bubble-tea option as well (very happy with that). But hey it just me thinking that I deteted the file an I wan tfull overwrite please. So passing somekind of `all-overwirte` flag make sense.

## Describe the solution you'd like

Is is possible to have `all-overwrite` flag passed to `chezmoi update` or `chezmoi apply`. 

ps. Hope that I am not missing the existance of this feature.

**Comment by twpayne** [comment]
[`--force`](https://www.chezmoi.io/reference/command-line-flags/global/#-force) ?

**Comment by dhruvinsh** [comment]
I knew that i was missing something here. I don't know why/how i missed it, even though now checking the history of commands i can see that I used it in the past (about 4 months ago).
