### ISSUE TITLE
"verify" does not recognize missing decrypted files, "update" reinstalls them

### ISSUE THREAD

**Issue by SebTM** [twpayne/chezmoi#239]
I tried to verify my process and the gpg-encryption is working well by deleting the decrypted files which are managed by chezmoi. After using "verify -nv" and even "apply -nv" nothing happen.

After running "update" the files appear again in the correct place and decrypted (in home dir). The files in "~/.local/share/chezmoi" were never touched by mysql and there is only the encrypted file located.

**Comment by twpayne** [comment]
Many thanks for the bug report! I will investigate.

**Comment by twpayne** [comment]
I think this is working as intended. The `-nv` arguments in the commands you are using are `--dry-run` (don't change anything in the destination directory) and `--verbose` (print what you're doing). The combination of `-n` and `-v` is verbose but does nothing.

Please re-open this issue if something is incorrect above.
