### ISSUE TITLE
Variable set in chezmoi.toml not loaded during first run

### ISSUE THREAD

**Issue by jacksonludwig** [twpayne/chezmoi#2414]
## Describe the bug

`chezmoi.toml` not evaluated before first `chezmoi init`. To manage multiple machines, the documentation states to place the following in `chezmoi.toml.tmpl`:
```
{{- $osid := .chezmoi.os -}}
{{- if hasKey .chezmoi.osRelease "id" -}}
{{-   $osid = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}
{{- end -}}

[data]
    osid = {{ $osid | quote }}
```

Then, in other configuration files and scripts, use the `$osid` variable to check what OS the user is on.

When using `chezmoi init` on a new machine where `$osid` has not yet been set, chezmoi fails to run since the `$osid` is an undefined variable.

## To reproduce

1. in your chezmoi directory, add a `chezmoi.toml.tmpl` with the above configuration.
2. create a test script which uses the `$osid` variable, e.g.
```
{{- if eq .osid "linux-ubuntu" }}

echo hello

{{- end }}
```
3. run `chezmoi apply`

## Expected behavior

The variable should be set and the config loaded before running the script.

## Output of command with the `--verbose` flag

*sorry I don't have this right now, I have to figure out a way to make run a mock init using a docker container or something*

## Output of `chezmoi doctor`

This output is from my linux machine, but I have seen the same issue on mac.

<details>

RESULT    CHECK                MESSAGE
ok        version              v2.21.1, commit 9f207f4f92429377387177d07e2eb55dcbc5ded5, built at 2022-08-29T21:16:43Z, built by goreleaser
warning   latest-version       v2.24.0
ok        os-arch              linux/amd64 (Ubuntu 22.04.1 LTS (Jammy Jellyfish))
ok        uname                Linux DESKTOP-BR97JV1 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.19 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-09-01T07:10:04-04:00
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
warning   suspicious-entries   ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        shell-command        found /bin/bash
ok        shell-args           /bin/bash
ok        cd-command           found /bin/bash
ok        cd-args              /bin/bash
ok        edit-command         found /usr/local/bin/nvim
ok        edit-args            /usr/local/bin/nvim
info      diff-command         not set
ok        umask                022
ok        git-command          found /usr/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keeper-command       keeper not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

</details>

**Comment by bradenhilton** [comment]
Are you running `chezmoi init` after editing the config template? It is required to rebuild the config file (`~/.config/chezmoi/chezmoi.toml`).

If I delete my existing config and use your example config template and script, then run `chezmoi init --apply` I receive no errors.

**Comment by jacksonludwig** [comment]
I see. Is there a difference in `chezmoi init --apply` from scratch and doing `chezmoi init <git_repo_url_here>`? When using a github URL, I observe the issue.

**Comment by bradenhilton** [comment]
Can you post the contents of the config template and file(s) from the git repo that give the error? Redact personal information if needed.

**Comment by twpayne** [comment]
Closing due to lack of response. Please re-open if needed.
