### ISSUE TITLE
`--include` flag not working for some target types

### ISSUE THREAD

**Issue by sm1999** [twpayne/chezmoi#2427]
## Describe the bug

I wanted to list files managed by chezmoi of target type encrypted. 
Running `chezmoi managed --include encrypted` does not yield any output.
After some testing, I found that files, dirs, scripts, remove, and symlinks target types are working when passed to the `--include` flag.
But encrypted and externals target types are not working.

 Running `chezmoi managed --include files,encrypted` works as expected. showing normal and encrypted  target types.
Also preceding target types with no works for all target types.

## To reproduce

Consider i have three files normal_file, encrypted_file, script_file.

1) run `chezmoi managed --include encrypted`
2) Output will be empty
3) run `chezmoi managed --include files,encrypted`
4) Output will contain normal_file, encrypted_fire. script_file is excluded.

## Expected behavior

`chezmoi managed --include encrypted` should show files with target type encrypted

## Output of command with the `--verbose` flag

```console
~ ❯ chezmoi managed --include=encrypted --verbose
~ ❯
(chezmoi exit with exit code 0)
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              dev
warning   latest-version       v2.24.0
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux sm1999-arch 5.15.72-1-lts #1 SMP Wed, 05 Oct 2022 12:15:15 +0000 x86_64 GNU/Linux
ok        go-version           go1.19.2 (gc)
ok        executable           ~/dev/Github/chezmoi/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.yaml, last modified 2022-09-03T22:49:28+05:30
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found /usr/local/bin/nvim
ok        edit-args            /usr/local/bin/nvim
ok        git-command          found /usr/bin/git, version 2.38.0
ok        merge-command        found /usr/local/bin/nvim
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        age-command          found /usr/bin/age, version 1.0.0
ok        gpg-command          found /usr/bin/gpg, version 2.2.39
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.1
ok        keepassxc-db         database.kdbx is a file
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

none

**Comment by twpayne** [comment]
Thank you for spotting this and opening this issue :) #2451 is a possible fix.

This bug exists because I combined both target entry types (e.g. whether the target is a file or a directory or a symlink) with source entry types (e.g. whether the source was encrypted or came from an external). Fundamentally, these are two orthogonal properties of a target, and combining the two leads to complications. For example, only files can be encrypted, but what should `chezmoi managed --include=encrypted --exclude=files` print?

#2451 is an attempt to fix this by propagating source state properties (namely `encrypted` and `external`) to the target state so that the include/exclude check can be performed on the target state. I'm sure I missed some cases.

**Comment by sm1999** [comment]
Thank you for the detailed explanation!

Have you considered adding filtering by filenames or paths? Often times I want to exclude a file. e.g file using a password manager template function as these files do not change often and I have to type the password for accessing secrets every time I run chezmoi status/diff/apply.
If it can be considered should I open a new issue?

**Comment by twpayne** [comment]
> Have you considered adding filtering by filenames or paths? Often times I want to exclude a file. e.g file using a password manager template function as these files do not change often and I have to type the password for accessing secrets every time I run chezmoi status/diff/apply.

In this case I would consider changing to a password manager that does not require you to type a password every time :) Many password managers offer a time-limited login via a session token stored in an environment variable or run a background process that persists the login.

It would be possible to add filtering based on filenames, but you'd have to remember which files use password manager template functions, which would be quite tiresome.
