### ISSUE TITLE
Suggestion: `get.chezmoi.io` as an alternative to `chezmoi.io/get`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#2430]
I'm following up #1816, because I believe I have found an alternative solution.

1. Create the `chezmoi/get.chezmoi.io` repository, configure it to deploy static HTML files as any normal GitHub page.
2. Configure the subdomain for it in the repo settings so it gets deployed to `get.chezmoi.io`.
3. Add the script to the repo and name it `index.html`, even though it's not a HTML.

Example:

https://github.com/felipecrs/get.felipecrs.com

```console
$ curl -fsSL get.felipecrs.com
#!/bin/sh

echo "Hello world!"

$ curl -fsSL get.felipecrs.com | sh
Hello world!
```

The only caveat is that GitHub will serve it using the wrong `Content-Type`:

```console
$ curl -fsSvL get.felipecrs.com 2>&1 | grep Content-Type
< Content-Type: text/html
```

This has no effect for the use case (`curl -fsSL get.chezmoi.io`), but do makes the page look weird if opened in the browser (https://get.felipecrs.com). I don't think it matters though.

For automating the update of the `index.html` once you change the script in the main repo, you can use GitHub Actions, and I can create the workflow for you if you like the idea.

What do you think? Feel totally free to say no, of course. :)

**Comment by twpayne** [comment]
This is a great idea, thank you! Please do create the workflow.

**Comment by felipecrs** [comment]
Thanks a lot, @twpayne!
