### ISSUE TITLE
Questions about `.chezmoiexternal`

### ISSUE THREAD

**Issue by xfzv** [twpayne/chezmoi#2449]
## What exactly are you trying to do?

I'm in the process of starting to use `chezmoi` to manage my dotfiles. I cannot figure how to solve the issue I'm going to try to describe.

I use a significant amount of dotfiles from third-party repositories I don't control, mostly mpv plugins such as [uosc](https://github.com/tomasklaen/uosc) or [thumbfast](https://github.com/po5/thumbfast). These plugins usually consist of a `.lua` and a `.conf` files, which have to be in `$HOME/.config/mpv/{scripts,script-opts}` directory.

For now, what I do is that I clone all these repositories in a single directory and symlink the files I want to use to my `$HOME` directory where they're supposed to be. I regularly run `git pull` recursively in all the repos to get the latest updates, commit my changes (mostly to the `.conf` files but some plug-ins don't have any, so I have to edit the `.lua` file instead) directly in the repos and sometimes deal with merge conflicts.

This method works for me, but the main issue is that it wouldn't work on another machine due to the symlinks approach (which I dislike regardless).

I would like to manage these dotfiles with `chezmoi` like the other ones, but still being able to keep them under version control like now.

## What have you tried so far?

[Include a subdirectory from a git-repository](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-from-a-git-repository) seems to be the way to go, but I'm not sure whether it doesn't cover this use case or if I don't know how to properly use it.

Should I use this for example ?

```yaml
# .chezmoiexternal

"external-git-repos":
  type: "git-repo"
  url: "https://github.com/tomasklaen/uosc"
  refreshPeriod: "168h"
```

In this case, which location am I supposed to use? all the plugins should go to `~/.config/mpv/scripts` and the config files should go to `~/.config/mpv/script-opts`. Having `~/.config/mpv/{repo1,repo2,repo3}` wouldn't work. It would work if each plugin could have it's own directory, which isn't the case.

Plus, some repositories don't have the `.lua` and `.conf` files in the `scripts` and `script-opts` directories, they're just at the root of the Git repo. Hence the need to use symlinks so that they're placed in the correct directories. Would I have to use a single directory and also use symlinks?

I know I could use `file` instead of `git-repo` with the absolute path for each file, but I would completely miss the VCS aspect, wouldn't I?

What about the synchronization between machines? let's say I keep committing my changes in these external repositories because I want to keep these files under version control. Should `external-git-repos` directory (or whatever path should be used) be managed by chezmoi so that I could `git push` from the current machine and `git pull` from the other in order to get all the Git changes and thus avoid managing the external Git repositories on every single machine?

I'm kind of lost, any idea on how to organize all of this is much appreciated.

Thanks!

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details: I explored [GitHub](https://github.com/search?q=chezmoi+type%3A+%22git-repo%22&type=Code) to see how people use `git-repo` but couldn't find any repo with some mpv plugins.

**Comment by bradenhilton** [comment]
In this case, you should not use the entire repo as the external, just the files you need.

As an aside, there are potential security concerns with using the main branch. If the repo uses releases (as `tomasklaen/uosc` does), you could use those if you don't mind updating the `.chezmoiexternal` file when there is a new release. Or you could use a permalink to the current commit on the main branch and update that periodically.

For example, I have the following external as a template at `<chezmoi source-path>/.chezmoitemplates/mpv/scripts/external.toml`:

```
["createchapter.lua"]
type = "file"
url = "https://raw.githubusercontent.com/shinchiro/mpv-createchapter/8dd33e2debbcb963a195ec1371e02c85b49e7faa/createchapter.lua"

["progressbar.lua"]
type = "file"
url = "https://raw.githubusercontent.com/torque/mpv-progressbar/build/progressbar.lua"

["mpv_thumbnail_script_client_osc.lua"]
type = "file"
url = "https://github.com/marzzzello/mpv_thumbnail_script/releases/download/0.4.8/mpv_thumbnail_script_client_osc.lua"

{{ range $i := until ((ceil (div .cpu.threads 4)) | int) -}}
[{{ (print "mpv_thumbnail_script_server_" (add1 $i) ".lua") | quote }}]
type = "file"
url = "https://github.com/marzzzello/mpv_thumbnail_script/releases/download/0.4.8/mpv_thumbnail_script_server.lua"

{{ end -}}

["sub-select.lua"]
type = "file"
url = "https://raw.githubusercontent.com/CogentRedTester/mpv-sub-select/b617cf9183e92619977d0512500ed5fd3a52b2da/sub-select.lua"
```

You could probably combine the above approach with the [gitHubLatestRelease](https://www.chezmoi.io/reference/templates/github-functions/gitHubLatestRelease/) template function.

I then place `{{ template "mpv/scripts/external.toml" . }}` in the following locations:

- `<chezmoi source-path>\AppData\Roaming\mpv\scripts\.chezmoiexternal.toml` for Windows
- `<chezmoi source-path>/private_dot_config/mpv/scripts/.chezmoiexternal.toml` for Linux/Mac

You probably don't need to get the plugin config files as externals, but you can use the same approach.

**Comment by bradenhilton** [comment]
>   1. I noticed the files added this way are now listed if I run `chezmoi managed`, as expected. However, since they were added via a template, If I run `chezmoi edit ~/.config/mpv/scripts/uosc.lua` for example, my `$EDITOR` opens blank and the current tab is called `create_`:
> 
> Does it mean I could only use `$EDITOR ~/.config/mpv/scripts/uosc.lua` to edit these kind of dotfiles and therefore not being able to manage them via `chezmoi` source directory? as a result, it seems that after any `chezmoi apply -R` (or `chezmoi apply` after the time defined in `refreshPeriod` is elapsed), if the file from upstream has been updated, I would only get this:
> 
> https://github.com/twpayne/chezmoi/blob/964810aa28319a720fe800b6e6b0a1934e2c8056/pkg/cmd/config.go#L899-L906
> 
> Which means no VCS at all, unless I'm mistaken?

What changes are you making to `uosc.lua`? uosc accepts a `uosc.conf` file, no?

If they are fixes or feature changes, perhaps consider opening a PR to see if they can be implemented for all users.

You could also maintain a personal fork of the plugin with the relevant changes and use this in the external.

If you can't do either of those, perhaps you'd be better off using a script which patches the files as needed. It isn't mandatory to use externals if they don't fit your needs. :)

> > As an aside, there are potential security concerns with using the main branch. If the repo uses releases [..]
> 
> Not sure what you mean by "_potential security concerns_", could you please elaborate? I've been using the files from the main branch of all my mpv plugins for years and never had any issue.

You're accepting any and all changes to the master/main branch, if someone managed to push a commit with malicious changes (either deliberately or by having their account compromised) you wouldn't be able to stop them, chezmoi will happily accept the new changes, and you may not know that it happened until after you've already run the plugin.

How likely is this? I suppose that depends on how many users with the relevant privileges a particular plugin has. I'm also not sure how much damage a plugin can cause to the host machine. Permalinking takes basically no additional time and prevents this, with the downside being that you have to periodically update the links in the external file.

> Plus, [tomasklaen/uosc](https://github.com/tomasklaen/uosc/) is one of the very few plug-ins I use which makes use of releases, I'd say 98% of the others don't.

This is true, but as you can see in my example above, I download `mpv-sub-select` using a permalink to a specific commit which I update periodically.

**Comment by bradenhilton** [comment]
> As I said in the first message, some plug-ins don't accept a config file and if you want to edit some settings, it should be done directly inside the `.lua` file, like [this one](https://github.com/oltodosel/mpv-scripts/blob/master/total_playtime.lua#L5-L8). But I mostly edit actual `.conf` files.
> 
> > You could also maintain a personal fork of the plugin with the relevant changes and use this in the external.
> 
> Interesting idea, even if it feels a bit overkill just to tweak some settings. But I could definitely do that.

For plugins which are actively maintained, consider asking the author to add support for `.conf` files, or at the very least support for named `script-opts`, so they can be configured in the main `mpv.conf` via [`--script-opts`](https://mpv.io/manual/stable/#options-script-opts). This would be a useful change for all users of the plugin, and [isn't terribly difficult to implement](https://mpv.io/manual/stable/#mp-options-functions).

That said, I am aware that some plugins are no longer maintained. This is one of the reasons why I recommended maintaining a fork.

> > If they are fixes or feature changes, perhaps consider opening a PR to see if they can be implemented for all users.
>
> I'm not a developer so I won't implement features or operate massive changes to an existing plug-in. Although the config files receive less commits, they still do. So I'd rather not giving up about the idea of using version control for these files.

Even if you aren't a developer, the documentation linked above is quite straight forward. If you copy the example and change the name and options you're basically done.

Untested, but the script you linked would be something like:

<details>
<summary><code>total_playtime.lua</code></summary>

```lua
--~ Shows total playtime of current playlist.
--~ If number of items in playlist didn't change since last calculation - it doesn't probe files anew.
--~ requires ffprobe (ffmpeg)

require 'mp.options'
local options = {
    key_binding = 'F12',
    save_probed = true,
    saved_probed_filename = '~~/home/scripts/total_playtime.list',
}
read_options(options, 'total_playtime')

-----------------------------------
local assdraw = require('mp.assdraw')
local osd_w, osd_h, aspect = mp.get_osd_size()

saved_probed_filename = mp.command_native({'expand-path', options.saved_probed_filename})

local utils = require 'mp.utils'

function disp_time(time)
	local hours = math.floor(time/3600)
	local minutes = math.floor((time % 3600)/60)
	local seconds = math.floor(time % 60)
	
	return string.format("%02d:%02d:%02d", hours, minutes, seconds)
end

function setContains(set, key)
	return set[key] ~= nil
end
playlist = {}
playlist_total = -1

function total_time()
	if #playlist ~= playlist_total then
		if options.save_probed then
			if io.open(saved_probed_filename, "rb") then
				probed_file = {}
				for line in io.lines(saved_probed_filename) do
					for k, v in line:gmatch("(.+)\t(.+)") do
						probed_file[k] = v
					end
				end
			else
				probed_file = {}
			end
		end
		
		local cwd = utils.getcwd()
		for pl_num, f in ipairs(mp.get_property_native("playlist")) do
			f = utils.join_path(cwd, f.filename)
			-- attempt basic path normalization
			if on_windows then
				f = string.gsub(f, "\\", "/")
			end
			f = string.gsub(f, "/%./", "/")
			local n
			repeat
				f, n = string.gsub(f, "/[^/]*/%.%./", "/", 1)
			until n == 0
			
			f = string.gsub(f, "\"", "\\\"")
			
			if options.save_probed and probed_file[f] then
				fprobe = probed_file[f]
			else
				fprobe = io.popen('ffprobe -v quiet -of csv=p=0 -show_entries format=duration "'.. f .. '"'):read()
				
				if fprobe and options.save_probed then
					file = io.open(saved_probed_filename, "a")
					file:write(f .. '\t' .. fprobe .."\n")
					file:close()
				end
			end
			if ( tonumber(fprobe) ~= nil) then
				playlist[#playlist + 1] = { f, tonumber(fprobe), pl_num }
			end
			
			
			local ass = assdraw:ass_new()
			ass:new_event()
			ass:an(3)
			ass:append(string.format("Calculating: %s/%s", #playlist, mp.get_property("playlist-count")))
			mp.set_osd_ass(osd_w, osd_h, ass.text)

			-- mp.osd_message(string.format("Calculating: %s/%s", #playlist, mp.get_property("playlist-count")))
		end
		playlist_total = #playlist

        mp.set_osd_ass(0, 0, "{}")
	end
	
	total_dur = 0
	played_dur = mp.get_property_number("time-pos")
	current_pos = mp.get_property_number("playlist-pos-1", 0)
	
	for i, fn in pairs(playlist) do
		if fn[2] ~= nil then
			total_dur = total_dur + fn[2]
			if i < current_pos then
				played_dur = played_dur + fn[2]
			end
		end
	end

	osdm = string.format(" %s / %s (%s%%) \n %s / %s (%.2fx) \n %s/%s",
			disp_time(played_dur),
			disp_time(total_dur),
			math.floor(played_dur*100/total_dur),
			disp_time(played_dur/mp.get_property_number("speed")),
			disp_time(total_dur/mp.get_property_number("speed")),
			mp.get_property_number("speed"),
			mp.get_property("playlist-pos-1"),
			mp.get_property("playlist-count")
		)
	
	mp.osd_message(osdm)
end

mp.add_forced_key_binding(options.key_binding, "total_time", total_time)

--------------------------------------------------
--------------------------------------------------
--------------------------------------------------

function sort_playlist_to_0()
	sort_playlist(1)
end

reverse = 0
function sort_playlist(start_0)
	total_time()

	table.sort(playlist, function (left, right)
		-- print(left[2])
		if reverse == 0 then
			return left[2] < right[2]
		else
			return left[2] > right[2]
		end
	end)

	if reverse == 0 then
		reverse = 1
	else
		reverse = 0
	end

	out = ''

	for i, f in pairs(playlist) do
		if f[2] ~= nil then			
			for i2, f2 in ipairs(mp.get_property_native("playlist")) do
				if f2.filename == f[1] then
					mp.commandv('playlist-move', i2 - 1, i - 1)
					
					if f2.filename == mp.get_property("path") then
						-- out = string.format('%s>>%s\t\t%s\n', out, disp_time(f[2]), f[1]:gsub('.+/', ''))
						out = string.format('%s%s\t\t%s\n', out, disp_time(f[2]), f[1]:gsub('.+/', ''))
					else
						out = string.format('%s%s\t\t%s\n', out, disp_time(f[2]), f[1]:gsub('.+/', ''))
					end
					break
				end
			end
		end
	end

	if start_0 ~= nil then
		mp.set_property('playlist-pos', 0)
		os.execute('sleep .1')
	end
	mp.osd_message(out, 3)
end

mp.add_forced_key_binding('KP4', "sort_playlist", sort_playlist)
mp.add_forced_key_binding('shift+KP4', "sort_playlist_to_0", sort_playlist_to_0)

```

</details>
