### ISSUE TITLE
interpreter config lost in chezmoi.yaml on windows

### ISSUE THREAD

**Issue by CrystalMethod** [twpayne/chezmoi#2490]
## Describe the bug

I need to define an interpreter to get my shellscripts (.sh.tmpl) executed on Windows.

#### .local/share/chezmoi/.chezmoi.yaml.tmpl
```.yaml
...
interpreters:
  sh:
    command: bash
...
```

after running `chezmoi init`

#### .config/chezmoi/chezmoi.yaml
```yaml
...
<the interpreters path has been removed .. all other settings have been applied>
...
```

and when running `chezmoi apply` the shellscripts result in error "..is not a valid Win32 application". As soon as I re-add these settings to `chezmoi.yaml` the scripts will be executed.

#### .local/share/chezmoi/.chezmoi.yaml.tmpl
```.yaml
...
interpreters:
  sh:
    command: bash
...
```

after running `chezmoi init`

#### .config/chezmoi/chezmoi.yaml
```yaml
...
interpreters:
  sh:
    command: bash
...
```
the settings have been applied.

I'm somewhat lost. Did I miss something?

**Comment by twpayne** [comment]
I don't see an `interpreters` section in [your config file template](https://github.com/CrystalMethod/dotfiles/blob/401269c925ea07de9737f196f572bb6cac881343/.chezmoi.yaml.tmpl).  Is it possible that your config file is being overwritten when you run `chezmoi init`?

Also, please do complete the bug report template completely when reporting a bug. Information like the output of `chezmoi doctor` and the output of the command with the `--verbose` flag helps everyone find the solution to your problem faster.

**Comment by CrystalMethod** [comment]
I apologize for disturbing you about this. The cause of my described problem was quite simple: I moved the dotfiles git repo to another location over time. but `sourceDir` still pointed to the old location. There the new settings for `interpreters` did not exist, which made it feel like my settings were lost. Correcting `sourceDir` thus solved the problem and the `interpreters` settings are applied correctly. Thank you!
