### ISSUE TITLE
Support for XDG base and user directories

### ISSUE THREAD

**Issue by Marathon2112** [twpayne/chezmoi#2496]
A typical use case would be to back up templates in the XDG_TEMPLATES_DIR and deploy them on a machine with a different locale. The source directory could be `~/Templates`, whereas the destination directory could be, say, `~/Modèles`. They are conceptually the same folder, but `chezmoi` would create a `~/Templates` folder on the second machine instead of using the correct locale.

**Comment by twpayne** [comment]
I'm sorry, I don't understand your request.

Environment variables like `$XDG_TEMPLATES_DIR` are already available in chezmoi's templates through the [`env` template function](http://masterminds.github.io/sprig/os.html).

What changes do you want to see to chezmoi?

**Comment by Marathon2112** [comment]
My apologies, I had not taken a look at all the sprig functions available. I guess then one could then create a template for moving the files to their correct location using `env XDG_TEMPLATES_DIR`.

**Comment by twpayne** [comment]
Ah, storing files in different locations on different machines is a bit tricky at the moment. There's an [FAQ entry with suggestions](https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#handle-different-file-locations-on-different-systems-with-the-same-contents).

#2273 should eventually make this easier, but I haven't started implementing yet.

**Comment by twpayne** [comment]
Hopefully this is now sorted (pending the #2273 enhancement, of course). Please re-open if needed.
