### ISSUE TITLE
Better error message for external refresh expecting git repository

### ISSUE THREAD

**Issue by dhruvinsh** [twpayne/chezmoi#2500]
## Is your feature request related to a problem? Please describe.

I use git repo for external directive and some time I manually and knowingly delete the managed config and create my own folder and config. Now next time when I run `chezmoi apply -R` it will throw the error, which is expected but the error is too generic.
```
chezmoi apply -R
fatal: not a git repository (or any of the parent directories): .git
chezmoi: exit status 128
```

## Describe the solution you'd like
Is it possible to make error message more verbose to show where the error happen (like which directory)? 

## Describe alternatives you've considered
I have to run `chezmoi apply -R --debug` to find where the issue lies.

**Comment by halostatue** [comment]
I don’t currently use externals (I probably should…), but it feels like we *should* be able to include the external for which the refresh is failing.
