### ISSUE TITLE
OS detection error - hasKey and index of .chezmoi.osRelease

### ISSUE THREAD

**Issue by gadams999** [twpayne/chezmoi#2502]
## What exactly are you trying to do?

I upgraded chezmoi to version:

```
chezmoi --version
chezmoi version v2.25.0, commit b3a8879e30a20134c9bef48646055e57aa78d8c5, built at 2022-10-13T14:01:32Z, built by goreleaser
```

and started to see my OS detection fail. I had been using this for detecting Linux variants:

```
{{ if (index .chezmoi.osRelease "id") -}}
{{   if eq .chezmoi.osRelease.id "raspbian" -}}
echo "Installing Raspberry Pi OS specific packages"
```

but then started to get errors about nil values (from the first line above):

```
chezmoi: template: run_once_before_10_install_packages.sh.tmpl:70:7: executing "run_once_before_10_install_packages.sh.tmpl" at <index .chezmoi.osRelease "id">: error calling index: index of untyped nil
```

Reading the docs, I saw the reference to using `hasKey` to check for `id` and then create an `osid` entry in my config file:

```
{{- $osid := .chezmoi.os -}}
{{- if hasKey .chezmoi.osRelease "id" -}}
{{-   $osid = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}
{{- end -}}

[data]
    osid = {{ $osid | quote }}
```

Now when trying `chezmoi init` I get the error:

```chezmoi: template: chezmoi.toml:7:22: executing "chezmoi.toml" at <.chezmoi.osRelease>: wrong type for value; expected map[string]interface {}; got interface {}
```

Below is the output from `--verbose` and my redacted data when running this on macOS.

**Looking for guidance on why `hasKey` errors out (details from `chezmoi data` below).**

## What have you tried so far?

1. Use the `hasKey` approach in my `.tmpl` files (with the same error above from the config file when running `chezmoi init`. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose apply
chezmoi: template: run_once_before_10_install_packages.sh.tmpl:70:7: executing "run_once_before_10_install_packages.sh.tmpl" at <index .chezmoi.osRelease "id">: error calling index: index of untyped nil
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.25.0, commit b3a8879e30a20134c9bef48646055e57aa78d8c5, built at 2022-10-13T14:01:32Z, built by goreleaser
ok        latest-version       v2.25.0
ok        os-arch              darwin/amd64
ok        uname                Darwin redacted 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
ok        go-version           go1.19.2 (gc)
ok        executable           ~/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-10-27T14:44:00-07:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
ok        edit-args            code --wait
ok        git-command          found /usr/bin/git, version 2.37.0
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        age-command          found /usr/local/bin/age, version 1.0.0
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
warning   bitwarden-command    found /usr/local/bin/bw, cannot parse version from Could not find dir, "~/Library/Application Support/Bitwarden CLI"; creating it instead.
Could not find data file, "~/Library/Application Support/Bitwarden CLI/data.json"; creating it instead.
2022.6.2
info   gopass-command      gopass not found in $PATH
info   keepassxc-command   keepassxc-cli not found in $PATH
info   keepassxc-db        not set
info   keeper-command      keeper not found in $PATH
info   lastpass-command    lpass not found in $PATH
info   pass-command        pass not found in $PATH
info   passhole-command    ph not found in $PATH
info   vault-command       vault not found in $PATH
info   secret-command      not set
```

</details>

## Additional context

```console
$ chezmoi data
{
  "chezmoi": {
    "arch": "amd64",
    "args": [
      "chezmoi",
      "data"
    ],
    "cacheDir": "/Users/xxx/.cache/chezmoi",
    "configFile": "/Users/xxx/.config/chezmoi/chezmoi.toml",
    "executable": "/Users/xxx/bin/chezmoi",
    "fqdnHostname": "redacted",
    "gid": "1896053708",
    "group": "",
    "homeDir": "/Users/xxx",
    "hostname": "redacted",
    "kernel": null,
    "os": "darwin",
    "osRelease": null,
    "sourceDir": "/Users/xxx/.local/share/chezmoi",
    "uid": "481389813",
    "username": "xxx",
    "version": {
      "builtBy": "goreleaser",
      "commit": "b3a8879e30a20134c9bef48646055e57aa78d8c5",
      "date": "2022-10-13T14:01:32Z",
      "version": "2.25.0"
    },
    "windowsVersion": null,
    "workingTree": "/Users/xxx/.local/share/chezmoi"
  },
  "email": "redacted",
  "encryption": "age",
  "environment": "work",
  "identity": "~/.age_chezmoi.txt",
  "name": "redacted",
  "recipient": "redacted"
}

**Comment by bradenhilton** [comment]
I think this is because `.chezmoi.osRelease` is `null`.

`/etc/os-release` does not exist on `darwin`, or at least it doesn't exist on my MBP:

```console
❯ /etc/os-release
zsh: no such file or directory: /etc/os-release
```

**Comment by gadams999** [comment]
Agreed that there is no `os-release` file. I would think since `.chezmoi.osRelease` is null and doesn't have the key, that shouldn't blow up? If so, it makes is challenging to have template logic that spans Windows, macOS, and Linux.

What's really weird is I had no issues a couple months ago the last time I did a `chezmoi apply`. Only after the update to 2.25.0 is when I saw the error. I may look to downgrade to a previous version and see that changes anything.

**Comment by bradenhilton** [comment]
You can just check if `.chezmoi.osRelease` isn't `null` by `and`ing it: `{{- if and (.chezmoi.osRelease) (hasKey .chezmoi.osRelease "id") -}}`:

```console
❯ chezmoi execute-template '{{- $osid := .chezmoi.os -}}{{- if hasKey .chezmoi.osRelease "id" -}}{{- $osid = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}{{- end -}}{{- $osid -}}'
chezmoi: template: arg1:1:50: executing "arg1" at <.chezmoi.osRelease>: wrong type for value; expected map[string]interface {}; got interface {}

❯ chezmoi execute-template '{{- $osid := .chezmoi.os -}}{{- if and (.chezmoi.osRelease) (hasKey .chezmoi.osRelease "id") -}}{{- $osid = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}{{- end -}}{{- $osid -}}'
windows
```

@twpayne We should probably add something like this to the template. I can do this tomorrow if you want.

**Comment by halostatue** [comment]
@twpayne, @bradenhilton this looks like a regression from 2.24.0 to 2.25.0.

```console
❯ for d in 3 4 5
      echo 2.2$d.0 && ./chezmoi-2.2$d.0 execute-template '{{ .chezmoi.osRelease | toJson }}' -W . | jq .
  end
2.23.0
{}
2.24.0
{}
2.25.0
null
```

**Comment by bradenhilton** [comment]
@halostatue Interesting. Would you be willing to try a bisect?

Re: `osRelease`, it's populated by reading `/etc/os-release` or `/usr/lib/os-release`:

https://github.com/twpayne/chezmoi/blob/3b95c7e8d8add5001db98c2a2aa38774c522b681/pkg/chezmoi/data.go#L53-L73

Are you suggesting we manually populate it with equivalent data if this isn't possible?

**Comment by halostatue** [comment]
I’m doing a code comparison now to investigate.

I am suggesting manually populating it with equivalent data. There are alternate keys for some of these (e.g., `windowsVersion`), but it feels like we could *probably* shift some of this into interesting places on a more regular basis. I have a bunch of functions I’ve written for `fish` that do this for macOS.

**Comment by halostatue** [comment]
I know which commit is causing this, but I can’t *quite* figure out why the previous commit returns `{}` and the suspect commit returns `null`.

**Comment by halostatue** [comment]
Found it…and it’s a doozy. Specifically, this is because of the JSON roundtrip in `func (c *Config) getTemplateDataMap() map[string]any`.

**Comment by bradenhilton** [comment]
Specifically https://github.com/twpayne/chezmoi/commit/964810aa28319a720fe800b6e6b0a1934e2c8056 if I'm not mistaken.
