### ISSUE TITLE
Make submodule checkout optional

### ISSUE THREAD

**Issue by breneser** [twpayne/chezmoi#2508]
## Is your feature request related to a problem? Please describe.

I have private submodules in a a public dotfiles repo. I setup my keys and logins using bitwarden and I install bitwarden with after scripts in the main public repo. With chezmoi trying to checkout submodule I am being asked for a password to checkout the submodules.

## Describe the solution you'd like

If there was a flag to not checkout submodules i would be able to setup my password manager and keys and then checkout submodules without the need to enter git host password, but just using my Bitwarden password.

**Comment by twpayne** [comment]
With #2511 and #2512, you can now pass the `--recurse-submodules=false` flag to `chezmoi init` and `chezmoi update`. You can also set the `update.recurseSubmodules` configuration variable to `false` to avoid having to pass the flag to `chezmoi update` each time.

**Comment by breneser** [comment]
@twpayne Can I ask when this is likely to be released ?

**Comment by twpayne** [comment]
Probably in the next couple of days. I need to check the behavior of #2473 first.

**Comment by breneser** [comment]
That's great. Also thanks for the great tool.
