### ISSUE TITLE
Fossil back-end

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [twpayne/chezmoi#2577]
Any chance of getting [Fossil](https://www.fossil-scm.org/) added as a back-end option?

I have a preference for Fossil.  Maybe I'm just weird.

Also, having a read of the Fossil projects [Fossil Versus Git](https://www.fossil-scm.org/home/doc/trunk/www/fossil-v-git.wiki) document, with thoughts of dotfiles in the back of one's head really highlights some of the advantages.  The biggest of which: _single binary application_ installable into user-space.

This means never worrying about getting git installed on your target machine if it doesn't exist.  chezmoi can just provision fossil into, for example, $XDG_DATA_HOME/bin (because this is almost universally included in default $PATH.)  This is especially important for remote machines where users do not have admin privileges.

**Comment by ParaplegicRacehorse** [comment]
Understood.  Close this request, then, unless others chime in.  I'm fairly confident I can manage my dots with _chezmoi_ and my repo separately with _fossil_, seeing as how I've been doing just that ever since I first set up _chezmoi_.

**Comment by twpayne** [comment]
Thinking about this more, being able to override what `chezmoi update` does helps a lot. See #2580.

**Comment by ParaplegicRacehorse** [comment]
Wow!  This looks great; and happened really fast.  It's a poor time for me to test it out and, when I do, you'll get feedback if it does not work as expected.

Thanks a bunch!
