### ISSUE TITLE
Support for SSH keys from other services

### ISSUE THREAD

**Issue by sochotnicky** [twpayne/chezmoi#2583]
## Is your feature request related to a problem? Please describe.

Currently [chezmoi documents](https://www.chezmoi.io/user-guide/manage-different-types-of-file/#populate-sshauthorized_keys-with-your-public-ssh-keys-from-github) usage of Github authorized SSH keys for initialization.

I looked at the code and noticed that this actually uses github API to query the keys.  However you can also just request URL such as:
https://github.com/sochotnicky.keys

To get approved SSH keys. Some other services provide the same. For example:
https://codeberg.org/sochotnicky.keys
https://gitlab.com/sochotnicky.keys

## Describe the solution you'd like

I'd like to add a more generic support (a new generic template function) for using keys from these sources. I am happy to create a PR with the change and go through the review process if this would be acceptable in principle.

Obviously a similar warning would be added to the function same as https://www.chezmoi.io/reference/templates/github-functions/gitHubKeys/ 

## Describe alternatives you've considered

Just doing things manually :-)

## Additional context

None

**Comment by twpayne** [comment]
> I'd like to add a more generic support (a new generic template function) for using keys from these sources. I am happy to create a PR with the change and go through the review process if this would be acceptable in principle.

Yup, this sounds great. Please do implement this, and use each service's API if possible as it provides more structured data (and therefore more flexibility) than using the `https://service.com/username.keys` URL. There should be a separate template function for each service.

**Comment by sochotnicky** [comment]
Well I did have a quick look around the APIs.

Codeberg API always requires an authentication/token (which makes it less than ideal to use on a new machine).
Gitlab instances have some APIs availabe without auth. One issue I see
* User keys can be queried using REST API easily (i.e. https://gitlab.com/api/v4/users/sochotnicky/keys )
* Project releases/tags can be queried from REST API without auth, but these use numeric project IDs (i.e. https://gitlab.freedesktop.org/api/v4/projects/4753/releases). Still doable to get the releases/tasks but would need multiple roundtrips.
* Gitlab supports GraphQL queries which means latest release/tag can be easily queried with a single query, but as far as I can tell this does not include user public ssh  keys anywhere (so would require 2 separate types of querying)

**Comment by sochotnicky** [comment]
One additional note - I don't have any specific project in either codeberg or one of the gitlab instances which would produce a binary release (i.e. something go/rust based that I'd use). So I have a bit less incentive to actually work on those parts.

And that actually leads to me to realize that I usually have to update/upload my ssh keys to all the various forges so it doesn't matter which one I take them from. So I might as well just use the one that already exists.

**Comment by twpayne** [comment]
OK. Is this still needed then?

**Comment by sochotnicky** [comment]
I realized that I don't need this after all (yet). If I ever come across something that is released from codeberg or one of the gitlab instances I can reopen :-)
