### ISSUE TITLE
Use a template to create a directory of files in different locations across OSes

### ISSUE THREAD

**Issue by baslat** [twpayne/chezmoi#2587]
###  What exactly are you trying to do?

I currently use templates to manage machine-to-machine differences for single files. However, I have the situation where I have a folder of files that are in different locations across OSes. AFAICT the only way to manage this would be to create a template for each file. I would like to be able to specify the folder location with a template, and have the contents be placed appropriately (without having to create a template for each file).

For example, on MacOS the paths might be:

```
~/thefolder/file1.txt
~/thefolder/file2.txt
~/thefolder/file3.txt
# etc
```

And on Windows

```
~/extrafolder/thefolder/file1.txt
~/extrafolder/thefolder/file2.txt
~/extrafolder/thefolder/file3.txt
# etc
```

## What have you tried so far?

Reading the documentation, searching the github issues, searching the internet, experimenting with templates.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

NA

## Output of `chezmoi doctor`

NA

## Additional context

NA

**Comment by twpayne** [comment]
See https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#handle-different-file-locations-on-different-systems-with-the-same-contents.

**Comment by twpayne** [comment]
Hopefully this answers your question. See also #2273 and #2335 that should make this easier in the future. Please re-open if needed.

**Comment by baslat** [comment]
Thanks, I think #2273 is the feature I'm after.
