### ISSUE TITLE
Ignore all except?

### ISSUE THREAD

**Issue by Kevin-Mok** [twpayne/chezmoi#261]
Is there a functionality currently implemented to provide an exception to ignoring a specific file in a directory? I tried using `!` like [in this SO answer](https://stackoverflow.com/a/987162/8811872), but it didn't seem to work.

**Comment by twpayne** [comment]
`chezmoi` doesn't currently support the `!` operator in `.chezmoiignore` files (to be honest I didn't know that `git` had this functionality) but it should be straightforward to add. I should have some time to work on this in the next couple of days.

**Comment by twpayne** [comment]
#262 should add this functionality. @Kevin-Mok would you be able to test and close this issue if it works for you? I might have missed something.

**Comment by Kevin-Mok** [comment]
Works just as Git's now. :+1: 

I did run into a minor problem while building the executable though on the latest `go` version on Ubuntu (1.10.4), where I had to import `os/user` and use `user.Current().HomeDir` in the following places:
```
go/src/github.com/twpayne/go-xdg/basedirectoryspecification.go:30:18: undefined: os.UserHomeDir
go/src/github.com/twpayne/chezmoi/cmd/config.go:348:18: undefined: os.UserHomeDir
go/src/github.com/twpayne/chezmoi/cmd/root.go:41:18: undefined: os.UserHomeDir
```

I guess it isn't really an issue though since all the executables are already built in the releases.
