### ISSUE TITLE
How would I ideally ship fonts with chezmoi?

### ISSUE THREAD

**Issue by KasperSkytte** [twpayne/chezmoi#2625]
Some prompts and shell enhancements like **starship** and **oh-my-zsh** require special fonts to display in the terminal correctly. I'd like to ship these in a convenient way with the dotfiles, in my case into `~/.local/share/fonts` on Linux. What's the most ideal way to do that with **chezmoi**?
 - Make a script that pulls and unpacks them (into the correct folder depending on OS)?
 - Keep the `.ttf` files with the dotfiles repo itself so chezmoi copies them (into the correct folder depending on OS)?
 - Define external archives/git repo subfolders in `.chezmoiexternal` (would be a whole folder with `.tff` files to copy from, but the fonts must be individual files in `~/.local/share/fonts`)?
 - Other?

**Comment by KasperSkytte** [comment]
My github issues search doesn't work at the moment for some reason, so my apologies if this is a duplicate

**Comment by twpayne** [comment]
> * Define external archives/git repo subfolders in `.chezmoiexternal` (would be a whole folder with `.tff` files to copy from, but the fonts must be individual files in `~/.local/share/fonts`)?

This is the approach I recommend and I use. You can see [how I manage fonts in my own dotfiles here](https://github.com/twpayne/dotfiles/blob/7a589153dc00cc0d17d49c3a0618e10cf1349a9e/home/.chezmoiexternal.toml#L39-L62). Note that the red syntax highlighting comes from the mix of Go template and TOML syntax.

**Comment by KasperSkytte** [comment]
Alright, thank you! I'm using both Meslo and Fira Code fonts, Fira has so many files. I guess I'll just pick them out individually

**Comment by bradenhilton** [comment]
If your package manager has the fonts, you can also install them with a `run_once_before_` script which invokes your package manager.
