### ISSUE TITLE
age: error: reading "${HOME}/key.txt": failed to open file

### ISSUE THREAD

**Issue by nick-youngblut** [twpayne/chezmoi#2629]
## Describe the bug

I followed the instructions at [encryption](https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/) for added encryption, but after completing the process, I get the following error when running `chezmoi apply` or `chezmoi diff`:

```
age: error: reading "${HOME}/key.txt": failed to open file: open ${HOME}/key.txt: no such file or directory
age: report unexpected or unhelpful errors at https://filippo.io/age/report
chezmoi: exit status 1
```

It appears that one must `cp key.txt.age ~/key.txt && chmod 0600 ~/.key.txt` and the end of the process described in [encryption](https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/ )

## To reproduce

OS: `osx 12.6 (21G115)`

```
brew install chezmoi
brew install age
# follow: https://www.chezmoi.io/quick-start/
# follow: https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/
chezmoi diff
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.28.0, commit 8e9ed2eee04b708b4d7531863e47b5c5a876050f, built at 2022-12-13T20:48:41Z, built by Homebrew
ok        latest-version       v2.28.0
ok        os-arch              darwin/arm64
ok        uname                Darwin Nicholass-Air.attlocal.net 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:20:07 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T8110 arm64 arm Darwin
ok        go-version           go1.19.4 (gc)
ok        executable           /opt/homebrew/bin/chezmoi
ok        upgrade-method       brew-upgrade
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-12-18T20:48:23-08:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found /opt/homebrew/bin/emacs
ok        edit-args            /opt/homebrew/bin/emacs
ok        git-command          found ~/opt/miniconda3/envs/nf-core/bin/git, version 2.37.3
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
ok        age-command          found /opt/homebrew/bin/age, version 1.0.0
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by nick-youngblut** [comment]
When setting up a new codespace, via:

```
# age
wget -O age.tar.gz https://dl.filippo.io/age/latest?for=linux/amd64
tar -pzxvf age.tar.gz
mv age/age $HOME/bin/
rm -rf age age.tar.gz
# chezmoi
sh -c "$(wget -qO- get.chezmoi.io)" -- -b $HOME/bin
export PATH=$HOME/bin:$PATH
chezmoi init --apply GITHUB_USERNAME
```

I get the error: 

```
chmod: cannot access '/home/gitpod/key.txt': No such file or directory
```

I have to manually copy over my `key.txt` file to my new codespace in order to get `chezmoi init --apply GITHUB_USERNAME` to work. If such manual copy-and-paste is needed, then it would be helpful to include this in the docs (e.g., at `Set up a new machine with a single command` in the `Quick start`)

**Comment by halostatue** [comment]
Ensuring the presence of security tooling that is *used* by chezmoi is generally outside of the scope of chezmoi itself, although there are interesting things that could be done with scripts run during initialization as #2630 suggests.

I think that the presence of an encryption key, unless provided through some other connected means such as 1Password (which *itself* must be installed before chezmoi can use it) is not an unexpected requirement.

**Comment by nick-youngblut** [comment]
I'm just trying to point out that the chezmoi documentation on using age for encryption appears to be incomplete, given that I followed the chezmoi documentation, which lead to the issues described above.

**Comment by twpayne** [comment]
Thanks for reporting this. #2636 updates the documentation.

To address a key misunderstanding in the posts above: you should not need to copy the unencrypted private key `key.txt` anywhere. Instead, the private key should be stored in the passphrase-protected file `key.age.txt`.

**Comment by nick-youngblut** [comment]
Thanks for clarifying! So the updated documentation describes how to generate the passphrase-protected `key.age.txt` file? At least for the previous version of the docs, no such passphrase-protected `key.age.txt` was generated when I followed the docs in chezmoi.

**Comment by twpayne** [comment]
> At least for the previous version of the docs, no such passphrase-protected `key.age.txt` was generated when I followed the docs in chezmoi.

That's strange, as the [docs include this exact statement](https://github.com/twpayne/chezmoi/blob/06280f0aa9ef51e411563e4d4f4af51db3ee77cb/assets/chezmoi.io/docs/user-guide/frequently-asked-questions/encryption.md#L24) for generating `key.txt.age`.

**Comment by nick-youngblut** [comment]
Sorry, I meant in a new codespace. I will run `chezmoi init --apply`, and then get the error: `age: error: reading "${HOME}/key.txt": failed to open file: open ${HOME}/key.txt: no such file or directory`. 

Maybe it set it up wrong. To be clear, `key.txt.age` should **not** be included in the dotfiles repo, correct?

**Comment by twpayne** [comment]
> Maybe it set it up wrong. To be clear, `key.txt.age` should **not** be included in the dotfiles repo, correct?

Incorrect. `key.txt.age` (which is your private key, encrypted with a passphrase) should be included in your dotfiles repo.

**Comment by nick-youngblut** [comment]
Thanks for the clarification! Maybe it would be helpful to make that explicit in the docs?

**Comment by twpayne** [comment]
Done in fcf6c4e144e9fd8727d2c24a3567a16932c4a4b2.

Hopefully this is now resolved. Please re-open if needed.
