### ISSUE TITLE
Difference between "MM" and "M" in Chezmoi status

### ISSUE THREAD

**Issue by Urthor** [twpayne/chezmoi#2635]
## What exactly are you trying to do?

Using the Chezmoi status command.

I want to understand the difference between:

`❯ chezmoi status
MM .local/share/chezmoi/dot_config/lvim/config.lua`

and

`❯ chezmoi status
M .local/share/chezmoi/dot_config/lvim/config.lua`

To grasp what the single 'M' or "MM" indicates.

Big picture, I'm trying to build my Chezmoi workflow re: the gap between my home directory's file system, and the Chezmoi cd git repo.

Currently using Chezmoi with 2 MacOS machines and 1 Debian derived distribution machines.  Want to build a good workflow.

## What have you tried so far?

Describe what you have tried so far.

The Chezmoi status help message says:

" Print the status of the files and scripts managed by chezmoi in a format
  similar to git status https://git-scm.com/docs/git-status.

  The first column of output indicates the difference between the last state
  written by chezmoi and the actual state. The second column indicates the
  difference between the actual state and the target state."

Looked at git-scm page, and read the Chezmoi status help line word by word.

The documentation at https://www.chezmoi.io/reference/commands/status/ but doesn't contain a reference to what the MM symbol and the M symbol represent. 

Unix man pages and google search, the old standbys, have not turned up anything.

## Where else have you checked for solutions?

* [ ] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

See above.

## Output of any commands you've tried with `--verbose` flag

```console
chezmoi on  master [!⇡] via 🌙 v5.4.4
❯ chezmoi --verbose status
MM .local/share/chezmoi/dot_config/lvim/config.lua
MM .local/share/chezmoi/private_dot_local/private_share/chezmoi/literal_dot_config/lvim/config.lua
MM vimwiki/index.wiki
MM vimwiki/sparkNotes.wiki
```

## Output of `chezmoi doctor`

<details>

```console
chezmoi on  master [!⇡] via 🌙 v5.4.4
❯ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.28.0, commit 8e9ed2eee04b708b4d7531863e47b5c5a876050f, built at 2022-12-18T18:40:56Z, built by goreleaser
ok        latest-version       v2.28.0
ok        os-arch              darwin/arm64
ok        uname                Darwin hmc.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
ok        go-version           go1.19.4 (gc)
ok        executable           ~/.asdf/installs/chezmoi/2.28.0/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-12-13T13:54:58+11:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
ok        diff-command         found ~/.local/bin/lvim
ok        edit-command         found ~/.local/bin/lvim
ok        edit-args            lvim
ok        git-command          found /usr/bin/git, version 2.37.1
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
info      age-command          age not found in $PATH
ok        gpg-command          found /opt/homebrew/bin/gpg, version 2.3.8
info      pinentry-command     not set
info      1password-command    op not found in $PATH
warning   bitwarden-command    found /opt/homebrew/bin/bw, cannot parse version from Could not find dir, "~/Library/Application Support/Bitwarden CLI"; creating it instead.
Could not find data file, "~/Library/Application Support/Bitwarden CLI/data.json"; creating it instead.
2022.11.0
info   gopass-command      gopass not found in $PATH
info   keepassxc-command   keepassxc-cli not found in $PATH
info   keepassxc-db        not set
info   keeper-command      keeper not found in $PATH
info   lastpass-command    lpass not found in $PATH
ok     pass-command        found /opt/homebrew/bin/pass, version 1.7.4
info   passhole-command    ph not found in $PATH
info   vault-command       vault not found in $PATH
info   secret-command      not set
```

</details>

## Additional context

Very, very simple question, my apologies.

I  just have not found the answer going through the help message or the documentation.  I'm really wondering how I *should* have figured out the answer.

I've clearly missed an avenue.

**Comment by twpayne** [comment]
> "The first column of output indicates the difference between the last state
> written by chezmoi and the actual state. The second column indicates the
> difference between the actual state and the target state."

This is the magic sentence. The status `MM` has an `M` (modified) in the first column and an `M` (modified) in the second column.

In your case, it looks like you've added chezmoi's source directory to chezmoi itself, which is going to break a lot of things. Specifically, files in `.local/share/chezmoi` should **not** be managed by chezmoi.

I recommend running the following:

```console
$ rm -rf $(chezmoi source-path ~/.local/share/chezmoi)
```

Please make sure you have a backup of `~/.local/share/chezmoi` before running this command.

**Comment by Urthor** [comment]
>   "The first column of output indicates the difference between the last state
    written by chezmoi and the actual state. The second column indicates the
    difference between the actual state and the target state."

>  This is the magic sentence. The status MM has an M (modified) in the first column and an M (modified) in the second column.

Perfect!

To write it another way as per https://www.chezmoi.io/reference/concepts/.

"First column of output indicates the difference between the last target state Chezmoi wrote to the destination directory, and the current destination state.  

The second column indicates the difference between the current destination file's state, and the current target file's state."

Actual state, aka destination state, aka the state of the file in the destination directory, is the state of the actual file.

Target state is _derived_ from source state (state of the file in ~/.local/share/chezmoi) plus Chezmoi's configs.  (Useful for per machine modification of .bashrc etc).

What's I've missed is:

Capital M stands for modified.

```bash
chezmoi on  master via 🌙 v5.4.4
❯ chezmoi status
 M .config/lvim/config.lua
 M Brewfile
 A vimwiki/KubernetesNotes.wiki
 A vimwiki/S3.wiki
 A vimwiki/StringsAndFiles.wiki
```

In the above, the letters are all in the second column, indicating a difference between destination state and target state.  The last written state in the first state is not displayed, simple enough.

M stands for *modified*.  A presumably stands for "Added."  D for "Deleted".  

And M, A, D, are presumably all you need.  Create, Update, Delete.  

Thank you for that, I've simply never encountered the M/A/D combination before.

M/A/D has just clicked in my brain now.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.

**Comment by Urthor** [comment]
All good.  Thanks a ton Tom, appreciate the help with such a basic issue.
