### ISSUE TITLE
Add builtin git support for git-repo externals

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#2671]
## Is your feature request related to a problem? Please describe.

chezmoi supports `git-repo` externals, but this relies on an external `git` command being present. chezmoi also has a builtin git (using the excellent [`github.com/go-git/go-git`](https://github.com/go-git/go-git)), but the builtin git does not support `git-repo` externals. Adding builtin git support for `git-repo` externals would improve the experience for users using chezmoi on machines without git installed.

## Describe the solution you'd like

`git-repo`s should be `clone`d and kept up-to-date using only the builtin git.

## Describe alternatives you've considered

Keeping things as they are.

## Additional context

The starting points for fixing this are [here](https://github.com/twpayne/chezmoi/blob/87fc2f1cc1ab419181fc49b5853c8406162afc89/pkg/chezmoi/sourcestate.go#L1023) and [here](https://github.com/twpayne/chezmoi/blob/87fc2f1cc1ab419181fc49b5853c8406162afc89/pkg/chezmoi/sourcestate.go#L1044).

**Comment by kazhuravlev** [comment]
clone and pull commands accept unstructured flags from config. Should we support them all or only several or we should create a new config options like (just for illustration) `clone.opts` (instead of `clone.args`) and `pull.opts` (instead of `pull.args`) with correspondingly deprecation warnings?

**Comment by twpayne** [comment]
The hard part about implementing this is making builtin git work just like external git. Adding `clone.opts` and `pull.opts` is an excellent choice as it focuses on the behavior. We can fix the UX (e.g. translating `pull.args` into the the equivalent `pull.opts`) later. Please do create new config options and we can work on the UX later :)

**Comment by twpayne** [comment]
This issue has only one received one comment and no reactions, so it's probably not needed. So, closing as not planned.
