### ISSUE TITLE
Add package howto install script

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#2672]
## Is your feature request related to a problem? Please describe.

chezmoi offers a [binary install script](https://github.com/twpayne/chezmoi/blob/87fc2f1cc1ab419181fc49b5853c8406162afc89/assets/scripts/install.sh) that can be invoked with

```console
$ sh -c "$(curl -fsLS get.chezmoi.io)"
```

The existence of such a script is often [criticized on social media](https://news.ycombinator.com/item?id=32636444) for being insecure.

## Describe the solution you'd like

A balance between the convenience of a `curl | sh` binary installation script and instructions to install from your local package manger would be nice. One option would be to provide a script that prints instructions to install chezmoi using your local package manager.

Roughly speaking this could look like:

```console
$ curl -fsSL get.chezmoi.io/package-howto | sh
run 'apt-get update && apt-get install chezmoi' to install chezmoi
```

Features:
* Only prints the install instructions, does not execute them.
* Does not require root privileges.
* Script should be easy to verify (i.e. short and simple).
* Obviously still runs untrusted code on your local machine, so still open to criticism.

## Describe alternatives you've considered

Arguing on social media. Not a great idea.

## Additional context

A full package install script (i.e. one that downloads and installs a chezmoi package using your local package manager) would also be very useful.

**Comment by halostatue** [comment]
I think that this is a neat idea, but won’t satisfy the people who complain about this, because it’s still piping something that is potentially unsafe through `sh`.

Maybe having a nicely formatted text output might be good:

```console
$ curl -fsSL get.chezmoi.io/package-howto
# Installing

(list the top two ways for each of macOS, Windows, and Linux)
(add `go install https://github.com/twpayne/chezmoi@latest`)
(Have a link to the install documentation page at the bottom)
```

If it’s about 25 lines, then it’s useful, I think.

**Comment by twpayne** [comment]
Good point. I'll close this issue for now.
