### ISSUE TITLE
chezmoi doctor warns chezmoi.toml as suspicious-entries

### ISSUE THREAD

**Issue by johnmanjiro13** [twpayne/chezmoi#2674]
## Describe the bug

When I manage `~/.config/chezmoi/chezmoi.toml` by chezmoi itself, `chezmoi doctor` warns chezmoi.toml as suspicious-entries.

## To reproduce

```console
$ touch ~/.config/chezmoi/chezmoi.toml
$ chezmoi add ~/.config/chezmoi/chezmoi.toml
$ chezmoi doctor

warning   suspicious-entries   ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml
```

## Expected behavior

`chezmoi doctor` doesn't warn chezmoi.toml.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
This is correct. To manage chezmoi's config file with chezmoi, use [a config file template](https://www.chezmoi.io/user-guide/setup/#create-a-config-file-on-a-new-machine-automatically) instead.

**Comment by johnmanjiro13** [comment]
That makes sense. Thank you!
