### ISSUE TITLE
Ignore single file inside a chezmoi managed directory using `.chezmoiignore`

### ISSUE THREAD

**Issue by isak102** [twpayne/chezmoi#2675]
## What exactly are you trying to do?

I am trying to exclude a single file from chezmoi that exists inside of the `nvim/` directory that is managed by chezmoi. The file that I want to exclude is `nvim/lazy-lock.json`. This is what the output of `tree -L 2 -F $(chezmoi source-path)/dot_config/nvim` looks like:
```
/home/isak102/.local/share/chezmoi/dot_config/nvim/
├── after/
│   └── plugin/
├── executable_chezmoi-apply-changes*
├── ftplugin/
│   ├── java.lua
│   └── qf.lua
├── init.lua
├── lazy-lock.json
└── lua/
    └── isak/

6 directories, 5 files
```
As you can see, the `lazy-lock.json` file exists inside the `nvim` directory which is managed by chezmoi. 

## What have you tried so far?

I have tried adding the path to that file to the `.chezmoiignore` file. This is what my `.chezmoiignore` looks like:
```
*.txt
*.log

info/
root/
arch-install/

dot_config/nvim/lazy-lock.json
```
I have also tried adding a line that looks like this: `dot_config/nvim/*.json` but that doesn't work either, chezmoi doesn't ignore the file and when it changes it is displayed by `chezmoi diff`

## Where else have you checked for solutions?

* [x ] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              v2.28.0, built at 2022-12-19T18:09:08Z
warning   latest-version       v2.29.1
ok        os-arch              linux/amd64 (Arch Linux)
ok        uname                Linux HP 6.1.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:55 +0000 x86_64 GNU/Linux
ok        go-version           go1.19.4 (gc)
ok        executable           /usr/bin/chezmoi
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-11-23T22:19:46+01:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
warning   suspicious-entries   ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /usr/bin/zsh
ok        cd-args              /usr/bin/zsh
info      diff-command         not set
ok        edit-command         found /usr/bin/nvim
ok        edit-args            /usr/bin/nvim
ok        git-command          found /usr/bin/git, version 2.39.0
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /usr/bin/zsh
ok        shell-args           /usr/bin/zsh
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.40
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by halostatue** [comment]
Probably the easiest thing to do is to `git rm dot_config/nvim/lazy-lock.json` from your chezmoi source, and then add `~/.config/nvim/lazy-lock.json` to `.chezmoiignore`.

The first is sufficient (but it would be re-added if you re-added `~/.config/nvim`), so the second would prevent the re-add. This would work because chezmoi does not overwrite files that it does not manage.

**Comment by isak102** [comment]
> Probably the easiest thing to do is to `git rm dot_config/nvim/lazy-lock.json` from your chezmoi source, and then add `~/.config/nvim/lazy-lock.json` to `.chezmoiignore`.
> 
> The first is sufficient (but it would be re-added if you re-added `~/.config/nvim`), so the second would prevent the re-add. This would work because chezmoi does not overwrite files that it does not manage.

It doesn't seem to work, my `.chezmoiignore` now looks like this:
```
*.txt
*.log
info/
root/
arch-install/

~/.config/nvim/lazy-lock.json 
```
And I ran `git rm dot_config/nvim/lazy-lock.json` before adding that line. It still doesn't ignore it. The output of `chezmoi ignored` looks like this:
```
arch-install
info
root
```
The `~/.config/nvim/lazy-lock.json`  line doesn't seem to have any effect. It was the same when I had `dot_config/nvim/lazy-lock.json` in the `.chezmoiignore`

**Comment by twpayne** [comment]
This line:

    ~/.config/nvim/lazy-lock.json

should be

    .config/nvim/lazy-lock.json

Paths in `.chezmoiignore` are relative to the target directory, not absolute paths.

**Comment by isak102** [comment]
> This line:
> 
> ```
> ~/.config/nvim/lazy-lock.json
> ```
> 
> should be
> 
> ```
> .config/nvim/lazy-lock.json
> ```
> 
> Paths in `.chezmoiignore` are relative to the target directory, not absolute paths.

Oh yeah I got it switched up, thank you!

**Comment by halostatue** [comment]
That was my error. Sorry about that.
