### ISSUE TITLE
Include external files from a template file?

### ISSUE THREAD

**Issue by Mixaz017** [twpayne/chezmoi#2691]
## What exactly are you trying to do?

I'm trying to `include` contents of a file from a remote repository, to use from a template file.

## What have you tried so far?

I have read [Include dotfiles from elsewhere](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/), but from what I understand, `.chezmoiexternal` is for using external files as-is, and isn't for my use case.
I also thought of using `output` template function to read output of programs like `curl`, but that isn't ideal since templates are executed often.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by bradenhilton** [comment]
If the contents of the file do not change, a `run_once_before_` script which gets the contents with `curl` and outputs it to a file which you then `include` is probably the best option.

If the contents of the file change, it may be better to use `.chezmoiexternal` to acquire it and keep it up to date, but there is no way to guarantee that the file will exist when the template is executed with this method.

Untested, but the following approach might be a good starting point:

```
{{ if not (stat "file/to/include") }}
{{   output "curl" "command" "here" }}
{{ else }}
{{   include "file/to/include" }}
{{ end }}
```

This way, the `output` is only run if the file to include does not exist. Once the external is downloaded, it should exist moving forward.

You could instead consider adding the file as a git submodule if applicable, then using it in `include`.

**Comment by Mixaz017** [comment]
Thank you for a quick response @bradenhilton ! I should have stated that the remote content might change, so I want the remote file to be up to date like `.chezmoiexternal`.

> there is no way to guarantee that the file will exist when the template is executed

I realized about this problem, so I think using git submodules is the best solution for my case so the content is guaranteed to exist.

Thank you for a helpful reply!
