### ISSUE TITLE
Can't extract archive in .chezmoiexternal.yaml

### ISSUE THREAD

**Issue by szinn** [twpayne/chezmoi#2700]
## Describe the bug

Adding in the JetBrainsMono font to be extracted via .chezmoiexternal support fails with a 'no such file or directory'

## To reproduce

Create .chezmoiexternal.yaml with below and 'chezmoi -R apply'

.chezmoiexternal.yaml:
```
"Library/Fonts/JetBrainsMono":
  url: "https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip"
  type: archive
  exact: true
  refreshPeriod: 168h
```

## Expected behavior

I would expect the archive to be extracted.

## Output of command with the `--verbose` flag

```console
$ chezmoi -R apply

chezmoi: mkdir /Users/scotte/Library/Fonts/JetBrainsMono/fonts/ttf: no such file or directory
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.29.2, commit b9536aae9100a2367e7b5baad8a7e251542c45bd, built at 2023-01-15T14:35:48Z, built by Homebrew
ok        latest-version       v2.29.2
ok        os-arch              darwin/arm64
ok        uname                Darwin Odin.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64 arm Darwin
ok        go-version           go1.19.5 (gc)
ok        executable           /opt/homebrew/bin/chezmoi
ok        upgrade-method       brew-upgrade
ok        config-file          ~/.config/chezmoi/chezmoi.yaml, last modified 2023-01-16T21:06:27-05:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
warning   suspicious-entries   ~/.local/share/chezmoi/home/.chezmoi.yaml and ~/.local/share/chezmoi/home/dot_config/chezmoi/chezmoi.yaml.tmpl
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /opt/homebrew/bin/fish
ok        cd-args              /opt/homebrew/bin/fish
info      diff-command         not set
ok        edit-command         found /opt/homebrew/bin/nvim
ok        edit-args            /opt/homebrew/bin/nvim
ok        git-command          found /opt/homebrew/bin/git, version 2.39.1
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /opt/homebrew/bin/fish
ok        shell-args           /opt/homebrew/bin/fish
ok        age-command          found /opt/homebrew/bin/age, version 1.1.1
ok        gpg-command          found /usr/local/bin/gpg, version 2.2.40
info      pinentry-command     not set
ok        1password-command    found /usr/local/bin/op, version 2.12.0
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

The archive has the structure:
```
AUTHORS.txt
OFL.txt
/font
  - no files in this directory
/font/ttf
  - font files
/font/variable
  - font files
/font/webfonts
  - font files
```

I suspect that Chezmoi isn't able to create files in /font/ttf because the /font directory was not created because there were no actual files to put into that directory. This hypothesis is supported by the fact that the apply works if I remove the 'exact' clause AND create JetBrainsMono/fonts directory before executing the apply.

**Comment by szinn** [comment]
The directories Library and Library/Fonts did already exist. That may be another issue that your solution resolves, but that is not the issue I encountered

**Comment by twpayne** [comment]
Ah, indeed. Will investigate further.

**Comment by szinn** [comment]
This might actually be fixed by PR2699 - https://github.com/twpayne/chezmoi/pull/2699

**Comment by szinn** [comment]
I'll take a crack at adding the zip file support for this.

**Comment by halostatue** [comment]
It might, but I’m not sure that it’s the right thing here. I don’t use externals at all right now, but if there’s a way to say that you want to extract `fonts/ttf/*.ttf` to the target directory, that is the *correct* thing, because `Library/Fonts` would not expect subdirectories, AFAIK.

**Comment by szinn** [comment]
@halostatue The issue, as I see it, is the archive contains fonts/ttf/font.ttf but there are no files in the fonts directory in the archive and zip files don't seem to support a directory-only entry like .tar files do. So when chezmoi goes to write fonts/ttf/font.ttf, it can't because the fonts directory doesn't exist to create the ttf directory in.

If I create the fonts directory and then run the apply, it is successful.

So, checking to make sure that all parent directories of the directory where the file goes exists from a top-down review is the way I will attempt it.

**Comment by szinn** [comment]
Re-read your comment on a bigger screen - Library/Fonts does seem to handle nested directories and it picks up all .ttf files below.

**Comment by szinn** [comment]
Submitted a fix - I have not written any Go code in years so this could be a bit rusty. Refactored a bit of the .tar solution
