### ISSUE TITLE
Have to specify keepassxc password multiple times in same command

### ISSUE THREAD

**Issue by bartlibert** [twpayne/chezmoi#2702]
## Describe the bug

I have multiple instances of `keepassxc` and `keepassxcAttribute` in my files. Every time I execute `chezmoi apply` or `chezmoi merge-all` for example, I have to enter my keepass password for every call of the template function, instead of only once per execution, as it was before.

## To reproduce

1. Have multiple files with multiple keepass template functions
2. Perform `chezmoi apply`
3. Enter you password multiple times

## Expected behavior

I have to enter my password only once (as it was before)

## Additional context

The bug was introduced in this commit: https://github.com/twpayne/chezmoi/commit/95b4073c691cc585ac126fce82e45799c5bbf8c9, most notable at these lines:

https://github.com/twpayne/chezmoi/blob/95b4073c691cc585ac126fce82e45799c5bbf8c9/pkg/cmd/keepassxctemplatefuncs.go#L138-L147

There is this line of code that passes the (stored) password to the command line:
https://github.com/twpayne/chezmoi/blob/95b4073c691cc585ac126fce82e45799c5bbf8c9/pkg/cmd/keepassxctemplatefuncs.go#L144

Before, this line was always executed, but now it is only executed if these two conditions are met:
https://github.com/twpayne/chezmoi/blob/95b4073c691cc585ac126fce82e45799c5bbf8c9/pkg/cmd/keepassxctemplatefuncs.go#L138

This means that, as soon as I have entered the password once, that specific line of code will never be executed again, and keepassxc-cli itself will now ask for the password instead (every time).

I'm not a go programmer, so I'll let it up to you to fix this if possible, otherwise I'll try to create a pull request myself.

**Comment by twpayne** [comment]
Thanks for reporting this, and double extra thanks for bisecting to find the offending commit!

#2704 should fix it. Is there any way you can test this?

**Comment by bartlibert** [comment]
I did a quick build with this change, and it seems to work. Thanks for the quick response!

**Comment by twpayne** [comment]
Thanks for the quick test! I'll merge as soon as the tests pass and then tag a new version of chezmoi.

**Comment by twpayne** [comment]
Grr, GitHub is having lots of issues (getting a lot of 5xx internal server error messages and external connectivity problems in CI). I'll wait for it to stabilize before tagging a new version.
