### ISSUE TITLE
Dealing with extension of a repo

### ISSUE THREAD

**Issue by owittek** [twpayne/chezmoi#2708]
## What exactly are you trying to do?

I am using AstroNvim as a Neovim base configuration. For that to work I have to clone the AstroNvim repo to \~/.config/nvim. To extend the config with my own, AstroNvim offers the option of creating a folder called user inside of the configuration (\~/.config/nvim/lua/user to be exact).

I want to automate this setup via chezmoi.

## What have you tried so far?

Before using chezmoi I was using a bare repo and simply cloned AstroNvim and then I pulled my user folder into ~/.config/nvim/lua. I have created a .chezmoiexternal.toml with the repo configured and I simply added my user folder to chezmoi as I did with the bare repo before. But running chezmoi status results in the following message:

> chezmoi: .config/nvim: inconsistent state (/Users/oli/.local/share/chezmoi/dot_config/nvim, https://github.com/AstroNvim/AstroNvim.git defined in /Users/oli/.local/share/chezmoi/.chezmoiexternal.toml)

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
warning   suspicious-entries   ~/.local/share/chezmoi/chezmoi.toml and ~/.local/share/chezmoi/dot_local/share/chezmoi/chezmoi.toml
```
The rest of the output was either OK or an info
</details>

## Additional context

My dotfiles are available here: https://github.com/owittek/dotfiles
AstroNvim: https://github.com/AstroNvim/AstroNvim

Thank you for your help!

**Comment by owittek** [comment]
I found a solution by moving my config from ~\/.config/nvim/lua/user to ~\/.config/astronvim/lua/user but that's a specific case for this framework. 

I think there might be other cases where you want to put a dir or files into a cloned repo for which there's no real documentation as to why I'm leaving this support requesto pen.

**Comment by twpayne** [comment]
The issue here is that `~/.config/nvim` is defined as a `git-repo` external:

```toml
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim.git"
```

By making this a `git-repo` external, you are delegating management of this directory to git, so chezmoi can no longer help you.

Instead, consider making `~/.config/nvim` an `archive` external, that is fully managed by chezmoi:

```toml
[".config/nvim"]
    type = "archive"
    url = "https://github.com/AstroNvim/AstroNvim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
```

With this, you can `chezmoi add` your own files within `~/.config/nvim` (although you might need to create a couple of directories manually, see #1574).

**Comment by owittek** [comment]
That makes sense but many tools require to be installed via git to offer self-updating functionality (and yes I am aware of refreshPeriod). A convenient solution might be to define such folders in chezmoiexternal and to stash and pop it automatically on repo-updates.

**Comment by twpayne** [comment]
chezmoi already passes the `--autostash` and `--rebase` flags to `git pull` when updating `git-repo` externals.
