### ISSUE TITLE
Integration of vault with chezmoi

### ISSUE THREAD

**Issue by Niba-nazar** [twpayne/chezmoi#2733]
Hi,

I would like to know the possibilites of integrating password manger vault with chezmoi. Gone through the link  https://www.chezmoi.io/user-guide/password-managers/, still not able to figure this out.

Could you please help me with this?

**Comment by twpayne** [comment]
You need to use the [`vault` template function](https://www.chezmoi.io/reference/templates/vault-functions/vault/) in a template. This template function returns secret from Vault.

Under the hood the `vault` template function uses the [`vault` command line interface](https://developer.hashicorp.com/vault/docs/commands), which you must have already configured.

**Comment by twpayne** [comment]
Hopefully this answers your question. Please re-open if needed.
