### ISSUE TITLE
Add winget support to `chezmoi upgrade`

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#2736]
## Is your feature request related to a problem? Please describe.

The [`chezmoi upgrade` command](https://www.chezmoi.io/reference/commands/upgrade/) attempts to detect how chezmoi was installed and then use the same mechanism to upgrade chezmoi. For example, if the user installed chezmoi with their package manager, then `chezmoi upgrade` should use the same package manager to install a new version of chezmoi.

Currently, when chezmoi is installed with winget, `chezmoi doctor` [reports](https://github.com/twpayne/chezmoi/pull/2735#issuecomment-1416390837) that `chezmoi upgrade` should use the generic `replace-executable` method to upgrade chezmoi.

##  Describe the solution you'd like

When chezmoi is installed with a winget package (#2735), then `chezmoi upgrade` should use winget to install the latest available version of chezmoi.

## Describe alternatives you've considered

Keeping this as-is.

## Additional context

There are two parts:

1. Detecting if chezmoi was installed with winget. The [current heuristics](https://github.com/twpayne/chezmoi/blob/213bac53127a41c9910186b498e9ffefdcf8ed5b/pkg/cmd/upgradecmd.go#L471-L538) look at the path to the executable and file ownership. These would need to be extended to detect winget installations of chezmoi.
2. Upgrading chezmoi via winget in this case. The [current code](https://github.com/twpayne/chezmoi/blob/213bac53127a41c9910186b498e9ffefdcf8ed5b/pkg/cmd/upgradecmd.go#L166-L192) would need to be extended to call winget to upgrade chezmoi.

@bradenhilton would you like to tackle this? Please assign yourself to this issue if/when you want to take it.

**Comment by bradenhilton** [comment]
Isn't it like this for all package managers on Windows? Seems like we need to do this for Chocolatey and Scoop as well as Winget.

**Comment by twpayne** [comment]
Yes, you're right. Let's do this one package manager at a time (either as separate commits or separate pull requests). Note that `chezmoi upgrade` is an optional command that [can be disabled by packagers](https://www.chezmoi.io/developer/packaging/) (search for `noupgrade`).

An incremental solution here is already an improvement for users, so please tackle the most important package manager for you first.

**Comment by bradenhilton** [comment]
Looks like they all install directly from the release assets, so I don't think `noupgrade` will be an issue unless I'm missing something else.

https://community.chocolatey.org/packages/chezmoi#files

https://github.com/ScoopInstaller/Main/blob/aec5e358dac75a8a1e5f67cd2643b9ca43fb7dfc/bucket/chezmoi.json
https://github.com/twpayne/scoop-bucket/blob/fe0864e9434ce8cd004723eeb215a6d865f5f38e/chezmoi.json

https://github.com/microsoft/winget-pkgs/blob/89374025ad6c5779f085f1d5f3b07dcee3b3f233/manifests/t/twpayne/chezmoi/2.29.4/twpayne.chezmoi.installer.yaml

The only one I can't test right now is Chocolatey, I'll have to reinstall it first.

**Comment by twpayne** [comment]
The reasoning behind `noupgrade` is that some distros (for very good reasons) prefer you to upgrade packages through their existing processes, which includes various security checks, distribution of the package to mirrors, etc.  It's entirely reasonable that they remove the `chezmoi upgrade` command from their distribution.

`chezmoi upgrade` is targeted at users who installed chezmoi with their preferred installation method and want to keep using that method without having to remember the exact command that they typed to install chezmoi. Under the hood `chezmoi upgrade` might run `apt`, `brew`, `pacman`, `yum`, or something else, depending on how chezmoi thinks it was installed.

All incremental improvements are fantastic improvements here. This is a user experience benefit that we can deliver one step at a time.

**Comment by bradenhilton** [comment]
On reflection, I think administrator privilege requirements complicate this quite a bit. It's not as simple as checking the UID for root.

For example, a default install of Chocolatey [must be performed in an administrator shell](https://docs.chocolatey.org/en-us/choco/setup#installing-chocolatey), as the default install location is only writable by users with administrator privileges. You can change the default location with an environment variable, [but it still must only be writable by users with administrator privileges](https://docs.chocolatey.org/en-us/choco/setup#installing-to-a-different-location).

[Default Chocolate Install Reasoning](https://docs.chocolatey.org/en-us/default-chocolatey-install-reasoning)

It's possible to [install as a non-administrator instead](https://docs.chocolatey.org/en-us/choco/setup#non-administrative-install), but this is not recommended, and it appears to severely limit which packages can be installed, [including chezmoi it seems](https://community.chocolatey.org/packages?q=id%3Aportable+tag%3Aportable+chezmoi).

This means that `choco upgrade chezmoi` must be performed with administrator privileges in most cases. I'm currently not sure how to achieve this (specifically, invoking the package manager in a sub-process with administrator privileges), I'll have to investigate this further.

Scoop is non-administrator by default, but it's possible to perform an [administrator installation](https://github.com/ScoopInstaller/Install/blob/f1cf244456a4201a4ee3d1ad8cea2ac96e301198/README.md), so I assume the same or similar applies here as well.

Winget has [some considerations](https://learn.microsoft.com/en-us/windows/package-manager/winget/#administrator-considerations), but they seem the easiest to work around at the moment.

Do you think now would be an appropriate time to separate the platform specific code into platform specific files (`upgradecmd_windows.go` etc.)? I can see the `switch` statements growing considerably.

We can of course start with basic non-administrator implementations, but we should  probably implement the rest at some point afterwards.

**Comment by twpayne** [comment]
> Do you think now would be an appropriate time to separate the platform specific code into platform specific files (`upgradecmd_windows.go` etc.)? I can see the `switch` statements growing considerably.

Yes, this makes lots of sense. We'll likely have to do this anyway at some point as soon as we need to make Windows system calls.

**Comment by bradenhilton** [comment]
> Winget has [some considerations](https://learn.microsoft.com/en-us/windows/package-manager/winget/#administrator-considerations), but they seem the easiest to work around at the moment.

I just had to say this didn't I :)

I have a very basic path check working for winget:

```console
❯ chezmoi doctor
RESULT    CHECK                MESSAGE
...
ok        go-version           go1.19.5 (gc)
ok        executable           ~/AppData/Local/Microsoft/WinGet/Links/chezmoi.exe
ok        upgrade-method       winget-upgrade
...
```

But `winget{.exe}` can't be run from `exec.Command()`:

```console
❯ chezmoi upgrade --force
chezmoi: exec: "winget.exe": executable file not found in %PATH%
```

Winget is indeed in my `%PATH%`:

```console
❯ ($env:PATH -split ';') -contains (Split-Path (Get-Command winget).Source)
True
```

I did some searching and it looks like it's because `winget.exe` is a 0 byte reparse point file. This then lead me [here](https://go-review.googlesource.com/c/go/+/460595). The linked change is merged but I can't decipher if it has been released in a stable version yet. The milestone on the issue mentioned in the commit is `go1.21`.

**Comment by twpayne** [comment]
Oh wow. Thank you for all your investigative work here - really appreciated. I had no idea that such a thing as a "0 byte reparse point file" existed and can only wonder what occult rituals were performed in the depths of Microsoft to summon such an unholy abomination into this world. Their need must have been great.

Adding a `patience` label here is very appropriate. Let's hope chezmoi doesn't have to summon any of the Old Ones.

**Comment by twpayne** [comment]
This is awesome progress, thank you.

> If winget cannot do what you ask it to do (e.g. you ask it to upgrade chezmoi and there is no new version available), it returns an error code. This currently causes chezmoi to exit with the code. Is this something we need to work around?

Debatable. One one hand `chezmoi upgrade` did actually fail because it did not upgrade chezmoi. On the other hand, `chezmoi upgrade` succeeded as chezmoi is at the latest version.

What's the Windows convention here? We could either keep the behavior as-is, or add a check to silently swallow this specific error from winget.

> It will probably take some time for this fix to be released in a stable version.

I suspect that this fix will be included in Go 1.20.1, which we can probably expect in about one month (wild guess). If there's no sign of Go 1.20.1 by mid-March, let's consider using one of the workarounds you suggest. I'm loathe to do complex extra work for temporary workarounds.

> Also, completely off-topic, but I noticed that my `.chezmoiroot` shows the CRLF line-ending in the debug output. My understanding is that the [contents of `.chezmoiroot` are trimmed](https://github.com/twpayne/chezmoi/blob/3ef62d6ce8f4c75f19bf9ea568d275b5399d4e47/pkg/cmd/config.go#L1234). Is this simply outputting the raw contents of the file?

Yes, exactly. The debug line is probably a `ReadFile` line. This prints the first few bytes of the files contents. The line endings are handled by a `bufio.Scanner` later.

**Comment by bradenhilton** [comment]
> Debatable. One one hand `chezmoi upgrade` did actually fail because it did not upgrade chezmoi. On the other hand, `chezmoi upgrade` succeeded as chezmoi is at the latest version.
> 
> What's the Windows convention here? We could either keep the behavior as-is, or add a check to silently swallow this specific error from winget.

I'm not sure if a convention exists. I did manage to find the [error definitions](https://github.com/microsoft/winget-cli/blob/b21389cbf07126f7678cee953543f5e0bcb0e0c1/src/AppInstallerSharedLib/Public/AppInstallerErrors.h) though.

> Yes, exactly. The debug line is probably a `ReadFile` line. This prints the first few bytes of the files contents. The line endings are handled by a `bufio.Scanner` later.

Good to know!

**Comment by twpayne** [comment]
Looks like we'll get Go 1.20.1 on Valentine's Day: https://groups.google.com/g/golang-nuts/c/IyxwZ75oh9g

Don't know if this will include https://go-review.googlesource.com/c/go/+/460595 or not.

**Comment by bradenhilton** [comment]
I might as well open a basic draft PR for now.

**Comment by twpayne** [comment]
Go 1.20.1 was released and, as far as I can tell, it [does not include](https://github.com/golang/go/issues?q=milestone%3AGo1.20.1+label%3ACherryPickApproved) https://go-review.googlesource.com/c/go/+/460595. Still, no rush on this.
