### ISSUE TITLE
provide an environment variable for Chezmoi-initiated shell

### ISSUE THREAD

**Issue by FranklinYu** [twpayne/chezmoi#2739]
## Is your feature request related to a problem? Please describe.

I would like to show in the shell prompt “whether this shell is under Chezmoi”. In other words, whether the shell is a decedent process of Chezmoi (including direct and indirect child processes). I myself just want `[c]` to appear in the prompt, but I’ll configure my prompt myself.

## Describe the solution you'd like

Chezmoi to output some environment variable. It could be as simple as `CHEZMOI=true`, or maybe we can make use of this to export something more useful like `CHEZMOI_SRC_DIR=/directory/of-source-state`?

## Describe alternatives you've considered

Maybe Chezmoi can inject something when it is starting the shell? But it sounds more complicated than setting an environment variable.

In theory I can also use some ways to recursively look up parent processes, but they could be platform dependent. For example procfs won’t work on macOS.

## Additional context

N/A.

**Comment by halostatue** [comment]
I think that there are a number of environment variables that could be exported for this that are also available to scripts when running `chezmoi apply`, but as you say, exporting `CHEZMOI=true` or `CHEZMOI_SHELL=true` would be an easy first pass.

**Comment by twpayne** [comment]
Yes, as @halostatue says, chezmoi currently sets a lot of environment variables for scripts, although this was never documented.

You can see the list of environment variables that are already set [here](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/config.go#L1869-L1905).

You can also add extra environment variables to be passed to scripts in your config file, which is also undocumented. Putting:

```toml
[scriptEnv]
    CHEZMOI = "true"
```

in `~/.config/chezmoi/chezmoi.toml` will set the `$CHEZMOI` environment variable to `true` in scripts.

I'll document this.

**Comment by twpayne** [comment]
Hat tip to @halostatue for both the idea and implementation in https://github.com/twpayne/chezmoi/pull/2418.

**Comment by halostatue** [comment]
> Yes, as @halostatue says, chezmoi currently sets a lot of environment variables for scripts, although this was never documented.
> 
> You can see the list of environment variables that are already set [here](https://github.com/twpayne/chezmoi/blob/master/pkg/cmd/config.go#L1869-L1905).

The suggestion, which I think is *also* a good idea, would be to expose the same environment variables (at least the default `$CHEZMOI_*` ones) when running `chezmoi cd`.

This would allow you to customize your prompt *if* you’re in a `chezmoi cd` executed shell.

**Comment by twpayne** [comment]
Ah, I see, thank you. Yes, that makes sense. Implemented in #2743.
