### ISSUE TITLE
Add Async Feature

### ISSUE THREAD

**Issue by ProfessorManhattan** [twpayne/chezmoi#2740]
Hey, I asked about this before but I'd like to be able to run scripts asynchronously. I think this could be accomplished in a backwards-compatible way. We could introduce the `async-#_` attribute. It could run all the files that have `async-14_` in the filename at the same time. I don't mind hiring a Go developer to add this but I was hoping to get into the main branch for the trustworthiness factor. Any thoughts?

**Comment by halostatue** [comment]
I’m not entirely sure that async scripts would be a good idea as a core feature.

However, it is possible to get parallelization in a bash script itself:

```bash
#! /usr/bin/env bash

run() {
  sleep "$1"
  echo "$2"
}

run 3 1 &
run 2 2 &
run 1 3 &

wait
```

**Comment by twpayne** [comment]
I am also opposed to async scripts in core chezmoi. Asynchronous programming is particularly hard, especially when there is shared global state involved. In the case of chezmoi, the shared global state is the entirety of local machine and some remote servers.

It is not a question of implementation effort. I cannot see a situation under which a PR implementing asynchronous scripts would be accepted. @halostatue gives a practical solution for controlled asynchronicity.

**Comment by twpayne** [comment]
Note that chezmoi already reads the source directory concurrently (#1851), and downloading externals concurrently is on the roadmap for v3 (#2673, #2670).
