### ISSUE TITLE
SHASUM Full Directory

### ISSUE THREAD

**Issue by ProfessorManhattan** [twpayne/chezmoi#2741]
Hey, I am trying to run a script whenever `onchange_` is in place and any file in a certain directory in the chezmoi.sourceDir changes. For instance, if there's a file in `{{ .chezmoi.sourceDir }}/.local/theme` that changes, I'd like the theme script in `.chezmoiscripts` to run. There are examples of how to do this for a file but I was wondering if you had any advice on the most efficient way of handling this scenario for full directories.

Thanks!

**Comment by twpayne** [comment]
This is tricky as there is a lot of non-determinism and lot of noise. For example, file access times change all the time, but you probably don't want to consider that a change. The order of iteration over a directory's contents is also not defined, so you might need a sorting step. If the files are large, you generally want to bail out as soon as you find a difference.

If you only care about file contents, I would suggest experimenting with `find` and `sha256sum`, for example:

```console
$ find $DIR -type f -exec sha256sum -b {} \; | sort | sha256sum | cut -d\   -f1
```

will give you an overall SHA256 sum based on all the files and their contents in `$DIR`.

**Comment by twpayne** [comment]
Hopefully this answers your question. Please re-open if needed.
