### ISSUE TITLE
how to execute some command after refresh externel  item?

### ISSUE THREAD

**Issue by Xiang929** [twpayne/chezmoi#2754]
ex.
```
[".oh-my-zsh/custom/themes/spaceship-prompt"]
    type = "git-repo"
    clone.args = ["--depth", "1"]
    url = "https://github.com/spaceship-prompt/spaceship-prompt"
```
I want to execute `ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme" ` after `git clone repo`.

What course of action should I take?

chezmoi version: v2.26.0
os: macOS 12.6

**Comment by bradenhilton** [comment]
You can use a `run_after_` script wherein you can perform any necessary steps.

Please update chezmoi to the latest version if you are able to.

**Comment by Xiang929** [comment]
> You can use a `run_after_` script wherein you can perform any necessary steps.
> 
> Please update chezmoi to the latest version if you are able to.
but I am seeking a solution to automate the execution of a command after refreshing an external component, such as refresh oh-my-zsh archive, without having to manually run 'chezmoi apply' each time."

**Comment by bradenhilton** [comment]
The external won't be refreshed unless you run `chezmoi apply` anyway, if I'm not mistaken.
