### ISSUE TITLE
chezmoi add fails when part of the path is a symlink

### ISSUE THREAD

**Issue by mrshu** [twpayne/chezmoi#2758]
## Describe the bug

I am trying to move to `chezmoi` form using [`stow`](https://www.gnu.org/software/stow/), which I had used to manage dotfiles stored in `/home/$USER/dotfiles`.

For instance, the [powerline](https://powerline.readthedocs.io/en/master/overview.html) configs in `~/.config/powerline` are symlinked as follows:

```
$ ls -dl ~/.config/powerline
lrwxrwxrwx. 1 user user 39 Aug  9  2017 /home/user/.config/powerline -> ../dotfiles/powerline/.config/powerline/
```

When I then tried to then add `~/.config/powerline/config.json` using `chezmoi add`, even with the `--follow` flag, `chezmoi` responded with the following.

```
$ chezmoi add --follow ~/.config/powerline/config.json --verbose
chezmoi: lstat /home/user/.local/share/chezmoi/dot_config/symlink_powerline/config.json: not a directory
```

To be completely fair, the `--follow` documentation as well as the ["Migrating from another dotfile manager"](https://www.chezmoi.io/migrating-from-another-dotfile-manager/#migrate-from-a-dotfile-manager-that-uses-symlinks) guide  does mention that only the last part of a target is added -- not the transitive directory which is what I was trying to do above:

> If the last part of a target is a symlink, add the target of the symlink instead of the symlink itself.

That said, I believe it would be great if `chezmoi` was able to support this case as well.

## To reproduce

```
$ mkdir -p dotfiles/test .config/
$ echo "echo test" > dotfiles/test/test.sh
$ cd .config
$ ln -s ../dotfiles/test test
$ chezmoi add --follow .config/test/test.sh
chezmoi: lstat /home/user/.local/share/chezmoi/dot_config/symlink_test/test.sh: not a directory
```

## Expected behavior

The file is added as if there was no symlinked directory involved.

## Output of command with the `--verbose` flag

```console
$ chezmoi add --follow ~/.config/powerline/config.json --verbose
diff --git a/dot_config/symlink_powerline b/dot_config/symlink_powerline
new file mode 100644
index 0000000000000000000000000000000000000000..d6f01b0950124e2f6d1b703e0568a1402e3c446c
--- /dev/null
+++ b/dot_config/symlink_powerline
@@ -0,0 +1 @@
+../dotfiles/powerline/.config/powerline
chezmoi: lstat /home/user/.local/share/chezmoi/dot_config/symlink_powerline/config.json: not a directory

```

## Output of `chezmoi doctor`

<details>

```console
RESULT    CHECK                MESSAGE
ok        version              v2.29.1, commit 5e7063ec11bb85efcf8e0c152dcd7dd674ed2d90, built at 2023-01-02T15:50:04Z, built by goreleaser
warning   latest-version       v2.30.1
ok        os-arch              linux/amd64 (Fedora Linux 36 (Workstation Edition))
ok        uname                Linux localhost 6.0.18-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:08:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.19.4 (gc)
ok        executable           /usr/bin/chezmoi
ok        upgrade-method       sudo-upgrade-package
ok        config-file          no config file found
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /usr/bin/fish
ok        cd-args              /usr/bin/fish
info      diff-command         not set
ok        edit-command         found /usr/bin/vim
ok        edit-args            /usr/bin/vim
ok        git-command          found /usr/bin/git, version 2.39.0
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /usr/bin/fish
ok        shell-args           /usr/bin/fish
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.3.7
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.7.4
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

This does seem similar to 
- https://github.com/twpayne/chezmoi/issues/2018
- https://github.com/twpayne/chezmoi/issues/2006
- https://github.com/twpayne/chezmoi/issues/1574

But these seem to be more about the `chezmoi managed` and `chezmoi external` rather than the usecase I tried to describe above. Please do let me know if I might have missed anything.

Thanks!

**Comment by twpayne** [comment]
Thanks for reporting this. Indeed, `chezmoi add` currently doesn't handle traversing through symlinks to directories. Fixing this will require significant effort and only be used in very limited cases, so it's something I might consider for version 3.

In the meantime, there's a [stow to chezmoi script](https://github.com/twpayne/chezmoi/blob/ea4f87e7f2da88e800f996aac2dc2f5379787443/assets/scripts/stow-to-chezmoi.sh) that might be helpful.

**Comment by mrshu** [comment]
Totally understood -- thanks @twpayne! I believe the stow to chezmoi script that you linked to might be all that's necessary for people like me :slightly_smiling_face:

Feel free to close this issue if that would help in any way!

**Comment by twpayne** [comment]
OK, I think it's reasonable to close this as not planned.
