### ISSUE TITLE
Why are chezmoi cd and exit commands needed?

### ISSUE THREAD

**Issue by avlapp** [twpayne/chezmoi#2760]
I'm wondering why chezmoi cd and exit commands are needed. Git has the -C path option where one can specify a directory right? That directory is fixed for chezmoi (or one could use a env var).

**Comment by twpayne** [comment]
See [this FAQ entry](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-cd-spawn-a-shell-instead-of-just-changing-directory).

**Comment by avlapp** [comment]
I could add some aliases in ~/.bashrc I guess:

alias chezmoiAddGit='git -C $HOME/.local/share/chezmoi/ add .'
alias chezmoiCommitGit='git -C $HOME/.local/share/chezmoi/ commit -am'
alias chezmoiPushGit='git -C $HOME/.local/share/chezmoi/ push origin main'

**Comment by twpayne** [comment]
The [`chezmoi git` command](https://www.chezmoi.io/reference/commands/git/) already exists for this purpose.
