### ISSUE TITLE
`--progress=auto` so that it display progress only if `stdinIsATTY`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#2766]
## Is your feature request related to a problem? Please describe.

Currently, if I add `progress: true` to either my chezmoi config or `--progress` to my chezmoi calls, chezmoi will fail if the terminal is not running interactively, like when it's run as part of CI.

## Describe the solution you'd like

A new option for the progress flag, like `--progress=auto` as opposed to `--progress=true`. When auto, progress would be enabled if stdinIsATTY, but will gracefully disable it if not.

Maybe this could be even set the default for progress option rather than being just `false`?

## Describe alternatives you've considered

On my init script:

```bash
# If interactive, display progress bar
if [ -t 0 ]; then
  set -- "$@" --progress
fi
```

On my chezmoi config:

```
{{ if stdinIsATTY -}}
progress: true
{{- end }}
```

## Additional context

The alternative solution isn't bad, I just think that sorting this in upstream would be more beneficial.

**Comment by halostatue** [comment]
This feels like something that should be handled more gracefully. That is, `--progress=true` should be disabled if `stdinIsATTY` is false.

It might be desirable to have a "log"-style progress which gets used when `--progress` is specified and `!stdinIsATTY`, but that may be a version 3 feature.

**Comment by halostatue** [comment]
It looks like `--progress` should be acting that way already:

https://github.com/twpayne/chezmoi/blob/725f4b04ecc7da1ec0de06d2872cc85dd8ca17d1/pkg/cmd/readhttpresponse.go#L117-L118

I don’t make heavy use of externals, so I can’t be sure what’s going on.

**Comment by felipecrs** [comment]
This is what happened when I added `progress: true` to my chezmoi.yaml:

https://github.com/felipecrs/dotfiles/actions/runs/4164536135/jobs/7206302386#step:3:130

```
chezmoi: open /dev/tty: no such device or address
```

**Comment by felipecrs** [comment]
Thanks a lot, @twpayne!
