### ISSUE TITLE
panic in windows

### ISSUE THREAD

**Issue by driftcrow** [twpayne/chezmoi#2777]
## Describe the bug

when apply in windows , it is panic.

## To reproduce

```console
$ chezmoi apply -v
```

## Output of command with the `--verbose` flag

```console
PS C:\WINDOWS\system32> chezmoi apply -v
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x994490]

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*EntryTypeSet).ContainsSourceStateEntry(0xc000791ea8, {0x0, 0x0})
        /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/entrytypeset.go:124 +0x30
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*EntryTypeFilter).IncludeSourceStateEntry(0xc0004543d0, {0x0, 0x0})
        /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/entrytypefilter.go:34 +0x2e
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Apply(0xc00022b760, {0x16c8d88, 0xc00050a6c0}, {0x16c8d88, 0xc00050a6c0}, {0x16c6658, 0xc00077d950}, {{0xc0004be1e0?, 0x5cac8f?}}, {{0x0, ...}}, ...)
        /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/sourcestate.go:580 +0xc5
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0xc0007a4000, {0x16c2470, 0xc0000380a8}, {0x16c8d88, 0xc00050a6c0}, {{0xc0004be1e0?, 0x0?}}, {0xc000455d20, 0x0, 0x1}, ...)
        /home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:561 +0x693
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runApplyCmd(0x0?, 0x0?, {0xc000455d20?, 0x0?, 0x0?})
        /home/runner/work/chezmoi/chezmoi/pkg/cmd/applycmd.go:42 +0xf6
github.com/spf13/cobra.(*Command).execute(0xc0002c9200, {0xc000455d00, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c8900)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0xc00071fdf8?, {0xc00006e050, 0x2, 0x3})
        /home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:1096 +0x78
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0x16b28c4, 0x6}, {0x16bfd00, 0x28}, {0x16b6480, 0x14}, {0x16b3430, 0xa}}, {0xc00006e050, 0x2, ...})
        /home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:285 +0x22a
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0x16b28c4, 0x6}, {0x16bfd00, 0x28}, {0x16b6480, 0x14}, {0x16b3430, 0xa}}, {0xc00006e050, 0x2, ...})
        /home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:108 +0xb1
main.main()
        /home/runner/work/chezmoi/chezmoi/main.go:26 +0x10c
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
What is the output of `chezmoi doctor`?

**Comment by driftcrow** [comment]
Thanks for help.
chezmoi doctor out:

> PS C:\WINDOWS\system32> chezmoi doctor
> RESULT    CHECK                MESSAGE
> ok        version              v2.30.1, commit ff0c704a9068c81b3ad301236d730fefcd9ce98c, built at 2023-02-11T19:17:48Z, built by goreleaser
> ok        latest-version       v2.30.1
> ok        os-arch              windows/amd64
> ok        systeminfo            ()
> ok        go-version           go1.20 (gc)
> ok        executable           ~/scoop/apps/chezmoi/current/chezmoi.exe
> ok        upgrade-method       replace-executable
> ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2023-02-15T16:07:15+08:00
> ok        source-dir           D:/workspace/repo/chezmoi/home is a directory
> ok        suspicious-entries   no suspicious entries
> warning   working-tree         D:/workspace/repo/chezmoi is a git working tree (dirty)
> ok        dest-dir             ~ is a directory
> ok        cd-command           found C:/WINDOWS/system32/cmd.exe
> ok        cd-args              'C:\\WINDOWS\\system32\\cmd.exe'
> info      diff-command         not set
> ok        edit-command         found C:/windows/system32/notepad.exe
> ok        edit-args            'C:\\windows\\system32\\notepad.exe'
> ok        git-command          found ~/scoop/shims/git.exe, version 2.39.2
> ok        merge-command        found ~/scoop/shims/vimdiff.exe
> ok        shell-command        found C:/WINDOWS/system32/cmd.exe
> ok        shell-args           'C:\\WINDOWS\\system32\\cmd.exe'
> info      age-command          age not found in $PATH
> info      gpg-command          gpg not found in $PATH
> info      pinentry-command     not set
> info      1password-command    op not found in $PATH
> info      bitwarden-command    bw not found in $PATH
> info      gopass-command       gopass not found in $PATH
> ok        keepassxc-command    found ~/scoop/shims/keepassxc-cli.exe, version 2.7.4
> info      keepassxc-db         not set
> info      keeper-command       keeper not found in $PATH
> info      lastpass-command     lpass not found in $PATH
> info      pass-command         pass not found in $PATH
> info      passhole-command     ph not found in $PATH
> info      vault-command        vault not found in $PATH
> info      secret-command       not set

**Comment by driftcrow** [comment]
other info:

> PS C:\WINDOWS\system32> chezmoi apply -v --debug
> 2023-02-16T10:43:10+08:00 INF persistentPreRunRootE args=["C:\\Users\\driftcrow\\scoop\\apps\\chezmoi\\current\\chezmoi.exe","apply","-v","--debug"] goVersion=go1.20 version={"builtBy":"goreleaser","commit":"ff0c704a9068c81b3ad301236d730fefcd9ce98c","date":"2023-02-11T19:17:48Z","version":"2.30.1"}
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=C:/Users/driftcrow/.config/chezmoi/chezmoistate.boltdb
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=D:/workspace/repo/chezmoi/home
> 2023-02-16T10:43:10+08:00 ERR Stat error="CreateFile D:/workspace/repo/chezmoi/home/.git: The system cannot find the file specified." component=system name=D:/workspace/repo/chezmoi/home/.git
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=D:/workspace/repo/chezmoi/.git
> 2023-02-16T10:43:10+08:00 ERR ReadFile error="open D:/workspace/repo/chezmoi/home/.chezmoiroot: The system cannot find the file specified." component=system data= name=D:/workspace/repo/chezmoi/home/.chezmoiroot size=0
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="\n{{ $full_name := promptStringOnce . \"full_name\" \"What is your f..." name=D:/workspace/repo/chezmoi/home/.chezmoi.toml.tmpl size=4016
> 2023-02-16T10:43:10+08:00 ERR Mkdir error="mkdir C:/Users/driftcrow/.config/chezmoi: Cannot create a file when that file already exists." component=system name=C:/Users/driftcrow/.config/chezmoi perm=511
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=C:/Users/driftcrow/.config/chezmoi
> 2023-02-16T10:43:10+08:00 INF Get bucket=configState component=persistentState key=configState value="{\"configTemplateContentsSHA256\":\"8c77e6fdd6a8470d3ef080c592c9bc87446969aeee5bb8a5f2db91d8dab6c595\"}"
> 2023-02-16T10:43:10+08:00 ERR ReadFile error="open D:/workspace/repo/chezmoi/home/.chezmoiversion: The system cannot find the file specified." component=system data= name=D:/workspace/repo/chezmoi/home/.chezmoiversion size=0
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=D:/workspace/repo/chezmoi/home
> 2023-02-16T10:43:10+08:00 INF Stat component=system name=D:/workspace/repo/chezmoi/home
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="editor = \"nvim\"\n\n[directions]\n\tup = \"k\"\n\tdown = \"j\"\n\tright = \"l\"..." name=D:/workspace/repo/chezmoi/home/.chezmoidata.toml size=77
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/.chezmoitemplates
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{\r\n  \"editor.bracketPairColorization.enabled\": true,\r\n  \"editor...." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/vscode size=505
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="#!/bin/bash\n\n\nif [ ! -d ~/.emacs.d ];then\n   git clone --depth 1..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/doom-emacs size=146
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="# General\n# ----------------------------------------------------..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/functions size=11506
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="#!/usr/bin/env bash\n\n# Make vim the default editor.\nexport EDITO..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/exports size=1165
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="# OSTYPE values used:\n#     - darwin: macOS\n#     - cygwin: Cygw..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/aliases size=18723
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="answer_is_yes() {\n    [[ \"$REPLY\" =~ ^[Yy]$ ]] \\\n        && retu..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/bash_utils size=4836
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="PYTHON_REQUIREMENTS=\"pip pysocks python-language-server black or..." name=D:/workspace/repo/chezmoi/home/.chezmoitemplates/python size=727
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="[\".oh-my-zsh\"]\n    type = \"archive\"\n    url = \"https://github.co..." name=D:/workspace/repo/chezmoi/home/.chezmoiexternal.toml size=1528
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data=".oh-my-zsh/cache/**\n.oh-my-zsh/custom/themes/powerlevel10k/**/*...." name=D:/workspace/repo/chezmoi/home/.chezmoiignore size=868
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data=".gitcookies\n.hgrc\n.ripgreprc\n" name=D:/workspace/repo/chezmoi/home/.chezmoiremove size=29
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/.chezmoiscripts
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/Documents
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/Documents/PowerShell
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_bin
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/autoload
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/exact_banner2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/fuz
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/fuz/Linux
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/fuz/Mac
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/fuz/Windows
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/Linux
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/bin
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/include
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/lib
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/share
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/share/cmake
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/darwin/share/cmake/rime
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/bin
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/include
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/lib
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/share
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/share/cmake
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/librime/win32/share/cmake/rime
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/local/templates
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/modules
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/modules/editor
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/modules/editor/meow
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/snippets
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_doom.d/snippets/org-mode
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local/bin
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local/share
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local/share/exact_rime
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local/share/exact_rime/imgs
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/dot_local/share/wallpapers
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/alacritty
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/code
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/code/User
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/environment.d
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/git
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/kitty
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/mpd
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/neofetch
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/ripgrep
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/systemd
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=D:/workspace/repo/chezmoi/home/private_dot_config/systemd/user
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=C:/Users/driftcrow/.local/share/rime
> 2023-02-16T10:43:10+08:00 INF ReadDir component=system name=C:/Users/driftcrow/.doom.d/local/banner
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{- if (eq .chezmoi.os \"darwin\") -}}\n#!/usr/bin/env bash\nxcode-s..." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_00-bootstrap-darwin.sh.tmpl size=382
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{ if (eq .chezmoi.os \"darwin\") -}}\n#!/bin/sh\n\nset -eufo pipefai..." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_10-install-packages-darwin.tmpl size=4992
> 2023-02-16T10:43:10+08:00 INF Get bucket=scriptState component=persistentState key=01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b value="{\n  \"name\": \".chezmoiscripts/10-install-packages-darwin\",\n  \"runAt\": \"2023-02-15T08:07:24.6793838Z\"\n}\n"
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{ if (eq .chezmoi.os \"linux\") -}}\n#!/bin/sh\n{{ if (eq .chezmoi...." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_10-install-packages-linux-arch.tmpl size=14107
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{ if (eq .chezmoi.os \"linux\") -}}\n{{ if (eq .chezmoi.osRelease...." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_10-install-packages-linux-ubuntu.sh.tmpl size=2615
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{ if (eq .chezmoi.os \"windows\") -}}\n\nscoop bucket add extras\nsc..." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_10-install-packages-windows.ps1.tmpl size=2615
> 2023-02-16T10:43:10+08:00 INF Get bucket=scriptState component=persistentState key=0231e5b884fa6fb2abd6f89073c9fdcecb533f3d39d818fb5fe728888cdc9b7c value="{\n  \"name\": \".chezmoiscripts/10-install-packages-windows.ps1\",\n  \"runAt\": \"2023-02-15T08:07:24.9756799Z\"\n}\n"
> 2023-02-16T10:43:10+08:00 INF ReadFile component=system data="{{ if (and (eq .chezmoi.os \"linux\") .kubernetes) -}}\n{{   if (eq..." name=D:/workspace/repo/chezmoi/home/.chezmoiscripts/run_once_before_20-install-kubernetes-ubuntu-linux.sh.tmpl size=3125
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x30 pc=0x954490]
> 
> goroutine 1 [running]:
> github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*EntryTypeSet).ContainsSourceStateEntry(0xc0007072a0, {0x0, 0x0})
>         /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/entrytypeset.go:124 +0x30
> github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*EntryTypeFilter).IncludeSourceStateEntry(0xc000281c40, {0x0, 0x0})
>         /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/entrytypefilter.go:34 +0x2e
> github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Apply(0xc00022b760, {0x1688d88, 0xc0004a0400}, {0x1688d88, 0xc0004a0400}, {0x16866b0, 0xc0003a4240}, {{0xc000037bf0?, 0x58ac8f?}}, {{0x0, ...}}, ...)
>         /home/runner/work/chezmoi/chezmoi/pkg/chezmoi/sourcestate.go:580 +0xc5
> github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0xc000718000, {0x1682470, 0xc0000380b8}, {0x1688d88, 0xc0004a0400}, {{0xc000037bf0?, 0x0?}}, {0xc00009b6a0, 0x0, 0x2}, ...)
>         /home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:561 +0x693
> github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runApplyCmd(0x0?, 0x0?, {0xc00009b6a0?, 0x0?, 0x0?})
>         /home/runner/work/chezmoi/chezmoi/pkg/cmd/applycmd.go:42 +0xf6
> github.com/spf13/cobra.(*Command).execute(0xc0002c8f00, {0xc00009b680, 0x2, 0x2})
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
> github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c8600)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
> github.com/spf13/cobra.(*Command).Execute(...)
>         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
> github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0xc00063fdf8?, {0xc00006e050, 0x3, 0x3})
>         /home/runner/work/chezmoi/chezmoi/pkg/cmd/config.go:1096 +0x78
> github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0x16728c4, 0x6}, {0x167fd00, 0x28}, {0x1676480, 0x14}, {0x1673430, 0xa}}, {0xc00006e050, 0x3, ...})
>         /home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:285 +0x22a
> github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0x16728c4, 0x6}, {0x167fd00, 0x28}, {0x1676480, 0x14}, {0x1673430, 0xa}}, {0xc00006e050, 0x3, ...})
>         /home/runner/work/chezmoi/chezmoi/pkg/cmd/cmd.go:108 +0xb1
> main.main()
>         /home/runner/work/chezmoi/chezmoi/main.go:26 +0x10c

**Comment by driftcrow** [comment]
PS C:\WINDOWS\system32> chezmoi data
{
  "chezmoi": {
    "arch": "amd64",
    "args": [
      "C:\\Users\\driftcrow\\scoop\\apps\\chezmoi\\current\\chezmoi.exe",
      "data"
    ],
    "cacheDir": "C:\\Users\\driftcrow\\.cache/chezmoi",
    "configFile": "C:/Users/driftcrow/.config/chezmoi/chezmoi.toml",
    "executable": "C:\\Users\\driftcrow\\scoop\\apps\\chezmoi\\current\\chezmoi.exe",
    "fqdnHostname": "driftcrow-PC",
    "gid": "S-1-5-21-2416827618-1515568788-2330222716-513",
    "group": "",
    "homeDir": "C:/Users/driftcrow",
    "hostname": "driftcrow-PC",
    "kernel": {},
    "os": "windows",
    "osRelease": {},
    "sourceDir": "D:/workspace/repo/chezmoi/home",
    "uid": "S-1-5-21-2416827618-1515568788-2330222716-1000",
    "username": "driftcrow-PC\\driftcrow",
    "version": {
      "builtBy": "goreleaser",
      "commit": "ff0c704a9068c81b3ad301236d730fefcd9ce98c",
      "date": "2023-02-11T19:17:48Z",
      "version": "2.30.1"
    },
    "windowsVersion": {
      "currentBuild": "19041",
      "currentMajorVersionNumber": 10,
      "currentMinorVersionNumber": 0,
      "currentVersion": "6.3",
      "editionID": "Professional",
      "productName": "Windows 10 Pro"
    },
    "workingTree": "D:/workspace/repo/chezmoi"
  },
  "develop": true,
  "devops": true,
  "directions": {
    "down": "j",
    "left": "h",
    "right": "l",
    "up": "k"
  },
  "editor": "nvim",
  "ephemeral": false,
  "full_name": "driftcrow",
  "game": true,
  "gl_noti_mail": "",
  "hacker": true,
  "headless": false,
  "hostname": "gowin",
  "is_mobile": false,
  "is_remote": false,
  "is_surface": false,
  "is_wsl": false,
  "isolated": false,
  "kubernetes": false,
  "minimal": false,
  "personal": true,
  "purpose": "work"
}

**Comment by twpayne** [comment]
Thanks for the extra info. Are your dotfiles online somewhere so I can try to reproduce the problem? This is definitely a bug in chezmoi.

**Comment by driftcrow** [comment]
This is my repo for windows [my chezmoi](https://github.com/driftcrow/chezmoi.git)

**Comment by twpayne** [comment]
Thanks very much for reporting this and providing information so I could reproduce the problem.

This was a bug in chezmoi that was triggered by your externals. Specifically, in [your `.chezmoiexternal.toml` file](https://github.com/driftcrow/chezmoi/blob/59ae3149362f9334959ba9647406cc8e97630b1c/home/.chezmoiexternal.toml#L31-L36), the `$fontDir` variable was not being set on Windows, which lead to the external font files having absolute paths. chezmoi did not detect this correctly on Windows, which later caused the panic.

#2796 fixes it. You'll now get an error on Windows if any of your externals have absolute paths.

**Comment by driftcrow** [comment]
Oh, I forget that ,  cause not mentioned it in debug information.  thanks for your work
