### ISSUE TITLE
$XDG_CONFIG_HOME Directory

### ISSUE THREAD

**Issue by PurpleMyst** [twpayne/chezmoi#2779]
## What exactly are you trying to do?

As per the title, I'd like to automatically place files that should be in `$XDG_CONFIG_HOME` based on the operating system. This, for example, means that I'd like Neovim's config directory to be placed in `~/AppData/Local` on Windows and `~/.config` on Linux (more specifically, Termux, but the specifics are not a cause of concern for the issue itself) 

## What have you tried so far?

I am able to do this non-automatically by doing it as indicated in the user guide, with includes and the like. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.30.1, commit ff0c704a9068c81b3ad301236d730fefcd9ce98c, built at 2023-02-11T19:17:48Z, built by goreleaser
ok        latest-version       v2.30.1
ok        os-arch              windows/amd64
ok        systeminfo           Microsoft Windows 11 Pro (10.0.22621 N/A Build 22621)
ok        go-version           go1.20 (gc)
ok        executable           ~/scoop/apps/chezmoi/current/chezmoi.exe
ok        upgrade-method       replace-executable
ok        config-file          no config file found
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        cd-command           found C:/Windows/system32/cmd.exe
ok        cd-args              'C:\\Windows\\system32\\cmd.exe'
info      diff-command         not set
ok        edit-command         found C:/Windows/system32/notepad.exe
ok        edit-args            'C:\\Windows\\system32\\notepad.exe'
ok        git-command          found ~/scoop/shims/git.exe, version 2.39.2
warning   merge-command        vimdiff not found in $PATH
ok        shell-command        found C:/Windows/system32/cmd.exe
ok        shell-args           'C:\\Windows\\system32\\cmd.exe'
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

**Comment by bradenhilton** [comment]
https://github.com/twpayne/chezmoi/issues/2273

**Comment by halostatue** [comment]
It’s worth noting that the XDG BDS is specific to Linux and treating `%XDG_CONFIG_HOME%` as `%USERPROFILE%\AppData\local` would not be entirely correct, just as `$HOME/Library/Application Support` would be only partially correct on macOS. It’s completely dependent on the applications in question.

I have a number of applications (including chezmoi) that see `$XDG_CONFIG_HOME` as `~/.config` and some (far rarer) that see it as `~/Library/Application Support` (`tfvm` uses `~/Library/Caches` as `$XDG_CACHE_HOME`).

**Comment by PurpleMyst** [comment]
You're entirely right. Something like "hey, i want the things I put in this directory to end up here" (as proposed in #2273) is the way to go

**Comment by halostatue** [comment]
I’m going to close this as a duplicate in favour of #2273.
