### ISSUE TITLE
Use folders as source for chezmoiexternal

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#2783]
## Is your feature request related to a problem? Please describe.

I use Windows and WSL. I store my SSH private key, public key, the config file, authorized keys and known hosts in my Windows profile so that applications like Windows Terminal, PowerShell and VS Code can use them.

However, some times I also use SSH from within WSL, and in that case, I'd like to have my `~/.ssh` in sync with my Windows' one.

## Describe the solution you'd like

```yaml
# .chezmoiexternal.yaml

".ssh":
  type: directory
  url: /mnt/c/Users/felip/.ssh
  exact: true
```

## Describe alternatives you've considered

The following script works:

```bash
#!/bin/bash

win_home="/mnt/c/Users/felip"
if [[ -f "${win_home}/.ssh/id_rsa" ]]; then
  cp -rf "${win_home}/.ssh/." "${HOME}/.ssh"
fi
```

But allowing me to use as a `chezmoiexternal` would give me the benefit of `diff`ing.

## Additional context

I actually also need to `chmod 600 ~/.ssh`, which is currently not possible with `chezmoiexternal`s but this is a separate topic.

Also, let me know what you think. Maybe I'm over engineering it.

**Comment by twpayne** [comment]
Here I would be tempted to use one of the following approaches:

* Use your existing approach, but with `rsync` instead of `cp`.
* Put the contents of `.ssh` in an encrypted archive and use `.chezmoiexternal`s for `${win_home}/.ssh` and `${HOME}/.ssh`.
* Use chezmoi to manage your home directory inside WSL, and configure `.chezmoiignore` so that only `.ssh` is populated.

**Comment by felipecrs** [comment]
> Use your existing approach, but with rsync instead of cp.

I actually realized this too and did it yesterday: 😅https://github.com/felipecrs/dotfiles/commit/39983f4fecf64e31890b5b50e3db1314e9bba6f3

> * Put the contents of `.ssh` in an encrypted archive and use `.chezmoiexternal`s for `${win_home}/.ssh` and `${HOME}/.ssh`.

I just don't know how easy it would be to keep up with my changes to `known_hosts` or `authorized_keys`, but other than that, it's a reasonable suggestion.

> Use chezmoi to manage your home directory inside WSL, and configure .chezmoiignore so that only .ssh is populated.

This I did not understand.

But anyway, if you don't think this is something that is worth being implemented, feel free to close it, no worries.

**Comment by twpayne** [comment]
> > Use chezmoi to manage your home directory inside WSL, and configure .chezmoiignore so that only .ssh is populated.
> 
> This I did not understand.

What I meant is that, assuming I understand correctly:

1. You have two home directories on your machine, one in Windows, and one in WSL.
2. You would like to sync the `.ssh` subdirectory from your Windows home directory to your WSL home directory.
3. Currently, your Windows home directory is managed with chezmoi, but your WSL home directory is not.
4. Would it make sense to manage both your Windows and your WSL home directories with chezmoi?

Separately, a different possible solution would be to use a directory synchronization mechanism between your `.ssh` directory in Windows and your `.ssh` directory in WSL. This would make updates to `known_hosts` bi-directional.

**Comment by felipecrs** [comment]
> Currently, your Windows home directory is managed with chezmoi, but your WSL home directory is not.

Ops, not quite. I only manage my WSL home with Chezmoi. I don't use anything to manage my Windows home (currently).

> Separately, a different possible solution would be to use a directory synchronization mechanism between your .ssh directory in Windows and your .ssh directory in WSL. This would make updates to known_hosts bi-directional.

That's true and it's a good idea. I think `rsync` can do it as well.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
