### ISSUE TITLE
Can't manually run a script that is in .chezmoiscripts

### ISSUE THREAD

**Issue by alexdelprete** [twpayne/chezmoi#2789]
## What exactly are you trying to do?

Manually run a script (`install-packages.sh`) that is under `.chezmoiscripts` as `run_onchange_install-packages.sh.tmpl`

## What have you tried so far?

`chezmoi cat ~/install-packages.sh | bash`

This worked, when the `run_*` scripts lived under the source state dir, now that I moved them in .chezmoiscripts, I can't the cat command gives me this error:

```console
❯ chezmoi cat ~/install-packages.sh
chezmoi: /root/install-packages.sh: not in source state
```

I also tried querying chezmoi for the target-path, but when I cat it, it gives me the same error:

```console
❯ chezmoi target-path ~/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
/root/source/.chezmoiscripts/install-packages.sh

❯ chezmoi cat /root/source/.chezmoiscripts/install-packages.sh
chezmoi: /root/source/.chezmoiscripts/install-packages.sh: not in source state

```

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
❯ chezmoi --verbose cat ~/install-packages.sh
chezmoi: /root/install-packages.sh: not in source state
```

## Output of `chezmoi doctor`

<details>

```console
RESULT    CHECK                MESSAGE
warning   version              v2.30.0, built by nixpkgs
warning   latest-version       v2.31.0
ok        os-arch              linux/amd64 (Ubuntu 22.10 (Kinetic Kudu))
ok        uname                Linux docker 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.19.5 (gc)
ok        executable           /nix/store/p6mx7b9nmfpvv8110vrgnz90lkyhd3f6-chezmoi-2.30.0/bin/chezmoi
ok        upgrade-method       upgrade-package
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-08-31T00:22:36+02:00
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
ok        suspicious-entries   no suspicious entries
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /usr/bin/zsh
ok        cd-args              /usr/bin/zsh
info      diff-command         not set
ok        edit-command         found /usr/bin/nano
ok        edit-args            nano
ok        git-command          found /usr/bin/git, version 2.37.2
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /usr/bin/zsh
ok        shell-args           /usr/bin/zsh
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.35
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found ~/.nix-profile/bin/bw, version 2023.1.0
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

My `source-dir` is `~/.local/share/chezmoi` and I have a `~/.local/share/chezmoi/.chezmoiroot` file that contains `source` so my source state files, along with the `.chezmoiscripts` directory are under the directory `~/.local/share/chezmoi/source`

**Comment by twpayne** [comment]
> ```
> ❯ chezmoi cat ~/install-packages.sh
> chezmoi: /root/install-packages.sh: not in source state
> ```

The home directory here is `/root`. Are you running chezmoi as root deliberately?

**Comment by alexdelprete** [comment]
> Are you running chezmoi as root deliberately?

Yes.

Meanwhile, I found the answer to the issue: the target path is `~/.chezmoiscripts/install-packages.sh`, and it's working fine, I can execute the script now, but I don't know if that's how it was supposed to work. I thought .chezmoiscripts should be "transparent", and indeed it's not created in the destination.

Source-path confirms it's the correct path:
```
❯ chezmoi source-path ~/.chezmoiscripts/install-packages.sh
/root/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
```

Then I double-checked with target-path, and it's not correct: (`source` is added, I guess because of `.chezmoiroot`)
```
❯ chezmoi target-path ~/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
/root/source/.chezmoiscripts/install-packages.sh
```

If I test the result path of target-path, it gives me the error:
```
❯ chezmoi cat ~/source/.chezmoiscripts/install-packages.sh
chezmoi: /root/source/.chezmoiscripts/install-packages.sh: not in source state
```

So target-path is reporting a wrong path. I don't know if it's a bug or not.

**Comment by twpayne** [comment]
Thanks for the investigation. This sounds like a bug in chezmoi.

**Comment by alexdelprete** [comment]
> Thanks for the investigation. This sounds like a bug in chezmoi.

My pleasure, and thanks for your work Tom.

**Comment by alexdelprete** [comment]
Tom, I found an another example: I noticed my `id_ed25519` ssh key was not being created (I pull it from github as per docs example). I thought the template wasn't working, so I tinkered a lot with it, but couldn't find any issue. Then I thought about this bug...so I did the same tests I did before: the `.chezmoiroot` directory is being added to the target-path, that is why (I guess) the key is not being created.

Do you think the bug is triggered because I'm using root, or it's because I use .chezmoiroot?

```console
❯ cm source-path .ssh/id_ed25519
/root/.local/share/chezmoi/source/private_dot_ssh/id_ed25519.tmpl

❯ cm target-path /root/.local/share/chezmoi/source/private_dot_ssh/id_ed25519.tmpl
/root/source/.ssh/id_ed25519

❯ cm cat /root/source/.ssh/id_ed25519
chezmoi: /root/source/.ssh/id_ed25519: not in source state
```

**Comment by twpayne** [comment]
Hmm, this is suspicious. I tried to reproduce this bug in ee84d55853e0d55a25196738c0d28e25450a25ef, but chezmoi seems to behave as expected.

Are your dotfiles online somewhere so I can reproduce what you're seeing, or do you have a small case that reproduces the issue?

**Comment by alexdelprete** [comment]
> Are your dotfiles online somewhere so I can reproduce what you're seeing

Tom, my repo is private as of right now because I'm not yet an expert with chezmoi so I will make it public only once I'm sure there's no sensitive information left in public. :)

I gave you access to the repo, let me know if you can see it, and thanks for the support.

**Comment by twpayne** [comment]
Thank you, I will investigate.

**Comment by alexdelprete** [comment]
If you need me to test something please let me know.

**Comment by twpayne** [comment]
OK, I did a bit of digging. I think there's some mismatch between your commands and the contents of your repo. Some of these might be because you've modified your repo since opening this issue.

> ```
> ❯ chezmoi cat /root/source/.ssh/id_ed25519
> chezmoi: /root/source/.ssh/id_ed25519: not in source state
> ```

This file doesn't exist in your source state. You do have `.ssh/$USERNAME_ed25519_256` though.

> ```
> ❯ chezmoi target-path ~/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_install-packages.sh.tmpl
> /root/source/.chezmoiscripts/install-packages.sh
> ```

This file also doesn't exist. You do have `source/.chezmoiscripts/run_onchange_after_install-packages.sh.tmpl` though.

I also saw in the your dotfiles repo that `~/.local/share/chezmoi/.chezmoiroot` was managed by chezmoi. It shouldn't be. Please remove this file (`chezmoi forget ~/.local/share/chezmoi/.chezmoiroot`).

Please could you fix the above and tell me what still isn't working. Maybe send me a commit hash so I can check out the same set of files as you that demonstrate problems.

**Comment by alexdelprete** [comment]
> This file doesn't exist in your source state. You do have `.ssh/$USERNAME_ed25519_256` though.

Yes, I renamed it.

> This file also doesn't exist. You do have `source/.chezmoiscripts/run_onchange_after_install-packages.sh.tmpl` though.

that is a template, but when I want to refer to it to execute it manually, the name of the file is `install-packages.sh`. The problem is the target-path of this file.

I'll repeat the test of the OP (`master` branch, commit `ebbcac5`):

Since I expect .chezmoiscripts and .chezmoiroot to be "transparent" in the target state, I tried pointing to the file through `chezmoi cat` in the $HOME folder:

Here you can see `~` is not where chezmoi "sees" the file
```shell
❯ chezmoi cat ~/install-packages.sh
chezmoi: /root/install-packages.sh: not in source state
```
I double check with source-path and CM confirms the result
```shell
❯ chezmoi source-path ~/install-packages.sh
chezmoi: /root/install-packages.sh: not in source state
```

So I found out that the folder in the target seen by chezmoi is `~/.chezmoiscripts/`:
```shell
❯ chezmoi cat ~/.chezmoiscripts/install-packages.sh
[it correctly shows the content of the script file]
```

I double check with source-path and CM confirms the path is correct, since it points back to the template file (notice the presence of the `.chezmoiroot` folder in the path):
```shell
❯ chezmoi source-path ~/.chezmoiscripts/install-packages.sh
/root/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_after_install-packages.sh.tmpl
```

Now I double-check the output of the `source-path` command with `target-path` and I notice that now `.chezmoiroot` is not in the resulting path (maybe there was an upgrade to chezmoi made after [this post](https://github.com/twpayne/chezmoi/issues/2789#issuecomment-1442229702)?):
```shell
❯ chezmoi target-path ~/.local/share/chezmoi/source/.chezmoiscripts/run_onchange_after_install-packages.sh.tmpl
/root/.chezmoiscripts/install-packages.sh
```

Anyway, based on this test, it seems that the only possible problem left is that scripts in .chezmoiscripts can be used with `~/.chezmoiscripts`, but reading the docs:

![image](https://user-images.githubusercontent.com/7027842/222541747-9de74465-b6b9-428b-ba65-abf3742e651d.png)

I expected .chezmoiscripts to be "transparent" in the target, so if I interpret the docs correctly `chezmoi cat ~/install-packages.sh` should work.

> I also saw in the your dotfiles repo that `~/.local/share/chezmoi/.chezmoiroot` was managed by chezmoi. It shouldn't be. Please remove this file (`chezmoi forget ~/.local/share/chezmoi/.chezmoiroot`).

I ran these tests before running the forget command, in order to not introduce another change. Regarding this point, here's what the docs say:

![image](https://user-images.githubusercontent.com/7027842/222540828-56d17790-91d8-4630-bdd9-15a0f5ab9f73.png)

Question: If I recall correctly (some months have passed) I simply created the file by editing it and saving, I didn't `chezmoi add` it. Maybe the docs should point out how to properly create the file so it won't be managed by chezmoi.

Thanks for the help.

**Comment by twpayne** [comment]
Apologies for the very late response. 

> I expected `.chezmoiscripts` to be "transparent" in the target, so if I interpret the docs correctly `chezmoi cat ~/install-packages.sh` should work.

`.chezmoiscripts` isn't transparent. It has the effect that all files in `.chezmoiscripts` are expected to be `run_` scripts and the benefit that your scripts and your dotfiles no longer share the same target namespace.

The easiest way to find how to run your scripts is to run:

```console
$ chezmoi managed --include=scripts
.chezmoiscripts/install-packages.sh
```

Note that chezmoi's attributes are removed from the filename.

You can then run each script individually with `chezmoi apply`, for example:

```console
$ chezmoi apply ~/.chezmoiscripts/install-packages.sh
```

> Question: If I recall correctly (some months have passed) I simply created the file by editing it and saving, I didn't `chezmoi add` it. Maybe the docs should point out how to properly create the file so it won't be managed by chezmoi.

By default, chezmoi doesn't manage files. You have to explicitly `chezmoi add` the files you want to manage.

Hope this resolves this issue. Please re-open if needed.
