### ISSUE TITLE
Add Dashlane support

### ISSUE THREAD

**Issue by XaF** [twpayne/chezmoi#2791]
## Is your feature request related to a problem? Please describe.
[Dashlane](https://www.dashlane.com/) is a password manager that could be integrated with chezmoi.
This was initially open then closed-not-solved in #1037.

## Describe the solution you'd like
It would be great if chezmoi include a template function called `dashlane` that allowed users to retrieve secrets from Dashlane.
It could even be `dashlanePassword` for a password entry, and `dashlaneNote` for a secure note.

## Additional context
Since #1037 there is now an experimental-but-official CLI for Dashlane which is available at [Dashlane/dashlane-cli](https://github.com/Dashlane/dashlane-cli). This supports outputting passwords in the JSON format, and can be either built locally or used through binaries provided with releases. This is also seems to be actively developed at the moment.

**Comment by twpayne** [comment]
Sure. Could you post the output of:

```console
$ dcli password --output json filter
```

for some `filter` so I have some example output to test with, please?

**Comment by XaF** [comment]
The filters are very basic "string matching" it seems.

The format is:
```json
[
    {
        "title": "<name of the entry>",
        "useFixedUrl": "<true/false>",
        "login": "<login>",
        "status": "ACCOUNT_NOT_VERIFIED",
        "note": "<any note>",
        "autoLogin": "<true/false>",
        "modificationDatetime": "<timestamp>",
        "checked": "<true/false>",
        "id": "<id>",
        "anonId": "<anonymous id>",
        "localeFormat": "UNIVERSAL",
        "password": "<password>",
        "creationDatetime": "<timestamp>",
        "userModificationDatetime": "<timestamp>",
        "lastBackupTime": "<timestamp>",
        "autoProtected": "<true/false>",
        "strength": "<int representing password strenght - probably a percentage 0-100>",
        "subdomainOnly": "<true/false>"
    },
    ...
]
```

When a single match is found, only one entry is returned in the list, but it still returns the list.
When called with `--output json` and no `filter`, it returns the entire list of password entries.

**Comment by XaF** [comment]
The `note|n` command returns the content of the note directly on the output, without any formatting:

```
$ dcli n testdata
This is my

note
.
```

**Comment by XaF** [comment]
When calling commands with a filter that does not return any results:

```
$ dcli password DoesNotExist
Error: No credential with this name found
    at selectCredential (xxxxx\getPasswords.js:69:15)
    at async getPassword (xxxxx\getPasswords.js:92:32)
    at async Command.<anonymous> (xxxxx\index.js:55:9)
    at async Command.parseAsync (xxxxx\command.js:917:5)
$ echo $?
1
$
```

```
$ dcli note DoesNotExist
Error: No note found
    at getNote (xxxxx\getSecureNotes.js:37:15)
    at async Command.<anonymous> (xxxxx\index.js:87:5)
    at async Command.parseAsync (xxxxx\command.js:917:5)
$ echo $?
1
$
```

So note that even if the `password` command always returns a list, it does not return an empty list when not found, but an error with return code 1.
