### ISSUE TITLE
zsh segment for chezmoi subshell

### ISSUE THREAD

**Issue by matiux** [twpayne/chezmoi#2800]
I'm wondering if there's a way to know if I am in chezmoi subshell. If I can understand this, I can create zsh segment that show me when I'm inside a chezmoi subshell. Obviously it would be great if this thing already exists.

**Comment by twpayne** [comment]
Yes, since #2743, multiple `CHEZMOI_` environment variables are set inside `chezmoi cd`. To see them:

```console
$ chezmoi cd
$ set | grep ^CHEZMOI_
```

**Comment by matiux** [comment]
Thanks @twpayne 
I currently  use `powerline10k` theme for oh-my-zsh. So I have created this function
```bash
  function prompt_chezmoisubshell() {
    if [ ! -z "${CHEZMOI}" ]; then
      p10k segment -b 'maroon' -f 'darkred' -i '🏠' -t "chezmoi subshell"
    fi
  }
```
to show when the user is inside the chezmoi subshell. It would be nice chose a more appropriate icon

**Comment by twpayne** [comment]
Very nice. I hope your question is now answered.
