### ISSUE TITLE
Escaping dots in `setValueAtPath` or `deleteValueAtPath`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#2813]
## Is your feature request related to a problem? Please describe.

I'm now trying to use modify templates to edit my VS Code config, and its keys are full of dots:

```json
{
    "window.titleBarStyle": "custom",
    "window.zoomLevel": 1,
    "editor.fontFamily": "FiraCode Nerd Font Mono"
}
```

However, these two chezmoi template functions interpret dots as nesting for keys.

## Describe the solution you'd like

If there was a way to escape them, it would be nice. Perhaps:

```
{{ setValueAtPath "window\.titleBarStyle" "custom" }}
```

## Describe alternatives you've considered

Fortunately, for my case I only need to set top level keys, so I can still use Sprig's `set`.

## Additional context

N/A

**Comment by bradenhilton** [comment]
Maybe they should optionally accept a list of keys instead of splitting a path string?

**Comment by twpayne** [comment]
> Maybe they should optionally accept a list of keys instead of splitting a path string?

Actually, they already do: https://www.chezmoi.io/reference/templates/functions/setValueAtPath/

> `setValueAtPath` modifies dict to set the value at path to value and returns dict. path can be either a string containing a .-separated list of keys **or a list of keys**"

So @felipecrs you should already be able to do:

```
{{ setValueAtPath (list "window.titleBarStyle") "custom" }}
```

**Comment by felipecrs** [comment]
Oh, that's great. Thank you.

**Comment by bradenhilton** [comment]
@twpayne Ahh, I was looking at the code and got confused after going back and forth from `keysFromPath` (`string`) and `setValueAtPathTemplateFunc` (`any`) a few times.
