### ISSUE TITLE
Super confusing user-experience.

### ISSUE THREAD

**Issue by EvanCarroll** [twpayne/chezmoi#2818]
At this point, I really don't like this user experience at all. It's the same functionality as `git` with all new names for reasons I don't understand.

Look what in my `~/.profile`

```shell
❯ grep perl ~/.profile
export MANPATH=$HOME/perl5/man:$MANPATH
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
```

That's old. Looks what is iin `dot_profile`

```shell
❯ chezmoi cd
❯ grep perl dot_profile
export MANPATH=$HOME/perl5/man:$MANPATH
if $(perl -Mlocal::lib 2>/dev/null); then
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
```

Let's go back to home, and run `chezmoi apply` and choose to overwrite...

```shell
❯ cd
❯ chezmoi apply
❯ grep perl dot_profile
export MANPATH=$HOME/perl5/man:$MANPATH
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
```

So that's still old. Now let's look what is in `dot_profile`..

```shell
❯ chezmoi cd
❯ grep perl dot_profile
export MANPATH=$HOME/perl5/man:$MANPATH
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
```

So apply doesn't change the actual dotfile, it changes the git repo?

Let's read the documentation for `chezmoi apply`,

>If no targets are specified, the state of all targets are ensured. If a target has been modified since chezmoi last wrote it then the user will be prompted if they want to overwrite the file.

What is a target in this context? A file in the home dir or a file in the git dir? Why is this so complex?

Let's go back and see what the status is.

```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dot_profile

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        dot_gitconfig

no changes added to commit (use "git add" and/or "git commit -a")
```

So apply and override, overrides the git directory? Ok let's see what init does?

> Setup the source directory, generate the config file, and optionally update the destination directory to match the **target state.**

So init the "target state" is the stuff in the homedir, but in apply "all targets" is stuff in the git repo? 

I don't understand this vocabulary, and this violates all expectations I have about operation.

**Comment by twpayne** [comment]
It's OK, no one's forcing you to use chezmoi and you're free to use any of the thousands of [other dotfile managers](https://dotfiles.github.io/utilities/) out there.

If you do want to learn more about chezmoi, I would encourage you to read the [quick start guide](https://www.chezmoi.io/quick-start/) and the [concepts in the reference guide](https://www.chezmoi.io/reference/concepts/).

**Comment by EvanCarroll** [comment]
I read all of your docs. I even cited them in the answer.

**Comment by bradenhilton** [comment]
@EvanCarroll I cannot reproduce in an empty Docker image:

```console
$ grep perl ~/.profile
export MANPATH=$HOME/perl5/man:$MANPATH
eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
$ chezmoi cd
$ grep perl dot_profile
export MANPATH=$HOME/perl5/man:$MANPATH
if $(perl -Mlocal::lib 2>/dev/null); then
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
$ cd
$ chezmoi apply
$ chezmoi cd
$ grep perl dot_profile
export MANPATH=$HOME/perl5/man:$MANPATH
if $(perl -Mlocal::lib 2>/dev/null); then
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
$ cd
$ grep perl ~/.profile
export MANPATH=$HOME/perl5/man:$MANPATH
if $(perl -Mlocal::lib 2>/dev/null); then
        eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
path[1,0]=$HOME/perl5/bin
```

**Comment by twpayne** [comment]
@bradenhilton thanks for testing here, but when a user takes a confrontational attitude like @EvanCarroll does here there then it is better not to engage with them.

Engaging with such users quickly leads to burnout in maintainers. See [entitlement in open source](https://tylercipriani.com/blog/2023/01/15/entitlement-burnout-and-toxicity/).
