### ISSUE TITLE
chezmoi cd should make it clear it's a subshell, and potentially prohibit further `chezmoi cd`

### ISSUE THREAD

**Issue by EvanCarroll** [twpayne/chezmoi#2821]
This is a minor UX improvement, `chezmoi cd` spawns a subshell. 

```shell
❯ chezmoi cd
❯ chezmoi cd
❯ chezmoi cd
❯ chezmoi cd
❯ chezmoi cd
❯ ps | grep chezmoi
 355766 pts/4    00:00:00 chezmoi
 355806 pts/4    00:00:00 chezmoi
 355844 pts/4    00:00:00 chezmoi
 355883 pts/4    00:00:00 chezmoi
 355921 pts/4    00:00:00 chezmoi
❯ exit
❯ ps | grep chezmoi
 355766 pts/4    00:00:00 chezmoi
 355806 pts/4    00:00:00 chezmoi
 355844 pts/4    00:00:00 chezmoi
 355883 pts/4    00:00:00 chezmoi
❯ exit
❯ exit
❯ ps | grep chezmoi
 355766 pts/4    00:00:00 chezmoi
 355806 pts/4    00:00:00 chezmoi
❯ exit
❯ ps | grep chezmoi
 355766 pts/4    00:00:00 chezmoi
❯ exit
❯ echo "I am back"
I am back
```

It is easy to forget you ran it, and exit that directory and to continue inside the chezmoi subshell. It would be nice to at least make it demonstrably different, so users know what happened.

    CHEZMOI_SUBSHELL=1 PS1="chezmoi >" sh

Would be great. Even better though if you're setting a custom `CHEZMOI_SUBSHELL` stop the user from running a subsequent `chezmoi cd` if it's set.

Steroids, security and containers.
====

Even better one more time? If the user has user-namespaces (and most do), and they're on Linux you can use them and ensure that _if_ the shell was compromised such as by giving access chezmoi on a shared host when you do not intend to give shell access you can stop the user from obtaining shell access or read-access on the rest of the filesystem with `chezmoi cd`.

**Comment by twpayne** [comment]
See #2800. chezmoi already sets the `CHEZMOI=1` environment variable so you can modify your prompt/shell to behave as required. Overriding `$PS1` directly is likely to mess with the user's existing shell configuration.

**Comment by bradenhilton** [comment]
We could certainly improve the documentation for setting the prompt using the environment variables and increase its visibility, but setting the prompt is OS/shell dependent and could get quite messy, so it's better to let the user set it how they want.

**Comment by EvanCarroll** [comment]
That's technically true, @bradenhilton. But [`PS1` is POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html). Without POSIX, "shell" can mean anything and there is no definition/spec (afaik). Windows certainly violates this though - however, if your prompt is literal (no variables) you can set it by duplicating the prompt to PROMPT: [this is what yadm does](https://github.com/TheLocehiliosan/yadm/blob/2d4dcd05ef78b7f4776a89809774fda9d3b713d5/yadm#L1111)

Side note, yadm does have a lot more logic with regard to disabling shell features (because the goal is always to allow it to the minimal) to support what your users are likely to want. Rather than jumping through all those hoops though I would just only spawn `sh` if it's there. Certainly easier.

**Comment by bradenhilton** [comment]
PowerShell is the biggest outlier here, it requires a [`prompt` function](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts?view=powershell-7.3#how-to-customize-the-prompt) from what I understand.

**Comment by EvanCarroll** [comment]
@bradenhilton I think it just requires a `PROMPT` environmental variable (rather than or in addition to `PS1`). YADM, sets both of them

> If you use the set command without any parameters, the current environment settings are displayed. These settings usually include the `COMSPEC` and `PATH` environment variables, which are used to help find programs on disk. Two other environment variables used by Windows are `PROMPT` and `DIRCMD`.

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1

**Comment by bradenhilton** [comment]
@EvanCarroll

```console
PowerShell 7.3.3

~
❯ $env:PROMPT = "chezmoi>"

~
❯ Get-ChildItem -Path env:* -Include 'PROMPT'

Name                           Value
----                           -----
PROMPT                         chezmoi>


~
❯ prompt

~
❯

~
❯ $prompt = prompt; function prompt { $prompt -replace '❯', 'chezmoi ❯' }

~
chezmoi ❯
```

**Comment by EvanCarroll** [comment]
Is that changing the prompt for the _current_ shell or for the _subshell_ you're spawning?

**Comment by bradenhilton** [comment]
That particular example is for the current shell, spawning a subshell changes nothing.

**Comment by EvanCarroll** [comment]
Guessing that's just a cmd.exe thing then? =(

**Comment by halostatue** [comment]
@EvanCarroll it’s not just PowerShell. I use `fish` and it requires a `fish_prompt` function. Elvish uses `edit:prompt` and `edit:rprompt` by setting functions to those variables.

**Comment by EvanCarroll** [comment]
#1353

**Comment by halostatue** [comment]
More relevant would be #2800 since we now have environment variables from which we can build this on a per-shell basis.
