### ISSUE TITLE
chezmoi: fork/exec /usr/bin/git: argument list too long

### ISSUE THREAD

**Issue by wereket** [twpayne/chezmoi#2838]
chezmoi add file

chezmoi: fork/exec /usr/bin/git: argument list too long

**Comment by halostatue** [comment]
Can you try with `chezmoi --use-builtin-git add file`?

To be able to debug this further, we need the output of `chezmoi doctor`.

**Comment by wereket** [comment]
chezmoi doctor

RESULT    CHECK                MESSAGE
ok        version              v2.28.0, commit 8e9ed2eee04b708b4d7531863e47b5c5a876050f, built at 2022-12-18T18:40:56Z, built by goreleaser
warning   latest-version       v2.31.1
ok        os-arch              linux/amd64 (Void)
ok        uname                Linux void-live 6.1.15_1 #1 SMP PREEMPT_DYNAMIC Tue Mar  7 00:44:23 UTC 2023 x86_64 GNU/Linux
ok        go-version           go1.19.4 (gc)
ok        executable           ~/.local/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2022-12-27T15:50:29-05:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found /usr/bin/vim
ok        edit-args            /usr/bin/vim
ok        git-command          found /usr/bin/git, version 2.39.2
warning   merge-command        vimdiff not found in $PATH
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.4.0
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
ok        pass-command         found /usr/bin/pass, version 1.7.4
info      passhole-command     ph not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

**Comment by wereket** [comment]
chezmoi --use-builtin-git add bookmarks.html
chezmoi: unknown command "bookmarks.html" for "chezmoi"

chezmoi --use-builtin-git add file bookmarks.html
chezmoi: unknown command "file" for "chezmoi"

**Comment by twpayne** [comment]
@wereket please us a provided [issue template](https://github.com/twpayne/chezmoi/issues/new/choose) when opening an issue because they ask for important information that we need when investigating problems. If you do not do this you are wasting our time.

> chezmoi --use-builtin-git add bookmarks.html chezmoi: unknown command "bookmarks.html" for "chezmoi"

This cannot be the command you typed as the output does not match the command.

What is the output of:

    chezmoi --debug add file

From looking at what you have reported so far, I suspect that you have messed up your shell configuration and strange things are happening when you try to run `chezmoi`.

**Comment by wereket** [comment]
sorry  it was an error from my side, somehow it was related from me adding
.emacs.d

**Comment by twpayne** [comment]
Great! Glad that the problem is solved :) Thanks for reporting back :)
