### ISSUE TITLE
How to include files outside home that aren't repos?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [twpayne/chezmoi#2840]
## What exactly are you trying to do?

Totally new to Chezmoi and also kind of a linux noobie in general; how can I include other "external" files that I'd like to monitor for changes, such as `/usr/share/vim/vimrc`?

## What have you tried so far?

I read the dox on external files, but they all describe semi-complicated things involving repos, extracting from repos, etc., I just want to add other local files outside of the Home directory.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by halostatue** [comment]
chezmoi really isn’t for managing whole systems, but home directories, so you probably don’t want to add `/usr/share/vim/vimrc`. Nothing *stops* you from doing `chezmoi add /usr/share/vim/vimrc`, but I don’t think it will do what you want it to do.

It’s worth noting that chezmoi doesn’t *monitor* files for changes. That is, if something changes in `/usr/share/vim/vimrc`, you would still need to re-add the file whenever it changes (chezmoi can *detect* changes between current state and target state, but it does not monitor). chezmoi will compute the target state based on the source state, which means that simply doing `chezmoi apply` will prompt you to overwrite `/usr/share/vimrc`.

**Comment by twpayne** [comment]
There is a FAQ entries for this exact question: https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-i-use-chezmoi-to-manage-files-outside-my-home-directory

**Comment by bradenhilton** [comment]
@YouveGotMeowxy 

A few clarifying questions:

- Do you have `~/.vimrc` in chezmoi's source state? (`<chezmoi source-directory>/dot_vimrc`)
- You want to monitor `/usr/share/vim/vimrc` for changes. What do you want to accomplish by doing this? Do you just want to see how it differs from `~/.vimrc`, or do you want to merge it with `~/.vimrc`?

**Comment by YouveGotMeowxy** [comment]
@bradenhilton 

> * Do you have `~/.vimrc` in chezmoi's source state? (`<chezmoi source-directory>/dot_vimrc`)

No, I don't. just the one at the path I mentioned in my OP; would it be better to create the file there instead and then use Chezmoi for that one instead? (again, linux noob here, so sorry about the entry-level questions). I'm not always sure which files (filenames) to create if they don't exist, when wanting to set the choices at the user level instead of system level.

> * You want to monitor `/usr/share/vim/vimrc` for changes. What do you want to accomplish by doing this? Do you just want to see how it differs from `~/.vimrc`, or do you want to merge it with `~/.vimrc`?

I want to just be able to make any customizations to vim/vimdiff and pass them onto my other machines, the same as for example, my bash_aliases.

**Comment by bradenhilton** [comment]
> would it be better to create the file there instead and then use Chezmoi for that one instead?

Correct. `~/.vimrc` (or `~/.vim/vimrc`) is [where per-user configuration goes](https://github.com/vim/vim/blob/be19d78c3d44221cbc38fbb5bac19302345c1def/runtime/doc/starting.txt#L809-L822). `/usr/share/vim/vimrc` is more of a system-wide configuration.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
