### ISSUE TITLE
Can't install from private repo?

### ISSUE THREAD

**Issue by STaRDoGG** [twpayne/chezmoi#2844]
## What exactly are you trying to do?

New to chezmoi, as well as not being super-proficient w/Github yet, and trying to do the 1 line install and apply from a private repo.

I'm logged into GH with my PAT, run the CM line, and:

![image](https://user-images.githubusercontent.com/1524526/224458836-7f1ad5f1-9235-4b3f-9ab6-71ff959cc555.png)

## What have you tried so far?

To test that my GH creds are working, I tried a simple direct clone of that same repo:

![image](https://user-images.githubusercontent.com/1524526/224458863-5ac78c45-2e23-4b37-b95f-bd85d368e652.png)

Which went off w/out a hitch.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

Did I miss doing something?

**Comment by halostatue** [comment]
You’re telling `chezmoi` to install via ssh:

```
$ sh -c "§(curl -fSLS get.chezmoi.io)" -- init --apply git@github.com:STaRDoGG/dotfiles.git
```

Try

```
$ sh -c "§(curl -fSLS get.chezmoi.io)" -- init --apply https://github.com/STaRDoGG/dotfiles.git
```

**Comment by STaRDoGG** [comment]
@halostatue aha! thanks! One of these days all this Linux-y stuff will finally click in this ol' Windows guy's head, lol.
