### ISSUE TITLE
file contains  `add` generate template with `{{ .chezmoi.command }}`

### ISSUE THREAD

**Issue by ghost** [twpayne/chezmoi#2859]
## Describe the bug

{{ .chezmoi.command }}  shouldn't exist as it's not a data value and it changes depending on the subcommand.

## To reproduce

file contains  `add` and then `chezmoi add --autotemplate $file`

## Expected behavior

no {{ .chezmoi.command }}

## Output of command with the `--verbose` flag

```console
» chezmoi diff
diff --git a/.config/git/config b/.config/git/config
index deb85c599c1cf34662dd3c5f6add1be9140f131d..8b34af97a5df2a1ac1f212f1ab768960529421b8 100644
--- a/.config/git/config
+++ b/.config/git/config
@@ -28,4 +28,4 @@
 [url "git@github.com:"]
   insteadOf = "https://github.com"
 [gpg "ssh"]
-	defaultKeyCommand = sh -c 'echo key::$(ssh-add -L)'
+	defaultKeyCommand = sh -c 'echo key::$(ssh-diff -L)'

▲ cat config.tmpl | tail -1
	defaultKeyCommand = sh -c 'echo key::$(ssh-{{ .chezmoi.command }} -L)'
```

**Comment by twpayne** [comment]
Thanks for reporting. Unfortunately `--autotemplate` often generates unwanted variable substitutions. It's best not to use it. I've updated the docs in #2860 to stop recommending `--autotemplate`.
