### ISSUE TITLE
Help with encryption on multiple machines

### ISSUE THREAD

**Issue by mathomp4** [twpayne/chezmoi#2909]
## What exactly are you trying to do?

This is a "help a newbie out" question. I'm still learning chezmoi and found some cases where I'd like to use encryption. So following the [age encryption page](https://www.chezmoi.io/user-guide/encryption/age/), I installed `age` with Brew, and ran `age-keygen` and added bits to my `chezmoi.toml` file.

And then I could run `chezmoi add --encrypt file` and I had a nice encrypted file. Yay!

This is my next question: I did this on Machine1, and now I want to use the encrypted file on Machine2. What does Machine2 need? Do I need to copy over the `key.txt` file from Machine1 offline and then just set up `chezmoi.toml` in the exact same way? Do I generate a new key?

Sorry about all this. SSH I sort of understand, and GPG I used to (keyservers, etc) but `age` is new to me. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details. ==> I looked on the GitHub Issues.

**Comment by twpayne** [comment]
With age, you have two options, depending on how secure/paranoid you want to be.

> Do I need to copy over the `key.txt` file from Machine1 offline and then just set up `chezmoi.toml` in the exact same way?

This is the easiest thing to do. You'll need to copy `age.txt` manually, or use [this trick so you only need to type a password once when setting up a new machine](https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/#how-do-i-configure-chezmoi-to-encrypt-files-but-only-request-a-passphrase-the-first-time-chezmoi-init-is-run).




> Do I generate a new key?

This is the more complex, but more secure alternative. You'll need to re-encrypt all your secrets so they can be decrypted with both keys (the magic phrase is "multiple recipients") but this allows you to control exactly which files can be decrypted on a per-machine basis, even in the presence of a hostile root user who can read your local private key.

This is all said, using a password manager to store your secrets generally gives a much smoother user experience than using age/GPG directly.

**Comment by halostatue** [comment]
You need to use the same key on all machines and use a similar configuration for such encryption.

**Comment by mathomp4** [comment]
> This all said, using a password manager to store your secrets generally gives a much smoother user experience than using age/GPG directly.

I would love to do this as I use 1password at home and on browser. But at work, I can't install the 1password macOS app [that `op` apparently depends on](https://developer.1password.com/docs/cli/get-started/#step-1-turn-on-the-1password-app-integration). ☹️ 

But thanks for the help and I'm going to try out the cool trick you pointed to.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.

**Comment by mathomp4** [comment]
> Hopefully this is now resolved. Please re-open if needed.

Oh. Sorry. Yes. It took me a bit to figure out the "trick". Mainly I had to remember to copy away my `chezmoi.toml` because I had to run `chezmoi init` again when I added the tmpl. Fun times!
