### ISSUE TITLE
How to mantain file permition when apply configuration

### ISSUE THREAD

**Issue by saccarosium** [twpayne/chezmoi#2918]
## What exactly are you trying to do?

I have a script directory where I have a lot of custom commands. When I do `chezmoi apply` and chomodx the scripts in the directory on the next apply chezmoi will prompt me that the file are changed and if I want to overwrite them, this bevomes really anoing after a wil pressing 's' a bunch of times.

## What have you tried so far?

- I've tried chmoded in the cheimoz root but it seem resetting the permissions.
- I've tried to chmod with a scripr `run_after` but then I need to restart bash because the shell state has not been reloaded.

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

## Output of `chezmoi doctor`

will update now on phone

```console
$ chezmoi doctor
```

**Comment by halostatue** [comment]
Add the attribute `executable`; in my `private_dot_local/bin/` directory, I have a script `executable_git-conflicts`. You can avoid modifying the permissions in a script separately.

**Comment by saccarosium** [comment]
@halostatue thanksit works!
