### ISSUE TITLE
Issue with --encrypt option

### ISSUE THREAD

**Issue by franek** [twpayne/chezmoi#292]
I am giving a try to chezmoi to replace another existing tool.

I am not able to encrypt my file : 
```
$ chezmoi add --encrypt  .ssh/config.d/perso --verbose
mkdir -m 755 /home/user/.local/share: mkdir /home/user/.local/share: file exists
chezmoi: exit status 2
```
I have defined within ~/.config/chezmoi/chezmoi.toml
```
gpgRecipient = "my key" 
```

The directory /home/user/.local/share exists with 755.

Gpg is present on my OS.
```
$ gpg --version
gpg (GnuPG) 2.2.8
```

I am running Ubuntu : 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```
```
$ chezmoi --version
chezmoi version 1.5.2, commit 9d4dba1953f313a84510397a284f4a755f621670, built at 2019-05-15T23:07:54Z
```

Have you any clues ? Thanks

**Comment by twpayne** [comment]
I am currently unable to reproduce this problem. Please post the output of:

    gpg --armor --encrypt --recipient $gpgRecipient < ~/.ssh/config.d/perso

where `$gpgRecipient` is the `gpgRecipient` value from your config file.

It might be that you're not passing the absolute path of `~/.ssh/config.d/perso` to `chezmoi add --encrypt`. Please also try:

**Comment by twpayne** [comment]
It may be that the key you are using is not trusted, which means gpg is prompting for  input when run. You can change the trust level of the key with the `gpg --edit-key` command. I'll add a check to chezmoi for this.

**Comment by franek** [comment]
It also occurs when you don't have configured GPG. It was my case... :man_facepalming:

**Comment by twpayne** [comment]
Happy to hear that the problem is resolved! I'll add some checks to chezmoi to make this easier to debug in the future.
