### ISSUE TITLE
[FR] group related configs into "packages"

### ISSUE THREAD

**Issue by ajeetdsouza** [twpayne/chezmoi#2923]
I'm a recent convert from stow, and one thing I really liked about it was the face that you could have a directory structure like this:

- i3 (contains configs for rofi, status bar, etc)
- zsh (I split my zshrc into multiple files and source them)
- common (this is used by all operating systems)

I'd like to be able to define directories of related configs, and in my chezmoiignore file, I would be able to pick which directories to apply for a given host.

**Comment by twpayne** [comment]
chezmoi deliberately doesn't work this way. See [this FAQ entry](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#can-chezmoi-support-multiple-sources-or-multiple-source-states).
