### ISSUE TITLE
Add a method for checking font availability

### ISSUE THREAD

**Issue by marjacob** [twpayne/chezmoi#2929]
## Is your feature request related to a problem? Please describe.

I work on some systems where licensed (commercial) fonts are available. I wish to use these with my tools when possible, but gracefully fall back to a sane alternative when not. Unfortunately, not all tools support specifying a list of alternate fonts.

## Describe the solution you'd like

I would like a way to verify font availability in a template, something like the following:

```
{{- $font := "Preferred Font Regular" -}}
{{- if not font $font }}
{{-   $font = "Fallback Font Italic" -}}
{{- end -}}
```

## Describe alternatives you've considered

Adding private fonts to my dotfiles repository with encryption is a possibility. I would have to implement font installation using scripts. This is not possible when fonts are licensed to someone other than me (e.g. my employer, for use on a specific workstation).

## Additional context

On Windows, the list of available fonts can be queried with [`EnumFontFamiliesExW`](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-enumfontfamiliesexw).

**Comment by twpayne** [comment]
This can be done with the existing `output` template function, for example:

```
{{ $installedFonts := output "reg" "query" "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts" "/s" }}
{{ if contains "Preferred Font Regular" $installedFonts }}
{{/* ... */}}
{{ end }}
```

**Comment by marjacob** [comment]
Neat idea, thank you for that suggestion. I got it working with `fc-list` as well for Linux.

```
{{- $fonts := list }}
{{- if eq .chezmoi.os "linux" }}
{{-   $fonts = output "fc-list" "-f" "%{family} %{style}\n" }}
{{- else if .chezmoi.os "windows" }}
{{-   $fonts = output "reg" "query" "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Fonts" "/s" }}
{{- end }}
```

**Comment by twpayne** [comment]
Thanks for the kind words!

Yes, please do close this issue if the solution is sufficient for you.
