### ISSUE TITLE
promptStringOnce only stores variables under [data]

### ISSUE THREAD

**Issue by dboeckenhoff** [twpayne/chezmoi#2938]
## What exactly are you trying to do?
My .chezmoi.toml.tmpl does

```
{{- $database := promptStringOnce . "database" "Please add the path to your keepass2 database to be used via keepassxc cli" -}}

[keepassxc]
    database = {{ $database | quote }}
```

However, with chezmoi init I am always prompted the database entry request.
This is rather invonvenient. If this is possible, I'd say the proper way should be documented.

## What have you tried so far?

The same syntax storing under [data] works. However, keepassxc requires the database entry to be under [keepassxc] (as I understand it).

## Where else have you checked for solutions?

* [ ] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

## Finally

Thanks for this awesome project!

**Comment by halostatue** [comment]
As a workaround, you could store things twice.

```
{{- $database := promptStringOnce . "keepassxc-database" "Please add the path to your keepass2 database to be used via keepassxc cli" -}}

[keepassxc]
    database = {{ $database | quote }}

[data]
# This is a workaround
keepassxc-database = {{ $database | quote }}
```

It seems like it could be useful, at least for `chezmoi init`, to have `.chezmoi.config.*` keys available so that you could do `promptStringOnce . "chezmoi.config.keepassxc.database" "DATABASE, MORTAL"`. I don’t know that it would be useful for normal usage.

**Comment by twpayne** [comment]
Thanks for the suggestion. Adding a `.chezmoi.config` template variable makes sense. Done in #2940.

**Comment by halostatue** [comment]
@dboeckenhoff I *believe* that once this is released, your template would be updated to

```
{{- $database := promptStringOnce . "chezmoi.config.keepassxc.database" "Please add the path to your keepass2 database to be used via keepassxc cli" -}}

[keepassxc]
    database = {{ $database | quote }}
```
