### ISSUE TITLE
[Feature] Ensure chezmoi binary is in current `$PATH` while running scripts.

### ISSUE THREAD

**Issue by aarondill** [twpayne/chezmoi#2993]
## Is your feature request related to a problem? Please describe.

When loading chezmoi in a new machine, running the chezmoi install script, chezmoi installs into `~/bin/chezmoi`, which is not in my 
PATH, as a new Ubuntu machine includes `~/bin` *only* if it exists when a new shell is loaded. Since my scripts call `chezmoi` (especially `chezmoi source-path`. I know `$CHEZMOI_SOURCE_DIR` is set, but I like to manually run my scripts with `bash SCRIPT`, so running the `chezmoi` binary allows universality). Because `~/bin` is not in my `$PATH`, running `chezmoi apply` fails with a `chezmoi: command not found`.

## Describe the solution you'd like

When running scripts, detect if the binary's parent directory is in the `$PATH`, and if not, then **append** it.

Another solution for potential safety is to create a temp dir and link the binary (there's a reason that not *every* path is in `$PATH`). This is implemented in bash, but hopefully you get the gist:
```bash
set -eu
temp_dir="$(mktemp -d)"
trap 'rm -rf "$temp_dir"' EXIT
ln -sT "$CHEZMOI_EXECUTABLE" "$temp_dir/chezmoi"
PATH="$PATH:$temp_dir"
```

## Describe alternatives you've considered

```bash
"${CHEZMOI_EXECUTABLE:-chezmoi}" ARGS
```

This works, but is not very clear, and would require that I change *every* one of my scripts. I could automate this, but I would prefer that `chezmoi ARGS` would *just work*™️

## Additional context

```console
> chezmoi apply
/tmp/1402241099.whyyyyyyy.sh: line 2: chezmoi: command not found
chezmoi: exit status 127
> chezmoi apply
/tmp/1402241099.whyyyyyyy.sh: line 2: chezmoi: command not found
chezmoi: exit status 127
> PATH="$PATH:$(dirname -- "$(which chezmoi)")" chezmoi apply
....
> # Finally
```

**Comment by twpayne** [comment]
Changing the user's `$PATH` is a no-no for many reasons, including security and transparency.

You can set environment variables for scripts, including `$CHEZMOI_EXECUTABLE`, with the `scriptEnv` configuration variable.

**Comment by aarondill** [comment]
Is there any way to do this using a run_script? since the confit is toml, there's no way to make it dynamic, and since scripts run in a sub shell, AFAIK there's no way to modify the environment of other scripts

**Comment by halostatue** [comment]
> When loading chezmoi in a new machine, running the chezmoi install script, chezmoi installs into `~/bin/chezmoi`, which is not in my PATH, as a new Ubuntu machine includes `~/bin` _only_ if it exists when a new shell is loaded. Since my scripts call `chezmoi` (especially `chezmoi source-path`. I know `$CHEZMOI_SOURCE_DIR` is set, but I like to manually run my scripts with `bash SCRIPT`, so running the `chezmoi` binary allows universality). Because `~/bin` is not in my `$PATH`, running `chezmoi apply` fails with a `chezmoi: command not found`.

Aside from the security reasons, on some systems it isn’t possible to determine *where* a currently running binary is running from. If you have a long-lived binary, you can `rm` the binary while it’s running and it simply doesn’t exist.

chezmoi really isn’t meant to be reentrant, so running `chezmoi` in a chezmoi run-script should be avoided (I would argue that for *most* chezmoi commands, that should be explicitly prevented in some way). However, there is a way that you can edit your scripts to work well in either case:

```bash
: "${CHEZMOI_SOURCE_DIR:="$(chezmoi source-path)"}"

# More explicitly:
if [[ -z "${CHEZMOI_SOURCE_DIR:-}" ]]; then
  CHEZMOI_SOURCE_DIR="$(chezmoi source-path)"
fi
```

That way, when running *under* chezmoi, nothing happens because `$CHEZMOI_SOURCE_DIR` is already set. When running standalone, it is set to the output of `chezmoi-source-path`.
