### ISSUE TITLE
Possible enhancements to `chezmoi ignored`

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#2998]
## Describe the solution you'd like

While looking over options available assisting with #2996, I thought that two possible improvements to the `chezmoi ignore` command might be useful:

- The ability to see what is ignored in a particular target directory (e.g., `chezmoi ignore ~/.vim`).
- The ability to see which ignore file (if multiple are present) causes a particular file to be ignored, when `--verbose` is used.

**Comment by twpayne** [comment]
I agree that this would be helpful. However, it would also be a lot of work to track provenance of ignore patterns, and we also have to handle ambiguity if multiple files or patterns match the same file.

I will close this as "won't fix" for now. We can re-open this later if we find that we need it more often. For future reference, the closest git command seems to be [`git check-ignore`](https://git-scm.com/docs/git-check-ignore).
