### ISSUE TITLE
External files: add manual version-like flag to force redownloading remote files

### ISSUE THREAD

**Issue by amospalla** [twpayne/chezmoi#3004]
## Is your feature request related to a problem? Please describe.

I put a big file on a public http server and use the external functionality to download it, so I don't pollute the git repository with binaries.

When computers do a chezmoi update, I want these to download the new file which resides on http://fqdn/file, but having a big refresh time will make them miss the file has changed, and having a low refresh time will make them redownload every time the new big file without need.

## Describe the solution you'd like

A simple way to tell chezmoi that the file has been modified is using some kind of flag in the .chezmoiexternal file, like `version=<integer>`, so when I upload a new version of the big file, I also increment this version counter, which chezmoi would keep track of, and so it knows file has been modified.

Thank you for reading and considering this and for such a great software :)

**Comment by amospalla** [comment]
Is it posible that chezmoi already takes into consideration the `Last-Modified` HTML header and I can just tell it to download the file with every chezmoi update by using a very low refresh time?

**Comment by amospalla** [comment]
Thank you !

In my specific case, my hoster provides both tags. If you or anybody else takes a look at this, consider what should be most beneficial to the whole chezmoi userbase, either one http tag, the other, or both.

**Comment by twpayne** [comment]
chezmoi already uses [github.com/gregjones/httpcache](https://github.com/gregjones/httpcache) for externals, which means that it already supports both the `Last-Modified` and `ETag` headers.

You can also use the [`--refresh-externals` flag](https://www.chezmoi.io/reference/command-line-flags/global/#-r-refresh-externals-value) to either prevent or force downloading externals, but this should not be necessary if your webserver is configured correctly.

Hopefully this resolves the issue. Please re-open if needed.
