### ISSUE TITLE
Keep original filename as part of chezmoi filename and disable metadata

### ISSUE THREAD

**Issue by kaddkaka** [twpayne/chezmoi#3022]
## Is your feature request related to a problem? 
When sharing config files with others the metadata file rename is confusing. "What is `dot_bashrc`?" "I copied your config file structure but it doesn't work, why?" 

## Describe the solution you'd like
Someway to keep filenames such as `. bashrc` intact, or atleast as part of the chezmoi filename. 

Suggestion part 1: have the metadata as a separate prefix from the original filename e.g. `PREFIX__ORIG_FILENAME`, such that `.bashrc` or `init.vim` is still the last part of the filename.  

 - `.bashrc` would be `dot__.bashrc`
 - a private dito would be `private_dot__.bashrc`

Suggestion part 2: possibility to configure chezmoi to skip prefix for the "dot" prefix so that many "non-special" files could keep their original filenames:

 - `.bashrc` would be `.bashrc`
 - a private dito would be `private__.bashrc`

## Additional context
Added benefit: editors would more often understand the filetype "out of the box".

**Comment by twpayne** [comment]
No. See https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-use-weird-filenames.
