### ISSUE TITLE
autoCommit with custom message

### ISSUE THREAD

**Issue by leo848** [twpayne/chezmoi#3023]
## Is your feature request related to a problem? Please describe.

I previously used dotbot to manage my dependencies, but I always forgot to commit when making a small change, leading to dozens of "something changed but I have absolutely no idea what" commits. Thus, `autoCommit` (and perhaps `autoPush`) are really essential for me. However, I would also like to not always be forced to use automatically-generated commit messages that are really contentless in tools like git-messenger (when I'm opening a file I know I modified it once, duh). Having titled commits really helps with version control and in general finding the stuff I wrote, which is the main reason to even use a Git repository for me.

## Describe the solution you'd like

Hence, I would propose a new option to introduce in the config file: `promptForCommitMessage` (the naming is irrelevant, there are likely better alternatives). Enabling this would be useless (or even an error) without also enabling `autoCommit`. When enabled, `autoCommit` does not automatically generate a commit message based on the changed file, but instead prompts the user via the terminal to enter a commit message (since they just wrote the change and presumably know best why it was done). Alternatively, an editor could be opened in the same way git opens one when using `git commit` without the `-m` flag. 

## Describe alternatives you've considered

One could disable `autoCommit` entirely and write a new bash script that first calls `chezmoi edit` and then prompts the user for a message afterwards. This has the advantage of being able to fully customize how it is presented (and one could also refer to external tools, e.g. doing a request to OpenAI to automatically summarize the commit), but the disadvantage of not integrating well with the rest of chezmoi and its philosophy. In addition, I believe this feature being available to all users of `autoCommit` would help commit quality overall and improve this already great tool.

**Comment by twpayne** [comment]
Nice idea. This is implemented in #3032.

Put the following in your config file:

```toml
[git]
    commitMessageTemplate = "{{ promptString \"Commit message\" }}"
```
