### ISSUE TITLE
Consider support for linuxbrew installation as well?

### ISSUE THREAD

**Issue by AmandaCameron** [twpayne/chezmoi#303]
With homebrew 2.0.0 linuxbrew is now part of homebrew, it'd be nice to have the ability to install chezmoi from the offical tap using the same tap. An example of doing this would be something along the lines of:

```ruby
  if OS.linux?
    url "https://github.com/twpayne/chezmoi/releases/download/v#{version}/chezmoi_#{version}_linux_amd64.tar.gz"
    sha256 "8855efbfeada22f9108688adc7342ae2eaee4c70adda2cc97d43558344362a87"
  elsif OS.macos?
    url "https://github.com/twpayne/chezmoi/releases/download/v#{version}/chezmoi_#{version}_darwin_amd64.tar.gz"
    sha256 "9f3da6eea97740e94d4728f370f6ed513338a930e7f0decb07bca8bfa95827e4"
  end
```

**Comment by twpayne** [comment]
This got added to goreleaser in https://github.com/goreleaser/goreleaser/pull/1043. I just released a new version of chezmoi (1.5.7), and linuxbrew should now be supported: https://github.com/twpayne/homebrew-taps/blob/master/Formula/chezmoi.rb.

Please re-open if there any any problems.
