### ISSUE TITLE
Clone and checkout to latest tag of a repository with chezmoiexternal

### ISSUE THREAD

**Issue by xph8** [twpayne/chezmoi#3033]
## What exactly are you trying to do?

I'm trying to set up .chezmoiexternal to checkout to the latest tag of asdf ([installation docs](https://asdf-vm.com/guide/getting-started.html#official-download)) by adding a command in clone args:
```
git ls-remote --tags --sort v:refname https://github.com/asdf-vm/asdf.git | tail --lines 1 | awk '{print $2}' | cut -d / -f 3
```
like:
```
[".config/asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
  [".config/asdf".clone]
    args = ["--branch", "{{ output "git" "ls-remote" "--tags" "--sort" "v:refname" "https://github.com/asdf-vm/asdf.git" "|" "tail" "--lines" "1" "|" "awk" "'{print $2}'" "|" "cut" "-d" "/" "-f" "3" }}"]
```
Piping does not seem to work and `output` function returns an empty string.

## What have you tried so far?

`.chezmoiexternal.toml.tmpl`
```
[".config/asdf"]
  type = "git-repo"
  url = "https://github.com/asdf-vm/asdf.git"
```
And then checkout to the latest tag from a chezmoi script. I wonder if there is a neat way to keep all logic in chezmoiexternal.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by twpayne** [comment]
> Piping does not seem to work and `output` function returns an empty string.

This is because pipes are only supported by the shell, not by the `output` template function.

Try running your shell commands in a shell spawned by output, something like:

```
{{ output "sh" "-c" "git ls-remote --tags ... | tail ... | awk ..." }}
```

**Comment by xph8** [comment]
```
{{ output "sh" "-c" "git ls-remote --tags ... | tail ... | awk ..." | trim }}
```

This works perfectly.
Thank you for creating this wonderful tool!
