### ISSUE TITLE
Ignore protected '.local/share/chezmoi' by default

### ISSUE THREAD

**Issue by MrHappy** [twpayne/chezmoi#3051]
## Is your feature request related to a problem? Please describe.
When I try to add .local to chezmoi and having '.local/share/chezmoi' in the ignore file it still says:
`cannot add chezmoi file to chezmoi (/home/user/.local/share/chezmoi is protected)`

I tried the following:
```
.local/share/chezmoi
.local/share/chezmoi/**
.local/share/chezmoi/**/*
```
and

```
**/chezmoi/
**/chezmoi/**
**/chezmoi/**/*
```

## Describe the solution you'd like
Honor the ignore-file and/or ignore the '.local/share/chezmoi'-folder by default

**Comment by twpayne** [comment]
Thanks for reporting this. Fixed with #3052.
