### ISSUE TITLE
PR 3069 makes things worse 

### ISSUE THREAD

**Issue by Sacro** [twpayne/chezmoi#3072]
## Describe the bug

It doesn't seem to be passing things via tar at all now (after #3069), just dumping the compressed data into the destination.

## To reproduce

Apply anything that should use filter.cmd/filter.args

## Expected behavior

Data is un-tarred 

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

## Additional context

[Edited by @halostatue to make the referenced PR clearer.]

**Comment by twpayne** [comment]
OK, I've reverted #3069 with 439ccf8f4f092a3b1f909e430775db933dc7c740.

**Comment by Sacro** [comment]
I've raised a feature request as 3079, to look at the idea of doing zip/tar stuff internally, rather than shelling out where possible.

Is there a Discord or something, I'm happy to take a look at this myself.

**Comment by twpayne** [comment]
This is being added in #3080.

There is no Discord for chezmoi. I don't have time to do chat support.
