### ISSUE TITLE
Preconditions before generating template-based files

### ISSUE THREAD

**Issue by x80486** [twpayne/chezmoi#3084]
## Description

I would like to be able to be able to run some checks in a way that's _not invasive_ to fail (or not) the generated file based on a given template.

For instance, I have a `config` file for `Git` with a `user` section that's similar to this:

```ini
...

[user]
  email = "{{ .git.gitlab.email }}"
  name = "{{ .git.gitlab.name }}"
  signingKey = "{{ .chezmoi.homeDir }}/.ssh/gitlab-personal.pub"
```

So if I try to generate the file based on this template, it should fail because `{{ .chezmoi.homeDir }}/.ssh/gitlab-personal.pub` is not present (if that's the case).

## Describe Solution(s) You Would Like

- A set of built-in functions at the top of the file to run the checks
- A built-in function you can place in the templates — e.g.: `{{ .chezmoi.homeDir/.ssh/gitlab-personal.pub | file_exists }}`

## Describe Alternatives You Have Considered

N/A

**Comment by halostatue** [comment]
I *think* what would be missing here shouldn’t be too hard to add, and that’s an unconditional "halt" template function.

It might work as something like:

```
...

[user]
  email = "{{ .git.gitlab.email }}"
  name = "{{ .git.gitlab.name }}"
{{- if stat (joinPath .chezmoi.homeDir ".ssh/gitlab-personal.pub")) }}
  signingKey = "{{ .chezmoi.homeDir }}/.ssh/gitlab-personal.pub"
{{ else }}
  {{ halt "Missing ~/.ssh/gitlab-personal.pub" }}
{{ end }}
```

This is imperfect and may be dangerous for normal execution cases, but the idea *could* work.

**Comment by twpayne** [comment]
You can use the existing [`fail` template function](https://masterminds.github.io/sprig/flow_control.html) for this.

**Comment by halostatue** [comment]
Good to know and good to know that such a template function already exists.
