### ISSUE TITLE
Is it possible to store JSON in a pass/gopass entry?

### ISSUE THREAD

**Issue by ps245** [twpayne/chezmoi#3093]
## What exactly are you trying to do?

Describe in as much detail as possible.

Say I used [`passRaw`](https://www.chezmoi.io/reference/templates/pass-functions/passRaw/) or [`gopassRaw`](https://www.chezmoi.io/reference/templates/gopass-functions/gopassRaw/) functions it should be possible to store an entire JSON object in there.

I had wondered if it was possible to do that with [`passFields`](https://www.chezmoi.io/reference/templates/pass-functions/passFields/) as it seems that produces a map with values in it.

## What have you tried so far?

If I have some values like for example 

```json
{
  "animals": [
    "dog",
    "cat",
    "snake"
  ],
  "dog": {
    "name": "rover",
    "sound": "woof",
    "color": "brown"
  },
  "cat": {
    "name": "fluff",
    "sound": "meow",
    "color": "white"
  },
  "snake": {
    "name": "snek",
    "sound": "ssss",
    "color": "black"
  }
}
```

I want to know how I would then select snake's color, or iterate animals with `index`.
 
## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
Yes, you can use the [`fromJson` template function](http://masterminds.github.io/sprig/defaults.html) to parse the field as JSON and extract the field you want, for example:

```
{{ (passRaw "my-name" | fromJson).dog.name }}
```
