### ISSUE TITLE
Let chezmoi add accept copy&pasted paths from diffs

### ISSUE THREAD

**Issue by eugenesvk** [twpayne/chezmoi#3096]
## Is your feature request related to a problem? Please describe.

You want to apply all the changes, but be careful, so you do `chezmoi apply -v --interactive`
Then you see there is a diff
```
diff --git a/.config/path/file.tst b/.config/path/file.tst
…
--- a/.config/path/file.tst
+++ b/.config/path/file.tst
```
and realize that you've edited the target file manually outside of chezmoi's knowledge and would like to preserve those changes

One easy way is to cancel, copy `b/.config/path/file.tst` and do `chezmoi add b/.config/path/file.tst`
But then there is this pesky `b/` that makes the easy path wrong :(

## Describe the solution you'd like

Maybe chezmoi could accept these invalid paths starting with `a/` or `b/` and recognize them to mean `~/`?

## Describe alternatives you've considered

There are ways to edit files in a way chezmoi recognizes them (either directly or a better via watchman), but then that still requires some premeditation vs. easily editing files in your text editor project for instant feedback with whatever tool you use and without having to do extra commands before every edit, so I often keep skipping those ways
(or if you're tracking configs from GUI apps, those definitely don't care about chezmoi )

**Comment by twpayne** [comment]
No. Adding this would create a huge number of complications (what if the user has a directory called `a` or `b`?) for a minor UX convenience for a corner-case. The work-around is to be more precise with cutting before pasting.

**Comment by eugenesvk** [comment]
> what if the user has a directory called `a` or `b`?

the user can't have a directory called `a/something`, it's not a valid path!

**Comment by halostatue** [comment]
`mkdir -p ~/a/something/odd && touch ~/a/something/odd/here.txt`

The user certainly *can* have a directory called `a/something`.

If you find you’ve done this, you’re better off running either `chezmoi merge ~/.config/path/file.tst` or (as I do, because I edit a lot of things outside of chezmoi frequently) `chezmoi merge-all` (goes through all changed files that need merging).

**Comment by eugenesvk** [comment]
> The user certainly can have a directory called `a/something`

No, the user can have a directory called
```
~a/something # but NOT without the ~
 a/something
```
that's the beauty of this override, it doesn't clash with real paths, only helps with copy&pasted "diff paths"

**Comment by halostatue** [comment]
`cd ~ && mkdir a/something && touch a/something/strange.txt`.

`a/` and `b/` are git-ish names. The *only* way that this would work is if you did what `patch(1)` does and add something analogous to `--strip N` or `-n N` support. So `chezmoi add a/something/strange.txt --strip-from-root 1`.

If you didn’t realize it, chezmoi is `$PWD`-aware, which means that I could do the following:

```console
$ cd .config
$ mkdir -p a/something
$ touch a/something/strange.txt
$ chezmoi add a/something/strange.txt
```

Under what you’ve requested, `a/something/strange.txt` would *mean* `~/a/something/strange.txt`, but it already currently means `$PWD/a/something/strange.txt`.

If you’re doing `chezmoi add ⌘-V` which results in `chezmoi add b/something/strange.txt`, it is probably best to back up a bit and replace `b` with `~` or `$HOME` just so you know you’re doing the right thing regardless.

I agree with @twpayne that this feature is a corner case, and it’s already well handled via `chezmoi merge` or `chezmoi merge-all` without adding special meaning to `a/` and `b/` in `chezmoi add` that works in ways that do not work that way for any other tool at all.

**Comment by eugenesvk** [comment]
> you’re better off running either `chezmoi merge ~/.config/path/file.tst` 

that doesn't help, I still need to copy&paste `a/.config/path/file.tst` and replace `a` with `~`

> `chezmoi merge-all` (goes through all changed files that need merging).

that would work sometimes, but sometimes I don't want to deal with all edits, I'm checking just this one file, and have pressed `n` in the cli, so wouldn't want `merge-all` to show all those skipped files

**Comment by eugenesvk** [comment]
> If you didn’t realize it, chezmoi is `$PWD`-aware, which means that I could do the following:

Yes, I forgot about this elephant in the room, sorry about that :(

I'm not sure there is a good general solution, so I'll maybe try to handle it in an alias and just rewrite the two `a/` and `b/` special cases locally

Thank you

**Comment by eugenesvk** [comment]
a simpler idea I should've remembered before adding the alias is use a different diff tool like delta that can print out the full path that's copy&pasteable without a/ b/
