### ISSUE TITLE
Docs: chezmoiignore exclude patterns

### ISSUE THREAD

**Issue by torculus** [twpayne/chezmoi#3098]
## What exactly are you trying to do?

I'd like to ignore all of the contents in `~/.config` from syncing to Windows ***except*** for `~/.config/myspecialfile.txt`. In the [documentation](https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#ignore-files-or-a-directory-on-different-machines), it gives an example of excluding `f` by using `!f`. Adapting to my use case, I've tried `!.config/myspecialfile.txt`, `.config/!myspecialfile.txt`, and `!myspecialfile.txt`. None of these have worked, as `chezmoi ignored` still says that `~/.config` is ignored

If the docs could be updated to use something like `file1.config` instead of just `f`, this would make it a lot clearer for users on where to put the `!`

## What have you tried so far?

My `.chezmoiignore` looks like this:
```
{{- if ne .chezmoi.os "windows" }}
AppData
_vimrc
vimfiles
{{ end }}
{{ if eq .chezmoi.os "windows" }} # things for Linux, FreeBSD, and illumos
.config
!.config/myspecialfile.txt # or .config/!myspecialfile.txt or !myspecialfile.txt
{{ end }}
```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
Thanks, I've updated the docs in #3103.
