### ISSUE TITLE
v2.35.0 not released to winget

### ISSUE THREAD

**Issue by dpprdan** [twpayne/chezmoi#3099]
AFAICT [v2.35.0](https://github.com/twpayne/chezmoi/releases/tag/v2.35.0) didn't make it to [the winget-pkgs repo](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+chezmoi).

Probably because [this action](https://github.com/twpayne/chezmoi/actions/runs/5569618618) failed?

**Comment by twpayne** [comment]
Yes, it's also not on snapcraft.io yet for the same reason.

Hopefully I'll have time to look at this later today.

**Comment by twpayne** [comment]
c251528495d1c3dd843c9f28489765b622dba35f should fix it. I'll release 2.35.1 later today.

**Comment by twpayne** [comment]
This is now fixed: https://github.com/microsoft/winget-pkgs/pull/112476
