### ISSUE TITLE
Add support for .chezmoiexternal directory

### ISSUE THREAD

**Issue by zydou** [twpayne/chezmoi#3106]
## Is your feature request related to a problem? Please describe.

I have many external files, which makes `.chezmoiexternal.toml` very long and cluttered.

## Describe the solution you'd like

A `.chezmoiexternal` folder that all files in it are treated as external templates.

```bash
.chezmoiexternal
├── cli-binaries.toml
├── node-stuffs.toml
├── personal-only.toml
├── vim-plugins.toml
├── work-only.toml
└── zsh-plugins.toml
```

## Additional context

related: #3008, #3009

**Comment by twpayne** [comment]
Good idea. Implemented in #3108.

**Comment by zydou** [comment]
Hello, thank you for the quick implementation. I have tested the binary generated by #3108 in the CI's `Artifacts`, and it is working perfectly!

**Comment by twpayne** [comment]
Great, thanks for testing!
