### ISSUE TITLE
Download Private Repo, without cloning

### ISSUE THREAD

**Issue by typkrft** [twpayne/chezmoi#3115]
## What exactly are you trying to do?
I'd  like to either be able to fetch an archive from a private repo, or download a repos files without actually have it as a repo. Essentially removing the `.git` folder and/or creating a submodule.

I've got a nix flake, which is required to be in a git repo with all of the inputs and files it will use to be in the repo and tracked. This repo however is simply inited and not tracked or pushed anywhere. I'm using chezmoi to bootstrap the install of nix. Because I keep my chezmoi dotfiles public, I'd like the ability to pull in private files separately. .chezmoiexternal seems like a great solution, but when I pull the private repo down into the uncommitted nix repo nix doesn't see the files because they are a separate repo. And I can't seem download an archive from my private repo as it results in a 404. 

## What have you tried so far?
I've tried looking through the documentation on the .chezmoiexternal. The repo pulls as a git repo, but not as an archive. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details. - Web searches

## Output of any commands you've tried with `--verbose` flag

```console
# NA
```

## Output of `chezmoi doctor`

<details>

```console
# NA
```

</details>

## Additional context
NA

**Comment by typkrft** [comment]
Today I learned about submodules. Thanks!

**Comment by twpayne** [comment]
Great! If you're using submodules, you'll probably also want to use the [`external_` attribute](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#use-git-submodules-in-your-source-directory).
