### ISSUE TITLE
Release notes do not credit contributors

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#3125]
## Describe the bug

A bunch of people contribute to chezmoi. The release notes do not show these contributions. For example:

* In https://github.com/twpayne/chezmoi/releases/tag/v2.36.0, @catay contributed https://github.com/twpayne/chezmoi/pull/3112 and https://github.com/twpayne/chezmoi/pull/3120, but these are not visible in the release notes.
* There was at least one other case where a contributor (I think a senior staff engineer at Github?) also made a significant contribution and was not credited in the release notes.

## To reproduce

Get some excellent contributions and then create a new release.

## Expected behavior

Contributors should be properly credited.

## Output of command with the `--verbose` flag

n/a

## Output of `chezmoi doctor`

n/a

## Additional context

I'm rebasing commits when merging PRs, but this should not affect anything.

**Comment by twpayne** [comment]
Furthermore, it's not just the contributors that aren't getting credited. The whole PR/commit goes missing.

For example, chezmoi 2.36.0 includes support for Azure Key Vault secrets from #3112, but this is not visible in the [release notes](https://github.com/twpayne/chezmoi/releases/tag/v2.36.0).

**Comment by bradenhilton** [comment]
For info, the latest release with contribution credits seems to be [`v2.34.3`](https://github.com/twpayne/chezmoi/releases/tag/v2.34.3).

**Comment by bradenhilton** [comment]
Could `github-native` be partly responsible here?

It also seems to credit based on PR author instead of commit author when it works correctly, which seems incorrect to me.

I'm not sure if `git{hub}` would be any better.
