### ISSUE TITLE
[feature request] Doppler support

### ISSUE THREAD

**Issue by equals03** [twpayne/chezmoi#3132]
## Is your feature request related to a problem? Please describe.

chezmoi includes support for HCP Vault Secrets using the `vlt` CLI to expose data through the `hcpVaultSecret` and `hcpVaultSecretJson` template functions. It does not, however, support [Doppler](https://www.doppler.com/). The feature set and implementation is _almost_  1:1 between `vlt` and the [Doppler CLI](https://docs.doppler.com/docs/cli).  

## Describe the solution you'd like

The Doppler CLI to be implemented.

## Describe alternatives you've considered

Using `vlt` but I like Doppler :smile: 

## Additional context

I would be willing to give implementation a stab (after all it is basically a copy and paste of the `vlt` implementation) time permitting and should this get enough interest/align with the project.

**Comment by twpayne** [comment]
Please do implement this :)

https://github.com/twpayne/chezmoi/pull/3067/files should give you an idea of what files need to be added/modified.
