### ISSUE TITLE
Disable cursor blinking when asking for user input as that breaks copy&paste

### ISSUE THREAD

**Issue by eugenesvk** [twpayne/chezmoi#3143]
## Is your feature request related to a problem? Please describe.

When doing `apply` and encountering a conflict chezmoi prompts for action displaying the conflicting file path.
I'm frustrated that I can't copy that file path due to the blinking cursor (see video below)

## Describe the solution you

An option to disable cursor blinking (or maybe it's not blinking per but some kind of other "line refresh")

## Describe alternatives you've considered

Maybe this is more of a terminal issue (I'm using Wezterm on a Mac, and I've tried on the builtin terminal where blinking didn't break copying, so I've also asked Wezterm to add such a feature), but I've tried using `read name` command, and it doesn't blink, so it seems like it's a least a combination of actors

Moving the input to another line from the path display also works as blinking seems to break only the current line

## Additional context

https://github.com/twpayne/chezmoi/assets/12956286/ccfab1f6-f58f-49a6-b721-af779236346a

**Comment by twpayne** [comment]
You can use the [`--no-tty` flag](https://www.chezmoi.io/reference/command-line-flags/global/#-no-tty) to disable the rich interactive input, which should solve the problem.

**Comment by eugenesvk** [comment]
The poor input is much worse as now I have to press enter to confirm input, which I do more often vs. copy&pasting, so if that's the only option then I'll live with hacky copy&paste
