### ISSUE TITLE
Install with `npm -g`

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#3145]
Inspired by the sad closing of #2130, I’m wondering if we want to offer an NPM package for installation, as William Melody does with https://github.com/xwmx/nb. I have seen other binaries and shells scripts offered this way or as `pip` or `gem` installs.

There are questions to which I do not personally have the answers (but I may have opinions):

- how can we automatically publish an NPM package securely?
- do we include the raw binaries for the major platforms and wrap them in a runner script which runs the appropriate binary?
- do we want to instead have a `chezmoi-install` or `install-chezmoi` package that can be run with `npx` (e.g., `npx chezmoi-install ...`) that replicates the `curl | sh` experience and installs the appropriate package for the local system?

I was looking to see whether GitHub Packages could act like a Debian repository, and the answer is "not at this time" (and maybe never), and then I remembered that several tools that I have seen over the years have offered `npm install` capabilities.

**Comment by twpayne** [comment]
Another option is to create a [Ubuntu PPA](https://help.ubuntu.com/community/PPA).

I'd rather not go the way of npm, as npm itself is a real pain to install.

**Comment by arran4** [comment]
Would like to see a PPA it's easier to keep in sync. Plus isn't based on having a development kit installed.
