### ISSUE TITLE
http cache fills over time

### ISSUE THREAD

**Issue by thmo** [twpayne/chezmoi#3149]
## Is your feature request related to a problem? Please describe.

Using `chezmoi upgrade` regularly, the cache in `~/.cache/chezmoi/httpcache` fills up significantly.

In my case it grew to 500MB before  I noticed.

## Describe the solution you'd like

There should be a mechanism to remove old entries in the cache, or, better, keep only the latest and relevant ones.

## Describe alternatives you've considered

Of course one can manually clean the cache from time to time, but only after noticing.

**Comment by twpayne** [comment]
I would like to fix this, but it's extremely hard to do correctly in chezmoi for a number of reasons:

1. Cache eviction is hard.
2. The HTTP caching library used by chezmoi is now archived and does not provide the necessary hooks to either iterate over cache entries or determine if an entry is stale.
3. It is not evident that chezmoi can even determine what entries should be evicted. For example, chezmoi cannot distinguish between a value that is no longer used vs. a value that was only not used in the current run of chezmoi.

You can safely delete the contents of `~/.cache/chezmoi` at any time.

Given that the alternative to `rm -rf ~/.cache/chezmoi` is a huge amount of work to implement something that is likely incorrect, I don't plan to work on this.
