### ISSUE TITLE
Suggest interactive `--autotemplate`

### ISSUE THREAD

**Issue by bryango** [twpayne/chezmoi#3166]
## Is your feature request related to a problem? Please describe.

I understand that `--autotemplate` is fragile and has been deprecated in #2877 and removed in #2943, but the functionality is so convenient and it's been very helpful to me.

## Describe the solution you'd like

I think that one way to re-introduce `--autotemplate` without the dangers of it being "too smart", is to always prompt the user for every matched variable, in a way similar to `chezmoi add --interactive`, with a diff view illustrating the templated change. The user can then choose whether to add the change or not.

## Describe alternatives you've considered

Manual templating: then I have to read the docs for the variables, which I am too lazy to...

## Additional context

`--autotemplate` was such a killer feature for me that I am falling back to an older version in order to keep using it.

**Comment by twpayne** [comment]
#3171 restores the `--autotemplate` flag.

Having an interactive `--autotemplate` flag is an interesting idea. However, the user interface is complicated: the user would likely have to be prompted with a series of diffs between the original file and the proposed template, and would be asked to accept or reject each one. Interactive workflows are tricky, and chezmoi is primarily a non-interactive program.

The same effect can be achieved with:

```console
$ chezmoi add --autotemplate $TARGET && chezmoi merge $TARGET
```

except now the user can accept or revert individual changes in their favorite diff/merge tool, which will have a much richer interface that chezmoi will ever have.

So, with #3171 restoring the flag, and `chezmoi add && chezmoi merge` providing the functionality, I'll close this as completed.

**Comment by bryango** [comment]
> The same effect can be achieved with:
> 
> ```console
> $ chezmoi add --autotemplate $TARGET && chezmoi merge $TARGET
> ```

That's perfect! I didn't know about `chezmoi merge`. Thank you!
