### ISSUE TITLE
Prompt function with predefined set of options

### ISSUE THREAD

**Issue by cglong** [twpayne/chezmoi#3167]
## Is your feature request related to a problem? Please describe.

I use the `prompt*` functions to help automate configuring a new machine. However:

- For a work machine, I'm always entering the same set of values. I have a different set of values for a personal machine, but they're always consistent too.
- I sometimes rely on hacks for templating behavior, like comparing the email address to determine what kind of Git authentication to use.

## Describe the solution you'd like

It'd be great if there was a `promptChoice` function that let me choose from one of a few predefined options. So I could e.g. have two options (`work` and `personal`) and the chosen value would be assigned to a variable. I could then dynamically set other variables based on this value.

## Describe alternatives you've considered

This could probably be done today using `promptString*` then checking the value, calling Sprig's `fail` function if the value wasn't in the defined list.

## Additional context

N/A

**Comment by halostatue** [comment]
This could be very nice for various things, and feasible with the charmbracelet/bubbletea tooling already in place.

I presume that you’re thinking an interface like:

```
{{ $value := promptChoice "prompt string" "default value" (list "a" "b" "c" "d") }}
```

**Comment by twpayne** [comment]
WIP in #3168.

**Comment by cglong** [comment]
@halostatue, I might move the default value to the last parameter, since I believe it's optional in other `prompt*`s. Otherwise, agree with everything you've said 🙂
