### ISSUE TITLE
Chezmoi diff to allow using source file as its argument

### ISSUE THREAD

**Issue by eugenesvk** [twpayne/chezmoi#3170]
## Is your feature request related to a problem? Please describe.

I'm editing my chezmoi source file `.../chezmoi/private_dot_config/app/settings.cfg` and then I'd like to know what the difference with the current state is.

But the problem is, the only path I have immediate access to is the source file path, so the easiest way is to copy this path from the text editor and just paste it to `chezmoi diff .../chezmoi/private_dot_config/app/settings.cfg`

But that doesn't work, I get a `not managed` error, so I need to manually translate the source to target and then type the path  `chezmoi diff ~/.config/app/settings.cfg`

## Describe the solution you'd like

`chezmoi diff` translates the source path automatically to the destination path and proceeds as usual

## Describe alternatives you've considered

Use `chezmoi diff`, but then that cycles through all the other not relevant changes as well

I thought about adding this to my chezmoi alias that already works by rewriting `a/` git paths, but this would mean parsing all the `private_` etc prefixes, which chezmoi app already is aware of

## Additional context

None

**Comment by twpayne** [comment]
This should already be possible by passing the `--source-path` flag to `chezmoi diff`. Note that this is currently undocumented.

**Comment by eugenesvk** [comment]
Thanks! Is it possible to allow configuring it as the **context-dependent** default? So that
- when I pass a **source** path, instead of an error I'd get a **diff**
- when I pass a **target** path, I get a **diff**

This way I don't need to think which path I'm currently pasting and **don't need to type** any flags. What is the value of an error when a user pastes the source path in a diff?

**Comment by twpayne** [comment]
No. I don't want to add magical behavior like this, as it invariably has awkward edge cases. 

Instead, you can write a wrapper script that tries the different ways of interpreting the arguments.
