### ISSUE TITLE
Website contribution issues

### ISSUE THREAD

**Issue by bradenhilton** [twpayne/chezmoi#3180]
I don't believe the traditional issue template is a good fit here, so I'm electing to just list the issues with any relevant information, along with my suggested resolutions.

While debugging the output in https://github.com/twpayne/chezmoi/pull/3177#issuecomment-1680640870, I noticed a few issues which I believe are relatively easy to solve.

| Issue | Resolution |
|--------|--------|
| Git symlink support [isn't great on Windows](https://github.com/git-for-windows/git/wiki/Symbolic-Links), and their usage breaks the template data for the website without manual intervention of the user, leading to 404 errors for the Links page(s). | Remove the symlinks, split each link type into its own `.yaml` file. |
| In the `on_pre_build` hook, paths are invariably joined with a unix style path separator, which creates mangled paths on Windows e.g. `C:\\working\\copy\\assets\\chezmoi.io\\docs/links/videos.md`. Whether or not this is fine seems to be software dependent, some can tolerate it just fine, some can't. | Use `pathlib` to create paths. |
| Hooks are [natively available in MkDocs](https://www.mkdocs.org/user-guide/configuration/#hooks), and `mkdocs-simple-hooks` is [deprecated in favor of them](https://github.com/aklajnert/mkdocs-simple-hooks/blob/62f4adcf93732ad923026d2a66cafc45fb7852bf/README.md#deprecated). | Use the native hooks, remove `mkdocs-simple-hooks`. |

I'll update this if I find anything else.

I'm happy to open a PR if my resolutions are deemed reasonable. I can also strip out and include my website contribution documentation changes from https://github.com/twpayne/chezmoi/pull/3177 as a general quality pass.

**Comment by twpayne** [comment]
This all sounds fantastic. Please do this! :)
