### ISSUE TITLE
Foolproof `chezmoi remove`

### ISSUE THREAD

**Issue by Azorlogh** [twpayne/chezmoi#3182]
## Is your feature request related to a problem? Please describe.

Might be somewhat controversial, but `chezmoi` makes it too easy to accidentally remove a directory full of content, because people might mix up `chezmoi remove` with `chezmoi forget`.
 
I know that `chezmoi remove` does show the paths that will get removed, and one should be careful about using a command with `remove` anyway, but I think the cost of losing files you care about is important enough to warrant making the command more foolproof.

## Describe the solution you'd like

Renaming `chezmoi remove` to `chezmoi remove-permanently` or similar.
Making `chezmoi remove` only return a message that approximately says: "Use `chezmoi forget` to remove a target from the source state. Use `chezmoi remove-permanently` to delete the actual item"

## Describe alternatives you've considered

Showing a red warning when executing `chezmoi remove` to make it clear that it deletes actual files
A clear and concise description of any alternative solutions or features you've
considered.

I understand that my proposed solution is a breaking change hence why I think it might be controversial. But I think it's worth it, as it's more foolproof than a warning (at the point where the warning would be shown, the user is only one keypress away from deleting the file/directory after all).

**Comment by twpayne** [comment]
I'm sorry that you deleted your files, but no to this. `chezmoi remove` behaves like `rm` by design. As you point out, it already includes multiple layers of protection against accidental misuse. In the worst case you should be able to restore the source file from your git repo.
