### ISSUE TITLE
Re-usable condition

### ISSUE THREAD

**Issue by ckt114** [twpayne/chezmoi#3183]
## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

I have a condition such as `{{ if and (eq "linux" .chezmoi.os) (not (eq "nixos" .chezmoi.osRelease.id)) }}` that I use in many different files and currently I have to copy that exact condition to every file. Is it possible to save that condition as something value and use it again in any file I want?

## Describe alternatives you've considered

Not aware of any alternative.

## Additional context

N/A

**Comment by halostatue** [comment]
Yes. Go templates treat the empty string as falsy:

```console
$ chezmoi execute-template '{{ if "" }}"yes"{{ else }}"no"{{ end }}'
"no"
```

So you can add that as `linux-not-nixos.tmpl` (the `.tmpl` may not be required in `.chezmoitemplates`), to [`.chezmoitemplates`](https://www.chezmoi.io/reference/special-files-and-directories/chezmoitemplates/) and use `{{ if (includeTemplate "linux-not-nixos.tmpl" .) }}`.

For a more advanced example with a JSON map, see my [`.chezmoitemplates/programs.tmpl`](https://github.com/halostatue/dotfiles/blob/main/home/.chezmoitemplates/programs.tmpl) and how I use it in [`private_dot_config/git/diff-merge.tmpl`](https://github.com/halostatue/dotfiles/blob/main/home/private_dot_config/git/diff-merge.tmpl).

**Comment by twpayne** [comment]
This is best done as a variable in the `data` section of your configuration file. This section is for data that is specific to the local machine but does not change.

For example, I have [this](https://github.com/twpayne/dotfiles/blob/f25b14407ec63b79b8c84a3a3159431fc4c02c24/home/.chezmoi.toml.tmpl#L9-L12) in my config file template:

```
{{- $osID := .chezmoi.os -}}
{{- if (and (eq .chezmoi.os "linux") (hasKey .chezmoi.osRelease "id")) -}}
{{-   $osID = printf "%s-%s" .chezmoi.os .chezmoi.osRelease.id -}}
{{- end -}}

[data]
    osid = {{ $osID | quote }}
```

which means my generated config file will contain something like:

```toml
[data]
    osid = "linux-nixos"
```

and I can then use `.osid` in my templates like:

```
{{ if eq .osid "linux-nixos" }}
...
{{ end }}
```

**Comment by ckt114** [comment]
Thanks @twpayne and @halostatue for your suggestions. I'll give these a try.
