### ISSUE TITLE
include, includeTemplate with git submodules

### ISSUE THREAD

**Issue by vaygr** [twpayne/chezmoi#3186]
## What exactly are you trying to do?

I'm using chezmoi with 2 git repositories, where one is a git submodule of the other. The main benefit is that I can have a small subset of dotfiles synced and available on a specific subset of nodes (e.g. servers) while parent repository that's used primarily on workstations can have symlinks to the files/templates in that "server" sub-repository. That works perfectly.

However when using a more lightweight approach for handling machine-to-machine differences (as described in [Without using symlinks](https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#without-using-symlinks)), I found out that both `include` and `includeTemplate` don't take sub-repo relativity into account.

For example, if I have:

```shell
$ cat dot_test.tmpl
{{ includeTemplate "test_template" }}
```

in `~/.local/share/chezmoi/dot_sdots` and this is executed on a node that uses parent git repository, it would look for a template in `~/.local/share/chezmoi/.chezmoitemplates` first, then fallback to `~/.local/share/chezmoi/`. Same for `include`.

Shouldn't chezmoi look for include files/templates relative to the original repository path (which in the example above would be `~/.local/share/chezmoi/dot_sdots`)?

## What have you tried so far?

N/A

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose $COMMAND
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
chezmoi doesn't know about git submodules when reading the source state. To chezmoi, the source state is just a normal directory.

Extending chezmoi to understand git submodule structures is something that I don't want to do for multiple reasons:
1. I want to keep the structure of chezmoi's source directory as simple as possible and keep the structure independent of the underlying VCS used.
2. git is complex, and I don't want to try to emulate git's functionality in chezmoi if I can avoid it.
3. In my experience, git submodules are a fractal nightmare of broken abstractions. I would recommend using absolutely anything else except git submodules if you can.

The whole point of chezmoi is that you can keep all your dotfiles for multiple machines in a single repo. chezmoi provides a huge range of features for controlling exactly which dotfiles are present on each machine, how their contents adapt to the local machine, and ensuring that secrets don't leak. Fundamentally, if you're using chezmoi with multiple dotfile repos, then you're not holding chezmoi correctly.

So, I would instead recommend using something like [this](https://github.com/twpayne/chezmoi/discussions/3202#discussioncomment-6855785) instead.
