### ISSUE TITLE
External files not being ignored when in sub directory of .chezmoiignore entry

### ISSUE THREAD

**Issue by stablestud** [twpayne/chezmoi#3196]
## Describe the bug

Same as #1520 but the bug has reappeared, or was never fixed?

When a directory has been ignored by `.chezmoiignore`, external files defined in `.chezmoiexternal.toml` are still placed into the ignored directory.

## To reproduce
Having this `.chezmoiignore`
```console
.config/i3
.config/rofi
.var/app
LICENSE
```
and this `.chezmoiexternal.toml.tmpl`
```toml
[".config/rofi/theme.rasi"]
	type = "file"
	url = "https://github.com/jan-warchol/selenized/raw/v1.0/other-apps/rofi/selenized-white.rasi"
	checksum.sha512 = "6c7a9410bb7347c215f2e74be07cc518800398987eea4bbad7e0e89ac67c0fc486295d47806a7a3c46d8ee80d98a00bc116918c2d5228e2e2b15ca2ca9d25348"
[".config/i3/theme.conf"]
	type = "file"
	url = "https://github.com/jan-warchol/selenized/raw/v1.0/other-apps/i3/i3-selenized-black.conf"
	checksum.sha512 = "9d70b42aa3faea7d50f03f719f2056ec4bcc93761d8d0638e6571fe930ff12fb55f728c74367784ece8c6f788d4a31e076de18950c79e39ee7ea80b01a1056ee"
```
and this source state directory (shortened ouput)

<details>

```console
$ tree 
.
├── LICENSE
├── private_dot_config
│   ├── i3
│   │   ├── applications.conf.tmpl
│   │   ├── bindings.conf.tmpl
│   │   ├── config.tmpl
│   │   ├── create_empty_custom.conf.tmpl
│   │   ├── i3status.conf.tmpl
│   │   ├── multimedia.conf.tmpl
│   │   ├── run_after_i3-init.sh.tmpl
│   │   └── workspaces.conf.tmpl
│   └── rofi
│       └── config.rasi
```

</details>

produces this ignored output

```console
$ chezmoi --verbose ignored
.config/i3
.config/rofi
.var/app
LICENSE
```
and this managed output
```console
$ chezmoi --verbose managed
.bin
.config
.config/i3
.config/i3
.config/i3/theme.conf
.config/rofi
.config/rofi
.config/rofi/theme.rasi
.gitconfig
.var
```
Both `theme.*` files are still being placed but this is wrong, because as in #1520 described, ignoring a parent path should ignore the complete tree (sub dirs)

## Expected behavior

Instead I expect the external files to be ignored and not managed/placed into these directories (output generated with applied fix #3197)

```console
$ chezmoi ignored
.config/i3
.config/i3/theme.conf
.config/rofi
.config/rofi/theme.rasi
.var/app
LICENSE
```

```console
$ chezmoi managed
.bin
.config
.gitconfig
.var
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.38.0, commit 0ce82b3a958191ee441034ee78da4b9440b51dc0, built at 2023-08-21T18:02:24Z, built by goreleaser
ok        latest-version       v2.38.0
ok        os-arch              linux/amd64 (Ubuntu 22.04.3 LTS (Jammy Jellyfish))
ok        uname                Linux hp-250-g8 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version           go1.21.0 (gc)
ok        executable           /snap/chezmoi/739/chezmoi
ok        upgrade-method       snap-refresh
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2023-08-27T15:07:08+02:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                002
ok        cd-command           found /usr/bin/fish
ok        cd-args              /usr/bin/fish
info      diff-command         not set
ok        edit-command         found /usr/bin/vim
ok        edit-args            /usr/bin/vim
ok        git-command          found /usr/bin/git, version 2.34.1
ok        merge-command        found /usr/bin/vimdiff
ok        shell-command        found /usr/bin/fish
ok        shell-args           /usr/bin/fish
info      age-command          age not found in $PATH
ok        gpg-command          found /usr/bin/gpg, version 2.2.27
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      dashlane-command     dcli not found in $PATH
info      doppler-command      doppler not found in $PATH
info      gopass-command       gopass not found in $PATH
ok        keepassxc-command    found /usr/bin/keepassxc-cli, version 2.6.6
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      rbw-command          rbw not found in $PATH
info      vault-command        vault not found in $PATH
info      vlt-command          vlt not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

I inspected the code and to my understanding the fix in #1520 never worked because `doublestar` doesn't consider the pattern `.config/i3` to match with `.config/i3/theme.conf`, either this is a bug with doublestar or we should make sure that the pattern `.config/i3` always matches its subcontent/subdirs, by appending `/**` to the pattern

**Comment by stablestud** [comment]
I created a fix in #3197 that works and that generated the expected behavior (see above)

**Comment by twpayne** [comment]
chezmoi allows you to ignore a directory but not its contents. This is different to `.gitignore`, which cannot make such a distinction. If you want to ignore a directory **and** its contents then you need both `dir` and `dir/**` in your `.chezmoiignore` file.

**Comment by stablestud** [comment]
Thanks

**Comment by bradenhilton** [comment]
> chezmoi allows you to ignore a directory but not its contents. This is different to `.gitignore`, which cannot make such a distinction. If you want to ignore a directory **and** its contents then you need both `dir` and `dir/**` in your `.chezmoiignore` file.

@twpayne Doesn't that mean the example in the docs is incorrect?

https://github.com/twpayne/chezmoi/blob/ba186488bd165990033945357ab9589ba52dd35e/assets/chezmoi.io/docs/reference/special-files-and-directories/chezmoiignore.md#L30-L32

Shouldn't the first comment say something like `# ignore backups folder in chezmoi directory but not its contents`?

**Comment by twpayne** [comment]
> Shouldn't the first comment say something like `# ignore backups folder in chezmoi directory but not its contents`?

Yes, you're correct. The docs are wrong.
