### ISSUE TITLE
More information on dashlanePasword

### ISSUE THREAD

**Issue by hulk510** [twpayne/chezmoi#3218]
## Is your feature request related to a problem? Please describe.

I successfully implemented to apply dashlane passwords using chezmoi, but it took a time to understand. Having more information in the [dashlanePassword documentation](https://www.chezmoi.io/reference/templates/dashlane-functions/dashlanePassword/) would have been helpful in saving time.

## Describe the solution you'd like

1. It would be beneficial to include specific details about what the "filter" refers to. 
 I read onepassword’s document first, so I thought "id" is filter parameter, however dashlanePassword filter "title" in the json.

![output dashlanePassword json](https://github.com/twpayne/chezmoi/assets/33943897/f1c2169b-ef46-4021-bc4d-7b6b82e08eea)

2. it would be helpful to provide guidance in the documentation regarding the usage of `{{ (index (dashlanePassword "filter") 0).password }}`. 
Firstly I write `{{ (index (dashlanePassword "filter") 0).password }}`, and it isn't changed to dashlane password value, I spent a significant amount of time attempting to troubleshoot, and I later realized that the file extension required set to template file.
I believe that including some form of guidance or reference to the [template page](https://www.chezmoi.io/user-guide/templating/#creating-a-template-file) would be beneficial.

## Additional context

**Comment by halostatue** [comment]
I agree with #1, and we would happily take a PR for that.

I’m less certain about #2, as the `dashlanePassword` template function is in the section on template functions. I think that there should be more cross-documentation linkage overall (and I have started doing so when it seems appropriate), but I’m not sure that this particular piece would be useful.

**Comment by hulk510** [comment]
thanks for the reply.

oh, sorry I didn't realize there is in template section. 
now I confirm to exist in the section!
![スクリーンショット 2023-09-05 8 47 38](https://github.com/twpayne/chezmoi/assets/33943897/bb553bd8-08cc-4d44-a0d0-a6e5a06de8e3)

The section had a large amount of accordions open and seemed a bit difficult to notice right away.
I thought it would be nice if this sticky scroll section, like "reference" in the image.

**Comment by halostatue** [comment]
That would improve things, but it is a part of the documentation template I don’t know anything about (it’s all in `mkdocs`).

**Comment by hulk510** [comment]
I see, thank you for sharing. I would like to create an issue if I find a good way to do this in mkdocs again.

Thank you very much.

**Comment by twpayne** [comment]
Thanks for offering to help @hulk510. I've assigned this issue to you.

**Comment by twpayne** [comment]
Please create a PR when you have one. In the meantime, I'll close this issue.
