### ISSUE TITLE
Example chezmoi.toml config file and the ability to specify its location

### ISSUE THREAD

**Issue by cshao06** [twpayne/chezmoi#322]
Hi Tom,

I came across this repo when I was looking for a config file manager. This seems to fit my needs really well.

As I bootstrap on this tool. I wish I could specify the location of the chezmoi.toml config file and just put it in the same git repo that it manages.

Also, it'd be nice if you can show an example chezmoi.toml file for people to start with easily.

Thanks!

**Comment by twpayne** [comment]
My config file looks like:

```
[data]
    name = "My Name"
    email = "me@mydomain.com"
```

This is only needed as I'm using templates for some of my dotfiles. For basic usage, you don't need a config file at all.

The reason that the config file is separate from the source directory is that the source directory specifies what is the same across all machines and the config file specifies what is specific to the current machine. If everything is the same across all machines then you don't need a config file.

If you really, really want the config file to be in the source directory, then it's easier to put the config file in a default location `e.g. ~/.config/chezmoi` and specify the source directory to be the same directory in the config file. You'll want to include the config file in `.chezmoiignore`.

**Comment by twpayne** [comment]
Please re-open if this hasn't answered your question.

**Comment by pvinis** [comment]
Is this file supposed to be shared?

Or I'm supposed to do 
```
[data]
  something = "value"
```
when I want it to stay local and off the repo, and 
```
{{ if ne .chezmoi.hostname "work-laptop" -}}
value
{{- end }}
```
when I want it to be in the repo and dependent on the name of the machine?

**Comment by twpayne** [comment]
The config file is not supposed to be shared, but you can if you want.

**Comment by pvinis** [comment]
Cool. Thanks!
