### ISSUE TITLE
WinGet installed a really old version?

### ISSUE THREAD

**Issue by cglong** [twpayne/chezmoi#3224]
## Describe the bug

I'm trying to init a new Windows machine with an existing repo and getting an error when processing my template.

## To reproduce

1. Install chezmoi using WinGet
2. Run `chezmoi init cglong`

## Expected behavior

The templates to be successfully processed and my dotfiles to be applied.

## Output of command with the `--verbose` flag

```console
~ ❯ chezmoi --verbose init cglong
chezmoi: template: chezmoi.toml:1: function "promptStringOnce" not defined
```

## Output of `chezmoi doctor`

<details>

```console
~ ❯ chezmoi doctor
RESULT    CHECK                MESSAGE
ok        version              v2.9.4, commit 7f0702503528fb708a5d9fc7b2a826decb777b26, built at 2021-12-19T22:18:18Z, built by goreleaser
ok        os-arch              windows/amd64
ok        go-version           go1.17.5 (gc)
ok        executable           C:/Program Files/Chezmoi/chezmoi.exe
ok        config-file          no config file found
ok        source-dir           ~/.local/share/chezmoi is a directory
warning   suspicious-entries   ~/.local/share/chezmoi/home/.chezmoidata.toml, ~/.local/share/chezmoi/home/.chezmoiexternal.toml.tmpl, ~/.local/share/chezmoi/home/.chezmoiignore.tmpl, and ~/.local/share/chezmoi/home/private_dot_config/.chezmoiignore.tmpl
ok        working-tree         ~/.local/share/chezmoi is a directory
ok        dest-dir             ~ is a directory
ok        shell                found C:/WINDOWS/system32/cmd.exe
ok        edit-command         found C:/WINDOWS/system32/notepad.exe
ok        git-command          found C:/Program Files/Git/cmd/git.exe, version 2.42.0
warning   merge-command        vimdiff not found in $PATH
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set
```

</details>

## Additional context

Even though `chezmoi doctor` is reporting a very old version, WinGet says I have the latest version installed:

```console
~ ❯ winget list chezmoi
Name    Id              Version Source
---------------------------------------
chezmoi twpayne.chezmoi 2.39.1  winget
```

**Comment by twpayne** [comment]
This is really weird. 2.9.4 is indeed ancient. even predating chezmoi's WinGet package by about two years.

chemzmoi 2.39.1 was added to WinGet yesterday in https://github.com/microsoft/winget-pkgs/pull/119009 and only includes references to chezmoi 2.39.1.

Is it possible that you have an old chezmoi.exe from somewhere else, e.g. restored from backup?

**Comment by bradenhilton** [comment]
Your `chezmoi doctor` output shows the executable as `C:/Program Files/Chezmoi/chezmoi.exe`. Unless you manually installed it to this path with WinGet, I suspect you manually installed version 2.9.4 there by some other means at some point.

You can run `$env:PATH -split ';'` in PowerShell to see if `C:\Program Files\Chezmoi` comes before `C:\Users\<USER>\AppData\Local\Microsoft\WinGet\Links`.

You should be able to safely delete the `C:\Program Files\Chezmoi` directory (after inspecting its contents, of course) or at least remove it from your `PATH`.

**Comment by cglong** [comment]
D'oh! You were exactly right @bradenhilton; sorry for the noise 😵‍💫
