### ISSUE TITLE
Builtin Age decrypt throws invalid armor error and fails to decrypt file

### ISSUE THREAD

**Issue by arrrgi** [twpayne/chezmoi#3226]
## Describe the bug

After introduction of 205fd6c I am getting an error that chezmoi was unable to decrypt an Age encrypted file. Chezmoi throws an error that the armor is invalid.

## To reproduce

Following along with docs here: [Encryption](https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/)

1. First create key file with age-keygen `age-keygen | age --passphrase > key.txt.age` on development system with **age** installed
2. Attempt to decrypt key file on target system with `chezmoi age decrypt --output "${HOME}/.config/chezmoi/key.txt" --passphrase "${HOME}/.local/share/chezmoi/home/.keys/key.txt.age"`

## Output of command with the `--verbose` flag

```console
chezmoi: failed to read header: parsing age header: failed to read intro: invalid armor: invalid first line: "age-encryption.org/v1"
```

## Output of `chezmoi doctor`

<details>

<br>
*Note: Output reduced for brevity as the command output could not be copy/pasted from the source machine*

```console
version    v2.39.1
os-arch    darwin/amd64
age-command    age not found in $PATH
```

</details>

**Comment by arrrgi** [comment]
Error can currently be reproduced from my public dotfiles repo on the development branch: https://github.com/arrrgi/dotfiles/tree/feature/setup-scripts

**Comment by twpayne** [comment]
Ah, the instructions forgot to include the `--armor` flag when generating the key.

This

    age-keygen | age --passphrase > key.txt.age

should be

    age-keygen | age --armor --passphrase > key.txt.age

I'll update the docs and add functionality to `chezmoi age decrypt` to handle non-armored files.

**Comment by arrrgi** [comment]
Will report back.

Is there a reason to prefer armored/PEM encoded files?

**Comment by twpayne** [comment]
> Is there a reason to prefer armored/PEM encoded files?

Yes, they tend to survive being mangled by version control systems and weird operating systems like Windows better.

**Comment by arrrgi** [comment]
Confirmed that worked. My source file contains the Base64 encoded contents and target state had the decrypted file as expected.
