### ISSUE TITLE
Setting sourceDir = "~/myconfig" doesn't work well with chezmoi add

### ISSUE THREAD

**Issue by cshao06** [twpayne/chezmoi#323]
Hi Tom,

I tried to put the source directory to an existing git repo I have, by setting `sourceDir = "~/myconfig"` in `chezmoi.toml`. However, when I run `chezmoi add ~/file`, it will create a `~` folder in whatever directory I'm running `chezmoi add` from. I think the correct behavior should be addng `file` to ~/myconfig.

Also, the default value of `sourceDir` in the `configuration variable` section in REFERENCE.md is wrong.

Thanks!

**Comment by twpayne** [comment]
This is because `~` is expanded by your shell to be your home directory. chezmoi doesn't (yet) support it in config values. You have to use the full path.
