### ISSUE TITLE
No support for deletion

### ISSUE THREAD

**Issue by alzedd** [twpayne/chezmoi#324]
I was trying to remove a file this morning from my dotfiles repo, did a chezmoi update && chezmoi apply and the file in my config was still there.

Is there something I missed? If a file is deleted from the repo it should be removed in the config when doing a chezmoi apply

**Comment by twpayne** [comment]
See [the FAQ entry](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#how-do-i-tell-chezmoi-to-always-delete-a-file).

If you delete a file in the source directory, chezmoi can't tell if this means that you want to delete the file in the target directory or if you no longer want to manage that file in chezmoi. chezmoi has no memory of which files it has managed in the past, it can only inspect the current state of the source and target directories.

That said, it might be worth adding explicit support for deletion. I'm thinking of something like: if a file called `.chezmoiremove` exists in the source directory, it is treated as a list of patterns of files to remove. This requires some thought though: what if a file exists in the source directory and matches one of the remove patterns?

**Comment by alzedd** [comment]
Oh Ok, I totally missed that. I saw the part regarding templates instead (if the result file of a template is an empty file it will be removed). 
I'm going to re add file so, but this time it will be empty.

a .chezmoiremove file can lead to a really bad behaviors, I don't think it's a good choice. 

I think I will just empty the files I want to delete from my config, commit, push, apply, and in the next commit remove them from the repo. It will works anyway.


Thank you (again)

**Comment by twpayne** [comment]
Thanks, the `--remove` flag is a good idea.

**Comment by alzedd** [comment]
I was thinking about your `.chezmoiremove` file.
how about adding a `.{$hostname}apply` which can contain all the files that can be applied on a single machine (based on the hostname, obviously).

```
dot_vimrc #appliable
!dot_another_vimrc # explicit removable
# every other file in the repo will not be handled by chemoi
```
(basically it will work the opposite way as a gitignore)


Do you mind if I write some kind of proposal?

**Comment by twpayne** [comment]
See also #205 for a suggestion to include the hostname in the filename.

I'm not a great fan of the `.apply` idea because:

* You'll have to create an `.apply` file for every host, which is lots of extra work.
* Whenever you add a file, you have to remember to add it to every `.apply` file.
* In my opinion, managed files should be included by default, exclusion should be explicit, not the other way around.

Feel free to write a proposal if you wish, but anything proposed should be consistent with how chezmoi currently works.
