### ISSUE TITLE
chezmoi update --verbose does not use pager in config

### ISSUE THREAD

**Issue by Crissante** [twpayne/chezmoi#3240]
## Describe the bug

When running `chezmoi update --verbose --dry-run` the diff is printed directly to the terminal without going through the pager set in config.toml

## To reproduce

1) Set the pager in config.toml
```toml
pager = "delta"
```
2) Make some changes in the source directory
3) Run `chezmoi update --verbose --dry-run`

## Expected behavior

The diff is passed to the pager

## Doctor output

<details>
<summary>Output</summary>

<pre>
RESULT   CHECK                       MESSAGE
ok       version                     v2.39.1, commit fe10a696fb9aad76776bce62f9fa9a4363bac62a, built at 2023-09-06T00:35:40Z, built by Homebrew
ok       latest-version              v2.39.1
ok       os-arch                     darwin/arm64
ok       go-version                  go1.21.0 (gc)
ok       executable                  /opt/homebrew/bin/chezmoi
ok       upgrade-method              brew-upgrade
ok       config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2023-09-14T22:58:45-07:00
ok       source-dir                  ~/.dotfiles is a git working tree (clean)
ok       suspicious-entries          no suspicious entries
ok       working-tree                ~/.dotfiles is a git working tree (clean)
ok       dest-dir                    ~ is a directory
ok       umask                       022
ok       cd-command                  found /opt/homebrew/bin/fish
ok       cd-args                     /opt/homebrew/bin/fish
ok       diff-command                found /opt/homebrew/bin/delta
ok       edit-command                found /usr/bin/vim
ok       edit-args                   /usr/bin/vim
ok       git-command                 found /opt/homebrew/bin/git, version 2.42.0
ok       merge-command               found /usr/bin/vimdiff
ok       shell-command               found /opt/homebrew/bin/fish
ok       shell-args                  /opt/homebrew/bin/fish
info     age-command                 age not found in $PATH
info     gpg-command                 gpg not found in $PATH
info     pinentry-command            not set
info     1password-command           op not found in $PATH
info     bitwarden-command           bw not found in $PATH
info     bitwarden-secrets-command   bws not found in $PATH
info     dashlane-command            dcli not found in $PATH
info     doppler-command             doppler not found in $PATH
info     gopass-command              gopass not found in $PATH
info     keepassxc-command           keepassxc-cli not found in $PATH
info     keepassxc-db                not set
info     keeper-command              keeper not found in $PATH
info     lastpass-command            lpass not found in $PATH
info     pass-command                pass not found in $PATH
info     passhole-command            ph not found in $PATH
info     rbw-command                 rbw not found in $PATH
info     vault-command               vault not found in $PATH
info     vlt-command                 vlt not found in $PATH
info     secret-command              not set
</pre>

</details>

## Additional context

The pager is used when running `chezmoi diff`

**Comment by twpayne** [comment]
What is the output of `chezmoi doctor`?

**Comment by twpayne** [comment]
For info, I confirm that this is a bug. The pager is only used in the `diff` command, and is not used in the `update` or `apply` commands (amongst others). Fixing this will require some fairly deep changes.

**Comment by Crissante** [comment]
> What is the output of `chezmoi doctor`?

Added to the description!
