### ISSUE TITLE
Understand where `chezmoi execute-template` runs into command not found error, related to symlink

### ISSUE THREAD

**Issue by jackmac92** [twpayne/chezmoi#3245]
## What exactly are you trying to do?

I've used chezmoi for a few years, on a number of computers. But setting up a new computer I get an error when I run `chezmoi execute-template` and I'm confused.

## What have you tried so far?

Trying to debug a chezmoi `run_*.sh.tmpl` script, via `chezmoi execute-template` I get the following error

```
chezmoi: stat /Users/jmccown/.why-is-chezmoi-looking-here-at-all-i-dont-know: no such file or directory
```

The file in question exists as a symlink

```
chezmoi --verbose execute-template                                                                                                           ─╯
Alias tip: cz --verbose execute-template
chezmoi: stat /Users/jmccown/.local/share/chezmoi/chez-ignore/scripts/core/scripts/cbi/set-branchname-for-ticket: no such file or directory
```

## Output of `chezmoi doctor`

```
RESULT    CHECK                MESSAGE
warning   version              v2.33.6, built by nixpkgs
warning   latest-version       v2.39.1
ok        os-arch              darwin/amd64
ok        uname                Darwin jmccown 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64 x86_64
ok        go-version           go1.20.8 (gc)
ok        executable           /etc/profiles/per-user/jmccown/bin/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2023-09-13T13:30:10-04:00
warning   source-dir           ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries   no suspicious entries
warning   working-tree         ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found ~/.doom.d/bin/e
ok        edit-args            ~/.doom.d/bin/e -w
ok        git-command          found /etc/profiles/per-user/jmccown/bin/git, version 2.40.1
ok        merge-command        found ~/.doom.d/ediff
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
info      age-command          age not found in $PATH
info      gpg-command          gpg not found in $PATH
info      pinentry-command     not set
info      1password-command    op not found in $PATH
ok        bitwarden-command    found /etc/profiles/per-user/jmccown/bin/bw, version 2023.4.0
info      dashlane-command     dcli not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
ok        lastpass-command     found /etc/profiles/per-user/jmccown/bin/lpass, version 1.3.4
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      rbw-command          rbw not found in $PATH
ok        vault-command        found /etc/profiles/per-user/jmccown/bin/vault, version 1.13.3
info      secret-command       not set
```

## Additional context

Not sure, open to ideas on user error haha

**Comment by twpayne** [comment]
What are the exact commands that reproduce the problem?

`chezmoi execute-template` is for testing and debugging templates. There is no reason to run it on a new machine.

What refers to `/Users/jmccown/.why-is-chezmoi-looking-here-at-all-i-dont-know`? This string is only mentioned once, without context.

What refers to `/Users/jmccown/.local/share/chezmoi/chez-ignore/scripts/core/scripts/cbi/set-branchname-for-ticket`? This string is also mentioned only once, without context.

If you want people to help you then you have to do the minimum work of describing your problem in a way that they have enough information to debug what could be wrong.

**Comment by jackmac92** [comment]
@twpayne apologies for the really bad report. I was overtired

I found the issue on my end is not caused by chezmoi, but quick description of how I broke it.
The symlink file in question is broken on the new machine. It is a non-chezmoi symlink which was broken because I made it on linux and it points to `/home`   

below is directly from my terminal, and what was stumping me. 
```
chezmoi --verbose execute-template                                                                                                           ─╯
Alias tip: cz --verbose execute-template
chezmoi: stat /Users/jmccown/.local/share/chezmoi/chez-ignore/scripts/core/scripts/cbi/set-branchname-for-ticket: no such file or directory
```

Execute template "seemed" more stateless, so I was surprised it cared about that file from my source dir at all.
I'm still not sure why that caused `execute-template` to fail, but I can rework the symlink problem that seems to be the root cause.

**Comment by jackmac92** [comment]
If the error w/ `execute-template` is something you want to look into I can try to make a small repo to reproduce the issue. Otherwise feel free to close this

**Comment by twpayne** [comment]
Thank you for following up!

I would love a repo that reproduces the issue. Fixing this bug now means that people won't encounter it in the future which will helps me and all current and future chezmoi users :)

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
