### ISSUE TITLE
Script execution not following ASCII / alphabetical order in subdirectories

### ISSUE THREAD

**Issue by arrrgi** [twpayne/chezmoi#3246]
## What exactly are you trying to do?

I have a .chezmoiscripts folder which has 3 nested directories:

**.chezmoiscripts**
- .chezmoiscripts/darwin
- .chezmoiscripts/global
- .chezmoiscripts/linux

The `darwin` directory has two scripts:
- run_onchange_before_10_setup-install-homebrew.sh.tmpl
- run_onchange_before_20_setup-brew-packages.sh.tmpl

The `global` directory has one script:
- run_before_00_bootstrap_decrypt-age-key.sh.tmpl

The `linux` directory is currently empty.

The `run_before_00_bootstrap-decrypt-age-key.sh.tmpl` should evaluate as the first script to be executed by the file naming convention.

I observed that Chezmoi also follows ASCII ordering for subdirectories, and by changing the `global` directory to the name `bootstrap` (or other name that evaluated as higher in precedence), the script ran first as desired. Is this an intended behaviour to have directory names in the **.chezmoiscripts** folder define order or execution?

If not, perhaps this could be a bug. If this is intended, I would suggest a docs update to make this clear.

## What have you tried so far?

I was able to resolve this by renaming the `global` directory to `bootstrap` as it seems that sub-directories are also processed in ASCII order.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by bradenhilton** [comment]
The subdirectory is part of the target path/name. If it wasn't, you could easily run into collisions with identically named files in separate directories. `.chezmoiscripts` entries still have a target path despite no file in the destination state being created.

From https://www.chezmoi.io/reference/application-order:

> 4. Run `run_before_` scripts in alphabetical order.
> 5. Update entries in the target state (files, directories, externals, scripts, symlinks, etc.) in alphabetical order of their target name. Directories (including those created by externals) are updated before the files they contain.
> 6. Run `run_after_` scripts in alphabetical order.
>
> Target names are considered after all attributes are stripped.

```console
chezmoi\home
❯ Get-ChildItem -File -Path @('.\.chezmoiscripts\global\', '.\.chezmoiscripts\darwin\', '.\.chezmoiscripts\linux\') | ForEach-Object { [System.IO.Path]::GetRelativePath((chezmoi target-path), (chezmoi target-path $_)) } | Sort-Object
.chezmoiscripts\darwin\10_setup-install-homebrew.sh
.chezmoiscripts\darwin\20_setup-brew-packages.sh
.chezmoiscripts\global\00_bootstrap_decrypt-age-key.sh
```

(Note how I deliberately accumulated the source directories in a non-alphabetical order and then finally sorted the target paths relative to the destination directory)

If the script really is global as you mention, consider moving it outside of the subdirectory i.e. `.chezmoiscripts/run_before_00_bootstrap_decrypt-age-key.sh.tmpl`:

```console
chezmoi\home
❯ Get-ChildItem -File -Path @('.\.chezmoiscripts\darwin\', '.\.chezmoiscripts\linux\', '.\.chezmoiscripts\') | ForEach-Object { [System.IO.Path]::GetRelativePath((chezmoi target-path), (chezmoi target-path $_)) } | Sort-Object
.chezmoiscripts\00_bootstrap_decrypt-age-key.sh
.chezmoiscripts\darwin\10_setup-install-homebrew.sh
.chezmoiscripts\darwin\20_setup-brew-packages.sh
```

(Again, note the deliberate incorrect order in which I generate the target paths, before sorting them)

**Comment by arrrgi** [comment]
Thanks for the clear and excellent explanation @bradenhilton 

> Target names are considered after all attributes are stripped.

This was the lightbulb moment in the documentation for me.
