### ISSUE TITLE
Re-usable associated text/templates

### ISSUE THREAD

**Issue by duckbrain** [twpayne/chezmoi#325]
I'm currently in transition from i3 to sway. Most of the configuration files are the same, but each has parts the other does not. sway supports including an external file in its configuration, but i3 does not.  i3 recommends templating if you need something like that. Right now I have to copy my changes between the two templates.

I'd use the config file, but then I'd be putting a large multi-line string in my config file and it wouldn't be source controlled. My other consideration was setting `genericSecret.command` to `cat`, and including the file that way, but that just seems kinda messy.

I'd like to have a way to include another "partial" template into the Go templates. Add a new directory, like `.chezmoi_templates/`, from which Got text/templates are loaded and included as associated templates for the templated config files. Then including templates would look like 

```tmpl
# Configure monitors

{{template "sway3"}}

# Configure i3bar
```

Optionally, the associated templates could have context passed into them for further templating.

**Comment by twpayne** [comment]
This is a really nice idea, and what you suggest makes perfect sense. Would you like to come up with a PR? If not, I'll happily implement it, but it'll be at least a few days before I have time to work on it.

**Comment by duckbrain** [comment]
It's going to be longer than a few days for me, so go ahead.

**Comment by twpayne** [comment]
This should now be fixed. Thanks again for the great idea :)

**Comment by duckbrain** [comment]
Awesome! Thank you for getting that so fast.
