### ISSUE TITLE
chezmoi status does not work as expected

### ISSUE THREAD

**Issue by bboydflo** [twpayne/chezmoi#3250]
## Describe the bug

Hi, and thank you for this awesome project. 

I might have used `chezmoi` wrong, since I am not using it too often.  I tried to updated my `run_once_install.sh` script and pushed that to github. Now when I run `chezmoi status` I can see something like below which makes me think chezmoi reports incorrectly:

```sh
❯ chezmoi status
 R install.sh
```

## Additional context

I am confused on how to best track the `run_once_install.sh`. I think the way I did it was to use `chezmoi cd` and commit and pushed from there. Honestly I am not sure how to best track this file, since it's not a dotfile per se.

Any help would be highly appreciated!

**Comment by twpayne** [comment]
This means that `run_once_install.sh` has changed since chezmoi last ran it on this machines, so if you run `chezmoi apply` then it will run the `run_once_install.sh` script again.

**Comment by bboydflo** [comment]
Thanks! It makes sense. It's true that the script has changed, but I also pushed it to GitHub so I wasn't expected to see anything when I ran `chezmoi status`.

What would be the correct way of updating this script locally and sync it to GitHub?

**Comment by twpayne** [comment]
> What would be the correct way of updating this script locally and sync it to GitHub?

Commit your changes and push them to GitHub.
