### ISSUE TITLE
Chezmoi Config templates should have access to default data

### ISSUE THREAD

**Issue by jakeswenson** [twpayne/chezmoi#326]
I would like to be able to use default data to build my chezmoi config. Right now i have a template like:
```tmpl
[data]
    name = "Jake Swenson"
    email = "...."
    is_work = {{if eq .chezmoi.username "jakes_work_user" }}true{{else}}false{{end}}
```

but when config templates are applied default data is not available:
https://github.com/twpayne/chezmoi/blob/master/cmd/init.go#L116

Seems like it should be possible to add default config data to this template init call. 
https://github.com/twpayne/chezmoi/blob/master/cmd/config.go#L341

**Comment by twpayne** [comment]
Great spot, thank you :)
