### ISSUE TITLE
Explain merge

### ISSUE THREAD

**Issue by philippludwig** [twpayne/chezmoi#3279]
## What exactly are you trying to do?

Merge a file that has been edited on two machines.

## What have you tried so far?

`chezmoi merge`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] stackoverflow etc.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --merge ~/.emacs

<Copying vim output is a bit too much I think>
```

## Output of `chezmoi doctor`

<details>

```console
RESULT    CHECK                       MESSAGE
ok        version                     v2.40.0, commit 6a8ca1634654734bb33a036ffb9c21e6b9f4d28d, built at 2023-09-19T09:56:08Z, built by goreleaser
ok        latest-version              v2.40.0
ok        os-arch                     linux/amd64 (Debian GNU/Linux 12 (bookworm))
ok        uname                       Linux lenovo 6.5.5-2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 6.5-6.1~bookworm (2023-09-30) x86_64 GNU/Linux
ok        go-version                  go1.21.1 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2023-06-20T14:59:00+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/bash
ok        cd-args                     /bin/bash
info      diff-command                not set
ok        edit-command                found /usr/bin/emacsclient
ok        edit-args                   /usr/bin/emacsclient
ok        git-command                 found /usr/bin/git, version 2.39.2
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/bash
ok        shell-args                  /bin/bash
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.2.40
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
ok        pass-command                found /usr/bin/pass, version 1.7.4
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

So "now" (since 2019 it seems) `chezmoi merge` is here and I tried to merge my `.emacs` file that I modified on machine A, pushed and then modified on machine B before pulling there. Silly me, I know.

Therefore I ran `chezmoi merge`, then `vimdiff` opens and I have no clue what to do. Consulting the chezmoi user guide does not help, it just states that I could use other tools, but I don’t know which are easier.  I know my way around Vim, so I tried the vimdiff integrated help, but that did not clear things up. I also have a really hard time to wrap my head around "destination"/"target"/"source", what does that even mean? I was expecting a "normal" git-like merge, i.e. when I pull some repository and have a merge conflict.

I have been using git for 10 years, but never had to do a 3-way merge. I usually get away by running `git stash`, `git pull`, `git stash pop` and then resolve the conflicts manually, which is something I would like to do here.

Since I could not find any satisfying tutorial to vimdiff online, I just tried *something* and of course it destroyed my file completely.

So here is my request: Could there be some noob-friendly explanation on how to use `merge` in the user guide? Or a stash feature?

Because right now, all I want to do is have the changes in my `~/.emacs` file that I made on *both* machines.

**Comment by twpayne** [comment]
Thank you for a very kind and complete answer @halostatue.

@philippludwig please re-open this issue if you have further questions.

**Comment by philippludwig** [comment]
Everything is clear now, thanks @halostatue.
