### ISSUE TITLE
How do I handle different configuration paths on *nix and Windows?

### ISSUE THREAD

**Issue by Yatta-Tim** [twpayne/chezmoi#3294]
## What exactly are you trying to do?
I want to use chezmoi to synchronize my nvim config (and possibly more in the future) between two machines, one is running Windows, one MacOS.

## What have you tried so far?
I followed the instructions and added my nvim config on Windows with `chezmoi.exe add ~\AppData\Local\nvim`. The resulting git repository has that very path in it. When I check it out on a *nix machine and apply it with chezmoi apply, it creates a directory just like that in my home folder. However, it is expected to be `.config/nvim`.

So what do I have to do to synchronize my configs between those machines?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] I have asked on Stackoverflow

**Comment by bradenhilton** [comment]
https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#handle-different-file-locations-on-different-systems-with-the-same-contents

**Comment by Yatta-Tim** [comment]
Thanks, @bradenhilton , and sorry for having missed that in the docs.

To me, this seems like a rather tedious process, especially since it is not just one file, but all of them. I think, I'll resort to plain git, until the pain grows so much that I come back 😜

**Comment by twpayne** [comment]
https://github.com/twpayne/chezmoi/issues/2273 tracks a feature that will make this much easier.

**Comment by Yatta-Tim** [comment]
Looks promising!
