### ISSUE TITLE
should provide `chezmoi editor-root` to respect editor assumption on path for `jsonschema`

### ISSUE THREAD

**Issue by loynoir** [twpayne/chezmoi#3296]
## Is your feature request related to a problem? Please describe.

Given

- `.XXX.json` or `.YYY.yml`, have a path pattern match [jsonschemastore](https://www.schemastore.org/json/)

Expected

- When `vscode` edit `.XXX.json` or `.YYY.yml`, `vscode` will support jsonschema, including **tab-completion**,  invalid-key-value hint.

Actual

- When edit `chezmoi` source dir, there only `dot_XXX.json` `dot_YYY.yml`. So, path pattern not match, there will be no jsonschema support.

## Describe the solution you'd like

```sh
$ cat .chezmoiroot 
home
$ cat .chezmoieditorroot 
editor-root
$ chezmoi editor-root
```

equivalent to

```
$ mkdir -p editor-root
$ # begin loop
$ ln -rsf home/dot_XXX.json editor-root/.XXX.json
$ # end loop
```

So, can use `vscode` `jsonschema` support, when edit

- `editor-root/.XXX.json`

- `editor-root/.XXX.yml`

**Comment by halostatue** [comment]
I don’t see this happening, and it is complicated by the possibility of `dot_XXX.json.tmpl` which would not match in any case.

I think that a better  change would be to add `dot_aliases` to the `.aliases` `fileMatch` entry *and other similar entries* in the open source `SchemaStore/schemastore` configuration. See https://github.com/SchemaStore/schemastore/blob/39b3f7022bdd7d50c1a521414ebfae1257468157/src/api/json/catalog.json#L5410 for details.

I have opened a ticket asking if SchemaStore would be willing to accept modifications to `catalog.json` for this purpose: SchemaStore/schemastore#3335.

**Comment by halostatue** [comment]
SchemaStore maintainers are unwilling to accept such a change, and as I said, I do not believe that this meets the goals of chezmoi itself.

It would not be too difficult to write an external script that traverses the Chezmoi source directory and constructs a parallel directory. Such a script would be ideal for adding to the [Related Software](https://www.chezmoi.io/links/related-software/) list.

**Comment by twpayne** [comment]
You can already use `chezmoi edit` to edit files in the source directory with a name matching the target file, which should resolve this.

Otherwise, as @halostatue says, this is not part of chezmoi, but we'll happily add a link in related software when you implement it.
