### ISSUE TITLE
`chezmoi` should provide a `vscode` extension

### ISSUE THREAD

**Issue by loynoir** [twpayne/chezmoi#3297]
## Is your feature request related to a problem? Please describe.

Same as https://github.com/twpayne/chezmoi/issues/3296

## Describe the solution you'd like

`chezmoi` should provide a `vscode` extension, which provide virtual filesystem.

In this virtual filesystem extension, `source-state-attributes` are stripped.

In this way, 

- can use `vscode` `jsonschema` tab-completion, invalid-key-value hint.

- will not modify filesystem.

- don't need to re-run `chezmoi editor-root` when `chezmoiroot` dir structure changed.

And it's possible, because `arcanis.vscode-zipfs` provide a virtual filesystem mapping to `.zip`.

## Describe alternatives you've considered

https://github.com/twpayne/chezmoi/issues/3296

**Comment by halostatue** [comment]
I do not think that this will happen, as I do not believe that any of the major contributors are VS Code developers (and VS Code extensions must be developed in javascript/typescript, not Go); I personally no longer use VS Code. Even if we were to develop it, maintenance on such a project would quickly become a burden.

If you are interested in developing such an extension, we would happily link to it in [Related Software](https://www.chezmoi.io/links/related-software/).
