### ISSUE TITLE
Add support for a distinct `merge-all` command

### ISSUE THREAD

**Issue by ElanHasson** [twpayne/chezmoi#3311]
I'd like to be able to specify a different command for `merge-all`.

I see it's really just looping through the files to be merged and calling `merge` for each one. 

https://github.com/twpayne/chezmoi/blob/692a1154a5ea7891776f0a520550b41508e5bdb5/internal/cmd/mergeallcmd.go#L70-L75

I am making a PR for this.

**Comment by twpayne** [comment]
What command, exactly, do you want to run instead?

**Comment by ElanHasson** [comment]
We can close this if you like @twpayne per the comment on the pr.

**Comment by twpayne** [comment]
Awesome, thank you very much for the detailed follow-up in https://github.com/twpayne/chezmoi/pull/3313#issuecomment-1793092902. Much appreciated!
