### ISSUE TITLE
[Chezmoi template] include files from destination directory that is ignored in the source dir

### ISSUE THREAD

**Issue by bonecountysheriff** [twpayne/chezmoi#3312]
## What exactly are you trying to do?

There's a folder in the destination directory that I cannot include in the dotfiles because of security reasons (my dotfiles need to be publicly hosted). This directory is a collection of text config files and I need to include them in a chezmoi template file.

I need to know if this is possible using chezmoi templates.

\<source-dir\>/config.txt.tmpl
```
# usual file contents which are public
.
.
.
.

[Include <destination-dir>/ignored-dir/*]
```

When applied, this should lead to the following destination config file.

\<destination-dir\>/config.txt
```
# usual file contents which are public
.
.
.
.

# contents from <destination-dir>/ignored-dir/file1
.
.

# contents from <destination-dir>/ignored-dir/file2
.
.

# contents from <destination-dir>/ignored-dir/file3
.
.

```

## What have you tried so far?

I have gone through https://www.chezmoi.io/user-guide/include-files-from-elsewhere/, but I'm not sure it is what I am looking for since it mentions web hosted files but not local ones.

## Where else have you checked for solutions?

* [.] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [.] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [] Other, please give details.

**Comment by twpayne** [comment]
A couple of options:

1) Store the private parts of the file in your password manager and use a password manager template function to retrieve them. [I use this approach](https://github.com/twpayne/dotfiles/blob/0b983a059ea2c4b4cac6e0f5c2c55b2ba22c969d/home/private_dot_ssh/config.tmpl#L17-L19).
2) Encrypt the private parts of the file and use the `decrypt` template function to decrypt them.
3) Include the parts as separate files in either `.chezmoitemplates` or `.chezmoidata` in your source directory and use `.gitignore` to avoid storing them in your git repo. You'll then need to distribute and update the files manually.
