### ISSUE TITLE
Allowing a script to run before decryption

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [twpayne/chezmoi#3316]
## Is your feature request related to a problem? Please describe.

I often need to setup new workstations that contain encrypted files. Symmetrical encryption requires to enter the passphrase all the time, which is far too slow, so i went with age asymmetrical encryption.
However, now now i need to get my age key to all the workstations before being able to get all my dotfiles. This is really slow as well.

So my idea was to encrypt the age key with symmetrical encryption with `gpg --symmetric --cipher-algo AES256 --output ~/.local/share/chezmoi/chezmoi_age_key_encrypted.enc ~/chezmoi_age_key.txt`.
Then, i have a `pre_run_once_init.sh` script that runs `gpg --decrypt --output "~/chezmoi_age_key.txt" ~/.local/share/chezmoi/chezmoi_age_key_encrypted.enc`.
However, despite this being a `pre_` script, it seems it does not run before the decryption step, as when i run `chezmoi apply`, i get a `chezmoi: open /home/matthieu/chezmoi_age_key.txt: no such file or directory` error.
So, it would be nice to have a way to run scripts at the very beginning, before the encryption key is checked.

## Describe the solution you'd like
A way to have scripts run before the decryption step.

**Comment by twpayne** [comment]
> Then, i have a `pre_run_once_init.sh` script that runs `gpg --decrypt --output "~/chezmoi_age_key.txt" ~/.local/share/chezmoi/chezmoi_age_key_encrypted.enc`.
> However, despite this being a `pre_` script, it seems it does not run before the decryption step, as when i run `chezmoi apply`, i get a `chezmoi: open /home/matthieu/chezmoi_age_key.txt: no such file or directory` error.

The script needs to be called `run_once_before_init.sh`. Note `before_` not `pre_`.

**Comment by Matthieu-LAURENT39** [comment]
I have no idea how i got that mixed up, it works fine now
Sorry about that :sweat_smile:
