### ISSUE TITLE
Unexpected ignore include/exclude behaviour

### ISSUE THREAD

**Issue by awebeer256** [twpayne/chezmoi#3317]
## Describe the bug

Ignore rules don't behave the way I expected them to, having read [the documentation on them](https://www.chezmoi.io/reference/special-files-and-directories/chezmoiignore/).

## To reproduce

Add the following to your `.chezmoiignore` file:
```
.config
!.config/git
```

## Expected behaviour

Everything in `<destination>/.config` gets ignored, except for `git` and its contents.

## Actual behaviour

Everything in `<destination>/.config` gets ignored, with no exceptions.

My expected behaviour is achieved by ignore-including the *contents* of `.config`, instead of the folder itself:
```
.config/*
!.config/git
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.40.4, commit 97de3c9738828f6f5c2c282b9e8114142f07edb5, built at 2023-10-29T18:05:59Z, built by goreleaser
ok        latest-version              v2.40.4
ok        os-arch                     windows/amd64
ok        systeminfo                  Microsoft Windows 10 Pro (10.0.19045 N/A Build 19045)
ok        go-version                  go1.21.3 (gc)
ok        executable                  C:/ProgramData/chocolatey/lib/chezmoi/tools/chezmoi.exe
ok        config-file                 no config file found
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        cd-command                  found C:/WINDOWS/system32/cmd.exe
ok        cd-args                     'C:\\WINDOWS\\system32\\cmd.exe'
info      diff-command                not set
ok        edit-command                found C:/WINDOWS/system32/notepad.exe
ok        edit-args                   'C:\\WINDOWS\\system32\\notepad.exe'
ok        git-command                 found C:/Program Files/Git/cmd/git.exe, version 2.42.0
warning   merge-command               vimdiff not found in $PATH
ok        shell-command               found C:/WINDOWS/system32/cmd.exe
ok        shell-args                  'C:\\WINDOWS\\system32\\cmd.exe'
info      age-command                 age not found in $PATH
info      gpg-command                 gpg not found in $PATH
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

I was really thrown off by the statement, "All excludes take priority over all includes." I thought that would mean that you could exclude something whose parent folder is included, but evidently it doesn't.

Having now read #2509, I think I understand better: directories have intrinsic significance in chezmoi, unlike in git where they only exist as parts of paths to files (e.g. in git, a directory being empty and being nonexistent are treated the same). And the behaviour that surprised me is a consequence of that. Right?

If so, then you should really make a bigger deal of this in multiple places in the documentation. chezmoi is so *openly* built on top of git, it's important to heavily emphasize the differences to prevent people from just using their git habits and getting tripped up.

**Comment by halostatue** [comment]
We would consider pull requests suggesting improvements to any aspect of the documentation, but I would like to address one misconception:

> If so, then you should really make a bigger deal of this in multiple places in the documentation. chezmoi is so _openly_ built on top of git, it's important to heavily emphasize the differences to prevent people from just using their git habits and getting tripped up.

Chezmoi *integrates* with git (any source control, really), but it is entirely possible to use chezmoi *without* using its git integration (I use chezmoi with git, but always manage the git operations myself). The include and exclude file processing is built mostly using the git *syntax* but without reference to the git exclusion *model*.

#2509 is just one of several discussions about how `.chezmoiignore` works:

- #1977 
- #2852
- #3196 (we have not had a documentation update to address this acknowledge issue as far as I can tell)

**Comment by twpayne** [comment]
@awebeer256 any improvement to chezmoi's documentation is very welcome. Please open a PR.

As this issue has been open for nearly two months without any response from the OP, I'll close this.
