### ISSUE TITLE
Allow gpg to encrypt files with a symmeticr key

### ISSUE THREAD

**Issue by TheEdgeOfRage** [twpayne/chezmoi#332]
While encrypting with a public key is usually the better option, I sometimes want to have my dotfiles available on a server, for example, where I don't want to have to transfer my private key.

A nice solution would be to encrypt the file with `gpg --symetric` (`-c`) and an interactive password prompt, since that way I can decrypt it later using only that password.

For example by passing `--symmetric` to `chezmoi add` or something along those lines.

Decrypting would still work the way it's already implemented, since both files encrypted with `--encrypt` and `--symmetric` are decrypted using the `--decrypt` option with no extra arguments.

**Comment by twpayne** [comment]
Nice suggestion! Implemented. Thanks!

**Comment by TheEdgeOfRage** [comment]
Thank you for the quick response. Now i can complete my setup. Loving it so far.
