### ISSUE TITLE
Speed up release GitHub Action

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#3366]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when chezmoi's CI takes about 40 minutes of wall clock time. I wish that chezmoi's CI would run quicker. This is especially frustrating in release builds where the [`test-release` job](https://github.com/twpayne/chezmoi/blob/694977b904e888ba285aa0fd44617d1d59d89bc7/.github/workflows/main.yml#L143-L205) and the [`release` job](https://github.com/twpayne/chezmoi/blob/694977b904e888ba285aa0fd44617d1d59d89bc7/.github/workflows/main.yml#L343-L395) each take about twenty minutes to run, one after the other, when they share the same work.  

## Describe the solution you'd like

chezmoi's GitHub Actions should re-use work where possible to reduce the overall wall clock time. Specifically, work from the `test-release` job should be re-used in the `release` job.

## Describe alternatives you've considered

Leaving things as they are. The current CI works and only runs a few times per day.

## Additional context

I expressed frustration in [this comment](https://github.com/twpayne/chezmoi/pull/3324#issuecomment-1802931252) and @halostatue asked for clarification in [this comment](https://github.com/twpayne/chezmoi/pull/3324#issuecomment-1803058487).

**Comment by halostatue** [comment]
I’m going to look at ways that this could be improved in my spare time over the holiday week. I can't promise a lot, because I’m also going to start an upgrade to Sonoma (probably tonight).

**Comment by bradenhilton** [comment]
On a more general note regarding the other jobs, would being just a touch more selective about the changes each job depends on be an easy win?

I'm aware we already sort of do this, but I'm wondering if we can't go a bit further and see if it increases or decreases friction.

For example, I'd imagine in most cases that editing one of the install scripts wouldn't necessitate building and testing chezmoi, on several different platforms no less.

Likewise, a quick chore change on the website also shouldn't typically require building and testing chezmoi.

Perhaps we could split them as best we can into groups such as src/website/scripts etc. and be more explicit about what changes the jobs in each group require to run.

The src group would naturally contain the most jobs.

The website group could largely depend on changes to `assets/chezmoi.io/**` etc. and only run jobs related to the website.

Each group could have its own workflow file.

Just thinking out loud.

**Comment by twpayne** [comment]
Yes please! The [changes job](https://github.com/twpayne/chezmoi/blob/c9ddc841bd0866202ce2e4493b2bae044b38d5ff/.github/workflows/main.yml#L26-L49) already tries to identify code changes and [other jobs depend on its output](https://github.com/twpayne/chezmoi/blob/c9ddc841bd0866202ce2e4493b2bae044b38d5ff/.github/workflows/main.yml#L52). Further refinement very welcome :)

**Comment by halostatue** [comment]
I believe we can get even more speedup, but I am entering a very busy period and don't expect to surface until late May.

**Comment by twpayne** [comment]
Thank you @halostatue! This is a volunteer project and there are zero expectations. All the best for your busy period :)

**Comment by KapJI** [comment]
It seems for splitting goreleaser job by platform or reusing results from previous `test-release` job you need goreleaser pro subscription: https://goreleaser.com/customization/partial/

Maybe they have discount for OSS projects, if you are interested.

Here is an example implementation: https://github.com/goreleaser/goreleaser-pro-split-merge-example/blob/main/.github/workflows/nightly.yml

**Comment by twpayne** [comment]
Fixed by @KapJI, thank you so much!

**Comment by twpayne** [comment]
To close the loop on this:

I just pushed the [`v2.54.0` release](https://github.com/twpayne/chezmoi/releases/tag/v2.54.0). Thanks to @KapJI's work here, the [entire release job](https://github.com/twpayne/chezmoi/actions/runs/11758974080) took under 17 minutes, which is over 20 minutes faster than the [previous release job](https://github.com/twpayne/chezmoi/actions/runs/11551981896). This is fantastic!

Regular CI builds have are also 10 minutes or more quicker. Thank you @KapJI!
