### ISSUE TITLE
Virtual destination (Windows Registry, macOS defaults) for comparison against the source

### ISSUE THREAD

**Issue by WantToLearnJapanese** [twpayne/chezmoi#3369]
## Is your feature request related to a problem? Please describe.
For example on macOS, there is a defaults command which can be used for extracting user-defined shortcuts.
Currently, I need to make intermediate files and script to work with them.

## Describe the solution you'd like
Anyway, the configs from defaults (for macOS) should be extracted as a file.
I suggest the feature comparing a source file against a target file which resides in defaults. (which must be also user-defined by a script)

## Describe alternatives you've considered
As I wrote above, it can be done with intermidate files and scripts.
But it looks not clean and may need two runs of 'chezmoi apply'.

**Comment by halostatue** [comment]
It's worth noting that both macOS `defaults` and the Windows registry store an *immense* amount of data, not all of it suitable for comparison or even quick summarization, so updating either of these *should* require a script.

I understand that what you’re wanting to do is along the lines of `set defaults-x xyz unless defaults-x == xyz`, but treating these data stores as if they were files (even though, on macOS, they mostly are — but well outside the purview of chezmoi) is extremely difficult.

**Comment by twpayne** [comment]
+1 on what @halostatue says. This is not realistic to implement.

> I understand that what you’re wanting to do is along the lines of `set defaults-x xyz unless defaults-x == xyz`

Note that this can be done in a normal `run_` script:

```bash
#!/bin/bash

if [ "$(defaults read com.apple.dock orientation)" != "left" ]; then
    defaults write com.apple.dock.orientation -string left && killall Dock
fi
```

Using the programming features of your scripting language, you can make this loop over the values that you are interested in.
