### ISSUE TITLE
Permission denied when modifying hidden files on Windows

### ISSUE THREAD

**Issue by awebeer256** [twpayne/chezmoi#3392]
## Describe the bug

On Windows, when chezmoi tries to overwrite a hidden file in the destination directory, it fails with a permission denied error.

## To reproduce

1. Create a file `foo` in the destination directory, with some contents.
2. Run `chezmoi add foo`
3. In Windows Explorer in the destination directory, right-click `foo` => "Properties" => check the box, "Hidden" => OK
4. Edit `foo` in the source directory.
5. Run `chezmoi apply foo`

## Expected behavior
`foo` in the destination directory has its contents replaced with the contents of `foo` in the source directory. `foo` in the destination directory also retains its hidden status: if it was hidden before, the new version is also hidden.

On a related note, I might make another Issue for this feature request:
If the system is Windows and a certain flag is set in chezmoi's configuration, then when chezmoi creates a new file (not replaces one) that starts with a period in the destination directory, it is set to hidden automatically.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose apply foo
diff --git a/foo b/foo
index 63d8dbd40c23542e740659a7168a0ce3138ea748..2e65efe2a145dda7ee51d1741299f848e5bf752e 100666
--- a/foo
+++ b/foo
@@ -1 +1 @@
-bar
\ No newline at end of file
+baz
\ No newline at end of file
chezmoi: open <destination>/foo: Access is denied.
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.42.1, commit 0b38793c15f3fe4785a58b6df9796d1a6cf8c79d, built at 2023-11-29T09:43:39Z, built by goreleaser
ok        latest-version              v2.42.1
ok        os-arch                     windows/amd64
ok        systeminfo                  Microsoft Windows 10 Pro (10.0.19045 N/A Build 19045)
ok        go-version                  go1.21.4 (gc)
ok        executable                  C:/ProgramData/chocolatey/lib/chezmoi/tools/chezmoi.exe
ok        config-file                 no config file found
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        cd-command                  found C:/WINDOWS/system32/cmd.exe
ok        cd-args                     'C:\\WINDOWS\\system32\\cmd.exe'
info      diff-command                not set
ok        edit-command                found C:/WINDOWS/system32/notepad.exe
ok        edit-args                   'C:\\WINDOWS\\system32\\notepad.exe'
ok        git-command                 found C:/Program Files/Git/cmd/git.exe, version 2.43.0
warning   merge-command               vimdiff not found in $PATH
ok        shell-command               found C:/WINDOWS/system32/cmd.exe
ok        shell-args                  'C:\\WINDOWS\\system32\\cmd.exe'
info      age-command                 age not found in $PATH
info      gpg-command                 gpg not found in $PATH
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

The use case is managing `~/.bashrc` and other literal dot files on Windows, for use with Git For Windows/MINGW64. I don't want to see them cluttering up my home directory.

If the destination file is `<destination>/bar/baz`, and `bar` is hidden but `baz` is not, then this bug does not occur.

**Comment by halostatue** [comment]
This looks possible to resolve, but I’m not sure that this is advisable to "automatically" resolve within Chezmoi. If you know which files you want to mark hidden, then you should be able to have a `run_before` script that *unhides* those files (if they exist) and a `run_after` script that *hides* those files.

I think that having chezmoi manage this directly would require a `hidden` attribute (like `private`, etc.) but such a thing would only work on Windows.

https://freshman.tech/snippets/go/detect-hidden-file/

If there is a bug, I think that the problem is that the *error* reported is less than useful. Otherwise, I think that this is a feature request.

**Comment by awebeer256** [comment]
> I think that having chezmoi manage this directly would require a hidden attribute (like private, etc.) but such a thing would only work on Windows.

Agreed, but I'm not asking for that.

> If there is a bug, I think that the problem is that the error reported is less than useful. Otherwise, I think that this is a feature request.

The problem is that chezmoi handles hidden files differently depending on what kind of system it's running on, because what it means for a file to be hidden is very different on Windows than on UNIX-like systems. The current behaviour on Windows is like if on *NIX, chezmoi was unable to manage any files that started with a period. That would *definitely* be a bug, so this is too.

The presumably easier to implement, but less desirable, fix is for chezmoi to successfully replace the file but clobber the hidden flag so the file is no longer hidden. The harder but better fix is for chezmoi to also check whether the hidden flag is set just before it overwrites the file, and if it was, then set it again after the overwrite.

**Comment by twpayne** [comment]
As @halostatue says, hidden files on Windows are nothing like files whose name begins with a `.` on UNIX systems.

It would be a huge amount of effort for chezmoi to support hidden files, for a very marginal gain. Please use the `run_before_`/`run_after_` script workaround.

**Comment by awebeer256** [comment]
@halostatue You've completely missed the point.

- *nix has a concept that is generally referred to as, "hidden files."
- Windows has a concept that is generally referred to as, "hidden files."
- People use the same name because the user-facing behaviour is similar.
- Therefore it is reasonable to request that a piece of cross-platform file synchronization software treat them similarly.

Instead of addressing that argument, you spent a huge number of words trying to explain to me that the underlying technical implementation of these concepts is very different, even though *I said that myself in my previous comment.*

---

> It would be a huge amount of effort for chezmoi to support hidden files, for a very marginal gain. Please use the `run_before_`/`run_after_` script workaround.

This, meanwhile, is a totally reasonable response. Thank you for your consideration @twpayne.

---

For anyone else reading this later, here's what I went with:

`run_before_unhidedot.bat`:
```batch
FOR %%F IN (.bashrc file2 file3) DO ATTRIB -H %%F
```

`run_after_hidedot.bat`:
```batch
FOR %%F IN (.bashrc file2 file3 .bashrc.d dir5 dir6) DO ATTRIB +H %%F
```
And then make sure chezmoi ignores `unhidedot.bat` and `hidedot.bat` everywhere except on Windows.

Directories are not in the unhide script because again, they still work if they're hidden, but they are still in the hide script because they will be created not-hidden.
