### ISSUE TITLE
Support symlinks in mackup command

### ISSUE THREAD

**Issue by ronlut** [twpayne/chezmoi#3406]
## Is your feature request related to a problem? Please describe.

[Continuing my chezmoi explorations](https://github.com/twpayne/chezmoi/pull/3400) with regards to using mackup, I stumbled upon another problem:
If one of the "configuration files" is a symlink pointing to a directory, or a file in a path that contains symlink, the command fails.
A good example of it would be the `iterm2` configuration files: [link](https://github.com/lra/mackup/blob/master/mackup/applications/iterm2.cfg):
```
[application]
name = iTerm2

[configuration_files]
Library/Preferences/com.googlecode.iterm2.plist

[xdg_configuration_files]
iterm2/AppSupport/DynamicProfiles
```

Part of the `iterm2/AppSupport/DynamicProfiles` file (directory) is a symlink, specifically the `AppSupport`:
```
~ ❯ ls -an ~/.config/iterm2/                                          
total 0
drwxr-xr-x   3 501  20   96 Jul 16  2021 .
drwxr-xr-x  10 501  20  320 Dec  8 23:42 ..
lrwxr-xr-x   1 501  20   46 Jul 16  2021 AppSupport -> /Users/<NAME>/Library/Application Support/iTerm2
```

Hence adding this won't work.

## Describe the solution you'd like

[I know chezmoi does't follow symlinks if it's not the last part of the path](https://github.com/twpayne/chezmoi/issues/2758). BUT I think in mackup's case it would make sense to evaluate symlinks on each of the `configuration_files` before calling the `add` functionality.
Reason being is that if I would want to add those files with chezmoi natively, I would just run `chezmoi add ~/.config/iterm2/Library/Application Support/iTerm2` and it would work.
Because mackup is basically the source for the `add` command, it might solve it pretty easily.

If that is an accepted solution, I will open a PR shortly to solve it :)
Thanks!

**Comment by halostatue** [comment]
I’m not sure what you mean by "mackup is the source for the `add` command", because the chezmoi mackup support is *mostly* unsupported and undocumented, and I’m not sure that adding more explicit support for its idiosyncratic configuration mechanism would be a good thing. Especially as mackup support is *only* enabled for macOS, although it appears that mackup has some Linux support now.

I’m not seeing anything that suggests that `~/.config/iterm2/AppSupport/DynamicProfiles` should be a link to `~/Library/Application Support/iTerm2/DynamicProfiles` or something like that.

**Comment by twpayne** [comment]
> Part of the `iterm2/AppSupport/DynamicProfiles` file (directory) is a symlink, specifically the `AppSupport`:
> 
> ```
> ~ ❯ ls -an ~/.config/iterm2/                                          
> total 0
> drwxr-xr-x   3 501  20   96 Jul 16  2021 .
> drwxr-xr-x  10 501  20  320 Dec  8 23:42 ..
> lrwxr-xr-x   1 501  20   46 Jul 16  2021 AppSupport -> /Users/<NAME>/Library/Application Support/iTerm2
> ```
> 
> Hence adding this won't work.

What do you mean by "adding this won't work"? chezmoi supports symlinks and running

    chezmoi add ~/.config/iterm2

results in `private_dot_config/iterm2/symlink_AppSupport` being added to the source state with the contents `/Users/<NAME>/Library/Application Support/iTerm2`.

What different result would you want?

**Comment by ronlut** [comment]
Maybe it wasn't clear enough, or I am missing something, I will try to explain a bit more:
iterm [as an example](https://iterm2.com/documentation-dynamic-profiles.html) stores **files** in `/Users/<NAME>/.config/iterm2/AppSupport/DynamicProfiles` which is actually, after symlink evaluation is `/Users/<NAME>/Library/Application\ Support/iTerm2/DynamicProfiles`.
What's important to backup here is not the symlink itself, but the files inside the target directory.
I am getting an error when trying to do that:
```
~ ❯ chezmoi add ~/.config/iterm2/AppSupport/DynamicProfiles            20:38:15
chezmoi: lstat /Users/<NAME>/.local/share/chezmoi/dot_config/iterm2/symlink_AppSupport/DynamicProfiles: not a directory
```

And I don't get an error with: `chezmoi add /Users/<NAME>/Library/Application\ Support/iTerm2/DynamicProfiles`

For example if a file named "a.txt" is in that directory, it will be backed up with method 2 but not with method 1.

**Comment by ronlut** [comment]
What I am suggesting is just doing `file path.EvalSymlinks` on each path passed to the `add` logic from mackup command (or in general actually).

**Comment by halostatue** [comment]
I’m not sure that would *quite* do what you really want, as to me you would want `chemzoi add ~/.config/iterm2/AppSupport/DynamicProfiles` *actually* add:

- `private_dot_config/iterm2/symlink_AppSupport`
- `private_Library/Application Support/iTerm2/DynamicProfiles/*`

That feels like too much magic to be a default behaviour. At the same time, I think that the `lstat` error provided is not useful, especially as it happens even with `--follow` enabled (where I would expect it to traverse through but only add `private_dot_config/iterm2/AppSupport/DynamicProfiles/*`).

I think that we have two issues:

1. chezmoi cannot pass through a directory symlink at all during `add` resolution, even with `--follow`. This is surprising and I think that it's a bug.
2. chezmoi should not magic its way into doing the right thing, but with a two step command the right thing should be *possible*, although it may require new flags that I don't have good names for:

   ```
   chezmoi add ~/.config/iterm2/AppSupport
   chezmoi add ~/.config/iterm2/AppSupport/DynamicProfiles --resolve-to-real-files
   ```

**Comment by ronlut** [comment]
I agree it's a bug, as I don't have enough history with chezmoi I thought it's expected.

Regarding the expected behaviour, I am not sure I agree:
The symlink is not something I try to backup at all. It's created by iterm and I'm OK with not backing it up, all I am interested in (and expect to work) is add `private_dot_config/iterm2/AppSupport/DynamicProfiles/* `

I agree there's an inherent problem of backing up this path and hoping it will apply successfully on another machine where iterm not necessarily set up the same symlink for `AppSupport`, but that is to handle by chezmoi user specifically for his use case (for example, having it apply to a different location depending on os).

What I am trying to say is the real value I see in the mackup integration is having the real backup paths available in a single command, hence I suggested to just `evalsymlinks` each mackup path before `add`ing.

I am OK with closing this issue without any action, it's not that important, just wanted to explain my thoughts 🤓
