### ISSUE TITLE
wish: install completions so they work out of the box

### ISSUE THREAD

**Issue by markstos** [twpayne/chezmoi#341]
As part of the packaging process, write the bash completions to:

    /etc/bash_completion.d/chezmoi

And Fish completions to:

   /etc/fish/completions/chezmoi

(I'm not certain about the correct zsh target, but I presume its similar). 

These are sensible paths at least on Debian and Ubuntu. I'm not sure about other Linux distributions or OS X. 

Perhaps this could be added to the `.deb` file as a first step, and other release targets could be supported in later patches.

**Comment by twpayne** [comment]
So this should now be implemented for `bash` and `zsh` with the `.deb` and `.rpm` packages for Linux in #343, but there are a few more places where this should be added. I'll keep this issue open for now, even though I hope that your immediate needs are met.
