### ISSUE TITLE
`run_onchange_` scripts are not re-executed after `chezmoi state delete-bucket --bucket=scriptState`

### ISSUE THREAD

**Issue by tummetott** [twpayne/chezmoi#3421]
## Describe the bug

The docs state:

#### Clear the state of all `run_onchange_` and `run_once_` scripts

chezmoi stores whether and when `run_onchange_` and `run_once_` scripts have been run in the `scriptState` bucket of its persistent state. To clear the s-tate, run:
```
$ chezmoi state delete-bucket --bucket=scriptState
```

However when running `chezmoi state delete-bucket --bucket=scriptState`, only `run_once_` script are re-executed but no `run_onchange` scripts.

## To reproduce

1. Create `run_onchange_after_test.tmpl` under `~/.local/share/chezmoi` with the following content:

```bash
#!/usr/bin/env bash

echo "hello"
```
2. Run `chezmoi apply` to run the scipt
3. Run `chezmoi state delete-bucket --bucket=scriptState` to delete the `scriptState`
4. Run `chezmoi init && chezmoi apply` again

--> The `echo` statement is not printed in step 4

## Expected behavior

The `run_onchange_` script should be run in step 4 

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose apply
```
--> no output

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```
Result:
```
RESULT    CHECK                       MESSAGE
ok        version                     v2.42.3, commit 43a4f5790ef1b709de881d36afb0a61745efa34f, built at 2023-12-16T23:26:32Z, built by goreleaser
ok        latest-version              v2.42.3
ok        os-arch                     darwin/arm64
ok        uname                       Darwin jonass-Virtual-Machine.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:19 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_VMAPPLE arm64
ok        go-version                  go1.21.5 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 no config file found
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /usr/bin/vi
ok        edit-args                   /usr/bin/vi
ok        git-command                 found /usr/bin/git, version 2.39.3
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
info      gpg-command                 gpg not found in $PATH
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

`run_once_` scripts are re-executed, but not `run_onchange_`

**Comment by twpayne** [comment]
Thanks for spotting this. This was actually a bug in the documentation. To clear the state of `run_onchange_` scripts you have to run:

```console
$ chezmoi state delete-bucket --bucket=entryState
```

#3423 updates the documentation.

**Comment by tummetott** [comment]
Thank you for the quick response. This is by far the best project I've discovered in a while.

**Comment by tummetott** [comment]
Is it somehow possible to call

```chezmoi state delete-bucket --bucket=entryState```

from inside a `run_` script?
If I do so I get the following error:
```
chezmoi: timeout obtaining persistent state lock, is another instance of chezmoi running?
```

My use case is the following: I have two scripts: `run_onchange_1` and `run_once_2`. When I boostrap a new machine, both scipts are run in alphabetical order. In the event of a failure during the execution of the first script, which may occur due to the need for a system reboot, it remains important that both scripts complete their execution. Instead of abruptly terminating the first script with an `exit 1` command, which would prevent the second script from running, I have implemented error handling to gracefully capture the error and allow the execution to continue. Consequently, both scripts are now marked as completed.
After a system reboot, I'd like to run `chezmoi apply` and **only the first scipt** is run again. So I somehow must clear the run-state of the first script, ideally from inside the first script once the error occurs.

**Comment by twpayne** [comment]
> Is it somehow possible to call
> 
> `chezmoi state delete-bucket --bucket=entryState`
> 
> from inside a `run_` script?

No. chezmoi stores its persistent state in a database that is locked while chezmoi is running. This is to ensure, as far as possible, that `run_once_` scripts are run exactly once. Imagine having `run_once_a` and `run_once_b`, running `chezmoi apply`, and then interrupting chezmoi after `run_once_a` has finished but before `run_once_b` has finished. The use of the database means that chezmoi will record that `run_once_a` has been run the next time you run `chezmoi apply`. Due to limitations of the database used (BoltDB), only one writer is allowed at a time, so scripts cannot modify the database while chezmoi is running.
