### ISSUE TITLE
rbw: pass additional arguments

### ISSUE THREAD

**Issue by shumvgolove** [twpayne/chezmoi#3426]
## Is your feature request related to a problem? Please describe.

Currently, `rbw` template function can not be extended with additional arguments. In my case, the critical piece is `--folder` arg: my password entries use folder structure and sometimes contain the same name (`foo` in `bar` folder and `foo` in `baz` folder), so I can't distinguish them without using an additional argument, making `rbw` template function useless :^(

## Describe the solution you'd like

Either:
- Pass additional arguments to `rbw` function
- Allow specifying optional folder argument like: `{{ (rbw "my-entry" "my-folder") }}` / `{{ (rbwFields "my-entry" "my-folder") }}`

## Describe alternatives you've considered

Alternatively, we can add a new template function like in https://github.com/twpayne/chezmoi/issues/416.

## Additional context

Thanks for your work on this awesome project!

**Comment by twpayne** [comment]
Makes sense. Implemented in #3427.

**Comment by shumvgolove** [comment]
Thank you!
