### ISSUE TITLE
Switching to chezmoi feels confusing

### ISSUE THREAD

**Issue by dariusgm** [twpayne/chezmoi#3435]
## What exactly are you trying to do?

I have a bunch of script that I want to migrate now for (better) maintenance.
You can find them [here](https://github.com/dariusgm/install).

Describe in as much detail as possible.

I get consides by the doc and by the provided examples and haven't found a way to figure out what to do.

## What have you tried so far?
I installed chezmoi via the install shell script and it placed it under ./bin/chezmoi what is unexpected, as I have to write out the full name each time.
I also installed it via snap (working on ubuntu LTS 22.04) and at least now its global available.
After I started with my first dot files, I wanted to continue with package management.

As you may see in my repository that I shared via the link, I have same basic installation and for specific applications an additional file that I execute when needed.

Describe what you have tried so far.

## Where else have you checked for solutions?

* [/] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [/] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [/] ChatGPT 3.5 Prompt

## Additional context

I am missing a full but yet simple example for ubuntu on how a migration would look like.
For example here: https://www.chezmoi.io/user-guide/advanced/install-packages-declaratively/ their is no ubuntu example provided. Also I am not familar with go and the templating language that is used here.

As far as I understand, dependency management may be represented by having several run_before callbacks. But the location of them (~/.local/share/chezmoi) or (~/.local/share/chezmoi/scripts) is not clear to me.

The examples I found on github also use different pattern.

Extending the getting-started docs with package installation best-practice would really help me a lot, maybe also for several operating systems in the next step, as I use win and ubuntu for development.

I also not understand the state management. When a script is evaluated once and how to enforce it (for "developing" of the templates)

Would love to get some links with hints or create a PR when I get it up and running.

Have a great new year
Darius

**Comment by twpayne** [comment]
chezmoi is a dotfile manager and it's not the responsibility of chezmoi's documentation to teach people how to use their systems. That said...

> I installed chezmoi via the install shell script and it placed it under ./bin/chezmoi what is unexpected, as I have to write out the full name each time.

Read up on the `PATH` environment variable. You can also use the `-b` option to the install script to chose a different location, or install chezmoi with one of your system's package managers.

> I am missing a full but yet simple example for ubuntu on how a migration would look like.
> For example here: https://www.chezmoi.io/user-guide/advanced/install-packages-declaratively/ their is no ubuntu example provided. Also I am not familar with go and the templating language that is used here.

chezmoi has a dedicated [guide to templating](https://www.chezmoi.io/user-guide/templating/). For a Ubuntu example, you can look at [my personal Ubuntu package installation script](https://github.com/twpayne/dotfiles/blob/76eccf5babe2efeac55f07fa7f96bb29f8859e2f/home/.chezmoiscripts/linux/run_onchange_before_install-packages.sh.tmpl).

> I also not understand the state management. When a script is evaluated once and how to enforce it (for "developing" of the templates)

Read the dedicated [guide to scripting](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/).
