### ISSUE TITLE
SSL cert expired? curl get.chezmoi.io fails.

### ISSUE THREAD

**Issue by HelloGrayson** [twpayne/chezmoi#3453]
Attempting to test my dotfiles on a new machine, I get the following error:

```
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply HelloGrayson
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Upon further inspection, it looks like the SSL cert is set to expire tomorrow:

![image](https://github.com/twpayne/chezmoi/assets/263587/27c2467c-6c7c-4d19-9ce9-cb94204cda2b)

Let me know how I can help.

**Comment by HelloGrayson** [comment]
As a temporary workaround, folks can pass `-k` to curl to ignore SSL errors:

```
$ sh -c "$(curl -kfsLS get.chezmoi.io)" -- init --apply HelloGrayson
```

**Comment by twpayne** [comment]
get.chezmoi.io is managed with GitHub Pages which is also responsible for SSL certificates.

Also, it looks like your clock is at least 24 hours wrong. It's January 4, not January 3.

**Comment by HelloGrayson** [comment]
Got it. I'm running from a virtual machine snapshot made yesterday - that explains it.

**Comment by HelloGrayson** [comment]
I was able to fix the issue on my `Fedora Linux 39 (Silverblue)` machine via:

```
$ systemctl start systemd-timesyncd
```

Then, even in when running an older restored VM snapshot, the time is automatically corrected.
