### ISSUE TITLE
Is it possible to provide the ability to enable scanning at will

### ISSUE THREAD

**Issue by akimdi** [twpayne/chezmoi#3479]
Thank you for making such a quality product. After a recent update, chezmoi has become slower. I think this is because it scans files using gitleaks. Is it possible to provide the ability to enable scanning at will? By default, chezmoi will scan, but anyone can disable this behavior.

https://github.com/twpayne/chezmoi/commit/7d915c0ac1fef0b7ff0049302a3fac1d17b26c51

**Comment by twpayne** [comment]
Could you be more specific about "chezmoi has become slower"?

The secret scanning should only affect `chezmoi add` (and the undocumented `chezmoi mackup add`).

You can disable secret scanning by setting the `add.secrets` configuration variable to `ignore` in your configuration file.

**Comment by halostatue** [comment]
The gitleaks scanning should *only* happen when doing `chezmoi add`, and only if `add.secret` is `warning` (the default) or `error`. You can disable secret scanning on add by setting `add.secret` to `ignore` (`chezmoi add --secret ignore …`).

What part of chezmoi is slower for you?

**Comment by twpayne** [comment]
Please re-open this issue when you have more information. Closing for now.
