### ISSUE TITLE
Minor Inconsistency in Documentation: age configuration variables

### ISSUE THREAD

**Issue by drwicid** [twpayne/chezmoi#3488]
In the documentation for configuration variables, age `recipientFile` and `recipientFiles` are missing an `s`.

https://github.com/twpayne/chezmoi/blob/85983f06931e86b157a877287a82d8b6faca8eea/assets/chezmoi.io/docs/reference/configuration-file/variables.md.yaml#L100-L104

Variable definition in code, is `recipientsFile` and `recipientsFiles` 
https://github.com/twpayne/chezmoi/blob/85983f06931e86b157a877287a82d8b6faca8eea/internal/chezmoi/ageencryption.go#L30-L31

**Comment by twpayne** [comment]
Thank you very much for spotting this. Fixed with #3492.
