### ISSUE TITLE
The edit-config-template command sometimes tries to edit the wrong file

### ISSUE THREAD

**Issue by paltherr** [twpayne/chezmoi#3501]
## Describe the bug

If there is no config template in the source directory, the `edit-config-template` command edits a file whose name is based on the current config file. If the current config file is specified with the `--config` option and/or its format is specified with the `--config-format` option, then it may lead the `edit-config-template` command to edit the wrong file.

## To reproduce

The following assumes that there is initially no `/tmp/chezmoi` file or directory.

```
% HOME=/tmp/chezmoi EDITOR=echo chezmoi edit-config-template                    
/tmp/chezmoi/.local/share/chezmoi/.chezmoi.toml.tmpl
chezmoi: warning: /bin/echo /tmp/chezmoi/.local/share/chezmoi/.chezmoi.toml.tmpl: returned in less than 1s

% HOME=/tmp/chezmoi EDITOR=echo chezmoi --config config.yaml edit-config-template
/tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl
chezmoi: warning: /bin/echo /tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl: returned in less than 1s

% HOME=/tmp/chezmoi EDITOR=echo chezmoi --config-format yaml edit-config-template 
/tmp/chezmoi/.local/share/chezmoi/.chezmoi.toml.tmpl
chezmoi: warning: /bin/echo /tmp/chezmoi/.local/share/chezmoi/.chezmoi.toml.tmpl: returned in less than 1s

% HOME=/tmp/chezmoi EDITOR=echo chezmoi --config config.yaml --config-format json edit-config-template
/tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl
chezmoi: warning: /bin/echo /tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl: returned in less than 1s
```

## Expected behavior

The 1st command edits the right file.
The 2nd command should edit the file .chezmoi.yaml.tmpl
The 3rd command should edit the file .chezmoi.yaml.tmpl
The 4th command should edit the file .chezmoi.json.tmpl

## Additional context

The problem is [here](https://github.com/twpayne/chezmoi/blob/9c273ebf76f8d7bc6be06d61210e43fdd11fbd4e/internal/cmd/editconfigtemplatecmd.go#L42). This line should instead use `chezmoi.Prefix` and the format extension of the following format:

```
var configFormat chezmoi.Format
if c.configFormat == "" {
	configFormat, _ = chezmoi.FormatFromAbsPath(c.configFileAbsPath)
} else {
	configFormat = c.configFormat.Format()
}
```

**Comment by twpayne** [comment]
Drive-by notes for later:

For testing the 2nd and 3rd commands, I used the following testscript change:

```diff
diff --git a/internal/cmd/testdata/scripts/editconfigtemplate.txtar b/internal/cmd/testdata/scripts/editconfigtemplate.txtar
index 7c705ae3a..c791315c2 100644
--- a/internal/cmd/testdata/scripts/editconfigtemplate.txtar
+++ b/internal/cmd/testdata/scripts/editconfigtemplate.txtar
@@ -22,6 +22,18 @@ chhome home4/user
 exec chezmoi edit-config-template
 cmp $CHEZMOISOURCEDIR/home/.chezmoi.yaml.tmpl golden/edited-chezmoi.yaml
 
+chhome home5/user
+
+# test chezmoi edit-config-template --config with a non-existent config file
+exec chezmoi --config=config.yaml --config-format=yaml edit-config-template
+cmp $CHEZMOISOURCEDIR/.config.yaml.tmpl golden/edited
+
+chhome home6/user
+
+# test chezmoi edit-config-template --config-format with a non-existent config file
+exec chezmoi --config-format=yaml edit-config-template
+cmp $CHEZMOISOURCEDIR/.config.yaml.tmpl golden/edited
+
 -- golden/edited --
 # edited
 -- golden/edited-chezmoi.yaml --
```

Re

> The 4th command should edit the file .chezmoi.json.tmpl

where the 4th command is:

```
% HOME=/tmp/chezmoi EDITOR=echo chezmoi --config config.yaml --config-format json edit-config-template
/tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl
chezmoi: warning: /bin/echo /tmp/chezmoi/.local/share/chezmoi/.config.yaml.tmpl: returned in less than 1s
```

There's a direct conflict here between `--config` and `--config-format`. In this case, I would suggest the rule that `--config-format` is only used when creating a new config file, i.e. that `--config-file` is ignored in this case (possibly with a warning) and this 4th command should edit `.chezmoi.yaml.tmpl`.

**Comment by paltherr** [comment]
Your first test should not include `--config-format=yaml`, (only [--config=config.yaml](url)).

I agree that for the 4th command the `--config` option should be ignored, i.e., the `--config-format` option supersedes whatever format might be implied by the `--config` option. However, this implies that the edited file should be `.chezmoi.json.tmpl` (json, not yaml).

You should add a 3rd new test:

```
exec chezmoi --config=config.toml --config-format=yaml edit-config-template
cmp $CHEZMOISOURCEDIR/.config.yaml.tmpl golden/edited
```

**Comment by twpayne** [comment]
As this is such an edge case, I'm going to close this as won't fix.
