### ISSUE TITLE
Support arbitrary encryption/decryption tools

### ISSUE THREAD

**Issue by Amolith** [twpayne/chezmoi#3503]
## Is your feature request related to a problem? Please describe.

I run chezmoi mostly-non-interactively with [darkman](https://gitlab.com/WhyNotHugo/darkman/) as part of an automated theme switching workflow. It worked wonderfully with GPG because there's a GUI prompt for the GPG passphrase; the script kicks off in the background and sends me a notification, so when the prompt appears a second later, I know what it's for, enter the PIN, and the rest executes without error. Since switching to age, however, it's much more painful because neither upstream age nor age bundled with chezmoi open that GUI prompt, so the script fails. I have to interactively switch themes from inside a shell because decryption immediately fails when there's no console.

I also can't use the age version bundled with chezmoi because it doesn't integrate with [age-plugin-yubikey](https://github.com/str4d/age-plugin-yubikey/) at all.

## Describe the solution you'd like

I think the _best_ solution would be allowing users to pick whatever encryption/decryption system they prefer; they could just specify the two commands for encryption/decryption with a `$FILEPATH` variable or something that chezmoi fills in before execution.

## Describe alternatives you've considered

Alternatively, adding support for just [rage](https://str4d.xyz/rage), which [does have a GUI prompt](https://github.com/str4d/age-plugin-yubikey/issues/154#issuecomment-1904788310) through `pinentry`, would solve my problem.

**Comment by twpayne** [comment]
> I think the _best_ solution would be allowing users to pick whatever encryption/decryption system they prefer;

This is already supported through the [custom secret manager template functions](https://www.chezmoi.io/user-guide/password-managers/custom/). Is there something missing from this?

**Comment by twpayne** [comment]
> Unless I misunderstand, that would require storing the entire config file in my secret manager, and even then, [templating](https://www.chezmoi.io/user-guide/templating/) wouldn't work, right?

I think you misunderstand. Only secrets need to be stored in your password manager. Have you read https://www.chezmoi.io/user-guide/password-managers/ ?

**Comment by twpayne** [comment]
Ah, my apologies, I was distracted with too many issues at once and misunderstood. My bad.

Right now, chezmoi has the [`output` template function](https://www.chezmoi.io/reference/templates/functions/output/) which should allow you to include output from rage.

chezmoi has an [internal encryption abstraction](https://github.com/twpayne/chezmoi/blob/ecf706d8f60a5a7c71af62683bd076efefcc9211/internal/chezmoi/encryption.go). It should be fairly straightforward to support arbitrary encryption/decryption tools here.

What would you like the interface to look like? Presumably there should be something like:

```
encryption = "custom"
[encryption.custom.encrypt]
    command = "rage"
    args = ["--encrypt"] # made up example, real args would be more complex
[encryption.custom.decrypt]
    command = "rage"
    args = ["--decrypt"] # made up example, real args would be more complex
```

**Comment by twpayne** [comment]
> Maybe it would be good to allow the user to specify where in the command the file path should go?

For this, we can use the same technique of templates as [used in custom diff tools](https://www.chezmoi.io/user-guide/tools/diff/#use-a-custom-diff-tool).

**Comment by twpayne** [comment]
> Alternatively, adding support for just [rage](https://str4d.xyz/rage), which [does have a GUI prompt](https://github.com/str4d/age-plugin-yubikey/issues/154#issuecomment-1904788310) through `pinentry`, would solve my problem.

Thinking more about this, is `rage` a drop-in replacement for `age`? i.e. can you put

```toml
[age]
    command = "rage"
```

in your config file? I haven't tested this.

**Comment by twpayne** [comment]
Thanks for testing! I'll add some tests to check that chezmoi works with `age.command = "rage"` to resolve this issue.
