### ISSUE TITLE
Chezmoi Fails to Detect Git

### ISSUE THREAD

**Issue by tummetott** [twpayne/chezmoi#3510]
## Describe the bug

When using an external source with `type = 'git-repo'`, then `git` is a pre-requisite for chezmoi. Thats why I created a `run_once_before_install-git.tmpl` script to install git for systems that have git not preinstalled (such as on Pi OS Lite):

```bash
#!/usr/bin/env bash

set -euo pipefail

# Git is a dependency for chezmoi. We need it for some external sources,
# therefore it must be installed before they are downloaded.
{{ if and (eq .chezmoi.os "linux") (eq .chezmoi.osRelease.id "debian") }}
if ! command -v git; then
    sudo apt update
    sudo apt -y install git
fi
{{ end }}
```

When I run `chezmoi apply`, git is installed as expected. However, afterward, chezmoi cannot continue cloning the external git repositories and fails with the following error:
```
exec: "git": executable file not found in $PATH
```

Then, when I rerun `chezmoi apply`, git is detected by chezmoi, and the external sources are cloned successfully.

## To reproduce

- Remove git
- Create an external source from type `git-repo`
- Add the provided `run_once_before_install-git.tmpl`
- Run `chezmoi apply`

## Expected behavior

Since git is installed within the `run_before` script BEFORE chezmoi attempts to clone the external git sources, I would expect that chezmoi detects the previously installed git application within this single run of `chezmoi apply`.

## Output of command with the `--verbose` flag

```console
$ chezmoi --verbose apply
exec: "git": executable file not found in $PATH
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.45.0, commit 371703e93f0c54dad81f7cfbea2906ece15a7428, built at 2024-01-13T20:01:02Z, built by goreleaser
ok        latest-version              v2.45.0
ok        os-arch                     linux/arm64 (Debian GNU/Linux 11 (bullseye))
ok        uname                       Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
ok        go-version                  go1.21.6 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-01-22T21:18:54+01:00
error     source-dir                  ~/.local/share/chezmoi is a git working tree (error)
ok        suspicious-entries          no suspicious entries
error     working-tree                ~/.local/share/chezmoi is a git working tree (error)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /usr/bin/zsh
ok        cd-args                     /usr/bin/zsh
info      diff-command                not set
ok        edit-command                found /snap/bin/nvim
ok        edit-args                   /snap/bin/nvim
warning   git-command                 git not found in $PATH
ok        merge-command               found ~/.local/share/scripts/nvimdiff
ok        shell-command               found /usr/bin/zsh
ok        shell-args                  /usr/bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.2.27
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

**Comment by tummetott** [comment]
I'm a bit puzzled as to why this was flagged as `"support"`? I followed the manpage exactly, and the only deviation is that the prerequisite seems to be necessary for external sources rather than template expansion.

- `/usr/bin` is in PATH
- Git is installed within the `run_before_` script to `/user/bin/git`
- The external sources are cloned **after** the `run_before_` scripts

Considering these factors, it seems logical that chezmoi should be able to locate git without any issues. It manages to do so when I run `chezmoi apply` a second time. So, I'm left wondering why it doesn't work on the initial run.

To me, this situation appears to be a bug because the ideal scenario would be to install everything, including prerequisites and dotfiles, with a single command (like `sh -c "$(curl -fsLS get.chezmoi.io/lb)" -- init --apply <username>`)

<img width="716" alt="image" src="https://github.com/twpayne/chezmoi/assets/19708025/b3eccb3d-0feb-4a30-849f-c7a184a9c871">

**Comment by halostatue** [comment]
We need to understand what you are seeing more explicitly before we can declare it as a bug or correct behaviour, therefore it is a `support` request.

**Comment by twpayne** [comment]
OK, this one is interesting. It's a "feature" of Go standard library's [`os/exec.Command`](https://pkg.go.dev/os/exec#Command) function. What's happening it:

1. When chezmoi reads the external file, it creates the `os/exec.Cmd` structure for the git command to be run using `os/exec.Command`.
2. `os/exec.Command` immediately looks for the `git` command, which it doesn't find, as `git` is not yet installed. It then stores that not found error for later.
3. Later, chezmoi runs the `install-git.sh` script, which installs `git`.
4. Later, chezmoi calls `Run()` on the `os/exec.Cmd` it created in step 1. Instead of checking again for the presence of `git` in `$PATH`, Go's standard library returns the not found error it saved at step 2.

I'll have a think about how to fix this.

**Comment by halostatue** [comment]
If chezmoi does a `lookPath` before step 4, does that affect the resolution?

**Comment by twpayne** [comment]
> If chezmoi does a `lookPath` before step 4, does that affect the resolution?

No. The lookup error is cached in the `os/exec.Cmd` struct and is unaffected by other calls to `os/exec.LookPath`. See https://github.com/golang/go/blob/go1.20.6/src/os/exec/exec.go#L418-L429.

**Comment by tummetott** [comment]
Thanks for the fast bugfix. You guys are amazing ! ❤️
