### ISSUE TITLE
Chezmoi wants to overwrite .config symlink

### ISSUE THREAD

**Issue by dgudim** [twpayne/chezmoi#3517]
I moved my config folder to a faster drive and symlinked it back into the home dir and now chezmoi is not happy

When running `chezmoi apply` it wants to overwrite the directory
```
diff --git a/.config b/.config
old mode 100000
new mode 40755
index df5c7ebe0b7ba9ce6b7b05a5c416412dcbfd7bb5..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- a/.config
+++ b/.config
@@ -1 +0,0 @@
-/mnt/fast_storage/FAST_CONFIG
\ No newline at end of file
```

Running `chezmoi diff` produces the following:
```
error: Could not access '/home/kloud/.config/null'
chezmoi: exit status 1
read /home/kloud/.config: is a directory
```

**Comment by twpayne** [comment]
chezmoi is behaving as intended here.

chezmoi [supports symbolic links natively](https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-doesnt-chezmoi-use-symlinks-like-gnu-stow). If you want `~/.config` to be a symbolic link then you have to tell chezmoi, i.e. replace the **directory** `dot_config` in your source directory with the **file** `symlink_dot_config` containing `/mnt/fast_storage/FAST_CONFIG`.

This is probably not what you want, however, as chezmoi only manages file in your home directory. If you move the files to `/mnt/fast_storage/FAST_CONFIG` then the files are no longer in your home directory. There are [some workarounds](https://github.com/twpayne/chezmoi/discussions/2574), however.

**Comment by dgudim** [comment]
Thanks for a quick reply! I ended up bind-mounting the directories in fstab, everything is perfect now

**Comment by twpayne** [comment]
That's a good solution :)

**Comment by dgudim** [comment]
This can be closed then I guess

**Comment by halostatue** [comment]
> Thanks for a quick reply! I ended up bind-mounting the directories in fstab, everything is perfect now

If you’re willing to share what you did, even though it’s chezmoi adjacent, a post in [Show & Tell](https://github.com/twpayne/chezmoi/discussions/categories/show-and-tell) might be useful for others who need to do this for other reasons.

**Comment by dgudim** [comment]
> > Thanks for a quick reply! I ended up bind-mounting the directories in fstab, everything is perfect now
> 
> If you’re willing to share what you did, even though it’s chezmoi adjacent, a post in [Show & Tell](https://github.com/twpayne/chezmoi/discussions/categories/show-and-tell) might be useful for others who need to do this for other reasons.

Done :) https://github.com/twpayne/chezmoi/discussions/3520
