### ISSUE TITLE
Chezmoi diff sets .Target wrong if the target dir does not exist

### ISSUE THREAD

**Issue by dgudim** [twpayne/chezmoi#3548]
## Describe the bug

When running `chezmoi diff` when the parent directory of the config does not exist leads `.Target` to be set to the directory 

## To reproduce

1. Create a folder inside chezmoi repo and put some file into it
```
e.g: dot_config/test123/file.txt
```
2. Set your diff to some custom program
```
[diff]
    command = "delta"
    exclude = ["scripts"]
    args = ["--pager=0", "{{ .Destination }}", "{{ .Target }}"]
```
3. Run `chezmoi diff`

> [!NOTE]
> Replacing delta with echo prints the following:
> ```
> /dev/null /tmp/chezmoi-diff2667899282/.config/test123
> ```

## Expected behavior

`.Target` is set to the file, not folder

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

RESULT    CHECK                       MESSAGE
ok        version                     v2.46.0, commit 06c31fa0c5fb5858d577d8508590de25b5d054b7-dirty, built at 2024-01-26T07:45:16Z
ok        latest-version              v2.46.0
ok        os-arch                     linux/amd64 (EndeavourOS)
ok        uname                       Linux kloud-xps13 6.7.3-arch1-2.1 #1 SMP PREEMPT_DYNAMIC Sun, 04 Feb 2024 20:10:51 +0000 x86_64 GNU/Linux
ok        go-version                  go1.21.6 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-02-09T21:01:52+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/bash
ok        cd-args                     /bin/bash
ok        diff-command                found /usr/bin/delta
ok        edit-command                found /usr/bin/nano
ok        edit-args                   /usr/bin/nano
ok        git-command                 found /usr/bin/git, version 2.43.0
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/bash
ok        shell-args                  /bin/bash
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.4.4
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
ok        keepassxc-command           found /usr/bin/keepassxc-cli, version 2.7.6
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set

</details>

**Comment by twpayne** [comment]
chezmoi is working as intended here. As the directory does not exist, the diff includes both the directory to be created and the file to be created.

Using the example you give, the output of `chezmoi diff` is:

```diff
diff --git a/.config/test123 b/.config/test123
new file mode 40755
index 0000000000000000000000000000000000000000..e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
--- /dev/null
+++ b/.config/test123
diff --git a/.config/test123/file.txt b/.config/test123/file.txt
new file mode 100644
index 0000000000000000000000000000000000000000..e445c490ff0389e63b7fe51fbc4e4ba27c03a997
--- /dev/null
+++ b/.config/test123/file.txt
@@ -0,0 +1 @@
+# contents of .config/test123/file.txt
```

Notice the new file mode of `40755` for the new `.config/test123` directory.

I suspect that in your case, `delta` is not able to handle the directory, and is giving an error.

The work-around is to exclude directories from the diff, which you can do by adding `dirs` to `diff.exclude`:

```toml
[diff]
    command = "delta"
    exclude = ["dirs", "scripts"]
    args = ["--pager=0", "{{ .Destination }}", "{{ .Target }}"]
```

**Comment by dgudim** [comment]
Ah, I see, skill issue on my part, didn't rtfm properly. Many thanks, it works. ;)
