### ISSUE TITLE
Explore apple/pkl support

### ISSUE THREAD

**Issue by bradenhilton** [twpayne/chezmoi#3556]
https://pkl-lang.org/ • [Integration with Go](https://pkl-lang.org/go/current/index.html) • https://github.com/apple/pkl • https://github.com/apple/pkl-go-examples

I suspect this will inevitably come up as/when it grows in popularity.

Some ideas off the top of my head:

- Using pkl for `.chezmoi*.$FORMAT` files
- Offering pkl's generation functionality and/or possibly pkl unmarshalling as template functions, e.g.:
    ```
    {{ toPklJson "config.pkl" }}
    {{ fromPkl "config.pkl" | toJson }} etc.
    ```
    so that config files can be stored in the source state as `.pkl` files and benefit from pkl's validation/error checking, while also being rendered in the appropriate format in the target state

**Comment by halostatue** [comment]
If it already had support for TS/JS and Elixir, I would be using it for a current work project, despite it being so new to the rest of the world.

One thing to be aware of *about* pkl is that it is a Turing-complete language, so it is not a *perfect* fit for how chezmoi sees its configuration files. But it is *very* exciting (IMO).

**Comment by twpayne** [comment]
I'm not sure if this is the right fit for chezmoi.

Pickle looks fantastic for complex configuration needs, as does [CUE](https://cuelang.org/), which solves a similar problem and a bunch of awesome Gophers work on. However, chezmoi's configuration is pretty simple and user-facing so maybe the current JSON/TOML/YAML config options are enough.

I would definitely support adding Pickle template functions, for example the proposed `toPklJson` and `fromPkl`, but I would like to hear support from users with problems that can only be solved by using Pickle before adding this.

**Comment by twpayne** [comment]
Let's wait for reported use cases for Pkl support. For now, I'll close this as "not planned".
