### ISSUE TITLE
Some variables from .chezmoi.config are still inaccessible in templates

### ISSUE THREAD

**Issue by juliuswz** [twpayne/chezmoi#3582]
## Describe the bug
After digging into #2940, #2942, and #2943, I am still encountering issues with the `.chezmoi.config` template variables being inaccessible.

It seems that not all variables are accessible, such as `identity` from `age`.

## To reproduce
`.chezmoi.toml.tmpl`:
```go
{{- $identity := promptStringOnce . ".chezmoi.config.age.identity" "Encryption key path (age)" -}}

encryption = "age"

[age]
identity = {{ $identity | quote }}
symmetric = true
```
`chezmoi init` output:

```
chezmoi: template: chezmoi.toml:11:17: executing "chezmoi.toml" at <promptStringOnce . ".chezmoi.config.age.identity" "Encryption key path (age)">: error calling promptStringOnce: empty path element at index 0
```
The error occurs even if I pre-populate `~/.config/chezmoi/chezmoi.toml`:

```toml
encryption = "age"

[age]
identity = "~/some/path"
symmetric = true
```
## Expected behavior

```shell
$ chezmoi execute-template '{{ .chezmoi.config.age.identity }}'
~/some/path

```

## Additional context

Even the `chezmoi data` command does not return the values:

```json
"age": {
        "args": null,
        "command": "age",
        "identities": null,
        "identity": {},
        "passphrase": false,
        "recipient": "",
        "recipients": null,
        "recipientsFile": {},
        "recipientsFiles": null,
        "suffix": ".age",
        "symmetric": true,
        "useBuiltin": false
      }
```

```shell
$ chezmoi --version 
chezmoi version v2.46.1, built at 2024-02-12T09:19:56Z
```

**Comment by twpayne** [comment]
Re:

    {{- $identity := promptStringOnce . ".chezmoi.config.age.identity" "Encryption key path (age)" -}}

I think this should be

    {{- $identity := promptStringOnce . "chezmoi.config.age.identity" "Encryption key path (age)" -}}

i.e. remove the leading `.`. The second argument to `promptStringOnce` is a path to a field in an object, not a template expression.

**Comment by twpayne** [comment]
Sorry, there is also a bug in chezmoi. It is the same bug as #3593.
