### ISSUE TITLE
No "CHEZMOI_" env vars visible to plugins

### ISSUE THREAD

**Issue by detly** [twpayne/chezmoi#3606]
A chezmoi plugin ie. a binary or script named `chezmoi-whatever`, cannot see any of the `CHEZMOI_` prefixed environment variables available in a `chezmoi cd` session.

For context, a remark on [this discussion](https://github.com/twpayne/chezmoi/discussions/3550) mentioned:

> > Oh, as a side note — the docs aren't super clear on what environment variables a plugin will see. Are they the same as for hooks and scripts? Is there a way to get the source and target directory without hard-coding?
>
> To see what environment variables are set, the easiest way is to run:
>     $ chezmoi cd
>     $ set | grep ^CHEZMOI_

Maybe I misunderstood, in which case, you don't need to consider this a feature request — it was just a surprise. The only information I need is the source directory, which I can get from `chezmoi source-dir`.

## To reproduce

Create this script as `chezmoi-getenv`:

```bash
#!/bin/sh
set | grep '^CHEZMOI_'
```

Make it executable: `chmod a+x chezmoi-getenv`

Move it or create a link to it in your `PATH`.

Run `chezmoi-getenv` and see:

```text
$ chezmoi getenv
chezmoi: exit status 1
```

(The exit status is 1 because `grep` fails to find anything.)

If instead I run `chezmoi cd` and then `chezmoi-getenv` (note the `-`, I'm running the script itself, not the plugin), I see:

```text
$ chezmoi cd
$ chezmoi-getenv
CHEZMOI_ARCH='amd64'
CHEZMOI_ARGS='/snap/chezmoi/845/chezmoi cd'
CHEZMOI_CACHE_DIR='/home/jason/.cache/chezmoi'
CHEZMOI_COMMAND='cd'
```

...and many more. And the script exits successfully.

Even running `chezmoi cd` and then `chezmoi getenv` (no `-` this time), I see none of the `CHEZMOI_` environment variables, suggesting that the environment is actually scrubbed of these when running plugins.
 
## Expected behavior

All the `CHEZMOI_*` environment variables are printed and the script exits successfully.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.47.0, commit 39bd915f446068862cc3064edb6dbeee795785ca, built at 2024-02-25T20:56:37Z, built by goreleaser
ok        latest-version              v2.47.0
ok        os-arch                     linux/amd64 (Ubuntu 23.10 (Mantic Minotaur))
ok        uname                       Linux gary 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version                  go1.22.0 (gc)
ok        executable                  /snap/chezmoi/845/chezmoi
ok        upgrade-method              snap-refresh
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-02-05T16:48:15+08:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       002
ok        cd-command                  found /usr/bin/zsh
ok        cd-args                     /usr/bin/zsh
info      diff-command                not set
ok        edit-command                found /snap/bin/micro
ok        edit-args                   /snap/bin/micro
ok        git-command                 found /usr/bin/git, version 2.43.2
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /usr/bin/zsh
ok        shell-args                  /usr/bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.2.40
info      pinentry-command            not set
info      1password-command           op not found in $PATH
ok        bitwarden-command           found /snap/bin/bw, version 2024.2.0
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

I installed chezmoi via Snap, so I suppose the sandboxing could be affecting it?

**Comment by twpayne** [comment]
Ah, this is an oversight. The environment variables are not set for plugins at the moment.
