### ISSUE TITLE
get.chezmoi.io still returns old install script

### ISSUE THREAD

**Issue by ErrrorMaxx** [twpayne/chezmoi#3628]
## Describe the bug

`get.chezmoi.io` still returns old install script despite https://github.com/twpayne/chezmoi/commit/d14bdd5e5af9103889cd3d2ffbb7195aacf02e45 was pushed some time ago

## To reproduce

```console
$ curl -fsLS get.chezmoi.io | grep termux-info
                if is_command termux-info; then
```

## Expected behavior

Running `curl -fsLS get.chezmoi.io | sh` in `proot-distro` in Termux should install `linux` binary, not `android` one.

**Comment by twpayne** [comment]
Thanks, fixed manually for now with https://github.com/chezmoi/get.chezmoi.io/commit/5f09ee7bb563c3d9880be3aa1fd9313f8a28fd47.

Due to #3622, the automatic deployment did not run. #3622 is fixed by #3623.
