### ISSUE TITLE
How to manage chezmoi config file with chezmoi itself?

### ISSUE THREAD

**Issue by arberosmani** [twpayne/chezmoi#3634]
How is it intended to manage the file `~/.config/chezmoi/chezmoi.toml`? When I try to add it using `chezmoi add`, I get the following error:

```
chezmoi: /home/user/.config/chezmoi/chezmoi.toml: cannot add chezmoi file to chezmoi (/home/user/.config/chezmoi/chezmoi.toml is protected)
```
While it is possible to achieve this by creating the config file as template in `/home/user/.local/share/chezmoi/.chezmoi.toml.tmpl` or as non-template in `/home/user/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml`.

But what is the suggested way to do that? I couldn't find anything about that in the documentation.

**Comment by halostatue** [comment]
You don't. The only supported way is [`.chezmoi.$FORMAT.tmpl`](https://www.chezmoi.io/reference/special-files-and-directories/chezmoi-format-tmpl/), which is used by [chezmoi init](https://www.chezmoi.io/reference/commands/init/). This is explained in somewhat more detail in [Setup](https://www.chezmoi.io/user-guide/setup/#create-a-config-file-on-a-new-machine-automatically).

If you have some suggestions for improving the documentation to make this easier to find, we will happily accept either pull requests or new issues with those suggestions.

We *do* request that people search all issues before opening a new one, as this exact question has been asked recently (#3405), with similar questions at #2854 and #3285.
