### ISSUE TITLE
Adding local changes to target which is templated

### ISSUE THREAD

**Issue by funkyfisch** [twpayne/chezmoi#3639]
## What exactly are you trying to do?

I have started using templates since I am managing multiple machines of various attributes (windows, native linux, desktop vs server etc) I have made some files to be templated (such as ~/.bashrc) and the template evaluates some conditionals and decides whether to place the lines or not when doing `chezmoi apply`. So far so good.

Now however I was forced to change my workflow. Before templates my workflow was like this:
1) edit local file -> 2) test changes -> 3) repeat 1&2 as necessary -> 4) chezmoi add ~/.bashrc -> 5) chezmoi cd, git add , git commit, git push

I can no longer do steps 1 through 4 because adding the new changes overrides any templating clauses (e.g. the conditionals) and just overwrites with the entire contents of my local copy.

What is the proposed workflow here? should I just work on the chezmoi copies (e.g. dot_bashrc) and everytime I want to test them locally, i hit `chezmoi apply` ?

## What have you tried so far?

I have read through the docs, but I feel like im missing something.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
The easiest workflow with templates is to use [`chezmoi edit`](https://www.chezmoi.io/reference/commands/edit/), for example:

    chezmoi edit --watch ~/.bashrc

This opens the template and applies the changes every time you save the template.

If you have local changes that you want to combine into the template then you can use [`chezmoi merge`](https://www.chezmoi.io/reference/commands/merge/), but it's best to avoid this by using `chezmoi edit` consistently.

See also [How do I edit my dotfiles with chezmoi?](https://www.chezmoi.io/user-guide/frequently-asked-questions/usage/#how-do-i-edit-my-dotfiles-with-chezmoi).

**Comment by halostatue** [comment]
I mostly use `chezmoi merge-all` and turn off diff-mode in the middle window for templates so that I can see what the difference between the generated file (right window) and the current target file (left window).

**Comment by funkyfisch** [comment]
> The easiest workflow with templates is to use [`chezmoi edit`](https://www.chezmoi.io/reference/commands/edit/), for example:
> 
> ```
> chezmoi edit --watch ~/.bashrc
> ```
> 
> This opens the template and applies the changes every time you save the template.

I think I really like this approach! It looks so obvious now that I can't comprehend how I didn't think of that earlier. It might be a bit costly if secrets are involved, but good thing I rarely edit the files containing secrets :D Thanks a lot - I will practice merge-all too just in case I happen to hastily edit targets.
