### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by DandyDev** [twpayne/chezmoi#366]
First of all: Chezmoi seems like a great tool! I ran into Chezmoi when looking for a way to manage my dotfiles across multiple machines (work laptop, private laptop), and Chezmoi seem to fit the bill!

A couple of suggestions though:
- Installation: I like the "One-line binary install" (`curl -sfL https://git.io/chezmoi | sh`, because it allows me to install Chezmoi on a fresh machine with zero dependencies (not even Homebrew), but it would be nice if this install method would also install shell completions
- Editing: my previous workflow for editing my dotfiles, was that I had an alias `editdf` which would open the directory containing my dotfiles in my editor, so I could edit them together. Chezmoi only allows editing a single file at a time using `chezmoi edit <file>`. It would be useful when I do `chezmoi edit` without an argument, that it would open the source directory with `$EDITOR`. If that's not possible for some reason, at least allow me to get the source dir without actually opening a shell (so `chezmoi cd` without opening a shell, just returning the source dir)

**Comment by DandyDev** [comment]
And another suggestion: doing `curl -sfL https://git.io/chezmoi | sh` installs chezmoi _relative_ to the current directory. Wouldn't it be more logical if it would always install relative to `$HOME`? For example `$HOME/bin/chezmoi`

**Comment by twpayne** [comment]
Thanks for the suggestions :)

For the installation script installing shell completions, currently chezmoi uses [godownloader](https://github.com/goreleaser/godownloader). This doesn't support shell completions at the moment. Installing shell completions with the script will be difficult to achieve. The install script runs with local user privileges only and does not have permission to install shell completions in system directories. Where shell completions need to be installed in the user's home directory to be picked up by that user's particular shell will depend on that user's particular configuration, and is consequently non-standard. The easy way to get shell completions out-of-the box is to install a package.

`chezmoi edit` opening `$EDITOR` with the source directory is a nice idea and I'll add this.

You can get the source directory directly by running [`chezmoi source-path`](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#source-path-targets).

For the one-line installing the binary relative to `$HOME`, I think this assumes too much. The user might want an installation in `./bin`. godownloader is currently widely used this way. I'll update the documentation to better describe the current behavior, however.

**Comment by DandyDev** [comment]
Thanks for the reply! For the shell completions, I found a workaround. I'll use the one-liner to bootstrap my dotfiles, but I have a run_once script that replaces the bootstrap version of chezmoi with the Homebrew version, that contains the shell completions.

> For the one-line installing the binary relative to $HOME, I think this assumes too much.
You're right.

**Comment by twpayne** [comment]
#368 should fix most of this, and I opened #369 to track the remaining work. Thanks again @DandyDev for the great suggestions :)

**Comment by DandyDev** [comment]
Thanks for the great tool and the quick responses! I'm very happy that my 2 Macbooks' configurations are now in sync!
