### ISSUE TITLE
Use regular file target with symlink mode enabled

### ISSUE THREAD

**Issue by zhengpd** [twpayne/chezmoi#3668]
There are some files I'd like to apply as regular files, while symlink mode is enabled in .chezmoi.toml. How to do this with chezmoi?

**Comment by twpayne** [comment]
This is not possible. The mode is a global setting. The way to achieve this is to use the normal ("file") mode and explicitly create symlinks with `symlink_` when you need them.

**Comment by zhengpd** [comment]
Okay, I thought there is something like `regular_` prefix to create regular file explicitly.
