### ISSUE TITLE
Unable to add  .config files - chezmoi: git: fork/exec /usr/bin/git: argument list too long

### ISSUE THREAD

**Issue by zany130** [twpayne/chezmoi#3688]
## What exactly are you trying to do?
add my .config files into my git repo

I enabled auto-commit and auto push

## What have you tried so far?

manually going into my chezmoi git folder and pushing the changes like this
```
git add *
git commit -m "add .config files"
git push
```
and I get 
```
Enumerating objects: 48184, done.
Counting objects: 100% (48184/48184), done.
Delta compression using up to 12 threads
Compressing objects: 100% (36128/36128), done.
error: RPC failed; HTTP 500 curl 92 HTTP/2 stream 7 was not closed cleanly: CANCEL (err 8)
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (48183/48183), 2.71 GiB | 56.97 MiB/s, done.
Total 48183 (delta 8745), reused 48090 (delta 8743), pack-reused 0 (from 0)
fatal: the remote end hung up unexpectedly
Everything up-to-date
```
## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details. https://stackoverflow.com/a/75817884/6112309

## Output of any commands you've tried with `--verbose` flag

```console
chezmoi --verbose add .config/ludusavi/config.yaml
chezmoi: git: fork/exec /usr/bin/git: argument list too long
```

## Output of `chezmoi doctor`

<details>

```console
chezmoi doctor
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
RESULT    CHECK                       MESSAGE
warning   version                     v2.47.3, built at 2024-04-01T09:30:33Z
ok        latest-version              v2.47.3
ok        os-arch                     linux/amd64 (Garuda Linux)
ok        uname                       Linux Garuda-Linux 6.8.4-1-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 17:20:20 +0000 x86_64 GNU/Linux
ok        go-version                  go1.22.1 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-04-08T16:59:28-04:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
error     dest-dir                    ~ is a git working tree (error)
ok        umask                       022
ok        cd-command                  found /usr/bin/fish
ok        cd-args                     /usr/bin/fish
info      diff-command                not set
ok        edit-command                found /usr/bin/code-oss
ok        edit-args                   /usr/bin/code-oss
ok        git-command                 found /usr/bin/git, version 2.44.0
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /usr/bin/fish
ok        shell-args                  /usr/bin/fish
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.4.5
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

it seems the problem is git has a 2GB upload file limit https://stackoverflow.com/a/75817884/6112309

tried the fixes listed there with no luck

**Comment by halostatue** [comment]
There are a couple of issues here, and only one of them appears to be related to chezmoi — but I don’t think that there’s a good fix for them.

- `argument list too long` is literally what happens when you call `git add …` with too many arguments or an argument list too long (1 million characters on macOS, but it may be shorter with `fork`). This could happen if full pathnames are used by chezmoi when calling `git add`; I don’t use auto-add, so I can’t say for certain whether this is the case.

- The git pack/disconnect is a git issue, unrelated to chezmoi. I have what I think is a fairly large chezmoi repo, and the pack is approximately 15Mb. (`git count-objects -vH` or `du -sh .git`).

   The report of a 2.7Gb pack suggests that you have committed large binary data (.zip files, etc.) which is a bad idea for git in general. This is something that you will need to resolve yourself, possibly following the suggestions in the linked SO post or other suggestions to shrink the size of a repository.

**Comment by twpayne** [comment]
It sounds like you have way too many files in git.

What's the output of

    chezmoi git status

?

**Comment by zany130** [comment]
> It sounds like you have way too many files in git.
> 
> What's the output of
> 
> ```
> chezmoi git status
> ```
> 
> ?
like I said in the op, I am trying to backup my WHOLE `.config` folder (well, with some exceptions that I added to `.local/share/chezmoi/.chezmoiignore` to ignore nonessential stuff like cache and logs). I think this may be my issue. as it seems what I am doing is not dotfile management but a backup of my files that so happen to be under `.folders`, and git is not suited for that?

```
chezmoi git status
On branch main
Your branch is ahead of 'origin/main' by 2 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by twpayne** [comment]
> think this may be my issue. as it seems what I am doing is not dotfile management but a backup of my files that so happen to be under `.folders`, and git is not suited for that?

Exactly. git is a version control system, not a backup system. chezmoi is a dotfiles manager, not a backup system.

**Comment by zany130** [comment]
I'm sorry I got them confused. I do want to do versioning of my backups. https://rdiff-backup.net seems to be a good tool for this. Thanks, though, for responding. Also, thanks for chezmoi. While it doesn't help with the backup of my .files, I will still be using it for syncing select configs between machines, and the templates seem very helpful.
