### ISSUE TITLE
Automatically add new files for monitored folder?

### ISSUE THREAD

**Issue by ckt114** [twpayne/chezmoi#3697]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
I've added a folder using `chezmoi add /path/to/folder` but when I add new files to that folder I have to manually remember to run `chezmoi add /path/to/folder` each time. Is there a way to automatically add new files to a folder that's currently monitored by chezmoi?

## Describe alternatives you've considered
Have not found an alternative.

## Additional context
An example use case would be a folder that have my passwords encrypted using `gopass`. When adding new passwords it create new files and those files are not added automatically.

**Comment by twpayne** [comment]
See https://github.com/twpayne/chezmoi/issues/3680#issuecomment-2034606352.

**Comment by ckt114** [comment]
Thanks, @twpayne but that doesn’t seem to be the solution especially I’m on a Mac. I’ll look into creating a pre-commit git hook instead. Is there a way to list all the directories that chezmoi currently monitor?

**Comment by twpayne** [comment]
> Is there a way to list all the directories that chezmoi currently monitor?

    chezmoi managed --include=dirs

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
