### ISSUE TITLE
chezmoi quick start documentation is out of date

### ISSUE THREAD

**Issue by o6uoq** [twpayne/chezmoi#3709]
[chezmoi quick start guide](https://www.chezmoi.io/quick-start/#start-using-chezmoi-on-your-current-machine) has the following instruction/command:

```
$ git remote add origin https://github.com/$GITHUB_USERNAME/dotfiles.git
$ git branch -M main
$ git push -u origin main
```

This won't work due to:

> As [previously announced](https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/), starting on August 13, 2021, at 09:00 PST, we will no longer accept account passwords when authenticating Git operations on GitHub.com. Instead, token-based authentication (for example, personal access, OAuth, SSH Key, or GitHub App installation token) will be required for all authenticated Git operations.

More info [here](https://github.blog/changelog/2021-08-12-git-password-authentication-is-shutting-down/).

Suggested that the docs are updated with current and working commands to get up and running via quick start guide.

**Comment by twpayne** [comment]
Thanks, this is fixed with #3710.
