### ISSUE TITLE
Multiple source directories

### ISSUE THREAD

**Issue by lutzky** [twpayne/chezmoi#3719]
## What exactly are you trying to do?

I would like to use chezmoi for work, and keep the work-specific files in an internal git repo at work (I'd like to avoid even the names of the files being public). Others at work seem to have used rcm's support for multiple `DOTFILES_DIRS` for this, and I'm looking to replicate this with chezmoi.

### What seems to work

Basically this:

```fish
alias chezvous "chezmoi -S ~/.local/share/chezmoi_work"
```

(My french is too rusty to tell me if `chezvous` or `cheztoi` would be better, but I'm thinking I'd like to visually distinguish the two 🤷 )

This seems hacky, however, and I was hoping to learn if there's a cleaner recommended method.

### Things that don't quite fit the bill

- Externals don't seem like they'd let me `chezmoi edit` the relevant files.
- Completely separate repos don't let me share common things (of which there are many); the same thing seem to apply to branch-based solutions

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

n/a

## Output of `chezmoi doctor`

n/a

## Additional context

n/a

**Comment by halostatue** [comment]
This is a "layered" approach, described nicely in #2574. I believe that Install Doctor (#3659) is doing something *similar*, but at the same time very different.

**Comment by lutzky** [comment]
Nice. I think this *kinda* validates my approach. Te implementation details of #2574 are such that, for my limited purposes, I'll go with just having two simultaneous-but-separate `chezmoi` configs with a `cheztoi` alias (similar to their `czb`). Thank you for showing me this!
