### ISSUE TITLE
Add a public_ attribute

### ISSUE THREAD

**Issue by tmccombs** [twpayne/chezmoi#3727]
## Is your feature request related to a problem? Please describe.
If you have a umask of 077 or 027, then all files created by chezmoi won't be publiclly readable. which is great. Except if you have something that you _do_ want to be publicly readable, there isn't a way to override that umask.

## Describe the solution you'd like

Add a `public_` attribute that specified that group and other should have read (and execute, if applicable) permissions. Basically, force  the umask to be 022 for that file.

## Describe alternatives you've considered

You could specify a umask of 022, and then add `private_` to everything you don't want public. But that is rather inconvenient. 

Maybe you could use a hook that changes the permission of the files after the fact, but I'm not sure quite how to do that.

**Comment by twpayne** [comment]
Use a `run_after_` script to set the permissions on the target file.

For more background information on how chezmoi handles permissions, see https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-use-weird-filenames.

**Comment by tmccombs** [comment]
> chezmoi's attributes of executable_, private_, and readonly_ allow the file permissions 0o644, 0o755, 0o600, 0o700, 0o444, 0o555, 0o400, and 0o500 to be represented

This is only true if the umask is 022. If the umask is instead 077 (either because that is the inherited umask, or it is explicitly configured so), then the possible file permissions are: 0o600, 0o700, 0o400, and 0o500. And `private_` doesn't really do anything. 

This is rare enough that a `run_after_` script is probably an acceptable solution, but it feels a little heavy-handed. But adding a new attribute wouldn't really be backwards compatible unless it was behind a flag. So I guess it's probably not worth adding. But if I were designing this from scratch I would probably add it.
