### ISSUE TITLE
Cannot set environment variable in read-source-state pre hook

### ISSUE THREAD

**Issue by lukasfri** [twpayne/chezmoi#3729]
## What exactly are you trying to do?

I'm trying to set the BW_SESSION environment variable in the read-source-state pre hook (after calling bitwarden unlock) so that all bitwarden calls does not need its own master password prompting.

## What have you tried so far?

I've tried exporting environment variables from the script file with no luck. The documentation for the bitwarden commands does not appear to have any way to provide the session manually so I seem to have to do it through env.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.
I have searched through all issues here on github related to hooks and environment variables without any luck.

## Output of any commands you've tried with `--verbose` flag

*NOT APPLICABLE*

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.48.0, commit c758a1c57fb6084631736a7dda5ac0aaeeffa946, built at 2024-04-26T20:38:57Z, built by goreleaser
ok        latest-version              v2.48.0
ok        os-arch                     linux/amd64 (Fedora Linux 40 (KDE Plasma))
ok        uname                       Linux CENSORED-HOSTNAME 6.8.7-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:21:08 UTC 2024 x86_64 GNU/Linux
ok        go-version                  go1.22.2 (gc)
ok        executable                  /var/lib/snapd/snap/chezmoi/876/chezmoi
ok        upgrade-method              snap-refresh
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-04-27T15:52:43+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
warning   suspicious-entries          ~/.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /usr/bin/zsh
ok        cd-args                     /usr/bin/zsh
info      diff-command                not set
ok        edit-command                found /usr/bin/nano
ok        edit-args                   /usr/bin/nano
ok        git-command                 found /usr/bin/git, version 2.44.0
warning   merge-command               vimdiff not found in $PATH
ok        shell-command               found /usr/bin/zsh
ok        shell-args                  /usr/bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.4.4
info      pinentry-command            not set
info      1password-command           op not found in $PATH
ok        bitwarden-command           found /var/lib/snapd/snap/bin/bw, version 2024.3.1
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

I've confirmed that the script runs by putting a print statement in it, which does execute. I've also tried setting a hard-coded env value to confirm that it's not being set.

**Comment by twpayne** [comment]
This is not possible on any UNIX-like system. Processes can set their own environment variables and can set the initial environment variables when spawning a subprocess, but they cannot modify another process's environment.

**Comment by lukasfri** [comment]
> This is not possible on any UNIX-like system. Processes can set their own environment variables and can set the initial environment variables when spawning a subprocess, but they cannot modify another process's environment.

Wouldn't it be possible to set the env for just the chezmoi process itself? Ie chezmoi would copy any env variables set in a subscript (or add a command/special CHEZMOI_SET_* env variables you can set that modifies the env of the rest of the apply process? I realize this is turning more into a feature request at that point, but I think it could be useful.

**Comment by twpayne** [comment]
No, because chezmoi cannot read the subprocess's environment.

**Comment by lukasfri** [comment]
Ah, shite. Could a way be added to set environment variables from the chezmoi secret manager post script? Ie you run chezmoi secret set in the script, then load BW_SESSION from the secret manager and then run the rest of the apply process, or is the environment setting process frozen when applying has started?

**Comment by halostatue** [comment]
Yes and no. There’s a thread that I summarized at https://github.com/twpayne/chezmoi/discussions/3202#discussioncomment-6853735. The standard Bitwarden CLI is a toxic mess (see https://github.com/twpayne/chezmoi/discussions/3657#discussioncomment-8860134) which should be avoided because it doesn’t handle sessions in a sensible way.

As I said in the second link:

> We would happily take a PR that would extend the bw support to grab a token just like we do with 1Password (I would want to make sure that we invalidate the token after use so that we’re behaving better than the bw cli by default).

I’m not in a position to make the change myself, because the only time that I’ve used Bitwarden is when testing in chezmoi, because I use and prefer 1Password.

**Comment by twpayne** [comment]
As @halostatue says, the underlying problem here is that Bitwarden doesn't provide a way to start temporary sessions from within a subprocess. I'd suggest requesting this as a feature from Bitwarden. In the meantime, I personally, like @halostatue, am a very happy 1Password user.

Closing this for now, as there's not much else chezmoi can do. You have to run `bw login` before running chezmoi at the moment, that's it.
