### ISSUE TITLE
`remove` should have a warning

### ISSUE THREAD

**Issue by jthn** [twpayne/chezmoi#373]
I think maybe this should have had some kind of a prompt/warning.  I'm new here, so I was thinking of chezmoi as something like apt.  I inadvertently added my entire `~/.config/nvim` directory, realized my mistake, so I removed it.

....and I'm pretty sure I just nuked my entire vim config, and it's been awhile since I backed it up (which is why I'm here).  I think since this command is destructive (as best I can tell), it would be a very good idea to add a force flag to remove without prompt and make the default behavior require confirmation that the command is destructive.

This is my mistake, but I won't be the last one to make it most likely.

**Comment by twpayne** [comment]
Oh pants! I'm really sorry about that.

You're right, `remove` should prompt for each file by default.

**Comment by jthn** [comment]
It's okay, with the language server coming out, I've been thinking of revisiting my setup in a pretty serious way.  This just makes sure I don't go for half measures.
