### ISSUE TITLE
re-add as an option when running update

### ISSUE THREAD

**Issue by nivaca** [twpayne/chezmoi#3731]
## Is your feature request related to a problem? Please describe.

When running `chezmoi update` and I get a notification saying that a file has been changed, and it happens that I approve of the change, I have to `skip` the update and then run `chezmoi re-add` to commit the changes.

## Describe the solution you'd like
A `re-add` option in the available options offered by `chezmoi update` would be great in order to streamline the workflow.

## Describe alternatives you've considered
I `skip` the update and then `re-add` the file. Two steps.

**Comment by halostatue** [comment]
Depending on what you’re using, that could be quite dangerous. My `.config/git/config` is templated, so a re-add option would destroy the template options with fixed resolution.

If you often modify files outside of chezmoi (like I do), it is worthwhile using `chezmoi merge TARGET` or `chezmoi merge-all`.

**Comment by twpayne** [comment]
I agree that this would be a nice feature. However, there are a couple of difficulties in implementing it:

1. As @halostatue says, `re-add` only works on simple files.
2. chezmoi's implementation is based on the assumption that the source state does not change while chezmoi is running. Adding such a `re-add` option would directly violate this as it modifies the source state directly while `chezmoi apply` is running.

So, I'll add this as a potential [`v3` feature](https://github.com/twpayne/chezmoi/issues?q=is%3Aissue+is%3Aopen+label%3Av3). There is no ETA for this.

**Comment by nivaca** [comment]
Thanks to both of you. So `re-add` should only be used with non-template files, you mean?

**Comment by halostatue** [comment]
Probably? I don’t think that I’ve *ever* used `chezmoi re-add`, because I find the workflow of `chezmoi merge` or `chezmoi merge-all` so much better. If I am performing an `apply` and see a file that I did not expect to see, I check the diff and if I don’t like it, I `q`uit the apply (or sometimes just hit `C-c`).

**Comment by twpayne** [comment]
The behavior of `re-add` [is documented](https://www.chezmoi.io/reference/commands/re-add/).

It's useful enough in its current form (at least, it's part of several people's workflow) that it's worth keeping as-is.

**Comment by nivaca** [comment]
I now understand the perils of using `re-add` automatically. However---and this is a more basic question---I have not grasped the use of `merge` and `merge-all`. If I change a (local) file, and I run `chezmoi merge-all` (or `chezmoi merge <file>`), I get the three-pan diff (using vimdiff or whatever). If I make any changes there, I have noticed that chezmoi doesn't push them to the git repo. So I'm at a loss here.

**Comment by twpayne** [comment]
Do you have any of `git.autoAdd`, `git.autoCommit`, or `git.autoPush` set?

**Comment by nivaca** [comment]
> Do you have any of `git.autoAdd`, `git.autoCommit`, or `git.autoPush` set?

I have the two latter set to true, but nothing on the first one.

**Comment by nivaca** [comment]
I set `git.autoAdd` to true and everything works as expected now. Thanks.
