### ISSUE TITLE
Is it possible to turn off name-mangling on push?

### ISSUE THREAD

**Issue by rtviii** [twpayne/chezmoi#3738]
I might be missing a plot point or two when using `chezmoi`:
1. i add a bunch of dotfiles via `chezmoi add ~/.config/test{1,2,3}.conf`
2. i make some edits to them over span of months
3. i forgot what edits i made where, so i `chezmoi re-add`
4. occasionally i add a new file to the fold `chezmoi add ~/.other_config/test.conf`
5. when i want to push them i `chezmoi cd`, `git add .` and `git push` from the `chezmoi` repo.

I'm really not sure if my step 5 is in line with the package philosophy or there is a cleverer layer of indirection on top... even so it's the most convenient utility i've used for config files so far. 

My issue is basically when i add file to the chezmoi repo, a bunch of names get prepended with stuff like "executable" and "private":
```
 rename private_dot_config/nvim/lua/{keys.lua => executable_keys.lua} (100%)
 rename private_dot_config/nvim/lua/{opts.lua => executable_opts.lua} (100%)
 rename private_dot_config/nvim/lua/{plugins.lua => executable_plugins.lua} (100%)
 rename private_dot_config/nvim/lua/{vars.lua => executable_vars.lua} (100%)
 rename private_dot_config/nvim/plugin/{packer_compiled.lua => executable_packer_compiled.lua} (100%)
 rename private_dot_config/private_Code/User/{keybindings.json => executable_keybindings.json} (100%)
 rename private_dot_config/private_Code/User/{settings.json => executable_settings.json} (100%)
 create mode 100644 private_dot_config/scripts/executable_repdf
 rename private_dot_config/sioyek/{keys_user.config => executable_keys_user.config} (100%)
```

Can i turn this off?

**Comment by twpayne** [comment]
Nope. See https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-use-weird-filenames.

**Comment by bradenhilton** [comment]
@twpayne is this a bug? I'm not sure why it adds the `executable` attribute to files which are not executable. I also noticed this in https://github.com/twpayne/chezmoi/issues/3715#issuecomment-2078061415.

I never use `add` or `re-add` so I'm not sure if it's always been like this.

**Comment by twpayne** [comment]
I don't think it's a bug, but I might be wrong. Executable flags can get set by all sorts of things like filesystems (I think older FAT filesystems always set them) and unpacking .zip files. Since the reporter of this issue ignored the issue templates, didn't give clear steps for others to reproduce the problem, and didn't even include the output of `chezmoi doctor` I am not inclined to investigate this further without some evidence of effort on their part.
