### ISSUE TITLE
One-line binary install script does not give an error when cannot establish HTTPS connection

### ISSUE THREAD

**Issue by bwobst** [twpayne/chezmoi#3756]
## What exactly are you trying to do?

I'm trying to install Chezmoi on a fresh Ubuntu Desktop instance.

The command:
```bash
sh -c "$(curl -fsLS get.chezmoi.io)"
```

The output:
```bash
error real_tag error retrieving GitHub release latest
```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

## Output of any commands you've tried with `--verbose` flag

N/A

## Output of `chezmoi doctor`

N/A

## Additional context

This command worked about an hour ago when I was setting up an identical Ubuntu Desktop instance. Perhaps the `latest` tag got botched accidentally?

**Comment by twpayne** [comment]
This is almost certainly a temporary issue on GitHub's side. Try again in 30 minutes or so.

**Comment by bradenhilton** [comment]
@twpayne It's possible that this could also be a factor in https://github.com/twpayne/chezmoi/issues/3749, though there isn't a great way to know for sure.

**Comment by bwobst** [comment]
Closing the loop on this issue. The fix was to install a few additional dependencies:
```bash
sudo apt install apt-transport-https ca-certificates software-properties-common
```

**Comment by twpayne** [comment]
Thanks for the investigation here. I suspect that the only package you actually need is `ca-certificates`. In any case, the one line install script should give a meaningful error message when it can't establish an authenticated connection to GitHub. So, I'll re-open this issue as a bug.
