### ISSUE TITLE
Using environment variable in onepasswordRead

### ISSUE THREAD

**Issue by chessbyte** [twpayne/chezmoi#3783]
## What exactly are you trying to do?

In a template, trying to specify 1password account from an environment variable.

## What have you tried so far?

This works
`{{ onepasswordRead "op://chessbyte/GitHub/access-token" "1234567890ABCDEF1234567890" }}`

but this doesn't
`{{ onepasswordRead "op://chessbyte/GitHub/access-token" "$OP_ACCOUNT" }}`

nor does this
`{{ onepasswordRead "op://chessbyte/GitHub/access-token" "{{ env "OP_ACCOUNT" }}" }}`

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by halostatue** [comment]
You want this:

```
{{ onepasswordRead "op://chessbyte/GitHub/access-token" (env "OP_ACCOUNT") }}
```

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
