### ISSUE TITLE
Support chmod in attributes

### ISSUE THREAD

**Issue by lilHermit** [twpayne/chezmoi#3784]
## Is your feature request related to a problem? Please describe.

Yes the problem is : I use the umask of 007 for `.config` and `.local` however when I add files / directories from within these chezmoi wants to to change them back to `755`  / `644`. I have setup a chezmoi run script to fix however this is annoying as `chezmoi diff` is difficult to read as it's littered with 

```console
diff --git a/.config b/.config
old mode 40750
new mode 40700
diff --git a/.config/tmux/plugins b/.config/tmux/plugins
old mode 40750
new mode 40755
diff --git a/.config/tmux/tmux.conf b/.config/tmux/tmux.conf
old mode 100640
new mode 100644
diff --git a/.local b/.local
old mode 40750
new mode 40700
diff --git a/.local/share b/.local/share
old mode 40750
new mode 40700
diff --git a/fix-perms.sh b/fix-perms.sh
new file mode 100755
```

## Describe the solution you'd like

It would be good if we can set chmod attributes to files / directory to prevent the default `755/644` being used

## Describe alternatives you've considered

I use the `run_fix-perms.sh` workaround but it makes dfffs awkward to read

**Comment by twpayne** [comment]
Use the [`private_` attribute](https://www.chezmoi.io/reference/source-state-attributes/):

```console
$ chezmoi chattr +private ~/.config ~/.local
```

**Comment by lilHermit** [comment]
but that sets the default chmod of  `755` / `644` I want to specify `750` / `640`  so 2 things might be useful

1. being able to specify in the config what private mode chmod looks like. For example
```yaml
priviate_chmod:
  file: 640
  directory: 750
```

2. Being able specific chmod per directory / file. For example
```bash
## Directory
$ chezmoi chattr +chmod 750 .config

##
$ chezmoi chattr +chmod 640 .config/tmux.conf
```

**Comment by halostatue** [comment]
Does the config option [umask](https://www.chezmoi.io/reference/configuration-file/umask/) help with your request?

**Comment by lilHermit** [comment]
@halostatue  Wow not sure how I missed that, thanks 

Iit helps greatly as if I set the umask to 027 all my files get the correct permission it `rw-r-----` . However chezmoi still sets the `.local` and `.config` directories to `rwx------` (`700`) however I need `750 ` so my backup script use can read my files.  As a result when I run `cheqmoi diff` I get the following:

```bash
diff --git a/.config b/.config
old mode 40750
new mode 40700
diff --git a/.local b/.local
old mode 40750
new mode 40700
diff --git a/.local/share b/.local/share
old mode 40750
new mode 40700
diff --git a/fix-perms.sh b/fix-perms.sh
new file mode 100755
index 0000000000000000000000000000000000000000..c135c3939e4f36bc1c27b98224a26509fe659b3c
--- /dev/null
+++ b/fix-perms.sh
@@ -0,0 +1,6 @@
+#!/bin/bash
+
+## Fixing permissions required for restic to backup
+chmod 750 ~/.config
+chmod 750 ~/.local
+chmod 750 ~/.local/share
```
Which is slightly annoying and would be great if that could be fixed.

**Comment by twpayne** [comment]
The current set of permission-related attributes work for almost everybody. Adding a new, complex, attribute which is not orthogonal to the existing attributes is too much complexity for too little gain. I would instead suggest modifying your backup script.
