### ISSUE TITLE
Powershell one-line install on Windows 11 error - update script at https://get.chezmoi.io/ps1

### ISSUE THREAD

**Issue by pmolodo** [twpayne/chezmoi#3787]
## Describe the bug

The one-line powershell install given [in the docs](https://www.chezmoi.io/install/#one-line-package-install) is:

```powershell
iex "&{$(irm 'https://get.chezmoi.io/ps1')}"
```

Unfortunately, this still does not work on a fresh Windows 11 install, because script at https://get.chezmoi.io/ps1 has not been updated with [this fix MR](https://github.com/twpayne/chezmoi/pull/3751) for [this issue](https://github.com/twpayne/chezmoi/issues/3749).

Please upload the updated script to https://get.chezmoi.io/ps1, or else update the docs to use

```powershell
iex "&{$(irm 'https://raw.githubusercontent.com/twpayne/chezmoi/master/assets/scripts/install.ps1')}"
```

...instead.  Thanks!

## To reproduce

See [issue 3749](https://github.com/twpayne/chezmoi/issues/3749) - on a fresh Windows 11 install, open powershell, and run:

```powershell
iex "&{$(irm 'https://get.chezmoi.io/ps1')}"
```

You will get this error:

```
You cannot call a method on a null-valued expression.
At line:1 char:1
+ &{<#
+ ~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

## Expected behavior

The chezmoi binary should get installed.

**Comment by twpayne** [comment]
This bug is #3749, as you identify. The install script is updated when a new version of chezmoi is released. I want to fix #3772 before releasing a new version of chezmoi.
