### ISSUE TITLE
forced update says "Already up to date."

### ISSUE THREAD

**Issue by k4lizen** [twpayne/chezmoi#3811]
## Describe the bug
`chezmoi update --force`
Does the expected thing but outputs to the screen "Already up to date." even when that is not the case and it successfully updated files.

## To reproduce
1. Change any tracked file so it differs from the chezmoi repo
2. chezmoi update --force

## Expected behavior
It gave a correct message.

**Comment by twpayne** [comment]
As per the [documentation on `chezmoi update`](https://www.chezmoi.io/reference/commands/update/), `chezmoi update` runs `git pull ...` in the source directory. The `Already up to date` message is coming from git, not chezmoi, and indicates that the source directory is up to date with respect to your dotfiles repo.
