### ISSUE TITLE
Ability to dry-run / diff scripts

### ISSUE THREAD

**Issue by cmfcmf** [twpayne/chezmoi#3812]
## Is your feature request related to a problem? Please describe.

I use some scripts with chezmoi. One such script is similar to the example script in the documentation and sets several `dconf` options using `dconf load /  ...`. However, it is currently not possible for me to dry-run the script to see what it would change. Before running `chezmoi apply`, I would like to run `chezmoi diff` to double-check the changes made by the script.

## Describe the solution you'd like

I would like to see what a script will do when running `chezmoi diff`. E.g., scripts could be called by chezmoi with an argument that indicates whether the script should actually make changes, or just perform a dry run and print the would-be-changes to stdout. It would of course be up to the script's author to calculate the dry-run diff.

However, I am not sure about the best way to do this in a backwards-compatible way - scripts would probably need to "opt-in" to supporting this dry-run/diff mode. Maybe these scripts could use a different name, like `run_with_diff_XXX`?

## Describe alternatives you've considered

N/A

## Additional context

Scripts provide awesome flexibility for tasks that are just not supported by chezmoi, such as setting dconf options. However, the fact that scripts are very much treated like a blackbox, makes them a little daunting to use. It would be really nice if they could integrate into chezmoi's diff system.

**Comment by twpayne** [comment]
```console
$ chezmoi diff --include=scripts
```

?

**Comment by cmfcmf** [comment]
This only shows me the contents of the script - I would like to see what the script will do. Maybe this hypothetical example of how I would like to write the script illustrates it better?

`run_install_htop.sh:`
```
#!/bin/bash

if [ "$1" == "dry-run" ]; then
  HAS_HTOP=$(dpkg-query -Wf'${db:Status-abbrev}' htop 2>/dev/null | grep -q '^i')
  if $HAS_HTOP; then
    # Package is already installed - so this script won't do anything.
  else
    echo "Need to install package htop"
  fi
else
  apt install htop
fi
```

I would then want something like the following output:

Assuming `htop` is not already installed:
```
$ chezmoi diff
-> run_install_htop.sh:
-> Need to install package htop
```

Assuming `htop is already installed:
```
$ chezmoi diff
# no output
```

In essence, chezmoi would need to determine whether or not this script needs to run by invoking it with "dry-run" as the first argument, and then checking whether it produces any output. Of course this is just an example of a possible approach for implementing something like this. There might be better ways :)

Now, for something simple like installing a package, the extra complexity doesn't really make sense. But if you have a more complex script that might execute a irreversible action, it would be nice to be able to dry run it.

**Comment by halostatue** [comment]
@twpayne: This could theoretically be *enabled* if we set `$CHEZMOI_DRY_RUN=1` when `--dry-run` is provided, but as it would still be running the scripts … it would 100% depend on users adding this to their script to support it.

@cmfcmf: I think that this is *very risky* as it would always run the scripts and depend on the person who had written the script to include a "dry-run" mode that doesn't do anything irreversible. As such, I’m down on this otherwise good idea. If there was an additional *explicit* configuration or command-line option (`--dry-run-scripts`) that basically says to chezmoi "I know that this is dangerous, but do it anyway because I know what I’m doing" … it might be viable.

**Comment by cmfcmf** [comment]
> I think that this is very risky

Yes, agreed! Maybe what I really want is a new script type `run_supportsdryrun_*` (or similar), which would run as part of `chezmoi diff` with something like a `$CHEZMOI_DRY_RUN` variable set to tell the script that it should dry run only. That way, each script opts in/out via its name. I don't think this should be the default behavior or be controllable only for _all_ scripts I have - a per script control would be nice.

(Potentially, these dry-run-capable scripts could also have a slightly different behavior compared to normal scripts: They could run twice as part of `chezmoi apply`, once with `$CHEZMOI_DRY_RUN` (or similar) to determine whether the script needs to run, and then, assuming it provided a diff, runs the script once more without `$CHEZMOI_DRY_RUN`. But I really don't know.)

Anyways, as you can see I don't really have a strong idea or opinion how something like this could be implemented, so I appreciate any thoughts that you have on this.

**Comment by twpayne** [comment]
I agree with @halostatue. Such a feature would be very hard to use. Printing the contents of the script, as `chezmoi diff --include=scripts` already does, shows you what the script will do.
