### ISSUE TITLE
Import/merge separate source directories?

### ISSUE THREAD

**Issue by rlue** [twpayne/chezmoi#3817]
## Problem

Many of my dotfiles are related to my employer; these dotfiles cannot be hosted publicly. (The IT department has conducted audits in the past and explicitly reached out to me to change the visibility on my dotfiles repo.)

* I would like to make manage these files in a private git repo.
* I would like to make all my _personal_ dotfiles public on GitHub.
* I would like to use chezmoi to manage both of these repos together.

To be clear, this is more than just one-line secrets like API keys; it includes scripts for interacting with protected assets on the company network, etc.

## Proposed Solution

```sh
$ git clone <personal-dotfiles> ~/.local/share/chezmoi
$ git clone <employer-dotfiles>
$ chezmoi <command> --import-source <employer-dotfiles>
```

chezmoi would compute source state based on merging both source directories. Conflicting chezmoi directive files (`.chezmoiignore`, `.chezmoiexternals`, etc.) would be concatenated, while conflicting source files (`dot_bashrc`, etc.) would have the imported version take precedence.

Chezmoi's config file could specify an `importedSources` property to apply this option implicitly.

### Added benefits

This approach would make it possible to simply delete the private/employer repo from my chezmoi config when I leave my current job, rather than having to comb through my entire dotfiles repo and untangle all the files and template conditionals related to it.

## Attempted Alternatives

* **Password manager integrations:** It would be extremely clunky to store all my employer-related dotfiles as pgp-encrypted secrets in `pass`.
* **`.chezmoiexternal`:** contradicts chezmoi's declarative model—and, using a git repo as a source only supports fully self-contained subdirectories (_i.e.,_ you can't have both repos manage files in, say, `~/.local/share/applications`).
* **Don't store dotfiles publicly:** :(

Hopefully I have missed a clean way to handle this problem that is already supported. I feel like I'm pretty late to the chezmoi party, but I'm really loving it so far; thanks for a fantastic utility.

**Comment by bradenhilton** [comment]
https://github.com/twpayne/chezmoi/discussions/2574 could be useful here.

**Comment by halostatue** [comment]
@bradenhilton beat me to it. The correct answer is to maintain two repos with aliases as described in #2574. This is something that chezmoi is unlikely to support natively with a fairly robust workaround available. The only thing to worry about is if you need to modify the same file from *both* repos (e.g., `~/.aws/credentials`)—and there's really no good answer for that.
