### ISSUE TITLE
Set command line options via environment variables

### ISSUE THREAD

**Issue by rlue** [twpayne/chezmoi#3820]
## Problem

I am using two separate dotfile repos to manage my dotfiles, as suggested in #3817. For the sake of convenience, I would like to be able to run `chezmoi` from within a non-standard source directory, without specifying the `--source` CLI option.

## Solution

```sh
$ cd ~/.local/share/chezmoi.alt
direnv: loading ~/.local/share/chezmoi.alt/.envrc
direnv: export +CHEZMOI_SOURCE
$ echo $CHEZMOI_SOURCE
.
$ chezmoi diff # implicitly applies --source=.
```

## Alternatives

N/A

**Comment by twpayne** [comment]
No. chezmoi sets environment variables for scripts and commands it executes. Having it also change its behavior based on the contents of those environment variables is a recipe for confusion.

Instead, use separate config files that specify `sourceDir` and create a shell alias for running chezmoi with each config file.
