### ISSUE TITLE
Chezmoi by default pipes to `less` pager

### ISSUE THREAD

**Issue by Archie-2021** [twpayne/chezmoi#3850]
## Describe the bug

Chezmoi by default pipes to `less` pager

## Expected behavior

To pipe to stdout

## Additional context

Hi, I just updated may packages and noticed in recent chezmoi update it is piping the output into `less` and that messes with coloring in my terminal. Is there a way to revert this behaviour? I don't mind to pip to `less` by default if I get rid of this color issue

Thanks

**Comment by twpayne** [comment]
To disable the pager, use the `--no-pager` flag or set the `pager` configuration variable to an empty string.

To disable coloring of diff output, use `--color=false` flag or set the `color` configuration variable to `false` or set the `NO_COLOR' environment variable to a non-empty value.

**Comment by Archie-2021** [comment]
> To disable the pager, use the `--no-pager` flag or set the `pager` configuration variable to an empty string.
> 
> To disable coloring of diff output, use `--color=false` flag or set the `color` configuration variable to `false` or set the `NO_COLOR` environment variable to a non-empty value.

Thanks
