### ISSUE TITLE
`add --recursive` with private dirs is broken on Windows

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#387]
Following adding Windows support in #381, it was found that there were some problems with the implementation of `IsPrivate`, which were mostly fixed in #386.

However, it seems that `add --recursive` is broken on Windows when used with private directories. Specifically, on Windows, a public file inside a private directory is reported as being private, not public.

Consider:

    $ ls -lR /home/user
    total 0
    drwx------  3 twp  staff  96 Jul  7 15:31 private

    /home/user/private:
    total 0
    -rw-r--r--  1 twp  staff  0 Jul  7 15:31 public

This breaks chezmoi as on POSIX systems the source state will contain

	private_private/public

whereas on Windows, `public` is detected as being private and there the source state is

	private_private/private_public

@zb140 Could you have a look at this please as I don't have a Windows system and so can't properly test/debug this.

I *think* what is needed for `IsPrivate` on Windows to return that public files in private directories as being public, not private.

**Comment by twpayne** [comment]
The failing tests are currently skipped on Windows. Revert commit 131ed26563a77966f9debed6b15451b3d2bf0252 to restore them.

**Comment by zb140** [comment]
Man, file permissions are a real headache on Windows...  #389 has a fix for `IsPrivate` and re-enables the tests.

**Comment by twpayne** [comment]
Fixed by @zb140 in #389.
