### ISSUE TITLE
Customize the path for a single file

### ISSUE THREAD

**Issue by zkkv** [twpayne/chezmoi#3905]
## What exactly are you trying to do?

I want to add a `settings.json` file generated by VS Code to Chezmoi but it's stored under `User/profiles/[id]/settings.json`. This means that if I add it to Chezmoi, it will have the same relative structure. I want the file in Git to be simply stored under `chezmoi/VSCode/settings.json`. 

## What have you tried so far?

If I change the path manually after adding the file, Chezmoi will think the actual file is not tracked anymore. I need to preserve the original file path but also have a consistent associations between the two files.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] I have searched for the answer online.

**Comment by twpayne** [comment]
See https://www.chezmoi.io/user-guide/manage-machine-to-machine-differences/#handle-different-file-locations-on-different-systems-with-the-same-contents.

**Comment by zkkv** [comment]
> Then create files for each system, for example Library/Application Support/App/file.conf.tmpl for macOS and dot_config/app/file.conf.tmpl for Linux.

Wouldn't that preserve the original file structure in version control, the very thing I'm trying to avoid?

**Comment by twpayne** [comment]
In that case use a script to install `settings.json` to the machine-specific location.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if necessary.
