### ISSUE TITLE
Way to add a file without `applying`

### ISSUE THREAD

**Issue by itsvyle** [twpayne/chezmoi#3913]
## What exactly are you trying to do?

I want to be able to `chezmoi add` files without it running a chezmoi apply automatically; I have quite a few externals which need to refresh and both my internet and disk are slow, so it takes a while.

I'm trying to add without running this automatic apply

## What have you tried so far?

- I have removed the `edit.apply` property in the config (and then ran `chezmoi init`) to see if it changed the behavior, but it didn't
- To check it was in fact running an apply (or some sort of similar opération), I added a "fail" statement to one of my files, and it did throw an error, meaning it got evaluated

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```console
$ chezmoi --verbose add file
Prints nothing after 30 seconds
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor

RESULT    CHECK                       MESSAGE
ok        version                     v2.52.0, commit 64f40d93ea1f1456a6788798b9e9c4813156d86e, built at 2024-08-07T21:09:57Z, built by goreleaser
warning   latest-version              v2.52.1
ok        os-arch                     windows/amd64
ok        systeminfo                  Microsoft Windows 10 Pro (10.0.19045 N/A Build 19045)
ok        go-version                  go1.22.6 (gc)
ok        executable                  ~/AppData/Local/Microsoft/WinGet/Packages/twpayne.chezmoi_Microsoft.Winget.Source_8wekyb3d8bbwe/chezmoi.exe
ok        upgrade-method              winget-upgrade
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-08-22T16:57:33+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
warning   suspicious-entries          ~/.local/share/chezmoi/home/.chezmoiexternal.toml.tmpl~
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        cd-command                  found C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe
ok        cd-args                     powershell.exe -nologo
ok        diff-command                found ~/.local/bin/delta.exe
ok        edit-command                found ~/AppData/Local/Programs/Microsoft VS Code/bin/code.cmd
ok        edit-args                   code --wait
ok        git-command                 found C:/Program Files/Git/cmd/git.exe, version 2.17.1
warning   merge-command               vimdiff not found in $PATH
ok        shell-command               found C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe
ok        shell-args                  powershell.exe -nologo
info      age-command                 age not found in $PATH
ok        gpg-command                 found ~/AppData/Local/Programs/GnuPG/bin/gpg.exe, version 2.4.3
info      pinentry-command            not set
info      1password-command           op not found in $PATH
ok        bitwarden-command           found ~/.local/bin/bw.exe, version 2024.7.1
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set

```

</details>

## Additional context

Also tried on linux and got same issue

Is there an obvious flag or setting I'm missing here?

**Comment by halostatue** [comment]
Something unusual is going on here, because `chezmoi add` does not invoke `chezmoi apply` (and I would be very unhappy if it did, since my workflow always involves `chezmoi merge-all`).

Please provide more details about what you mean by having added a `fail` to one of your files.

**Comment by itsvyle** [comment]
`fail` is a sprig template function that exits the template with an error - documented at https://masterminds.github.io/sprig/flow_control.html

By adding one and seeing an error trigger when I `chezmoi add` I can basically prove that there's at least an evaluation of the `.chezmoiexternals.tmpl` file done when I add a new file.

**Comment by twpayne** [comment]
> By adding one and seeing an error trigger when I `chezmoi add` I can basically prove that there's at least an evaluation of the `.chezmoiexternals.tmpl` file done when I add a new file.

Yup. chezmoi has to do this because part of the source state is defined by externals and so chezmoi has to evaluate them.

**Comment by itsvyle** [comment]
Ah ok; I'll try to increase cache times for GitHub requests then.

Thank you very much,
