### ISSUE TITLE
Using scripts on Windows?

### ISSUE THREAD

**Issue by Sjlver** [twpayne/chezmoi#3917]
## What exactly are you trying to do?

I'm interested in using scripts to install packages (e.g., my password manager). The documentation for that is rather sparse, and I couldn't figure out how to do this in a way that works on Windows.

## What have you tried so far?

Currently, I have a somewhat portable Chezmoi configuration, using conditions like this (I could also do OS checks, but it seems cleaner to directly check whether a file is needed):

```
# .chezmoiignore
{{ if not (findExecutable "bash" (list "/bin" "/usr/bin")) }}
.bashrc
{{ end }}
```

I think that I could use similar mechanisms to run different versions of a script on Windows and on Linux. After reading https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/, I'm still unsure how to proceed. On Windows, I don't have `sh` available. I would probably need a Powershell script instead. Also, there's no concept of Shebang on Windows, so how would I make it executable?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Additional context

In general, I as a new user would benefit from more examples in the documentation. I've tried looking at popular dotfile repos on GitHub; the popular ones are complex, and it's hard to find my way around. I would have thought that using Chezmoi on both Windows and Linux is a common case, but there's little information on that. In general, Chezmoi seems focused on Unix environments, and Windows feels a bit left out, particularly in the documentation.

If there's a way for me to contribute some docs back after the problem is solved, let me know.

**Comment by bradenhilton** [comment]
https://www.chezmoi.io/reference/target-types/#scripts-on-windows

**Comment by Sjlver** [comment]
Thanks!

I've also found https://github.com/twpayne/dotfiles/blob/master/home/.chezmoiignore.tmpl, which provides a pretty nice example for how to execute scripts for one OS only.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
