### ISSUE TITLE
Add support to gopass multiline values

### ISSUE THREAD

**Issue by MiguelTVMS** [twpayne/chezmoi#3919]
## Is your feature request related to a problem? Please describe.

When using gopass integration, chezmoi passes the parameter `--password` that only retrieves the first line.
Because of that, I cannot use gopass in the template to generate my private SSH key files since only `-----BEGIN OPENSSH PRIVATE KEY----` goes to the created file.

## Describe the solution you'd like

To avoid breaking everyone using single-line passwords, add a parameter to the gopass template called `multiline` to suppress the `--password` argument on the gopass command. e.g.
```
{{ gopass multiline "$PASS_NAME" }}
```

**Comment by 4ooc** [comment]
This function [gopassRaw](https://www.chezmoi.io/reference/templates/gopass-functions/gopassRaw/) already does what you want.

**Comment by MiguelTVMS** [comment]
Thanks, it works perfectly.
