### ISSUE TITLE
On Windows only, some files written as public are detected as private

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#392]
AppVeyor Windows builds, with *exactly the same code* sometimes pass, sometimes fail. For example:

* [Build 39](https://ci.appveyor.com/project/twpayne/chezmoi/builds/25833279), following a doc change (no change to the code), passes just fine.
* [Build 40](https://ci.appveyor.com/project/twpayne/chezmoi/builds/25833284) also passes just fine.
* [Build 41](https://ci.appveyor.com/project/twpayne/chezmoi/builds/25833560), which is exactly the same change merged into `master`, fails.

The PR is based on the latest `master` and only includes documentation changes, so the build result should be the same in all cases.

Ideas as to why this is welcome.

cc @zb140, as the Windows expert :)

**Comment by twpayne** [comment]
Observations:

* All tests pass just fine on Linux/macOS.
* chezmoi uses a random temporary directory for each filesystem-related test (see https://godoc.org/github.com/twpayne/go-vfs/vfst#NewTestFS), and cleaning up afterwards.

Initial theories:

* AppVeyor is re-using VMs and random number seeds too aggressively, which seems unlikely.

It's more likely that the implicit assumptions in chezmoi's test suite are not valid on Windows, but I've no idea where the problem is. Input appreciated.

**Comment by zb140** [comment]
I'll be happy to take a look, but I'm traveling this week. I'm sure I'll have time to look at it at some point, but I'll probably be a little slower to get things done than I have been in the past.

**Comment by twpayne** [comment]
Of course, no rush. I know you're volunteering your time. Thank you so much for your contributions so far!

**Comment by twpayne** [comment]
Here is an another example of two builds of the exact same code resulting in different outcomes on AppVeyor:

* [Build 49](https://ci.appveyor.com/project/twpayne/chezmoi/builds/26539090) (fails)
* [Build 50](https://ci.appveyor.com/project/twpayne/chezmoi/builds/26539097) (passes)

AppVeyor looks unreliable. I'll remove support for it. Maybe we can use Travis for Windows CI instead.

**Comment by twpayne** [comment]
Let's try an alternative Windows CI instead, maybe Travis.

**Comment by twpayne** [comment]
It seems that this flakiness is not limited to AppVeyor. In this build, something that build just fine on Windows before failed on Windows: https://github.com/twpayne/chezmoi/runs/274062037

**Comment by twpayne** [comment]
Same problem on GitHub actions: https://github.com/twpayne/chezmoi/pull/471/checks?check_run_id=286681655

**Comment by twpayne** [comment]
I did some investigation and was able to determine why the tests are flaky, but not the underlying cause. The simplest flaky test case is `TestAddAfterModification` in `cmd/add_test.go`. The test does the following:

1. Populate a test filesystem with `~/.bashrc`.
2. Run `chezmoi add ~/.bashrc` and verify that this creates `dot_bashrc` in the source state.
3. Modify the contents of `~/.bashrc`.
4. Run `chezmoi add ~/.bashrc` again and verify that `dot_bashrc` in the source state is updated to match the new contents.

What's happening on Windows occasionally, but not on any other operating system, is that the second `chezmoi add ~/.bashrc` detects `~/.bashrc` as being a private file and therefore step four creates `private_dot_bashrc` instead of `dot_bashrc`. The test checks for `dot_bashrc`, which no longer exists, causing the test to fail.

There are two likely probable causes:

1. When the contents of `~/.bashrc` are written a second time (step 3), something is different, which causes chezmoi to write `~/.bashrc` as a private file.
2. chezmoi's method for detecting whether a file is private is flaky and/or incorrect.

**Comment by twpayne** [comment]
https://github.com/twpayne/chezmoi/pull/492 demonstrates the problem - `/home/user/.bashrc` is detected as being private on Windows whereas it should be public.

@zb140 If you have a moment to look at this issue, I'd very much appreciate your Windows expertise.

**Comment by zb140** [comment]
Great analysis! My best guess is that your probable cause #2 is the most likely culprit. Detecting private files on Windows is complicated because the native permissions are focused more on "can I read/write/etc this file right this minute given all the current relevant conditions" rather than a more straightforward "does this user have permission".

I'd be happy to have a look but I'm traveling this week due to the holiday in the US. I'll be back at my computer a week from Monday and I'll see what I can figure out.

**Comment by twpayne** [comment]
Would it make more sense to simply ignore the private/public distinction on Windows? i.e. attributes in the source state (`private_`) would be preserved, but not enforced or set in the target directory. It would be as if the public/private distinction does not exist on Windows.

**Comment by zb140** [comment]
I apologize for not getting to this sooner -- my day job got in the way and I haven't had time for side projects until today.  I've been trying various ideas all afternoon and I haven't come up with anything that works more reliably than what's already there. I believe your suggestion to preserve but not enforce privacy on Windows is probably the best path forward.  In my experience, Windows users don't often change the permissions of individual files and folders anyway, so I don't think many people will miss this feature.

**Comment by twpayne** [comment]
Thank you very much for spending time looking into this @zb140.

**Comment by zb140** [comment]
I may be slow sometimes, but I'm glad to help when I can. I find chezmoi to be a hugely useful tool, and something like 2/3 of my computers are WIndows, so I definitely have an interest in keeping it working 😃
