### ISSUE TITLE
Don't auto generate the template by default when adding files as templates

### ISSUE THREAD

**Issue by 15cm** [twpayne/chezmoi#393]
The current behavior of "adding files as templates" is quite annoying as it always modify the template although I just want to add it as it is. Should we disable the template auto generating by default and let users add a flag such as `--template-auto-generate` for it when they intend to do so?

**Comment by twpayne** [comment]
Yes, I think you're right that the autotemplating should be disabled by default.

**Comment by 15cm** [comment]
Np. Take your time for this PR.
