### ISSUE TITLE
Chezmoi with NeoVim installed with Kickstarter and Lazy as Plugin Manager

### ISSUE THREAD

**Issue by felixbello** [twpayne/chezmoi#3937]
## What exactly are you trying to do?

I have only recently started using Chezmoi with NeoVim and Lazy as a plugin manager

For config files like ".zshrc" it works like a charm!

But I've now the Issue, that I would like to use it as well for NeoVim and the Plugins.

I've NeoVim in the folder ".config/..." if I do a small config change it works with Chezmoi, but if I try to "deactive","remove" or "update" a Plugin in NeoVim, I still can add the changes with "chezmoi add .." but, changing the computer, or updating again a Plugin NeoVim gives me Errors.

## What have you tried so far?

Searched online for any recommendations, how to use it

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] general online search

## Additional context

Now my Question is, any experience with "Chezmoi in combination with Neovim installed witch Kickstarter and Lazy Plugin Manager" ?

**Comment by bradenhilton** [comment]
Can you provide a small example that demonstrates the problem?

**Comment by felixbello** [comment]
Hi @bradenhilton,

sure:

I've right now a Plugin called "which-key", which I did in the config file comment out, to not load it anymore.

I add the change to the config file to chezmoi and update the repository.

on the other computer, I update chezmoi and the config file gets updated, so the plugin "which-key" is as well not loaded anymore.

Now I want to clean up the system, as I don't want to use that Plugin anymore, so I remove the Plugin.

Once this is done, I update again chezmoi adding all the changes which where done in the path of NeoVim.

I change again the Computer and update Chezmoi.

Now on the other Computer I want to update a Plugin which is out of date, so I use Lazy to update the Plugin, and now it throws errors, is not able to Update the Plugin.

To show the Errors I post here a Screenshot, please consider, that this happens on all plugins.

If I do the updates without adding and managing with Chezmoi the updates works:

<img width="732" alt="image" src="https://github.com/user-attachments/assets/ef4fa547-5084-49cb-a2c2-eafb04089c73">

**Comment by halostatue** [comment]
I don't use nvim anymore, but I have used it in the past with chezmoi and with lazy. This should not be happening. Are you keeping the plugins *themselves* in chezmoi? That is, are you keeping the files in `~/.local/share/nvim/lazy`? If so, stop. chezmoi should not be separately managing files that are managed by lazy. (It is questionable whether the lazy lockfile should be managed or not.)
