### ISSUE TITLE
chezmoi cd - modifies (breaks) shell environment

### ISSUE THREAD

**Issue by mil1i** [twpayne/chezmoi#3943]
## Describe the bug

I'm not entirely sure how to describe this as I don't fully understand what is occurring. But running `chezmoi cd` does correctly move into my src directory, but it is modifying my shell in a way that I don't understand what it is doing.

On Windows, in PowerShell Core I am using starship.rs + zioxide. Upon issuing `chezmoi cd` it moves into my src repo but my prompt immediately gets reset to the default powershell prompt and normal commands don't work properly. I have to close and re-open my terminal to "fix" it.

On macOS, I'm on zsh + powerlevel10k + zioxide. Similar but not as noticable an issue immediately here. It moves me to my src repo, prompt stays the same and every looks normal. But it seems to modify how my terminal interacts. Typically I can press `opt+arrow` to navigate back and forth between a word but after a `chezmoi cd` some other behavior is occurring where I get the warning bell and my standard prompt rotates from `❯` to `❮` on first press then subsequent starts alarming/beeping. At this moment I don't know what it is doing when this happens. Same behavior if I disable initializing zioxide.

Obviously using `zioxide` I don't really need to utilize `chezmoi cd` and can instead just do `cd chezmoi` presuming it's hit frequently enough.

## To reproduce

Unsure if this is exactly reproducable, but all I am doing from two separate machines is running `chezmoi cd` and this behavior is occurring. Unsure if it's an issue with chezmoi + starship/powerlevel10k or just whatever command `chezmoi` is running to change dirs (perhaps entering a new login shell of some sorts?)

## Expected behavior

I expect `chezmoi cd` to just change my current working directy to that of the src repo location without modifying my shell environment in any way.

## Output of command with the `--verbose` flag

```console
❯ chezmoi --verbose cd

 ~/src/home/chezmoi  main                                                                                                                                 
❯
```

<details>

## Output of `chezmoi doctor`

```console
❯ chezmoi doctor
RESULT   CHECK                       MESSAGE
ok       version                     v2.52.2, commit Homebrew, built at 2024-09-09T23:51:42Z, built by Homebrew
ok       latest-version              v2.52.2
ok       os-arch                     darwin/arm64
ok       uname                       Darwin macbook 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64
ok       go-version                  go1.23.1 (gc)
ok       executable                  /opt/homebrew/bin/chezmoi
ok       upgrade-method              brew-upgrade
ok       config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-09-13T23:18:36-06:00
ok       source-dir                  ~/src/home/chezmoi is a git working tree (clean)
ok       suspicious-entries          no suspicious entries
ok       working-tree                ~/src/home/chezmoi is a git working tree (clean)
ok       dest-dir                    ~ is a directory
ok       umask                       022
ok       cd-command                  found /opt/homebrew/bin/zsh
ok       cd-args                     /opt/homebrew/bin/zsh
info     diff-command                not set
ok       edit-command                found ~/.local/bin/code
ok       edit-args                   code
ok       git-command                 found /opt/homebrew/bin/git, version 2.46.0
ok       merge-command               found /usr/bin/vimdiff
ok       shell-command               found /opt/homebrew/bin/zsh
ok       shell-args                  /opt/homebrew/bin/zsh
info     age-command                 age not found in $PATH
ok       gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.5
info     pinentry-command            not set
ok       1password-command           found /opt/homebrew/bin/op, version 2.30.0
ok       bitwarden-command           found /opt/homebrew/bin/bw, version 2024.8.2
ok       bitwarden-secrets-command   found ~/.local/bin/bws, version 0.2.1
info     dashlane-command            dcli not found in $PATH
info     doppler-command             doppler not found in $PATH
info     gopass-command              gopass not found in $PATH
info     keepassxc-command           keepassxc-cli not found in $PATH
info     keepassxc-db                not set
info     keeper-command              keeper not found in $PATH
info     lastpass-command            lpass not found in $PATH
info     pass-command                pass not found in $PATH
info     passhole-command            ph not found in $PATH
info     rbw-command                 rbw not found in $PATH
ok       vault-command               found ~/.local/share/mise/installs/vault/latest/bin/vault, version 1.17.5
info     vlt-command                 vlt not found in $PATH
info     secret-command              not set
```

</details>

**Comment by mil1i** [comment]
Nevermind I re-read the docs and it does say that this command does spawn a new shell. Just seems like an odd default behavior. Closing this.

**Comment by twpayne** [comment]
See https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-cd-spawn-a-shell-instead-of-just-changing-directory.
