### ISSUE TITLE
Installing on windows fails due to windows defender

### ISSUE THREAD

**Issue by luislopes-outsystems** [twpayne/chezmoi#3951]
## What exactly are you trying to do?
When I run the command 

winget install twpayne.chezmoi

windows defender deletes the installer, and then installation fails. 
I get a popup saying windows defender found a threat

I dont know how to progress or what info should I pass 
![Screenshot 2024-09-19 211348](https://github.com/user-attachments/assets/e32690dc-cbde-4e79-bc08-c3264c85e7c7)

**Comment by luislopes-outsystems** [comment]
I was able to do : winget install twpayne.chezmoi --version 2.52.1 ... at least im not blocked

**Comment by twpayne** [comment]
This is probably a bug in Windows Defender. See https://go.dev/doc/faq#virus.

If chezmoi's or winget's release process is compromised please share as much information publicly as you can.

cc @azinsharaf for https://github.com/twpayne/chezmoi/security/advisories/GHSA-ch94-qf3q-3p6m. I added a security doc update in https://github.com/twpayne/chezmoi/commit/f84b8e5ca2d59ba59cb5af7ca6f4430d0486d5a2.

**Comment by twpayne** [comment]
Refs https://github.com/twpayne/chezmoi/commit/f84b8e5ca2d59ba59cb5af7ca6f4430d0486d5a2.

Note that I just added this commit, and that several other people have reported that Windows Defender claims to have found the same trojan.

If chezmoi's release process is compromised, let's talk about it publicly.

**Comment by halostatue** [comment]
Just FYI, https://github.com/twpayne/chezmoi/security/advisories/GHSA-ch94-qf3q-3p6m is not accessible to the public (for good reasons), but it also doesn't appear to be accessible to repository collaborators (not that I’m likely to be able to assist with this as I don't have Windows available).

**Comment by twpayne** [comment]
Yeah, unfortunately there seems to be no mechanism in GitHub Security Advisories to make them public but not accepted, even for my own repo. I'll disable GitHub Security Advisories as they seem pretty useless.
