### ISSUE TITLE
Windows Defender on Windows 11 reported chezmoi winget package as infected by Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by Lockszmith-GH** [twpayne/chezmoi#3952]
Most likely a false positive.

I've downloaded the winget package on Sept 10th.
I just now got the Defender error - which means the detection is based on some updated test in it's database.

![image](https://github.com/user-attachments/assets/9106e962-fc36-4ccb-aa80-2da943e6f28e)

I've retrieved chezmoi.exe from quarantine, and submitted it to VirusTotal - [link to results](https://www.virustotal.com/gui/file/b63dd6f408952207889d5d06df489a37bbd9a5d840f71412d7d3a6b28fc07a2c) - all clear right now.

Probably a bug with Windows Defender's most updated thread definitions, but important to report nontheless for tracking.

**Comment by twpayne** [comment]
Dup of #3951.
