### ISSUE TITLE
Not working in certain directory?

### ISSUE THREAD

**Issue by Kevin-Mok** [twpayne/chezmoi#396]
I can't seem to figure out the reason why the program seems to have stopped working in a certain directory for me for whatever reason. Specifically, `~/.config/i3`. It's not noticing any difference in the template file from my source directory.

## Things I Tried
- deleting the file from the source directory, adding it from the target directory and changing it again
  - doesn't detect any difference
- looking in `chezmoi dump` for the file
  - can't be found
- try adding a simple file in a another directory to see if it can find and apply changes
  - it does
- varying pre-built/self-compiled versions of `chezmoi`
- ensuring that all the permissions for the directories and files are the same
- ensuring the components are "ok" in `chezmoi doctor`
- using a fresh clone of my dotfile repository

I'm completely at a loss as to what made it stop working. What am I doing wrong?

**Comment by twpayne** [comment]
What's the output of `chezmoi doctor`?

Could you post the contents of your source directory, particularly the contents of `dot_config/i3`?

**Comment by Kevin-Mok** [comment]
```
> chezmoi doctor
warning: version dev, commit unknown, built at unknown
     ok: /home/kevin/linux-config (source directory, perm 700)
     ok: /home/kevin (destination directory, perm 755)
     ok: /home/kevin/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/nvim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.22.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.16)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
warning: vault (Vault CLI, not found)
```

[i3 config.](https://github.com/Kevin-Mok/linux-config/blob/master/dot_config/i3/config.tmpl)

**Comment by Kevin-Mok** [comment]
Woops... I had a faulty if statement in my `.chezmoiignore`.
