### ISSUE TITLE
Add per-file config for file changes when run `chezmoi apply`

### ISSUE THREAD

**Issue by chuxubank** [twpayne/chezmoi#3969]
## Is your feature request related to a problem? Please describe.

I'm always frustrated when using `chezmoi apply`,
I did not change anything, but I have some config like
```conf
[nutstore]
type = webdav
url = https://dav.jianguoyun.com/dav/
vendor = other
user = chuxubank@qq.com
pass = {{ pass "Personal/Nutstore/rclone" | output "rclone" "obscure" }}

[rpi]
type = sftp
host = raspberrypi.local
pass = {{ "123456" | output "rclone" "obscure" }}
```
for rclone.
The `rclone obscure` will *digest* the password, but each execution will get different output.
I do not want the file's change suspend the execution of `chezmoi apply`
<img width="918" alt="image" src="https://github.com/user-attachments/assets/7d024e7d-73ea-4a14-86a7-644398a83344">

## Describe the solution you'd like
If a per-file config or a file name rule is applied to that file, do not ask questions about the changes but just do the action.
I do not want use `-f` option because it's dangerous and may loss modifications on other files. 

## Describe alternatives you've considered
Add a `.chezmoiforce` or something that indicate the files we want to overwrite.

**Comment by halostatue** [comment]
Put the `obscure`d values in your `.chezmoi.toml.tmpl` and use them as data values. Alternatively, do something like `{{ pass "Personal/Nutstore/rclone-obscured" }}`. It means that when you update the `rclone` password for `Nutstore` you would need to also update `rclone-obscured`, and then run `chezmoi init`, but that gives you something that will report differences less frequently (more or less; it may report that the config has updated).

I don't really have any other suggestion for this because the output is nondeterministic.

**Comment by chuxubank** [comment]
Thanks for the suggestions, it will work but not the way I want.
My thoughts is add a prefix for the file name
Before:
`~/.local/share/chezmoi/dot_config/rclone/private_rclone.conf.tmpl`
After:
`~/.local/share/chezmoi/dot_config/rclone/overwrite_private_rclone.conf.tmpl`

It's really a big change but could have more usecases?

**Comment by halostatue** [comment]
Not sure as I don't use cmm. Bypassing it with a script is not recommended. I don't see adding an `overwrite_` flag as something that is likely to be implemented. It's extremely niche and should probably not be applied to *most* files.

**Comment by chuxubank** [comment]
I then achieve this with 
https://www.chezmoi.io/user-guide/manage-different-types-of-file/#manage-part-but-not-all-of-a-file
Just ignore the input and convert it a to a `modify_` script.
Before:
~/.local/share/chezmoi/dot_config/rclone/private_rclone.conf.tmpl
After:
~/.local/share/chezmoi/dot_config/rclone/modify_private_rclone.conf
Finally:
```
{{- /* chezmoi:modify-template */ -}}
[nutstore]
type = webdav
url = https://dav.jianguoyun.com/dav/
vendor = other
user = chuxubank@qq.com
pass = {{ pass "Personal/Nutstore/rclone" | output "rclone" "obscure" }}

[rpi]
type = sftp
host = raspberrypi.local
pass = {{ "123456" | output "rclone" "obscure" }}
```

@halostatue Thanks for the quick reply!
