### ISSUE TITLE
Builtin age doesn't work

### ISSUE THREAD

**Issue by KapJI** [twpayne/chezmoi#3980]
## Describe the bug

From docs (https://www.chezmoi.io/user-guide/encryption/age/#builtin-age-encryption):
```
chezmoi has builtin support for age encryption which is automatically used if the age command is not found in $PATH.
```

I configured `age` to be installed via `.chezmoiexternal.toml`:
```toml
[".local/bin/age"]
    type = "archive-file"
    url = "https://dl.filippo.io/age/latest?for=linux/amd64"
    path = "age/age"
    executable = true
    refreshPeriod = "168h"
```

But `czm apply` fails with:
```console
$ czm apply
chezmoi: .config/zsh/config.d/work.zsh: exec: "age": executable file not found in $PATH
```

`externals` files are processed in order of target names, that's mentioned in docs. I guess I can put age to `.bin` to make it work, although I'd like keep binaries where they are currently. And ideally remove dependency on age completely from my setup.

`chezmoi age` doesn't work here either but I guess this is expected, although a bit confusing:
```console
$ chezmoi age decrypt dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: only passphrase encryption is supported
```

**So is it no longer supported and docs are outdated or something is broken here?**

## To reproduce

With `age` uninstalled:
```console
$ chezmoi decrypt --verbose dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: exec: "age": executable file not found in $PATH
```

Adding `--use-builtin-age on` doesn't show any errors:
```console
$ chezmoi --use-builtin-age on --verbose decrypt dot_config/zsh/config.d/encrypted_work.zsh.tmpl.age
chezmoi: exec: "age": executable file not found in $PATH
```

age config in `.config/chezmoi/chezmoi.toml`:
```toml
encryption = "age"

[age]
    identity = "~/.config/chezmoi/key.txt"
    recipient = "age1p6n7pr73yfxysh8qjty4guhfea9gqgh7uwk8w6e3wx7r9eqqw4sqeg4r9g"
```

Tested on Linux (x64), Mac (arm64) and Windows (x64).

## Expected behavior

Builtin age is used.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.52.3, commit c136cd0324b46d311427eaf8ebff3d4532effbb1, built at 2024-09-30T09:03:56Z, built by goreleaser
warning   latest-version              v2.52.4
ok        os-arch                     linux/amd64 (CentOS Stream 9)
ok        uname                       Linux hostname 5.19.0-0 #1 SMP Fri Jan 1 12:00:00 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
ok        go-version                  go1.23.1 (gc)
ok        executable                  ~/.local/bin/chezmoi
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-10-10T06:52:17-07:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /usr/bin/nvim
ok        edit-args                   /usr/bin/nvim
ok        git-command                 found /usr/local/bin/git, version 2.43.5
ok        merge-command               found /usr/bin/nvim
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.3.3
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

**Comment by twpayne** [comment]
> So is it no longer supported and docs are outdated or something is broken here?

Is `age` actually in your `$PATH`? It looks like you install it in `~/.local/age`. Did you mean to install it in `~/.local/bin/age`?

**Comment by KapJI** [comment]
> It looks like you install it in ~/.local/age
Sorry, this is typo after changing it back and forth. I tested `~/.local/bin/age` correctly. And it's installed as expected if I run `chezmoi apply -i externals`.

My point is that before `age` is installed builtin age should be used instead (as it's said in the docs).

Looking at the code I can see that here for some reason `c.Encryption` is set to an empty string. Although in my config you can see that `encryption = "age"` is set:
https://github.com/twpayne/chezmoi/blob/bf2ccfe0e981261ce5d3fd42e6c56b4215c03606/internal/cmd/config.go#L2467

If I force it to "age" then builtin age is used.

**Comment by KapJI** [comment]
Ok, I found why. Basically this is because I got used yaml configs and thought that indentation matters. I had this:

```toml
[data]
    value = "something"
    
 encryption = "age"
 
 [age]
    identity = "..."
    recipient = "pubkey"
 ```
 
 With this `encryption` is part of `[data]` map, not global. It'd be nice to show some warning if `[age]` map is present but `encryption` is not set. Because not working builtin age is the only side effect I noticed from bad configuration.

**Comment by twpayne** [comment]
Thanks for the further investigation.

chezmoi already uses age encryption if you've configured it but not set `encryption`:

https://github.com/twpayne/chezmoi/blob/bea13383eec62e8a61444b4d9b6cbf6282056621/internal/cmd/config.go#L2478-L2488

**Comment by KapJI** [comment]
Yes, and that what caused this issue.

Basically if it decides to use age because age config is present, it doesn't respect built-in age anymore. Therefore this error.

What I would do:
1. Add check if built-in age should be used when age config is present.
2. Don't fail but show warning if encryption is empty but age or gpg configs are present. This looks like misconfiguration and may happen if user copied encryption config from docs to the end of their chezmoi.toml.

I can submit a PR if you agree with any of these.

**Comment by twpayne** [comment]
Sounds good. A PR would be very welcome:)
