### ISSUE TITLE
`chezmoi edit <file>` doesn't open source file when <file> is a symlink 

### ISSUE THREAD

**Issue by peterlobster** [twpayne/chezmoi#399]
I have a bad habit of getting frustrated at my home directory when I forget exactly what folder goes to a whatever program (I'm sure we've all been there). Naturally, I've been using GNU Stow for a really long time to handle my stuff and my concern; but I have my own fair share of grievances with GNU Stow that Chezmoi seems to handle quite nicely.

So after a lot of tweaking, I think I can modestly get what I want using...
```bash
$ chezmoi add ~/.bashrc $(readlink ~/.bashrc)
```
Which you suggested in https://github.com/twpayne/chezmoi/issues/167#issuecomment-457652243

Like most people using Stow, I had a folder called, `.dotfiles` where I kept all my stuff in separate directories. To start the move, I've renamed `.dotfiles` to `.files` and 're-stowed' everything. Now when I run the above-mentioned command (with the addition of `-T`, cause I use the `.chezmoi.os` variable to switch off the macOS specific parts of the configuration), I have the source `.bashrc` file put into `.local` -> `share` -> `chezmoi` -> `dot_files` -> `bash` -> `executable_dot_bashrc.tmpl` and the symlink in `.local` -> `share` -> `chezmoi` -> `symlink_dot_bashrc`. This also works for my `.bashrc.d` directory. I've attached a picture for reference...

![Screen Shot 2019-07-31 at 5 13 00 PM](https://user-images.githubusercontent.com/38382145/62256554-89dea380-b3b6-11e9-8eed-920339c47edf.png)

**So far I haven't been having any problems, except when I run `chezmoi edit .bashrc` my editor opens up the symlink file, as opposed to following the link to open the source file. Would there be a way to address, or is this just the way it's gonna be?** 

![Screen Shot 2019-07-31 at 5 16 43 PM](https://user-images.githubusercontent.com/38382145/62256667-070a1880-b3b7-11e9-8f4b-c373e46c32a3.png)

_I can edit the file just file by navigating to it and then applying the changes, so it's really not super critical._

**Comment by peterlobster** [comment]
@twpayne Also `chezmoi forgot` and `chemoi remove` only remove the `symlink_dot_*`; so I have to manually remove the sources files. However, templates, variables, and everything else I tested work fine.

**Comment by twpayne** [comment]
This is working as intended. Unlike GNU Stow, chezmoi writes normal files, not symlinks. You can simulate GNU Stow-style symlinks with chezmoi, but you'll run in to the exact issues that you describe here.

There's a shorthand for adding files that are managed as a symlink:

    chezmoi add --follow ~/.bashrc

This will assume that `~/.bashrc` is a symlink to a file containing the desired contents, and add those contents to the source state directly. When you next run `chezmoi apply`, the `~/.bashrc` symlink will be replaced with a normal file with the desired contents.

**Comment by peterlobster** [comment]
@twpayne Understood, but correct me if I'm wrong, that I'd the organization aspect of the `.files` directory because they would 'atomically' matched 1:1 from the root of `.local/share/chezmoi/`; correct?

**Comment by peterlobster** [comment]
To add insight, what I've been doing is recreating my folder structure, but only committing the core files (i.e., `.bashrc`, `.gitconfig`, etc...) to git. I'm using `.gitignore` extensively to be able to still use the `chezmoi` functionality with my files but only track the important ones. I'm also using `.chezmoiignore` to build my files according to the several conditionals and my `.chezmoi.toml.tmpl`. 

So, I don't know if I'm way too far out of that park here, but so far I seem to be have been getting the best of both worlds; with those couple of expectations.
