### ISSUE TITLE
`chezmoi edit` doesn't handle case insensitive path

### ISSUE THREAD

**Issue by KapJI** [twpayne/chezmoi#3990]
## Describe the bug

`chezmoi edit` cannot open file on Windows with case insensitive path on NTFS.

## To reproduce

In Powershell on Windows:
```console
~ $ echo "test" > ~\Documents\Powershell\test.txt

~ $ chezmoi add ~\Documents\Powershell\test.txt

~ $ chezmoi git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        home/readonly_Documents/PowerShell/test.txt

nothing added to commit but untracked files present (use "git add" to track)

~ $ chezmoi edit ~/Documents/Powershell/test.txt
chezmoi: ~/Documents/Powershell/test.txt: not managed

~ $ rm ~/Documents/Powershell/test.txt

~ $ chezmoi status
 A Documents/PowerShell/test.txt
```

Correct folder name is `PowerShell`. File is added successfully but `edit` fails with `not managed`.

## Expected behavior

`chezmoi edit` successfully opens file.

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.52.3, commit c136cd0324b46d311427eaf8ebff3d4532effbb1, built at 2024-09-30T09:03:56Z, built by goreleaser
warning   latest-version              v2.52.4
ok        os-arch                     windows/amd64
ok        systeminfo                  Microsoft Windows 11 Enterprise (10.0.22621 N/A Build 22621)
ok        go-version                  go1.23.1 (gc)
ok        executable                  ~/.local/bin/chezmoi.exe
ok        upgrade-method              replace-executable
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-10-12T12:26:25+01:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        cd-command                  found C:/Program Files/PowerShell/7/pwsh.exe
ok        cd-args                     pwsh.exe
info      diff-command                not set
ok        edit-command                found C:/Program Files/Neovim/bin/nvim.exe
ok        edit-args                   'C:\\Program Files\\Neovim\\bin\\nvim.exe'
ok        git-command                 found C:/Program Files/Git/cmd/git.exe, version 2.46.2
ok        merge-command               found C:/Program Files/Neovim/bin/nvim.exe
ok        shell-command               found C:/WINDOWS/system32/cmd.exe
ok        shell-args                  'C:\\WINDOWS\\system32\\cmd.exe'
info      age-command                 age not found in $PATH
info      gpg-command                 gpg not found in $PATH
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

**Comment by KapJI** [comment]
Looks like this is intentional?

https://www.chezmoi.io/developer-guide/architecture/#path-handling
> chezmoi is case-sensitive internally and makes no attempt to handle case-insensitive or case-preserving filesystems.

I find current behaviour that some commands may work while other fail a bit incosistent but it's up to you of course.

It would be nice to lookup lowercased file tree to find the closest match in case of `not managed` error and show "maybe you meant this" message.

**Comment by KapJI** [comment]
Another case where chezmoi wants to add paths with different names to what they were on filesystem:
```console
$ mkdir ~\Documents\TestDir

$ echo "test" > ~\Documents\testdir\test.txt

$ chezmoi add ~\Documents\testdir\TesT.txt

$ chezmoi git status
Untracked files:
        home/readonly_Documents/testdir/

$ ls .\.local\share\chezmoi\home\readonly_Documents\testdir

Directory: .\.local\share\chezmoi\home\readonly_Documents\testdir


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---        10/12/2024   7:50 PM              6 TesT.txt

$ rmdir ~\Documents\TestDir

$ chezmoi status
DA Documents/testdir
DA Documents/testdir/TesT.txt
```

**Comment by halostatue** [comment]
Minor correction: NTFS and APFS are case-preserving and handle Unicode encoding and folding differently (at one point, NTFS used a bastardized UCS-2 that could act almost like UTF-16; I think that APFS uses NKFD whereas everyone else uses NKFC for composite characters). That makes full case insensitivity fairly difficult and prone to errors, especially when you add git's handling (or lack thereof) of case to the mix.

**Comment by twpayne** [comment]
Yeah, there's simply no way to handle Windows paths sensibly. In Windows, the same file has thousands of different filenames: not just case sensitivity and case non-preserving filesystems, but also short and long filenames, UNC paths, network drives, etc. etc.

So, this will not be worked on.

**Comment by halostatue** [comment]
See also golang/go#17084, closed seven years ago as something that won't be implemented.

**Comment by KapJI** [comment]
> Yeah, there's simply no way to handle Windows paths sensibly. 

I understand the complexity involved, but I think it’s worth addressing the common cases, which would cover the vast majority of real-world use cases. Handling all edge cases perfectly isn’t necessary to provide meaningful improvement for users.

> In Windows, the same file has thousands of different filenames

I'm aware of the intricacies of Windows paths, but it's a finite number of cases, and I believe we can handle the most reasonable scenarios well, while maintaining the current behavior for more exotic cases.

I've developed a prototype that manages case-preserving paths on Windows in a way that seems to work well. Here's the link:

https://gist.github.com/KapJI/82ce1f47b78c6c2bc4287022d41c4975

This implementation supports:

1. Absolute and relative regular paths
2. Relative paths from current folder with disk drive (e.g, `C:project/file.txt`)
3. Relative paths from current disk (e.g, `/Windows/System.ini`)
4. Short DOS 8.3 paths (e.g, `C:\PROGRA~1\`)
5. Local UNC paths
6. Network UNC paths
7. Paths longer than MAX_PATH (260 characters)
7. Expands `~` when the shell doesn't

Documentation: https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats

I recognise this logic is complex, but if you're open to the idea, I can publish it as a separate library. I also think it's possible to find a reasonable solution for MacOS.

> See also golang/go#17084, closed seven years ago as something that won't be implemented.

That discussion was more about defining the behavior, but for their case, a solution could be as simple as using [`GetFinalPathNameByHandleW`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew).

**Comment by twpayne** [comment]
Thanks for the gist, but to be honest I've already lost days of my life to Windows path handling and have no wish to lose more.

[chezmoi's current behavior](https://www.chezmoi.io/developer-guide/architecture/#path-handling) is simple and - most importantly - predictable, and chezmoi is targeted at power users who are able to understand case sensitivity.



> I've developed a prototype that manages case-preserving paths on Windows in a way that seems to work well.

Note that chezmoi needs unambiguous bidirectional path mapping, i.e. it needs to map paths in the source directory to paths in the destination direction (e.g. when running `chezmoi apply`) as well as in the reverse direction (e.g. when running `chezmoi add`).

Note also that on Linux and macOS at least (and maybe on Windows as well, I'm not sure) you can have different filesystems with different behaviors mounted in different subdirectories of your home directory. On Windows it's not just NTFS: the user's home directory might be a Samba share on some Solaris/ZFS server. There is no way that you can assume that paths behave in a certain way with respect to case handling, and some subdirectories might behave differently to others.

> I recognise this logic is complex, but if you're open to the idea, I can publish it as a separate library.

If you're keen to pursue this, then I recommend proposing an addition to [Go's `path/filepath` package](https://pkg.go.dev/path/filepath). If it gets accepted there, then we can consider whether it is even possible to use it in chezmoi. Due to the requirement for unambiguous bidirectional path mapping, I suspect that it won't be, but I can be persuaded by working code with exhaustive tests.

In the short term, it's simpler and clearer for users to use the shift key when needed.

**Comment by halostatue** [comment]
> Note also that on Linux and macOS at least (and maybe on Windows as well, I'm not sure) you can have different filesystems with different behaviors mounted in different subdirectories of your home directory. On Windows it's not just NTFS: the user's home directory might be a Samba share on some Solaris/ZFS server. There is no way that you can assume that paths behave in a certain way with respect to case handling, and some subdirectories might behave differently to others.

This is correct for Windows as well, through junction points.

This is even more complex because individual folders on modern Windows systems can be marked as case-sensitive: <https://www.thewindowsclub.com/enable-case-sensitive-attribute-folders>

TIL.

**Comment by KapJI** [comment]
Thank you for detailed answer.

> the user's home directory might be a Samba share on some Solaris/ZFS server. There is no way that you can assume that paths behave in a certain way with respect to case handling, and some subdirectories might behave differently to others.

> individual folders on modern Windows systems can be marked as case-sensitive

That's true, but just to be fair, if you take a look at the implementation I linked, it doesn't make any assumptions about filesystem case sensitivity. Instead, it queries the OS, which is aware of all these details and handles them accordingly.

> [chezmoi's current behavior](https://www.chezmoi.io/developer-guide/architecture/#path-handling) is simple and - most importantly - predictable

I agree that it's simple, but I believe some of the examples I showed above are only predictable if you're familiar with specific implementation details mentioned in the developer documentation. For instance, when chezmoi renames files because they were added with incorrect names to the source tree, this behaviour might not be intuitive to all users.

> chezmoi is targeted at power users who are able to understand case sensitivity.

I consider myself a power user, but I spent a non-trivial amount of time figuring out the "not managed" error I mentioned in the issue description. It’s not intuitive that the same path can be used for `chezmoi add` but not for `chezmoi edit`. Mistakes happen and I think it would be great if the software could help by either showing a more meaningful error message or fixing such mistakes automatically.

> Note that chezmoi needs unambiguous bidirectional path mapping

I'm not proposing making chezmoi case-insensitive internally. My suggestion is to improve the path normalisation for `ExtPath` provided by users. Of course, there are still cases which can't be covered by this feature, like when the source tree already contains incorrectly named files or when paths differ between systems. However, I believe the proposed behaviour is more reasonable and user-friendly compared to the current handling in such cases.

> I recommend proposing an addition to [Go's path/filepath package](https://pkg.go.dev/path/filepath).

I don't think this functionality would be a good fit for the standard library. The `path/filepath` package aims to provide basic cross-platform abstractions, while this functionality is highly specific to case handling on different filesystems and OS-level queries.

**Comment by KapJI** [comment]
Another example where current behaviour is not great. On MacOS:

```
$ chezmoi add --template .config/zsh/.zshrc
$ chezmoi add .config/zsh/.Zshrc
$ echo "line1" >> $(chezmoi source-path)/dot_config/zsh/dot_zshrc.tmpl
$ echo "line2" >> $(chezmoi source-path)/dot_config/zsh/dot_Zshrc
$ chezmoi status
 M .config/zsh/.Zshrc
 M .config/zsh/.zshrc
```

That could be ok if user messed up with source tree structure manually but I think `chezmoi add` should be able to handle this better. And `chezmoi status` should show "inconsistent state" error in this case, like it does if there are mutiple versions of the same file with different attributes.

**Comment by twpayne** [comment]
> Another example where current behaviour is not great. On MacOS:

Are you using case-sensitive APFS or case-insensitive APFS? The example you give behaves differently on these two different file system configurations.

**Comment by KapJI** [comment]
This is default case-insensitive APFS. On case sensitive variant second `chezmoi add` fails as expected:
```console
$ chezmoi add .config/zsh/.Zshrc
chezmoi: lstat .config/zsh/.Zshrc: no such file or directory
```

**Comment by halostatue** [comment]
> > I recommend proposing an addition to [Go's path/filepath package](https://pkg.go.dev/path/filepath).
> 
> I don't think this functionality would be a good fit for the standard library. The `path/filepath` package aims to provide basic cross-platform abstractions, while this functionality is highly specific to case handling on different filesystems and OS-level queries.

I think that where both @twpayne and I disagree with you is that this is *exactly* something that should be handled at the stdlib OS abstraction level if it's going to exist. Java provides `getCanonicalPath()`, Rust provides `std::fs::canonicalize()`, and C++ provides `std::filesystem:canonical()` — but *none* of these does case folding (the Windows functions for canonicalization might) and they both resolve symlinks (which could move the canonical filename *outside* of a place where chezmoi could manage it).

Go has chosen not to provide such a function, which means that we would either be depending on a dependency that may not support all of the chezmoi target platforms or have to support such code ourselves. I *personally* did my time with cross-platform filesystem shenanigans when I was working for a backup company and don't want to deal with it again.

BTW, chezmoi uses absolute target paths as keys in the state database, so it cannot see that `~/.config/zsh/.Zshrc` and `~/.config/zsh/.zshrc` are the same file on macOS.
