### ISSUE TITLE
docs: `.chezmoidata/` is undocumented

### ISSUE THREAD

**Issue by sysadmiral** [twpayne/chezmoi#3991]
## Describe the bug

This isn't a code bug but the documentation for `.chezmoidata/` is missing. It's mentioned on other pages but there's no explicit documentation like there is for `.chezmoitemplates/`.

![image](https://github.com/user-attachments/assets/7ae97775-de8b-4bc7-9cd0-0b6b3ab1f181)

## To reproduce

Go to https://chezmoi.io/reference and scroll down to "Special files and directories".

## Expected behavior

There is documentation for the `.chezmoidata/` directory available.

**Comment by twpayne** [comment]
Great spot, thanks! Would you like to submit a PR for this? No worries at all if not.

**Comment by sysadmiral** [comment]
> Great spot, thanks! Would you like to submit a PR for this? No worries at all if not.

Yes I'd be happy to! Leave it with me and I'll get it done before the end of the week.

**Comment by KapJI** [comment]
It's actually mentioned on `.chezmoidata.<format>` page: https://www.chezmoi.io/reference/special-files-and-directories/chezmoidata-format/
