### ISSUE TITLE
Templating with `.chezmoidata`

### ISSUE THREAD

**Issue by Ra2-IFV** [twpayne/chezmoi#3998]
## Is your feature request related to a problem? Please describe.

I was trying to move some templates under `[data]` from `.chezmoi.toml.tmpl` to `.chezmoidata`.
`.chezmoidata.SUFFIX` doesn't support templating.

## Describe the solution you'd like

Templating `.chezmoidata.SUFFIX`.

## Describe alternatives you've considered

```
{{ if condition -}}
{{ $foo := "bar" }}
{{ end -}}

chezmoi_is_good = "{{ $foo }}"
```
I have to use them multiple times if I need them in different files.

## Additional context

No... Should be clear enough

**Comment by twpayne** [comment]
This would cause a cyclic dependency. `.chezmoidata` is read before templates are executed. Dup of #3526.

**Comment by Ra2-IFV** [comment]
Is there a place like discussion group or forum to answer my stupid thoughts or questions? I'm getting quite deep into chezmoi but also confused about it. I don't want to do spams like this ...

**Comment by halostatue** [comment]
There are [discussions](https://github.com/twpayne/chezmoi/discussions) here I chezmoi.

**Comment by Ra2-IFV** [comment]
Okay okay... Thanks for your patience
