### ISSUE TITLE
`chezmoi init` does not respect existing `.chezmoiroot` for `includeTemplate`

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#4002]
> Inside `.chezmoiroot` is `home`, and there is `home/foobar.tmpl`.  
If I use `{{ includeTemplate "foobar.tmpl" }}` in`home/.chezmoi.toml.tmpl`, chezmoi will report:
> 
> `executing "chezmoi.toml" at <includeTemplate "foobar.tmpl">: error calling includeTemplate: open ~/.local/share/chezmoi/foobar.tmpl: no such file or directory`
even if I put it in the `home/.chezmoitemplates` directory. I have to use this instead:
`{{ includeTemplate "home/foobar.tmpl" }}`
> 
> This line works in other template files. I guess it's a bug?
>
> _Originally posted by @Ra2-IFV in https://github.com/twpayne/chezmoi/discussions/4001_

I can confirm this behaviour. Adding `fmt.Printf("%#v\n, searchDirAbsPaths)` at `internal/cmd/tempaltefuncs.go:275` produces the following results:

```console
$ go run . execute-template --init '{{ includeTemplate "programs.tmpl" . }}'
[]chezmoi.AbsPath{"/Users/austin/.local/share/chezmoi/home/.chezmoitemplates", "/Users/austin/.local/share/chezmoi/home"}
{"alacritty":"alacritty",…,"zoxide":"zoxide"}⏎       
$ go run . init
[]chezmoi.AbsPath{"/Users/austin/.local/share/chezmoi/.chezmoitemplates", "/Users/austin/.local/share/chezmoi"}
chezmoi: template: chezmoi.toml:1:17: executing "chezmoi.toml" at <includeTemplate "programs.tmpl">: error calling includeTemplate: open /Users/austin/.local/share/chezmoi/programs.tmpl: no such file or directory
exit status 1
```

This obviously would *not* work in the case of a bare init, but in the reinit case, it *could* work. Note that using `home/templatename` *does not* work in the normal case even though it works in the `init` case. I'm not sure what the fix should be.

**Comment by twpayne** [comment]
I added a test case for this in #4022, but the test passes. Presumably there's something wrong with the test. Can you have a look at #4022 and spot what is missing?

**Comment by twpayne** [comment]
Thanks for reporting! #4022 should fix it.

Under the hood, I suspect there are more bugs related to `.chezmoiroot`, but I'll open a separate PR to fix these.
