### ISSUE TITLE
Template function `include` should support tilde slash (`~/`) as the beginning of a path

### ISSUE THREAD

**Issue by LoHertel** [twpayne/chezmoi#4005]
## Is your feature request related to a problem? Please describe.

According to the [documentation of the  `include` templating function](https://www.chezmoi.io/reference/templates/functions/include/), I could do the following:
* relative path:  `{{ include "dot_gitconfig" }}` will load content from file `/home/user/.local/share/chezmoi/dot_gitconfig`
* absolute path: `{{ include "/home/user/.gitconfig" }}` will load content from file  `/home/user/.gitconfig`

I would like to include a path to the current user's home directory without having to explicitly state the absolute path, but instead use a path like `~/.gitconfig`.

But `{{ include "~/.gitconfig" }}` currently produces the following error:
```
<include "~/.gitconfig">: error calling include: open /home/user/.local/share/chezmoi/~/.gitconfig: no such file or directory
```

Why do I need this?  
I would like to check whether the gitconfig has changed and rerun a script by including `{{ include "~/.gitconfig" | sha256sum }}` as comment.

## Describe the solution you'd like

`{{ include "~/.gitconfig" }}` should be evaluated as  `/home/user/.gitconfig`.

## Describe alternatives you've considered

Using the absolute path, which includes the specific user name, is not very scalable.
I would need to do something like this as workaround, which looks ugly:
```
{{ include (cat .chezmoi.homeDir "/.gitconfig" | nospace) | sha256sum }}
```

## Additional context

When asking GitHub Copilot, how to rewrite the function in `internal/cmd/templatefuncs.go`, it suggests this, which might not be the best solution (I don't know Go):
```diff
func (c *Config) includeTemplateFunc(filename string) string {
+	if strings.HasPrefix(filename, "~/") {
+		homeDir, err := os.UserHomeDir()
+		if err != nil {
+			panic(err)
+		}
+		filename = filepath.Join(homeDir, filename[2:])
+	}
+
	searchDirAbsPaths := []chezmoi.AbsPath{c.SourceDirAbsPath}
	contents, err := c.readFile(filename, searchDirAbsPaths)
	if err != nil {
		panic(err)
	}
	return string(contents)
}
```

**Comment by halostatue** [comment]
This is not required and does not work well for Windows users. Use this instead:

```
{{ include (joinPath .chezmoi.homeDir ".gitconfig") }}
```

**Comment by twpayne** [comment]
> When asking GitHub Copilot

Please never ever post LLM-generated content to this repo or any other of my repos. It is of such low quality that it generates more work than it saves. If you post LLM-generated content again I will ban you.
