### ISSUE TITLE
Template function `quote` doesn't work for pointers

### ISSUE THREAD

**Issue by KapJI** [twpayne/chezmoi#4007]
## Describe the bug

`quote`, `squote` and `quoteList` return quoted pointer value instead of quoted string this pointer points to.

## To reproduce

```
{{- $release := (gitHubLatestRelease "sharkdp/bat").Assets | first -}}
Name: {{ $release.Name }}
Name quote: {{ $release.Name | quote }}
Name quoteList: {{ list $release.Name | quoteList }}
Name type: {{ $release.Name | kindOf }}
```
Prints:
```
Name: bat-musl_0.24.0_amd64.deb
Name quoted: '0xc000a841b0'
Name quoteList: ["0xc00078ad80"]
Name type: ptr
```

## Expected behavior

`{{ $ptr | quote }}` returns quoted `{{ $ptr }}`. In the meantime `"{{ $ptr}}"` can be used as a replacement.

## Additional context

I know that `quote` is coming from `sprig`, `quoteList` [is first party](https://github.com/twpayne/chezmoi/blob/35df0684e172ae0d7f8504bb004584e40df38b52/internal/cmd/templatefuncs.go#L406) though. `sprig` is not very well supported and this behaviour can be very confusing for chezmoi users. I guess that's one more reason to replace `sprig` with something better like proposed in https://github.com/twpayne/chezmoi/issues/2668

**Comment by halostatue** [comment]
I have confirmed this. This won't be easy to resolve, but even piping through `toString` fails. This, at a minimum, should be shored up to convert `*string` to `string` so that even if something like `$ptr | quote` won't work because of the difficulties involved, `$ptr | toString | quote` or `list $ptr | toStrings | quoteList` *absolutely* work.

**Comment by twpayne** [comment]
Thanks for reporting this. #4007 should fix it for `quote` and `quoteList` at least. [sprig's implementation of `squote`](https://github.com/Masterminds/sprig/blob/fc7fc0d6a0377bca7049c4a99e80b85f222d8caf/strings.go#L93-L101) is hilariously broken, so I don't propose to attempt to fix this.
