### ISSUE TITLE
Pipe Config Values together for Templates

### ISSUE THREAD

**Issue by RayJW** [twpayne/chezmoi#4008]
## What exactly are you trying to do?

I checked everywhere in the docs, and even in example dotfiles from different repos to see if anyone did this, and sadly so far I've been unsuccessful in my search. I'm trying to pipe data values from multiple sources together to access data values without having a bunch of if else statements.

## What have you tried so far?

I've tried a few things, all of which were unsuccessful so far. To set the stage, let's say I have my `.chezmoidata.toml` file, which has the following layout:
```toml
[hostname]
ip_address="10.0.0.1"
```
Now I want to access that value, based on the `.chezmoi.hostname` field. I know this probably must be possible considering the amount of crazy complex things people have achieved with chezmoi, but I can't get it to work. Some of the things I tried:
- `{{ . | (.chezmoi.hostname) | .ip_address }}`
- `{{ .chezmoi.hostname | .ip_address }}`
- `{{ \. | "(.chezmoi.hostname)" | .ip_address }}`
- `{{ index. "hostname" | index.chezmoi.hostname |.ip_address }}`
- `{{ .{{ .chezmoi.hostname }}.ip_address }}`

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [X] Other, please give details. Configs of other people I found online.

## Output of any commands you've tried with `--verbose` flag

```console
❯ chezmoi --verbose execute-template '{{ . | .chezmoi.hostname | .ip_address }}'
chezmoi: template: arg1:1:15: executing "arg1" at <.chezmoi.hostname>: hostname is not a method but has arguments
```

## Output of `chezmoi doctor`

<details>

```console
❯ chezmoi doctor                                                                
RESULT    CHECK                       MESSAGE
ok        version                     v2.52.4, commit 0bd04065a9dc995dd6b2a7e1ebfe5e62dbc14923-dirty, built at 2024-10-10T21:13:26Z
ok        latest-version              v2.52.4
ok        os-arch                     linux/amd64 (Arch Linux)
ok        uname                       Linux hostname 6.11.4-4-cachyos #1 SMP PREEMPT_DYNAMIC Fri, 18 Oct 2024 23:15:24 +0000 x86_64 GNU/Linux
ok        go-version                  go1.23.2 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-10-09T10:59:47+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
ok        diff-command                found /usr/bin/nvim
ok        edit-command                found /usr/bin/nvim
ok        edit-args                   /usr/bin/nvim
ok        git-command                 found /usr/bin/git, version 2.47.0
ok        merge-command               found /usr/bin/nvim
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
ok        age-command                 found /usr/bin/age, version 1.2.0
ok        gpg-command                 found /usr/bin/gpg, version 2.4.5
info      pinentry-command            not set
info      1password-command           op not found in $PATH
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

**Comment by bradenhilton** [comment]
`{{ .hostname.ip_address }}`

**Comment by RayJW** [comment]
> `{{ .hostname.ip_address }}`

Sorry, I don't think I was clear enough. The TOML table is not called hostname, but whatever the value of `{{ .chezmoi.hostname }}` would be. So I need to pipe this value into the `{{ .hostname.ip_address }}` value. So say the hostname is desktop would mean the value of `{{ .chezmoi.hostname }}` is desktop and thus the value I want to use in a template would be `{{ .desktop.ip_address }}`, but then that value won't be correct for a different machine. Then I would like to directly use whatever the value of `{{ .chezmoi.hostname }}` is to determine the table we want to take values from inside the TOML file.

**Comment by twpayne** [comment]
`{{ (index . .chezmoi.hostname).ip_address }}`

**Comment by RayJW** [comment]
> `{{ (index . .chezmoi.hostname).ip_address }}`

That's exactly what I tried to do, thank you!
