### ISSUE TITLE
Organizing chezmoiexternals by OS

### ISSUE THREAD

**Issue by goarano** [twpayne/chezmoi#4014]
## What exactly are you trying to do?

I had a giant `.chezmoiexternals.toml.tmpl` where I installed tools on different OSs using templating if statements.
Since this file has grown too much I want to organize it better similarly to how I organize my `.chezmoiscripts`.

My idea is to have a folder structure such as the one below and use `.chezmoiignore` to ignore external files that are not meant to be installed on the local OS.
This way, I don't have to use if statements within the files.

```
.chezmoiexternals
.chezmoiexternals/zsh.toml
.chezmoiexternals/windows
.chezmoiexternals/windows/tools.toml
.chezmoiexternals/tools.toml
.chezmoiexternals/linux
.chezmoiexternals/linux/fonts.toml
.chezmoiexternals/package_managers.toml
.chezmoiexternals/unix
.chezmoiexternals/unix/tools.toml
.chezmoiexternals/darwin
.chezmoiexternals/darwin/fonts.toml
```

## What have you tried so far?

I have created the setup above, but I am struggling to add `.chezmoiignore` entries to ignore the tools for other OSs.
For example, on Linux the following rules should apply (in `.chezmoiignore`):
```
{{ if ne .chezmoi.os "darwin" -}}
.chezmoiscripts/darwin/*
.chezmoiexternals/darwin/
.chezmoiexternals/Library/
Library
{{- end }}
```

However, running `chezmoi managed` it's clear that the above entries are not working (the files below are defined in `.chezmoiexternals/darwin/fonts.toml`):
```
.chezmoiexternals/Library
.chezmoiexternals/Library/Fonts
.chezmoiexternals/Library/Fonts
.chezmoiexternals/Library/Fonts/Monaco Nerd Font Complete.ttf
.chezmoiexternals/Library/Fonts/Monaco for Powerline.otf
```

I stumbled upon this randomly when I ran `chezmoi update` and chezmoi tried to get one of these font files for Mac on Linux:
```
chezmoi: .chezmoiexternals/Library/Fonts/Monaco Nerd Font Complete.ttf: https://github.com/Karmenzind/monaco-nerd-fonts/raw/master/fonts/Monaco%20Nerd%20Font%20Complete.ttf: 404 Not Found
```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [x] Other, please give details.

## Additional context

It is possible that the font files mentioned above won't actually end up in the `$HOME/Library` folder, however it seems that chezmoi does some sort of processing and/or downloading of these files anyway, although they are/should be ignored.

Is there a way to ignore certain chezmoiexternal files using `.chezmoiignore` or is this not supported?
If not, how could I separate the files for specific OSs without using if statements?

Thanks in advance!

**Comment by twpayne** [comment]
> Is there a way to ignore certain chezmoiexternal files using `.chezmoiignore` or is this not supported?

This is supported, but the mechanism is different to `.chezmoiignore`.

Each `.chezmoiexternals` file is in a template, so you can selectively include files by wrapping them in an `{{ if ... }}`/`{{ end }}` block.

For example, to have `.chezmoiexternals/windows/tools.toml` only have effect on Windows, wrap it with

```
{{ if eq .chezmoi.os "windows" }}
["path/to/windows/tool"]
    type = "file"
    url = "https://whatever.com/..."
{{ end }}
```

**Comment by goarano** [comment]
So if I understand it correctly, internally chezmoi basically concats all files within `.chezmoiexternals/` into one big file for externals and then evaluates it without using the `.chezmoiignore` functionality, right?

In the meantime I have found a post stating that you can add a `.chezmoiexternal` file into a subfolder of the chezmoi repo.
Is this compatible with the `.chezmoiignore` functionality?

E.g.

chezmoi files:
```
AppData/.chezmoiexternal.toml # install some windows tool
```

`.chezmoiignore`
```
{{ if ne .chezmoi.os "windows" }}
AppData # Ignore the external tool in non-windows
{{ end }}
```

**Comment by twpayne** [comment]
`.chezmoiignore` does not apply to `.chezmoiexternals`. If you want conditional externals you have to use templating.

**Comment by goarano** [comment]
For anyone with the same questions, I have done further analysis on my part and if you add a `SUBFOLDER/.chezmoiexternal.toml` file to a ignored subfolder (using an entry `.chezmoiignore`) it will indeed ignore also ignore whatever you are defining in there without the need for templating.

However, as @twpayne wrote, it is currently not possible to make this distinction within `.chezmoiexternals/` without resorting to templating.

**Comment by halostatue** [comment]
> For anyone with the same questions, I have done further analysis on my part and if you add a `SUBFOLDER/.chezmoiexternal.toml` file to a ignored subfolder (using an entry `.chezmoiignore`) it will indeed ignore also ignore whatever you are defining in there without the need for templating (as seen in my post above).

@goarano, thanks for investigating this. If you would be so kind as to consider creating a documentation PR that records this, that would be fabulous. I think that this could be a new Frequently Asked Question in Usage, something like "How do I skip some externals for some machines?". Alternatively, it could be a note in `.chezmoiexternal.$FORMAT`, but I think that the FAQ would be a better place for it now (the externals page is fairly long already and this risks being lost there).
