### ISSUE TITLE
Support Configuration file in ~/.local/share/chezmoi

### ISSUE THREAD

**Issue by rondymesquita** [twpayne/chezmoi#4031]
## Is your feature request related to a problem? Please describe.

Context
Depending on the situation, I need to have multiple configuration files and dotfiles. For that, it would interesting if chezmoi could read the configuration in the current folder running the command (working dir).

## Describe the solution you'd like

Read the configuration file in the following order. If not exist, read the next:
1. ./chezmoi.$FORMAT
2. $HOME/.config/chezmoi/chezmoi.$FORMAT

Suppose I have a folder called `mydotfiles` anywhere in my computer.
I can just enter in that folder, run the `chezmoi` command, and, by default, it tries to read the chezmoi.$FORMAT in the current folder. If not found, reads for $HOME/.config/chezmoi/chezmoi.$FORMAT.
I am aassuming that this will allow also, to have my dotfiles anywhere in my computer, not only in .local/share/chezmoi

This allow us some things:
1. Versioning the configuration file along dot files.
2. Having multiples directories in same dotfiles folder
For example:
dotfiles/mac/chezmoi.$FORMAT
dotfiles/windows/chezmoi.$FORMAT
3. Even, not need to having all dotfiles under `dotfiles` folder.
/home/foo/bar/mysettings/win/chezmoi.$FORMAT
/home/foo/bar/mysettings/win/dot_bashrc

/home/foo/bar/mysettings/mac/chezmoi.$FORMAT
/home/foo/bar/mysettings/win/dot_bashrc

## Describe alternatives you've considered
 
There is the possibility to use the `--config` flag. But I need to repeat the flag for every single command.

For versioning I can run `chezmoi add ~/.local/share/chezmoi`. But is not so straightforward for new users. 
Also, I still need to use the `--config` flag.

## Additional context

N/A

**Comment by twpayne** [comment]
No, for multiple reasons:

* The chezmoi way of handling differences between machines is templates, not different config files.
* Reading the config file from the current directory first will be confusing and tricky to debug as the behavior of chezmoi will vary depending on which directory it's run in.
* Reading the config file from `~/.local/share/chezmoi` violates the XDG Specification, which chezmoi adheres to.
