### ISSUE TITLE
Add a flag or command to delete unmanaged files on destination

### ISSUE THREAD

**Issue by 0x7375** [twpayne/chezmoi#4037]
## Is your feature request related to a problem? Please describe.

Currently, when using chezmoi across multiple machines, any files deleted from the source stay on the destination until cleaned up. This requires manually deleting every file on every machine to keep a consistent setup, which is a bit time-consuming.

## Describe the solution you'd like

Adding a flag (e.g., ```--replace/--clean```) to ```chezmoi apply/update``` to delete the files unmanaged on the destination (probably with a prompt to delete the file, unless the file is in ```.chezmoiignore```).

## Describe alternatives you've considered

Manually deleting files on each machine after removing them, which is inefficient and error-prone (when I move/rename a few files in my config, I end up with a mess on another machine).

## Additional context

The way I use chezmoi is pretty much only ```chezmoi re-add ~/.config/dir``` then ```chezmoi update``` on every other machine which is quick and convenient, until I delete a file

**Comment by twpayne** [comment]
Use [`.chezmoiremove`](https://www.chezmoi.io/reference/special-files/chezmoiremove/) for this.

**Comment by halostatue** [comment]
This also seems that the `exact_` attribute does this for contents of directories.
