### ISSUE TITLE
Differences in chezmoiexternal implementations across OS

### ISSUE THREAD

**Issue by motty-mio2** [twpayne/chezmoi#4050]
## What exactly are you trying to do?

Trying to include private git repositories in ‘chezmoiexternal’.
https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#handle-tar-archives-in-an-unsupported-compression-format

If I do not have access to the private git repository, I would like to skip it without cloning.
This is the behaviour on Linux.
However, in windows, an error occurs there and the operation is terminated.
If access fails due to using windows, lack of authorisation, etc., I want it to be skipped.

## What have you tried so far?

I created ‘chezmoiexternal’ and tested on windows and linux.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ ] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose` flag

```powershell
PS C:\Users\WDAGUtilityAccount> chezmoi apply -k --verbose
Cloning into 'C:/Users/WDAGUtilityAccount/path/to/external'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
chezmoi: ./path/to/external C:/Users/WDAGUtilityAccount/path/to/external: exit status 128
```

## Output of `chezmoi doctor`

<details>

```console
$ chezmoi doctor
```

</details>

**Comment by twpayne** [comment]
`.chezmoiexternal` files are templates, so you can exclude parts of the conditionally, for example:

```
{{ if ne .chezmoi.os "windows" }}
# only include this git-repo external on non-Windows systems
["path/to/external"]
    type = "git-repo"
    # ...
{{ end }}
```

**Comment by motty-mio2** [comment]
Thank you.
But I want to use it on Windows too.

Chezmoi In Linix
1. Some chezmoi process
2. Try to clone / pull
3. Failed to clone / pull
4. Other chezmoi process

Chezmoi In Windows
1. Some chezmoi process
2. Try to clone / pull
3. Failed to clone / pull
4. Stop chezmoi process

So, some process not run in windows

**Comment by halostatue** [comment]
Can you try with `chezmoi apply --keep-going`?

**Comment by motty-mio2** [comment]
Yes. It works!
I did wrong command option!
thank you!
