### ISSUE TITLE
Replace chezmoi's file name convention with git notes metadata

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#4061]
## Is your feature request related to a problem? Please describe.

I want to easily move between git repos in editors.  Most editors have support for this, i.e. to open recently used repositories. This means using `chezmoi edit` to start an editing session is an extra step required just for chezmoi.

I still want to be able to use editors syntax highlighting. Most editors require the file extension for this to work, since file extensions are mapped to language identifiers.

I also want to be able to list or view my repository immeditely in a terminal to see the file names so I can quickly see the file names as they are in the target directory.

I want to reduce the cognitive overload in all these instances. Both moving between repos immediately, and immediately seeing files as the map 1-to-1 between source and target state, achieves this.

## Describe the solution you'd like

Replace chezmoi's file name convention with [git notes](https://git-scm.com/docs/git-notes). It solves all key aspects of what is explained in https://www.chezmoi.io/user-guide/frequently-asked-questions/design/#why-does-chezmoi-use-weird-filenames, yet enables aspect not currently solved by the current design, as explained in the problem description.

## Describe alternatives you've considered

none

## Additional context

Git notes allow users to append metadata to commits, blobs, and trees in git without altering the original objects. This feature is highly versatile, enabling a range of applications from tracking time per commit.

I know this has been a heated discussion in the past. I wanted to add this alternate approach to at least give it a thought. I know this was raised ages ago before Mercurial was removed, but since then git is the only supported VCS. (Though other VCS's have similar functionality.)

**Comment by KapJI** [comment]
> but since then git is the only supported VCS

chezmoi doc claims it can work with other vcs than git: https://www.chezmoi.io/user-guide/advanced/customize-your-source-directory/#use-a-different-version-control-system-to-git

**Comment by thernstig** [comment]
@KapJI that is a good find, I had not seen that. That makes this hard. Closing. At least it is here for reference in the future if someone ask the same questions.

**Comment by twpayne** [comment]
As @KapJi says, chezmoi is designed to work well with git but not to require git.

My understanding is that git notes apply to git objects, like commits, whereas chezmoi needs to associate metadata with files and directories. My understanding might be incorrect, but if it is correct then the immediate problems with git notes seem to be:

* To find the metadata for a given file, chezmoi would have to search that file's commit history to find the relevant git note.
* A single git commit may touch multiple files, making it hard to determine which metadata is associated with which file, especially when renames occur (and remember that git tracks content, not renames).
* git notes do not solve the ambiguity of whether a file called `.gitconfig` is a dotfile you want in your home directory or a configuration file for git in your source state. You need to be able to support both simultaneously, with different contents for each file.



> I still want to be able to use editors syntax highlighting. Most editors require the file extension for this to work, since file extensions are mapped to language identifiers.

There are multiple third-party [editor plugins for chezmoi](https://www.chezmoi.io/links/related-software/#editor-integration) that configure syntax highlighting, even if you don't use `chezmoi edit`.



> I also want to be able to list or view my repository immeditely in a terminal to see the file names so I can quickly see the file names as they are in the target directory.

Use `chezmoi managed` (to see everything that's managed) or `chezmoi status` (to see everything that is out of sync).

**Comment by twpayne** [comment]
BTW you previously suggested using git notes in https://github.com/twpayne/chezmoi/issues/769, and there's relevant discussion there.

**Comment by thernstig** [comment]
@twpayne correct, I suggested it previously there, thanks for linking. The reason back then was that it did not scale to other SCMs, a thing I thought was removed now. 😆
