### ISSUE TITLE
Allow creating `run_` scripts that only run on an interval

### ISSUE THREAD

**Issue by macintacos** [twpayne/chezmoi#4084]
## Is your feature request related to a problem? Please describe.

I'm a bit new to `chezmoi` so apologies if this is the wrong approach.

In my previous iteration of my dotfiles, I had a script that would back up a number of packages from disparate sources (Homebrew, Cargo, npm, etc.) and shove the results into a `backup/` folder. The files in this folder could then be fed into some install scripts that I have, in case I was starting from scratch or whatever. It also just felt nice to have the "real" list of all the things I had installed, in case that ever got out of sync with whatever I had in an install script. I was reading the documentation about [scripts](https://www.chezmoi.io/user-guide/use-scripts-to-perform-actions/), and the thing that I don't really like is that while you could add the `brew install` commands to a script, it's not like it'll keep track of things that I've `brew uninstall`'d afterwards. The `backup/` solution I had is a nice safety blanket, and could be used as the "source" instead.

I don't really have a way to replicate this in `chezmoi` unless I do something like add a `backup`-style command to the end of my `run_` scripts, which feels a little overkill for me.

## Describe the solution you'd like

I'd like to have a new type of `run_` script that runs on an interval that I can set, similar to the `refreshPeriod` for external sources. The way I would imagine it working is that `chezmoi` would keep track of the last time the script was run via `apply`, and then only re-run the script after the interval has passed. The contents of the script can remain the same - the contents of it do not need to change.

## Describe alternatives you've considered

- Adding a "backup"-style command to the end of my `run_` script that is installing packages (but I backed away for this partly because of the reasoning above)
- Just creating a cronjob to do this on my own to backup the files. This feels a little icky (I kinda just want this feature instead), but if this feature request is rejected I think I'll probably try to make this work.

If there's a better way to approach this problem, I'm all ears!

**Comment by KapJI** [comment]
chezmoi supports this using templates. You need to put interval index (e.g, day, week number, etc) to comment somewhere in the script.

Docs: https://www.chezmoi.io/user-guide/frequently-asked-questions/usage/#how-do-i-run-a-script-periodically

Real example script which runs brew weekly: https://github.com/KapJI/dotfiles/blob/main/home/.chezmoiscripts/macos/run_onchange_before_11-install-homebrew-packages.sh.tmpl

**Comment by macintacos** [comment]
Ha! Thank you for that! I'll close this out in that case, sorry for the noise.
