### ISSUE TITLE
Set VScodium flatpak as default diff tool

### ISSUE THREAD

**Issue by laguill** [twpayne/chezmoi#4085]
## What exactly are you trying to do?
I would like to set vscodium flatpak as my default diff tool.
I already have an alias
```bash
# codium
alias codium='flatpak run com.vscodium.codium'
```
Here is the content of my chezmoi.toml
```
[diff]
command = "flatpak run com.vscodium.codium" # Tried also with codium
args = ["--wait", "--diff"]
```
When I run `chezmoi diff ~/.bashrc` I am getting this error
```bash
chezmoi: .bashrc: exec: "flatpak run com.vscodium.codium": executable file not found in $PATH
```
Thanks for your help

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

**Comment by KapJI** [comment]
"flatpak" is the command, everything else is args.

**Comment by twpayne** [comment]
> "flatpak" is the command, everything else is args.

Exactly. The config needs to be

```toml
[diff]
    command = "flatpak"
    args = ["run", "com.vscodium.codium", "--wait", "--diff"]
```

**Comment by laguill** [comment]
Thansk now codium is opening but I still have an error on the window
![image](https://github.com/user-attachments/assets/6527a040-ec6a-481d-b214-f28ecb3ed6b0)

Shoud I edit some filesystem variable with flatseal ? or something else ?

**Comment by halostatue** [comment]
You may want to change your command to "echo" and see what the parameters are and then try to call flatpak with that. From this point, though, it's purely a flatpak issue.

**Comment by laguill** [comment]
ok so I changed my chezmoi.toml file with
```
[diff]
    command = "echo"
    args = ["flatpak", "run", "com.vscodium.codium", "--wait", "--diff"]

```

now here is the output of `chezmoi diff`
```
flatpak run com.vscodium.codium --wait --diff /home/laguill/.bashrc /tmp/chezmoi-diff848018656/.bashrc
```
I tried to add the ~/.local/share/chezmoi to codium but without better results

**Comment by laguill** [comment]
I manually tried to diff both files and did not get any error
`flatpak run com.vscodium.codium --wait --diff ~/.bashrc ~/.local/share/chezmoi/dot_bashrc 
`

**Comment by halostatue** [comment]
Yes. `chezmoi diff` always uses a temporary file because it needs to compare the result of templating.

You will need to determine what is required to give flatpak access to the temporary file.

**Comment by twpayne** [comment]
> You will need to determine what is required to give flatpak access to the temporary file.

You can also set chezmoi's `tempDir` configuration variable to a directory that Flatpak permits VSCodium to access.

**Comment by laguill** [comment]
It seams that flatpak does not allowed `/tmp`
For cleaness or security I am not really sure see issue [flatpak#3438](https://github.com/flatpak/flatpak/issues/3438)

How do you change tempDir to `/var/tmp` ?

**Comment by twpayne** [comment]
> How do you change tempDir to `/var/tmp` ?

Put

```toml
tempDir = "/var/tmp"
```

in `~/.config/chezmoi/chezmoi.toml`. Make sure it's near the start of the file, in the top level config section.
