### ISSUE TITLE
Chezmoi diff does not show who has what change

### ISSUE THREAD

**Issue by alper** [twpayne/chezmoi#4095]
After the discussion [here](https://github.com/twpayne/chezmoi/issues/4056) which was closed I'm trying to follow the guidelines and not having a lot of luck.

`chezmoi diff` for me outputs this:

```diff
❯ chezmoi diff                                        [🕙 18 13:21] 
diff --git a/.config/zed/settings.json b/.config/zed/settings.json
index 0fbe14e039de3339d43dba3528e21e7ff3030fa1..e9fef572719bb578e554a078e7a58cdb2c9b1bbc 100600
--- a/.config/zed/settings.json
+++ b/.config/zed/settings.json
@@ -14,7 +14,9 @@   "theme": "Catppuccin Mocha",
   "buffer_font_size": 18,
   "buffer_font_family": "JetBrainsMonoNL Nerd Font",
   "file_types": {
-    "Picat": ["pi"]
+    "Picat": [
+      "pi"
+    ]
   },
```

So it's diffing the same paths against each other prefixed with `a/` and `b/`? How am I supposed to figure out which is which?

I just did `merge-all` and had already resolved all these changes, but now they're coming back again? I have absolutely no idea where they are coming from or what `merge-all` then did.

**Comment by alper** [comment]
I don't see the answer to this question here: https://www.chezmoi.io/reference/commands/diff/

But I understand what you're saying. I'll either have to paranoidly double check every change that `chezmoi` does to make sure it's moving changes in the direction that I'm expecting or reconsider my usage of this tool.

**Comment by twpayne** [comment]
Given your response, I would also recommend reading https://github.com/twpayne/chezmoi/discussions/2819.
