### ISSUE TITLE
Looking for way to conditionally have submodule or external source

### ISSUE THREAD

**Issue by inquisitev** [twpayne/chezmoi#4103]
## What exactly are you trying to do?
I work for a business where i deal with things that can be categorized as confidential. I write scripts that use the confidential stuff. 
I have setup a private-dotfiles repo that i want to pull into my public dotfiles repo provided that I my fqdnHostName matches my work computers.  I want to use the same public dotfiles on my personal computers and not pull in the private dotfiles. 

I can use submodules to pull in the private dotfiles on my work computer, thats fine, but when i try to use it on my personal computer, I am unable to get it to not try to pull the submodule
Describe in as much detail as possible.

## What have you tried so far?
I have tried to make gitmodules a tmpl
I have tried to use external files, but i would need to 'git' external type that is not available (yet?)

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

**Comment by twpayne** [comment]
> I have tried to use external files, but i would need to 'git' external type that is not available (yet?)

There is a [`git-repo` external type](https://www.chezmoi.io/reference/special-files/chezmoiexternal-format/).

However, chezmoi is designed to manage your dotfiles from a single source of truth. `.gitmodules` brings in multiple sources of truth.

I would recommend encrypting the sensitive files with age encryption and storing them in your public dotfiles repo.

**Comment by inquisitev** [comment]
ah ok, git repo seems to work fine enough. I think i am breaking a rule or two by symlinking some files to that directory since its not under the chezmoi source tree, but thats fine for me. 

Thanks!
