### ISSUE TITLE
Set `sourceDir` to a path relative to home dir?

### ISSUE THREAD

**Issue by darkfeline** [twpayne/chezmoi#4117]
## What exactly are you trying to do?

Try to set `sourceDir` to a path relative to home dir.

## What have you tried so far?

`$HOME/some/path/foobar`, `some/path/foobar`

## Where else have you checked for solutions?

* [X] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [X] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ ] Other, please give details.

## Additional context

I assume based on what I've read, tried, and https://github.com/twpayne/chezmoi/issues/323 that this isn't possible at the moment, in which case could I request this?  It seems like a generally useful feature.

**Comment by twpayne** [comment]
You should be able to do this with `~`:

```
sourceDir = "~/some/path/foobar"
```

chezmoi will expand `~` to your home directory.

**Comment by twpayne** [comment]
Hopefully this is now resolved. Please re-open if needed.
