### ISSUE TITLE
Provide scripts with the destination directory

### ISSUE THREAD

**Issue by DianaNites** [twpayne/chezmoi#4122]
## Is your feature request related to a problem? Please describe.

I'm trying to test my scripts and chezmoi in general, without clobbering my home directory or having to edit my config back and forth. This works fine normally by passing `--destination <some temp directory>`, but this is difficult to do correctly if scripts need any access to the destination directory.

chezmoi also [suggests](https://www.chezmoi.io/user-guide/include-files-from-elsewhere/#include-a-subdirectory-from-a-url) using scripts to unpack large external files, but this is also extremely difficult to do correctly without script access to the actual destination, like chezmoi itself has and uses for externals.

## Describe the solution you'd like

Scripts(via an environment variable), templates, or both should gain `.chezmoi.destDir`, which should reflect the actual final destination directory in use at runtime.

## Describe alternatives you've considered

There are three ways that the destination directory can be acquired by a script:

The current working directory for the script is set to it, *or* the first existing parent. This is too unreliable and filesystem dependent for me, and makes it too easy to accidentally clobber the wrong directory since theres no way to know if its correct.

Some scripts, due to naming, may run before directories they depend on. `_before` scripts always will, and in the event that the destination directory doesn't exist, they first run and *then* chezmoi fails because it doesnt seem to create parents itself. e.g.

```sh
> chezmoi apply -D=/home/me/not-exist-testing-dir
# `run_before` script runs with CWD `/home/me`, the first existing parent.
# This directory is clobbered if the script assumed CWD or homeDir was the destination.
chezmoi: .config: mkdir /home/me/not-exist-testing-dir/.config: no such file or directory
```

---

The destination is like any other argument also passed in `CHEZMOI_ARGS`, but re-implementing argument parsing in a bunch of scripts is more complex, silly, prone to edge case differences between go/chezmoi and whatever is being run as a script, requires the CLI to be stable, and requires additional fallback handling for it being statically set in the config.

---

It can also be accessed through `.chezmoi.config.destDir`, but because `.chezmoi.config` is "The configuration, as read from the config file", it does not account for the CLI flag.

## Additional context

edit: noticed that while `.chezmoi.config.destDir` doesn't update with the CLI, `chezmoi dump-config` and `chezmoi data` **do**.

I initially thought that this would be a suitably simple and reliable workaround, before trying it and realizing that theres no way to use this from a script without forwarding the arguments, including `--destination`, which the inability to sensibly do is the whole problem.

**Comment by twpayne** [comment]
Thanks for the thoroughly-thought-through request!

#4123 adds the `.chezmoi.destDir` template variable and `$CHEZMOI_DEST_DIR` environment variable for scripts.

The reason for not including this originally is that I hoped that dotfiles would always be relocatable in any directory, i.e. independent of the destination directory, but you're right that this is not always the case for scripts.
