### ISSUE TITLE
Ignore a file after initial deployment

### ISSUE THREAD

**Issue by wzzrd** [twpayne/chezmoi#4125]
## What exactly are you trying to do?

I want to initially deploy a kubeconfig or mc.ini file to a new machine. After that, I might want to forcefully redeploy it from the central repo, but otherwise I want to ignore any local changes by default.

Reasoning behind this is that those specific two files will have local changes based on normal usage that I will not want to overwrite from the central repo, nor adopt them into the central repo. I just want to deploy once, most of the time ignore changes, until I choose to redeploy forcefull. Hope that makes sense.

## What have you tried so far?

Normal workflow and just hit 'ignore' every time

## Where else have you checked for solutions?

* [x] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.

## Additional context

Maybe this is simply out of scope, or maybe I'm misinterpreting what is already possible. Just trying to figure this out :)

**Comment by twpayne** [comment]
For this you can use the [`create_` attribute](https://www.chezmoi.io/reference/source-state-attributes/). chezmoi will create the file if it does not already exist, otherwise chezmoi will ignore it.

**Comment by wzzrd** [comment]
Ah, see, I knew there would be something! Thanks!
