### ISSUE TITLE
`chezmoi add --recursive` adding files present in global gitignore

### ISSUE THREAD

**Issue by j-lakeman** [twpayne/chezmoi#4133]
## Describe the bug

title should be sufficient

## To reproduce

1. `chezmoi add --recursive folder`
2. e.g. `create mode 100644 folderpath/dot_DS_Store` on macOS

## Expected behavior

respect global gitignore e.g. `~/.config/git/ignore`

Awesome application nevertheless!

**Comment by halostatue** [comment]
Chezmoi uses [`.chezmoiignore`](https://www.chezmoi.io/reference/special-files/chezmoiignore/) for target ignores, not gitignore. There are many reasons for this, but it is mostly because the *purpose* of `.gitignore` and `.chezmoiignore` is different, therefore the behaviour will be different.
