### ISSUE TITLE
error on 'invalid cross-device link'

### ISSUE THREAD

**Issue by Thijxx** [twpayne/chezmoi#4143]
## Is your feature request related to a problem? Please describe.

When using chezmoi cross-device it does not error but it goes coocoo and it killed my dotfiles as well as kept me busy for 6 hours.
All command responses are blank. The silent treatment. 
No matter what you choose at apply, all local changes are gone and not backed up in any way, I learned my backups were not good enough.

## Describe the solution you'd like

An error, to the user, now only visible among many other messages when using the `--debug` flag. Please yell at me when my data is lost.

## Describe alternatives you've considered

Throwing computer out of window.

## Additional context

I don't think I actually use this cross-device, it looks like it trips over the `/tmp` path it created so I couldn't really see this coming. This also means this may be a bug and not a feature request.

```
time=2024-12-17T20:26:06.082+01:00 level=ERROR msg=Link component=system err="link /home/thijs/.local/share/chezmoi/dot_vimrc /tmp/chezmoi-edit4111376846/.vimrc: invalid cross-device link" oldPath=/home/thijs/.local/share/chezmoi/dot_vimrc newPath=/tmp/chezmoi-edit4111376846/.vimrc
```

**Comment by twpayne** [comment]
You need to provide more information. You haven't even included the output of `chezmoi doctor` or any details about your system.

**Comment by Thijxx** [comment]
> You need to provide more information. You haven't even included the output of `chezmoi doctor` or any details about your system.
  
Ah yes, sorry, I wrote the issue again so many times, in the end I forgot these details.

```
RESULT    CHECK                       MESSAGE
warning   version                     v2.55.0, built at 2024-12-02T09:09:10Z
warning   latest-version              v2.56.0
ok        os-arch                     linux/amd64 (Manjaro Linux)
ok        uname                       Linux PucSway 6.6.65-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 11 22:24:04 UTC 2024 x86_64 GNU/Linux
ok        go-version                  go1.23.3 (gc)
ok        executable                  /usr/bin/chezmoi
ok        config-file                 no config file found
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /usr/bin/vim
ok        edit-args                   /usr/bin/vim
ok        git-command                 found /usr/bin/git, version 2.47.1
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /usr/bin/gpg, version 2.4.7
info      pinentry-command            not set
ok        1password-command           found /usr/bin/op, version 2.30.3
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
ok        pass-command                found /usr/bin/pass, version 1.7.4
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

**Comment by twpayne** [comment]
Thanks for the info!

What's the output of `mount`? What command did you run that triggered the problem? The only chezmoi command that uses the `link` system call is `chezmoi edit`, and I'm not sure how editing `.vimrc` can kill your dotfiles.

**Comment by Thijxx** [comment]
The `mount` output is 3 pages long and I will not share it :D but if you need anything specific I will grep it. The tempfs is in RAM, the home directory is on an NVME partition, no encryption, just ext4.

These are probably relevant:
`/dev/nvme0n1p2 on / type ext4 (rw,noatime)`
`tmpfs on /tmp type tmpfs (rw,noatime,inode64)`

The flow was as follows:

- chezmoi init remote ....
- chezmoi edit ~/.vimrc
- chezmoi apply

here I tried to choose 'overwrite' but I don't know how, a button, the arrow keys? Maybe something is missing in my terminal, I tried to type 'overwrite' but the command returned blank while typing. So maybe at that point things were already broken.

At that point I had the remote version while I was expecting the local (edited) version.

**Comment by twpayne** [comment]
Thanks for the follow-up.



> here I tried to choose 'overwrite' but I don't know how, a button, the arrow keys?

`o`verwrite should only overwrite a single file, see https://github.com/twpayne/chezmoi/blob/3558b71471e91230ca4e87c1969c9dca62cd9b54/internal/cmd/config.go#L1084. Only typing `a`(ll-overwrite) should overwrite all your dotfiles.

Just to be clear: did you lose *all* your dotfiles or only `.vimrc` on the local machine?

Given:

> The flow was as follows:
> 
> * chezmoi init remote ....
> * chezmoi edit ~/.vimrc
> * chezmoi apply

This implies to me that `chezmoi edit` failed with the link error, but it was `chezmoi apply` (without any arguments like `--dry-run`) that overwrote your dotfiles. Could this be correct?

**Comment by Thijxx** [comment]
> Thanks for the follow-up.
> 
> > here I tried to choose 'overwrite' but I don't know how, a button, the arrow keys?
> 
> `o`verwrite should only overwrite a single file, see
> 
> https://github.com/twpayne/chezmoi/blob/3558b71471e91230ca4e87c1969c9dca62cd9b54/internal/cmd/config.go#L1084
> 
> . Only typing `a`(ll-overwrite) should overwrite all your dotfiles.
> Just to be clear: did you lose _all_ your dotfiles or only `.vimrc` on the local machine?
> 
> Given:
> 
> > The flow was as follows:
> > 
> > * chezmoi init remote ....
> > * chezmoi edit ~/.vimrc
> > * chezmoi apply
> 
> This implies to me that `chezmoi edit` failed with the link error, but it was `chezmoi apply` (without any arguments like `--dry-run`) that overwrote your dotfiles. Could this be correct?

Yes, only the file I edited was overwritten, one at a time. I don't understand how it is supposed to work, apply will sometimes push and sometimes pull?

**Comment by twpayne** [comment]
`chezmoi apply` always pushes. `chezmoi apply` never pulls.

`chezmoi apply` overwrites your dotfiles in your home directory (destination state) with the ones from `~/.local/share/chezmoi` (source state). `chezmoi apply` has a bunch of checks to make sure you're not losing changes.

**Comment by Thijxx** [comment]
Thank you for your support, these are the last things I tried, I give up and will use something else in stead.

- pacman -R chezmoi
- rm -rf ~/.config/chezmoi
- rm -rf ~/.local/share/chezmoi
- rm -rf ~/.cache/chezmoi
- pacman -S chezmoi
- chezmoi --debug init myrepo.git
- error on boltdb, error on .git in local/share, error on chezmoiroot, error on .chezmoiversion, error on .chezmoiroot
- the repo in .local/share/chezmoi looks good
- chezmoi edit ~/.vimrc
- making changes to the file, saving the file
- chezmoi diff: nothing
- chezmoi apply: nothing
- git diff in .local/share/chezmoi looks good but changes not staged
- chezmoi update: Already up to date.

**Comment by twpayne** [comment]
> * error on boltdb, error on .git in local/share, error on chezmoiroot, error on .chezmoiversion, error on .chezmoiroot

What error?

**Comment by Thijxx** [comment]
I moved to YADM but these are the errors I found in my terminal.

```
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Stat component=system err="stat /home/thijs/.config/chezmoi/chezmoistate.boltdb: no such file or directory" name=/home/thijs/.config/chezmoi/chezmoistate.boltdb
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Mkdir component=system err="mkdir /run/user/1000: file exists" name=/run/user/1000 perm=448
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Stat component=system err="stat /home/thijs/.local/share/chezmoi/.git: no such file or directory" name=/home/thijs/.local/share/chezmoi/.git
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Stat component=system err="stat /home/thijs/.local/share/.git: no such file or directory" name=/home/thijs/.local/share/.git
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Stat component=system err="stat /home/thijs/.local/.git: no such file or directory" name=/home/thijs/.local/.git
time=2024-12-17T22:06:14.067+01:00 level=ERROR msg=Mkdir component=system err="mkdir /home/thijs/.local/share/chezmoi: file exists" name=/home/thijs/.local/share/chezmoi perm=511
time=2024-12-17T22:06:14.069+01:00 level=ERROR msg=ReadFile component=system err="open /home/thijs/.local/share/chezmoi/O: no such file or directory" name=/home/thijs/.local/share/chezmoi/.chezmoiroot size=0 data=""
time=2024-12-17T22:06:14.070+01:00 level=ERROR msg=Stat component=system err="stat /home/thijs/.local/share/chezmoi/.git: no such file or directory" name=/home/thijs/.local/share/chezmoi/.git
time=2024-12-17T22:06:15.618+01:00 level=ERROR msg=ReadFile component=system err="open /home/thijs/.local/share/chezmoi/.chezmoiversion: no such file or directory" name=/home/thijs/.local/share/chezmoi/.chezmoiversion size=0 data=""
time=2024-12-17T22:06:15.618+01:00 level=ERROR msg=ReadFile component=system err="open /home/thijs/.local/share/chezmoi/.chezmoiroot: no such file or directory" name=/home/thijs/.local/share/chezmoi/.chezmoiroot size=0 data=""
```

**Comment by twpayne** [comment]
User resorted to entitlement threats. Closed.
