### ISSUE TITLE
Keepass support via go library

### ISSUE THREAD

**Issue by bakito** [twpayne/chezmoi#4148]
## Is your feature request related to a problem? Please describe.

When using secrets from keepass, it would be nice in it would work without a dependency of keepassxc-cli.
Especially when flatpak is used and a wrapper script has to be used for the cli.

## Describe the solution you'd like

Using this library github.com/tobischo/gokeepasslib could make chezmoi independent of the cli.

## Describe alternatives you've considered

Using a wrapper script for the cli with flatpak.

## Additional context

-

**Comment by halostatue** [comment]
We would need to verify that it could work with Yubikeys since a number of chezmoi users use Keepass with yubikeys. I see no mention of yubikeys in the codebase.

**Comment by bakito** [comment]
True, this seems not to be supported.

**Comment by twpayne** [comment]
I still think this is worth adding, even if it doesn't support the full range of KeepassXC functionality at the moment.

**Comment by bakito** [comment]
@twpayne I already id some first tests with the library.
Technically it works, but it's open to naming and implementation suggestions.

**Comment by twpayne** [comment]
Thanks @bakito! Let's discuss the implementation in #4149.
