### ISSUE TITLE
Add interpreter support for hooks

### ISSUE THREAD

**Issue by LeonardoMor** [twpayne/chezmoi#4151]
## What exactly are you trying to do?

I have the following file from which the local chezmoi config is generated (as explained in the documentation):
```
{{- if not (eq .chezmoi.os "windows") }}
encryption = "gpg"
[gpg]
    recipient = "leomc145@gmail.com"
    args = ["--quiet"]

[hooks.read-source-state.pre]
    command = "{{ .chezmoi.sourceDir }}/.chezmoiscripts/{{ .chezmoi.os }}/.prereqs.sh"
{{- else -}}
[hooks.read-source-state.pre]
    command = "{{ .chezmoi.sourceDir }}/.chezmoiscripts/{{ .chezmoi.os }}/.prereqs.ps1"

[cd]
    command = "C:\\Program Files\\PowerShell\\7\\pwsh.exe"

{{ end -}}
```

I can run `chezmoi init` with no issues. When I run `chezmoi apply` I get the following:
```output
❯ chezmoi apply --verbose --dry-run
chezmoi: C:/Users/leomc/.local/share/chezmoi/.chezmoiscripts/windows/.prereqs.ps1: fork/exec C:/Users/leomc/.local/share/chezmoi/.chezmoiscripts/windows/.prereqs.ps1: %1 is not a valid Win32 application.
```

The file `C:/Users/leomc/.local/share/chezmoi/.chezmoiscripts/windows/.prereqs.ps1` exists and its contents are:
```powershell
winget upgrade winget
```

This file is likely to get more complicated in the future as I have to install 1Password before doing anything else.

## What have you tried so far?

Tried setting the interpreter to `pwsh.exe` as explained [here](https://www.chezmoi.io/reference/target-types/#scripts-on-windows). It made no difference.

## Where else have you checked for solutions?

* [x ] I have read [chezmoi's user guide](https://chezmoi.io/user-guide/command-overview/), and not found the answer.
* [ x] I have searched [chezmoi's reference guide](https://chezmoi.io/reference/), and not found the answer.
* [ x] Other, please give details.

I did not find anyone with an issue like this, which is why I'm opening this issue.

## Output of any commands you've tried with `--verbose` flag

```console
chezmoi master*​
❯ chezmoi init --verbose

chezmoi master*​
❯ chezmoi apply --verbose --dry-run
chezmoi: C:/Users/leomc/.local/share/chezmoi/.chezmoiscripts/windows/.prereqs.ps1: fork/exec C:/Users/leomc/.local/share/chezmoi/.chezmoiscripts/windows/.prereqs.ps1: %1 is not a valid Win32 application.
```

## Output of `chezmoi doctor`

<details>

```console
chezmoi master*​
❯ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.56.0, commit 3558b71471e91230ca4e87c1969c9dca62cd9b54, built at 2024-12-14T20:15:02Z, built by goreleaser
ok        latest-version              v2.56.0
ok        os-arch                     windows/amd64
ok        systeminfo                  Microsoft Windows 11 Home (10.0.26100 N/A Build 26100)
ok        go-version                  go1.23.4 (gc)
ok        executable                  ~/AppData/Local/Microsoft/WinGet/Packages/twpayne.chezmoi_Microsoft.Winget.Source_8wekyb3d8bbwe/chezmoi.exe
ok        upgrade-method              winget-upgrade
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2024-12-20T18:06:36-06:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        cd-command                  found C:/Program Files/PowerShell/7/pwsh.exe
ok        cd-args                     'C:\\Program Files\\PowerShell\\7\\pwsh.exe'
info      diff-command                not set
warning   edit-command                nvim not found in $PATH
ok        edit-args                   nvim
ok        git-command                 found C:/Program Files/Git/cmd/git.exe, version 2.47.1
warning   merge-command               nvim not found in $PATH
ok        shell-command               found C:/Windows/system32/cmd.exe
ok        shell-args                  'C:\\Windows\\system32\\cmd.exe'
info      age-command                 age not found in $PATH
info      gpg-command                 gpg not found in $PATH
info      pinentry-command            not set
ok        1password-command           found ~/AppData/Local/Microsoft/WinGet/Packages/AgileBits.1Password.CLI_Microsoft.Winget.Source_8wekyb3d8bbwe/op.exe, version 2.30.3
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

My config woks well on macOS and Arch Linux.

**Comment by KapJI** [comment]
PowerShell scripts can't be executed directly on Windows. Only .exe and .bat files can be executed without interpreter (and few more less common file extensions). You need to prepend your command with `powershell`.

**Comment by bradenhilton** [comment]
If you want to be explicit, you could have something like

```text
[hooks.read-source-state.pre]
    command = "powershell" # or pwsh
    args = ["-NoLogo", "-NoProfile", "-File", "{{ .chezmoi.sourceDir }}/.chezmoiscripts/{{ .chezmoi.os }}/.prereqs.ps1"]
```

I would also probably construct the path with `joinPath`, though that is largely a preference thing.

It's worth keeping in mind that having this as a hook will mean that it is executed frequently, and PowerShell itself *can* have a relatively lengthy startup (in the hundreds of milliseconds, which can certainly add up over time).

If this starts to bother you, you can convert `.prereqs.ps1` to a `run_once_before_*` or `run_onchange_before_*` script. This approach is slightly less correct due to a few issues (notably, if a prerequisite is uninstalled after the script is executed, and the script has not been executed since this happened), but is still likely good enough in practice.

**Comment by LeonardoMor** [comment]
You're right. Just re-read [the docs](https://www.chezmoi.io/reference/target-types/#scripts), quote:

> The execution of scripts on Windows depends on the script's file extension. Windows will natively execute scripts with a .bat, .cmd, .com, and .exe extensions. Other extensions require an interpreter, which must be in your %PATH%.

Then the default interpreters are listed.

I understood that it was enough for the interpreter to be on my `%PATH%`.  It might be beneficial to state explicitly that you need to add the actual command on the config.

**Comment by halostatue** [comment]
You *might* be able to make `.ps1` files execute by adding the extension to `%PATHEXT%`, although this is probably *not* recommended: https://superuser.com/questions/1653303/enable-direct-native-running-of-ps1-files-how-to and https://superuser.com/questions/1653312/enable-direct-native-running-of-ps1-files-warnings-considerations.

**Comment by twpayne** [comment]
chezmoi's [interpreter support on Windows](https://www.chezmoi.io/reference/target-types/#scripts-on-windows) currently only applies to scripts, not to hooks. This behavior is confusing. chezmoi should use interpreters for hooks as well.
