### ISSUE TITLE
Question: How to pass custom arguments to KeePassXC function

### ISSUE THREAD

**Issue by talal** [twpayne/chezmoi#416]
Hi,

First of all, thank you for this great tool.

I use KeePassXC to store my secrets (e.g. SSH Keys). KeePassXC entries have attributes which I believe provide the same functionality as secure notes in Lastpass.

The attributes are in form of `key:value` and they can not be retrieved using the regular show command (which is what the `keepassxc` function in chezmoi provides):

```
keepassxc-cli show $database $entry
```

We need to pass an option/flag to the show command. E.g: to fetch the value of the "private-key" attribute from my entry "SSH Key", I would need:

```
keepassxc-cli show --attributes private-key $database "SSH Key"
```

Now, coming to my question:

How can I pass custom arguments to the keepassxc function?

I looked through the code and found that `keePassXCCmdConfig` struct [has a](https://github.com/twpayne/chezmoi/blob/d4355dd006177e7b41c6b203aa885d4c67b1dedf/cmd/secretkeepassxc.go#L28) `Args` field which is a string slice and it is being ultimately passed to the `runKeePassXCCLICommand` method.

Can I modify the syntax of the `keepassxc` function to pass a string like `--attributes=private-key` to achieve my desired functionality?

**Comment by twpayne** [comment]
Thank you for your kind words :)

You should be able to pass extra arguments to the `keepassxc-cli` command by adding the following to your config file ([doc](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#configuration-variables)):

```toml
[keepassxc]
  args = [ "--attributes=private-key" ]
```

Please try this and please report back here if it works or not. It should work in theory, but this has not been tested in practice, so your feedback will (positive or negative) will be very helpful.

**Comment by twpayne** [comment]
The above solution should add `--attributes=private-key` to every invocation of `keepassxc-cli`. I think it might be necessary to add different arguments to select different arguments in different situations. Give me a few minutes to come up with a PR.

**Comment by twpayne** [comment]
Thinking about this again, chezmooi [already parses key-value pairs from the output of `keepassxc-cli`](https://github.com/twpayne/chezmoi/blob/master/cmd/secretkeepassxc.go#L87-L99). The parsing likely doesn't handle `-` in keys. I suspect that this is the underlying bug. In theory, you should be able to put

```
{{ (keepassxc "SSH Key").privateKey }}
```

in your template. Let me try another PR.

**Comment by talal** [comment]
Thank you for the quick response and the PR :)

You are right that chezmoi already parses key-value pairs from the output of keepassxc-cli but the show command does not output the value of attributes, it only gives default key-value fields such as `Username`, `Password`, etc. The value of attributes can only be retrieved using `--attributes` option.

And the output of a show command with this option is just a string. For example, the regular show command would give something like:
```
$ keepassxc-cli show $database "SSH Key"
Username: talal
Password: 1234
Email: myemail@mail.com
Notes: ...
```

However, the show command with the option gives:

```
$ keepassxc-cli show --attributes private-key $database "SSH Key"
---- BEGIN SSH PRIVATE KEY ----
...
---- END SSH PRIVATE KEY ----
```

From an implementation point of view, it would make sense to allow `attribute` after the dot limiter (like you mentioned in your last comment) in the keepassxc function as they are extensions of the `entry` itself, so similar to how one would use `{{ (keepassxc "example.com").UserName }}` for UserName field which is given by the regular `show` command. For an attribute called `privateKey`, one would use `{{ (keepassxc "example.com").privateKey}}`.

chezmoi would first do a regular `show` to check if that populates its data structure if not then it will use the key and do a show command with the attribute flag and add that information to its data structure.

In fact, now that I think about this. I am not sure if using `--attributes=UserName` would work because if it does then you can make attribute the default behavior.

Give me a couple of minutes to test this out and get back to you.

For Keepass, one could use `{{ (keepassxc "SSH Key" "private-key").UserName }}`

**Comment by talal** [comment]
Okay, apparently the fields that you get from the default `show` command are also attributes and are the default ones that a KeepassXC entry has. However, user defined attributes are only shown with the explicit use of `attributes` flag.

For your reference:

This is how a default entry looks in KeepassXC app:
![Screenshot from 2019-09-07 02 07 12@2x](https://user-images.githubusercontent.com/3526562/64466895-9e7c2d00-d114-11e9-9fca-d2fccbe6fc0c.png)

This is where you define custom attributes and this is how they look:
![Screenshot from 2019-09-07 02 07 30@2x](https://user-images.githubusercontent.com/3526562/64466928-c1a6dc80-d114-11e9-8aac-7936d217fb42.png)

From a CLI standpoint:
![Screenshot from 2019-09-07 02 06 43@2x](https://user-images.githubusercontent.com/3526562/64466940-d4b9ac80-d114-11e9-992c-cea237b74b31.png)

Hopefully, this will give you a better understanding of how KeepassXC attributes work.

So essentially you can make `attributes` flag the default on the `keepassxc` function but it might effect those users who would use:
```
[keepassxc]
  args = [ "--some-other-option" ]
```

in their config files.

Again, thank you for your effort on this case, it is much appreciated :smile:

**Comment by twpayne** [comment]
Thanks for this info. Let me cogitate on it and come up with a PR in the next day or two (it's late now).

**Comment by twpayne** [comment]
#418 is a better solution: it adds a new template function `keepassxcAttribute` to avoid the complexity of making the `keepassxc`template function do multiple things.

**Comment by talal** [comment]
Thank you!
