### ISSUE TITLE
Wish: warn by default if there are differences before applying

### ISSUE THREAD

**Issue by markstos** [twpayne/chezmoi#423]
I enjoy `chezmoi` and use it regularly now. Thanks for the tool!

#### Description of issue

I have not adopted the use of use of `chezmoi edit` on a regular basis. Some tools, like Fish shell can end up adding or updating their own config files directly, so local changes outside of `chezmoi edit` are unavoidable. 

Instead, I edit my dot files directly and use `chezmoi diff` and then `add`, `apply` or `merge` to resolve differences.

Today I ran `chezmoi update` for the first time, not realizing beforehand that it would `apply` by default. I might have lost of some changes-- I'm not sure.

`apply` or `update` could be made safer with some kind pre-check to see if there are changes. I'm not sure which options which would best. Some warning signs there have been local changes:

 * Before a `pull`, does `chezmoi diff` show a change?
 * Has the local file changed since the most recent Git commit was created?

A more formal solution might also be possible: When `apply` updates all the files, also write out an inventory file that contains SHAs of each file written out by chezmoi.

The next time `apply` runs, check to see if the SHAs still match. If not, the file has been modified outside of `chezmoi`.

Whatever the mechanism, `chezmoi` could become "safe by default" by stopping an `apply` if any local changes are detected. Options could be presented to view or merge the differences or force the application.

**Comment by twpayne** [comment]
Another great idea @markstos! I will implement it when I have time.

**Comment by GabrielDuarteM** [comment]
Was about to suggest that. As @markstos said, some tools automatically add stuff to your configs, and I lost some of them due to an `apply` I made later. Checking for diffs before every `apply` would be really nice to avoid those cases.

**Comment by lunik1** [comment]
I did this more often than I would like to admit :). Adding this snippet to your `.zshrc` or `.bashrc` (other shells untested) should stop chezmoi from overwriting any changes when `chezmoi apply` is run
```bash
# Don't let 'chezmoi apply' overwrite changes
chezmoi() {
  if [[ "$1" == apply ]] && [[ $(command chezmoi apply -n -v "${@:2}") ]]; then
    printf "This would overwrite changes! Aborting!\n"
  else
    command chezmoi "${@}"
  fi
}
```
A couple of limitations:
- It won't work if there are flags between `chezmoi` and `apply`
- It won't protect you from `chezmoi edit --apply` etc.

Hope it's useful! Would love to have this check built-in.

**Comment by lunik1** [comment]
If you use zsh here is a snippet you can add to your `.zshrc` to make sure any changes made by `chezmoi apply` are manually confirmed.
```zsh
# Ask before applying changes with chezmoi
chezmoi() {
  changes=$(command chezmoi apply -n -v --color "on" "${@:2}")
  if [[ "$1" == apply ]] && [[ ! -z "${changes}" ]]; then
    printf "${changes}\n"
    if $(read -q "?Apply changes? [y/N] "); then
      command chezmoi "${@}"
    fi
    printf "\n"
  else
    command chezmoi "${@}"
  fi
}
```
A couple of limitations:
- It won't work if there are any flags between `chezmoi` and `apply`
- It won't save you from overwriting changes with `chezmoi edit --apply`

Hope it's useful! I would like to see something like this added to chezmoi proper, too.
