### ISSUE TITLE
wish: chezmoi status

### ISSUE THREAD

**Issue by markstos** [twpayne/chezmoi#424]
I keep expecting `chezmoi status` to exist.

Parallel to `git status`, it would work like a condensed version of `chezmoi diff` to only list files that that differ between source and target. 

Ideally, it would also tell me:

  * If there any patches to push or pull
  * When source and target files differ, which one has newer modifications.

**Comment by twpayne** [comment]
This is a great idea, and, as you say, ties in very nicely with #423.

I'm not sure when I'll get time to implement this (hopefully sometime in the next few weeks), but it will definitely get done.

**Comment by astorath** [comment]
It would also be nice to have `git ls-files` alternative as an option for `chezmoi status`. We can then be able to use it's output in completion scripts.
