### ISSUE TITLE
Add symlink support for apply and diff command

### ISSUE THREAD

**Issue by kraml** [twpayne/chezmoi#425]
Currently there is no symlink support for the apply and diff commands. This causes problem for files added by the "add --follow" command, as the apply and diff commands always thought the file does not exist and ask to create a new (regular) file.

Could you please consider fixing this?

**Comment by twpayne** [comment]
The `add --follow` command is a shortcut to help people migrate from symlink-based systems, like GNU Stow. chezmoi itself prefers you to use regular files and directories (although you can re-create GNU Stow-style symlinks if you really want).

Say `~/.bashrc` is a symlink to the "real" `.bashrc`:

```
$ ls -l ~/.bashrc
lrwxrwxrwx 1 user group 1 Sep 16 11:40 .bashrc -> somedir/real_bashrc
```

There are two ways to add this: a plain `add` or an `add --follow`.

If you use a plain `add` then chezmoi will record that you want `~/.bashrc` to be a symlink to `somedir/real_bashrc`. The next time you run `chezmoi apply` then chezmoi will do nothing as `.bashrc` is already in this state.

If you use `add --follow` then chezmoi will record that you want `~/.bashrc` to be a normal file with the same contents as `somedir/real_bashrc`. The next time you run `chezmoi apply` it will replace the symlink with a normal file with these contents.

Does this make sense?

**Comment by kraml** [comment]
Yes I understood how `add --follow` works and what it's meant for.

> If you use `add --follow` then chezmoi will record that you want `~/.bashrc` to be a normal file with the same contents as `somedir/real_bashrc`. The next time you run `chezmoi apply` it will replace the symlink with a normal file with these contents.
> 
And here is the part that I would like to have a solution for. What I'm asking is to have the `--follow` option for `apply` and `diff` also, so they will not replace the symlinked file by a regular one.

My use case is some files under my home are symlinked to other places so that they are shared by different environments: WSL, msys, native Windows. I just need to maintain a true one and others are symlinked to it.

**Comment by twpayne** [comment]
Thank you for the further details - they are very helpful.

I think #430 should fix this. It makes `--follow` a global option (that you can also set in your configuration file), and also applies to the `apply` and `diff` commands, as you requested.

If you can test this, that would be awesome.

**Comment by twpayne** [comment]
Fixed with #430.

**Comment by kraml** [comment]
I would like to test but where can I find the binary?

**Comment by twpayne** [comment]
I'll push a new version for you now (v1.6.4). Please check the [releases page](https://github.com/twpayne/chezmoi/releases) in about 15 minutes.

**Comment by kraml** [comment]
I've tested 1.6.4 and yes it works perfectly in my case now.

Kudos to you and chezmoi!

**Comment by twpayne** [comment]
Great! Happy to hear! Thanks for your kind words :)
