### ISSUE TITLE
How should docs be packaged?

### ISSUE THREAD

**Issue by daurnimator** [twpayne/chezmoi#427]
I'm the maintainer of the archlinux package ([see build process here](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/chezmoi)).
I noticed today that the `docs` command doesn't work

```
$ chezmoi docs --verbose
chezmoi: stat /home/docs/REFERENCE.md: no such file or directory
```

How should the documentation be packaged with chezmoi?

**Comment by twpayne** [comment]
Thanks for your work @daurnimator!

The docs get packaged in the chezmoi binary using [packr2](https://github.com/gobuffalo/packr/blob/master/v2/README.md). To enable this, `packr2` needs to be run as part of the build process. This means:

1. The `packr2` tool needs to be installed ([example from `Makefile`](https://github.com/twpayne/chezmoi/blob/master/Makefile#L48)).
2. `packr2` needs to be run before `go build` ([example from `Makefile`](https://github.com/twpayne/chezmoi/blob/master/Makefile#L37)).

Once this is done, the `chezmoi docs` command should work.

Note that the [`go generate ./...` step](https://github.com/twpayne/chezmoi/blob/master/Makefile#L36) is not strictly required as those particular generated files (mainly help texts) are already checked into the chezmoi's git repo. packr2 needs special treatment though.

Please let me know if this solves the problem.

**Comment by twpayne** [comment]
While I have your attention, would it be possible to add the commit hash, version number and build timestamp to the binary in the AUR package? Currently running `chezmoi --version` with the Arch Linux package prints:

```
chezmoi version dev, commit unknown, built at unknown
```

The easiest way to achieve this would be to use the pre-built binaries from [the releases page](https://github.com/twpayne/chezmoi/releases), and this would also solve the docs packaging problem described in this issue. If you need a specific build for Arch Linux (I note that the `PKGBUILD` script includes a few extra flags to `go build`) then I would be very happy to generate Arch-specific binaries as part of chezmoi's release process.

Another option would be to add AUR support to goreleaser, see https://github.com/goreleaser/goreleaser/issues/641.

Please let me know what would work best for you.

**Comment by twpayne** [comment]
Here's a `PKGBUILD` file that uses the pre-built binary:

```sh
# Maintainer: Daurnimator <daurnimator@archlinux.org>
# Contributor: Tom Payne <twpayne@gmail.com>
# Contributor:  <godeater@gmail.com>

pkgname=chezmoi
pkgver=1.6.3
pkgrel=1
pkgdesc="Multi-machine dotfile management system"
arch=('x86_64')
url='https://github.com/twpayne/chezmoi'
license=('MIT')
depends=('glibc')
source=("https://github.com/twpayne/chezmoi/releases/download/v${pkgver}/chezmoi_${pkgver}_linux_amd64.tar.gz")
sha256sums=('49067b8f932800c9ec476ad51915b6e2d6f5f29c09606d5f3930b1f98a877517')

package() {
  install -D "$pkgname" "$pkgdir/usr/bin/$pkgname"

  install -Dm644 completions/chezmoi-completion.bash "$pkgdir/usr/share/bash-completion/completions/chezmoi"
  install -Dm644 completions/chezmoi.fish "$pkgdir/usr/share/fish/vendor_completions.d/chezmoi.fish"
  install -Dm644 completions/chezmoi.zsh "$pkgdir/usr/share/zsh/site-functions/_chezmoi"

  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

**Comment by daurnimator** [comment]
pre-built binaries are a huge no-no for nearly all distributions: you always want to build from source on a trusted machine.



> Another option would be to add AUR support to goreleaser, see [goreleaser/goreleaser#641](https://github.com/goreleaser/goreleaser/issues/641).

The AUR is not involved here: AUR is repository of arch-user submitted package builds. chezmoi is now in "community", which is one of the officially supported repositories.

-----------------

I'll need to sit down and look at this on the weekend.

**Comment by daurnimator** [comment]
I would prefer to ship docs under `/usr/share` than have them bundled into the binary. Could you provide a build option to just let me embed a path for `chezmoi docs` to 'cat'?

**Comment by twpayne** [comment]
Sure, I can add a build flag to disable embedding the docs and read them from the filesystem instead if needed. What's the reason for not having both embedded docs and docs in `/usr/share`?

**Comment by daurnimator** [comment]
> would it be possible to add the commit hash, version number and build timestamp to the binary in the AUR package?

  - commit hash... no; because I download your release tarball: I don't clone your git repository
  - version number yes.
  - build timestamp no: that would be against the reproducible build principle. I could insert e.g. the timestamp of your newest modified file instead? though I don't really know what value that would add.

**Comment by twpayne** [comment]
The reason for including the commit hash and build timestamp is to assist debugging when a user reports a problem - it's very useful to know exactly what version their using.

Taking the timestamp of the newest modified file sounds good.

For the commit hash, I propose to add a file to the release tarball called `COMMIT.txt` containing the git commit hash at which the release was build. Could you then use this as the commit hash in the binary you build?

**Comment by daurnimator** [comment]
Why would you need the release commit? Isn't the knowledge that it was built from the (e.g.) 1.6.3 tag enough?

**Comment by twpayne** [comment]
The commit is useful when people build chezmoi themselves - they might build at an untagged version, e.g. the latest `master`, although I agree that it is not required when you know the the source is built at a tagged version, as is the case for Arch packages. My suggestion for `COMMIT.txt` won't work because the source tarballs are built by GitHub, not by chezmoi's release automation. So, as you suggest, let's not include the commit hash in the binary in the Arch package.

I'm adding a build flag to disable embedded docs now. I'll add you as a reviewer on the PR when it's ready.

**Comment by twpayne** [comment]
OK, #431 is now merged and I've tagged version `v1.6.5`. The release automation takes about 15 minutes to run, so all the tarballs should be available very soon.

**Comment by daurnimator** [comment]
Thanks, 1.6.5 now uploaded to arch.

**Comment by twpayne** [comment]
Great, thank you very much for your work @daurnimator :)
