### ISSUE TITLE
Can't run chezmoi source-path within script

### ISSUE THREAD

**Issue by schrej** [twpayne/chezmoi#433]
###### I did all the troubleshooting

I'm struggling with running chezmoi within chezmoi. I need to retrieve the chezmoi source path within my script. I used to retrieve it by running `sourcedir=$(chezmoi source-path)` and it worked until recently. Now that command just hangs forever while running `chezmoi apply`. If I run `chezmoi source-path` in a second terminal, it hangs until I terminate `chezmoi apply`.
Were there any changes that now only allow one chezmoi instance to execute in parallel?

It might also be an issue with my system, but I'm out of ideas.

#### Command that failed

```
chezmoi -v apply
```

#### Output of command with `--verbose`
It outputs my script, which contains `sourcedir=$(chezmoi source-path)`, then hangs.

#### Output of `chezmoi doctor`
Only missing a few password manager executables.

#### Output of `chezmoi --version`
```
chezmoi version 1.6.5, commit 3733485a2e018dfe174423c5c58edd6d03f0e3c6, built at 2019-09-20T12:17:47Z
```

**Comment by twpayne** [comment]
Interesting!

> Were there any changes that now only allow one chezmoi instance to execute in parallel?

Not explicitly. The only interaction between chezmoi instances should be through the BoltDB database (where chemzoi records which run-once scripts it has already run), but this has been in place since May and should be safe for concurrent use, and is not used by the `source-path` command anyway.

I just tested this bug my macOS system, and get the same behavior as you (i.e. it hangs). I'll investigate in more detail this evening.

**Comment by twpayne** [comment]
Just did one more test: chezmoi is blocking when opening the BoltDB database in the second process. [BoltDB locks the database](https://github.com/etcd-io/bbolt/blob/master/db.go#L216-L226) while it is opened in read-write mode.

chezmoi needs to fix how it opens the database: it should use read-only mode by default, and only use read-write when running `apply` in non-dry-run mode. I'll look again this evening.

**Comment by twpayne** [comment]
Thanks for the investigation. My rough plan is:

* open the database in read-only mode by default.
* if writing is needed (only when running `apply`) then close the read-only database and open a read-write database.

This will prevent concurrent runs of `apply` if you're using run-once scripts, but everything else should be able to run concurrently.

Are there any flaws in this plan?

**Comment by schrej** [comment]
I started to fix it myself. My approach is to extend the PersistentState struct with `Open(write bool) error` and `Close() error`, only open the database when required (aka. during `(*TargetState) Apply()` (in read-only when DryRun is true) and close it afterwards.
