### ISSUE TITLE
sprig is outdated

### ISSUE THREAD

**Issue by martin2250** [twpayne/chezmoi#436]
so sprig is constrained to an old version by [go.mod](https://github.com/twpayne/chezmoi/blob/master/go.mod#L9). This means it's missing the concat function for lists. I tried building with the latest version of sprig and it worked fine, so please update go.mod (if there is no compelling reason not to do so that I'm not seeing) :)

Cheers,
Martin

**Comment by twpayne** [comment]
Thanks for raising this @martin2250. I've updated the version of sprig in #437. Are you OK with using your own build of chezmoi for now, or do you need a new official release?

**Comment by martin2250** [comment]
Sure thing. On that note, thanks for publishing chezmoi!

Yeah, a new release would be great. Though I'll manage a few days if there are some other changes you'd like to include.


One more thought: Variables can't leave templates, so my understanding is that there is currently no way to define variables inside a .chezmoitemplates/ file and use them in other files. My use case would be to essentially include the  local config file inside a template that checks for the hostname and user. Do you think it would be a good idea to make it possible for variables to leave templates?
(a possible way to implement this would be to have a directive to copy the text from a template into another template, kind of like #include in the C preprocessor, before the outer template is parsed)

**Comment by twpayne** [comment]
> Do you think it would be a good idea to make it possible for variables to leave templates?

The template system is `text/template` from Go's standard library, and I don't want to change its behavior in any way, so whatever `text/template` does with respect to variables escaping templates, that's what you get.

Note that you can define template values in your config file (`~/.config/chezmoi/chezmoi.toml`) in the `data` section, and these values are available in all templates.

Could you give an example of your use of `.chezmoitemplates/` that would require variables to leave templates? Maybe we can find an alternative approach.

**Comment by martin2250** [comment]
My use case would be to add the values from `~/.config/chezmoi/chezmoi.toml` to VCS as well, essentially setting global variables based on eg. the hostname. I could do that by using `.chezmoi.<format>.tmpl`, but then I'd have to delete and re-generate this file every time I want to change something.

One alternative approach could be a second `.chezmoi.<format>.tmpl` (or a whole folder of such files), that gets evaluated for every `chezmoi apply`. Something like this:

`~/.local/share/chezmoi/.chezmoi/monitors.toml`
```
[data/monitors]
{{ if eq .chezmoi.hostname "my-PC" }}
  monitors = ["HDMI-1", "HDMI-2"]
{{ else if eq .chezmoi.hostname "my-Laptop" }}
  monitors = ["eDP-1"]
{{ else }}
  monitors = []
{{ end }}
```

and access it like this in any template
```
{{ .monitors }}
```

**Comment by twpayne** [comment]
If you have a file called `~/.local/share/chezmoi/.chezmoitemplates/monitors.tmpl` containing the `[data/monitors]` section above, you can access it in any other template with

	{{ template "monitors.tmpl" }}

I think this is what you want to achieve.

**Comment by martin2250** [comment]
Does this allow me to access the variables from that template? eg.

```
{{ template "monitors.tmpl" }}
...
{{ if ge ( len .monitors ) 1 }}
    ...
{{ end }}
```

**Comment by twpayne** [comment]
No, you can't access variables from the template, only its output.

Why not make `monitors` a variable in your chezmoi config file? Then it will be available in all your templates.

**Comment by martin2250** [comment]
Because the contents of the config file are not in VCS. And if I use `.chezmoi.<format>.tmpl`, changes are only propagated if the config file does not exist yet.

This would serve two purposes:
- machine specific config is also backed up (and when setting up a new machine, I can just copy together the config from my old machines)
- it's possible generate additional global variables based on the contents of the config file and hostname etc.

**Comment by twpayne** [comment]
OK, thanks for the explanation. The use case makes sense.

Here's what I propose:

If a file called `.chezmoidata.<format>` exists in the source directory (where format is one of `json`, `toml`, `yaml`, etc.) then the structured data in it is available under `.` in templates. For example, if `.chezmoidata.toml` contains:

```toml
[hosts]

	[hosts.my-PC]
    	monitors = [ "left", "right" ]

	[hosts.my-Laptop]
    	monitors = [ "primary" ]
```

then, for example, you can use the following in your templates:

```
numMonitors = {{ len ((index .hosts .chezmoi.hostname).monitors) }}
```

This way you can stored `.chezmoidata.<format>` in version control and have its data available in all templates.

How does this sound?

**Comment by martin2250** [comment]
Yes, that would definitely be a good addition, but IMO it would lead to a lot of overhead in each file that uses the variables (at least in this use case) for each time the 'monitors' variable is accessed.

Also, perhaps more importantly, it wouldn't be as flexible as having the proposed `.chezmoidata` file interpreted as a template itself. Eg if a variable should not only depend on the hostname but also the user name. And if such an additional dependency is introduced when a lot of files already use that variable, every one of these files would need to be changed instead of only `.chezmoidata`.

**Comment by twpayne** [comment]
I'd like to keep things as simple as possible. If we make `.chezmoidata.<format>.tmpl` a template, then the flow starts to look like:

1. Data is collected from the system and the config file.
2. `.chezmoidata.<format>.tmpl` is evaluated as template.
3. The resulting file is then parsed as a JSON/YAML/TOML file.
4. The result of the parsing is then added to the template data.
5. The target state templates are evaluated as a template with the updated data.

This is way too complex to be justifiable.

**Comment by martin2250** [comment]
Too bad, but I can get behind your reasoning. Anyhow, a regular `.chezmoidata.<format>` is still useful.

**Comment by twpayne** [comment]
> Yes, that would definitely be a good addition, but IMO it would lead to a lot of overhead in each file that uses the variables (at least in this use case) for each time the 'monitors' variable is accessed.

For info, templates can define and reuse variables, so you can do:

```
{{- $monitors := (index .hosts .chezmoi.hostname).monitors -}}
numMonitors = {{ len $monitors }}
```

This means that the awkward variable access only needs to happen once per file.
