### ISSUE TITLE
Additional syntax for ease of use

### ISSUE THREAD

**Issue by skupfer** [twpayne/chezmoi#439]
It would be great if chezmoi made a better use of the underlying versioning system.

i.e. currently you have to do the following:
```
chezmoi add .dotfile
chezmoi cd
git add dot_bashrc
git commit -m "Add .bashrc"
git remote add origin https://github.com/username/dotfiles.git
git push -u origin master
exit
```

But it could look more like this:
```
chezmoi add .dotfile -c "commit message"
chezmoi push
```
or
```
chezmoi add .dotfile
chezmoi commit
chezmoi push
```

As you can see there are less commands involved and this would be more intuitive instead of having to "chezmoi cd" into the chezmoi home dir and using the VCS commands separately while having a program (chezmoi) available which could do it on its own.

In case you don't want to combine your existing commands with the VCS commands or still want to have the additional stage before adding the files to the VCS I have a suggestion:
I.e. `chezmoi add <file>` would become `chezmoi include <file>`, thus not interfering with the VCS-like syntax:
```
chezmoi include .dotfile
chezmoi cd
git add dot_bashrc
git commit -m "Add .bashrc"
git remote add origin https://github.com/username/dotfiles.git
git push -u origin master
exit
```

**Comment by skupfer** [comment]
@jhamfler

**Comment by twpayne** [comment]
Thanks for the suggestion :)

A related suggestion is #413, with a work-in-progress PR in #432.

Note that chezmoi already has the [`source` command](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#source-args) to run VCS commands in the source directory, so the suggested `chezmoi commit` can be written as:

    chezmoi source commit

I don't want to break backwards compatibility by changing the behavior of the `add` command, but we can add flags and/or configuration variables.

I propose to update #432 with three configuration variables:

`autoadd`: if set, `git add` changed files to the git index after any change to the source directory through the chezmoi command (e.g. after `add`, `edit`, or `remove`).

`autocommit`: if set, `git commit` with an automatically-generated message after any change the source directory.

`autopush`: if set, run `git pull --rebase && git push` after any change to the source directory.

How does this sound?

**Comment by twpayne** [comment]
`autoCommit` and `autoPush` are [now stable and documented](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#automatically-commit-and-push-changes-to-your-repo) which I think covers the feature requested here.
