### ISSUE TITLE
[Usage] Checking if I understand chezmoiignore use 

### ISSUE THREAD

**Issue by webframp** [twpayne/chezmoi#440]
Hey 👋 

This tool is exactly what I've been looking for to update my dotfiles management. As I work through converting I wondered if I understand this right. If I have a `.chezmoiignore` like this in my source repo:

```
README.org
{{- if ne .chezmoi.os "linux" }}
.Xcompose
.xinitrc
.Xmodmap
.xmonad
.Xresources*
{{- end }}
{{- if ne .chezmoi.os "darwin" }}
Brewfile
.yabairc
.skhdrc
{{- end }}
```

Then, for example, the `.xinitrc` will only be managed on linux and the `Brewfile` would only be managed on macOS ?

**Comment by twpayne** [comment]
Yes, your understanding is correct :)

The double negative ("ignore these files if the OS is not Linux") is a bit weird/confusing I acknowledge. I would be very interested to hear of better ways to achieve the same. Please re-open this issue if needed.
