### ISSUE TITLE
whish: support for gopass

### ISSUE THREAD

**Issue by CrystalMethod** [twpayne/chezmoi#444]
It would be highly appreciated to support `gopass` in addition to `pass`. I simply created a symlink with `ln -s gopass pass`. But it's probably more convenient to configure the executable.

https://www.gopass.pw/

**Comment by CrystalMethod** [comment]
Reading carefully often helps..

**Comment by twpayne** [comment]
I think you can set the `pass.command` configuration variable to achieve this. Please tell me if this doesn't work.

[link](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#configuration-variables)

**Comment by CrystalMethod** [comment]
Yes, thanks.

Using TOML...
```toml
[pass]
command = "gopass"
```
...or YAML...
```yaml
pass:
        command: gopass
```
