### ISSUE TITLE
Running scripts fails in Termux

### ISSUE THREAD

**Issue by fbartels** [twpayne/chezmoi#445]
Hi, I am currently reorganising my dotfiles and your program provides a really nice base for this. I have especially the handling of secrets. After implementing a few things in a clean home dir I now wanted to merge this with some dotfiles I have in termux on my tablet. Applying changes to files works, but bit I cannot execute scripts that are part of the repository. 

#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

Running scripts via the run_ macro fails in Termux (Linux env for Android) with `no such file or directory`.
 

#### Command that failed

```
chezmoi apply
```

#### Output of command with `--verbose`

```
u0_a248@localhost:~$ chezmoi apply --verbose
#!/bin/bash

set -o errexit
set -o nounset

echo "Installing some basic packages"

sudo apt update && sudo apt full-upgrade

chezmoi: fork/exec /data/data/com.termux/files/usr/tmp/868183141.install_10base.sh: no such file or directory
u0_a248@localhost:~$ /bin/bash
u0_a248@localhost:~$ exit
exit
```
Running the script directly in the source dir succeeds (both with `./script` and `bash script`) 

#### Output of `chezmoi doctor`

```
u0_a248@localhost:~/.local/share/chezmoi$ chezmoi doctor
     ok: version 1.6.5, commit 3733485a2e018dfe174423c5c58edd6d03f0e3c6, built at 2019-09-20T12:17:54Z
     ok: /data/data/com.termux/files/home/.local/share/chezmoi (source directory, perm 700)
     ok: /data/data/com.termux/files/home (destination directory, perm 700)
     ok: /data/data/com.termux/files/home/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /data/data/com.termux/files/usr/bin/nano (editor)
warning: vimdiff (merge command, not found)
     ok: /data/data/com.termux/files/usr/bin/git (source VCS command, version 2.23.0)
     ok: /data/data/com.termux/files/usr/bin/gpg (GnuPG, version 2.2.17)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

#### Output of `chezmoi --version`

```
u0_a248@localhost:~$ chezmoi --version
chezmoi version 1.6.5, commit 3733485a2e018dfe174423c5c58edd6d03f0e3c6, built at 2019-09-20T12:17:54Z
```

**Comment by twpayne** [comment]
OK, so I did some investigating. The underlying problem seems to be that [termux is significantly different from Linux](https://wiki.termux.com/wiki/Differences_from_Linux). Specific differences that affect chezmoi include:

* `/bin/bash` does not exist.
* [`getent(1)`](http://man7.org/linux/man-pages/man1/getent.1.html) is not installed, which means that chezmoi cannot determine the current user's shell (which breaks `chezmoi cd`).

I was able to get the script to run if I changed the shebang line from

```sh
#!/bin/bash
```

to the path to `bash`, namely (on my Android phone):

```sh
#!/data/data/com.termux/files/usr/bin/bash
```

If you want your scripts to be portable across Linux and termux then I suggest making the scripts templates and defining a variable with the path to `bash`, e.g.

In `~/.config/chezmoi/chezmoi.toml`:

```toml
[data]
    bash = "/data/data/com.termux/files/usr/bin/bash"
```

In `~/.local/share/chezmoi/run_install_10base.sh.tmpl`:

```sh
#!{{ .bash }}

set -o errexit
set -o nounset

# etc...
```

Please re-open this issue if this does not solve your problem adequately.

**Comment by fbartels** [comment]
Hi @twpayne,

thanks for taking such a thorough  look into this. Yes, I've also noticed that `chezmoi cd` complained about missing `getent`, but did not see the direct connection. it is true that there is technically no `/bin/bash` in termux (`/bin` really comes from the Android system and all Termux files are stored in `$PREFIX`), they are using a library to remap this (could not find the pr for this) so that you can actually use `/bin/bash` in scripts. Executing them directly with e.g. `./script` works as well.

Making the file a template could work, but comes with the additional burden that one has to define bash as an option on all chezmoi config files.

I have to think about this.

**Comment by twpayne** [comment]
> Making the file a template could work, but comes with the additional burden that one has to define bash as an option on all chezmoi config files.

A couple of possibly useful threads here:

1. You can auto-generate most of your chezmoi config file by including a [`.chezmoi.<format>.tmpl` file in your repo](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiformattmpl).

2. You can cope with missing variables in templates. I think (but have not tested) that you can combine this with one of the [`default` functions](http://masterminds.github.io/sprig/defaults.html). For example, you should be able to do this:

```
#!{{ default "/bin/bash" (index . "bash") }}
```

This should allow you to only specify `bash` when it's different from normal.

**Comment by fbartels** [comment]
https://wiki.termux.com/wiki/Termux-exec was that I was thinking about, but it seems that their recommendation is still to change the shebang so I'll update my scripts to be templates instead.

Thanks again
