### ISSUE TITLE
After clean Windows install, trying to add a file results in an error

### ISSUE THREAD

**Issue by spatenotte** [twpayne/chezmoi#455]
#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

#### After a clean install on Windows, trying to add a file results in `C:\Users\sammy\.local\share\chezmoi: not private, but should be` error

History of commands:
```
scoop bucket add twpayne https://github.com/twpayne/scoop-bucket
scoop install chezmoi
chezmoi init
chezmoi add .\.gitconfig
chmod 0600 .\.local\share\chezmoi\
chezmoi doctor
```

#### Command that failed

```
 chezmoi add .\.gitconfig
```

#### Output of command with `--verbose`

```
PS C:\Users\sammy> chezmoi add --verbose .\.gitconfig
C:\Users\sammy\.local\share\chezmoi: not private, but should be
mkdir -m 777 C:\Users\sammy\.local\share: mkdir C:\Users\sammy\.local\share: Cannot create a file when that file already exists.
chmod 700 C:\Users\sammy\.local\share\chezmoi
```

Note: `private_dot_gitconfig` exists after the command, in `C:\Users\sammy\.local\share\chezmoi\private_dot_gitconfig`

#### Output of `chezmoi doctor`

```
C:\Users\sammy\.local\share\chezmoi: not private, but should be
     ok: version 1.7.0, commit f51a1ce5191cab883b8766c72f8cc295cc40a489, built at 2019-10-10T18:33:33Z
  ERROR: C:\Users\sammy\.local\share\chezmoi (source directory, perm 777)
     ok: C:\Users\sammy (destination directory, perm 777)
warning: C:\Users\sammy\.config\chezmoi\chezmoi.toml (configuration file)
     ok: D:\Cygwin\bin\vi.exe (editor)
warning: vimdiff (merge command, not found)
     ok: C:\Program Files\Git\cmd\git.exe (source VCS command, version 2.22.0)
warning: gpg (GnuPG, not found)
     ok: D:\Apps\op.exe (1Password CLI, version 0.6.2)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

#### Output of `chezmoi --version`

```
chezmoi version 1.7.0, commit f51a1ce5191cab883b8766c72f8cc295cc40a489, built at 2019-10-10T18:33:33Z
```

**Comment by twpayne** [comment]
Thanks for reporting this - this looks like a clear bug in chezmoi on Windows. Specifically, chezmoi tries to check that the source directory is private, it's clearly not getting it quite right on Windows. Note that it's just a warning message, not an error.

I've disabled the check (#456), created an issue to re-add it (#457), and pushed a new version of chezmoi (1.7.1) which should be built in the next 15 minutes so you can continue using chezmoi without the warning.

**Comment by spatenotte** [comment]
Thanks for the quick workaround! I saw from #457 that you don't have easy access to a Windows machine. While I don't know if I could actually help with the implementation side of things (I'll try to take a look regardless), I would be happy to help with testing the fix, if one is found.
