### ISSUE TITLE
chezmoi is incredibly slow on my machine

### ISSUE THREAD

**Issue by webframp** [twpayne/chezmoi#461]
#### Troubleshooting
- [X] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [X] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [X] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

All chezmoi commands are incredible slow, not sure how to begin debugging this so I'm open to any suggestions.

#### Command that failed

```
chezmoi cd
```

#### Output of command with `--verbose`

```
❯ chezmoi cd --verbose
mkdir -m 755 /Users/sme/.local/share: mkdir /Users/sme/.local/share: file exists
exec /usr/local/bin/zsh
chezmoi via  v1.13.1 took 1m3s
```

#### Output of `chezmoi doctor`

```
❯ chezmoi doctor
     ok: version 1.7.2, commit 41c4fdc2faf1bf9f0ded922d1ea7724a838bca3f, built at 2019-10-17T00:29:03Z
     ok: /Users/sme/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/sme (destination directory, perm 755)
     ok: /Users/sme/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/local/bin/zsh (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.23.0)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.17)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
     ok: /usr/local/bin/lpass (LastPass CLI, version 1.3.3)
     ok: /usr/local/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/local/bin/vault (Vault CLI, version 1.2.3)

chezmoi on  master [⇡!] took 29s
```

#### Output of `chezmoi --version`

```
❯ chezmoi --version
chezmoi version 1.7.2, commit 41c4fdc2faf1bf9f0ded922d1ea7724a838bca3f, built at 2019-10-17T00:29:03Z
```

#### Other info
I have not updated to Catalina:
```
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G103
```

My shell startup time is very fast:
```
bash-5.0$ for i in $(seq 1 10); do /usr/bin/time zsh -i -c exit; done
        0.39 real         0.23 user         0.14 sys
        0.54 real         0.27 user         0.16 sys
        0.38 real         0.22 user         0.14 sys
        0.40 real         0.22 user         0.14 sys
        0.41 real         0.24 user         0.14 sys
        0.38 real         0.22 user         0.14 sys
        0.39 real         0.22 user         0.14 sys
        0.39 real         0.22 user         0.14 sys
        0.38 real         0.22 user         0.14 sys
        0.38 real         0.22 user         0.14 sys
```

I normally use zsh, with https://starship.rs/ prompt. I have tested this issue as well in tcsh, sh, and bash with default configurations and see similar behavior.

**Comment by webframp** [comment]
dtruss generated a 15MB file as output, when I used `sudo dtruss -C -e -f chezmoi cd 2>dtruss.log`. I can send it to you if you're interested, not sure about attaching a file that size here?

Here's the call counts at least:
```
CALL                                        COUNT
csrctl                                          1
execve                                          1
fork                                            1
getentropy                                      1
getuid                                          1
kqueue                                          1
mkdir                                           1
rmdir                                           1
shared_region_check_np                          1
sigreturn                                       1
unlink                                          1
write                                           1
__mac_syscall                                   2
access                                          2
exit                                            2
getegid                                         2
gettid                                          2
issetugid                                       2
readlink                                        2
sysctlbyname                                    2
wait4_nocancel                                  2
bsdthread_register                              3
dup2                                            3
geteuid                                         3
proc_info                                       3
getpid                                          4
pipe                                            4
csops                                           5
ioctl                                           6
sysctl                                          6
bsdthread_create                               11
read                                           13
thread_selfid                                  13
mprotect                                       16
mmap                                           22
sigaltstack                                    26
fcntl                                          30
kevent                                         34
__pthread_sigmask                              41
sigaction                                     125
lstat64                                       210
stat64                                        403
psynch_cvclrprepost                           603
psynch_mutexdrop                              723
madvise                                       834
psynch_mutexwait                              903
open                                         6210
close                                        6215
close_nocancel                              12445
fstatfs64                                   12464
fcntl_nocancel                              12468
openat                                      12473
fstat64                                     18714
lseek                                       24924
psynch_cvsignal                             25103
psynch_cvwait                               25340
getdirentries64                             25429
__semwait_signal                            27105
```

For other q's:
```
❯ time dscl . -read $HOME UserShell
UserShell: /usr/local/bin/zsh
dscl . -read $HOME UserShell  0.02s user 0.02s system 93% cpu 0.038 total
```

I have a virus checker (Avast) so I tested adding an exclusion of my entire home dir under /Users, but had the same result. 

I also use [RansomWhere](https://objective-see.com/products/ransomwhere.html) from Objective-See, which I uninstalled temporarily to check if that was the issue but it made no difference.

**Comment by twpayne** [comment]
Thanks for the further investigation.

While running chezmoi under `dtruss`, is there any point at which the output pauses?

I notice that `chezmoi doctor` takes 29 seconds. It takes 2.1 seconds on my five-year-old MacBook Pro. Is there any obviously long pause in the output of `chezmoi doctor` while the command runs?

The time of 1 minute 3 seconds for `chezmoi cd` makes me suspect that there is something being run with 60 second timeout, which then timeouts, allowing execution to continue.

I'll add some profiling code to chezmoi to help track down the slowness.

**Comment by twpayne** [comment]
OK, I created #464 to help investigate this. This is not merged into `master` yet. Are you able to build and run chezmoi locally with the Go tool? Instructions for enabling profiling are in the PR.

For what it's worth, on my machine, running `chezmoi doctor` results in an empty profile because chezmoi spends all its time waiting for other programs to run. Profiling `chezmoi diff` shows time spent in the Go scheduler. chezmoi does very little CPU-intensive work itself.

**Comment by webframp** [comment]
Ran with the changes from #464, generated the following png:
![profile001](https://user-images.githubusercontent.com/774378/67239801-031ded80-f41e-11e9-9329-b03a7c718eeb.png)

I really don't think the issue is with chezmoi at this point, which I suspected originally, but it's a weird issue that's tricky to pin down. 

I thought it could be something related to my zsh setup, so I tried the following and got the same behavior. It does seem like it's hanging
```
❯ bash --noprofile --norc
bash-5.0$ echo $PATH
/usr/local/sbin:/usr/local/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
bash-5.0$ which chezmoi
/usr/local/bin/chezmoi
bash-5.0$ chezmoi cd
bash-5.0$ sudo dtruss -e chezmoi doctor 2>|dtruss.bash.log
```
There's 11MB of output, not clear what the issue is exactly but something is getting exec'd that has a timeout like you suggested

**Comment by twpayne** [comment]
Apologies for the lack of recent response. Some stuff happened in real life.

Any more clues?

I'm preparing a PR that adds logging for individual operations that might help isolate the slow step.

**Comment by webframp** [comment]
Can confirm at least that this is still happening, whatever helps to pinpoint it let me know. 
I see crazy high cpu just from `chezmoi cd` considering what it's doing:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/774378/68693150-c76dd380-0544-11ea-8639-16d3168251bd.png">

I'm assuming it's my config somehow still and not directly chezmoi, but don't know where to isolate the issue.

**Comment by twpayne** [comment]
I haven't forgotten about this. Hooking in the logging everywhere is leading to a larger internal refactor that I wanted to do but is turning out to be larger than expected.

**Comment by twpayne** [comment]
Could you try running the latest `master` with the `--debug` flag?

    chezmoi cd --debug

This will print more detailed information about what chezmoi is doing, including how long various operations take to run.

**Comment by webframp** [comment]
Thanks @twpayne ! Here's the info from a few attempts, I can't recreate the same slowness but it may also be something changed in my environment:
```
2019/11/20 14:56:34 Mkdir("/Users/sme/.local/share", 0755) == mkdir /Users/sme/.local/share: file exists (74.661µs)
2019/11/20 14:56:34 Stat("/Users/sme/.local/share") (52.158µs)
2019/11/20 14:56:35 Run("/usr/local/bin/zsh")

2019/11/20 14:57:20 Mkdir("/Users/sme/.local/share", 0755) == mkdir /Users/sme/.local/share: file exists (62.662µs)
2019/11/20 14:57:20 Stat("/Users/sme/.local/share") (78.105µs)
2019/11/20 14:57:21 Run("/usr/local/bin/zsh")

2019/11/20 14:57:37 Mkdir("/Users/sme/.local/share", 0755) == mkdir /Users/sme/.local/share: file exists (59.878µs)
2019/11/20 14:57:37 Stat("/Users/sme/.local/share") (46.571µs)
2019/11/20 14:57:38 Run("/usr/local/bin/zsh")
```

**Comment by twpayne** [comment]
Thanks for running the tests. As the slowness issues has disappeared on your machine, I'll close this issue, but please re-open it if the problem re-occurs.
