### ISSUE TITLE
Add the `dotfile-manager` tag

### ISSUE THREAD

**Issue by jwatt** [twpayne/chezmoi#462]
Other popular dotfiles managers have the [dotfile-manager](https://github.com/topics/dotfile-manager) and other handy tags on their project. For example:

https://github.com/TheLocehiliosan/yadm
https://github.com/andsens/homeshick

It would be helpful if this project could add some of those too to make be more discoverable.

**Comment by twpayne** [comment]
Done, thanks for the input.
