### ISSUE TITLE
Question about programs which manipulate their configs directly

### ISSUE THREAD

**Issue by sseneca** [twpayne/chezmoi#467]
First off, thanks for `chezmoi`, I find it really useful.

My question regards applications where management of their configuration is done through said application. For example, with `irssi` or `weechat`, most configuration occurs within the program itself, where it overwrites the configuration file in question. The same is true for `emacs` (or at least spacemcs) -- using the inbuilt `customize` interface overwrites the configuration file, which would then be overwritten on `chezmoi apply`, losing all changes made.

The current workaround I'm using for `emacs` is a hook that looks like this:

```elisp
(defun dotspacemacsfile_hook ()
  (when (string= (file-name-nondirectory (buffer-file-name)) "init.el")
    (shell-command "/usr/bin/chezmoi add /home/sseneca/.config/emacs/init.el")
    (message "chezmoi added init.el!")
    ))
(add-hook 'after-save-hook 'dotspacemacsfile_hook)
```

so all it's doing is running `chezmoi add ~/.config/emacs/init.el` each time it writes to that file.

This works, but I was wondering if there's a way `chezmoi` natively handles situations like these, so I don't have to write something like that hook or a script/plugin for each of `weechat` / `irssi` etc.

Thanks again!

**Comment by twpayne** [comment]
Thanks for the kind words :)

Right now, your hook solution is good. I hope to improve the situation in chezmoi with fixes for #423 and #424. In short, chezmoi will record the last contents that it wrote to a file, and therefore be able to detect if the file was changed by a third party after chezmoi wrote it. The behavior in such cases can be configurable, say re-add the file to chezmoi (as your hook does), run a three-way merge tool (see #224), overwrite the changes, or leave everything unchanged.

Hopefully I'll get some time to implement this in the next few weeks.

**Comment by duckbrain** [comment]
I *just* thought of this, so let me know if I missed something. I think you could use a symlink to something in your `~/.local/share/chezmoi` directory (which is under source control). 

In my case I have `~/.config/Code/User/settings.json` that Code will allow me to change through the GUI. So I might have a configuration that looks like this.

```
├── .config
│   └── Code
│       └── User
│           └── settings.json
└── dot_config
    └── Code
        └── User
            └── symlink_settings.json
```

The symlink would be deployed to your `~`, but the file it points to is in your source control. As long as your tool doesn't unlink, then write the file, it should update target.

The naming convention is completely optional, you could have a non-`.` directory and use `.chezmoiignore` to avoid copying it.

I'll try this out later and report back here how it goes.

**Comment by duckbrain** [comment]
I've been doing this for a few days, and it's working great. `symlink_` prefixes allow you to create a symlink and `{{ .chezmoi .homedir }}` allows you to make an absolute path. It would be a bit nicer if there was a `{{ .chezmoi .srcdir }}`, so it could work when using `--source` and be a bit shorter.

I ended up using a convention of underscore prefixes for these files I symlink to, with `_*` in my `.chezmoiignore`.

```
_bin # Scripts that are referenced (rofi scripts, i3blocks, etc.)
_config # Config files that may be modified by other programs. (VSCode, mimeapps.list)
```

The warning of modified files would be nice too, but for files that I'm frequently changing through another program, it's much more convenience to symlink.

**Comment by twpayne** [comment]
Thanks very much for this @duckbrain - that's a really neat solution. I've added a `.chezmoi.sourceDir` template variable in #485 and will do a new release with this soon.

**Comment by sseneca** [comment]
Switched from using the custom hook to this and it's working great, thanks to you both!
