### ISSUE TITLE
Parsing data in templates

### ISSUE THREAD

**Issue by rcorrear** [twpayne/chezmoi#474]
Hi,

Thanks for `chezmoi`, been using it only very briefly but find the whole concept fascinating and very consistently thought through!

I'm having an issue with the 1Password  integration, the output from the command:

`op get item xxx | jq` looks something like:

```
{
  "uuid": "xxx",
  ...
  "details": {
    "fields": [
      {
        "designation": "password",
        "name": "password",
        "type": "P",
        "value": "REDACTED"
      },
     ...
    ]
  },
  ...
}
```

This means that to get the value of password I'd need to use some query language like jsonpath with a query like `{{ (onepassword "xxx") | jsonpath "$.details.fields[0].value" }}` (just some made up syntax).

AFAICT there's no support for this, and unless I'm missing something this is probably the only way, so I'd like to discuss the possibility of adding it.

**Comment by rcorrear** [comment]
After some looking around I noticed that in items of type "Password" you get the password as a property and not inside the "details.fields" array. This might be a simple workaround, the downside being that if you need a username for example, it needs to be in a different item.

**Comment by twpayne** [comment]
Thanks for the nice feedback :)

The `onepassword` function already parses the JSON output and returns the structured result, as [documented in the reference manual](https://www.chezmoi.io/docs/reference/#onepassword-uuid). You can use normal `text/template` syntax to extract the data you want. In your case, I believe (but have not verified) that

    {{ (onepassword "xxx") | jsonpath "$.details.fields[0].value" }}

would look something like:

    {{ (index (onepassword "xxx).details.fields 0).value }}

Please re-open this issue if this does not fix your problem.

**Comment by rcorrear** [comment]
This is great! I missed it when reading the documentation for `text/template`. Thanks for pointing it out (maybe having it in the docs would be helpful, it's not immediately obvious how to do it).

**Comment by twpayne** [comment]
I added some documentation in https://github.com/twpayne/chezmoi/pull/476. Further improvements very welcome :)

**Comment by pvinis** [comment]
How would I use something like this?

`export PASSWORD={{ (onepassword "theuuid") | jq '.details.fields[] | select(.name == "password") | .value' }}`

Basically, I dont want to have something like `fields[1]` to get the password, I want to search in the `fields` array for something that has the `name` `password` and get the `value` from inside there.

The obj is like this:
```
 "details": {
    "fields": [
      {
        "designation": "password",
        "name": "password",
        "type": "P",
        "value": "suuuupersecret"
      },
      {
        "designation": "username",
        "name": "username",
        "type": "T",
        "value": ""
      }
    ]
  }
```

**Comment by rcorrear** [comment]
I'll tell you about my experience: on my templates I use the hard-coded index solution. I believe to have something automatically searching a named field like "password" there should be a function that does something like jsonpath.
However, I found that hard-coded indexes are fine as I very rarely change the structure of my 1Password entries (and when I've done it it's more or less easy to update the templates).

**Comment by twpayne** [comment]
You can do something like this:

```
{{ range (onepassword "theuuid").details.fields }}
{{ if eq .name "password" }}{{ .value }}{{ end }}
{{ end }}
```

You'll probably want to put this on one line to avoid introducing newlines into the output:

```
export PASSWORD={{ range (onepassword "theuuid").details.fields }}{{ if eq .name "password" }}{{ .value }}{{ end }}{{ end }}
```

**Comment by pvinis** [comment]
Hm.. I like the name-checking way, but I hate the verbosity of it. I like the simplicity of the indexed way, but I hate the hardcoded-ness of it.

Welcome to computers I guess 😅.

`jq` is so easy, and I could make a function out of it, but no idea how that would combine with the rest of the templating. I guess because chezmoi is in go, we can (for now) only use the go template/json things, right?

**Comment by pvinis** [comment]
Since I'm here, I'll also comment that I have no idea how the "right" way to add a template file like that is. What I did is `chezmoi add myfile`, then went in `.local/...` dir, renamed the file to `myfile.tmpl` and then replaced the password with the `{{}}` string. Is there a better way?

**Comment by twpayne** [comment]
chezmoi uses Go's [`text/template`](https://godoc.org/text/template) for templating, which is part of Go's standard library. I agree that `jq` is more concise than `text/template` for extracting individual fields from strings containing JSON but note that the value returned from the `onepassword` is a parsed value, not a string containing JSON. Changing this would break backwards compatibility and introducing a second language would add a lot of complexity just to save a few characters of typing, so I don't think it's worth it.

To add a template file, you can specify the `--template` (`-T`) option to add:

    chezmoi add --template myfile

This will add the `.tmpl` extension.

You can also use the `--autotemplate` (`-a`) option which attempts automatically create a template by finding matching variables, but this does not work for variables that are stored in your password manager.

You can also use the `.tmpl` extension with the `chattr` command:

    chezmoi chattr template myfile

These all have the exact same effect as renaming the file in the source directory, though.

There's more information in [the how-to section on templates](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-templates-to-manage-files-that-vary-from-machine-to-machine).

**Comment by pvinis** [comment]
I decided to do it like:
```
export PASSWORD={{ range (onepassword "theuuid").details.fields -}}
  {{ if eq .name "password" }}
    {{ .value }}
  {{ end }}
{{- end }}
```

The `-` in the first and last line is stripping whitespaces. https://golang.org/doc/go1.6#template

Thanks both!

**Comment by pvinis** [comment]
Also, as an extra info, when I create a "Password" type in 1password, I can access it by `{{ (onepassword "theuuid").details.password }}`, and when it's a "Login" type, I need to do the above, with `range` and `eq .name` etc.

**Comment by ubuntudroid** [comment]
@pvinis thanks for that very last hint! 🤗 @twpayne could we get support for fetching 1password login type items with the simple dot notation at some point as well? Most passwords are actually login items as they often need a username/ID which the password type does not have by default.
