### ISSUE TITLE
Wish: running scripts before applying changes

### ISSUE THREAD

**Issue by oscarbenedito** [twpayne/chezmoi#475]
`chezmoi` is a really nice tool, thank you for making and mantaining it!

I have found that the scripts with the `run_` prefix run after `chezmoi` changes the dotfiles. Is there any way you could add an option to be able to run them before the canges (either by having a different prefix or introducing an option to chezmoi).

Thank you so much!

**Comment by twpayne** [comment]
Thank you for your kind words :)

What exactly is the use case here? We could consider adding a `pre_` prefix to scripts (e.g. `pre_run_foo.sh`) for scripts that should be run before chezmoi updates the dotfiles, but what exactly should run before chezmoi changes the dotfiles but should not run after?

**Comment by oscarbenedito** [comment]
Hey! In my case I would want it so I can write my dotfiles using literate programming tools. The script would then get the "tangled" text and output the files for chezmoi to process.

For this to be completely correct, the script would also have to be run even for dry-runs or when running `chezmoi diff`, but I see why that isn't necessarily good.

Another solution that would solve both the problems would be adding something similar to `chezmoi exec` that simply runs all the scripts without doing anything else (or scripts with a particular prefix). In that case, I would have to run `chezmoi exec` and then I could either run `chezmoi diff` or `chezmoi apply`. It is true that the only usefulness I can think of for this feature is to be able to edit the files processed by chezmoi and that might not align with what the software is trying to achieve.

Whether the feature is added or not, thank you anyway for the great piece of software!

**Comment by twpayne** [comment]
Thanks for the background info.

How about creating a shell alias for chezmoi that runs your literate programming tool and then calls chezmoi?

```bash
chezmoi() {
    run-literate-programming-tool && /usr/bin/chezmoi $*
}
```

Admittedly, this executes `run-literate-programming-tool` before every invocation of chezmoi, which isn't exactly what you want, but maybe it's close enough?

**Comment by oscarbenedito** [comment]
Yes, this should definitely do! Thank you so much for the help and the quick replies!
