### ISSUE TITLE
Cannot use keybase git repo 

### ISSUE THREAD

**Issue by RMHogervorst** [twpayne/chezmoi#495]
#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

I wonder if it could be possible to use the keybase git repo for chezmoi?
I get a curious error: `fatal: not a git repository (or any of the parent directories): .git` Which doesn't happen when I try to add a remote to a local repo on a different part of my computer (say ~/Documents/testrepo).

#### Command that failed

```
git remote add origin keybase://private/rmhogervorst/personaltokens
```

#### Output of command with `--verbose`

```
fatal: not a git repository (or any of the parent directories): .git
```

#### Output of `chezmoi doctor`

```
     ok: version 1.7.3, commit 4d678ce6850c9d81c7ab2fe0d8f20c1547688b91, built at 2019-11-23T18:22:47Z
     ok: /Users/roelhogervorst/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/roelhogervorst (destination directory, perm 755)
warning: /Users/roelhogervorst/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.23.0)
warning: gpg (GnuPG, not found)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

#### Output of `chezmoi --version`

```
chezmoi version 1.7.3, commit 4d678ce6850c9d81c7ab2fe0d8f20c1547688b91, built at 2019-11-23T18:22:47Z
```

**Comment by twpayne** [comment]
Thank you for trying chezmoi with Keybase. It's a nice combination.

Where are you running the `git remote` command? Are you running it inside a git working copy? If not, I think it will fail with the error message you got.

I was able to successfully store my dotfiles in a Keybase repo using the following steps:

1. Install Keybase (I used `brew cask install keybase`).
2. Run Keybase.
3. Create a Keybase encrypted repo called `test`.
4. Change to my source directory with `chezmoi cd`.
5. Add the Keybase repo as a remote with `git remote add keybase keybase://private/twpayne/test`.
6. Push my dotfiles to the repo with `git push keybase master`.

At this point I saw:

```
$ git push keybase master
Initializing Keybase... done.
Syncing with Keybase... done.
Syncing encrypted data to Keybase: (100.00%) 2.22/2.22 KB... done.
Preparing and encrypting: (100.00%) 4.88/4.88K objects... done.
Indexing hashes: (5.25%) 0.26/4.88K objects... done.
Indexing CRCs: (5.25%) 0.26/4.88K objects... done.
Indexing offsets: (5.25%) 0.26/4.88K objects... done.
Syncing encrypted data to Keybase: (100.00%) 9.29/9.29 MB... done.
To keybase://private/twpayne/test
 * [new branch]      master -> master
```

I then quit the `chezmoi cd` shell by running `exit` and moved my source directory out of the way. I was then able to run `chezmoi init` with a Keybase repo:

```
$ chezmoi init keybase://private/twpayne/test
Cloning into '/Users/twp/.local/share/chezmoi'...
Initializing Keybase... done.
Syncing with Keybase... done.
Counting: 8.91 MB... done.
Cryptographic cloning: (100.00%) 8.91/8.91 MB... done.
Updating files: 100% (1112/1112), done.
```

Could you give some exact steps to reproduce the problem that you see?

**Comment by RMHogervorst** [comment]
Oh weird, I tried that. Let me your steps tonight and I'll update you

**Comment by RMHogervorst** [comment]
I did the following steps:

0. (keybase is already installed)
1. chezmoi cd 
2. git remote add keybase keybase://private/rmhogervorst/chezmoi
and got

```
fatal: not a git repository (or any of the parent directories): .git
```

Could be related to zsh? 

I can connect to a keybase git repo outside of chezmoi.

**Comment by RMHogervorst** [comment]
I'm running zsh 5.7.1 (x86_64-apple-darwin18.2.0)

**Comment by twpayne** [comment]
I think you need to create a git repository before you add a remote. Try:

* Either, run `git init` between steps 1 and 2.

* Or, run: `chezmoi init keybase://private/rmhogervorst/chezmoi && chezmoi cd`.

**Comment by RMHogervorst** [comment]
yes! The git init in the chezmoi folder was the missing step

**Comment by twpayne** [comment]
Great! Thanks for the exact steps to reproduce the problem and I'm glad we found the solution. Please re-open this issue if needed.
