### ISSUE TITLE
chezmoi add does not show warning on ignored file

### ISSUE THREAD

**Issue by Rubonnek** [twpayne/chezmoi#507]
#### Troubleshooting
- [x] I ran `chezmoi doctor` and fixed as many issues as possible and retried my command.
- [x] I have double checked the instructions for [Installation](https://github.com/twpayne/chezmoi/blob/master/docs/INSTALL.md) and the [Quickstart Guide](https://github.com/twpayne/chezmoi/blob/master/docs/QUICKSTART.md).
- [x] I have search for previous issues that have been reported/opened, and none of them relate to my problem.

Failure to follow the troubleshooting steps (and to report information requested below), may make it difficult to provide the proper support required. Furthermore, your issue may be closed without reply, if the instructions were not properly followed.

---

#### Description of issue

`chezmoi add` does not show warning when attempting to add file that is being ignored

#### Command that failed

```
chezmoi add test_file #while test_file is included in .chezmoiignore
```

#### Output of command with `--verbose`

```
# no output
```

#### Output of `chezmoi doctor`

```
     ok: version v1.7.3-6-g97258b3, commit 97258b3a9507ac748a4ce59d4c3e537d1ac4e45d, built at 00:00:00_01/12/2019
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/wilson/.local/share/chezmoi (source directory, perm 700)
     ok: /home/wilson (destination directory, perm 700)
     ok: /home/wilson/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.18)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /usr/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/bin/vault (Vault CLI, version 1.2.0)
```

#### Output of `chezmoi --version`

```
chezmoi version v1.7.3-6-g97258b3, commit 97258b3a9507ac748a4ce59d4c3e537d1ac4e45d, built at 00:00:00_01/12/2019
```

**Comment by twpayne** [comment]
Thank you for reporting this :) chezmoi could definitely do better here.

**Comment by Rubonnek** [comment]
@twpayne Thank you for the patch and this **awesome** dotfiles manager! I've migrated twice from two different dotfiles manager by now and I'm truly glad to finally have one that meets all my needs!
