### ISSUE TITLE
chezmoi diff echoes password manager command line

### ISSUE THREAD

**Issue by Rubonnek** [twpayne/chezmoi#522]
**Describe the bug**
When a template grabs a password using a password manager, like `gopass`, then `chezmoi diff` echoes the command it's running on the background

**To reproduce**
`chezmoi diff #while myfile.config.tmpl contains {{ gopass "MyPassword" }}`

**Expected behavior**
I expected chezmoi to show nothing on screen since the source and target state of my file were the same.

**Output of command with `--verbose`**
```
$ chezmoi diff --verbose
/usr/bin/gopass show MyPassword
```

**Output of `chezmoi doctor`**
```
$ chezmoi doctor
warning: version 1.7.6
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/wilson/.local/share/chezmoi (source directory, perm 700)
     ok: /home/wilson (destination directory, perm 700)
     ok: /home/wilson/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /usr/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/bin/vault (Vault CLI, version 1.2.0)
```
**Additional Context**
Perhaps the password manager echoed command should only be shown when using the `--verbose` flag

**Comment by twpayne** [comment]
Thanks for the bug report, good catch. This was effectively due to stale debugging code that I'd left in while working on the password manager integration.

#523 fixes this by not printing executed commands that should be idempotent, unless they fail.

There's also a `--debug` flag to emit much more information which prints every command executed.
