### ISSUE TITLE
chezmoi add on empty file does not change source state on non-empty source file

### ISSUE THREAD

**Issue by Rubonnek** [twpayne/chezmoi#529]
**Describe the bug**
Say `myfile.config` was already populated, added to the source directory and applied to the target state. Then user empties out `myfile.config` on the target state and runs `chezmoi add myfile.config` to update the source state to an empty file. Nothing happens to the source state in this case.

**To reproduce**
````shell
printf "%s\n" test > "$(chezmoi source-path)/myfile.config"
touch $HOME/myfile.config
cd $HOME
chezmoi add myfile.config # myfile.config source state remains untouched
cat "$(chezmoi source-path)/myfile.config" # outputs 'test' but expected empty file
````

**Expected behavior**
Since emptying out `myfile.config` with `chezmoi edit` triggers a file removal on the destination directory, I was expecting that `chezmoi add` would empty the file on the source state and trigger a file removal on `chezmoi apply`.

But perhaps, instead of doing that, it might be better to simply prompt the user to use `chezmoi remove` instead if their intention is to remove the matching file found in the source state when the `-e` flag of `chezmoi add` is not present.

**Output of command with `--verbose` and `--debug`**
````shell
$ chezmoi diff --verbose --debug 
install -m 644 /dev/null /home/wilson/myfile.config
--- a/home/wilson/myfile.config
+++ b/home/wilson/myfile.config
@@ -0,0 +1,1 @@
+test
````

**Output of `chezmoi doctor`**
```
$ chezmoi doctor
warning: version 1.7.9
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/wilson/.local/share/chezmoi (source directory, perm 700)
     ok: /home/wilson (destination directory, perm 710)
     ok: /home/wilson/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /usr/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/bin/vault (Vault CLI, version 1.2.0)
```

**Additional context**
There might be another bug hidden in issue since emptying out a file with `chezmoi edit` triggers a file removal on the next `chezmoi apply` but the source state file lingers about without an `empty_` prefix.

**Comment by twpayne** [comment]
Thank you very much (again!) for the clear bug report and for your in-depth testing of chezmoi.
