### ISSUE TITLE
chezmoi add -e removes previous matching file without warning

### ISSUE THREAD

**Issue by Rubonnek** [twpayne/chezmoi#531]
**Describe the bug**
A non-empty source file `myfile.config` gets emptied without warning when `chezmoi add -e myfile.config` executes on an empty target file.

**To reproduce**
````shell
printf "%s\n" test > "$(chezmoi source-path)/myfile.config"
touch $HOME/myfile.config
cd $HOME
chezmoi add -e myfile.config # myfile.config gets removed on source state 
cat "$(chezmoi source-path)/empty_myfile.config" # outputs nothing as expected
````

**Expected behavior**
Expected to get a warning that a non-empty `myfile.config` file existed on the source directory before removing the file.

**Output of command with `--verbose` and `--debug`**
```
$ chezmoi add -e myfile.config --verbose --debug
2019/12/23 00:24:21 RemoveAll("/home/wilson/.local/share/chezmoi/myfile.config") (116.238µs)
rm -rf /home/wilson/.local/share/chezmoi/myfile.config
2019/12/23 00:24:21 WriteFile("/home/wilson/.local/share/chezmoi/empty_myfile.config", _, 0644, _) (7.222043ms)
install -m 644 /dev/null /home/wilson/.local/share/chezmoi/empty_myfile.config
--- a/home/wilson/.local/share/chezmoi/empty_myfile.config
+++ b/home/wilson/.local/share/chezmoi/empty_myfile.config
@@ -1,1 +0,0 @@
-test
```

**Output of `chezmoi doctor`**
```
$ chezmoi doctor
warning: version 1.7.9
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/wilson/.local/share/chezmoi (source directory, perm 700)
     ok: /home/wilson (destination directory, perm 710)
     ok: /home/wilson/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: /usr/bin/gopass (gopass CLI)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
     ok: /usr/bin/vault (Vault CLI, version 1.2.0)
```

**Comment by twpayne** [comment]
Thank you again for the thorough testing and extremely clear reports with exact how-to-reproduce steps!

I agree that adding a file a second time with `chezmoi add --empty` with an empty file in the target state leads to data loss in the source state if there was an existing file in the source state. However:

1. The source state should be under version control, so in practice the original data should be recoverable.

2. `chezmoi add` is used when adding a file for the first time, or to update the source state after updating the file in the target state.

Replacing the file in the target state with an empty file is a valid update to the target state. Emptying the target clearly leads to data loss as described in this issue, but there are many other updates to the target state that also cause data loss, for example replacing the file in the target state with random data and then running `chezmoi add`.

chezmoi could try to come up with some heuristic to determine whether "too much" data is being lost, for example by looking at the edit distance between the source and target states when doing `chezmoi add`, but this is likely to give both false positives and false negatives in practice.

The current behavior of chezmoi, although falling victim to the scenario presented above, is consistent and predictable. Changing the behavior of `chezmoi add` would break its usefulness for adding files updated in the target state. Given that lost data should be retrievable from version control in any case, I think chezmoi's current behavior is reasonable.

Does this make sense?

**Comment by Rubonnek** [comment]
You are welcome! And thank you for this amazing tool!

At first I opened this issue because I still have the bad habit of thinking
that a dotfile manager should auto cache the file like the previous dotfile
managers I've used, but after thinking about the way chezmoi works it makes sense to
have chezmoi not cache the file unless explicitly told to do so. But this was already covered on  #439 

And yes, I agree. The current behavior does make sense now.

What's bugging me underneath, however, is how quiet chezmoi is when performing
these source state attribute changes.

See, I'm currently coalescing three different dotfile repos into a single one
using chezmoi. The file permissions, encrypted files, and basically everything
else is all over the place in all three repos and long story short it's a mess
and I'm bound to make mistakes when adding these files to the repo.

I've found myself several times using `chezmoi add` against files instead of
`chezmoi edit` only to figure out later that I dropped the `private_` or the
`encrypted_` source state attribute when I did not mean to do that but chezmoi
never notified me of this change.

I'm aware that if all these files were cached in, say, a git repo before
running `chezmoi add`, then a `git status` will show whether the source state
attribute of a file changed or not. But the way I see it, notifying the user of
whether the source state attribute changed should be the job of the dotfile manager
and not the job of the VCS software.

Wouldn't you agree?

Perhaps the source state attributes could be color-coded and only printed out
when chezmoi detects a source state attribute change.

**Comment by twpayne** [comment]
I really like that you're pushing chezmoi to its limits (and beyond) here :)

`chemzoi status` (#424) when it eventually gets implemented should fix some of these issues.

In the mean time, please know that the `-n` and `-v` options also apply to `chezmoi add`. With `chezmoi add -n -v` chezmoi will show you what updates it will make to the source state, without actually making any changes. Maybe this will help enough to catch unwanted changes in the short term to assist you in your epic three system migration?

**Comment by Rubonnek** [comment]
Welp, that will definitely help in the meantime. Thanks!

**Comment by twpayne** [comment]
> I'm aware that if all these files were cached in, say, a git repo before
running chezmoi add, then a git status will show whether the source state
attribute of a file changed or not. But the way I see it, notifying the user of
whether the source state attribute changed should be the job of the dotfile manager
and not the job of the VCS software.
> 
> Wouldn't you agree?

Yup, totally! I think you've identified a real weakness in chezmoi here: it doesn't maintain consistency in the source state well enough, or communicate attribute changes to the user properly. Thank you again for raising these issues - they'll definitely make chezmoi better and have given me a lot to think about :)

**Comment by twpayne** [comment]
A possible enhancement here would be for chezmoi to warn the user when either of the `private_` or `encrypted_` attributes are removed.

**Comment by twpayne** [comment]
There's now also [`chezmoi re-add`](https://www.chezmoi.io/reference/commands/re-add/). On top of `chezmoi status` and `chezmoi add -n -v` being available, I'll close this issue.
