### ISSUE TITLE
zsh tab completion doesn't work

### ISSUE THREAD

**Issue by alock** [twpayne/chezmoi#534]
**Describe the bug**
I installed chezmoi via homebrew with `brew install twpayne/taps/chezmoi` and the zsh tab completions do not work.  Please let me know if there is any other information you need.

**Expected behavior**
I expected tab completion to work with the brew install since it adds a symlink to `_chezmoi` in my `$fpath`.

```shell
$ echo $fpath | tr ' ' '\n' | grep /usr/local/share/zsh/site-functions
/usr/local/share/zsh/site-functions
$ ls -la /usr/local/share/zsh/site-functions | grep chezmoi
 _chezmoi -> ../../../Cellar/chezmoi/1.7.9/share/zsh/site-functions/_chezmoi
```

**Comment by twpayne** [comment]
Hmm, I have chezmoi installed the same way on my mac and the zsh completions are working for me:

```
twp@Toms-MBP ➜  ~ chezmoi a<tab><tab>
add      -- Add an existing file, directory, or symlink to the source state
apply    -- Update the destination directory to match the target state
archive  -- Write a tar archive of the target state to stdout
```

The zsh completion should be installed by the brew formula. The brew formula itself is built with goreleaser and the zsh completion is installed [at this line](https://github.com/twpayne/chezmoi/blob/master/.goreleaser.yaml#L144). The relevant line in the Brewfile is [here](https://github.com/twpayne/homebrew-taps/blob/master/Formula/chezmoi.rb#L28).

Is it possible that you need to re-login for the changes to take effect?

**Comment by alock** [comment]
I did not expect you to respond today, thanks you!  I have tried a new shell with the same behavior.  I wanted to create the ticket incase you (or someone) knew of some simple fix.  I will continue researching if there is any debugging tool I can find to see what zsh is evaluating when I hit tab.

Also thank you for building a pretty amazing tool!  I will update this issue if I find anything in the coming days.

**Comment by alock** [comment]
I actually figured out the issue.  I have some optimization code for the compinit that I forgot about and after I ran `rm ~/.zcompdump*`, close and reopen the shell it works.  I got the tip from this [ohmyzsh debug doc](https://github.com/ohmyzsh/ohmyzsh/wiki/Troubleshooting#completion-problems).

**Comment by twpayne** [comment]
Great! Really happy to hear that this got sorted.

**Comment by alock** [comment]
@twpayne - its seems this commit https://github.com/twpayne/chezmoi/commit/9f0b03e51590b00b83792ace90b52409d6392e1a changes the tab completion link on a fresh install for zsh.  The file name has gone from `_chezmoi` to `chezmoi.zsh` is that intentional?

**Comment by twpayne** [comment]
9f0b03e51590b00b83792ace90b52409d6392e1a only changes how the completions are generated by the build system, it doesn't change any filenames.

`chezmoi.zsh` is renamed to `_chezmoi` by the Homebrew formula here: https://github.com/twpayne/homebrew-taps/blob/master/Formula/chezmoi.rb#L28

but I see that the rename is missing from the Homebrew core chezmoi formula:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/chezmoi.rb#L30

I'll open a PR to fix the Homebrew core chezmoi formula.

**Comment by alock** [comment]
👏 - kudos on the crazy fast response!

That makes sense I got a little turned around switching from your tap to the core tap with a new install.

Thanks for updating this.

**Comment by twpayne** [comment]
Thanks for finding this! I was also noticing problems with zsh completion on macOS, but hadn't investigated them. Thanks for finding the problem :)

**Comment by twpayne** [comment]
@alock https://github.com/Homebrew/homebrew-core/pull/54627 is now merged and when you `brew upgrade chezmoi` you'll get working zsh completion again :)

**Comment by alock** [comment]
Verified it works again thanks!
