### ISSUE TITLE
Add age support

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#539]
[age](https://github.com/FiloSottile/age) is a modern alternative to `gpg` and a good candidate for encrypted file support. Maybe chezmoi should support it.

**Comment by Fuzen-py** [comment]
Has this been audited?

**Comment by twpayne** [comment]
@Fuzen-py I don't think age has been audited, best to ask the question at https://github.com/FiloSottile/age.

**Comment by Fuzen-py** [comment]
Reading through the specification for age, it hasn't been, or at least thoroughly. I think for this util to be promoted, it should be out of beta. I happen to find this comment in the specification for age to be concerning:

> I know I am using signing keys for encryption, which is unholy. I’m sorry? It would be nice to check further for cross-protocol attacks but it looks like we'll be ok. The X25519 with the tweak is meant to generate a derived key for some domain separation.

If this is to be added, I think a warning should be shown in the documentation for chezmoi as this is beta software.
