### ISSUE TITLE
Update keepassxc integration

### ISSUE THREAD

**Issue by franek** [twpayne/chezmoi#552]
**Describe the bug**
Since last version of keepassxc-cli, password are not returned by default (cf. https://github.com/keepassxreboot/keepassxc/pull/3710) we need to use `--show-protected` option.

**To reproduce**

Use the last version of keepassxc-cli (2.5.1) and try to retrieve a password from keepass.

**Output of command with `--verbose`**
```
chezmoi apply -v --debug
Insert password to unlock .../bdd.kdbx:
2020/01/08 16:24:36 IdempotentCmdOutput("/Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli show .../bdd.kdbx 'my entry'") (358.815397ms)
```

The file generated by chezmoi contains "PROTECTED" and not the password.

**Output of `chezmoi doctor`**
```
     ok: version 1.7.10, commit a402f9eba1245b45de1aa0b05dda4b35c164f345, built at 2019-12-27T22:37:13Z
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/user/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/user (destination directory, perm 755)
     ok: /Users/user/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /Users/user/bdd.kdbx (KeePassXC database)
     ok: /usr/local/bin/vi (editor)
     ok: /usr/local/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.21.0)
warning: gpg (GnuPG, not found)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /Applications/KeePassXC.app/Contents/MacOS/keepassxc-cli (KeePassXC CLI, version 2.5.2)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Thanks very much for reporting this :)

In #553 I've updated chezmoi to pass the `--show-protected` flag to `keepassxc-cli` when needed. I've also released a new version of chezmoi with this change (1.7.11) so it should soon be available to all users.
