### ISSUE TITLE
Diff does not show colors properly con Windows

### ISSUE THREAD

**Issue by omry** [twpayne/chezmoi#554]
Getting started on Windows, looks like the colors does not work properly.
(Or maybe the diff format is just too weird for me).

![image](https://user-images.githubusercontent.com/376455/72045403-d59d4f00-326a-11ea-8fc6-c13fd5760009.png)

**Comment by twpayne** [comment]
Thanks for reporting this. chezmoi uses ANSI escape sequences to colorize diff output, but these need [an extra function call to enable them](https://docs.microsoft.com/en-us/windows/console/setconsolemode) on Windows. #556 does this. In the short term you can use the `--color=off` flag to disable colors until a new version of chezmoi is released.

**Comment by omry** [comment]
Great, thanks for the quick fix.

**Comment by omry** [comment]
Using this for a few basic questions (let me know if there is another preferred channel):
After adding a file (chefmoi add ~/.gitconfig), should I manually go into the git repo (~/.local/share/chezmoi) to commit and push or is there a chezmoi command I can use for that?

**Comment by twpayne** [comment]
Fine to ask questions here - there aren't any other channels - and this will help me improve the documentation.

After running `chezmoi add`, there are several options to make the commit:

* `chezmoi source` runs a git command in the source directory. So you can run:

    ```
    chezmoi source add .
    chezmoi source commit -m "Add .gitconfig"
    ```

  This runs `git add` and `git commit` in the source directory.

* I personally tend to use `chezmoi cd` to switch to the source directory quickly and use my usual git aliases to make my commits.

* Finally, there's the `autocommit` and `autopush` options, [described in the how to](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#automatically-commit-and-push-changes-to-your-repo) for fully hands-off operation. These should work (no known bugs), but are not well tested. Any feedback on these would be appreciated.

**Comment by omry** [comment]
Cool. I figured there might be a shortcut, but I was expecting something like `chezmoi git`. could be a nice alias to use (along with other supported scms).

also good to know about cd.
once I get more comfortable with chezmoi I will try the autocommit/autopush feature.

**Comment by twpayne** [comment]
> Cool. I figured there might be a shortcut, but I was expecting something like chezmoi git. could be a nice alias to use (along with other supported scms).

Great idea! I'll add this.

**Comment by omry** [comment]
By the way, did you see an uptick in new users after your FLOSS weekly interview?
I am going to be interviewing in February for my project, [Hydra](https://hydra.cc).

**Comment by twpayne** [comment]
> By the way, did you see an uptick in new users after your FLOSS weekly interview?

Yes, it felt like there was an uptick in the rate of change of stars on GitHub. I don't have any hard data or actual user numbers, and don't want to add any sort of monitoring to chezmoi (even though it would be really useful to know what features people are actually using). The biggest GitHub star spike by far came from floating near the top of Hacker News for a day or so.

> I am going to be interviewing in February for my project, Hydra.

Great! I will be sure to tune in.

**Comment by omry** [comment]
Yeah, I feel the same about adding a call-home feature.

Feel free to check out the project ahead of time!
Even though Python may not be your thing, it can be very useful as yaml configuration generator.

**Comment by omry** [comment]
I am using [this](https://seladb.github.io/StarTrack-js/) to see the chart of starts for Hydra.

**Comment by omry** [comment]
Hi Tom!
1. did you see this?
https://fedoramagazine.org/take-back-your-dotfiles-with-chezmoi/

2. I had my FLOSS weekly Hydra interview yesterday, take a look! :)

**Comment by twpayne** [comment]
Thanks @omry! I saw a sudden increase in users and a did a bit of digging to find out that it was @blackphidora's article that triggered the boost.

Will check out your FLOSS podcast :)

**Comment by Blackphidora** [comment]
@twpayne Happy to spread the good news :)
