### ISSUE TITLE
chezmoi: unknown flag: --autotemplate

### ISSUE THREAD

**Issue by TheBrainScrambler** [twpayne/chezmoi#566]
Running `chezmoi add --template --autotemplate ~/.` drops this error `chezmoi: unknown flag: --autotemplate`, but the Github and the official website says you can use it. So, do I have to write my templates manually ?
Also, when trying to look for the template documentation on https://godoc.org/, I get this nice SSL error : `SEC_ERROR_OCSP_UNAUTHORIZED_REQUEST` would just like to know if the problem comes from me or the server.

**Comment by twpayne** [comment]
Please follow the steps in the [issue template](https://github.com/twpayne/chezmoi/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and report what you find here so I can help fix your problem.

What is the exact URL are you trying to access at godoc.org? The only reference to godoc.org in chezmoi is https://godoc.org/text/template. The error sounds like a problem local to your machine or network and is certainly unrelated to chezmoi.

**Comment by TheBrainScrambler** [comment]
Ok sorry for being too fast,
for the godoc.org problem, it happens if I access any URL, so yes it is probably a local problem.

**Describe the bug : ** When trying to append the `--autotemplate` when trying to create a new template with `-T`, it refuses to do it, and I get this error : `chezmoi: unknown flag: --autotemplate`
**To reproduce : ** Run `chezmoi add --template --autotemplate ~/.gitconfig`. You can replace .gitconfig by any dotfile
**Expected behavior : ** The behavior described by the [how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-templates-to-manage-files-that-vary-from-machine-to-machine)
**Output of command with `--verbose` : ** `chezmoi: unknown flag: --autotemplate` verbose flag doesn't say something more than without it
**Output of `chezmoi doctor` : ** 
` ok: /home/the_pumpkin_man/.local/share/chezmoi (source directory, perm 700)
     ok: /home/the_pumpkin_man (destination directory, perm 700)
warning: /home/the_pumpkin_man/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /run/current-system/sw/bin/nvim (editor)
warning: vimdiff (merge command, not found)
     ok: /run/current-system/sw/bin/git (source VCS command, version 2.23.1)
warning: gpg (GnuPG, not found)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
     ok: /run/current-system/sw/bin/keepassxc-cli (KeePassXC CLI, version 2.4.3)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)`
**Additional context : ** I am actually on NixOS, maybe this could have an impact.

Thanks in advance for your help.

**Comment by twpayne** [comment]
It looks like you're using a very old version of chezmoi, maybe 1.5.5, or even older. `--autotemplate` was added as a flag in version 1.6.1. Please can you try with a more recent version of chezmoi.

**Comment by twpayne** [comment]
Are you using Nix perchance? ;)

**Comment by TheBrainScrambler** [comment]
Yes, as NixOS user I'm using Nix. And you're right, if you look at https://nixos.org/nixos/packages.html?channel=nixos-19.09&query=chezmoi (I'm using nixos-19.09 channel) it is version 1.5.5. I can't retrieve a more recent version, as I want to stay in a stable channel, so gonna wait until it gets updated. I can still use templates manually.
Thank you for your help and your quick replies, that's really impressive ! :o
Closing it
