### ISSUE TITLE
autocommit insufficient documentation

### ISSUE THREAD

**Issue by poldi1405** [twpayne/chezmoi#572]
Hi,
after enabling autoCommit & autoPush and editing a config chezmoi tries to read the commit-message template but under the path `/home/templates/COMMIT_MESSAGE.tmpl` which I find odd.

I haven't been able to find the place in the docs where that path is explained (or how to change it) and a documentation of special autoCommit & -Push Variables like `{{ .changedFile }}` if they exist. I'd love to add this documentation myself but I've just recently started using chezmoi and I haven't even taken a look at the codebase.

`chezmoi doctor` output:
```
warning: version 1.7.11
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/moritz/.local/share/chezmoi (source directory, perm 700)
     ok: /home/moritz (destination directory, perm 700)
     ok: /home/moritz/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/fish (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.25.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Please include the output of chezmoi doctor in your issue.

**Comment by poldi1405** [comment]
added.

**Comment by twpayne** [comment]
Thanks. How did you install chezmoi?

I think what's happening here is:

* The file `COMMIT_MESSAGE.tmpl` is normally built in to the chezmoi binary using [`packr2`](https://github.com/gobuffalo/packr/tree/master/v2).
* This requires an extra build step when building chezmoi from source, which generates an extra source file which is not checked in to chezmoi's git repo.
* This build step is executed in the "official" release builds but is not mentioned in the install or contributing docs, and might be missing from some chezmoi packages.

I think the solution is to include the generated file in chezmoi's git repo.

**Comment by poldi1405** [comment]
I installed it using pacman which does not have this file included (probably for that reason). Thank you very much, I'll just take it from a release for now.

**Comment by twpayne** [comment]
Thank you for reporting this. With #575, this should be fixed :)
