### ISSUE TITLE
Preserve OLDPWD when executing `chezmoi cd`

### ISSUE THREAD

**Issue by Azza292** [twpayne/chezmoi#578]
## Is your feature request related to a problem? Please describe.

When executing:
```bash
$ chezmoi cd
```
After commiting changes, I would like to return to my previous directory with:
```shell 
$ cd -
```
Currently the output is:
```shell
$ cd -
bash: cd: OLDPWD not set
```
## Describe the solution you'd like

I would expect `OLDPWD` to be set so I can return to my previous working directory.

## Describe alternatives you've considered

Manually changing the back to the desired directory.

**Comment by twpayne** [comment]
`chezmoi cd` opens a subshell in the source directory. It doesn't change the directory of the current shell. You can go back to the previous directory by exiting the subshell, for example with `exit` or `Ctrl-D`.

As far as I know, there is no way for chezmoi to be able to change the directory of the current shell itself, but there is a workaround:

If you want to change directory of the current shell, you can use:

```sh
$ cd $(chezmoi source-path)
```

then `cd -` will work as you expect.

You can create an alias for this, for example:

```sh
$ chezmoi-cd() { cd $(chezmoi source-path) }
$ chezmoi-cd
$ cd -
```

Hope this helps!

**Comment by Azza292** [comment]
That's perfect!

Thank you for the incredibly quick reply and explanation.
