### ISSUE TITLE
Chezmoi crashes my computer when I try to diff a massive log file

### ISSUE THREAD

**Issue by johnhamelink** [twpayne/chezmoi#583]
## Describe the bug

When running `chezmoi diff` with a big IRC log file accidentally in its list of source state, chezmoi will happily attempt to diff the file, even if that crashes my computer.

## To reproduce

```
chezmoi add ~/.weechat/logs
chezmoi diff
```

## Expected behavior

A warning message letting me know the file has been skipped because its too big might be better in this case?

**Comment by twpayne** [comment]
Please include the output of `chezmoi doctor` in your report.

What do you mean by "crashes your computer" exactly? Kernel panic? Blue screen of death?
