### ISSUE TITLE
chezmoi cd - custom shell command

### ISSUE THREAD

**Issue by elrond79** [twpayne/chezmoi#596]
## Is your feature request related to a problem? Please describe.

One of the operating systems I use is windows, but unfortunately, I hate the default terminal / shell.  I'd love it if I could specify a custom shell to execute (ie, git-bash) when `chezmoi cd` is run.

## Describe the solution you'd like

A configuration setting to set a custom command that `chezmoi cd` will execute instead of the platform default. (Ideally, you could set this per OS.)

## Describe alternatives you've considered

Just dealing with windows' cmd.  I mean, I can do it, but it makes my heart-bunny cry.

**Comment by twpayne** [comment]
Nice idea! #597 adds this. Are you able to test this? I've tested it on macOS, but don't have access to a Windows machine.

**Comment by twpayne** [comment]
> (Ideally, you could set this per OS.)

To set this per-OS, I'd do this using a [config file template](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#create-a-config-file-on-a-new-machine-automatically). In your case, I think it would look something like:

```
{{ if eq .chezmoi.os "windows" }}
[cd]
  command = "git-bash"
{{ end }}
```

**Comment by elrond79** [comment]
Woo hoo! Success! Tried out the PR, and it worked great on windows! Thanks muchly!
