### ISSUE TITLE
`unmanaged` is listing chezmoi directory itself

### ISSUE THREAD

**Issue by pvinis** [twpayne/chezmoi#599]
## Describe the bug

When I run `chezmoi unmanaged`, I guess it shouldn't list files under `.local/share/chezmoi`, right?

## To reproduce

- Run `chezmoi unmanaged`
- Look at output containing `.local/share/chezmoi`

## Expected behavior

chezmoi files should not be in the list

## Output of command with `--verbose`

```
$ chezmoi command --verbose
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
I think this is debatable. chezmoi normally doesn't manage files in `~/.local/share/chezmoi`, and it can be argued the same for `~/.config/chezmoi`. However, I don't think these add too much noise to the output of `chezmoi unmanaged`, and as they aren't managed by chezmoi it's actually correct that they're included in the output. Thanks for raising the idea though!
