### ISSUE TITLE
Print out Template Variables

### ISSUE THREAD

**Issue by pvinis** [twpayne/chezmoi#601]
## Is your feature request related to a problem? Please describe.

It would be nice to be able to run something like `chezmoi print` or something, and get a list of the "template variables", like `.chezmoi.hostname` and `.chezmoi.orRelease` etc.

It would be useful to when we want to make sure that the values we expect are the ones that actually exist.

**Comment by twpayne** [comment]
`chezmoi data` does exactly this.

Please take a few minutes to read through [chezmoi's documentation](https://github.com/twpayne/chezmoi/tree/master/docs).

**Comment by pvinis** [comment]
Damn, I read and searched and still somehow missed this. Sorry and thanks.
