### ISSUE TITLE
Add custom prefix

### ISSUE THREAD

**Issue by nb5p** [twpayne/chezmoi#613]
## Is your feature request related to a problem? Please describe.

No. Suggest to add custom prefix function to make the directory look cleaner.

## Describe the solution you'd like

in config file
```
"run_" = "_run/"
...
```
expected result
```
/run_once_a.sh => /_run/once_a.sh
/run_once_b.sh => /_run/once_b.sh
```

**Comment by twpayne** [comment]
Thank you for the suggestion. This would be complex to implement. For example, in the example you give, the matching of prefixes has moved from the basename of the file to the name of one of its parent directories.

Overall, I think the complexity of this feature far outweighs the gain in functionality.
