### ISSUE TITLE
Site - chezmoi.io - Some relative links within pages not working as intended (404)

### ISSUE THREAD

**Issue by keevan** [twpayne/chezmoi#614]
## Describe the bug

e.g. Home page, under the section how do I start with chezmoi, the various links use links that work on github.com but not on chezmoi.io, resulting in a 404 page.

It should link to:
https://www.chezmoi.io/docs/install/
but instead links to:
https://www.chezmoi.io/docs/INSTALL.md

Relevant files that could be used to fix issue:
https://github.com/twpayne/chezmoi/blob/master/chezmoi.io/content/docs/menu/index.md

Relevant file with issue:
https://github.com/twpayne/chezmoi/blob/master/chezmoi.io/content/_index.md

## To reproduce

As above

## Expected behavior

Link should resolve to correct page

## Output of command with `--verbose`

N/A

## Output of `chezmoi doctor`

N/A

## Additional notes

Just thought it would be worth fixing up if they stumbled on to the chezmoi.io page via the search engine instead of the github page. Of course it would be great if the content needn't be duplicated.

**Comment by twpayne** [comment]
Thanks very much for reporting this :)
