### ISSUE TITLE
Mark autoCommit and autoPush as stable

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#619]
autoCommit and autoPush were introduced in #432 based on @lewisacidic's suggestion.

chezmoi users, what are your experiences with autoCommit and autoPush? What needs fixing before this can be marked stable?

cc people who've been involved in the discussion:
@lewisacidic @olfway @daniel-illi @lolilijve @poldi1405 @skupfer @aBARICHELLO @kortsi

**Comment by aBARICHELLO** [comment]
Works fine for me, the only problem I had was due to missing template files since I installed chezmoi through Arch's AUR.

**Comment by kortsi** [comment]
I have been using it for awhile now and it has worked flawlessly apart from the mentioned missing template file problem, which is now fixed.

**Comment by lewisacidic** [comment]
Been working well for me too, thanks for taking on board the feature suggestion!
