### ISSUE TITLE
`chezmoi update` and `-a` flag

### ISSUE THREAD

**Issue by pvinis** [twpayne/chezmoi#627]
## Describe the bug

I couldn't find a way to disable the applying part of `update`. I want to just fetch/pull my changes, but without applying them.

The docs say that there is the `-a` flag to apply, but then it also says that this flag is enabled by default, so how am I supposed to do this? 🤔 

## To reproduce

Run `chezmoi update` and `chezmoi update -a`, they will both apply the diffs. I don't know how to not apply them.

## Expected behavior

To have a way to only pull and not apply them.

## Output of command with `--verbose`

```
$ chezmoi command --verbose
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
To just fetch your changes you can run:

    chezmoi git pull -- --rebase

To see what changes would be applied, you can run:

    chezmoi diff

Hope this helps, and please re-open this issue if you have further questions.

**Comment by pvinis** [comment]
Would it make sense to have a `chezmoi pull`?

**Comment by twpayne** [comment]
I don't think it's worth it, as people use git in different ways (e.g. they might not want to use `--rebase`) and it only saves a few characters of typing.

**Comment by pvinis** [comment]
Ok. I'll make an alias for me I guess then.

How about the `-a` flag? It exists but it's on by default, and there is no way to turn it off. Would it make sense to remove the flag or better to add a way to disable it?

**Comment by twpayne** [comment]
Can you give a link to or an example of the `-a` flag you're talking about? There's one in `chezmoi edit`, which is off by default, but no other, unless I'm missing something.

**Comment by pvinis** [comment]
https://github.com/twpayne/chezmoi/blob/master/cmd/update.go#L28

**Comment by pvinis** [comment]
<img width="740" alt="Screen Shot 2020-03-13 at 18 12 00" src="https://user-images.githubusercontent.com/100233/76643852-2aed2980-6556-11ea-93b0-d0b1a1bc16e8.png">
And here I guess, in the Flags section.

**Comment by twpayne** [comment]
Thank you! I missed that somehow.

You can turn off the `--apply` flag with:

    chezmoi update --apply=false

As well as `false` you can pass any value parsed by [`strconv.ParseBool`](https://pkg.go.dev/strconv?tab=doc#ParseBool), e.g. `0`, `f`, `F`, and `False`.

**Comment by pvinis** [comment]
Awesome! That's easy enough then. `alias chepull=che update --apply=false` :D and I already have `alias che=chezmoi`.

**Comment by twpayne** [comment]
Great! Thanks again for opening this issue, and happy that chezmoi is useful to you :)
