### ISSUE TITLE
Chezmoi fails with error permission denied in termux

### ISSUE THREAD

**Issue by ibnishak** [twpayne/chezmoi#632]
## Describe the bug
Chezmoi apply fails with error `chezmoi:open /proc/sys/kernel/version: permission denied` in termux version 0.92, Android version 9
## To reproduce
Run chezmoi apply
## Output of `chezmoi doctor`

```
$ chezmoi doctor
```
```
ok: version 1.7.16, commit ce06ed92b682852937c45e40ae313cbf39ed81cd, built at 2020-03-04T22:58:22Z
     ok: runtime.GOOS linux, runtime.GOARCH arm64
     ok: /data/data/com.termux/files/home/.local/share/chezmoi (source directory, perm 700)
     ok: /data/data/com.termux/files/home (destination directory, perm 700)
warning: /data/data/com.termux/files/home/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /data/data/com.termux/files/usr/bin/bash (shell)
     ok: /data/data/com.termux/files/usr/bin/applets/vi (editor)
warning: vimdiff (merge command, not found)
     ok: /data/data/com.termux/files/usr/bin/git (source VCS command, version 2.25.2)
warning: gpg (GnuPG, not found)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context
* Chezmoi init works
* Chezmoi downloads the git repo successfully

**Comment by twpayne** [comment]
Thank you very much for reporting this bug. Termux is quite different to normal Linux, but there's no reason why chezmoi shouldn't support it. This should be fixed with #633.

Note that if you're using chezmoi's script support then you might need to tweak them for Termux - see #445.

**Comment by ibnishak** [comment]
Actually I have been using chezmoi successly in my old android phone (Android 6). I recently bought a new phone with Android 9.0

I tried installing chezmoi using the `curl` one liner. It installed successfully and even downloaded my existing repo from gitlab. However `chezmoi apply` failed. 

So I went ahead and tried compiling chezmoi in device using termux. Using the compiled binary I tried the command `chezmoi apply` again. This time it failed with the error `LookupGroupId not implemented in android`

**Comment by ibnishak** [comment]
No, it is not related to differences in `shebang` between linux and termux

**Comment by twpayne** [comment]
> So I went ahead and tried compiling chezmoi in device using termux. Using the compiled binary I tried the command `chezmoi apply` again. This time it failed with the error `LookupGroupId not implemented in android`.

This is a different problem to the one reported in this issue.

**Comment by twpayne** [comment]
See https://github.com/twpayne/chezmoi/blob/master/cmd/config.go#L320-L334.

Basically, chezmoi assumes that if cgo is enabled then `user.LookupGroupId` should work. However, this is clearly not the case on Android (because users and groups are used very differently on Android compared to Linux). I think the correct fix is to silently ignore any errors from `user.LookupGroupId`.

**Comment by ibnishak** [comment]
Confirming resolution of issue. Building against commit id `d22a3cf503596261e54790e61f4dcb80bf170690` resolves the issue. Hope it finds its way to master and binaries.
