### ISSUE TITLE
chezmoi apply stopped running my run_once_install-packages.sh script

### ISSUE THREAD

**Issue by nawordar** [twpayne/chezmoi#636]
## Describe the bug

I use `run_once_install-packages.sh` script to synchronize packages between my machines. Yesterday, it suddenly stopped launching on `chezmoi apply` command. When I launch it manually using `$(chezmoi source-path)/run_once_install-packages.sh` it works as usual.

## To reproduce

Clone [my repository](https://github.com/nawordar/dotfiles) and run `chezmoi apply`.

## Expected behavior

Execute `$(chezmoi source-path)/run_once_install-packages.sh` on file change.

## Output of command with `--verbose`

```
$ chezmoi command --verbose

```
No output, return code 0.

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version dev
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/nawordar/.local/share/chezmoi (source directory, perm 700)
     ok: /home/nawordar (destination directory, perm 710)
warning: /home/nawordar/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /bin/nvim (editor)
     ok: /bin/vimdiff (merge command)
     ok: /bin/git (source VCS command, version 2.25.2)
     ok: /bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
     ok: /bin/pass (pass CLI, version 1.7.3)
warning: vault (Vault CLI, not found)
```

## Additional context
I have tried:
- to reduce amount in lines in this code, but it did not changed anything;
- to create another file `run_once_test.sh` but it was not run by `chezmoi` either.

**Comment by nawordar** [comment]
I just had error in my `.chezmoiignore`, closing.

**Comment by twpayne** [comment]
Thanks very much for reporting here and also reporting that you found the fix :)

Please excuse the "invalid" label - it's just to indicate that this turned out not to be a bug in chezmoi.

Thanks for using chezmoi!
