### ISSUE TITLE
Misleading documentation: Handle configuration files which are externally modified

### ISSUE THREAD

**Issue by jsamr** [twpayne/chezmoi#637]
I think [the example](https://www.chezmoi.io/docs/how-to/#handle-configuration-files-which-are-externally-modified) has a typo (should replace `.` with `dot`):

```
mkdir -p $(chezmoi source-path)/.config/Code/User
echo -n "{{ .chezmoi.sourceDir }}/settings.json" > $(chezmoi source-path)/.config/Code/User/symlink_settings.json.tmpl
```
should be replaced with

```
mkdir -p $(chezmoi source-path)/dot_config/Code/User
echo -n "{{ .chezmoi.sourceDir }}/settings.json" > $(chezmoi source-path)/dot_config/Code/User/symlink_settings.json.tmpl
```

Otherwise
```
chezmoi apply -v
```
is no-op.

**Comment by nawordar** [comment]
I was confused by that example too and I can confirm that it should be `dot_` not `.`

**Comment by twpayne** [comment]
Thanks for reporting this @jsamr and thanks for the fix @nawordar :)
