### ISSUE TITLE
Misleading documentation feature: 'Declarative' section

### ISSUE THREAD

**Issue by ihommani** [twpayne/chezmoi#639]
## Describe the bug
When the documentation writes: 
`Declarative: you declare the desired state of files, directories, and symbolic links in your **home directory** and chezmoi updates your home directory to match that state.`

## To reproduce
N/A

## Expected behavior
`Declarative: you declare the desired state of files, directories, and symbolic links in your **source directory** and chezmoi updates your home directory to match that state.`

## Additional context
If it's OK, I can author a pull request.

**Comment by twpayne** [comment]
Great spot! A pull request would be very welcome, thank you. Note that you'll need to run `go generate` after updating the documentation (see the [contributing guide](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#documentation-and-templates-changes)).

**Comment by twpayne** [comment]
Just as a thought on this, this documentation is in `README.md`, which is read by  people before they are familiar with chezmoi's concepts of source directories and target directories. Is there a wording that would convey the meaning without requiring the user to understand the words "source directory" in the context of chezmoi?

**Comment by ihommani** [comment]
@twpayne , I see the point. Reading the README, we already mentioned the notion of "source of truth". Would it be a better fit that "source directory" in this context? I think so. 
Note: I first spoted this enhancemnet on chezmoi.io website.  Is it smthg that I can also fix or are you the only one in charge for this one?

**Comment by twpayne** [comment]
> Reading the README, we already mentioned the notion of "source of truth". Would it be a better fit than "source directory" in this context? I think so.

Agreed.

> Note: I first spoted this enhancemnet on chezmoi.io website. Is it smthg that I can also fix or are you the only one in charge for this one? I guess there is some kind of synchronisation (through chezmoi :) )

Currently I need to run a command manually to update the website from the documentation. See:

https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#updating-the-website

Updating chezmoi.io requires push access to this repo, which only I have at the moment.

**Comment by ihommani** [comment]
PR done

**Comment by twpayne** [comment]
Fixed by @ihommani in #641.

Thank you!
