### ISSUE TITLE
Tagged version does not end up in the binary

### ISSUE THREAD

**Issue by cailloumajor** [twpayne/chezmoi#643]
## Describe the bug

After installing chezmoi according to the documentation, `chezmoi --version` and `chezmoi doctor` all two return `version dev`.

## To reproduce

Install chezmoi following the documentation. I tested those two methods :
- one-line binary install (`curl -sfL https://git.io/chezmoi | sh`)
- Debian package install, downloaded from the repository releases page

## Expected behavior

Printed version should be the tagged version.

## Output of command with `--verbose`

```
$ chezmoi --version --verbose
chezmoi version dev
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version dev
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/nono/.local/share/chezmoi (source directory, perm 700)
     ok: /home/nono (destination directory, perm 755)
warning: /home/nono/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/code (editor)
warning: vimdiff (merge command, not found)
     ok: /usr/bin/git (source VCS command, version 2.25.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.20)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context

Output of one-line binary install:
```
$ curl -sfL https://git.io/chezmoi | sh
twpayne/chezmoi info checking GitHub for latest tag
twpayne/chezmoi info found version: 1.7.17 for v1.7.17/linux/amd64
twpayne/chezmoi info installed ./bin/chezmoi
twpayne/chezmoi info installed ./bin/chezmoi
```

**Comment by twpayne** [comment]
Thank you very much for the clear and complete bug report :)

#644 fixes the problem, and I'll tag a new version of chezmoi to include this fix.

**Comment by cailloumajor** [comment]
Thank you for this great project and for the fast resolution :100:
