### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by louwers** [twpayne/chezmoi#645]
https://www.chezmoi.io/docs/quick-start/

contains a link to

https://www.chezmoi.io/docs/quick-start/HOWTO.md

however it should link to

https://www.chezmoi.io/docs/how-to/

**Comment by twpayne** [comment]
Thank you very much for reporting this :)

Fixed with #646. The links in the markdown files are converted to links on the website by a small script, which didn't work for relative URLs.
