### ISSUE TITLE
How to restore a binary file from 1Password ?

### ISSUE THREAD

**Issue by bric3** [twpayne/chezmoi#650]
## What exactly are you trying to do?

I'm trying to get gnupg binary files from 1password.

## What have you tried so far?

What approaches have you tried to 

```bash
❯ chezmoi add --template --autotemplate .gnupg/trustdb.gpg
❯ chezmoi add --template --autotemplate .gnupg/pubring.kbx
❯ chezmoi edit .gnupg/trustdb.gpg
❯ chezmoi edit .gnupg/pubring.kbx
```

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [x] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [x] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```bash
$ chezmoi command --verbose
```

I'm not sure this section is relevant, as I'm trying to edit the _binary file template_ to replace it by `{{- onepasswordDocument "uuid" -}}` but vim complains quite a bit.

Is there a procedure to restore secret binary files ?

## Output of `chezmoi doctor`

```bash
❯ chezmoi doctor
     ok: version 1.7.18, commit 8284da771e8db09a6b9a4651154bb5f7820a62f0, built at 2020-03-29T15:18:14Z, built by goreleaser
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/bric3/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/bric3 (destination directory, perm 755)
warning: /Users/bric3/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/local/bin/vi (editor)
     ok: /usr/local/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.26.0)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.17)
     ok: /usr/local/bin/op (1Password CLI, version 0.9.4)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Generally speaking, binary files aren't amenable to templating or editing with a normal text editor. Something as trivial as changing or adding or removing a single character will often break the binary file completely.

You can [edit binary files in vim](https://vi.stackexchange.com/questions/343/how-to-edit-binary-files-with-vim), but unless you have a good understanding of the structure of the binary file, any edit will most likely result in a broken file.

Realistically, the only way to reliably modify `.gpg/trustdb.gpg` and `.gpg/pubring.kbx` is through the `gpg` command itself. chezmoi can't really help you here.

To get files out of 1Password, you can use the `onepasswordDocument` function that you've already identified, but you should probably use it like this:

    {{- onepasswordDocument "uuid" -}}

Note the extra `-`s: these strip any trailing and following whitespace that might have been added by your editor (e.g. a newline at the end of the template file).

This probably wasn't the answer you wanted, but I hope it helps.

**Comment by bric3** [comment]
Hi thanks for replying that fast !!!

Actually I don't want to template binary files, I was just trying to get a binary file from 1Password, using `chezmoi edit ...` isn't very friendly because it opens the template file which is binary.

Actually I had to :

```bash
❯ chezmoi cd
❯ truncate --size 0 private_dot_gnupg/private_trustdb.gpg.tmpl
# then edit the template file to app the go-template
```

While this appear to work I wanted to check I didn't screw up, so I expected to be able to verify the files are the same using the following command, but `chezmoi` complains I'm not sure why

```bash
❯ chezmoi apply --debug --verbose --dry-run .gnupg/trustdb.gpg --destination /Users/bric3/tmp
chezmoi: /Users/bric3/.gnupg/trustdb.gpg: outside target directory
```

----

I think that `chezmoi` could add a file as template, e.g. something like

```bash
chezmoi add --template --as-onepassword-document uuid .gnupg/trustdb.gpg
```

**Comment by twpayne** [comment]
OK, thanks for the clarification

For some things, it's easier to edit the files in the source state directly. Here's how I'd suggest doing it:

    chezmoi cd
    mkdir -p private_dot_gnupg
    echo -n '{{- onepasswordDocument "uuid" -}}' > private_dot_gnupg/private_trustdb.gpg.tmpl

The "outside target directory" errors you are getting are because the filenames are relative to the current directory (unless you specify an absolute path). Try instead:

    chezmoi apply --debug --verbose --dry-run /Users/bric3/tmp/.gnupg/trustdb.gpg --destination /Users/bric3/tmp

For the adding a file as a template idea, it's interesting. I'd like to keep chezmoi as neutral as possible with regard to password managers, i.e. I don't want to add password-manager-specific flags to top-level commands like `chezmoi add`. However, I will improve the documentation.

Let me know how you get on with the above.

**Comment by bric3** [comment]
Cool, "templating" works, and the apply in temporary too, thanks a lot !!!

```bash
❯ b3sum /Users/bric3/tmp/.gnupg/trustdb.gpg
f0783c3910b426de0fb4a48131843ce8603071812624e99fc9ae711a28cf30ff  /Users/bric3/tmpcm/.gnupg/trustdb.gpg
❯ b3sum /Users/bric3/.gnupg/trustdb.gpg
f0783c3910b426de0fb4a48131843ce8603071812624e99fc9ae711a28cf30ff  /Users/bric3/.gnupg/trustdb.gpg
```

----

Just to let you know `chezmoi` doesn't auto create directories

```bash
❯ chezmoi apply --debug --verbose /Users/bric3/tmpcm/.gnupg/trustdb.gpg --destination /Users/bric3
2020/04/01 21:56:19 IdempotentCmdOutput("/usr/local/bin/op get document ...")
2020/04/01 21:56:20 IdempotentCmdOutput("/usr/local/bin/op get document ...") (1.817571823s)
2020/04/01 21:56:20 WriteFile("/Users/bric3/tmp/.gnupg/trustdb.gpg", _, 0600, _) == stat /Users/bric3/tmp/.gnupg: no such file or directory (22.796µs)
install -m 600 /dev/null /Users/bric3/tmp/.gnupg/trustdb.gpg: stat /Users/bric3/tmp/.gnupg: no such file or directory
chezmoi: stat /Users/bric3/tmp/.gnupg: no such file or directory
```

Instead I had to apply the `.gnupg` directory.

```bash
❯ chezmoi apply --debug --verbose /Users/bric3/tmp/.gnupg/ --destination /Users/bric3/tmp
```

**Comment by twpayne** [comment]
Great that it works :)

> Just to let you know `chezmoi` doesn't auto create directories
> Instead I had to apply the `.gnupg` directory.

Ah, I see what is happening here. `chezmoi apply`, when given a list of targets, only updates those specific targets, and not any of their parent directories. As `.gnupg` did not already exist in `/Users/bric3/tmp`, you got the "no such file or directory" error. I think this behavior is OK, as people will normally use `chezmoi apply` without any arguments (meaning apply everything).

**Comment by twpayne** [comment]
I updated the docs in #651. Please re-open this issue if needed.

**Comment by bric3** [comment]
Yes that's what I figured. Thanks for the help it's much appreciated!

----

For usability I'd really consder having a command that can create the template for you for a whole file.

**Comment by bric3** [comment]
@twpayne Hi again, I was thinking about a thing, currently I'm using 1password to store the binary content of some gpg files. I also notice that chezmoi has a knowledge about gpg for ecnrypting files.

Now GPG keys can be exported this way

```bash
gpg -a --export my@email.com > bric3-public-gpg.key
gpg -a --export-secret-keys my@email.com > bric3-secret-gpg.key
gpg --export-ownertrust > bric3-ownertrust-gpg.txt
```

and imported this way

```bash
gpg --import bric3-secret-gpg.key
gpg --import-ownertrust bric3-ownertrust-gpg.txt
```

I wonder if it would be a feature to consider to support gpg keys import using templates in combination with password manager. I know one could probably use a _run_ script that does it, but as mentionned in the doc this kinda break the declarative approach.

I'm not sure of the form this is exported as different files, and should be imported form different files. Maybe put these in a chezmoi.toml key

```
{{- onepasswordDocument "uuid" | gpgImport -}}
```

```
{{- onepasswordDocument "uuid" | gpgImportOwnerTrust -}}
```

**Comment by twpayne** [comment]
> I wonder if it would be a feature to consider to support gpg keys import using templates in combination with password manager. I know one could probably use a run script that does it, but as mentionned in the doc this kinda break the declarative approach.

`gpg --import` modifies global state so it's fundamentally not compatible with a declarative approach. A `run_once_` script is most applicable here.

**Comment by bric3** [comment]
Hi,

Ah yes indeed, thanks for the precision. So the _run once_ script could invoke the client command directly then ?

**Comment by twpayne** [comment]
Yes, exactly.

I'd imagine something like the following. Please note that I haven't run or tested this code.

`run_once_gpg-import.sh`:

```sh
#!/bin/sh

# configuration
SECRET_KEY_UUID="..."
OWNER_TRUST_UUID="..."

# create a private temporary directory and ensure that it is removed
tmpdir=$(mktemp -d)
cleanup() {
  rm -rf $tmpdir
}
trap cleanup EXIT
chmod 700 $tmpdir

# extract files from 1password
op get document $SECRET_KEY_UUID > $tmpdir/secret-key
op get document $OWNER_TRUST_UUID > $tmpdir/owner-trust

# import files
gpg --import $tmpdir/secret-key
gpg --import-ownertrust $tmpdir/owner-trust
```

**Comment by bric3** [comment]
Cool! I didn't think about the temporary folder removal trick.
Thanks!

**Comment by bendavies** [comment]
@bric3 does your [blog post](https://blog.arkey.fr/2020/04/01/manage_dotfiles_with_chezmoi/) related to this actually work?
I found that following your blog post does not restore the secret keys. I had to use the above bash script instead.

**Comment by bric3** [comment]
Yeah not as much as I wanted. At first it was ok, but then I had to sync new keys. And it got messier. Instead I am now using armored export / import which was easier to got right with gpg.

That said the binary templates do work.
`{{- onepasswordDocument "eggghhh..." -}}` just make there's no other characters around.
