### ISSUE TITLE
Managed command

### ISSUE THREAD

**Issue by remigourdon** [twpayne/chezmoi#659]
## Is your feature request related to a problem? Please describe.

I generally like to have a quick way to access my configuration files for edits and the fact that chezmoi offers the ability to edit and apply in one go is very useful to me. Unfortunately there doesn't seem to be a command that allows listing the target filenames in order to select from them and pass them to `chezmoi edit -a`.

## Describe the solution you'd like

I see 2 options to bring this capability:

* a **managed** command that would list the target filenames managed by chezmoi
* allow the **edit** command to take source filenames (maybe using an optional switch ?)

I would definitely favor the first option as getting an accurate listing of source filenames can be tricky (there are files in the chezmoi directory that aren't actually managed configuration files). I can also see a list of managed target filenames being useful in other contexts (not only for edits).

## Describe alternatives you've considered

Currently I resort to a couple bash scripts I wrote that parse the chezmoi source directory and output the matching target filenames, which I then select from using fzf and pass to `chezmoi edit -a`.

## Additional comments

I have some basic go knowledge so if one one the 2 solutions appear like a good one I would be happy to try to implement it myself and submit a pull request.

Thanks from a happy (new) user of chezmoi!

**Comment by twpayne** [comment]
Thanks for the great suggestion and happy that you're enjoying chezmoi!

This is a very good idea, and a nice complement to the existing `unmanaged` command.

Right now I'm re-working the internals of chezmoi in #654, so now is not a great time to submit PRs to the existing code, but once the rework is done it should be straightforward to add the command.

What's the reasoning behind having the `edit` command take source file names? There should be a 1:1 mapping between source file names and target names and if we just use the target name then you don't need to remember what attributes are present in the source file name.

**Comment by remigourdon** [comment]
Alright I will keep an eye on #654 and look at submitting a PR once this rework is in.

As far as the suggestion for the `edit` command I do think the way you have it now, taking target filenames, is the right way to do it. My point was merely to provide a workaround to my problem since it is easier to grab all source files for selection than finding all target files in a home directory.

**Comment by twpayne** [comment]
Note that you can get a list of source files right now using `chezmoi dump` and [`jq`](https://stedolan.github.io/jq/):

    chezmoi dump | jq -r '.. | .sourcePath? | values'

Advance warning: the structure of `chezmoi dump`'s output might change in version 2 (after #654) but this might be enough for now.

**Comment by twpayne** [comment]
@remigourdon if you'd like to submit a PR to the current code then I'd be very happy. #654 is in progress, but will take a bit of time, and will not change the user interface. So we (you?) can implement this now and we can port this forward when #654 gets merged.

**Comment by remigourdon** [comment]
Funny enough I used a variation of this jq command originally to do just this, but when I started moving secrets to bitwarden and since my vault is generally locked, every call to `chezmoi dump` required an unlock. So I moved to a dirty method to retrieve the target file names from the source ones.

Will look at submitting this PR over the weekend!
