### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by nielsk** [twpayne/chezmoi#666]
I have this problem on Arch and Ubuntu 20.04 beta. In Ubuntu I tried the snap and the binary install.
When I run ‘chezmoi apply’ I get the following error:
```
chezmoi: fork/exec /tmp/102609852.test262.js: exec format error
```
and nothing gets applied apparently.

**Comment by nielsk** [comment]
When I run chezmoi -v apply:
````
chezmoi -v apply
const fs = require("fs")
const path = require("path")
const run = require("test262-parser-runner")
const parse = require("..").parse

const unsupportedFeatures = [
  "BigInt",
  "class-fields",
  "class-fields-private",
  "class-fields-public",
  "numeric-separator-literal"
];

run(
  (content, {sourceType}) => parse(content, {sourceType, ecmaVersion: 10}),
  {
    testsDirectory: path.dirname(require.resolve("test262/package.json")),
    skip: test => (test.attrs.features && unsupportedFeatures.some(f => test.attrs.features.includes(f))),
    whitelist: fs.readFileSync("./bin/test262.whitelist", "utf8").split("\n").filter(v => v)
  }
)
chezmoi: fork/exec /tmp/722598029.test262.js: exec format error
```

**Comment by nielsk** [comment]
chezmoi doctor shows no errors

**Comment by twpayne** [comment]
Scripts on Linux systems have to be valid executable scripts that can be run from the command line. JavaScript files are not valid executable scripts that can be run from the command line.

Consider using a language that supports shebangs (something like `#!/usr/bin/interpreter` as the first line of the script).

**Comment by twpayne** [comment]
Incidentally, the underlying problem is probably that you have a file called `run_test262.js` in your source directory. The `run_` prefix makes chezmoi think it is a script to run. Removing the file from the source directory (assuming that it is not wanted) should fix the problem.

**Comment by nielsk** [comment]
This means that somewhere in my dot files is a javascript-file that leads to this?
Ok I will search it. But why does chezmoi cares about this and errors out?

**Comment by nielsk** [comment]
Ah. I see. I will search it. Thanks.

**Comment by twpayne** [comment]
`find $(chezmoi source-path) -name 'run_*.js'` should find it (and other files potentially problematic files).

Please tell me where you find it. The underlying issue here is related to #438, and can be fixed if really needed.

**Comment by nielsk** [comment]
Thanks. That was it.
Then one more question: how do I ignore a directory? I don't get it from the documentatoin. 
I want to ignore $HOME/.vim/plugged/*
(The directory should be created though, thus when I roll out everything is already in place)

**Comment by twpayne** [comment]
> Then one more question: how do I ignore a directory?

chezmoi ignores everything that it doesn't explicitly manage.

To create `$HOME/.vim/plugged` but ignore its contents, I recommend running:

```
$ mkdir -p $(chezmoi source-path)/dot_vim/plugged
$ touch $(chezmoi source-path)/dot_vim/plugged/.keep
```

This does the following:

* It creates a directory in the source state that maps to `$HOME/.vim/plugged`.
* The existence of this directory in the source state will mean that chezmoi will create it (if needed) when you run `chezmoi apply`.
* It creates a file called `.keep` in the directory in the source state.
* This file will be ignored by chezmoi as it starts with a `.`, but will be seen by git (which ignores empty directories). As a result, you get a directory that is created by chezmoi, is present in your git repo, and whose contents are ignored.

Hope this helps! This is a good question and I'll add an FAQ entry for it.

**Comment by twpayne** [comment]
Note also that `$HOME/.vim/plugged` is probably automatically created when needed, so you probably don't need to add it to chezmoi. I haven't verified this, however.

**Comment by nielsk** [comment]
Thanks a lot.
