### ISSUE TITLE
Add optional support for diff-so-fancy

### ISSUE THREAD

**Issue by Gerrit-K** [twpayne/chezmoi#673]
It would be really cool if `chezmoi diff` / `chezmoi <...> -v` could also use [`diff-so-fancy`](https://github.com/so-fancy/diff-so-fancy), if it's available.
 
Since [this issue](https://github.com/so-fancy/diff-so-fancy#220), diff-so-fancy can display arbitrary unified diffs from stdin:
```diff -u file1 file2 | diff-so-fancy```

Alternatively I could also think of an option to make the diff tool completely configurable to the users choice, but that might be a little more difficult.

**Comment by twpayne** [comment]
Re-opening as this needs #677 too.

**Comment by twpayne** [comment]
Fixed with #674 and #678.
