### ISSUE TITLE
Ignoring directories in .chezmoiignore is not working

### ISSUE THREAD

**Issue by sandorex** [twpayne/chezmoi#691]
## What exactly are you trying to do?

Describe in as much detail as possible.

I am trying to ignore my old dotfiles directory but it does not work

## What have you tried so far?

What approaches have you tried to 

I have tried using `legacy/**/*` `legacy` `legacy/` but it does not work

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [x] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [x] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [x] Other, please give details.

## Output of any commands you've tried with `--verbose`

`chezmoi managed` command does not change depending on verbosity level
```
❯ cat .chezmoiignore                                   
README.md
LICENSE.txt
legacy

chezmoi on  master [✘»!?] 
❯ chezmoi managed   
/home/sandorex/.bashrc
/home/sandorex/.bin
/home/sandorex/.bin/archive-git
/home/sandorex/.bin/basic-server
/home/sandorex/.bin/bill-parser
/home/sandorex/.config
/home/sandorex/.config/kitty
/home/sandorex/.config/kitty/kitty.conf
/home/sandorex/.config/kitty/themes
/home/sandorex/.config/kitty/themes/dracula.conf
/home/sandorex/.gitconfig
/home/sandorex/.shell
/home/sandorex/.zshrc
/home/sandorex/legacy/firefox
/home/sandorex/legacy/firefox/chrome
/home/sandorex/legacy/firefox/chrome/userChrome.css
/home/sandorex/legacy/firefox/extensions.txt
/home/sandorex/legacy/firefox/generate-extension-list.py
/home/sandorex/legacy/firefox/user.js
/home/sandorex/legacy/init
/home/sandorex/legacy/init/NOTE.txt
/home/sandorex/legacy/init/init.sh
/home/sandorex/legacy/init/user-init.service
/home/sandorex/legacy/old
/home/sandorex/legacy/old/todo
/home/sandorex/legacy/old/todo/@other
/home/sandorex/legacy/old/todo/@other/@arch
# ... omitted
```

## Output of `chezmoi doctor`

```
❯ chezmoi doctor           
     ok: version 1.8.0, commit 017a83f4055a98ac90b030d5739aa560dde239b7, built at 2020-04-19T22:48:17Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/sandorex/.local/share/chezmoi (source directory, perm 700)
     ok: /home/sandorex (destination directory, perm 710)
warning: /home/sandorex/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/vi (editor)
warning: vimdiff (merge command, not found)
     ok: /usr/bin/git (source VCS command, version 2.25.3)
     ok: /usr/bin/gpg (GnuPG, version 2.2.18)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by sandorex** [comment]
I am not quite sure if this is meant to be but it should definitely be specified in documentation if it is
This structure
```
❯ tree -aF test
test
├── a/
│   └── b
└── b

1 directory, 2 files
```
takes 3 lines to ignore completely
```
test
test/*
test/**/*
```
could `test/**/*` be changed exclude everything ??

**Comment by twpayne** [comment]
This occurs because chezmoi currently uses Go's [`filepath.Match`](https://pkg.go.dev/path/filepath?tab=doc#Match) function, which does not support the `**` pattern. There's a discussion about this that's been going on for five years in https://github.com/golang/go/issues/11862.

I think the best solution is to use a third-party matching function instead, e.g.   [`bmatcuk/doublestar`](https://github.com/bmatcuk/doublestar). PR coming up.

**Comment by sandorex** [comment]
Wow that was fast, thank you!
