### ISSUE TITLE
chezmoi sets .ssh/config as group writable

### ISSUE THREAD

**Issue by skymoo** [twpayne/chezmoi#694]
I'm trying to manage my `.ssh/config` using `chezmoi`. This is working perfectly on all but one machine, a machine running Scientific Linux 7. I have my `.ssh` folder added as `private_dot_ssh` and this contains the file `config`, added as `private_config`:

```console
➜  dotfiles git:(master) ls -la private_dot_ssh 
total 44
drwxr-xr-x 1 ram ram  442 Apr 17 22:30 .
drwx------ 1 ram ram  994 Apr 20 21:21 ..
-rw-r--r-- 1 ram ram 1506 Apr 17 22:30 authorized_keys
-rw-r--r-- 1 ram ram 1288 Apr 17 22:30 encrypted_private_id_ecdsa_osmc
-rw-r--r-- 1 ram ram 1361 Apr 17 22:30 encrypted_private_id_ed25519
-rw-r--r-- 1 ram ram 2702 Apr 17 22:30 encrypted_private_id_rsa
-rw-r--r-- 1 ram ram 4331 Apr 17 22:30 encrypted_private_id_rsa_cgca
-rw-r--r-- 1 ram ram 2516 Apr 17 22:30 private_config
-rw-r--r-- 1 ram ram  263 Apr 17 22:30 private_id_ecdsa_osmc.pub
-rw-r--r-- 1 ram ram   98 Apr 17 22:30 private_id_ed25519.pub
-rw-r--r-- 1 ram ram  748 Apr 17 22:30 private_id_rsa_cgca.pub
-rw-r--r-- 1 ram ram  397 Apr 17 22:30 private_id_rsa.pub
➜  dotfiles git:(master) 
```

On all but this SL7 machine it works perfectly but on SL7 whenever I update my configuration it adds group write permissions to my `.ssh/config` file which breaks ssh:

```console
➜  .ssh ls -l
total 64
-rw-r--r--. 1 adam.mercer adam.mercer 2516 Apr 20 23:17 config
-rw-r--r--. 1 adam.mercer adam.mercer 2369 Apr 20 23:14 known_hosts
➜  .ssh chezmoi update -v 
Already up to date.
Current branch master is up to date.
( cd /home/adam.mercer/.local/share/chezmoi && /usr/bin/git pull --rebase )
chmod 664 /home/adam.mercer/.ssh/config
➜  .ssh ls -l
total 64
-rw-rw-r--. 1 adam.mercer adam.mercer 2516 Apr 20 23:17 config
-rw-r--r--. 1 adam.mercer adam.mercer 2369 Apr 20 23:14 known_hosts
➜  .ssh 
```

This works without issue on all the other machines I've tried it on, two Fedora 31 machine and two macOS Mojave machines, it's just this one SL7 machine which wants to set writable permissions on my `.ssh/config` file.

Any idea why it's doing this?

I'm currently working around this problem with the following:

```console
➜  dotfiles git:(master) cat run_10-fix-ssh-config-permissions.sh.tmpl 
#!/bin/bash
chmod g-w $HOME/.ssh/config
➜  dotfiles git:(master)
```

But would clearly like to resolve why it's wanting to use the incorrect permissions in the first place.

**Comment by twpayne** [comment]
This is likely due to the umask being different on the SL7 machine. Run `umask` to see what the value is set to.

Is it possible that umask is `022` on your other machines and `002` on your SL7 machine?

If the above is the case then there are at least two options:

1. Set `umask = 022` in chezmoi's config file on the SL7 machine.
2. Set your umask to `022` using the `umask 022` command in one of your shell init scripts on the SL7 machine. This will set the umask for all programs, not just chezmoi.

Hope this helps and please let me know what effect the above has.

**Comment by skymoo** [comment]
That's definitely the problem, thanks! This is a shared system at work and it seems they've overridden the default umask. What is the format for setting the umask option in my chezmoi configuration, I've added:

 ```
umask = 022
```

at the top of my `~/.config/chezmoi/chezmoi.toml`, which is what the [documentation](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#umask-configuration) seems to say I should be doing, but this seems to be incorrect as all chezmoi processes then fail with:

```
warning: /home/adam.mercer/.config/chezmoi/chezmoi.toml: While parsing config: invalid base
chezmoi: config contains errors, aborting
```

**Comment by twpayne** [comment]
Oops, sorry, that's my error. I mis-remembered the syntax for [octal integers in TOML](https://github.com/toml-lang/toml#user-content-integer). Try:

```toml
umask = 0o22
```

**Comment by skymoo** [comment]
Confirmed, that did the trick! Thanks.
