### ISSUE TITLE
Add a man page

### ISSUE THREAD

**Issue by jsamr** [twpayne/chezmoi#696]
## Is your feature request related to a problem? Please describe.

I guess usability. I love to have access to an exhaustive documentation from the terminal, and don't rely on any window manager. Also, this is extremely valuated in the *nix world.

## Describe the solution you'd like

I personally suggest mdoc (see `groff_mdoc(7)`) macros, because they offer a full DSL. They are also very widespread and portable (ex: `sudo(8)`).

## Additional context

The online documentation of `chezmoi` is of very good didactic quality, and I understand the burden of maintaining two "sources of truth". I would be happy to help.

**Comment by twpayne** [comment]
Thanks for the suggestion :)

chezmoi embeds its Markdown documentation in the binary, so you can access it by running

	chezmoi docs

* I want to keep a single source of truth for all documentation. Maintaining more than one manually leads to inconsistencies and tedious extra effort. At the moment, the single source of truth is the `docs/` directory, and the website, embedded docs, help text, and examples are all generated from this single source. I realize that man pages have a different structure to chezmoi's reference manual, so some cleverness might be needed to extract common parts.

* chezmoi has a pure Go build process, which greatly simplifies contributing. Generating the man page needs to be part of the CI to ensure that all documentation is up to date with the source of truth. There are existing tools to generate man pages from (say) Markdown, but these require installation and are written in other languages which will complicate the build process.

A well-written man page is indeed a beautiful thing, but I'm not sure if the upside is sufficient here to justify the increased complexity in managing the documentation and the build process, especially given that `chezmoi docs` already exists.

Thoughts?

**Comment by jsamr** [comment]
@twpayne 

To address the "single source of truth" issue, I suggest to split documentation between:

- Didactic content (MD)
- Reference manuals (mdoc)

So you would transfer the "reference" page to:

- chezmoi(1) for synopsis, concepts, templates, prefixes, commands and flags
- chezmoi(5) for the config file

And you can then include the manual content in your document site. [`mandoc`](https://man.openbsd.org/mandoc.1) utility and the [`mdoc`](https://man.openbsd.org/mdoc.7) macros are solid tools developed originally for OpenBSD. It offers markdown, html and of course tty output generation. [Sample html](https://jsamr.github.io/bootiso/).

> Generating the man page needs to be part of the CI to ensure that all documentation is up to date with the source of truth.

True, but one could decouple doc generation and build process, such that doc generation becomes an optional shell script invoked by your CI server. However, I don't know the tooling used in this process and how difficult that might be.

**Comment by twpayne** [comment]
Thanks for this. What do you think about reformatting `docs/REFERENCE.md` to match the man page format?

**Comment by jsamr** [comment]
@twpayne Yes, I think that would work out pretty well. Note that there are two conventions for page sections. One stems from traditional man, and the other from mandoc. But given the former is now shipped in many Linux distributions today (Debian), it is fair to say the two conventions are equally spread and accepted.

**Legacy sections convention**:

NAME, SYNOPSIS, CONFIGURATION, DESCRIPTION, OPTIONS, EXIT STATUS, RETURN VALUE, ERRORS, ENVIRONMENT, FILES, VERSIONS, CONFORMING TO, NOTES, BUGS, EXAMPLE, AUTHORS, SEE ALSO

source: [man](http://man7.org/linux/man-pages/man1/man.1.html)

**Mdoc sections convention**:

NAME, SYNOPSIS, DESCRIPTION, ENVIRONMENT, FILES, EXIT STATUS, EXAMPLES, DIAGNOSTICS, COMPATIBILITY, ERRORS, SEE ALSO, STANDARDS, HISTORY, AUTHORS, CAVEATS, BUGS

source: [groff_mdoc](https://www.systutorials.com/docs/linux/man/7-groff_mdoc/)

The main difference is how options are displayed. I find the mdoc more flexible towards utilities with a lot of sub-comands. The legacy "man" way is to split man pages per subcommands because the OPTIONS section was de-facto standard. A good example of this is git.

So, I would rather be in favor of mdoc conventions, with a list of options related to each command in sub-sections.

**Comment by twpayne** [comment]
With #1826, chezmoi has moved to [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) to generate its website. Contributions to generate a man page for all projects using MkDocs would help many.
