### ISSUE TITLE
Using secret in a template returns a string represtation of an array of bytes

### ISSUE THREAD

**Issue by georgyo** [twpayne/chezmoi#711]
## Describe the bug

Using the generic secret handler and the `secret` function in a template it will put in the template something like [103 101 116] which is not very useful.

Storing the secret as a json string and then using `secretJSON` does return a proper string. 

## To reproduce

1. Set `genericSecret.command` to `/bin/echo'
2. run `chezmoi execute-template '{{ secret "foo" }}'`
3. Notice that you got back `[103 101 116]` instead of the desired `foo`

## Expected behavior

To get back the string instead of array of bytes.

This is on chezmoi 1.8.0.

**Comment by twpayne** [comment]
Whoops! Thanks for reporting this and for the clear and minimal steps to be reproduce.
