### ISSUE TITLE
autocommit fails on re-adding a file after chmod

### ISSUE THREAD

**Issue by billwanjohi** [twpayne/chezmoi#713]
## Describe the bug

Autocommit when dealing with file permissions-only change seems to partially fail. Specifically, the change is propagated, the file is staged, but the commit is not made

## To reproduce

I added `chezmoi.toml` to source control and committed with autocommit set to true. Then I read the advice to set it's permissions to `0600`, so I did that. Then I re-added the file.

## Expected behavior

I was expecting a commit to be silently registered.

## Output of command with `--verbose`

```
➜ chezmoi add --verbose .config/chezmoi/chezmoi.toml
( cd /Users/bill/.local/share/chezmoi && /usr/local/bin/git add . )
chezmoi: cannot parse "2 R. N... 100644 100644 100644 ddbd961d7e4db2bb6615a9e8ce86364fa65e732d ddbd961d7e4db2bb6615a9e8ce86364fa65e732d R100 dot_config/chezmoi/private_chezmoi.toml\tdot_config/chezmoi/chezmoi.toml"

```

## Output of `chezmoi doctor`

```
➜ chezmoi doctor
     ok: version 1.8.0, commit 017a83f4055a98ac90b030d5739aa560dde239b7, built at 2020-04-24T15:03:37Z, built by homebrew
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/bill/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/bill (destination directory, perm 755)
     ok: /Users/bill/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/local/bin/zsh (shell)
     ok: /usr/local/bin/nvim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.26.2)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.20)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context

This was immediately after a successful autocommit, specifically of my original contents of `chezmoi.toml` with the more open file permissions.

**Comment by twpayne** [comment]
Thank you very much for reporting this and for the very clear bug report and precise instructions to reproduce it :)

There were (at least) two bugs:

1. chezmoi's git status parser got a separator wrong. The filenames are separated with `'\t'`, not `' '`.
2. Autocommit and autopush were not run after `chezmoi chattr` (discovered in testing).

I notice as well that you're managing chezmoi's configuration file with chezmoi itself. This is OK but I'm sure that you're already aware of the limitations. Specifically, chezmoi reads its configuration file on startup, which means that any changes you make to the configuration file will not be seen until the next time you run chezmoi.

Thanks again - your report was spot on and excellent :)
