### ISSUE TITLE
Can't seem to get .chezmoiignore to work

### ISSUE THREAD

**Issue by terminalmage** [twpayne/chezmoi#721]
## What exactly are you trying to do?

Selectively ignore stuff in my `~/.vim` dir

## What have you tried so far?

```
% cat $(chezmoi source-path)/.chezmoiignore
# Don't track vim backups
.vim/backup
# Don't ignore my user-defined settings, but ignore cloned packages
.vim/pack/erik/start/*
!.vim/pack/erik/start/user-defined
% chezmoi add -r .vim
warning: /home/erik/.vim/backup: skipping file ignored by .chezmoiignore
warning: /home/erik/.vim/pack/erik/start/salt-vim: skipping file ignored by .chezmoiignore
```

Awesome! It skipped what I wanted it to skip. Everything worked, right?

Nope.

Everything in the directories that chezmoi has told me will be ignored, has nonetheless been copied into the source directory:

```bash
% find $(chezmoi source-path)/dot_vim/pack/erik/start/salt-vim | wc -l
55
% find $(chezmoi source-path)/dot_vim/backup
/home/erik/.local/share/chezmoi/dot_vim/backup
/home/erik/.local/share/chezmoi/dot_vim/backup/dot_chezmoiignore.swp
/home/erik/.local/share/chezmoi/dot_vim/backup/dot_chezmoiignore~
```

Have I missed something painfully obvious?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not
  found the answer.
* [x] I have read [chezmoi's
  FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not
  found the answer.
* [x] I have searched [chezmoi's reference
  guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and
  not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```bash
% chezmoi doctor
warning: version dev
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/erik/.local/share/chezmoi (source directory, perm 700)
     ok: /home/erik (destination directory, perm 700)
warning: /home/erik/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /usr/bin/vim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.26.2)
warning: /usr/bin/gpg (GnuPG)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)```

**Comment by twpayne** [comment]
Thanks for the report.

I think there are a couple of things here:

1. `.chezmoiignore` was initially implemented to control what files are written when you run `chezmoi apply`. There are likely bugs around how it is handled when you run `chezmoi add -r`. This behavior will be more consistent with v2 (#654).

2. The patterns in `.chezmoiignore` don't recurse into subdirectories (see #700 for example). This is partially fixed with #693.

So I think there are two actions from this:

1. I need to fix the bugs around `.chezmoiignore` and `chezmoi add -r`.

2. Using `**` in your patterns might help. You'll need version 1.8.0 of chezmoi or later.

**Comment by terminalmage** [comment]
Thanks for the detailed explanation. I do happen to have 1.8.0 so I'll look into it, and I've subscribed to #654 so I am aware when merged.

**Comment by thernstig** [comment]
`chezmoi add -r` - the `-r` seems to be missing from the fish shell completion?

**Comment by twpayne** [comment]
> `chezmoi add -r` - the `-r` seems to be missing from the fish shell completion?

I don't think this is relevant to what's being discussed in this issue.

The `-r` is completed for me on macOS:

```
twp@Toms-MBP ~> chezmoi add -<Tab>
-a  --autotemplate  (auto generate the template when adding files as templates)
-c  --config  --config=                                           (config file)
-D  --destination  --destination=                       (destination directory)
-e  --empty                                                   (add empty files)
…and 13 more rows
```

Please open a new support issue if `-r` completion is not working for you.
