### ISSUE TITLE
Template characters in already existing files

### ISSUE THREAD

**Issue by adelin-b** [twpayne/chezmoi#722]
## Describe the bug

Template like strings that already exists aren't escaped (this is issue is also valable for templates of template)

for example 
```vim
" .config/nvim/init.vim
" vim: set foldmethod=marker foldmarker={{,}}
...
```
Will result in 
```
> chezmoi add /home/adelin/.config/nvim/init.vim --verbose --force
chezmoi: template: /home/adelin/.local/share/chezmoi/dot_config/nvim/executable_init.vim.tmpl:1: unexpected "," in command
```
## To reproduce

```
touch .simplefile      
echo "\"vim: set foldmethod=marker foldmarker={{,}}" > .simplefile
chezmoi add .simplefile
```
## Expected behavior

Better way to handle ambiguous templates that might fail

For example pseudocode for `chezmoi add`
```javascript
chez_moi_add(file) {
  template_blocks = get_template_blocks_from(file)
  for block in template_blocks {
    if (is_valid(block)
      default_behavior()
    else 
       conflict_resolution = prompt_for_conflict()
       switch (conflict_resolution)
         case 'escape'
           escape_block(block)
         case 'error'
           default(behavior)
        
  }
}
```

**Comment by twpayne** [comment]
Great catch, thank you for reporting this and for the very clear bug report.

The proposed pseudocode is very interesting and well thought through. I think that if we can make `escape_block` be 100% reliable then we can make it the default behavior for `chezmoi add --template`.

**Comment by twpayne** [comment]
OK, #723 escapes template delimiters when `--autotemplate` is passed to `chezmoi add --template`. I think this is a reasonable and simple compromise.
