### ISSUE TITLE
How do I manage dotfiles outside home dir?

### ISSUE THREAD

**Issue by BSDxxxx** [twpayne/chezmoi#725]
Such as: ` D:\my.config`, I want to manage this dotfiles along with dotfiles under `C:\User\name`.
Can I manage dotfiles under `C:\` `D:\` the same time?

Is this request improper? I have tried other dotfile managers too, but they seemed all base in home directory.

**Comment by twpayne** [comment]
Not directly, and this is deliberate. There's an [FAQ question](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#can-i-use-chezmoi-outside-my-home-directory) on this.

As well as the workarounds listed in the FAQ entry, you can also use a script to run arbitrary commands, including updating files outside your home directory.
