### ISSUE TITLE
How do I add all the dotfiles inside a directory in Window10?

### ISSUE THREAD

**Issue by BSDxxxx** [twpayne/chezmoi#727]
In linux I can do this easily:
```cmd
chezmoi add dir/*
```
But this won't work in CMD.

**Comment by twpayne** [comment]
Use the `-r` option to `chezmoi add`:

	chezmoi add -r dir

**Comment by BSDxxxx** [comment]
@twpayne Thanks, why isn't this `-r` option in the `chezmoi help`?

**Comment by twpayne** [comment]
The `-r` option only applies to `chezmoi add`, you'll see it in:

	chezmoi help add
