### ISSUE TITLE
chezmoi cd fails without config file

### ISSUE THREAD

**Issue by jhillyerd** [twpayne/chezmoi#73]
`chezmoi cd` fails without config file:

```
> chezmoi cd
open /usr/local/google/home/jhillyerd/.config/chezmoi/chezmoi.yaml: no such file or directory
```

`chezmoi version` fails with same error

version `bdecf50 (HEAD -> master, tag: v0.0.8, origin/master, origin/HEAD)`

**Comment by jhillyerd** [comment]
Pretty much all commands are broken.   But just creating an empty file (I did .toml) resolved it.

**Comment by twpayne** [comment]
Doh! Thanks very much for the bug report :)
