### ISSUE TITLE
Treat `cd.command` as a command line instead of an executable

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#732]
## Describe the solution you'd like

Similar to #625, it would be nice to treat `cd.command` as a full command line rather than just an executable.  I like to use Powershell on Windows, but it has an annoying habit of printing out a bunch of banner-type info when it starts.  It has a `-nologo` option to suppress this, but with the current implementation I can't pass it in.

## Describe alternatives you've considered

I suppose I could use a wrapper script or something, but it'd be weird to launch a shell for the script just to turn around and launch another shell...  The best alternative, really, is to just live with it :grin:  What's there now is already better than what I used to do.

## Additional context

This is not at all a high priority, but I wanted to throw it out there.  Thanks!

**Comment by twpayne** [comment]
Nice suggestion, implemented.

Add this to your configuration file:

```toml
[cd]
	args = ["-nologo"]
```
