### ISSUE TITLE
Enable integration tests on Windows

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#733]
@zb140 would you be able to have a look at this? The idea is to build a suite of integration tests to make the internal refactoring for v2 (#654) safer.

#730 adds some initial integration test infrastructure using [`github.com/rogpeppe/go-internal/testscript`](https://pkg.go.dev/github.com/rogpeppe/go-internal/testscript?tab=doc). All but a couple of simple tests are skipped on Windows, and it would be nice to enable them.

What's required:

* Populate the `setupWindowsEnv` function in `main_test.go` to set up a home directory, editor, shell, and `.gitconfig` on Windows. See `setupPOSIXEnv` in the same file for a guideline.
* Enable individual tests by removing the `[windows] stop` conditions from the top of the scripts in `testdata/scripts`.
* Fix any tests so that they pass on Windows as well as Linux/macOS.

Possibly helpful:

* https://github.com/rogpeppe/go-internal/blob/master/testscript/testdata/exec_path_change.txt is a good example of a testscript that works on all operating systems.
* The environment variables `$exe` (`.exe` on Windows, `` elsewhere), `${/}` (path separator), and `${:}` (path list separator) are probably useful.
* If you're using VIM, [`github.com/twpayne/vim-testscript`](https://github.com/twpayne/vim-testscript) has basic syntax highlighting for testscripts.

The planned sequence of events is:

1. Build a small suite of non-trivial tests that work on all operating systems.
2. Use these tests as examples for building a comprehensive test suite for as much as chezmoi's functionality as possible.
3. Use the test suite as a safety net for the internal refactoring (#654).

Thanks in advance for any help :)

**Comment by zb140** [comment]
Sure, I'd be happy to! I think I have a pretty clear understanding of what to do, so I'll give it a shot and report back.

**Comment by zb140** [comment]
Thanks for the pointers! I made some good progress tonight, and I expect I'll have something that's ready to share in the next couple days.

**Comment by zb140** [comment]
Ok, I've implemented `setupWindowsEnv` and updated all the tests to run (and pass 😄) on both Windows and Linux.  🎉

I generally followed the same approach as the POSIX implementation, but it did require a small change to `go-shell`.  I had to add the ability to override the shell with an environment variable on Windows.  At first glance, it seems like you should already be able to do that by changing `%ComSpec%`, but that variable also controls the shell script interpreter at the OS level, so if you want to use a shell script as a shell, as in this case, you end up with a script that tries to use itself as its own interpreter...

If you agree that adding the extra variable to `go-shell` makes sense, I'll submit a pull request over there, then my changes will be ready for review.  Or if you have a different idea for how to override the shell, of course I'm open to that too.

**Comment by twpayne** [comment]
Fantastic!

Currently the user's shell is used in three places, and all codepaths are very short:

* The `cd` command.
* To invoke `diff.pager` if it contains spaces.
* The `doctor` command.

I think that if we change the logic around getting the user's shell to be overridable for testing, then we'll end up with more complexity just to test the test codepaths themselves, rather than the original codepaths, which defeats the purposes of the tes. I think the original codepaths are straightforward enough that it's OK not to test them.

Therefore, rather than adding extra variables to `go-shell` I think we should skip these tests on Windows for now.

**Comment by zb140** [comment]
Makes sense to me.  I made that change and submitted #737 for review.

**Comment by twpayne** [comment]
Fixed by @zb140 with #737. Thank you :)
