### ISSUE TITLE
chezmoi diff :: exact_ directory :: Missing target file blocks proper diff

### ISSUE THREAD

**Issue by lcrockett** [twpayne/chezmoi#740]
## Describe the bug

Using `chezmoi diff` while managing a target directory using the `exact_` attribute blocks proper diff output if one of the target files are missing.

## To reproduce

1. Have a target directory specified using the `exact_` attribute
```shell
$ find ~/.local/share/chezmoi/exact_private_dot_neomutt
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/colorscheme
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/colorscheme/gruvbox-powerline.neomuttrc
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/extra
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/extra/mailcap-gui
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/extra/mailcap-cli
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/theme
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/theme/powerline.neomuttrc
/Users/lcrockett/.local/share/chezmoi/exact_private_dot_neomutt/theme/powerline-rounded.neomuttrc
```

2. Create an actual difference and run `chezmoi diff` -> diff OK
```shell
$ printf '\nmiauw\n' >> ~/.zshrc
$ chezmoi diff
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: .zshrc
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@@ -16,5 +16,3 @@         # Action :: Include Z shell run commands include files
         source "$zshrc"
     end
 fi
-
-miauw
```

3. Remove a target file within the `exact_` target directory
```shell
$ ls -l ~/.neomutt/extra
total 16
-rw-r--r--  1 lcrockett  lcrockett  351 May  9 17:20 mailcap-cli
-rw-r--r--  1 lcrockett  lcrockett  372 May 10 04:07 mailcap-gui
$ rm -v ~/.neomutt/extra/mailcap-gui
/Users/lcrockett/.neomutt/extra/mailcap-gui
$ ls -l ~/.neomutt/extra
total 8
-rw-r--r--  1 lcrockett  lcrockett  351 May  9 17:20 mailcap-cli
```

4. Run `chezmoi diff` -> diff NOT_OK
```shell
$ chezmoi diff
chezmoi: stat /Users/lcrockett/.neomutt/extra/mailcap-gui: no such file or directory
```

5. Run `chezmoi apply` to fix restore the missing target file
```shell
$ chezmoi apply
$ ls -l ~/.neomutt/extra
total 16
-rw-r--r--  1 lcrockett  lcrockett  351 May  9 17:20 mailcap-cli
-rw-r--r--  1 lcrockett  lcrockett  372 May 10 04:10 mailcap-gui
```

6. Run `chezmoi diff` again -> diff OK
```shell
$ chezmoi diff
$ 
```

## Expected behavior

I would expect a `chezmoi diff` to run OK and actually show the diff of `~/.zshrc` + an informational message stating the target file is missing / nonexistent. Currently it seems to stop processing output of a `chezmoi diff` due to the missing target file.

## Output of command with `--verbose`

Same output with `--verbose` as laid out above in step 4.

## Output of `chezmoi doctor`

```
$ chezmoi doctor
     ok: version 1.8.1, commit 4def4f3b96cb01cefe8d7887e8dbfb77908ef267, built at 2020-05-06T18:08:59Z, built by goreleaser
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/lcrockett/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/lcrockett (destination directory, perm 755)
     ok: /Users/lcrockett/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/local/bin/vi (editor)
     ok: /usr/local/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.24.2)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.17)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
     ok: /usr/local/bin/vault (Vault CLI, version 1.4.1)
```

## Additional context

No additional context.

**Comment by twpayne** [comment]
Nice find! Thank you very much for the full bug report and clear steps to reproduce :)

**Comment by twpayne** [comment]
This is unrelated to the reported issue, but I noticed this in the output of `chezmoi doctor`:

```
     ok: /usr/local/bin/vault (Vault CLI, version 1.4.1)
```

Are you using Vault for secret management in chezmoi, or does it just happen to be installed on your machine for other reasons? Just curious, as this is the first time that I've seen Vault installed on the same machine as chezmoi in the wild, and I'm curious as to how well it works and if there are any known bugs.

**Comment by lcrockett** [comment]
I do have Hashicorp Vault installed indeed via Homebrew. However, I don't use it with chezmoi but rather use it to interact with Vault server instances running outside the scope of my workstations. Therefore I don't have any valuable feedback regarding it's integration with chezmoi.

I'm rather waiting for Enpass to come out with a CLI version as that's the secret manager I personally use.

**Comment by lcrockett** [comment]
I think I found the culprit of this bug.

`~/.config/chezmoi/chezmoi.toml` contained the follow block:

```
[diff]
    format = "git"
    pager = "diff-so-fancy"
```

Getting rid of the `format` directive fixes the issue:

```
[diff]
    pager = "diff-so-fancy"
```

Considering the upcoming changes in 2.0.0 regarding chezmoi's diff format, perhaps this bug might become redundant by the time 2.0.0 comes out ?

**Comment by twpayne** [comment]
For info, the bug was specific to the git diff format. The git diff format includes file modes in both the old and the new files, and chezmoi's code did not handle the old file not existing.

Thanks again for reporting this - much appreciated!

**Comment by lcrockett** [comment]
Perfect, thank you for the quick fix. I'll test it as soon as a new Brew versions comes out.
