### ISSUE TITLE
apply file changes on write with edit --apply

### ISSUE THREAD

**Issue by jmattheis** [twpayne/chezmoi#752]
My current workflow for changing my config is 
```
$ chezmoi edit --apply ~/.config/some/config
```
then I've to write quit my `$EDITOR` to apply the changes. It would be cool, if I didn't have to close my editor and only write the file (`:w` in vim). Chezmoi could listen on file changes (with something like inotify) and then apply them.

Usecases are:
* vim: edit config, write, source applied config from chezmoi
* i3: edit config, write, inplace reload i3 without killing existing windows

This is only a minor inconvenience so feel free to close the issue if you don't see the need for it.

Anyway, keep up the good work with chezmoi!

**Comment by twpayne** [comment]
Interesting idea, and related to what @Zackhardtoname is [asking for](https://github.com/twpayne/chezmoi/issues/748#issuecomment-629262971).

This should be fairly straightforward to implement, but I'd like to get the v2 rework done first. I expect to add this though :)

**Comment by Lilja** [comment]
So I randomly looked into this thread and felt a bit bored and decided to create my first vim plugin. 

It solves this problem by getting the current PID of the vim process, looks up the parent PID and sees if chezmoi was invoked(`chezmoi edit $dotfile`). If so, it will listen to buffer write and invoke the `chezmoi apply $dotfile` automatically.

Feel free to use it! https://github.com/lilja/vim-chezmoi

**Comment by camgraff** [comment]
+1 for this! I'd love to get back the ability to make a change to my .vimrc, save, re-source, and test if my change results in the expected functionality all without ever heaving to leave the editor. 

@twpayne if you're too busy right now and this doesn't conflict with the v2 rework, I'd be happy to get a PR up for this. Id' just need a little direction on the design i.e. would you want this to become the default behavior or introduce a new flag with `chezmoi edit`?

**Comment by twpayne** [comment]
@camgraff Thanks for your offer - it's not quite time to work on this yet.

At the moment, the v2 branch is nearing completion (please do check out the `v2` branch and try it) but one of the two remaining things left to implement are `chezmoi edit` with encrypted files, which is a prerequisite for implementing the file watching functionality. In the case of encrypted source files, `chezmoi edit` decrypts the source file to a temporary private directory, opens the decrypted file in `$EDITOR`, and then re-encrypts the edited file and writes it back to the source directory when the editor exits. This means that file to watch for updates is not the file in the source directory but instead the decrypted file in the temporary private directory. This mechanism is not yet complete in the `v2` branch.

**Comment by tnek213** [comment]
I hacked this together and use it as **_chezmoi-edit_** :
``#!/bin/bash

# run this sub-process in the background until chezmoi edit exits
(
    sleep 1 # give chezmoi a second to start the editor

    while pgrep chezmoi &>/dev/null; do
        # only sync if there are ONLY modified files in the chezmoi source
        chezmoi status | grep -q '^ M ' && if ! chezmoi status | grep -qv '^ M '; then
            chezmoi apply &>/dev/null
        fi
        sleep 1
    done
) &

chezmoi edit "$@"
``

It might be of interest to someone until something better comes along! Also, use it at your own risk! :-)
