### ISSUE TITLE
Is chezmoi dotfile structure changeable/configurable? 

### ISSUE THREAD

**Issue by Lilja** [twpayne/chezmoi#753]
I've had a look into a few other people's dotfile github repositories that uses chezmoi. In those projects, the files and the file structure looks a bit messy. 

I'm right now am on the lookout to escape my python installation script of my dotfiles and have had a look into tools like chezmoi to do so. Everything about this project look good, except the project structure of the files that eventually gets pushed to a git repo.

I had a look into [this guy's repo](https://github.com/Azza292/dotfiles) and it looks like there is a `dot_` prefix of all folders. To be honest, it kind of put me off. Comparing it [my own](https://github.com/lilja/dotfiles) I set it up so every folder is a tool and usually is just symlinkable to `$XDG_CONFIG_HOME`. I think this is a better layout since anyone can view this repository and have a look and know where to view files.

It would be great if there was a way to preserve this layout instead of creating lots of directories and files with `dot_` as a prefix, in my opinion.

**Comment by twpayne** [comment]
chezmoi explicitly uses a 1:1 mapping between files in the source directory and files in the target state. One of the reasons for doing this is to avoid ambiguity. If you have a folder per tool, what happens if the same dotfile occurs in multiple folders with different contents?

The chezmoi dotfile structure is not changeable or configurable, and this is not likely to change as the complexity of doing so far outweighs any benefits in my opinion. You are, of course, free not to use chezmoi :)

**Comment by Lilja** [comment]
Thanks for the response!

> If you have a folder per tool, what happens if the same dotfile occurs in multiple folders with different contents?

Not sure what you mean by this. Care to elaborate?

**Comment by twpayne** [comment]
Of course.

Consider running the following commands in your dotfile repo:

```
echo "# fish bashrc" >> fish/bashrc
echo "# zsh bashrc" >> zsh/bashrc
```

What should be the contents of `~/.bashrc` given that all of `bash/bashrc`, `fish/bashrc`, and `zsh/bashrc` all exist?

Note that I realize that chezmoi is not immune to this problem: you could have `dot_bashrc`, `empty_dot_bashrc`, etc. in your chezmoi dotfiles repo, but chezmoi does check for this and all these files have to be in the same directory, which makes it a little easier to spot.

**Comment by Lilja** [comment]
Right! I thought about this before I wrote the question but I guess I didn't realize it. The answer is probably that there is no way to figure out that _automagically_. Well, I mean, in my install script I essentially have this(not exactly, but paraphrasing).
```python
target_map = {
    f'{XDG_CONFIG_HOME}/fish': 'fish/'
}

for target_to_install, source_file in target_map.items():
    # some logic to install that file
```
Which `target_map` is essentially a map where to install files. I guess what I'm getting at is that it would be great to tell chezmoi where to put these files.

```yaml
# Some cool file to tell chezmoi where to store files. Probably in root of git repo.
git_structure:
    ~.bashrc: fish/bashrc
    ~.config/vim/vimrc:vim/vimrc
```

Any thoughts on this? Does my comment make sense?

**Comment by twpayne** [comment]
(Reopening this while the discussion is still in progress - I will reply to your just-posted comment shortly)

There are a few more problems with per-tool directories, on top of the inconsistency problem mentioned in my last comment.

* How should `chezmoi add` work out which per-tool directory a file should be added to? (you just gave a hint, but I'll write a bit more).
* How should configs that affect multiple tools be handled? Say I have a git plugin in my zsh config, which only makes sense if both git and zsh are installed. Should this go in the `zsh` tool directory or the `git` tool directory?

**Comment by twpayne** [comment]
> Which `target_map` is essentially a map where to install files. I guess what I'm getting at is that it would be great to tell chezmoi where to put these files.

Well, if you do this then every time you `chezmoi add` a new file you have to update `target_map` first. Another option would be to make `chezmoi add` take a `--tool` option to specify which per-tool directory the file should be added to, which also updates `target_map` but now chezmoi has to update user-written config files that might include hand-written comments.

Thanks for this discussion - I do appreciate it. cc @offbyone who raised a similar issue in #189.

**Comment by twpayne** [comment]
#226 cc @johnramsden is also relevant.

**Comment by Lilja** [comment]
> How should chezmoi add work out which per-tool directory a file should be added to? (you just gave a hint, but I'll write a bit more).
Hmm. I would say that chezmoi would know that the theoretical `git_structure` config property has been populated. So any `chezmoi add ...` would either:
* Reject. Chezmoi errors and states that `chezmoi add ...` must be supplied with `--tool`(like you mentioned) flag or similar must be supplied.
* Enter some sort of interactive mode where the user is prompted to select a folder(I have no idea if this is feasible, just spitting out ideas)

> How should configs that affect multiple tools be handled? Say I have a git plugin in my zsh config, which only makes sense if both git and zsh are installed. Should this go in the zsh tool directory or the git tool directory?
I suppose the keyword in this sentence is zsh. Since it's a plugin for zsh I'd say it's a tool that goes into the zsh directory. But I guess you're not just after these two concrete examples, but rather how to reason about dependencies around multiple folders? I'd say the user should figure it out if they would want to. In the end, the files should be findable by the respective programs so as long as they're found I don't think it would matter too much.

**Comment by twpayne** [comment]
OK, I'm open to the possibility of implementing this but no promises yet! The v2 rework makes something like this much easier to implement, but it definitely won't land in the initial v2 release.

Another problem is: how do you tell when a per-tool directory is a per-tool directory? i.e. how do you know that `bash/dot_bashrc` should target `~/.bashrc` and not `~/bash/.bashrc`?

What if you have `git-submodule/bash/dot_bashrc`? How do you say that `git-submodule` and `git-submodule/bash` should be ignored but `git-submodule/bash/dot_bashrc` should target `~/.bashrc`?

**Comment by offbyone** [comment]
Honestly, much as #189 still eats me a bit, I think the simplicity of the obvious 1:1 mapping far outweighs any aesthetic distasted for the different file names. I'd be really leery of introducing that ambiguity to an otherwise incredibly simple system.

**Comment by Lilja** [comment]
Long post!

Maybe it's because I've only spent around 5 minutes reading the documentation of chezmoi, so please bear in my ignorance. But why do all these questions matter? Let's say I'm doing a fresh chezmoi init on a new system.

```
# machine 1
$ chezmoi init
$ chezmoi add ~/.bashrc --tool bash/bashrc
# At this point, chezmoi should create a structure in some config file in the git repo, that say that bash/bashrc should point to ~/.bashrc
$ chezmoi cd
$ git commit && git push

# machine 2
$ chezmoi init https://github.com/username/dotfiles.git
# chezmoi sees the config file, lists all the files in the repo, does an intersection of the values of the translation map and the list of all folders/files in the repo. Since bash/bashrc is the only one currently in that intersection, it knows the source file and where to install
$ chezmoi -v apply
[ -f "~/.bashrc" ] && echo "bashrc exists" || echo "bashrc don't exists" 
bashrc exists
```

Some thoughts regarding `chezmoi add ~/.bashrc`: it would be nice if chezmoi could supply with an out of the box suggestion for this. So instead of creating a map `~/.bashrc: dot_bashrc.tmpl` it would find the _term_ `~/.bashrc` in some sort of list of suggestions, indicating to put it under `bash/bashrc`(personally I prefer no dot in the filenames of my dotfiles, _oh, the irony_). Please excuse the continuation of python, I don't know much about go.
```python
# chezmoi add implementation
suggestions = {
    "~/.bashrc": "bash/bashrc",
    "~/.gitconfig": "git/config",
    "~/.config/fish/config.fish": "fish/config.fish"
}
def add(filename, tool=None):
    if filename in suggestions.keys():
        save_file_to_git_repo(filename, suggestions[filename])
```

How does my interpretation of chezmoi play out in reality? Because if it can or the v2 remake can do, then I don't think if those questions about submodules and per-tool directories matter, if they are to be ignored or not, since **the user probably know what they want**.

> how do you tell when a per-tool directory is a per-tool directory? i.e. how do you know that `bash/dot_bashrc` should target `~/.bashrc` and not `~/bash/.bashrc`?

At least for my setup, my tool folders sometimes arent 1:1 to the structure the program requires. For example, i have `bash/bashrc` in my repo. But bash wouldn't understand if i simply just copied over `bash/` to `$XDG_CONFIG_HOME/bash`, because bash is quite old and does not follow the xdg base directory folder structure. [Link 1](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Hardcoded), [link 2](https://savannah.gnu.org/support/?108134). To confuse things even further, I even have a folder called `nas-script` which is a script for me to access my NAS remotely, it is a python package that I create a binary with and place it under `bin/` in my repo. There are no configuration files, just a tool. 

> What if you have git-submodule/bash/dot_bashrc? How do you say that git-submodule and git-submodule/bash should be ignored but git-submodule/bash/dot_bashrc should target ~/.bashrc?

I think this ties into my first answer, if there nothing automagic that chezmoi can do, let the user determine where they want their files put.

**Comment by twpayne** [comment]
I echo @offbyone's sentiments here:

> Honestly, much as #189 still eats me a bit, I think the simplicity of the obvious 1:1 mapping far outweighs any aesthetic distasted for the different file names.

chezmoi is just another tool that plugs into other tools. It uses git for version control and anything distributed, your personal editor for editing, gpg for encryption, and a widely-used template language for templates.

You can also treat chezmoi as a pluggable tool itself. For example, you can use whatever scripts you want to assemble per-tool configuration directories into a single chezmoi source directory and then feed that directory to `chezmoi apply` (e.g. using the `-S` option). Equally, you can write wrapper scripts to integrate with other tools, as you so nicely did with https://github.com/lilja/vim-chezmoi.

So, I would recommend taking chezmoi at a face value: it takes a source directory, computes a target state from that, and updates a destination directory to match that target state. It doesn't care where the source directory comes from, and this gives you the freedom to create that source directory however you want.

**Comment by Lilja** [comment]
I respectfully disagree.

On one hand, I think a lot of open source tools let's you dictate where the output of its logic is stored. Here are some similar tools to chezmoi that solves this.
* [Dotbot](https://github.com/anishathalye/dotbot), has the setup of using a yaml file [to map its contents to the real system from a source directory](https://github.com/anishathalye/dotbot#full-example).
* [vcsh](https://github.com/RichiH/vcsh), let's users mirror ~/. [Example](https://github.com/mpsq/dotfiles).

On the other hand, I understand that simplicity is key. Which is probably what was wanted when chezmoi was being written.

> chezmoi is just another tool that plugs into other tools.

> You can also treat chezmoi as a pluggable tool itself. For example, you can use whatever scripts you want to assemble per-tool configuration directories into a single chezmoi source directory and then feed that directory to chezmoi apply (e.g. using the -S option)

I had a look into the -S option, which if I understand correctly. Is an option to specify where all of the output from chezmoi should be. I suppose that it could be possible to create a wrapper between chezmoi and a git repo create some converter. But in my opinion, this is more of a hack rather than solution. If chezmoi internals change that script would break fairly quickly.

> So, I would recommend taking chezmoi at a face value: it takes a source directory, computes a target state from that, and updates a destination directory to match that target state. It doesn't care where the source directory comes from, and this gives you the freedom to create that source directory however you want.

> It doesn't care where the source directory comes from

But that's just the issue, it cares where the source directory comes from.

Let's look at this on another way. Chezmoi has a exclusive rights on the directory structure in the source directory. I say 'exclusive rights' since there are no explicit git commands that the user performs, rather `chezmoi push` and `chezmoi update` are the go to instructions to share the files with the rest of your/the worlds machines. Compare chezmoi with dotbot, where dotbot has a yaml file to map the contents of the source directory to the target directory. I don't think I can say that dotbot has exclusive rights to the source directory because it's not doing anything with the source directory. Chezmoi is much more black box in her nature that it might be a bit artificial where a file/directory is placed. To me, it looks like chezmoi is just dumping its contents with a `dot_` prefix on everything it is suppose to register. It's this part that is bothering me. Chezmoi has exclusive rights to the source directory, but it chooses this non elegant way(very opinionated, I know) of storing files. I'm just trying to shed some light on what I think is a problem that could be addressed with a different method. Where it up to me and I would write a tool like chezmoi from scratch, I would create some kind of yaml-file at the root of the source directory which would indicate "aha, I'm a chezmoi-directory meant for managing dotfiles". The contents of the file would say which files and directories are managed by the dotmanager-tool and those files and directories not referenced anywhere should probably be ignored.

I don't think that creating an optional translation map for a sort of advanced use case is that controversial from a usability perspective. In terms of code, my gut feeling says it's not a lot of LOC that would be needed to be implemented.

I hope my points here are not seen as vile criticism, but rather more as constructive feedback. I know it's a very opinionated matter, but I personally feel like this problem could be solved a bit differently. To me chezmoi looks like a great tool and creating a change that would allow some more transparency with the source directory would make it go from great to excellent.

**Comment by twpayne** [comment]
I recommend that you read through chezmoi's documentation, particularly the [core concepts](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#concepts) to understand how chezmoi interacts with your system. There are a number of fundamental errors in your post, notably:

> I had a look into the -S option, which if I understand correctly. Is an option to specify where all of the output from chezmoi should be.

No, `-S` allows you to change the source directory per run. For example, if you have per-tool source directories in `~/dotfiles/bash`, `~/dotfiles/git`, and `~/dotfiles/iterm2` then you can apply all of them to the same destination directory (e.g. `~`) by invoking `chezmoi apply` multiple times, for example:

```
for tooldir in bash git iterm2; do
    chezmoi apply -S $HOME/dotfiles/$tool
done
```

> Let's look at this on another way. Chezmoi has a exclusive rights on the directory structure in the source directory.

This is not correct. You can use whatever you want to manage your source directory. chezmoi has close integration with git and `$EDITOR` because that is what almost everybody uses, but there's no obligation to use these.

chezmoi is opinionated software and you are free to use it or not as you wish. If you don't like aspects of it, then you can build your own tooling around chezmoi to adapt those aspects, or fork it, or use a completely different system.

chezmoi will stick with the 1:1 source:destination approach for now.

**Comment by twpayne** [comment]
I hope you have a response to this issue now, even if it's not the one you wanted. Please re-open this issue if needed.
