### ISSUE TITLE
Remove empty directories

### ISSUE THREAD

**Issue by youam** [twpayne/chezmoi#754]
Sometimes, chezmoi templates lead to it creating empty directories.

For example, I want to put my window manager config only on hosts where I do use a gui. I manage this by wrapping the full configuration into an {{ if }} leadging to an empty (and thus, removed) file if I don't want it on this box:

```
$ head -n1 ./private_dot_config/awesome/rc.lua.tmpl
{{- if index . "has_gui" }}{{ if .has_gui -}}
$ tail -n1 ./private_dot_config/awesome/rc.lua.tmpl
{{- end -}}{{ end }}
```

As the template rc.lua.tmpl does *not* have the `empty` attribute, the resulting target file is removed. But as the directory private_dot_config/awesome does exist in the source directory, ~/.config/awesome is created nontheless.

Please consider either removing empty directories in the target directory if the source directory is *not* tagged empty (matching the file behaviour, but changing current behaviour), or add a new attribute to enable removing of empty target directories.

Thank you for such a useful tool!

**Comment by twpayne** [comment]
Good idea.

In the short term I think you can achieve this with chezmoi's `.chezmoiremove` functionality by putting this in your `.chezmoiremove` file:

```
{{ if not (index . "has_gui") }}
.config/awesome
{{ end }}
```

And then running `chezmoi apply` with the `--remove` flag.

In the medium term, the upcoming version 2 release gives an opportunity to make minor changes to the behavior, for example adding the `empty_` attribute to directories.

I'm cautious about chezmoi causing data loss by removing entire directories: there might be files in the directory unrelated to chezmoi.

I propose:

### Directories with the `empty_` prefix

Directory is created by `chezmoi apply`, even if it contains no entries in the target state. chezmoi will never remove the directory, unless it is listed in `.chezmoiremove`.

### Directories without the `empty_` prefix (the new default and new behavior)

`chezmoi apply` will only create the directory if it contains further entries managed by chezmoi. chezmoi will never remove the directory, unless it is listed in `.chezmoiremove`.

Does this sound reasonable?

**Comment by youam** [comment]
For `empty_`, I'd always create it, yes. I'm not sure whether I'd expect it to be removed even if it exists in `.chezmoiremove` and in the tree. Probably not, because I've explicitly tagged it `empty_`.

For the other case, I'd actually prefer chezmoi to remove the directory without listing it in `.chezmoiremove`. I concur that this MUST NOT lead to data loss. Using `syscall.rmdir()` should be enough to guarantee this, though, as rmdir(2) does only remove directories atomically which don't contain any files.

If you don't want to add this as the default behaviour without attributes, how about asking for it with a new attribute `rmdir_`? IMHO this feels way less like a hack than having to add the directory to `.chezmoiremove` and guarding it with whatever conditions are needed by the files within? 

I think this handles it better for unmanaged files, too. E.g. in my example above, I'd want private_dot_config to only be created when there are managed files/directories within, but I can't say whether I can ever remove it afterwards from within `.chezmoiremove`, as so many other tools are bound to create it.

That is, I'd prefer:

- `empty_` prefix: always create, never remove, ignore `.chezmoiremove`. 

- no `empty_` prefix: create whenever any file inside should exist, remove when actually empty (safeguarded by rmdir syscall). if `exact_` attribute is also given, the safeguard isn't even needed, because we're supposed to clean up

**Comment by davidolrik** [comment]
I too have this issue, and I can't get the short term workaround to work.

Instead I get this error when trying to remove the "empty" `Library` folder on non Darwin os'es.

```
chezmoi: Library: duplicate source state entries (, private_Library); Library/LaunchAgents: duplicate source state entries (, private_Library/LaunchAgents)
```

The `Library` folder is actually not empty it contains an empty `LaunchAgents` directory but no files has been created.
(Both folders are created by `chezmoi`)

**Comment by twpayne** [comment]
Thanks for reporting this @davidolrik - this is clearly a bug in chezmoi with regards to removing directories.

In the short term, you might be able to work around it by ignoring `Library` on non-macOS systems with `.chezmoiignore`:

    {{ if (ne .chezmoi.os "darwin") }}
    Library
    {{ end }}

**Comment by davidolrik** [comment]
Ah, I now see the error of my ways 😊

I was ignoring the actual local directory like so:

{{- if ne .chezmoi.hostname "marklar" }}
private_Library
{{- end }}

...and not the destination directory.

Removing the `private_` prefix works as you say - thanks!
