### ISSUE TITLE
What is the right way to managed an application managed file that is GPG encrypted?

### ISSUE THREAD

**Issue by Blackphidora** [twpayne/chezmoi#755]
## What exactly are you trying to do?

I have a config file managed by an external program (Rclone and ~/.config/rclone/rclone.conf) that is added using `chezmoi add --encrypt` I would like to keep this file encrypted but Rclone is used to edit and manage the config file.

## What have you tried so far?

I took a look and found [this page](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#handle-configuration-files-which-are-externally-modified) But this method still keeps the file contents readable

## Where else have you checked for solutions?

* [X] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```
$ chezmoi doctor 
     ok: version 1.7.12, commit bed22fcb91787c0d3d2d8ca61ebfe7799380f961, built at 2020-01-24T02:30:18Z
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/blackphidora/.local/share/chezmoi (source directory, perm 700)
     ok: /home/blackphidora (destination directory, perm 711)
     ok: /home/blackphidora/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /usr/bin/nvim (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.25.4)
     ok: /usr/bin/gpg (GnuPG, version 2.2.18)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
     ok: /usr/bin/keepassxc-cli (KeePassXC CLI, version 2.5.4)
warning: lpass (LastPass CLI, not found)
     ok: /usr/bin/pass (pass CLI, version 1.7.3)
warning: vault (Vault CLI, not found)

```

## Additional context
My gut reaction fix idea would be to allow `chezmoi edit` to have a `--proxy` command flag, which would return a path to stdin that I could then pass to Rclone, however this seems more like a hack than a solution.

ex: 

`alias 'rclone config'='rclone config --config $(chezmoi edit ~/.config/rclone/rclone.conf --proxy --apply)`

**Comment by twpayne** [comment]
I might have misunderstood something, but I think this is already achievable:

* chezmoi encrypted files are only encrypted in the source directory. When you run `chezmoi apply` the decrypted plaintext file is written to the destination directory. Therefore, rclone should already see an unencrypted file in `~/.config/rclone/rclone.conf`.

* After rclone has modified the config file, you can update it in the source directory by running `chezmoi add --encrypt ~/.config/rclone/rclone.conf`.

So, I think you want:

```bash
alias 'rclone config`=`rclone config --config $HOME/.config/rclone/rclone.conf && chezmoi add $HOME/.config/rclone/rclone.conf
```

**Comment by Blackphidora** [comment]
Very close, I was able to achieve what you mention with the following
`alias rconfig='rclone config && chezmoi add --encrypt $HOME/.config/rclone/rclone.conf'`

This solves my current issue. Thank you very much!

Ryan Walter
Ryan@blackphidora.com

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
