### ISSUE TITLE
Docs: .chezmoiignore how to example incorrect

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#761]
## Describe the bug

In the docs https://www.chezmoi.io/docs/how-to/ it reads:

```
README.md
{{- if ne .chezmoi.hostname "work-laptop" }}
.work # only manage .work on work-laptop
{{- end }}
```

Shouldn't it say `eq` instead?

Also, the text slightly above this is missing some sort of word in this text:

> For coarser-grained control of files and entire directories are managed on different machines

**Comment by twpayne** [comment]
I agree that `ne` looks weird, but it's actually correct.

What we want to achieve is "only install `.work` if hostname is `work-laptop`" but chezmoi installs everything by default, so we have to turn the logic around to be "ignore `.work` unless the hostname is `work-laptop`".

Thanks for spotting the other doc problem. I'll update the docs to make the use of `ne` clearer and fix the second problem.

**Comment by thernstig** [comment]
Ah right, it is an ignore so we want the opposite of equal in this case, thanks for explaining.
