### ISSUE TITLE
Persist file permissions for group and other

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#769]
First, as I have not said this yet, great tool! I was evaluating all kind of various dotfile tools and found this one to be the most well-thought implementation. Great job 😃 

## Is your feature request related to a problem? Please describe.

By example:

```sh
# In my home directory
~> ll testingprivexec2.txt
.rwx--x--x 7 userA groupA 24 May 10:56 testingprivexec2.txt*
~> chmod 711 testingprivexec2.txt
~> chezmoi add testingprivexec2.txt
~> chezmoi apply
~> ll testingprivexec2.txt
.rwxrwxrwx 7 userA groupA 24 May 10:56 testingprivexec2.txt*
```

If I set a specific `group` or `other` permission on a file in my home directory that is controlled by chezmoi, that permission is not persisted after a `chezmoi apply`. By experiment I've found it to use the umask, which does feel natural as that is how it works e.g. for `git clone`.

It would be nice though if all file permissions could be persisted. It is possible this is not in the scope of chezmoi.

## Describe the solution you'd like

I have not investigated this deeply, but here is an outlandish idea that at least works i git. Use [git notes](https://git-scm.com/docs/git-notes) e.g. like shown here https://stackoverflow.com/a/5960171. This could also be used to store the private and executable info, so files did not have to get renamed to `executable_` or `private_` etc. 

## Describe alternatives you've considered

No alternatives considered.

**Comment by twpayne** [comment]
Thank you for your kind words about chezmoi :)

> It would be nice though if all file permissions could be persisted. It is possible this is not in the scope of chezmoi.

It's true that chezmoi has a very simple model of permissions: private/not private and executable/not executable. `chezmoi add` considers a file executable if any of the user/group/other permissions are executable, and considers a file private if neither group nor other have any permissions.

This does mean that permissions like `711` are not preserved precisely: chezmoi considers such a file to be not private but executable, which means that when you run `chezmoi apply` it will be given permissions `777 &^ umask`, usually `755` when `umask` is `022`.

At the same time, `711` permissions on a file are slightly strange, and I genuinely am not sure how different operating systems would treat such a file. Are you allowed to execute a file without reading its contents? Of course, it's different for directories where `r` means reading contents and `x` means that you are allowed to traverse it.

Could you give a concrete example of file permissions that chezmoi doesn't handle (like `711`) that you'd like to preserve and why you want to preserve them?

Note that is a quick fix you can patch up permissions with a `run_` script which will get run on every `chezmoi apply`, e.g.

`~/.local/share/chezmoi/run_fix-perms.sh`
```sh
#!/bin/sh

chmod 711 ~/testingprivexec2.txt
```

**Comment by twpayne** [comment]
BTW, thank you for the suggestion of git notes. I've used git for a long time but had no idea that they existed. Note that git notes are attached to a blob, i.e. some file's contents, so they are lost when you change the file's contents, which is probably undesirable.

chezmoi also aims to be independent of the version control system that you use (although obviously it has extra integration with git because that's what most people use most of the time). In theory you could zip up a chezmoi source state (which contains just simple files and directories), unzip it somewhere else, and run `chezmoi apply` pointing at the unzipped files. chezmoi stores all of its metadata in file/directory names.

**Comment by thernstig** [comment]
My example was admittedly a bit contrived with `711` 😄 A more real example would have been `744`, where `group` and `other` has `r`, but not `w` or `x` rights. Not that common, but it could be the case.

I think my main concern was that something that was only `x` suddenly also turned into `w`. This means it's possible for another user to re-write the file and then execute it. E.g. on my Ubuntu 16.04 install the default umask was 000 unless I set one in my own shell config startup files.

I am honestly not sure anything can be done about all this, I just wanted to lift a potential risk and thought `git notes` could be a solution. It'd be possible to check previous git notes of a file in a git hook and re-add whatever it was previously, but it is definitely not VCS agnostic 😞 

p.s. The `run_` was a happy, and cool, surprise! Thanks for that hint. I will make sure to read _all_ docs from end-to-end one day soon.

**Comment by twpayne** [comment]
I agree that chezmoi's simple model of permissions cannot model `744`, but I haven't seen such permissions used in practice, especially not in the context of managing an individual's dotfiles. Have you encountered such an example?

> E.g. on my Ubuntu 16.04 install the default umask was 000 unless I set one in my own shell config startup files.

That's a bit strange. Ubuntu normally uses `022` as the umask:

```
$ docker pull ubuntu:16.04
$ docker run ubuntu:16.04 /bin/sh -c umask
0022
```

**Comment by thernstig** [comment]
`744` not that much, but `644` is not that uncommon. I am using [wsl](https://ubuntu.com/wsl) where the default umask is set to 000 (or 0000 to be explicit).

Another Ubuntu install I have (a real VM this time) has 0002.

I am ok with closing this issue, as the permission model has the "fail-safe" with umask. I thought that possibly `git notes` or something else could be used to achieve complete 1-to-1 permission, but it is also possible that is something users do not want. That they rather stay with the umask way of handling it. I'm still very pleased with how well thought out all this is from the start.

**Comment by twpayne** [comment]
`644` is the default permissions if neither of the `private_` or `executable_` attributes are set.

Systems that use a umask of `002` usually have user-specific group (i.e. the user's primary group is a group with the same name as the user and containing only that user).

The `000` umask in WSL is a bit surprising. I'll look into this in more detail as I want to support Windows and WSL as first-class citizens.

**Comment by liukun** [comment]
Since there may be more attributes. Would it be easier that using a separate file to store the attributes?
For example:
```
file_.bashrc
attr_.bashrc.json

dir_.config/
attr_.config.toml
```

`git notes` is good but will not follow the file if its content changed.

**Comment by thernstig** [comment]
Adding a git hook to handle `git notes` is an idea that might work and not be too exotic. I think the biggest problem is that it does not scale to other SCMs. Unless you use other features in those depending the system used.

**Comment by twpayne** [comment]
Thanks for the suggestion @liukun.

I recently added the FAQ entry [Can I change how chezmoi's source state is represented on disk?](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#can-i-change-how-chezmois-source-state-is-represented-on-disk) to provide more background information on why chezmoi uses its current system and the criteria that changes to it must meet.

**Comment by m-rey** [comment]
Would it be possible to add the file permissions to to the filename (like it is done currently), but by specifying it in a more granular way than `encrypted` or `private`?
Like adding `711` somehow to the filename (of a file that has `0o711` permissions) and applying those permissions on a "best-effort" basis, when using `chezmoi apply`?

**Comment by twpayne** [comment]
What is the concrete use case for permissions `0o711` in your dotfiles?

**Comment by m-rey** [comment]
I personally have no use case for permissions `0o711` in my dotfiles and am happy the way permissions are managed at the moment. Permissions `711` were just an example, because you mentioned it here: https://github.com/twpayne/chezmoi/issues/769#issuecomment-634269028.
I just wanted to ask if adding the exact permission to the filename could be an option to solve this issue, instead of using things like git notes.

**Comment by twpayne** [comment]
git notes is definitely not an option because they are version control system specific and are lost whenever the contents of the file changes.

We can of course extend the attributes to support different permissions. I propose to do this when there is a clear requirement for permissions other than the ones currently supported by chezmoi, and not before.

**Comment by thernstig** [comment]
I suppose a `.chezmoipermissions` file would not work to mark all file and paths? Maybe not the best idea :)

One thing with the current system is that it is very verbose, so when I compare files 1-to-1 directly with what I have in my home directory it is not an immediate 1-to-1 mapping you see. With permissions not in the file name, the only difference would be the .tmpl at the end. Not a huge deal though.

**Comment by twpayne** [comment]
> One thing with the current system is that it is very verbose, so when I compare files 1-to-1 directly with what I have in my home directory it is not an immediate 1-to-1 mapping you see.

Note the current commands for comparing files between:
* `chezmoi diff`
* `chezmoi managed`
* `chezmoi unmanaged`

**Comment by thernstig** [comment]
I open the chezmoi repo in my editor (VS Code) to view all files, that is the context I work in when editing files. If it would have looked exactly like my home dir (with the addition of .tmpl) it would have felt like directly actually editing my home dir (recognizability).

Please don't take this as critique, I am just stating the ins and outs of my experience. I'm promoting Chezmoi to my heart's content as the nr. 1 dotfile project.

**Comment by thernstig** [comment]
I've found another thing that is a bit cumbersome with the permission handling. Editors, such as VS Code, can automatically highlight files with the correct syntax (language mode). E.g. if you edit a .bashrc file, VS Code will know to parse and higlight the code as bash.

As chezmoi renames it to dot_bashrc, this is not the case anymore. Admittedly it is possible to manually select the language mode. But as I open my whole chezmoi source directory in my editor VS Code when I want to do changes, it is not a great experience have to do that for every file. And if you work across computers (which kind of is the purpose of chezmoi), when you open the same file in VS Code on the other computer, that language mode selection does not persist - so I have to re-do it for every host.

**Comment by m-rey** [comment]
The workaround I use for vim is to add metadata that helps (neo)vim recognize the filetype. For example, I've added something like the following comment in my `.zshrc` file:
`# vim:filetype=zsh`
Now the syntax highlighting works again, even though the file extension is `.tmpl`. 
See here, for example: https://github.com/m-rey/dotfiles/blob/20c74b96052e2503ab8aad73e59ce192a5f18572/dot_config/zsh/dot_zshrc.tmpl#L139

**Comment by thernstig** [comment]
@m-rey That is not a great solution. Imagine there are 100 editors, that would mean you need 100 lines of code at the start of every file. In actuallity, I've done a lot of PRs in projects to _remove_ vim specific file-metadata. It's just a bad practice vim is using.

**Comment by twpayne** [comment]
With #1403 chezmoi now has a `readonly_` attribute which clears the write permission bits for all users. I think that this, combined with `private_`, `executable_`, and a custom `umask` allows all practical file and directory permissions to be represented. Please re-open if needed.

**Comment by thernstig** [comment]
@twpayne have you considered using git notes as, if I got this correctly, git is the only supported source control now? There are benefits over renaming, such as editor support.

**Comment by twpayne** [comment]
My understand of [git notes](https://git-scm.com/docs/git-notes) is that they are attached to git objects. Whenever you commit a new version of a file it will be represented by a new git object, which means that the previous notes will effectively be lost and the user will have to manually copy the notes from the old object to the new object.

[gitattributes](https://git-scm.com/docs/gitattributes) would perhaps be a better fit, but there are still a couple of problems:
1.  chezmoi's name mangling also have the effect of marking which files are part of the source state and which files are part of the git repository. As a specific example, without name mangling, how would you tell git and chezmoi that `.gitignore` should be a file in your home directory and not treated as a `.gitignore` file in your dotfiles repo?
2. Using `gitattributes` would mean that you'd need to manually maintain a `.gitattributes` file, which is tiresome and error prone.

That said, I think I have a possible solution for editing...
