### ISSUE TITLE
Add support for not syntax in ignore file

### ISSUE THREAD

**Issue by 3v1n0** [twpayne/chezmoi#773]
Would be nice to be able to ignore files not matching a pattern as well

**Comment by twpayne** [comment]
This should already be supported. What version of chezmoi are you using? Do you have an example where it does not work as you expect?

**Comment by 3v1n0** [comment]
> This should already be supported. What version of chezmoi are you using? Do you have an example where it does not work as you expect?

I'm using the snap at version chezmoi version 1.8.1, commit 4def4f3b96cb01cefe8d7887e8dbfb77908ef267, built at 2020-05-06T18:12:58Z, built by goreleaser.

I was thinking to something like git allows (https://stackoverflow.com/a/987162/210151)

**Comment by twpayne** [comment]
chezmoi should already support the `!` syntax in `.chezmoiignore` files in the version you are using. Do you have an example where it does not work as expected?

**Comment by twpayne** [comment]
Timed out waiting for response.
