### ISSUE TITLE
More helpers in templates.

### ISSUE THREAD

**Issue by rajaravivarma-r** [twpayne/chezmoi#774]
## What exactly are you trying to do?
I am trying to use helpers in the template files, like `if chezmoi.os.pathExists?(chezmoi.home.joinpath('.pyenv')`, to dynamically generate `.bash_profile`.
Describe in as much detail as possible.
I looking for helper methods in template files apart from the ones provided by sprig. Additional helper methods like `fileExists`, `dirExists`, `isExecutable` would be helpful indeed.

## What have you tried so far?
Checked if sprig supports such helpers and found out that it doesn't.

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi command --verbose
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
chezmoi templates only get executed when you run `chezmoi apply`, which you only need to do when you change your dotfiles. For behavior conditional on the presence of files, I would strongly recommend doing this in the dotfile itself, instead of using templates, for example:

`~/.bashrc`
```bash
#!/bin/bash

if [ -f ~/.pyenv ]; then
   # config for if ~/.pyenv exists
fi
```

This makes your dotfiles more adaptable and means that you don't have to run `chezmoi apply` so often.

Hope this helps - is there a usecase that this does not cover?

**Comment by rajaravivarma-r** [comment]
I have been doing it like this, but there are lot of such conditions, which makes sourcing the `.bash_profile` slow. It impacts everytime I open a new tab in the terminal. So I was wondering if this was possible to do. If this is something not desired, then please close the issue.

**Comment by twpayne** [comment]
Another option is using custom template variables, for example:

`~/.config/chezmoi/chezmoi.toml`
```toml
[data]
    pyenv = true
```

`~/.local/share/chezmoi/dot_bashrc.tmpl`
```
#!/bin/bash

{{ if .pyenv }}
# pyenv config
{{ end }}
```

I'm hesitant to add too many non-hermetic functions to the template system as they make the template execution depend on external factors and therefore hard to reason about. I realize that I'm not 100% consistent on this, for example chezmoi imports `env` from `Masterminds/sprig` which allows you to use environment variables in your templates (#655), but I want to set a high barrier for such functions.

**Comment by rajaravivarma-r** [comment]
Thank you for the suggestion. I got the point and I will close the issue.

**Comment by twpayne** [comment]
Re-opening because clearly this functionality would be useful.
