### ISSUE TITLE
Explain the different 'states' in the FAQ

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#775]
## Is your feature request related to a problem? Please describe.

In a lot of documentation, the terms 'source state', 'target state' and 'destination state' is mentioned. There is no place in the docs where these are described what they mean, and they are not easy to understand directly if you are new to chezmoi. (Although you will get it after a while.)

## Describe the solution you'd like

An entry in the FAQ explaining these states to a beginner. Possibly also that the section should be linked to from one of the mentions of "state" in the [Quick Start](https://www.chezmoi.io/docs/quick-start/).

## Describe alternatives you've considered

Be smarter than I am to grok these terms directly, but I've yet to find a reliable supplier of brain upgrades.

**Comment by twpayne** [comment]
These are documented in the first section of the reference manual: https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#concepts

However, the FAQ can clearly be improved here!

**Comment by thernstig** [comment]
@twpayne Apologize for missing that, I will close this. I think that is sufficient.

**Comment by thernstig** [comment]
Although it is possible that the difference between `target` and `destination` can be hard to understand. At least the first time reading them. Reason being the words could be seen as synonyms.

Subjectively, I would have found `current state` easier to grok than `destination state`.

**Comment by twpayne** [comment]
> Subjectively, I would have found `current state` easier to grok than `destination state`. But that will not fit well with `destination directory` - so `destination` is most likely already a good choice.

Thanks, I pushed 7c79c88b422c5ae6f8b0bea8c4087d96d53045c1 to address this. I think the "destination" is important because the source and target states can also be "current".
