### ISSUE TITLE
Fish shell: Completion not installed with 'curl -sfL https://git.io/chezmoi | sh'

### ISSUE THREAD

**Issue by thernstig** [twpayne/chezmoi#777]
## Describe the bug

Fish shell: Completion not installed with `curl -sfL https://git.io/chezmoi | sh`

## Additional context

It installs fish completions fine with the .deb package. I also realize there is a command to do this, https://www.chezmoi.io/docs/reference/#completion-shell, but would it not be nice to do this by default with the above installer?

Also the above example shows that they are placed in the the user local directory. It's possible the installer should place them in the vendor dir? https://fishshell.com/docs/current/#where-to-put-completions

Possibly a separate issue: Does `chezmoi upgrade` also update completions depending on the way chezmoi has been installed?

**Comment by twpayne** [comment]
Thanks for reporting this, but this is not really fixable.

The one line shell installer just installs the binary. It is designed to run as a normal user who (on most systems) does not have permission to create files in the shared directory where completions are stored (`/usr/share/fish` on most Linux systems, for example).

Packages are installed by the root user and so do have permission to add files to the shared directory.

`chezmoi update` tries to detect how chezmoi was installed and re-use the same mechanism. It's subject to the same permissions limitations.

**Comment by thernstig** [comment]
Would it be possible, or smart, for the install script to detect which current shell is used and output in the terminal on how to install completions? I know the info exists on chezmoi.com but it would be more discoverable by new users if the user got direct feedback on how to install completions, Just an idea.

**Comment by twpayne** [comment]
The install script is generated by [`github.com/goreleaser/godownloader`](https://github.com/goreleaser/godownloader). I personally don't want to spend lots of time writing shell scripts that will save a handful of users a couple of minutes, but contributions are welcome :)
