### ISSUE TITLE
Manage multiple dotfiles config

### ISSUE THREAD

**Issue by luigibarbato** [twpayne/chezmoi#780]
## What exactly are you trying to do?

Currently I have my own configuration of the dotfiles generic and therefore perfect for the public. I would like to have a second version of this configuration for my personal customizations. So every time I would like to implement a switch between the two to make different changes. How is it possible to manage this situation in the best way with chezmoi?

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.

**Comment by twpayne** [comment]
I'm sorry, I don't understand what you are trying to do.

Please could you give some shell commands that demonstrate what you want to do.

**Comment by luigibarbato** [comment]
> I'm sorry, I don't understand what you are trying to do.
> 
> Please could you give some shell commands that demonstrate what you want to do.

I have two config: A and B

i would to switch from configuration A to configuration B everytime I need a different enviroment configuration

**Comment by twpayne** [comment]
Ah, I see.

Here are a few suggestions:

1. Use two completely different source directories and pass the `-S` (`--source`) option option when you run `chezmoi apply`, e.g. `chezmoi apply -S ~/.local/share/chezmoi_configA`, `chezmoi apply -S ~/.local/share/chezmoi_configB`.

2. Make the dotfiles that vary between the two configurations templates, and then use one of the following options:
    1. Use a template variable (set in your configuration file) to control the templates. Either edit the configuration file before running `chezmoi apply` or use multiple configuration files (one per config) and pass the `-c` (`--config`) option to `chezmoi apply`, e.g `chezmoi apply -c ~/.config/chezmoi/chezmoi_configA.toml`.
    2. Use an environment variable, which you can read with the `env` function in templates, and set that environment variable before running `chezmoi apply`, e.g. `CONFIG=A chezmoi apply`.

Hope this helps.
