### ISSUE TITLE
Include other files in templates

### ISSUE THREAD

**Issue by hg-zt** [twpayne/chezmoi#787]
This would make managing configurations vary from machines more flexible.

## Describe the solution you'd like

`config.tmpl`
```ini
# Common
## Keybindings
"Ctrl-A" = ...
"Ctrl-B" = ...
## Other settings
show_line_numbers = true

# OS specific
{{ if eq .chezmoi.os "linux" -}}
cache_dir = $XDG_CACHE_HOME/my-app
  {{ include linux.conf }}
{{ else if eq .chezmoi.os "darwin" -}}
  ...
{{ end -}}

# Machine specific
; Or maybe in this form? I'm not familiar with golang so I'don't know if it's possible
{{ include {{ .chezmoi.hostname }}.conf }}

```

In fact, I'm already managing my emacs config in this way. Since elisp is a programming language, it's easy to load(include) other files. But many config file types (`.toml`, `.conf`, etc.) are lack of such abilities.

**Comment by twpayne** [comment]
You can use a `.chezmoitemplates` directory to do almost exactly this, see the [section in the reference manual](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoitemplates). See also [this issue discussion](https://github.com/twpayne/chezmoi/issues/749#issuecomment-628048523) for a worked example including passing parameters.

chezmoi could certainly be better documented here.

**Comment by hg-zt** [comment]
Thanks for your quick reply!
I did find `{{ template ... }}` on the golang template reference page but do not have idea of how to use it.

**Comment by Legion2** [comment]
@hg-zt you use `{{ template ... }}` just like `{{ include... }}` but you only can include files from the `.chezmoitemplates` directory.

@twpayne can we also "include" files outside `.chezmoitemplates`? For Example:
`.chezmoiignore`
```
.bashrc_*
```

`dot_bashrc_linux`
...
`dot_bashrc_windows`
...

`dot_bashrc.tmpl`
```
{{ if eq .chezmoi.os "windows" }}
{{ include "dot_bashrc_windows" }}
{{ end }}
{{ if eq .chezmoi.os "linux" }}
{{ include "dot_bashrc_linux" }}
{{ end }}
´´´
So we don't have to use symlinks

**Comment by twpayne** [comment]
> @twpayne can we also "include" files outside `.chezmoitemplates`?

Right now, you can only include files in `.chezmoitemplates`, but I can add a template function to include arbitrary files.
