### ISSUE TITLE
Add gpg or asc suffix to encrypted files

### ISSUE THREAD

**Issue by renard** [twpayne/chezmoi#789]
## Is your feature request related to a problem? Please describe.

Many editors such as Emacs or vim allows to perform transparent decryption / encryption of files with `.pgg` or `.asc` suffix. It would be nice to have an option to let the user chose if he want to add a suffix or not to encrypted files.

This will also allow the user to edit files directly from the repo without having to invoque chezmoi.

## Describe the solution you'd like

An option in the configuration file such as:

```
# Use .gpg for binary encryption or .asc for armored encryption.
gpg.suffix = ".gpg"
```

## Describe alternatives you've considered

Reconfiguring the editor to handle files starting with `encrypted_` fo be handled. This is not a good solution in the long term since those changes are very chezmoi related.

**Comment by twpayne** [comment]
Thanks for the suggestion, this makes good sense. Also when/if chezmoi eventually adds age support (#539) this will help distinguish between gpg- and age-encrypted files.

I'd like to get version 2 released first (#654) but I expect to add `gpg.suffix` as you request in the future.
