### ISSUE TITLE
Scripts are not executed if the name after `run_` matches another file

### ISSUE THREAD

**Issue by ptxmac** [twpayne/chezmoi#791]
## Describe the bug

If a file next to a script has the same name it will silently be overwritten when the target state is populated

## To reproduce

Create a file named `install_packages` and another `run_install_packages` (or `run_once_`).

## Expected behavior

It would expect this to "just work" or at least give a warning/error that it's not allowed

## Additional Context

In my case the `install_packages` file is a script downloaded from the internet that I prefer not to change, and to run it I want chezmoi to add additional arguments (i.e. adding `-y` to auto-accept some question). It seemed logical to have the run_once_ script use the same name, but I caused a lot of confusion as it did work.

**Comment by twpayne** [comment]
Great catch, thanks!

I'll target a fix for this in v2 (#654).
