### ISSUE TITLE
Support `difftool.cmd` and `mergetool.cmd` like git

### ISSUE THREAD

**Issue by hg-zt** [twpayne/chezmoi#793]
`chezmoi merge` supports additional args, while the order of `dest` `source` `target` is hard-coded. It is suitable for `vimdiff`, but tools like `meld`, `vscode` won't work like this (e.g. `vscode` would open three files)

Here's how to setup `meld` in git config (from https://stackoverflow.com/questions/34119866/setting-up-and-using-meld-as-your-git-difftool-and-mergetool)
```ini
[diff]
    tool = meld
[difftool]
    prompt = false
[difftool "meld"]
    cmd = meld "$LOCAL" "$REMOTE"

[merge]
    tool = meld
[mergetool "meld"]
    # Choose one of these 2 lines (not both!) explained below.
    cmd = meld "$LOCAL" "$MERGED" "$REMOTE" --output "$MERGED"
    cmd = meld "$LOCAL" "$BASE" "$REMOTE" --output "$MERGED"
```

<details><summary>vscode</summary>
<p>

```ini
[merge]
    tool = vscode
[mergetool "vscode"]
    cmd = code --wait $MERGED
[diff]
    tool = vscode
[difftool "vscode"]
    cmd = code --wait --diff $LOCAL $REMOTE
```
</p>
</details>

<details><summary>emacs</summary>
<p>

```ini
[difftool "ediff"]
          cmd = emacs --eval \"(ediff-files \\\"$LOCAL\\\" \\\"$REMOTE\\\")\"
[difftool "ediffclient"]
          cmd = emacsclient --eval \"(ediff-files \\\"$LOCAL\\\" \\\"$REMOTE\\\")\"
```

</p>
</details>

## Describe the solution you'd like

- add `diff.command`
- allow interpolation in `merge.command` and `diff.command` for `$SOURCE, $TARGET, $DESTINATION`

  - or `$LOCAL, $REMOTE, $MERGED` (like git)
  - or `{{ .source }} ` ...

**Comment by twpayne** [comment]
Thanks for the suggestion. This makes sense, but will likely land sometime after v2.

**Comment by twpayne** [comment]
#1324 adds configurable argument order for the merge command.

How do you see the configurable diff command working when there are multiple files with differences? Should the diff command be invoked once for each one?

chezmoi's builtin diff handles both symlinks (showing a diff if a symlink would change) and scripts (showing the contents of the script that would be run). How should the configurable diff command handle these?

**Comment by hg-zt** [comment]
> #1324 adds configurable argument order for the merge command.

Great!

> How do you see the configurable diff command working when there are multiple files with differences? Should the diff command be invoked once for each one?

`git-difftool` invokes external tools in serial by default. So chezmoi could do the same. After all, external difftool is desired when the change set is more than a few lines and need to be reviewed per file.
`git-difftool` has an option (`--dir-diff`) for comparing all files at directory-level which is supported by tools like meld. But files managed by chezmoi are scattered over the $HOME tree so I'm afraid chezmoi could not take this approach.

> chezmoi's builtin diff handles both symlinks (showing a diff if a symlink would change) and scripts (showing the contents of the script that would be run). How should the configurable diff command handle these?

Maybe chezmoi could send file changes to external tools, and show special changes afterwards, or at least warn users that there are additional changes except from those shown in external tools.
