### ISSUE TITLE
Script modifying/using tracked files/chezmoi config

### ISSUE THREAD

**Issue by vogu66** [twpayne/chezmoi#794]
## What exactly are you trying to do?

I have two use cases in mind. 

1. Suppose you have a bunch of aliases linked to specific programs. When you do `chezmoi apply`, you would like only the aliases for which the program is installed to be added. Similarly, you may want scripts or other files to be added only if the relevant programs are there.

2. For the .ssh folder, there is a number of connection configurations. For each connection, if there is no corresponding authentication key, then one may want a script to generate one.

## What have you tried so far?

Well, the way I see it, there are three ways to solve this, none are really elegant and I wonder if there is an alternative I haven't thought about. Also, the actual implementation depends on whether scripts are run before or after the changes have been applied to the computer -- I couldn't find that bit of information in the documentation, but I suppose it's after the application and not before.

1. For the first problem and not the second, I could have a script that lists all existing programs and adds them to the configuration file in the data section. Then I would use templates to check whether a program is in the list. If the scripts run after application, I would either need to apply changes twice every time to have the list used in the templates, or I could use the script separately (I suppose I could add `chezmoi apply` at the end of the script so I only need to run a single command). That would have the drawback to make a pretty uselessly long config file and it can't be used for every purpose but otherwise it's an ok solution, I think.

2. I could read the config file, check that the programs mentioned in it are there (or not) and modify the config file accordingly, and for the ssh hing I could just find in the config file the list of identities and use those. Now, this only works if the scripts are run before the application, because otherwise changing the config file is pretty useless. In addition, it seems redundant to parse the config file manually when `chezmoi` will parse it as well just afterwards.

3. If the scripts run after the application, I could make a script that reads the output and modifies it accordingly or uses its data accordingly. That has the drawback to leave uncommitted changes in the output files, plus reading a non-systematic file is, well, non-systematic.

So, I was wondering if there were a more elegant way to do this? The best solution I could come up with was to have functions in the template that work like the "secret" function, they would take a given text argument and potentially return text. For the first case you would just add `if program_exists <program>` in the template, and for the second you would simply add, after the account is set, `keygen <key-name>`, it wouldn't change the template if the result was just an empty string. And you define `keygen` and `program_exists` as a script or command that can be passed to the shell with text arguments.

I'm not sure if something like that or an alternative solution already exists, which is why I put this in support and not enhancement. Plus, it "breaks chezmoi's declarative approach", just as the scripts, so maybe it could not be implemented.

As a side note, it could also nicely enhance or just resolve the need for issue #664 .

## Where else have you checked for solutions?

* [x ] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x ] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x ] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x ] Other, please give details.

<https://pkg.go.dev/text/template?tab=doc#example-Template-Helpers>

<http://masterminds.github.io/sprig/>

**Comment by twpayne** [comment]
> Also, the actual implementation depends on whether scripts are run before or after the changes have been applied to the computer -- I couldn't find that bit of information in the documentation, but I suppose it's after the application and not before.

chezmoi runs through things in alphabetical order, so whether scripts run before changes to the file system or vice versa depends on the name of the files and the names of the scripts. If you call your scripts `run_000_first.sh` or `run_zzz_last.sh` then you should be able to ensure first or last execution. This might be a bit flaky in corner cases with the current version (but should always be consistent), and will be reliable in v2 (#654).

> For the first case you would just add `if program_exists <program>` in the template

#800 (just created) might help here. It adds a function `lookPath` that can be used to determine if `<program>` is in your `$PATH`.

For the rest of points in this issue, I need to think a bit more :)

**Comment by vogu66** [comment]
Both things are good to know, thanks a lot ! It makes it possible to work something in any case I can think of, really.

Also, just because I'm reading what I wrote again, and it doesn't seem really clear, the idea I had was to have custom scripts that can be registered as custom template commands by the user. The way I re-read it was more just specific commands that could be added to chezmoi, but that's not what I meant. Which is why it could be an alternative for #664; you could have `.chezmoi.<format>.tmpl` ask a question about the configuration and launch the related scripts as well as modify the related config, or if you need more information (say, you want chezmoi to install something only if there is enough RAM and if the pc has a configuration "video" for example) you could launch a script to check the ram only after the configuration has been decided as "video".

Now, it's just an idea, and you do what you want with it, I suppose you can change and re-open the issue as enhancement or link it if you want to have an example at hand for the feature, if you decide it's worth investigating more. With the lookPath function though the use becomes super specific applications, which can be worked around with normal scripts, I think, although sometimes it would be interesting to get information directly rather than re-reading the config file. In the meantime I'll close this since the questions have been answered; thank you, by the way.
