### ISSUE TITLE
Can't get the "get" function (sprig) to work

### ISSUE THREAD

**Issue by vogu66** [twpayne/chezmoi#795]
## What exactly are you trying to do?

I have in data a list of ssh config : 
```
[data]
  [[data.ssh_config]]
    friendly="GitHub.com, vogu66"
    host= "github.com"
    hostname= ""
    id= "github_vogu"
  (...)
```
And I want to extract one key of one element using slice then get.

## What have you tried so far?

I have in the template : 

```
# {{ $account := slice .ssh_config 4 5}}
# {{ $account := first $account }}
# {{ $account }}
# {{ get $account "id"}}
```

Which gives, using `chezmoi -nv apply` :

```
chezmoi: template: /home/vogu/.local/share/chezmoi/executable_dot_alias.tmpl:17: function "get" not defined
```

And as far as I know, it should work. When doing : 

```
# {{ $account := slice .ssh_config 4 5}}
# {{ $account := first $account }}
# {{ $account }}
# {{ hasKey $account "id"}}
```

I get (with names instead of ####)

```
+# 
+# 
+# map[friendly:#### host:#### hostname:#### id:#### user:####]
+# true
```

And set works as well.

## Where else have you checked for solutions?

* [*] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [*] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [*] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```
~ >>> chezmoi doctor   
warning: version dev
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/vogu/.local/share/chezmoi (source directory, perm 700)
     ok: /home/vogu (destination directory, perm 700)
     ok: /home/vogu/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/zsh (shell)
     ok: /usr/bin/nano (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.27.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.20)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

I'm using manjaro and the version 1.8.1-1 of the official repo.

## Additional context

This tool is great, thanks.

**Comment by twpayne** [comment]
You can use `.` notation to get an individual field:

```
$ chezmoi execute-template '{{ (index .ssh_config 0).id }}'
github_vogu
```

**Comment by twpayne** [comment]
Hopefully this answers your question. Please re-open this issue if needed. Apologies for closing this issue without getting confirmation from you first - I'm doing a quick tidy of issues after getting back from holiday.

**Comment by vogu66** [comment]
Yes it does, thanks a lot, really !
