### ISSUE TITLE
Support symlinks for ignored files

### ISSUE THREAD

**Issue by vogu66** [twpayne/chezmoi#796]
## Is your feature request related to a problem? Please describe.

It's annoying to switch between the config file and the repo, so I added a symlink to `~/.config/chezmoi/chezmoi.toml` in `~/.local/share/chezmoi/`, and I added it to `.chezmoiignore`. Unfortunately, the file type is marked as "unsupported" so `chezmoi` doesn't work.

## Describe the solution you'd like

It would be nice if the check for supported file type ran only on files that aren't in `.chezmoiignore`.

## Describe alternatives you've considered

It's pretty much the only solution I see since that way the contents of the config file don't go online, and without that I need two atom windows open at the same time.

**Comment by twpayne** [comment]
Thanks, that makes sense. I'll target this for v2 (#654).

**Comment by twpayne** [comment]
I just added an initial implementation to #654. Symlinks are now followed from the source directory.

Notes:
* The file attributes are parsed from the file name but the contents are filled from following the link. For example, if you have `run_script` as a symlink to `dot_file` then this will be treated as a script to run with the same contents as the eventual `.file`.
* `.chezmoiignore` uses relative paths in the destination directory. If you create a symlink `chezmoi.toml` -> `$HOME/.config/chezmoi/chezmoi.toml` then you need to add just `chezmoi.toml` to your `.chezmoiignore` file.
* Symlinks are platform dependent. If you use symlinks in your dotfiles repo, they might not work on Windows.
* This change makes it easier to support the "same file contents, different locations" use case (#875, #164). Now you can have one file with the desired contents and the other being a symlink to it, and choose which gets instantiated with `.chezmoiignore`.

**Comment by vogu66** [comment]
Thanks a lot! I'll consider this solved then, so you can have less open issues, and I eagerly wait for v2 on the official repos.

**Comment by twpayne** [comment]
Thanks! I'll keep the issue open until v2 is merged through.
