### ISSUE TITLE
LastPass note values always come with an appended newline

### ISSUE THREAD

**Issue by JohnTasto** [twpayne/chezmoi#799]
I don't know if this is a bug or if I'm just missing something, so I'm writing this up as a support request.

## What exactly are you trying to do?

I'm trying to insert a value from LastPass between some quotes:
```yaml
# `home/john/.local/share/chezmoi/dot_stack/private_config.yaml.tmpl`
...
templates:
  params:
    ...
    author-email: '{{ (index (lastpass "keys/dotfiles") 0).note.email }}'
    ...
```

but it always comes with a newline at the end:
```diff
john@John-PC > /e/Haskell/arrows $ chezmoi diff
install -m 600 /dev/null /home/john/.stack/config.yaml
--- a/home/john/.stack/config.yaml
+++ b/home/john/.stack/config.yaml
@@ -8,10 +8,11 @@
 # See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
 templates:
   params:
-#    author-name:
-#    author-email:
-#    copyright:
-#    github-username:
+    author-name: 'John Tasto'
+    author-email: 'redacted
+'
+    category: 'Unclassified'
+    github-username: 'JohnTasto'

 # The following parameter specifies stack's output styles; STYLES is a
 # colon-delimited sequence of key=value, where 'key' is a style name and
```

## What have you tried so far?

- I've tried using `{{-` and `-}}` (they only affect whitespace outside the template)
- I've tried removing the newline after the `email` key in my LastPass note
- I've tried creating a new note with no newline for chezmoi/LastPass cache busting
- I've tried adding dummy keys and values after the `email` key
- I've tried adding _extra_ newlines after the `email` key, just to see what happens, and they actually come through in the output!
- I've tried adding a `quotedEmail` key and corresponding value - it works, but it feels like a hack and isn't my preferred solution, and still doesn't produce quite what I want

  - Exhibit A:

    ```yaml
        author-email: {{ (index (lastpass "keys/dotfiles") 0).note.quotedEmail }}
    ```

    ```diff
    john@John-PC > /e/Haskell/arrows $ chezmoi diff
    ...
    +    author-name: 'John Tasto'
    +    author-email: 'redacted'
    
    +    category: 'Unclassified'
    +    github-username: 'JohnTasto'
    +
     # The following parameter specifies stack's output styles; STYLES is a
    ...
    ```

    I don't know what this means in a diff, but

    - there is a new blank line with no corresponding `+` after the `author-email` key
    - there is a `+` after the `github-username` key on a blank line that was already there

    I ran `chezmoi apply` just to see the result, and there is indeed an extra line after `author-email`. It isn't ideal, but it does at least parse correctly

  - Exhibit B:

    ```yaml
        author-email: {{ (index (lastpass "keys/dotfiles") 0).note.quotedEmail -}}
    ```

    ```diff
    john@John-PC > /e/Haskell/arrows $ chezmoi diff
    ...
    +    author-name: 'John Tasto'
    +    author-email: 'redacted'
    +category: 'Unclassified'
    +    github-username: 'JohnTasto'

     # The following parameter specifies stack's output styles; STYLES is a
    ...
    ```
    `yaml` is indentation sensitive, so this won't work

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] I have searched [chezmoi's issue tracker](https://github.com/twpayne/chezmoi/issues), and not found any similar issues.
* [x] I have skimmed the [text/template documentation](https://pkg.go.dev/text/template?tab=doc), though admittedly not thoroughly.

## Output of `chezmoi doctor`

```
john@John-PC > /e/Haskell/arrows $ chezmoi doctor
     ok: version 1.8.2, commit 323cba56195179ade6b061fa2d6af37d16cd193e, built at 2020-06-09T13:42:18Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/john/.local/share/chezmoi (source directory, perm 700)
     ok: /home/john (destination directory, perm 755)
warning: /home/john/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /c/Program Files/Microsoft VS Code/bin/code (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.25.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
     ok: /usr/bin/lpass (LastPass CLI, version 1.3.3)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional comments

chezmoi is awesome, its the best solution I've found so far, way better than the custom scripts I'd been using. Thank you for creating it, and thank you for your help here.

**Comment by zb140** [comment]
You can use the sprig functions in your templates (http://masterminds.github.io/sprig/).  You might try something like this:

```
    author-email: {{ squote (trim ((index (lastpass "keys/dotfiles") 0).note.email)) }}
```

`trim` removes whitespace from the ends and `squote` wraps the string in single quotes.

**Comment by twpayne** [comment]
Thanks for the kind words @JohnTasto and thanks for the fix @zb140.

To give a bit more info on what's happening here:
* chezmoi tries to automatically parse the `note` section of the LastPass entry.
* The `note` section has no well-defined format and so cannot always be parsed reliably (see #607 for another example of this).
* In particular, a single `note` entry might span one or more lines.
* chezmoi keeps the newlines, even for single-line note entries like `email` as in this case, as it simplifies the parsing logic.

@zb140's suggestion of using the `trim` function is spot-on, and the `squote` function adds extra robustness in case the entry contains single quotes.

Note also that you can use pipes in templates, e.g.

```
{{ (index (lastpass "keys/dotfiles") 0).note.email | trim | squote }}
```

which can be a bit easier to read.

**Comment by JohnTasto** [comment]
Thanks, it works perfectly now!

I'm curious how `squote` makes it more robust. All of these produce the same output:
```yaml
author-email: {{ (index (lastpass "keys/dotfiles") 0).note.email | trim | squote }}
author-email: {{ (index (lastpass "keys/dotfiles") 0).note.quotedEmail | trim }}
author-email: '{{ (index (lastpass "keys/dotfiles") 0).note.email | trim }}'
```

and the combination:
```yaml
author-email: '{{ (index (lastpass "keys/dotfiles") 0).note.quotedEmail | trim | squote }}'
```

results in three nested quotes, as one would expect.

What is an example that would fail or produce an unexpected result without `squote`?

**Comment by twpayne** [comment]
Hope that this is now resolved. Please re-open if needed.
