### ISSUE TITLE
Can't use template functions in .chezmoitemplates?

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#802]
## Describe the bug

The various template functions (sprig functions, secret functions, the new file/executable stuff) can't be used in templates from `.chezmoitemplates`.  

## To reproduce

Put this file in `.chezmoitemplates/functest`:
```
{{ cat .one .two }}
```

and this in `.local/share/chezmoi/test.tmpl` (or similar):
```
{{ template "functest" (dict "one" "hello" "two" "world") }}
```

then run `chezmoi apply`

## Expected behavior

`~/test` should contain "hello world"

## Output of command with `--verbose`

Interestingly, the error message is a complete red herring:
```
$ chezmoi apply --verbose
chezmoi: file does not exist
```

## Additional context

After some digging, I tracked down the problem to this line: https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/targetstate.go#L755 . When the templates in `.chezmoitemplates` are parsed, they aren't given the template funcs.

I changed it to match the other template parsing line here: https://github.com/twpayne/chezmoi/blob/master/internal/chezmoi/targetstate.go#L392 and things start working as expected. But, I'm not certain if this is safe or not -- it seems to work as far as I've tested, but it could have been left out on purpose.  Is it expected that template functions should work in `.chezmoitemplates`?  If not, could it be? :wink:

**Comment by twpayne** [comment]
> Is it expected that template functions should work in `.chezmoitemplates`? If not, could it be? 😉

I think this is simply an oversight. Do you have a PR (with a test) ready? If not, I'll be able to look at it later today.

**Comment by zb140** [comment]
Thanks for the super quick fix!  I would have been happy to put together a PR, but I was asleep when your reply came in :smile:
