### ISSUE TITLE
Github authentication help

### ISSUE THREAD

**Issue by rmferrer** [twpayne/chezmoi#803]
## What exactly are you trying to do?
Hi! Thank you very much for writing chezmoi. I have been looking for something along these lines to manage dotfiles cross machine and I came across your project.

I am trying to use chezmoi init https://github.com/mydotiles_path to clone my existing chezmoi managed dotfiles onto another machine. When executing chezmoi asks for my github credentials which I would preferrably not enter. I would like to ask what the rationale for using master credentials vs using ssh keys that are scoped down to the project, and if that is a possible feature.

**Comment by Legion2** [comment]
chezmoi init clones the repo and you can give it any valid git repo url. This is not limited to the https url.

**Comment by twpayne** [comment]
As @Legion2, `chezmoi init` passes the repo URL directly to `git clone`, so you can do

    chezmoi init git@github.com:rmferrer/dotfiles.git

**Comment by twpayne** [comment]
Hope this is now resolved - please re-open if not.

**Comment by davidolrik** [comment]
Could we add a flag that would use ssh instead of https and save some typing?

E.g. ```sh
chezmoi init --ssh rmferrer
```

**Comment by twpayne** [comment]
@davidolrik In the future please make feature requests by opening a new issue rather adding comments to closed issues that are nearly a year old. Comments added to old, closed issues are easy to miss and do not appear in the list of open issues, and so are easily forgotten.
