### ISSUE TITLE
DOC: Broken links for chezmoi.io

### ISSUE THREAD

**Issue by Geod24** [twpayne/chezmoi#806]
The website https://www.chezmoi.io/ has a few broken links that refers to `.md` files.

E.g. the intro "Install chezmoi" references https://www.chezmoi.io/docs/INSTALL.md which is 404 (the correct link is https://www.chezmoi.io/docs/install/ which is accessible from the menu). Quick start guide and how-to are also affected.

**Comment by twpayne** [comment]
Thanks very much for reporting this :)
