### ISSUE TITLE
A way to guarantee the existence of a file, regarless of it's contents

### ISSUE THREAD

**Issue by zuntik** [twpayne/chezmoi#810]
## Is your feature request related to a problem? Please describe.

Applications like mpd need certain files to exist before their first run (like log files). They will have to be created by me but then they will be populated by the application with stuff that doesn't matter. I would like them to be created automatically by chezmoi.

## Describe the solution you'd like
Just as a .keep file guarantees that a target directory exists. I would like a "exists_" prefix given to a file such that chezmoi creates it but then ignores it, i.e., "chezmoi diff" won't complain if the target is different to the file in the repo.

A "exists_" prefix for files such that the target file exists but "chezmoi diff" shows nothing, regardless of the difference between the source and target files.

## Alternative, already existing, work around
The most obvious alternative would be a script to be run once that creates the files that are necessary with the "touch" command.

**Comment by twpayne** [comment]
Thank you very much for this request :)

Is there a case where the alternative, already existing, work around that you suggest is not a sufficiently-good solution?

**Comment by zuntik** [comment]
Yes, because the "chezmoi diff" command can help give a clue of why applications that need files to exist may not be working, because these necessary files may accidentaly be deleted throught the time of the computer's usage.

> 
> 
> Thank you very much for this request :)
> 
> Is there a case where the alternative, already existing, work around that you suggest is not a sufficiently-good solution?

**Comment by zb140** [comment]
Also, for what it's worth, something like an `exists_` prefix is more declarative about the desired state than `touch` inside a script would be.  A user could just mark a file (or hopefully directory too) as needing to exist, and let the system worry about making that happen as needed.

**Comment by twpayne** [comment]
OK, thank you for the feedback. This all makes sense. I'll target it for v2.
