### ISSUE TITLE
Add dot notation method for retrieving 1password login data

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#814]
This is a new issue to track @ubuntudroid's [request](https://github.com/twpayne/chezmoi/issues/474#issuecomment-660507543) in #474.

## Is your feature request related to a problem? Please describe.

Getting values out of 1password requires some template gymnastics, as demonstrated in @pvinis's [comment](https://github.com/twpayne/chezmoi/issues/474#issuecomment-586157328).

## Describe the solution you'd like

@ubuntudroid [writes](https://github.com/twpayne/chezmoi/issues/474#issuecomment-660507543):

> could we get support for fetching 1password login type items with the simple dot notation at some point as well? Most passwords are actually login items as they often need a username/ID which the password type does not have by default.

## Describe alternatives you've considered

Using the existing template gymnastics, but this is frustrating.

## Additional context

There is example 1password login data in [this comment](https://github.com/twpayne/chezmoi/issues/474#issuecomment-585731243).

**Comment by twpayne** [comment]
Proposal:

Add a `onepasswordDetailFields` function that parses the `details` value of the output of `onepassword "theuuid"` and returns a value that can be dot-indexed by each field's designation.

Specifically, given this output:

```json
 "details": {
    "fields": [
      {
        "designation": "password",
        "name": "password",
        "type": "P",
        "value": "suuuupersecret"
      },
      {
        "designation": "username",
        "name": "username",
        "type": "T",
        "value": ""
      }
    ]
  }
```

It would be used like this:

```
PASSWORD={{ (onepasswordDetailsFields "theuuid").password.value }}
```

Assumptions:
* Each field's `designation` is unique, the function will error if duplicate `designation`s are encountered.
* `.value` is required to access the value. `.type`, `.name` will also be available.

@ubuntudroid @pvinis Does this sound reasonable? What can be improved?

**Comment by pvinis** [comment]
Seems great!

**Comment by zb140** [comment]
Just to throw it out there: 1password-cli version 1.0.0 and newer has a `--fields` argument to `op item get` that controls which data is actually returned.  So, something like `op item get [uuid] --fields password` would return just the password as a plain string, while `op item get [uuid] --fields username,password` returns a JSON object like `{"username":"user", "password": "whatever"}`.  Adding support for the `--fields` argument could cut down on custom parsing logic, but at the expense of only working with 1password-cli > 1.0.0.
