### ISSUE TITLE
The sourceDir in chezmoi.toml doesn't seems to be working

### ISSUE THREAD

**Issue by felipecassiors** [twpayne/chezmoi#817]
![vRXXdvRSI1](https://user-images.githubusercontent.com/29582865/88449245-b091b780-ce1b-11ea-9ddc-2970d689a7c7.gif)

**Comment by twpayne** [comment]
What is happening here is:

You are adding the `sourceDir` variable *inside* the `[data]` section of the configuration file. Note that TOML does not care about indentation (unlike YAML). To fix this, put the `sourceDir` line *before* the `[data]` section, for example:

```toml
sourceDir = "/home/felipesantos/.dotfiles"

[data]
  email = "hi@gmail.com"
```

Please, also, when submitting issues:

1. Use the appropriate issue template as requested by the repo owner ([bug](https://github.com/twpayne/chezmoi/issues/new?assignees=&template=03_bug_report.md&title=) in this case) and fill in all the requested fields.
2. Post text steps to reproduce, not screenshots or animations. Screenshots and animations cannot be quoted or copied-and-pasted.

Thanks!

**Comment by felipecassiors** [comment]
> What is happening here is:
> 
> You are adding the `sourceDir` variable _inside_ the `[data]` section of the configuration file. Note that TOML does not care about indentation (unlike YAML). To fix this, put the `sourceDir` line _before_ the `[data]` section, for example:
> 
> ```toml
> sourceDir = "/home/felipesantos/.dotfiles"
> 
> [data]
>   email = "hi@gmail.com"
> ```

There is no mention that the configuration keys must be at the top level of the configuration file (despite now I understand it). This should be in the documentation, don't you think? In this section, I believe: https://www.chezmoi.io/docs/reference/#configuration-file

> Please, also, when submitting issues:
> 
> 1. Use the appropriate issue template as requested by the repo owner ([bug](https://github.com/twpayne/chezmoi/issues/new?assignees=&template=03_bug_report.md&title=) in this case) and fill in all the requested fields.
> 2. Post text steps to reproduce, not screenshots or animations. Screenshots and animations cannot be quoted or copied-and-pasted.
> 
> Thanks!

Sure, sorry about that!

**Comment by m-rey** [comment]
> However, there is no mention that the configuration keys must be at the top level of the configuration file (despite now I understand it). This should be in the documentation, don't you think?

I disagree.

The documentation clearly states which configuration file formats are supported and links to them if further information about its structure or syntax is needed.  
[TOML](https://github.com/toml-lang/toml), the one you currently use, has different sections and, as stated, doesn't care about indentation. Other config file formats do care about indentation and have a different syntax. Adding a note about it, only for TOML, to the reference guide wouldn't make much sense, in my opinion.

If you really really want to have a note somewhere about it (because others may also get the TOML syntax wrong), I'd add a small reminder to the FAQ or something like that.

**Comment by felipecassiors** [comment]
Actually my point was not only about TOML, but to be clear about where these variables should be set: top level.

Exactly what you did in your PR, it sounds awesome!

**Comment by m-rey** [comment]
Ah, I've misunderstood the issue then. Thanks für clarifying!

I agree, the #823 PR looks good! Thank you @twpayne!

**Comment by twpayne** [comment]
Thank you very much for both your contributions here @felipecassiors and @m-rey :)
