### ISSUE TITLE
Support GitHub Codespaces, Visual Studio Codespaces and VS Code Dev Containers

### ISSUE THREAD

**Issue by felipecassiors** [twpayne/chezmoi#818]
Would be good if `chezmoi` could _support_ how `dotfiles` are managed in these services, using its default settings. 

## What needs to be made

There is no much work to do on `chezmoi` itself (I believe) and the outcome would be to probably have everything on the documentation.

### Write a `bootstrap.sh` script 

This script must be able to install `chezmoi` and reuse the current folder for `chezmoi init`. I have one [here](https://github.com/felipecassiors/dotfiles/blob/master/install) (with a bunch of unnecessary fashion).

### Support `~/dotfiles` as permanent source dir

This can be actually anywhere since the user can set it in the settings of these services. I believe this can be made with:

```
# bootstrap.sh
script_dir="$(cd "${BASH_SOURCE[0]%/*}" && pwd)"
chezmoi init --apply --source $script_dir
```

And have the following in the `.chezmoi.toml.tmpl`

```toml
# This key must be at the top level of the configuration file,
# for TOML, it means before any [field] such as [data]
sourceDir = "{{ .chezmoi.sourceDir }}"
```
This will pick up whatever source dir was passed as a parameter in the `chezmoi init`.

### Document everything, and:

How about adding a flag to `chezmoi init` to create the `bootstrap.sh` and the snippet on `.chezmoi.toml.tmpl`?

How about creating a [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) with everything already set, to make it easy for newcomers? They wouldn't even need to install `chezmoi` by themselves to get started.

## References

- Visual Studio Codespaces: https://docs.microsoft.com/pt-br/visualstudio/codespaces/reference/personalizing
- GitHub Codespaces: https://docs.github.com/en/github/developing-online-with-codespaces/personalizing-codespaces-for-your-account
- Visual Studio Code Remote Development - Containers: https://code.visualstudio.com/docs/remote/containers#_personalizing-with-dotfile-repositories

**Comment by twpayne** [comment]
This is a great suggestion, thanks.

I just got accepted to the Codespaces beta, #834 is a work in progress PR.

**Comment by felipecassiors** [comment]
@twpayne, any words about this?

> How about adding a flag to chezmoi init to create the bootstrap.sh and the snippet on .chezmoi.toml.tmpl?
> 
> How about creating a template repository with everything already set, to make it easy for newcomers? They wouldn't even need to install chezmoi by themselves to get started.

**Comment by twpayne** [comment]
> How about adding a flag to chezmoi init to create the bootstrap.sh and the snippet on .chezmoi.toml.tmpl?

At the moment, I'd like to hold off implementing this for the following reasons:

* chezmoi is just starting to be used for Codespaces and I don't think it's had quite enough time for the definitive best practices to be established, so I don't want to hardcode anything into chezmoi related to it yet.
* `bootstrap.sh` does not contain any user-specific code, so it does not need to be generated. Right now, I think it's OK to copy it from a how-to document.

> How about creating a template repository with everything already set, to make it easy for newcomers? They wouldn't even need to install chezmoi by themselves to get started.

This is a great idea, I'll create an issue so that it's not forgotten.
