### ISSUE TITLE
Install script hangs when installing to a custom folder multiple times

### ISSUE THREAD

**Issue by felipecassiors** [twpayne/chezmoi#819]
Try this, multiple times:

```bash
curl -sfL https://git.io/chezmoi | sh -s -- -b /tmp/bin
```

![e5WiFVRfYA](https://user-images.githubusercontent.com/29582865/88502375-a3ec9b00-cfa4-11ea-971c-94098d707c70.gif)

However, it doesn't seem to be failing when we don't specify a custom bindir, and it can be a workaround:

```bash
bindir=/tmp/bin
mkdir -p $bindir
cd $(dirname $bin_dir)
curl -sfL https://git.io/chezmoi | sh
cd - >/dev/null
```

Probably the issue comes from the [godownloader](https://github.com/goreleaser/godownloader), but perhaps it's just outdated.

**Comment by twpayne** [comment]
I'm unable to duplicate this on Ubuntu 20.04 or macOS 10.15.6. On both machines, the install script completes in a timely fashion.

What operating system do you observe this behavior on?

**Comment by m-rey** [comment]
Can't duplicate this on openSUSE Tumbleweed with the 5.6.0-rc4-1.g8a04afc-default kernel.

**Comment by felipecassiors** [comment]
I tested on Ubuntu 20.04 on WSL, I'll test in more environments.

**Comment by felipecassiors** [comment]
That's true, I can't reproduce this in an Ubuntu 20.04 machine. I'll investigate further to check if the issue comes only from WSL.

**Comment by twpayne** [comment]
My suspicion (just a hunch, no hard data) is that Windows is somehow locking the installed binary while it scans it with Windows Defender, and this prevents the second run of the installer from writing the new binary.

Does the problem occur on Ubuntu 20.04 on WSL if you wait a few seconds between re-runs of the install script?

**Comment by felipecassiors** [comment]
> Does the problem occur on Ubuntu 20.04 on WSL if you wait a few seconds between re-runs of the install script?

No, I tried it today. The file was there since yesterday. No luck. I'll make more tests.

**Comment by felipecassiors** [comment]
The same thing happens in a Docker container:
```
docker run -it --rm buildpack-deps:focal-curl bash
curl -sfL https://git.io/chezmoi | sh -s -- -b /tmp/bin
```

**Comment by felipecassiors** [comment]
Ok, nevermind.

It seems to be an issue with my connection. I connected to NordVPN and the error was gone. (When I used Ubuntu earlier for testing, I was connected to a VPN).
