### ISSUE TITLE
chezmoi.io: search not working

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#820]
![VNsjv6Gt3r](https://user-images.githubusercontent.com/29582865/88503825-342cdf00-cfa9-11ea-8cea-c4e3e6b3f42a.gif)
(I'm pressing `Enter` after typing)

I have no clue, but it might be related to https://github.com/alex-shpak/hugo-book/issues/193.

**Comment by twpayne** [comment]
Thanks for reporting this. It does look the issue you found is the underlying cause. I'll switch to a different theme with a working search in v2.

**Comment by felipecassiors** [comment]
I think that [Gitbook](Gitbook) is one of the best alternatives or at least one of the most beautiful and functional ones. And it's [free for open-source](https://www.gitbook.com/pricing) projects. 

The good thing is that you can keep your `.md`s on GitHub in a readable way, and this is very important for my personal choice.

**Comment by felipecassiors** [comment]
Nevermind, I believe the best documentation site overall today is [`docusaurus`](https://v2.docusaurus.io/).

**Comment by twpayne** [comment]
At some point the Hugo Book theme search got fixes, so this is now working.

I may still consider switching to gitbook.

**Comment by felipecrs** [comment]
Awesome.

BTW, I have been working with Docusaurus in the past weeks, and it's very cool. The builtin theme is quite beautiful, and it has tons of features. It works well having a subfolder for the website source code and another as the docs folder with the md files as you have today.
