### ISSUE TITLE
Add info how to add folders to quick-start

### ISSUE THREAD

**Issue by ASDFGamer** [twpayne/chezmoi#825]
## Is your feature request related to a problem? Please describe.
I just started using Chezmoi and used the quick-start guide to learn how to use it.
There is a example where the bash config is added via the add command. I thought that the add command could also be used to add whole folders without other arguments. This lead to confusion as i looked into the generated repo.

## Describe the solution you'd like

I would propose to add a short statement into the quick-start, that whole folders can be added via the -r argument.

## Describe alternatives you've considered

There could also be a example for that, but I think that is too much for the quick-start.

## Additional context
I don't have any additional context

**Comment by twpayne** [comment]
Yes, this would be a great addition. Would you like to submit a PR? Alternatively, I can add this on your behalf.

**Comment by ASDFGamer** [comment]
I created a pull request
