### ISSUE TITLE
Add pre_ and post_ attributes for scripts

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#831]
## Is your feature request related to a problem? Please describe.

Currently chezmoi applies targets in alphabetical order of target name (this is implemented, but not documented). However, in practice this is annoying because all dotfiles (starting with a `.`, character 46) are applied before all scripts starting with a `0` (character 48). This is doubly confusing because the chezmoi documentation uses `run_once_00` scripts in its examples.

## Describe the solution you'd like

I would like clear `pre_` and `post_` attributes for scripts that ensure that they are applied either before or after the main dotfiles are applied.

## Describe alternatives you've considered

Scripts can be renamed to something that sorts before `.foo`, e.g. `run_once_.00_bootstrap.sh` but this is very ugly.

## Additional context

See #830.

@Kasuko does this sound reasonable to you?

**Comment by Kasuko** [comment]
I might be biased because I just made this mistake :P but I found myself instinctively ignoring the attributes when mentally sorting the files, so this would make more sense to me!

**Comment by twpayne** [comment]
I've added an initial implementation in #654. The attributes apply to scripts only and are called `first_` and `last_`, so you end up with something like `run_first_once_setup_chezmoi.sh`. All `run_first_` scripts are run before files, directories, and symlinks are updated. All `run_last_` scripts are run after files etc. are updated.
