### ISSUE TITLE
.github with README.md

### ISSUE THREAD

**Issue by hoaxdream** [twpayne/chezmoi#835]
## What exactly are you trying to do?
Before i use chezmoi i used git bare and i have a file called ~/.github which contains all my README.md license and all other
md files,. but when i add with chezmoi add ~/.github it makes dot_github so when i pushed them to github, github can't recognized my README.md, is there a way to do this in chezmoi? i just started using this today. any help is appreciated. thank you.

**Comment by twpayne** [comment]
Yes, you can do this. You need to store your `.github/` directory in the source state directly, not add with `chezmoi add`. Try these commands:

```
chezmoi cd
cp -r ~/.github .
git add .github
git commit -m "Add .github directory"
```

Note that chezmoi ignores anything that begins with a `.` in the source state, so it will ignore the `.github` directory.

Please let me know if this works for you.

**Comment by hoaxdream** [comment]
yea it works, thank you..  if understand this correctly on how this will work. if i want to make some changes of my files in ~/.github and to be sync in my github repository, i need to edit them directly in ~/.local/share/chezmoi/ ?

**Comment by twpayne** [comment]
Ah, maybe I misunderstood.

If you want your `$HOME/.github` directory to be managed by chezmoi and created on every machine, then you should use `chezmoi add -r ~/.github` as you did in your initial post. This will appear as `dot_github` directory in your dotfiles repo.

If you want to `.github` to be present in your dotfiles repo, but *not* copied into your home directory then use the commands that I gave in the second post.

In both cases the directory will be managed by git.

There might be a third possibility. Do you want `$HOME/.github` to be managed by chezmoi *and* a `.github` directory in your dotfiles repo so that GitHub shows its contents?

**Comment by Legion2** [comment]
@hoaxdream why do you have all your Readme, etc. files in the `.github` directory?

**Comment by hoaxdream** [comment]
> There might be a third possibility. Do you want `$HOME/.github` to be managed by chezmoi _and_ a `.github` directory in your dotfiles repo so that GitHub shows its contents?

yes this is what i want, is it possible sir?

**Comment by twpayne** [comment]
Currently the only way to have *both* `$HOME/.github` managed by chezmoi and a `.github` directory in your dotfiles repo is to duplicate the directories, i.e. have both `dot_github` and `.github` in your dotfiles repo containing the same files.

However, I have to ask why do you want to do this? Specifically, why do you need a `.github` directory in your home directory?

**Comment by hoaxdream** [comment]
i see, i used to have `.github` when i was using git bare to manage dotfiles to have a clean `$HOME` directory with those README.md and LICENSE showing in my `$HOME` directory but also shows my README.md content in my github repositroy.

i also used a script  before to hide those but i prefer putting them in `.github` and not to worry about them anymore.
```
#!/bin/sh
d() { git --git-dir="$HOME/.config/dots-git/" --work-tree="$HOME" "$@"; }

case $1 in
up) d pull && d update-index --assume-unchanged ~/LICENSE ~/README.md && rm -rf ~/LICENSE ~/README.md ;;
push) d push "${2:--u}" "${3:-origin}" master ;;
res) d checkout HEAD -- "$2" ;;
*) d "$@" ;;
esac
```
thank you sir for your time. i really like chezmoi, hopefully this could be implemented in near future :)

**Comment by twpayne** [comment]
A few things that might be useful:

* You can tell chezmoi to ignore files like `README.md`, [read this](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md#chezmoiignore).
* `chezmoi git` runs git in the source directory.
