### ISSUE TITLE
Changelog is not complete

### ISSUE THREAD

**Issue by Legion2** [twpayne/chezmoi#849]
## Describe the bug

The changelog of the last few releases in GitHub only shows one commit.

## To reproduce

Look at the latest (v1.8.4) release https://github.com/twpayne/chezmoi/releases/tag/v1.8.4
There is only one commit in the changelog, but there are actually 69 commits between v1.8.3 and v1.8.4 as you can see here https://github.com/twpayne/chezmoi/compare/v1.8.3...v1.8.4

## Expected behavior

All changes are listed in the changelog, or at least a summary of the important changes

**Comment by twpayne** [comment]
I finally found out what was causing the changelogs to be incomplete (I think). chezmoi's release GitHub Action was doing a shallow (`--depth=1`) clone of the repo, meaning that it was missing the history. This is specifically called out in the [goreleaser docs](https://goreleaser.com/ci/actions/#workflow). Oopsie.
