### ISSUE TITLE
Variable .chezmoi.fullHostname not working as expected

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#853]
## Describe the bug

The variable `.chezmoi.fullHostname` is not working as expected, for me, it's returning the same of `.chezmoi.hostname`

## To reproduce

```sh-session
$ hostname --fqdn
ICCSO-035976-NB.local.inatel.br
$ echo '{{ .chezmoi.fullHostname }}' | chezmoi execute-template
ICCSO-035976-NB
```

Screenshot:
![image](https://user-images.githubusercontent.com/29582865/90442108-7cbf5000-e0b0-11ea-8c4a-3cd682c7877d.png)

## Expected behavior

It was supposed to contain the fully qualified domain name of the hostname, not just the hostname.

## Output of command with `--verbose`

```sh-session
$ echo '{{ .chezmoi.fullHostname }}' | chezmoi execute-template --verbose
ICCSO-035976-NB
```

## Output of `chezmoi doctor`

```sh-session
$ chezmoi doctor
     ok: version 1.8.4, commit 99ef18b52acee575fa961a038709e202349c283d, built at 2020-08-12T11:50:45Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/felipesantos/.dotfiles (source directory, perm 700)
     ok: /home/felipesantos (destination directory, perm 755)
     ok: /home/felipesantos/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/zsh (shell)
     ok: /home/felipesantos/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/bin/code (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.25.1)
     ok: /usr/bin/gpg (GnuPG, version 2.2.19)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

## Additional context

I'm running Ubuntu 20.04 on WSL2.

**Comment by twpayne** [comment]
chezmoi's `fullHostname` value is taken from the Go standard library's [`os.Hostname()`](https://pkg.go.dev/os?tab=doc#Hostname) function. It seems that this is not returning the full hostname in some cases. Some digging reveals that [Kubernetes prefers executing `hostname`](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/node/node.go#L49-L67). I'll port the same to chezmoi.

**Comment by twpayne** [comment]
Oops, what I wrote is not correct. Kubernetes has used `hostname` in the past, see https://github.com/mesos/mesos-go/pull/218/files, but doesn't now.

I'll have access to a Windows machine in a few days and will install WSL2 on it to do some digging.

**Comment by felipecassiors** [comment]
Awesome!
