### ISSUE TITLE
Add `--no-scripts` and `--re-run-scripts` to `chezmoi apply`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#854]
I searched and I could not find anything about this.

## Describe the solution you'd like

To add `--no-scripts` and `--re-run-scripts` to `chezmoi apply`, which would respectively `apply` but not run scripts, and `apply` and re-run the scripts already marked as ran.

It would be also good if we could have those options available on `chezmoi init --apply` as well.

## Describe alternatives you've considered

There is no current way to prevent the scripts to execute I think. To make a script already marked as ran to run again I have to change its contents, so `chezmoi` will run it. (I'm talking about the scripts `run_once` and not just `run`.

**Comment by twpayne** [comment]
This is a great suggestion, thanks.

`--no-scripts` is implemented in the `v2` branch (#654) which adds an `--include` flag that allows you to specify what types of entry to apply. I hope to finish `v2` in the next few weeks.

There's currently no `--re-run-scripts` flag, but you can simulate this by deleting chezmoi's state which is by default stored in `~/.config/chezmoi/chezmoistate.boltdb` before running `chezmoi apply`.

Hope this helps in the short term.

**Comment by felipecassiors** [comment]
> There's currently no `--re-run-scripts` flag, but you can simulate this by deleting chezmoi's state which is by default stored in `~/.config/chezmoi/chezmoistate.boltdb` before running `chezmoi apply`.
> 
> Hope this helps in the short term.

It does, thank you so much!
