### ISSUE TITLE
Discussion: is `chezmoi init --clone=false` really needed?

### ISSUE THREAD

**Issue by felipecassiors** [twpayne/chezmoi#855]
This is not a bug report, feature request, or support request. 

So, `chezmoi` can surely detect if the `source` folder is already "`git initiated`", is there a need for including such an option?

It would help people like me who like to change the `.chezmoi.toml.tmpl` a lot and thus need to run `chezmoi init --clone=false` to apply the changes.

**Comment by twpayne** [comment]
> So, `chezmoi` can surely detect if the `source` folder is already "`git initiated`", is there a need for including such an option?

That's a great idea, thanks. I hadn't thought of that. I can't think of any downsides. I'll implement it now.
