### ISSUE TITLE
Add Codespaces dotfiles template repo

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#857]
## Is your feature request related to a problem? Please describe.

As suggested by @felipecassiors in #818:

> How about creating a [template repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) with everything already set, to make it easy for newcomers? They wouldn't even need to install `chezmoi` by themselves to get started.

## Describe the solution you'd like

Create a template repository as described above.

## Describe alternatives you've considered

Having documentation describing how to do achieve the same, but this is slower for users to start with.

## Additional context

None.

**Comment by felipecassiors** [comment]
It would be super cool if the template repository could be named just `dotfiles`, so the users forking (or creating from template) would not even need to rename it. But `twpayne/dotfiles` already points to your personal `dotfiles`, and `chezmoi` namespace on GitHub was already taken, I think that's not possible.

**Comment by twpayne** [comment]
888890b0fca01b913b32262c46a931003fc3c78c adds some documentation, which I think was the final thing needed to call this done. Thanks for your help!
