### ISSUE TITLE
Make source folder private automatically

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#859]
## The problem

In the first time when I run `chezmoi init`, it warns me `/home/felipesantos/.dotfiles: not private, but should be`.

## Solution

Can chezmoi automatically fix the folder permissions if needed? Is it a good idea?

## Alternatives

We can also do it by ourselves, such as adding a `chmod 700 ~/.dotfiles` before running `chezmoi init`, for example, in the `install.sh` snippet for the Codespaces.

**Comment by twpayne** [comment]
Thanks for raising this. This check was added before chezmoi had good secrets support, and I think it's no longer necessary as people should be using password managers or encryption to store their secrets, so the permissions on the source directory should not matter. I'll remove the check.
