### ISSUE TITLE
wish: chezmoi run

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#863]
## Why

Sometimes I just want to run some commands in the source folder, and `chezmoi cd && a command` does not work, so I have to

```sh-session
$ chezmoi cd
$ a command
$ exit
```

## Solution

A `chezmoi run` command, which will run whatever is passed after the first non-option argument, similar to  `docker run`, in the source folder. It can also be like `npm run`, where you must use `--` to set the arguments for the command to run and not for `npm` itself.

Then, I could run `chezmoi run a command` to run `a command` in my dotfiles repository.

EDIT:

I just figured out `chezmoi edit`, which opens my dotfiles in my editor.

**Comment by twpayne** [comment]
OK, I'll close this for now but we can re-open if we come up with a good use for it. It's very easy to implement.
