### ISSUE TITLE
Allow a file's output location to be customized

### ISSUE THREAD

**Issue by offbyone** [twpayne/chezmoi#875]
## Is your feature request related to a problem? Please describe.

I have a tool that sets its configuration location differently depending on the platform I'm on. On macOS it puts the configuration in `Library/Application Support/pypoetry/` and on Linux it puts it in `~/.config/pypoetry` using the `$XDG_CONFIG_HOME` environment variable. (this is documented in [pypoetry#1239](https://github.com/python-poetry/poetry/issues/1239)).

## Describe the solution you'd like

I can solve this with symlinks, _maybe_, as long as every tool that does this (and poetry is just one) follows symlinks when writing their config, which is not a guarantee. So, I want a way to manage a single file in chezmoi but have it written to a location that depends on the OS. I've got some tools that do the right thing when writing to a symlink, and others that do not.

**Comment by twpayne** [comment]
#164 has some suggestions for how to handle this situation. I should add this to the how-to documentation.

**Comment by twpayne** [comment]
I've added an FAQ entry for this. Please re-open if needed.

**Comment by offbyone** [comment]
That solves it for me nicely, thanks! I probably could have worked that out eventually, but it is a lot of moving parts :)
