### ISSUE TITLE
Compression of Docs Into Single Document

### ISSUE THREAD

**Issue by p0da** [twpayne/chezmoi#884]
It currently appears that chezmoi has its docs spread out across its Reference, Howto, and FAQ pages along with a few github issues. Would you consider condensing all the information in these sources into a single definitive document for easier reference?

Btw thanks for making chezmoi, it works quite well.

**Comment by twpayne** [comment]
Thanks for the suggestion and the kind words.

chezmoi's documentation structure is based on the popular structure described in https://documentation.divio.com/introduction/. That said, it would be nice to have a single document as you describe.

Please have a read through the comments in #696.

**Comment by Rayqan** [comment]
Perhaps a compromise could be reached by using the current documentation layout while also ensuring that all details in alternative documents are also in the reference manual/newly created man page? I also see that https://github.com/twpayne/chezmoi/issues/792 discusses consolidating a portion of the docs.

**Comment by twpayne** [comment]
With #1826, chezmoi has moved to [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) to generate its website. Contributions to generate a single doc for all projects using MkDocs would help many.
