### ISSUE TITLE
Add pre-defined templates for config files of popular applications

### ISSUE THREAD

**Issue by MurzNN** [twpayne/chezmoi#885]
At now, when we want to add configuration of some new app to chezmoi, we must manually search needed config files and add it to chezmoi. I have found similar project "mackup", that have cool feature: pre-defined ready-to-use templates for popular applications, here is list of them: https://github.com/lra/mackup#supported-applications

Will be good to have same feature in chezmoi too, for simply type something like `chezmoi add-app blender`, instead of search for each configuration file/folder and add it manually to chezmoi.

What do you think about this idea?

**Comment by twpayne** [comment]
Thank you, this is a really interesting idea. A couple of observations:

1. mackup has a really nice [configuration directory containing language-neutral configuration files](https://github.com/lra/mackup/tree/master/mackup/applications). It would be easy to import this data into chezmoi.
2. mackup is [licensed under the GPL-3](https://github.com/lra/mackup/blob/master/LICENSE) whereas chezmoi [has a MIT license](https://github.com/twpayne/chezmoi/blob/master/LICENSE). It's not clear if we can combine the two. I'm not a lawyer but an obvious question is whether mackup's configuration files are part of its source code.
3. We need to think carefully about what should happen when only some of the configuration files associated with an application are present when you run `chezmoi add-app`. Should the absent configuration files be forced to be empty, be ignored, or something else?

Thank you again for proposing this: this is potentially a very nice improvment.

**Comment by twpayne** [comment]
A possible solution to point 2 is for chezmoi to read mackup's configuration files from an existing mackup installation (e.g. if you have already installed mackup with `brew install mackup`). This means that the two tools are distributed independently and should avoid licensing problems. The downside is that you have to install mackup before you can use the `add-app` command.

**Comment by MurzNN** [comment]
About point 2 - maybe you can talk directly with author of mackup about "joining forces" for manage shared independent catalog of `.cfg` files with app config files info, using current file format, on separate MIT license, that will use `mackup` and `chezmoi` together (and maybe other apps in future too)?

> 3. We need to think carefully about what should happen when only some of the configuration files associated with an application are present when you run `chezmoi add-app`. Should the absent configuration files be forced to be empty, be ignored, or something else?

About missing files - I think, that good solution will be store them in `chezmoi` as some "waiting for source" mode, so check file availability on each run, and if file is absent - nothing happens, if appeared - add it to repository and start to manage, like other files.

**Comment by twpayne** [comment]
We're waiting for a response about use of the mackup data in https://github.com/lra/mackup/issues/1733.

**Comment by twpayne** [comment]
So, I gave up waiting for a response from the Mackup folk on this and implemented `chezmoi mackup add` in #1325. Please have a look and report what you think.

**Comment by twpayne** [comment]
@MurzNN do you still need this feature? It's implemented in chezmoi, but I propose to remove it unless it's actually used.

**Comment by twpayne** [comment]
It seems that nobody else needs or wants the feature. As the command was never documented, #1458 removes it completely.

**Comment by twpayne** [comment]
Please 👍 this message if you want this feature.

**Comment by benbender** [comment]
@twpayne thx for your efforts – a complete solution of some sort would be great and a *very* distinctive feature for chezmoi 👍

**Comment by eugenesvk** [comment]
Thank you very much for adding this! Though I've got an error trying to use it
```
chezmoi mackup add -n -v AltTab
chezmoi: "Python 3.12.0b4\n": cannot determine Python version
```

**Comment by twpayne** [comment]
Thanks for testing!

What is the output of

```console
$ ls ls `brew --prefix`/Cellar/mackup/`mackup --version | awk '{print $2}'`/libexec/lib
```

on your system?

**Comment by eugenesvk** [comment]
Thanks for your help (that `\n` threw me off, thought it was some parsing issue) ! Mackup's version is 3.11, and after I've changed the shell's version to 3.11, it worked! 🎉

Though is there any way to tell chezmoi explicitly which python to use so that it doesn't depend on the shell's environment, but always uses brew's python (which would always match mackup's, I guess)?. Another alternative would be to install mackup with pip, though brew's path is a tad bit more convenient

**Comment by eugenesvk** [comment]
Thank for for a prompt update, can confirm that it's adding mackup's config even with a different shell python version!
One last missing piece is supporting user app config files (for overriding central database or adding an app that's not yet in the central database) located in the `~/.mackup` folder

**Comment by eugenesvk** [comment]
Thanks, cusom user configs also seem to work fine now!
