### ISSUE TITLE
Suggestion: name of symlinked content directory

### ISSUE THREAD

**Issue by kcthrn** [twpayne/chezmoi#886]
If chezmoi gains the ability to completely automate symlink handling, I suggest that the top-level directory for **symlinked content** in the Source directory be called _symlinked_. I think that name properly describes its purpose.

Perhaps this _symlinked_ directory could be made a convention when covering symlinks in the documentation.

**UPDATE:** Added summary

---

<details><summary>Summary</summary>

# Summary

chezmoi will support two methods of symlinking.

1. Manual (no different from how chezmoi does it now)

2. Automatic:

   - Makes [symlink mode] obsolete
   
     > By default, chezmoi will create regular files and directories. Setting mode = "symlink" will make chezmoi behave more like a dotfile manager that uses symlinks by default, i.e. chezmoi apply will make dotfiles symlinks to files in the source directory if the target is a regular file and is not encrypted, executable, private, or a template.
   - There'll be a special directory called _chezmoilinked_ in chezmoi's source directory.
   - _chezmoilinked_ mimics its parent's directory structure
   - On `chezmoi apply`, chezmoi will handle files in _chezmoilinked_ as if [symlink mode] is enabled.
   - `symlink_*` files within `chezmoilinked` ignored in addition to those in [symlink mode],
   
     > encrypted, executable, private, or a template

     **TODO: Except for `template_*`, not sure about ignoring these other attributes**
   - chezmoi can add files to be linked to; e.g:
     ```
     $ chezmoi link "$HOME/.config/app/config.json"
     ```
     This creates `chezmoilinked/private_dot_config/app/config.json` in chezmoi's source directory.
     
     Also:
     ```
     $ chezmoi link --target "$HOME/.config/app/config.json" ./backups/configs/app/config.json

     ```
     `--target FILE` is a path to a file (does not have to exist) in the target directory, that chezmoi will place as a symlink on the next `chezmoi apply`. This creates `chezmoilinked/private_dot_config/app/config.json` in chezmoi's source directory, with the contents of `./backups/configs/app/config.json`.

     
Conflicts can occur if a file in the target directory would be created though multiple ways.

For example, on `chezmoi apply`, a source directory such as,
```
foo.txt
symlink_foo.txt  <-- "/media/docs/foobar.txt"
symlink_foo.txt.tmpl  <-- "{{ .chezmoi.sourceDir }}/my_sym_src/bar.txt"
chezmoilinked/foo.txt
my_sym_src/bar.txt
```
...would produce the target, `$HOME/foo.txt`.

How chezmoi handles conflicts, is that when attempting `chezmoi apply`, chezmoi will abort and product an error message with details of the conflicting files.

[symlink mode]: <https://www.chezmoi.io/docs/reference/#symlink-mode>

</details>

**Comment by twpayne** [comment]
Thanks for the suggestion. Could you give more details on how a `symlinked` directory would work?

**Comment by kcthrn** [comment]
In [Handle configuration files which are externally modified][1], instead of what is done here:

> Copy the configuration file to your source directory:
>
> `cp ~/.config/Code/User/settings.json $(chezmoi source-path)`

I think, _by convention_, the config file (settings.json) should be placed in `"$(chezmoi source-path)/symlinked/Code/User"`.

I realized later that the `symlinked` directory could be a _special directory_, so instead of _symlinked_ (and to avoid name conflicts and have it ignored by chezmoi) it could be _.chezmoisymlinked_ or _.chezmoilinked_. So settings.json would be placed in `"$(chezmoi source-path)/.chezmoilinked/Code/User"`

Notice that the _.config_ directory was dropped. I think it is unnecessary since the config files are already grouped in directories named after the program they belong to.

[1]:  https://www.chezmoi.io/docs/how-to/#handle-configuration-files-which-are-externally-modified

**Comment by eugenesvk** [comment]
Interesting idea, that's almost exactly what I'm using — `~/.local/share/chezmoi/sym_src` — to place all files that are symlinked (and adding this folder to `.chezmoiignore`) — this allows me to have a proper structure of all the files vs. dumping them all into `$(chezmoi source-path)` and ignoring them one by one.
One thing I think wouldn't be that great, though, is having this folder hidden (`. chezmoilinked`) since I think you might need to access about as often as the `private_dot_config` folder

Btw, in your proposal this special folder would then allow chezmoi to drop the `~/.local/share/chezmoi/app/symlink_config.json` files that  only have one line like `{{ .chezmoi.sourceDir }}/sym_src/app/config.json`?
Or would those still remain, but just point to this one centralized location?

**Comment by kcthrn** [comment]
@eugenesvk 

> One thing I think wouldn't be that great, though, is having this folder hidden (`. chezmoilinked`) since I think you might need to access about as often as the `private_dot_config` folder

I agree. I was following the naming convention in the docs. IMHO, special files like `.chezmoi...` as described in [Special files and directories](https://www.chezmoi.io/docs/reference/#special-files-and-directories) would be better off as not hidden (prefixed with "."). It's a little annoying to have to remember to do `ls -la` to see those files in chezmoi's source dir.

> Btw, in your proposal this special folder would then allow chezmoi to drop the `~/.local/share/chezmoi/app/symlink_config.json` files that only have one line like `{{ .chezmoi.sourceDir }}/sym_src/app/config.json`?
> Or would those still remain, but just point to this one centralized location?

 `symlink_config.json` should be `symlink_config.json.tmpl`. Note that chezmoi will create a symbolic link, `$HOME/app/config.json`, that points to the source file.

Special files like those would remain since the lines like `{{ .chezmoi.sourceDir }}/sym_src/app/config.json` are how chezmoi knows
 how to link the symlink to it's source. The current process of manually creating symlinks is painful, but if it gets automated then we wouldn't need to give much attention to special details like these.

**Comment by kcthrn** [comment]
@eugenesvk I think once it gets automated, we'll only need manual intervention if we want to take advantage of `symlink_*.tmpl` files being templates, as described by the chezmoi's author in paragraph 2 here: <https://github.com/twpayne/chezmoi/issues/980#issuecomment-753238079>

> ...and even more advanced features not found elsewhere like having the same symlink point to different targets on different machines by using templates.

**Comment by eugenesvk** [comment]
> `symlink_config.json` should be `symlink_config.json.tmpl`.

You're right, that was a typo.

> Special files like those would remain since the lines like `{{ .chezmoi.sourceDir }}/sym_src/app/config.json` are how chezmoi knows how to link the symlink to it's source.

The structure of the special folder would be the new way for chezmoi to know that — just like it uses the structure of `$(chezmoi source-path)` to understand where to put non-links in the target path — e.g. it would list the `sym_src` dir and then apply the same rules it applies to he regular folders

Though in this case my example file wouldn't be in
`{{ .chezmoi.sourceDir }}/sym_src/app/config.json` but in
`{{ .chezmoi.sourceDir }}/sym_src/private_dot_config/app/config.json` to indicate that the symlink to the source folder should be created in
`~/.config/app/config.json`

> The current process of manually creating symlinks is painful, but if it gets automated then we wouldn't need to give much attention to special details like these.

Well, they'd still show in the git and you'd need to remember to delete them when you delete your symlink, so it's an extra inconvenience... for no apparent benefit(?) since you already have all the info about how to deal with them in the dir structure


> we'll only need manual intervention if we want to take advantage of `symlink_*.tmpl` files being templates, as described by chezmoi's author in paragraph 2 here: [#980 (comment)](https://github.com/twpayne/chezmoi/issues/980#issuecomment-753238079)
> 
> > ...and even more advanced features not found elsewhere like having the same symlink point to different targets on different machines by using templates.

Yes, that's the benefit, but then in my proposal you'd only need these templates files when you do indeed want to have to use the template language to do something more advanced, and then these template files would override the default behavior of using the `chezmoilinked` folder structure to get the basic information about the target location for a symlink

**Comment by kcthrn** [comment]
@eugenesvk 

> The structure of the special folder would be the new way for chezmoi to know that — just like it uses the structure of `$(chezmoi source-path)` to understand where to put non-links in the target path — e.g. it would list the `sym_src` dir and then apply the same rules it applies to he regular folders
> 
> Though in this case my example file wouldn't be in
> `{{ .chezmoi.sourceDir }}/sym_src/app/config.json` but in
> `{{ .chezmoi.sourceDir }}/sym_src/private_dot_config/app/config.json` to indicate that the symlink to the source folder should be created in
> `~/.config/app/config.json`

I see. This is better, it's simpler.

> > The current process of manually creating symlinks is painful, but if it gets automated then we wouldn't need to give much attention to special details like these.
> 
> Well, they'd still show in the git and you'd need to remember to delete them when you delete your symlink, so it's an extra inconvenience... for no apparent benefit(?) since you already have all the info about how to deal with them in the dir structure

I agree. Additionally, removing symlinks could be also be automated (similar to something like the `chezmoi remove` and `chezmoi forget` commands).

> > we'll only need manual intervention if we want to take advantage of `symlink_*.tmpl` files being templates, as described by chezmoi's author in paragraph 2 here: [#980 (comment)](https://github.com/twpayne/chezmoi/issues/980#issuecomment-753238079)
> > > ...and even more advanced features not found elsewhere like having the same symlink point to different targets on different machines by using templates.
> 
> Yes, that's the benefit, but then in my proposal you'd only need these templates files when you do indeed want to have to use the template language to do something more advanced, and then these template files would override the default behavior of using the `chezmoilinked` folder structure to get the basic information about the target location for a symlink

So in it's final form, how chezmoi handles symlinks could be like this?

1. Automated symlinking with your proposal
2. Manual symlinking as how chezmoi handles symlinks currently

I think it could work well. It's easy to understand.

The only issue I see is the possiblity of conflicts between the two methods. Pehaps to counter that one method should have precedence over the other when applying, with a warning message put out by chezmoi?

For example, with a source dir like:
```
.../chezmoi/chezmoilinked/private_dot_config/app/config.json
.../chezmoi/private_dot_config/app/symlink_config.json.tmpl <-- "{{ .chezmoi.sourceDir }}/my_linked_src/foo.json"
.../chezmoi/my_linked_src/foo.json
```

And another issue, having a `symlink_*.tmpl` file inside the `chezmoilinked` dir.

**Comment by eugenesvk** [comment]
> An issue I see is the possiblity of conflicts between the two methods. Pehaps to counter that one method should have precedence over the other when applying, with a warning message put out by chezmoi?

Good idea, maybe let the manual way always win (but as long as a warning is there, don't really have a preference)?

> Another issue: Having a `symlink_*.tmpl` file inside the `chezmoilinked` dir.

Use these templates to create `*` files with different content, e.g. the result of
`../chezmoilinked/private_dot_config/app/symlink_config.json.tmpl` would be
`../chezmoilinked/private_dot_config/app/config.json` (with the appropriate content, e.g. depending on the OS), which in turn would be a regular file that will be linked to in the `~/.config/app/config.json` symlink

> And another: Attempting to automatically remove manual simlinks (Should be disallowed, user should just `rm` the target simlink, then delete the symlinked sources in chezmoi's source directory.

Hm, I wouldn't mind automatic cleanup if the template creating this symlink gets removed, but that might be a bit complicated to track, so erring on the side of "manual deletion after manual creation" is also fine

**Comment by kcthrn** [comment]
@eugenesvk 

> P.S. Might be worth including the summary of the design details from this conversation into your top issue description so that whenever twpayne gets around to implementing this it'd be easier for him to understand what is being proposed?

I placed a summary in the opening comment taking into our ideas so far. There's copy below if we need to refer to this version later.

Let me know if you'd like to see any changes to the summary.

<details><summary>Copy of summary</summary>

# Summary

chezmoi will support two methods of symlinking.

1. Manual (no different from how chezmoi does it now)

2. Automatic:

   - Make's [symlink mode] obsolete
   
     > By default, chezmoi will create regular files and directories. Setting mode = "symlink" will make chezmoi behave more like a dotfile manager that uses symlinks by default, i.e. chezmoi apply will make dotfiles symlinks to files in the source directory if the target is a regular file and is not encrypted, executable, private, or a template.
   - There'll be a special directory called _chezmoilinked_ in chezmoi's source directory.
   - _chezmoilinked_ mimics its parent's directory structure
   - On `chezmoi apply`, chezmoi will handle files in _chezmoilinked_ as if [symlink mode] is enabled.
   - `symlink_*` files within `chezmoilinked` ignored in addition to those in [symlink mode],
   
     > encrypted, executable, private, or a template

     **TODO: Except for `template_*`, sure about ignoring these other attributes**
   - chezmoi can add files to be linked to; e.g:
     ```
     $ chezmoi link "$HOME/.config/app/config.json"
     ```
     This creates `chezmoilinked/private_dot_config/app/config.json` in chezmoi's source directory.
     
     Also:
     ```
     $ chezmoi link --target "$HOME/.config/app/config.json" ./backups/configs/app/config.json

     ```
     `--target FILE` is a path to a file (does not have to exist) in the target directory, that chezmoi will place as a symlink on the next `chezmoi apply`. This creates `chezmoilinked/private_dot_config/app/config.json` in chezmoi's source directory, with the contents of `./backups/configs/app/config.json`.

     
Conflicts can occur if a file in the target directory would be created though multiple ways.

For example, on `chezmoi apply`, a source directory such as,
```
foo.txt
symlink_foo.txt  <-- "/media/docs/foobar.txt"
symlink_foo.txt.tmpl  <-- "{{ .chezmoi.sourceDir }}/my_sym_src/bar.txt"
chezmoilinked/foo.txt
my_sym_src/bar.txt
```
...would produce the target, `$HOME/foo.txt`.


How chezmoi handles conflicts, is that when attempting `chezmoi apply`, chezmoi will abort and product an error message with details of the conflicting files.

[symlink mode]: <https://www.chezmoi.io/docs/reference/#symlink-mode>

</details>

---

Concerning this:

> > Another issue: Having a `symlink_*.tmpl` file inside the `chezmoilinked` dir.
> 
> Use these templates to create `*` files with different content, e.g. the result of
> `../chezmoilinked/private_dot_config/app/symlink_config.json.tmpl` would be
> `../chezmoilinked/private_dot_config/app/config.json` (with the appropriate content, e.g. depending on the OS), which in turn would be a regular file that will be linked to in the `~/.config/app/config.json` symlink

It sounds good but wouldn't work because:

1. Changes made by `App` to `../chezmoilinked/private_dot_config/app/config.json` would not be reflected in `../chezmoilinked/private_dot_config/app/symlink_config.json.tmpl`.

2. How the contents of `symlink_*.tmpl` files are handled currently.

   - According to https://www.chezmoi.io/docs/reference/#template-execution

     > The result is treated differently depending on whether the target is a file or a symlink.

   - And https://www.chezmoi.io/docs/reference/#symbolic-links

     The contents of files with prefix `symlink_` must be the path to the symlink (i.e. to the file linked to in the source dir)

What I meant by taking advantage of `symlink_*.tmpl` in an earlier post is that the _path_ itself to the target file could vary, so for example, in source dir, within `../private_dot_config/app/symlink_config.json.tmpl`:
```
{{ if (eq .chezmoi.os "darwin") }}
  {{- .chezmoiDir.srcDir }}/my_sym_src/app/config.darwin.json }}
{{ else }}
  {{- .chezmoiDir.srcDir }}/my_sym_src/app/config.linux.json }}
{{ end }}
```

**Comment by twpayne** [comment]
Thanks for all the discussion here. I'm going to close this as WONTFIX because:
* The proposal breaks the 1:1 mapping between files in the source direction and files in the destination directory
* There are [many good reasons why you shouldn't use symlinks for your dotfiles](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#why-doesnt-chezmoi-use-symlinks-like-gnu-stow)
* chezmoi has a [symlink mode](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md#what-are-the-limitations-of-chezmois-symlink-mode) which you can use where necessary.
* For the remaining use cases where you do actually want a symlink, you can do this with a `symlink_`.

**Comment by twpayne** [comment]
#2018 is similar request.
