### ISSUE TITLE
Template homedir recognition fails

### ISSUE THREAD

**Issue by BeastyBlacksmith** [twpayne/chezmoi#89]
running `chezmoi add -T file`, where `file` contains `/Users/name/...` results in `/Users/{{ .chezmoi.username }}/...` instead of `{{ .chezmoi.homedir }}/...`.

**Comment by twpayne** [comment]
Thanks for the bug report!

I have a FIXME for this in the code: https://github.com/twpayne/chezmoi/blob/master/lib/chezmoi/autotemplate_test.go#L42-L52 but I haven't fixed it yet.

**Comment by twpayne** [comment]
Fixed in `v0.0.12`. Please tell me of any problems. Thanks again for the bug report :)

**Comment by BeastyBlacksmith** [comment]
You are welcome and thanks for fixing :)
