### ISSUE TITLE
Linux binaries aren't compatible with musl libc systems (dynamic glibc depency)

### ISSUE THREAD

**Issue by 0x5c** [twpayne/chezmoi#892]
## Describe the bug

The linux binaries are dynamically linked to glibc. This breaks compatibility with musl libc systems, like voidlinux musl and alpine (the package on `apk` is built correctly).

## To reproduce

1. Try to use a linux build on a musl libc system.

## Expected behavior

The binaries are *truly* statically linked an just work.

## Additional info

Following the build instruction on a musl system works just fine, but I expect those builds to not work on glibc systems.

**Comment by twpayne** [comment]
Thanks for reporting this! This should now be fixed. I'll tag a new release.

**Comment by 0x5c** [comment]
Thank you! It works well now
