### ISSUE TITLE
Symmetric encryption doesn't seem to work

### ISSUE THREAD

**Issue by flowchartsman** [twpayne/chezmoi#894]
## To reproduce

My chezmoi.toml is only the following:
```
[gpg]
    symmetric = true
```

```
$ chezmoi add  --encrypt ~/.local/share/system_bootstrap/Brewfile
You did not specify a user ID. (you may use "-r")

Current recipients:

Enter the user ID.  End with an empty line:
```

## Expected behavior

Prompted for password, file or directory is encrypted and moved into `~/.local/share/chezmoi`

## Output of command with `--verbose`

```
$ chezmoi add --verbose --encrypt ~/.local/share/system_bootstrap/Brewfile
You did not specify a user ID. (you may use "-r")

Current recipients:

Enter the user ID.  End with an empty line
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
warning: version dev
     ok: runtime.GOOS darwin, runtime.GOARCH amd64
     ok: /Users/<me>/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/<me> (destination directory, perm 755)
warning: /Users/<me>/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /usr/local/bin/nvim (editor)
     ok: /usr/local/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.28.0)
     ok: /usr/local/bin/gpg (GnuPG, version 2.2.23)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Ah, chezmoi's documentation is severely lacking here. It's been a while since I wrote the code, but chezmoi assumes that you already have gpg configured and doesn't help you do this. In short, you need to configure gpg so that `gpg --symmetric` works on its own, outside chezmoi, then you should be able to use the config that you posted.

Apologies for this, I'll keep this issue open until the documentation is improved.

**Comment by flowchartsman** [comment]
Actually, it seems the main issue was that  my config was in `~/.local/share/chezmoi` and not in `~/.config/chezmoi`.  And  had I  read the `chezmoi  doctor` output more  carefully,  I would have  realized that.  That said, it still doesn't do what I want, but I think that's probably because I'm pushing the boundaries a little.  My intent is to have an encrypted blob that's the contents of a directory that will  be extracted to `~/.local/share/system_bootstrap` where  I can keep things like license files. I think my best  bet is probably just creating that directory with a `private` subdirectory that's ignored and then just put a `gpgtar`ed blob with the contents of private in there that I unpack in a `run_once`

**Comment by flowchartsman** [comment]
if you're feeling generous, it would be nice to have the  ability to have an encrypted, opaque directory so that filenames inside it are not exposed. But that probably breaks the  relatively 1:1 filesystem mapping you have going on. :)

**Comment by twpayne** [comment]
> I think my best bet is probably just creating that directory with a `private` subdirectory that's ignored and then just put a `gpgtar`ed blob with the contents of private in there that I unpack in a `run_once`

That sounds like a good solution given chezmoi's functionality at the moment. At the same time, is it worth using a password manager to achieve this? chezmoi supports almost all of the popular ones, and tools like [pass](https://www.passwordstore.org/) are very close to what you'll end up implementing in the `run_once` script.

**Comment by twpayne** [comment]
> if you're feeling generous, it would be nice to have the ability to have an encrypted, opaque directory so that filenames inside it are not exposed. But that probably breaks the relatively 1:1 filesystem mapping you have going on. :)

This would likely be similar to #662 except with the added functionality that the tarball is encrypted, and I think it's a very good idea.

**Comment by flowchartsman** [comment]
Yeah, I'm currently re-doing my entire new-system bootstrapping process and part of that is moving password managers to one that doesn't strong-arm me into using their cloud storage.  Yet another task to push on the stack first, I suppose.

**Comment by twpayne** [comment]
If it's any help, chezmoi supports multiple password managers simultaneously (just use different template functions) and you can of course hook your own in with the generic secret functionality. This might help you do an incremental migration.

**Comment by twpayne** [comment]
chezmoi now includes [symmetric encryption tests](https://github.com/twpayne/chezmoi/blob/master/testdata/scripts/gpgencryption_symmetric.txt) so I'm reasonably sure that symmetric encryption is working correctly.

> > if you're feeling generous, it would be nice to have the ability to have an encrypted, opaque directory so that filenames inside it are not exposed. But that probably breaks the relatively 1:1 filesystem mapping you have going on. :)
> 
> This would likely be similar to #662 except with the added functionality that the tarball is encrypted, and I think it's a very good idea.

I've opened #1159 to track this.

Hopefully this issue is now resolved. Please re-open if needed.
