### ISSUE TITLE
Improve documentation on templates

### ISSUE THREAD

**Issue by fwSmit** [twpayne/chezmoi#897]
Recently I posted an issue here regarding templates in chezmoi (#888). The problem here is that the documentation on templates in chezmoi is kind of hard to find. There is the golang website, https://pkg.go.dev/text/template where most of the functionality is documented, but that's hard to read with few examples. There is also documentation scattered in the FAQ and the HOWTO, but it's not complete.
I'm just posting this issue to see if you think the documentation on templates needs to improve. If so, I will gladly make a pull request.

**Comment by twpayne** [comment]
Yes, please do! I also agree that the template documentation has a huge amount of room for improvement. #792 raises a similar issue.

Let me set up a bit of infrastructure for this...

**Comment by twpayne** [comment]
Closing this thanks to @fwSmit's work in #901 and #908.
