### ISSUE TITLE
A command to update all managed files in source state

### ISSUE THREAD

**Issue by pasha009** [twpayne/chezmoi#899]
## Problem

I almost always edit dotfiles in the destination directory. So to update these changes, I have to

1. Run `chezmoi diff` and find what files are changed
2. Manually add all files with `chezmoi add <file>`

More often i don't find the need to update dotfiles selectively.

## Solution

If we can add a single option which will do the above.
Which will first list all files that it would change in the destination with an index associated with each.
One can choose to add files here selectively if they want, by giving space separated indices as input.
But more importantly, if should have a default to update all files. 

## Alternatives

A script that takes all managed files from `chezmoi managed` and iterate over all with `chezmoi add <file>`.

`for file in $(chezmoi managed); chezmoi add $file;`

It would be slower for large dotfiles repos.

## Additional context

It is just a convenient feature to have and I think will come handy for those who have dotfiles in various nested directories.
I find it slow to type the entire path of the files to be updated.

**Comment by m-rey** [comment]
You also have to consider that some manages configs are templates, so simply using using `chezmoi add` isn't enough, as it would overwrite templates you have set up.

**Comment by pasha009** [comment]
> You also have to consider that some managed configs are templates, so simply using using `chezmoi add` isn't enough, as it would overwrite templates you have set up.

I don't use templates, currently. Can't we add this feature with a warning that this overwrites templates. This surely won't clash with existing use cases, if they don't use this.

I was previously using `homesick` but it required that all dotfiles be symlinked to the `homesick castle`. That had some problems.
In `chezmoi` one have the source and target independently as regular files. That was the selling point for me.

**Comment by twpayne** [comment]
Thank you for this very interesting idea. As @m-rey says, this gets complicated when the files in the source state are templates.

That said, I think this is a good idea, and v2 is bringing in a `chezmoi status` command (#424) that makes it possible to know when the contents of the dotfile on disk, the contents of the dotfile as defined by the source state, and the last contents written by chezmoi are out of sync. This should be helpful implementing a command like what you suggest here.

I think @pasha009's idea is good, and something like it will probably land in v2.1 or so.

> I find it slow to type the entire path of the files to be updated.

Your shell's tab completion can help here.

**Comment by twpayne** [comment]
Fixed with #1208.
