### ISSUE TITLE
packaging for void linux: what are the dependencies?

### ISSUE THREAD

**Issue by classabbyamp** [twpayne/chezmoi#900]
I'm working on packaging chezmoi for void linux. What dependencies are required to build chezmoi? `go` of course is required, but what about `git` or other programs? Which of them are only required for the build process (i.e. linking against headers) vs which are dependencies?

Thanks!

**Comment by twpayne** [comment]
That's great to hear, thank you!

There's a [section on packaging chezmoi in the contributing guide](https://github.com/twpayne/chezmoi/blob/master/docs/CONTRIBUTING.md#packaging). chezmoi itself has no dependencies beyond the standard Go toolchain. I think it should be possible to adapt something like the [golangci-lint template](https://github.com/void-linux/void-packages/blob/master/srcpkgs/golangci-lint/template) to chezmoi.

**Comment by classabbyamp** [comment]
Oh I didn't notice that, thanks. Is there any specific way `cgo` gets enabled?

**Comment by twpayne** [comment]
cgo is typically enabled by default, unless you're cross-compiling for a different OS/architecture to the one you're building on.
