### ISSUE TITLE
chezmoi cd stops without being usable on fish shell

### ISSUE THREAD

**Issue by simonszu** [twpayne/chezmoi#909]
## Describe the bug

```
 simonszu@naugol  ~  chezmoi cd
Job 1, 'chezmoi cd' has stopped
simonszu@naugol ~
```
So, effectively, the `chezmoi cd` subshell is not usable on fish shell, since the command returns immediately, stopped. 

## To reproduce

1. Install chezmoi
2. Do the Quickstart steps until `chezmoi cd`

## Expected behavior

According to the Quickstart, i would expect a subshell or chroot to happen, where i can do the git commands. 

## Output of command with `--verbose`

```
simonszu@naugol  ~  chezmoi cd --verbose  
Job 2, 'chezmoi cd --verbose' has stopped

```

## Output of `chezmoi doctor`

```
 simonszu@naugol  ~  chezmoi doctor
     ok: version 1.8.7, commit 3b285d96b45f4f832775b771d39c83e6442d3b4d, built at 2020-10-10T10:03:09Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/simonszu/.local/share/chezmoi (source directory, perm 700)
     ok: /home/simonszu (destination directory, perm 755)
warning: /home/simonszu/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.27.0)
     ok: /usr/bin/gpg (GnuPG, version 2.2.20)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)

```

## Additional context

Like described in the beginning, i am using the fish shell. This shell is not fully POSIX compliant, but is widely adopted. Apparently everything works fine when using bash (tested on another host). However, since `chezmoi <cmd> --verbose` and `chezmoi doctor` and the documentation do not output any hint that fish isn't compatible with chezmoi, i am a unable to solve this problem for myself and would at least need a confirmation that chezmoi needs a POSIX compliant shell.

**Comment by twpayne** [comment]
This is strange: chezmoi is detecting your shell as being `bash`, not `fish`. This is indicated in the `chezmoi doctor` output.

The `chezmoi cd` command only changes to the source directly and `exec`s your shell. It does not run any shell code itself.

What is the output of the following commands?
1. `echo $SHELL`
2. `SHELL=/usr/bin/fish chezmoi cd`

**Comment by simonszu** [comment]
Ah, this is a valuable hint. I think, back then when I started using fish, I followed a recommendation that one shouldnt start fish directly but set bash as the shell which will then start fish with a rc file, because some tools like ssh-copy-key expect the server to have a POSIX compliant shell as default.

OK, I have to think about it, because this is a bit inconvenient. Or do you have a recommendation by chance?

**Comment by twpayne** [comment]
You can override the shell in chezmoi's configuration file, e.g. put this in `~/.config/chezmoi/chezmoi.toml`:

```toml
[cd]
    command = "fish"
```

This is probably the quickest solution that does not require any other changes to your system.

w.r.t. to using `bash` to invoke `fish`, I'd ask the experts on fish about that. I use chezmoi to manage `~/.ssh/authorized_keys` so I don't need `ssh-copy-key`.

**Comment by simonszu** [comment]
OK, thanks. The override was the quickest solution. I'll check the other stuff later. I still need to decide whether i keep fish or go back to zsh ;)
