### ISSUE TITLE
Edit doesn't work for scripts

### ISSUE THREAD

**Issue by riccardomc** [twpayne/chezmoi#911]
## Describe the bug

Hello, I enjoy using chezmoi and I often have to edit a few script files. I would really like to be able to access them with my editor using  `chezmoi edit <script in chezmoi directory>`, but unfortunately it fails with:

```
 chezmoi: file does not exist
```

## To reproduce

1. add a script as specified in the [guide](https://www.chezmoi.io/docs/how-to/#use-scripts-to-perform-actions)
2. use `chezmoi edit <the added script>`

Notice that the script is shown by the auto completion

## Expected behavior

I would expect to be able to edit the script in `$EDITOR`

## Output of command with `--verbose`

```
➜ cm edit --verbose run_install_debian_packages.sh 
chezmoi: file does not exist
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

## Additional context

My dot folder is public and can be used to reproduce the issue:
https://github.com/riccardomc/rcs

**Comment by twpayne** [comment]
Thank you for your kind words and this suggestion 👍 

This is implemented in the `v2` branch, with the only caveat being that the filename doesn't include any of chezmoi's attributes. This means that in the example you give of `chezmoi edit run_install_debian_packages.sh` the actual command would be `chezmoi edit install_debian_packages.sh`.

Hopefully I'll get `v2` out soon 🙈
