### ISSUE TITLE
Chezmoi config template inside dot_config/chezmoi folder

### ISSUE THREAD

**Issue by adelin-b** [twpayne/chezmoi#915]
## Is your feature request related to a problem? Please describe.

Im forced to have a `.chezmoi.toml.tpml` in my home directory and in `$CHEZMOI_HOME`, I would rather avoid hidden files in my chezmoi directory and use the config folder

## Describe the solution you'd like

A way to have my `chezmoi.toml.tmpl` in the `$XDG_CONFIG/chezmoi/` folder using `chezmoi init` 

- lookup in `$CHEZMOI_HOME/dot_config/chezmoi/chezmoi.toml.tmpl` instead of just `$CHEZMOI_HOME/.chezmoi.toml.tpml` for the automatic `chezmoi init` config generation

- onafterinit script so I can mv ~/.chezmoi.toml ~/.config/chezmoi/` once generated
## Describe alternatives you've considered

Here is how I hack around it
With chezmoi config in `$XDG_CONFIG/chezmoi` 
```
rm ~/.config/chezmoi/chezmoi.toml 
chezmoi init
chezmoi apply
chezmoi apply
```

With `$CHEZMOI_HOME/.chezmoi.toml.tmpl`

```
chezmoi init
mv ~/.chezmoi.toml ~/.config/chezmoi/
```

**Comment by twpayne** [comment]
> Im forced to have a `.chezmoi.toml.tpml` in my home directory and in `$CHEZMOI_HOME`, I would rather avoid hidden files in my chezmoi directory and use the config folder

This sounds weird. chezmoi stores files in only two directories: `.local/share/chezmoi` for the source directory and `.config/chezmoi` for its configuration and state file. `chezmoi init` will create `.config/chezmoi/chezmoi.toml` from `.local/share/chezmoi/.chezmoi.toml.tmpl`. There is no such thing as `$CHEZMOI_HOME`.

What is the output of running the following commands on your system?

```
$ chezmoi doctor
$ find $HOME -name '*chezmoi*'
```

**Comment by adelin-b** [comment]
Okay the part about chezmoi file ending up in my home was a bad manipulation sorry, I added a dot_chezmoi and thats why

About this
> chezmoi init will create `.config/chezmoi/chezmoi.toml` from `.local/share/chezmoi/.chezmoi.toml.tmpl`
Here is what I think should also be possible and coherent
chezmoi init will create `.config/chezmoi/chezmoi.toml` from .local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl`

**Comment by twpayne** [comment]
> Here is what I think should also be possible and coherent
> chezmoi init will create `.config/chezmoi/chezmoi.toml` from `.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl`

This is not correct. `.config/chezmoi/chezmoi.toml` is created from `.local/share/.chezmoi.toml.tmpl`.

**Comment by twpayne** [comment]
Happy to discuss this further, but I'm confident that chezmoi is behaving correctly here.

**Comment by adelin-b** [comment]
> Happy to discuss this further, but I'm confident that chezmoi is behaving correctly here.

The issue is a feature request rather than something not behaving as wanted.

 It is strange in my opinion to have all the config files in `dot_config/` folders but not for chezmoi which require an hidden file template.

And the request was to make this statement true.
"chezmoi init will create `.config/chezmoi/chezmoi.toml` from `.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl`"

**Comment by twpayne** [comment]
chezmoi's config file is special. It's not like other dotfiles and cannot be treated in the same way.

Notably:
* chezmoi needs to read its config file before computing the contents of other dotfiles. This is why `chezmoi init --apply` creates chezmoi's config file and then re-executes chezmoi with the config file in place.
* The location of chezmoi's config file is configurable (e.g. you can override it with `-c` option), it's not always in `.config/chezmoi/chezmoi.toml`.
* If chezmoi were to manage its own config though `.local/share/chezmoi/dot_config/chezmoi/chezmoi.toml.tmpl`, then what should chezmoi do when it changes its own config file? Should it use the old config, the new config, or somehow switch and re-read the new config file halfway through?

This is why there is special-case handling for chezmoi's own config file.

**Comment by adelin-b** [comment]
Okay it is not worth the effort to make it happen, thank you
