### ISSUE TITLE
Add version check

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#92]
As `chezmoi` gathers features, source directories might depend on features that are not present in older versions of `chezmoi`. `chezmoi` should include a way to specify the minimum version of `chezmoi` for the source directory to apply correctly, and issue an error or warning when the current version of `chezmoi` is too old.

**Comment by kkirsche** [comment]
Do you envision this being granular, at a file or directory level or per feature / capability, or more coarse like a general this version or newer style check?

**Comment by twpayne** [comment]
I think a general "minimum chezmoi version" field in the source state somewhere (maybe in a `.chezmoiversion` file) is sufficient.
