### ISSUE TITLE
Calling gopass from any template prepends Password: to template output

### ISSUE THREAD

**Issue by tdemin** [twpayne/chezmoi#925]
Recent versions of gopass have changed the output format (invoking `gopass show secretname` now displays `Password: <secret>` instead of just `<secret>`, you have to call it as follows: `gopass show -o secretname`). As of chezmoi **v1.8.7**, chezmoi inserts the output of `gopass show` in place of `{{ gopass "secretname" }}`, which results in having `Password: <secret>` inserted into the config file. 

### Reproducing

1. `gopass insert something`
2. Add `{{ gopass "something" }}` into an existing template.
3. Enjoy `Password: ...` in place of where the secret should have been.

**Comment by tdemin** [comment]
Relevant versions:

* gopass: v1.10.1
* chezmoi: v1.8.7

**Comment by twpayne** [comment]
Oh whoops. Sorry about that and thanks for reporting. I'll fix this now.

In the short term you can use the `trimPrefix` function to remove the `Password: ` prefix, e.g.

    {{ gopass "something" | trimPrefix "Password: " }}

**Comment by twpayne** [comment]
I'm unable to duplicate this with either gopass 1.10.1 or the latest version of gopass built from `master`:

```
❯ gopass version
gopass 1.10.1 go1.15 darwin amd64
<root>     - gpg 2.2.23 - git 2.29.2
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
❯ gopass show test | cat
testpassword%
```
```
❯ pwd
/Users/twp/src/github.com/gopasspw/gopass
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
❯ go run . version
gopass 1.10.1-git+HEAD go1.15.3 darwin amd64
<root>     - gpg 2.2.23 - git 2.29.2
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
❯ go run . show test | cat
testpassword%                                                                                                                                                                          
```

Note the use of `| cat` prevents gopass's stdout being a TTY and so prevents gopass's automatic coloring of the output. chezmoi invokes gopass with gopass's stdout connected to a pipe (not a TTY).

There's also no mention of the `Password: ` prefix in the [gopass documentation](https://github.com/gopasspw/gopass/blob/master/docs/features.md#show-a-secret) and I don't see it in [the source of `gopass show`](https://github.com/gopasspw/gopass/blob/master/internal/action/show.go#L129-159) either.

Are you sure that `Password: ` is coming from gopass?

**Comment by tdemin** [comment]
@twpayne it is definitely coming from gopass, but it looks like gopass inserts the `Password: ` at insertion time. :thinking: This is happening on the Arch Linux build of gopass, but [it doesn't seem](https://github.com/archlinux/svntogit-community/blob/packages/gopass/trunk/PKGBUILD) to tinker with anything aside from a minor patch that fixes the version flag.

```
~ > gopass insert test1
Enter password for test1:
Retype password for test1:
Warning: Password is too short
~ > gopass show test1
Password: test

~ > gopass show test1 | cat
Password: test

~ > gopass version
gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64
<root>     - gpg 2.2.23 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
~ > pass test1
GOPASS-SECRET-1.0
Password: test

```

![image](https://user-images.githubusercontent.com/26599554/97785228-8e9b9400-1bc5-11eb-9e57-fca89b087163.png)

**Comment by twpayne** [comment]
Interesting! For what it's worth I don't see this behavior on `darwin/amd64` but I *do* see this when running `gopass` at `master` (commit 333a76a06b730c6ebb457fa2adb556a9b857834a) on Ubuntu 20.04 on `linux/amd64`:

```
❯ pwd
/home/twp/src/github.com/gopasspw/gopass
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
❯ go run . insert test
Enter password for test:
Retype password for test:
Warning: Password is too common / from a dictionary
Warning: git has no remote. Ignoring auto-push option
Run: gopass git remote add origin ...
❯ go run . show test
Password: password
```

So, it looks like this is a bug in gopass. Would you care to [open an issue there](https://github.com/gopasspw/gopass/issues/new/choose)?

**Comment by AnomalRoil** [comment]
This is caused by the new "Mime" format that Gopass added recently.
We want to support richer functionalities, and this requires having a "common" format to store our secrets.

We mistakenly enabled the feature for every one upon update, which is causing a lot of issues like that.

That being said the recommended way to get "just" the password is to use the `-o` flag along with `gopass show`:
`gopass show -o test` will ALWAYS return just the password, no matter what format the secret is using.

Otherwise doing a call by "key" allows one to get the password or the username easily.
Here is the expected behaviour of gopass:
``` 
$ gopass show test password
s3cret
$ gopass show test user
myname
$ gopass show -o test
s3cret
$ gopass show -f test
Password: s3cret
User: myname
```

Otherwise you can also disable the new mime format by setting `gopass config mime false`, but this will not impact new secrets that were created or edited after having enabled the said option, and thus can cause issues if you've been using Gopass with the `mime` option set to true since a while.

**Comment by twpayne** [comment]
Thanks @AnomalRoil!

If I understand correctly, the `-o` option was added to gopass in [this commit](https://github.com/gopasspw/gopass/commit/8fa13d84e3656cfc4ee6717f5f485c9e471ad996) almost three years ago, so  it's safe for all versions of gopass since v1.6.1.
