### ISSUE TITLE
Add a flag to keep going even if there is an error on apply

### ISSUE THREAD

**Issue by contrun** [twpayne/chezmoi#927]
## Is your feature request related to a problem? Please describe.

I have several machines between which I want to share the same dotfiles. But not all machines are equal. Some machines are inherently insecure, so I will not decrypt my secrets on them. Currently I use chezmoi with gpg to encrypt part of my dotfiles. I'd like to see chezmoi have the option to keep going even if there is an error on apply.

## Describe the solution you'd like

Add a flag to keep going even if there is an error on apply.

## Describe alternatives you've considered

In my use case, just a flag to not decrypting encrypted files is enough. But I think keep-going option is better.

**Comment by twpayne** [comment]
Thanks for this great suggestion - I'll target this for v2 (#654).

In the short term you can skip the encrypted files by using `.chezmoiignore`. For example, say `~/.gitcookies` is encrypted, put this in your config file (`~/.config/chezmoi/chezmoi.toml`):

```toml
[data]
  trusted = false # or true on trusted machines
```

And then in `~/.local/share/chezmoi/.chezmoiignore`:

```
{{ if (not .trusted) }}
.gitcookies
{{ end }}
```

This will stop chezmoi from trying to write `~/.gitcookies` on non-trusted machines.

The nice thing about this approach is that it applies to all commands, not just `chezmoi apply`. Other commands that would need a "keep going" option for consistency and correctness are `diff`, `init`, `update`, and `verify`.

Note that #778 is tracking the option to exclude encrypted files which is also targeted for v2.

cc @3v1n0
