### ISSUE TITLE
Comments on .chezmoi.toml.tmpl breaks functionality

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#928]
## Describe the bug

If I add a comment in the `.chezmoi.toml.tmpl` file, variables defined in the top-level do not work properly.

## To reproduce

In this example, I'm setting `sourceDir`.

[![asciicast](https://asciinema.org/a/9tAADWLYhRxQl4KcGmrXWRlFI.svg)](https://asciinema.org/a/9tAADWLYhRxQl4KcGmrXWRlFI)

## Expected behavior

It was expected to work since it's just a comment.

**Comment by zb140** [comment]
You should be able to confirm this by looking at the generated `chezmoi.toml`, but I'm fairly sure that what's happening here is that your `sourceDir` property is actually getting commented out by the whitespace stripping `{{- -}}` markers, which will remove all whitespace including newlines.  For a concrete example, this:
```
# a comment here
{{- $var := "foo" -}}
sourceDir = "{{ $var }}"
```

is actually getting transformed to 
```toml
# a comment here sourceDir = "foo"
```
(Honestly, I've come to the conclusion that trying to use `{{-` and `-}}` to manage whitespace in the output of templates is a losing battle and usually more trouble than it's worth.  Really, the only time I try to do that any more is when the whitespace is actually significant. :smile:)

**Comment by felipecrs** [comment]
That's good to know. My lesson was: do not include `{{-` in the first template statement.

```sh-session
# The following variables are only available within this file

{{ $personalName := "x" -}}
{{- $personalEmail := "x" -}}
```
