### ISSUE TITLE
Default custom data at init

### ISSUE THREAD

**Issue by madmarxofficial** [twpayne/chezmoi#931]
I'm always frustrated when I have to `chezmoi init` on a new device.

I've set in my `.chezmoiignore` a condition that needs a custom parameter : 
```
{{- if (eq .graphical false) }}
.config/sway
{{- end }}
```

`.graphical` is normally defined in `.config\chezmoi\chezmoi.toml` but at that time the file being empty, I've got an error because `.graphical` is not set when I try a command (eg. chezmoi diff, chezmoi apply).

```
$ chezmoi diff
chezmoi: template: C:\Users\---\.local\share\chezmoi\.chezmoiignore:13:11: executing "C:\\Users\\---\\.local\\share\\chezmoi\\.chezmoiignore" at <.graphical>: map has no entry for key "graphical"
```

That would be great if at `chezmoi init` the file `.config\chezmoi\chezmoi.toml` would be initialized with `.local\share\chezmoi\private_dot_config\chezmoi\chezmoi.toml.tmpl` as default value which in my case is like :
```
[data]
  graphical = false
```

For now I have to manually fill `chezmoi.toml` on each machine and it's kinda annoying.

Thanks in advance for your consideration !

Keep up the good work

**Comment by twpayne** [comment]
chezmoi has [a mechanism is generate a config file](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#create-a-config-file-on-a-new-machine-automatically) automatically when you run `chezmoi init`. If I understand the question correctly, this should meet your requirements.

**Comment by madmarxofficial** [comment]
Oh great ! Sorry, should have read the docs a little more.
