### ISSUE TITLE
QUESTION: Best place to put chezmoi executable on a FreeBSD box?

### ISSUE THREAD

**Issue by sydbarrett74** [twpayne/chezmoi#933]
I have FreeBSD 12.2, and when I unzipped the tar.gz, it installed to my home directory. I know that Chezmoi by default doesn't manage dotfiles outside of $HOME, but instead of having the chezmoi executable in $HOME, could it be in $HOME/bin? Or /usr/local/bin? I'm just trying to be consistent with where I place my executable files.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.

**Comment by zb140** [comment]
Yes, you can put the executable pretty much wherever you prefer.  It does not need to be in `$HOME`.  For example, on systems where I manually install, I put it in `$HOME/.local/bin`, but it would work just fine in `/usr/local/bin`, too.

**Comment by sydbarrett74** [comment]
@zb140 Thank you! I'll go ahead and close this issue.
