### ISSUE TITLE
 unknown userid

### ISSUE THREAD

**Issue by KyQiao** [twpayne/chezmoi#953]
## What exactly are you trying to do?

I’m running chezmoi(via one-line binary install) on a HPC machine. 

When I try to apply a configuration, it gives:

```
kqiao@login-1:~$ chezmoi apply --verbose
chezmoi: user: unknown userid 1450
```

## What have you tried so far?

Read the reference and check the issues. 

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [ ] Other, please give details.

## Output of `chezmoi doctor`

```
$ chezmoi doctor
     ok: version 1.8.9, commit 4fd06fa089912eb833bc6dc33fd50c0129a0e6ae, built at 2020-11-20T03:48:19Z, built by goreleaser
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/kqiao/.local/share/chezmoi (source directory, perm 700)
     ok: /home/kqiao (destination directory, perm 700)
warning: /home/kqiao/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /bin/bash (shell)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 1.8.3)
     ok: /usr/bin/gpg (GnuPG, version 2.0.22)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Thanks again @KyQiao for the clear report. Two key phrases in your description ("one-line binary install" and "HPC") were critical - thank you for including this detail.

The comment in the new code in #954 explains the underlying problem. In this particular case chezmoi's one-line binary install installs the musl-linked binary which is not aware of the NIS/LDAP password database used on the HPC cluster.

The immediate quick fix for you is to use a glibc-linked chezmoi binary on the HPC system. All of the chezmoi binaries in the released .rpm and .deb packages are linked with glibc.

The long term fix for this is that chezmoi's one-line installer should detect whether the system uses glibc or musl and install the correct binary. I'll open an issue for this.

Thanks again - reporting your experience here is really helpful!

**Comment by KyQiao** [comment]
Hi @twpayne. I tried the quick fix and now it works fine. Thanks a lot for the help.
