### ISSUE TITLE
chezmoi doesn't seem to recognize fish environment variables

### ISSUE THREAD

**Issue by praetorxyn** [twpayne/chezmoi#956]
I've been playing with chezmoi in a snapshotted VM, that way if I screw something up I can just restore.

When I run `chezmoi edit <file>` using fish, it falls back to using basic vi.
The documentation says it's supposed to use $VISUAL, and if it can't find that, $EDITOR, and if it can't find that, vi. This would seem to indicate to me that it isn't recognizing those environment variables using fish.

So if I run `echo $EDITOR` I get nvim, but chezmoi edit falls back to vi (which I don't even have installed, because with neovim why would I?)

If I run `EDITOR=nvim chezmoi edit <file>` it works as expected.

If I switch to bash, things work as expected. This leads me to believe it's not picking up EDITOR and VISUAL because I'm using fish. I'm assuming I'm just doing something wrong, but after tinkering with it for 20 minutes I couldn't make it work.

**Comment by twpayne** [comment]
chezmoi tries to find your editor using this code: https://github.com/twpayne/chezmoi/blob/master/cmd/config.go#L406-L416

What's the output of `set | grep EDITOR`?

Environment variables are a fairly standard thing these days, they're a function of UNIX not the shell. Fish might do things differently of course.

**Comment by praetorxyn** [comment]
> chezmoi tries to find your editor using this code: https://github.com/twpayne/chezmoi/blob/master/cmd/config.go#L406-L416
> 
> What's the output of `set | grep EDITOR`?
> 
> Environment variables are a fairly standard thing these days, they're a function of UNIX not the shell. Fish might do things differently of course.

The output of `set | grep EDITOR` is:
EDITOR nvim
The output of `set | grep VISUAL` is:
VISUAL kate

as kate was installed already, and I haven't taken the trouble of setting up anything else.

I am new to fish as well, but giving it a shot because it's the only shell that supports the XDG Base Directory Specification, and I hate dotfile clutter in my home (which is one of the reasons I want to use a dotfile manager in the first place).

In ~/.config/fish/config.fish, those variables are set using:
```
set EDITOR "nvim"
set VISUAL "kate"
```

I thought maybe fish needed some extra flag to make it pass along to programs or something, but other than that, that's all I can think of.

I have never used Go before, but that function matches how I'd have expected it to be implemented. I'm guessing it's something simple and stupid that will appear obvious in hindsight,  that's normally the way my luck runs.

**Comment by twpayne** [comment]
You might need:

```fish
set -gx EDITOR nvim
set -gx VISUAL kate
```

This is from reading the [fish FAQ](https://fishshell.com/docs/current/faq.html) entry on ["Why doesn't `set -Ux` (exported universal variables) seem to work?"](https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work).

**Comment by praetorxyn** [comment]
> You might need:
> 
> ```fish
> set -gx EDITOR nvim
> set -gx VISUAL kate
> ```
> 
> This is from reading the [fish FAQ](https://fishshell.com/docs/current/faq.html) entry on ["Why doesn't `set -Ux` (exported universal variables) seem to work?"](https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work).

Just adding -x by itself seems to have fixed the issue. Sorry for the trouble, I figured it was something stupid. I installed Garuda KDE Dr4g0nized, which has fish as the default shell and seemed to be setup pretty well, it just didn't have "-x" on those set commands.
