### ISSUE TITLE
Symlinks not portable between OSes

### ISSUE THREAD

**Issue by zb140** [twpayne/chezmoi#959]
## Is your feature request related to a problem? Please describe.

I was setting up Neovim today and I wanted to symlink my `~/.config/nvim/init.vim` to my existing `~/.vimrc`, both of which I have in the same locations on Windows and Linux.  I created and added the symlink on Windows, which stored `..\..\.vimrc` in `symlink_init.vim`.  When I did a `chezmoi update` on Linux, it dutifully created a symlink to `..\..\.vimrc` which is technically a valid filename, but doesn't refer to the file I'd like it to refer to :smile:

So I thought, "no problem, nearly all Windows APIs can handle `/`-separated paths", and I changed `symlink_init.vim` to `../../.vimrc`.  Well, I'll give you one guess which Windows API _can't_ handle `/`...

## Describe the solution you'd like

I propose that `symlink_` files should always be created with `/`-separated paths.  Then, when `chezmoi` reads the link target from the file, it should convert the path to the host-local representation before creating the link.  For backwards compatibility, it should probably do that conversion with something like `filepath.FromSlash(filepath.ToSlash(...))` so it can handle any `symlink_` files that already exist with `\` in them.

## Describe alternatives you've considered

I suppose I could do something clever with templates (side note: can `symlink_` files be templates? I don't think I've ever tried that).  But this feels like an opportunity to make something Just Work the way (I think) most people would expect.

## Additional context

This is the part where I usually say "I made a prototype over here", but I didn't have time to get to it today.  If you think I'm on the right track, I should be able to get to it in the next day or two.

**Comment by twpayne** [comment]
`symlink_` files can indeed be templates and there's a [`joinPath`](https://www.chezmoi.io/docs/reference/#joinpath-elements) template function that uses the platform-specific path separator, so you should be able to create `dot_config/nvim/symlink_init.vim.tmpl` containing

    {{- joinPath ".." ".." "vimrc" -}}

The idea of passing processing all symlinks with `filepath.FromSlash` is an interesting one. I don't think the inner `filepath.ToSlash` is needed - any backslashes will be passed through unchanged. The only case where I think that it might cause problems is where you have the same filesystem shared by both Linux and Windows, e.g. inside WSL2, but I have't investigated what actually happens. Are there any cases where using `filepath.FromSlash` on symlinks might cause problems?

**Comment by zb140** [comment]
Excellent, I'll use the template to get unstuck for now.

As long as we always create `symlink_` files containing `/`-separated paths, you're right that the `ToSlash` isn't necessary.  My reasoning for including it was to try to "fix" any pre-existing symlinks that were created on Windows so they'd start working on Linux.  But on second thought, it's not that hard to remove and re-add them, so maybe that's not a concern.  Plus, since `\` is a valid-but-silly character in a Linux filename, there's a (IMO small) risk of actually _breaking_ some links by using `ToSlash`.

I haven't upgraded to WSL2 yet, but WSL1 seems to behave like "real" Linux as long as you're staying within the WSL environment.  Visiting `\\wsl$\<distro>` from the Windows side does show some weirdness`[1]` around symlinks but the same is true whether or not `chezmoi` is involved, so I think that's ok.

I think using `filepath.FromSlash` should be safe.  It's already a no-op on platforms that use `/`, so they shouldn't see any difference in behavior.  On Windows, `/` is a reserved character in filenames, so there isn't any risk of accidentally converting a `/` that shouldn't be converted.

My overarching goal here is to make it so that I can create a symlink and `chezmoi add` it on either platform and then automatically have the link created (and pointing to the right file) when I pull those changes to the other platform.  I'm very open to other possible solutions, I'd just like it to be as hassle-free as possible :smile:

`[1]` "weirdness" in this case means that from the Windows side you can see that the file exists but you can't see its contents and you can't modify it at all.  I haven't tried deleting it.

**Comment by zb140** [comment]
I put together something super-simple over here: https://github.com/zb140/chezmoi/tree/959-portable-symlinks

It seems to work so far but I haven't played with it much.  I've been busier than normal lately but I should be able to find some time to exercise it soon.
