### ISSUE TITLE
Update sprig to v3.2.0

### ISSUE THREAD

**Issue by Coksnuss** [twpayne/chezmoi#961]
5 days ago sprig v3.2.0 was released:
https://github.com/Masterminds/sprig/releases

It comes with a really helpful function "dig" to traverse a nested set of dicts and allows providing a default value in case a nested key does not exist. It would be really helpful for my setup to have this function and I wonder if chezmoi could update this dependency to its latest minor version.

Thanks.

**Comment by twpayne** [comment]
I've also tagged version 1.8.10 which includes this change. The release pipeline will take ~15 minutes to run.

**Comment by Coksnuss** [comment]
Wow that was quick. Thanks a ton!
