### ISSUE TITLE
Template conditions with osRelease.name error on macOS

### ISSUE THREAD

**Issue by davidkna** [twpayne/chezmoi#969]
## What exactly are you trying to do?

Since #532 was merged `osRelease` is only set on linux. My dotfiles uses `osRelease` in a few place to handle different linux distros.

I want to use my dotfiles on macOS too, but e.g. `{{- if eq .chezmoi.osRelease.name "Fedora" }}` causes an error on macOS now.

How do I write a condition for that checks the distro name, keeping support for macOS?

## What have you tried so far?

- `{{- if and (eq .chezmoi.os "linux" ) (eq .chezmoi.osRelease.name "Fedora") }}` does not work (I hoped it would cancel the second condition out but it doesn't)
- `{{-if eq (get .chezmoi "osRelease.name") "Fedora" }}` does not work (`get .chezmoi "osRelease"` works but it only goes one level deep)

Describe what you have tried so far.

## Where else have you checked for solutions?

* [x] I have read [chezmoi's how-to guide](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md), and not found the answer.
* [x] I have read [chezmoi's FAQ](https://github.com/twpayne/chezmoi/blob/master/docs/FAQ.md), and not found the answer.
* [x] I have searched [chezmoi's reference guide](https://github.com/twpayne/chezmoi/blob/master/docs/REFERENCE.md), and not found the answer.
* [x] Other, please give details.
text/template and sprig docs.

## Output of any commands you've tried with `--verbose`

```
$ chezmoi execute-template --verbose '{{and (eq .chezmoi.os "linux" ) (eq .chezmoi.osRelease.name "Fedora")}}'
chezmoi: template: arg1:1:44: executing "arg1" at <.chezmoi.osRelease.name>: map has no entry for key "osRelease"
```

## Output of `chezmoi doctor`

```
$ chezmoi doctor
```

**Comment by twpayne** [comment]
Thank you for the well-asked question :)

chezmoi is by default strict about template errors, and the `text/template` library it uses is quite eager in its evaluation of arguments, which means it can be tricky to avoid missing keys.

One solution is to use nested `if`s instead of doing everything in a single `and`, i.e.:

```
{{ if eq .chezmoi.os "linux" }}
{{   if eq .chezmoi.osRelease.id "fedora" }}
# fedora-specific config
{{  end }}
{{ end }}
```

**Comment by davidkna** [comment]
Thanks. That works for me.
