### ISSUE TITLE
Chezmoi terminate the parent shell on SIGINT under `chezmoi cd`

### ISSUE THREAD

**Issue by tuxiqae** [twpayne/chezmoi#973]
## Describe the bug
When `Ctrl+C` is pressed under `chezmoi cd` - it crashes and kills its' parent process - thus killing the SSH/shell you were in.

## To reproduce
- Install the latest version of Chezmoi
- Run `$ chezmoi cd`
- Press `Ctrl+C` and then `Enter` **twice** - you will see the parent shell close with your history.

## Expected behavior
I would expect a `Ctrl+C` to do either of the two:
- Let the shell deal with it - I use `Ctrl+C` a lot when I have a typo for example.
- Terminate Chezmoi's sub-shell and go back to the parent.

## Output of command with `--verbose`
`⏎` == Ctrl+C

**Red**: SSH Client
**Green**: SSH Server
![image](https://user-images.githubusercontent.com/39622904/103108013-66bc3000-464c-11eb-9c71-314184959b50.png)

## Output of `chezmoi doctor`

```
warning: version 1.8.10
     ok: runtime.GOOS linux, runtime.GOARCH amd64
     ok: /home/user/.local/share/chezmoi (source directory, perm 700)
     ok: /home/user (destination directory, perm 700)
warning: /home/user/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/fish (shell)
  ERROR: vi (editor, not found)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.29.2)
     ok: /usr/bin/gpg (GnuPG, version 2.2.25)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: gopass (gopass CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)

```

## Additional context
I have tested the issue only on 1.8.10, on two computers, both up-to-date Arch installations.
It happens both in Fish and in Bash.

Feel free to contact me for more information

**Comment by twpayne** [comment]
This behavior seems specific to the fish shell. bash and zsh swallow the Ctrl+C (SIGINT). You can test other shells by running:

```
SHELL=/bin/bash chezmoi cd
SHELL=/usr/bin/zsh chezmoi cd
```

etc.

As far as I can tell, fish [tries to be clever in its handling of SIGINT](https://github.com/fish-shell/fish-shell/search?q=SIGINT&type=issues) and it looks like fish's heuristics behave differently to what you want here. I don't think this is a bug in chezmoi. Please re-open if you disagree.
