### ISSUE TITLE
Check for executable in $PATH from templates

### ISSUE THREAD

**Issue by halostatue** [twpayne/chezmoi#991]
## Problem

I have some templates that I’m converting from a homegrown system to chezmoi that are going to be difficult/ugly to implement because I don’t see a way in the documentation to put a conditional in templates if an executable can be found in $PATH. This would be equivalent to the following bash command: `which ksdiff > /dev/null 2>/dev/null`.

## Feature

Ideally, I’d be able to do something like this in my `private_gitconfig.tmpl`:

```
{{- if commandInPath "ksdiff" -}}
[difftool "Kaleidoscope"]
  cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"

[mergetool "Kaleidoscope"]
  cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" --snapshot \"$REMOTE\" --snapshot
  trustExitCode = true
{{- end }}
```

## Alternatives

At every point where I need to do this, I _might_ be able to do something like (this is rough and probably has bugs):

```
{{- $paths := env "PATH" | split ":" -}}
{{- $found := false -}}
{{- range $paths -}}{{- if and (not $found) (stat (joinPath . "ksdiff")) -}}{{- $found := true -}}{{- end -}}{{- end -}}
{{- if $found -}}
[difftool "Kaleidoscope"]
  cmd = ksdiff --partial-changeset --relative-path \"$MERGED\" -- \"$LOCAL\" \"$REMOTE\"

[mergetool "Kaleidoscope"]
  cmd = ksdiff --merge --output \"$MERGED\" --base \"$BASE\" -- \"$LOCAL\" --snapshot \"$REMOTE\" --snapshot
  trustExitCode = true
{{- end }}
```

…I think. In my homegrown code (using Ruby), this is written as:

```
% on in_path?('ksdiff') do
…
% end
```

If there’s an alternative way to do this, I haven’t seen one in the Chezmoi docs or any issues.

**Comment by zb140** [comment]
There's a helper function called `lookPath` that should pretty much be a drop-in replacement for `commandInPath` in your first example.  Here's a link to it in the docs: https://www.chezmoi.io/docs/reference/#lookpath-file

There's a whole bunch of other helpers you can read about there, plus you can use all the functions from the sprig library.  There's a link to those in the "Template functions" section here: https://www.chezmoi.io/docs/reference/#template-functions

**Comment by halostatue** [comment]
That does look to be exactly what I’m looking for. I swear that I looked over the entire documentation last night. Thank you.
