### ISSUE TITLE
umask docs incorrect

### ISSUE THREAD

**Issue by sersorrel** [twpayne/chezmoi#994]
#779 mistakenly "corrected" the FAQ example for setting the umask in the config (originally added in #695): https://github.com/twpayne/chezmoi/pull/779/files#diff-0bb42a85d04c8b7c9b659307979fd43e8f6e084283a300bfff959adfcbddfd17L146-R146

The correct syntax is `umask = 0o22`, not `umask = 0022`.

**Comment by twpayne** [comment]
Thank you very much! Fixed in #998.
